### ISSUE TITLE
Change .net Client api to use longs instead of int for position

### ISSUE THREAD

**Issue by kstrauss** [EventStore/EventStore#1016]
We have a problem where the stream is larger than a max int. The client api (EventStoreStreamCatchUpSubscription ) uses int.
https://github.com/EventStore/EventStore/blob/2772c1c2d8d229b552ede402350cab8b0ac4b639/src/EventStore.ClientAPI/IEventStoreConnection.cs#L289 

What about using a long ?

**Comment by gregoryyoung** [comment]
This is not just about client API the version is 32 bits everywhere

Better question: why do you have a stream with > 2b events in it? Why not rotate streams etc?
