### ISSUE TITLE
Replica Status: negative total bytes sent

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#1034]
I noticed this today under cluster status

![replica_status_odd_total_sent](https://cloud.githubusercontent.com/assets/153607/18137620/fba77788-6fa0-11e6-8acc-dbf7dd06cd7f.png)

Is this because of int vs. long in UI?

**Comment by gregoryyoung** [comment]
This looks like the UI is converting it to a 32 bit int :)

**Comment by ahjohannessen** [comment]
👯  :)
