### ISSUE TITLE
Set environment variables

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStore#1038]
As previously reported I get OutOfMemory exceptions fairly commonly if I have a client that gets all events from an EventStore using the HTTP API. The suggestion in that issue was to set MONO_GC_PARAMS environment variable. However, the commonly suggested way to do that is to edit the startup script, and the eventstored service (I install EventStore through apt-get) appears to be a binary file.

I would like for the service to execute a named file that can set environment variables like this prior to startup, so that I can tune the VM and GC, to avoid OOMs in the future. Thanks!!

**Comment by gregoryyoung** [comment]
which package are you using, the event store packages usually are set up through systemd init.d etc.

**Comment by rickardoberg** [comment]
I'm using this one:
'https://packagecloud.io/EventStore/EventStore-OSS/ubuntu/ trusty main"

Is there documentation anywhere on how to change environment variables using what you mentioned?

**Comment by pgermishuys** [comment]
@rickardoberg you can find the upstart script in `/etc/init/eventstore.conf` You will see that it calls `exec /usr/bin/eventstored`. You can make adjustments to this if need be.

**Comment by rickardoberg** [comment]
Thanks!

**Comment by pgermishuys** [comment]
Hi @rickardoberg. Going to close this issue, please feel free to reopen if you require any further help related to it.
