### ISSUE TITLE
Codedoc wrong

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#1053]
https://github.com/EventStore/EventStore/blob/oss-v3.9.1/src/EventStore.ClientAPI/IEventStoreConnection.cs#L501-L502

Says it returns a value, but it doesn't.

**Comment by pgermishuys** [comment]
Thanks for reporting this @haf will update the docs.

**Comment by jasonmitchell** [comment]
There seems to be a little inconsistency in the <returns> comments in this file.  I don't mind going through and making them consistent.

Is there any preference on the format?  E.g. 

When no generic argument in the `Task` specify:
`/// <returns>A <see cref="Task"/> that can be waited upon.</returns>`

When there is a generic argument have a message such as:
`/// <returns>A <see cref="Task&lt;EventReadResult&gt;"/> containing the results of the read operation</returns>`

**Comment by pgermishuys** [comment]
@jasonmitchell that seems reasonable to me and it would be very kind of you to pick this one up. Thank you.
