### ISSUE TITLE
Unclear documentation on EventStoreAllCatchUpSubscription.Stop(TimeSpan timeout)

### ISSUE THREAD

**Issue by jpierson** [EventStore/EventStore#1054]
I've noticed that the parameterless `Stop()` method on `EventStoreAllCatchUpSubscription` mentions that it is non-blocking but the one that takes a timeout value doesn't explicitly say that is is blocking for that timeout period. Specifically this is what the code comment has to say.

Current:

> The amount of time within which the subscription should stop.

Is it safe to assume that it is blocking? It appears based on the fact that a `TimeoutException` can be thrown that it is. If so wording the comment for the _timeout_ parameter or the summary of the _Stop_ method itself could state this more clearly such as.

Suggested:

> The maximum amount of time which the current thread will block waiting for the subscription to stop before throwing a TimeoutException.

**Comment by gregoryyoung** [comment]
A PR probably would have been less work? :)

:+1: on the doc change
