### ISSUE TITLE
Checking EventStore connection

### ISSUE THREAD

**Issue by kalyanrajsista** [EventStore/EventStore#1064]
There should be a property/method available on the ES connection that lets me see it's current state. Is it active?  Has it been closed?  Is there any simple check that would fix it.

**Comment by gregoryyoung** [comment]
There are events for such things 

https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.ClientAPI/IEventStoreConnection.cs#L571

https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.ClientAPI/IEventStoreConnection.cs#L589

**Comment by Narvalex** [comment]
I think that what @kalyanrajsista asked is a simple property or method to get the current state of the connection instead of handling events ourselves to keep the current state of the connection (event sourcing with connection events?)
