### ISSUE TITLE
projections partitions queries give an empty result

### ISSUE THREAD

**Issue by rm2k** [EventStore/EventStore#1065]
Following along with [Ashton](http://codeofrob.com/entries/re-partitioning-streams-in-the-event-store-for-better-projections.html) projections guide, but a query to  `.../?partition=...` just return a blank page.

**Comment by pgermishuys** [comment]
Would you mind reading through an example of a very similar query raised awhile ago that explained how partitions and querying their results work? The example is in the following issue. https://github.com/EventStore/EventStore/issues/699

**Comment by rm2k** [comment]
I see. That solves my problem. I'm also for @robashton's examples should be updated. Wasted a lot of time trying to figure out what I was doing wrong.

**Comment by pgermishuys** [comment]
Those posts were written quite a long time ago and should be correct as at the time they were written. When projections are released for production use, they will be accompanied with documentation.

**Comment by rm2k** [comment]
On projections again, but now on clientAPI.

Seeing that ProjectionsManger requires EventStore.ClientAPI.ILogger and operationTimeout. Are they currently being used? Or am I missing a point or two?
