### ISSUE TITLE
Still waiting for chaser to catch up already for . ...

### ISSUE THREAD

**Issue by xenoputtss** [EventStore/EventStore#1072]
I'm running windows version 3.9.1.0 and am running into the this issue where EventStore never seems to finish catching up from a restart.

The event store has 550GB of data in roughly 100 streams (it's performing mainly as an audit log for table changes from a legacy SQL Database).  I loaded the data previously, had to shutdown the server for some updates, and then started everything back up.  Ran into issues with it taking 2 days to start so I took it down, deleted the indexes and logs and restarted.  This is the current state it is in after 3 days of it running.

[logs.zip](https://github.com/EventStore/EventStore/files/519583/logs.zip)

```
[PID:02452:017 2016.10.10 09:51:31.284 TRACE InMemoryBus         ] SLOW BUS MSG [MainBus]: EventCommitted - 62ms. Handler: WideningHandler`2.
[PID:02452:017 2016.10.10 09:51:31.284 TRACE QueuedHandlerMRES   ] SLOW QUEUE MSG [MainQueue]: EventCommitted - 62ms. Q: 43348/44042.
[PID:02452:015 2016.10.10 09:51:34.581 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:40:30.1850153...
[PID:02452:015 2016.10.10 09:51:34.784 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:40:30.3879748...
[PID:02452:015 2016.10.10 09:51:34.987 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:40:30.5909336...
[PID:02452:015 2016.10.10 09:51:35.190 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:40:30.7940148...
[PID:02452:015 2016.10.10 09:51:35.393 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:40:30.9969725...
[PID:02452:015 2016.10.10 09:52:04.456 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:41:00.0511684...
[PID:02452:015 2016.10.10 09:52:04.659 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:41:00.2540415...
[PID:02452:015 2016.10.10 09:52:04.862 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:41:00.4570321...
[PID:02452:015 2016.10.10 09:52:05.065 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:41:00.6601063...
[PID:02452:015 2016.10.10 09:52:05.284 DEBUG StorageWriterService] Still waiting for chaser to catch up already for 14:41:00.8679941...
[PID:02452:017 2016.10.10 09:52:26.144 TRACE InMemoryBus         ] SLOW BUS MSG [MainBus]: EventCommitted - 62ms. Handler: WideningHandler`2.
[PID:02452:017 2016.10.10 09:52:26.144 TRACE QueuedHandlerMRES   ] SLOW QUEUE MSG [MainQueue]: EventCommitted - 62ms. Q: 72148/78734.

```

**Comment by gregoryyoung** [comment]
It looks like you have a full index rebuild going:

[PID:02452:043 2016.10.10 13:30:22.093 TRACE PTable              ] PTables merge finished in 00:35:21.5748974 ([138240000, 138240000] entries merged into 276480000).
[PID:02452:043 2016.10.10 13:30:22.093 TRACE PTable              ] Loading and Verification of PTable '21327fa6-26e8-469f-a7bc-7dacd30fb968' started...
[PID:02452:018 2016.10.10 13:30:27.857 TRACE TableIndex          ] Switching MemTable, currently: 34 awaiting tables.

So there are +- 34m index records left to go to disk (looks like about 600m) total were there.

**Comment by xenoputtss** [comment]
Ok, if it is still working I'm fine with that.

How were you able to figure out

> So there are +- 34m index records left to go to disk (looks like about 600m) total were there.

from the logs?  the `PTables merge finished in` don't seem to contain that information (the numbers are not always increasing.

**Comment by gregoryyoung** [comment]
See the "awaiting memtables" part.

**Comment by xenoputtss** [comment]
in my logs locally, that message seems to be increasing in value.
`[PID:02452:018 2016.10.10 14:20:05.322 TRACE TableIndex          ] Switching MemTable, currently: 48 awaiting tables.`

Where did you find the ~600m total message?  Was it from this
'[PID:02452:018 2016.10.09 19:06:16.565 DEBUG IndexCommitter      ] ReadIndex rebuilding done: total processed 608309753 records, time elapsed: 2.05:34:37.2143937.
'
?
