### ISSUE TITLE
Support X-Forwarded-Prefix

### ISSUE THREAD

**Issue by fchaillou** [EventStore/EventStore#1074]
Hello,

I created https://github.com/EventStore/EventStore.UI/issues/132 but actually the issues seems to be more on the core project so here it is. I can delete my other issue if needed.

We are reaching the eventstore ui or doing queries through and nginx reverse proxy with an url prefix in the reverse proxy.

Right now, eventstore always return incorrect url to the client when doing requests through nginx.
Adding support for X-Forwarded-Prefix (along X-Forwarded-Host that is already there) would fix the issue.

Here is a stackoverflow example of the same issue (on a spring service but the issue is exactly the same) : http://stackoverflow.com/questions/36731055/nginx-reverse-proxy-spring-resourcesupport-produces-wrong-url-path-prefix

Thanks for your help !

**Comment by gregoryyoung** [comment]
https://github.com/EventStore/EventStore/blob/08c2bdf7dcadd154cffa549d273e3a8e4673c5a1/src/EventStore.Transport.Http/ProxyHeaders.cs#L6 we have proto defined

**Comment by fchaillou** [comment]
If i get this correctly, X-Forwarded-Proto is for the protocol (ie : http or https), what i want here is to be able to correct url when you access eventstore behind a reverse proxy that adds a prefix in your path :
- In your private network you can join eventstore on http://IPX:2113
- On the internet, your eventstore is available on http://yourdomain/eventstore

**Comment by gregoryyoung** [comment]
see the other X-headers they are already supported eg Forward-Host Forward-Port (set them to what you want it to reply as)

**Comment by fchaillou** [comment]
None of the headers you support do what i want, the issue still exists, can you reopen it ?

**Comment by gregoryyoung** [comment]
Ah so not the whole host just a prefix. its +- 15 minutes of work. expect in 4.0

**Comment by pgermishuys** [comment]
Fixed by #1156
