### ISSUE TITLE
Introduction doc should provide the most recent cURL command first

### ISSUE THREAD

**Issue by drozzy** [EventStore/EventStore#1077]
When reading the intro docs:
http://docs.geteventstore.com/introduction/3.9.0/

the section _Writing Events to an Event Stream_ provides the command for an older version first:

`curl -i -d @event.txt "http://127.0.0.1:2113/streams/newstream" -H "Content-Type:application/json"`

Running this gives an error. The guide later provides the correct command:

`curl -i -d @event.txt "http://127.0.0.1:2113/streams/newstream" -H "Content-Type:application/vnd.eventstore.events+json"`

But when a new user is reading this - they might never get to the second command, as they are stuck debugging the error.

Solution: provide the correct command first (i.e. with "vnd.eventstore.events+json"), and then mention that in _older_ versions (i.e. pre 3.0.0 RC9), one should use the alternative.

Of course, this is an issue caused by docs being for version 3.9.0, while download being for 3.9.2. New user will find this confusing.

Just providing some feedback, as I spent about 20 minutes debugging content types, before I saw the next paragraph mentioning that this was changed in _current_ version.

**Comment by pgermishuys** [comment]
Thanks for reporting this issue @drozzy. Would you be so kind as to open this in the relevant repository over [here](https://github.com/EventStore/docs.geteventstore.com)?

**Comment by drozzy** [comment]
@pgermishuys Will do.
