### ISSUE TITLE
Show connection name (if available) on the dashboard

### ISSUE THREAD

**Issue by ONE75** [EventStore/EventStore#1089]
When connection to GES with the .net client, one has the ability to provide a connection name. It would be really convenient to have this name on the dashboard. 

(another solution would be to expose the connection id that's currently being displayed to the client connection so they can be correlated)

**Comment by gregoryyoung** [comment]
This will require a protocol change to add a message to name the connection. 4.0 seems like a reasonable time to add such a thing.

**Comment by gregoryyoung** [comment]
btw adding just the connection id would be trivial, the name requires pushing it up from the client.

**Comment by ONE75** [comment]
I'm more than happy with the connection id so I know which app has lost connection to GES or created too many connections...

**Comment by gregoryyoung** [comment]
Its already there curl http://127.0.0.1:2113/stats/tcp adding would just be adding to the js.

```
  {
    "remoteEndPoint": "127.0.0.1:52101",
    "localEndPoint": "127.0.0.1:1113",
    "connectionId": "c3bf06bf-3948-45d0-9416-30ea4128e2e3",
    "totalBytesSent": 89667,
    "totalBytesReceived": 25306,
    "pendingSendBytes": 0,
    "pendingReceivedBytes": 0,
    "isExternalConnection": true
  },
  {
    "remoteEndPoint": "127.0.0.1:52114",
    "localEndPoint": "127.0.0.1:1113",
    "connectionId": "338ef7e8-4120-453c-9a28-f726ec3b8de1",
    "totalBytesSent": 84609,
    "totalBytesReceived": 23885,
    "pendingSendBytes": 0,
    "pendingReceivedBytes": 0,
    "isExternalConnection": true
  },
  {
    "remoteEndPoint": "127.0.0.1:52117",
    "localEndPoint": "127.0.0.1:1113",
    "connectionId": "85222a87-6666-4965-89ef-f65bcba59667",
    "totalBytesSent": 83453,
    "totalBytesReceived": 23555,
    "pendingSendBytes": 0,
    "pendingReceivedBytes": 0,
    "isExternalConnection": true
  },
  {
    "remoteEndPoint": "127.0.0.1:52112",
    "localEndPoint": "127.0.0.1:1113",
    "connectionId": "af916abc-deda-4680-b499-1f8c5957e23b",
    "totalBytesSent": 86216,
    "totalBytesReceived": 24293,
    "pendingSendBytes": 0,
    "pendingReceivedBytes": 0,
    "isExternalConnection": true
  }
]
```

**Comment by ONE75** [comment]
I was referring to the connection id on the TcpPackageConnection like shown in the logs

[14,08:11:17.580,DEBUG] TcpPackageConnection: connected to [127.0.0.1:1113, L127.0.0.1:63729, {55154ff2-ea98-4ff7-9d8e-7bba43d18756}].

This doesn't match with the connection id on the UI (or api)

![image](https://cloud.githubusercontent.com/assets/785838/20244454/e23a0664-a982-11e6-9259-902ebde93e6c.png)

**Comment by gregoryyoung** [comment]
L127.0.0.1:63729 is listed under (it represents the local) ip address no? the first part 127.0.0.1 will be the same for all clients.1§21
