### ISSUE TITLE
System.OutOfMemoryException in EventStore.ClientAPI.Transport.Tcp.TcpConnection.StartReceive()

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/EventStore#1090]
On some conditions that we are not sure about, but it seems to be the service is stopping, we get this exception and the service crashes:

> Failed to stop service. System.InvalidOperationException: An unhandled exception was detected ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at EventStore.ClientAPI.Transport.Tcp.TcpConnection.StartReceive()
>    at EventStore.ClientAPI.Transport.Tcp.TcpConnection.ProcessReceive(SocketAsyncEventArgs socketArgs)
>    at EventStore.ClientAPI.Transport.Tcp.TcpConnection.OnReceiveAsyncCompleted(Object sender, SocketAsyncEventArgs e)
>    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
>    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object ignored)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callb...

Verbose logging is enabled but we cannot see it since the batched logger fails to flush events due to the process termination.

**Comment by alexeyzimarev** [comment]
I think it is mine, really just out of memory issue.

**Comment by gregoryyoung** [comment]
I had typed that but got distracted by my son and never hit submit :) There isn't much code there and it looks like a stock OOM https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.ClientAPI/Transport.Tcp/TcpConnection.cs#L209
