### ISSUE TITLE
Possible to delete Events?

### ISSUE THREAD

**Issue by jamescarter-le** [EventStore/EventStore#1091]
I know this is not the intended use for EventStore - but the application fits my needs better than Kafka.

I want to be able to store approx. 100GB of events in a stream, but then delete those older than 30 days.

Is it possible to delete events from a Stream using the clients? I couldn't see any documentation, Issue or operation in the Client to do this.

**Comment by blakeholl** [comment]
Just looking at the code in GitHub - I see a DeleteStreamAsync() https://github.com/EventStore/EventStore/blob/08c2bdf7dcadd154cffa549d273e3a8e4673c5a1/src/EventStore.ClientAPI/IEventStoreConnection.cs#L49

**Comment by jamescarter-le** [comment]
Ah - I've seen StreamMetadata has properties such as

- MaxAge
- MaxCount
- TruncateBefore

This looks like it would do for me, can I change these values on the fly using SetStreamMetadata?

**Comment by gregoryyoung** [comment]
yes you can also just delete streams

**Comment by jamescarter-le** [comment]
Thanks @gregoryyoung 
I want to expose my Stream via Competing Consumers to many clients, so do not want to disturb them by changing the Stream name, so I would like to delete messages from the stream.
If I set TruncateBefore does that delete the messages from the file storage?

**Comment by gregoryyoung** [comment]
That is exactly what it does. You can also jsut set maxAge and it will do this automatically for you. EG maxAge : 30 will always only contain the last 30 seconds of data in the stream.

**Comment by jamescarter-le** [comment]
Superb - thank you @gregoryyoung

**Comment by gregoryyoung** [comment]
Just to add Delete (with hard delete set to false so it will do a softdelete) will just $tb on the metadata.

Also be careful with competing consumers + deletions etc. It can feasibly cause you to miss a message on the stream if the consumer isn't keeping up.
