### ISSUE TITLE
Roadmap for ubuntu?

### ISSUE THREAD

**Issue by hazinstore** [EventStore/EventStore#1095]
Your currently supported linux build is for 14.04 which is at or near EOL at the time of this writing.
We're faced with either not upgrading and losing out on security fixes, or moving to something that will run on a current LTS distro.

Do you have any sort of timeline on moving into the present?
Thanks!

**Comment by jen20** [comment]
Hi @hazinstore! Ubuntu 14.04 is a LTS release, meaning it is supported for 5 years - it is _nowhere near_ "end of life".

However, Ubuntu 16.04 brings vast improvements - notably ZFS support, which is something that works very well with Event Store. We're almost done testing with the stock 16.04 kernel, and there will be appropriate packages with systemd-based init released soon.
