### ISSUE TITLE
Test Client picks up the configuration from the node's default configuration path.

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#1102]
Since the Test Client is using the same `Options` object as the node is, it appears to be picking up some of the options from configuration that is living in the default location.

**Reproduction on Linux**

- `echo "RunProjections: All" > eventstore.conf`
- `mono EventStore.TestClient.exe`

**Fails with**
 
```
Error while parsing options:
The option RunProjections is not a known option
```

**Comment by gregoryyoung** [comment]
Wouldn't the solution to this just to be to specify the config file??

**Comment by pgermishuys** [comment]
Yeah, however if someone were to run into this issue, they wouldn't immediately know that the test client picks up the node's config because you only see the error message and not what the configuration source was.

**Comment by gregoryyoung** [comment]
hmm maybe make the code look for a different filename by default than eventstore.conf (say testclient.conf) so that way they wouldn't clash by default.
