### ISSUE TITLE
Function docs in the new docs?

### ISSUE THREAD

**Issue by drozzy** [EventStore/EventStore#1103]
Where is the documentation for functions like `when` in the new docs?

Here is the old doc:

https://github.com/EventStore/EventStore/wiki/Projections-when

But I can't seem to find an equivalent page in http://docs.geteventstore.com/

**Comment by pgermishuys** [comment]
Hi @drozzy 
They will be part of the projection documentation that is still not published yet. Projections are to be released as part of 4.0.0.

**Comment by drozzy** [comment]
I see. I guess "DOCS HAVE MOVED" is not a very accurate description then. Maybe "Some of the docs have moved" would be better.

Anyways, let's hope this issue helps people with the same question in the future.

**Comment by drozzy** [comment]
Can you publish the documentation before 4.0.0?

Scouring the [blog posts](http://codeofrob.com/entries/creating-a-projection-per-stream-in-the-eventstore.html) and [old wikis](https://github.com/EventStore/EventStore/wiki) is not very comfortable.

**Comment by pgermishuys** [comment]
Yes, this will be done as part of releasing a public RC for 4.0.0.

**Comment by pgermishuys** [comment]
There is now a set of initial [projections documentation](http://docs.geteventstore.com/projections/4.0.0/getting-started/).

I am going to close this issue for now, please feel free to reopen if you require any further questions answered related to this issue.

If the question/issue is related to the projections documentation, please open them [here](https://github.com/EventStore/docs.geteventstore.com).

**Comment by gregoryyoung** [comment]
http://docs.geteventstore.com/projections/4.0.0/user-defined-projections/
