### ISSUE TITLE
Projection processing events more than once

### ISSUE THREAD

**Issue by RyanMelenaNoesis** [EventStore/EventStore#1128]
We're seeing a strange behavior where our projection seems to process individual events more than once.  In our scenario the misbehaving projection is responsible for linking events which results in duplicate events in the destination stream.

We have created a [small example repo](https://github.com/RyanMelenaNoesis/EventStoreProjectionIssue) that will consistently reproduce the issue in our environment.

The first attached image shows the result of running the aforementioned repo code against an empty EventStore instance.  ![eventstoreissue1128](https://cloud.githubusercontent.com/assets/7570707/21279368/80358096-c3a5-11e6-92ae-92694725726f.png) As you can see, the projection lists Events processed as 12 despite the fact that only 10 events have been stored.  As a result, the destination stream contains duplicate events which cause an error in the EventStore web UI (as shown in the second attached image).
![eventstoreissue1128b](https://cloud.githubusercontent.com/assets/7570707/21279491/0a8e88f0-c3a6-11e6-91e8-295186ccad45.png)

Version: EventStore 3.9.3
Host: Ubuntu 14.04.5 LTS (single server, no cluster)

_It appears this same behavior was reported a little over a year ago [here](https://groups.google.com/d/msg/event-store/VQr_KEUP8wQ/OsMZuQmgCQAJ)._

**Comment by volak** [comment]
I working on an example repo for this issue a few days ago - but you beat me too it!  I see the same issue.

I've been compete consuming from a projection just like this and getting multiple same events occasionally.  Good to finally know its the projection and not competing consumers - I've been thinking it was due to bucket assignments.
