### ISSUE TITLE
Public constructor for StreamEventsSlice

### ISSUE THREAD

**Issue by dasjestyr** [EventStore/EventStore#1130]
I was trying to write a test for a facade written around the EventStore client in order to test that my code is correctly iterating over the available slices, but I found that I have no access to construct an instance of the class let alone any of the properties that I need to set in order to set up the test. I thought to subclass it, but again, the only available ctor seems to be internal.

I'd like to request a fix for this. Either a public constructor, factory method, or other solution.

**Comment by gregoryyoung** [comment]
This has been brought up before. Why are you trying to 'unit test' at this level you likely want a single integration test and your own abstraction.

**Comment by dasjestyr** [comment]
It actually is my abstraction. For example, I have a GetEventsAsync method that wraps the call to the EventStore client's ReadStreamForwardAsync method. My method handles the loop loop that is run while IsEndOfStream is false. In order to test that is being executed correctly, I need to be able to set the properties on the slice. So I'm not trying to test the EventStore client so much as I'm trying to test my interaction with the client.

**Comment by gregoryyoung** [comment]
Please see previous threads on this. It is trivial for us to do but you are likely doing the wrong thing.

**Comment by dasjestyr** [comment]
Perhaps, but it still feels right in this scenario. So, I realize that we shouldn't mock data, but I'm more interested in the flag. Would it not be prudent to provide an interface for items like that considering how it is used?

**Comment by gregoryyoung** [comment]
But this is an interface on data. This has been discussed many times (I won't go through the discussion again). Assuming a .net client you can also just use the embedded client for this and it will send things exactly the way a real node would.

**Comment by gregoryyoung** [comment]
btw if you totally disagree with the answer it is not that hard to work around with reflections.

**Comment by dasjestyr** [comment]
I don't wanna get into the habit of reflecting out internals. But ok, I guess I'll just not put any coverage on this code.

**Comment by gregoryyoung** [comment]
Please read the previous threads before making such comments. There are long and subtle arguments on both sides.

What exactly would you be testing? It being you are making up responses that may or may not actually be possible to be created by us? There are some arguments for making odd error conditions, but why is this the focus of your testing? And certainly coverage is not actually a metric worth striving towards.

**Comment by thefringeninja** [comment]
From what I remember, `EventStoreData` used to be `IEventStoreData` but they got rid of it because people were trying to mock it.

What we've done is write a simple generic `EventStoreClientRepository<T>` that completely encapsulates EventStore - other than passing IEventStoreClient in the constructor. Then the implementation of our domain repos wraps this class.

At this point we only need to verify what happens when we persist an aggregate that has been `new`d up, what happens with one that has been loaded, modified, and saved again, and what to do when a concurrency check fails.

**Comment by dasjestyr** [comment]
I apologize for that and for everything else that I write. I often sound more curt than intended. when I said "But ok, I guess I'll just not put any coverage on this code." I didn't intend for that to sound snarky, although "I won't go through the discussion again" sounded like the door slamming shut in my face. I literally meant "fine, no coverage". I filtered it out of the test suite as to hide the red marks all over my screen telling me that I'm being lazy for not testing this simple routine. Hopefully it doesn't become an issue later.

@gregoryyoung I don't expect any more discussion from you since you've made it clear that you don't want to have it. I'm not offended. The issue is closed and I'm just rambling now in case any one else has anything else to add...

To answer the question: the objective is to test anything _we_ write. Pretty simple really, and I've never understood any argument against the _desire_ to do so. While I don't think 100% coverage should be the goal in every case, I do kind of feel that if you can get 100% coverage without having to turn the project upside down, then you should at least make the effort. When the classes are simple, it's usually not that hard. More often than not, when I'm told to stop trying to test/mock the thing, there's usually another way to get the same coverage without creating a ridiculous interface (see: fake HttpMessageHandler instead of trying to mock HttpClient, fools). But in this case, it seems my only option is to simply ignore it. Tough pill to swallow, but I'll survive.

@thefringeninja what you described is pretty much what I wrote, but I had an additional separation. My event store repo actually takes an instance of my adapter which is essentially a wrapper for the event store client. The logic behind separating the two is really that the adapter is the communication abstraction and the repo is the access abstraction. The store could change, but the repository interface likely will not. The repository is 100% covered. I wrote in some snapshotting logic and it has some stuff that constructs the stream names and so on. That's all fine. 

The adapter that I wrote which wraps around the event store adapts this wrapper to an interface that I own, IStoreEvents; I could reimplement it as an ADO store, nosql, whatever. That implementation is injected as a dependency to the repository.  You get the idea, standard stuff. The question could be "yeah, but are you going to change that any time soon; what's the point? And the answer would be, with our current roadmap and lack of experience with EventStore, quite possibly, yes. And it's not like it took a lot of effort to separate the two, and now I can test the repo logic without actually talking to EventStore which is the kind of isolation anyone should want imo.

The implementation that I wrote here doesn't do too much fancy, but it handles all of the converting from our Event base class to an instance of EventData in order to get events into the store, and also manages the process of getting them out of the store and back into usable objects -- typical abstration stuff so that devs don't have to mess with it. All of that stuff works like gangbusters, but I'd like to get the coverage on the code that I wrote for sanity sake. It's not like the test is hard to write, I just need to be able to set those values to ensure all the control and decision structures are written correctly. It's not the end of the world that I don't get coverage, but it's kind of annoying the heck out of me that I can't set the condition. And, It's not like I'm testing that EventStore is giving me back correct data, but rather that I want to test that I'm handling it correctly based on the reported state of each slice.

Why did I think to write this test and why do I care? Well because I already nozzed it up once. In some other tests, I totally forgot to loop through the read operation at all. Once I hit a state where there was a second page, none of those events were getting loaded into the domain object and my state was bad. It took a while to realize that I derped it up, but by then, the data was just bad. Developer mistake of course, but that's why I want the test. Who knows what the next guy is going to do when he goes in there looking to "make things better". This particular unit test was trying to assert that all expected events were being pulled from the store. So if the page size was 1000, and there was a 1001 events, I should get 2 pages before the loops exits. To test that, I need to be able to tell the client to return 1000 events on the first call, with the flag set to true, telling me there's more and then 1 event on the second call with the flag set to false saying we're all done. But I can't set that condition; I just have to trust that my handling is correct. I've written simple tests like this tons of times. It doesn't dig into the internals of the client, it's just reacting to the communicated state of each call. It's kind like saying "ok if the http server returns a 500, then do this stuff" -- assuming the reaction is to retry 3 times and then call POTUS, then I need to make sure my http client is returning 500 so that I can assert the condition resulted in an action, and I can do that by faking the message handler. Basic testing, right? GIven the specified conditions, assert that blah blah blah. I mean, what if a read from EventStore failed? I currently don't even know how it'll behave (does it throw an exception? What exception?), but I see there is a status enum in the object that I could probably check. But I can't test that because I can't set the condition. I mean, I learn the details as I encounter the problems, but you get my point, I hope.

The way that I originally saw StreamEventsSlice wasn't that it was data that shouldn't be mocked. I saw it as an envelope that had data as well as some other information used for indexing. In other words, all of the index properties and the flag that says "hey, there's more" is not data in and of itself. That's information I potentially need in order to communicate with the server, so I think being able to test my handling of such a thing isn't a crazy thing to want. And of course, the remaining property, Events, IS data and I have no desire to mock it.

I didn't find any other threads on the google forum. I'd appreciate any relevant links. If not; no big deal. I saw some related to IEventStoreConnection, but I'm not having a problem with that. I was able to mock the interface just fine which I only did to verify that I was calling the correct methods depending given the condition.

**Comment by thefringeninja** [comment]
When I see 'the repository' I tend to get a little worried...

We have found the following to be more than adequate for ensuring our aggregates are persisted properly.

```
[Fact]
public async Task multiple_pages(){
	var ct = CancellationToken.None;

	var sut = new TestRepository(EventStoreConnection.Create(...));

	var id = Guid.NewGuid();

	var aggregate = TestAggregate.Create(id);

	for (var i=0;i<GenericEventStoreRepository<TestAggregate>.PAGE_SIZE+10;i++) {
		aggregate.DoSomething(); // applies one event, the application of which increases Count by 1
	}

	await sut.Save(aggregate, ct);

	aggregate = await sut.GetById(id, ct);

	Assert.Equal(GenericEventStoreRepository<TestAggregate>.PAGE_SIZE+10, aggregate.Count);
}

class TestRepository {
	public TestRepository(IEventStoreConnection connection) {
		_inner = new GenericEventStoreRepository<TestAggregate>(connection); 
	}
}
```

Won't compile of course but you should get the idea. I personally see no need for an additional `IStoreEvents` abstraction, since the implementation of a domain specific repository is usually just a dumb wrapper around the generic one. In our current project, we were originally using GES (but switched to SSS due to on premise operational concerns). Switching out the store took all of 15 minutes, as all we needed to do was change the generic repository implementation + a simple search and replace.

**Comment by dasjestyr** [comment]
@thefringeninja I've been considering recombining them and probably will.

Thanks for the example, it did give me some ideas.
