### ISSUE TITLE
EventStore Core Client in Normal Console app

### ISSUE THREAD

**Issue by Gentlehag** [EventStore/EventStore#1134]
I created a .net standard (1.4) lib in which i write events to event store.

When  I use this lib from a .net core console  application everything works fine.

When I use it from a default windows console application i got this error

System.TypeInitializationException: 'The Typeinitialisor for EventStore.ClientAPI.Transport.Tcp.TcpPackageConnection" raised a exception

**Comment by jageall** [comment]
Thanks for raising this, I will look into it. when you say "default windows console application", do you mean an application targeting the full CLR version > 4.0?

**Comment by Gentlehag** [comment]
sorry for the delay. it was a 4.6.2 console app and the package was made in .net standard 1.4

**Comment by pgermishuys** [comment]
Moved to https://github.com/EventStore/ClientAPI.NetCore/issues/6
