### ISSUE TITLE
QUESTION: Is it possible to partition a projection by any other means than streams?

### ISSUE THREAD

**Issue by PaulGrimshaw** [EventStore/EventStore#1135]
We use the forEachStream() fairly extensively, and find it really useful with the automatic partioning.  However in some cases it would be useful to partition by a different parameter rather than streams, such as  status or similar.  Is it possible to do this?  I would imagine listening to a "category" ($ce-xxx) stream, and somehow creating mulitple state partitions based on criteria found in the events.

**Comment by gregoryyoung** [comment]
Yes you can use statePartitionedBy(function) to provide a custom state partitioning.

**Comment by gregoryyoung** [comment]
It is worth noting that foreachStream is also able to be run in parallel on a historical query where as statePartitionedBy must be run sequentially. foreachStream is basically saying "I have a fold per stream" where as statePartitionedBy is saying "I have one big fold with custom partitioning"

**Comment by PaulGrimshaw** [comment]
This is really useful, thank you.  Is there somewhere where the full projection API is documented?  Or somewhere in the source to look?  There seems to be a lot of useful nuggets in there, but haven't seen a clear overview of what is possible.

**Comment by pgermishuys** [comment]
The projection documentation is underway and will accompany Event Store 4.0.0. If you want to have a look at the API, the best place to start looking is https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.Projections.Core/Prelude/Projections.js

**Comment by PaulGrimshaw** [comment]
Perfect, thanks
