### ISSUE TITLE
Case Against ThreadPool.QueueUserWorkItem

### ISSUE THREAD

**Issue by volak** [EventStore/EventStore#1144]
I'm opening this ticket for discussion on the use of the ThreadPool to deliver messages from the client api to the user.  I hear from slack there have been several discussions already so hopefully this will be brief 📦 

For starters - my position is there should be a config option to tell the client api to spin a new dedicated thread per subscription instead of using the thread pool.  My reasoning is below and for transparency I use ES in my project here: https://github.com/volak/Aggregates.NET where my use case involves a fixed small number of subscriptions to ES with blocking calls while processing events to prevent consumers from overloading themselves.

The current design of event delivery is to commandeer a thread from the pool to deliver all the events in the live queue then release the thread.  This is fine, assuming the user doesn't block the thread himself for IO or processing or w/e. 

One easy example is if we want to support parallel processing events.  Say I want to have 10 events processing at the same time.  My eventAppeared code would look like this:

```
var limit = new SemaphoreSlim(10,10);
eventAppeared: (sub, e) => {
    limit.Wait();

    Task.Run(async () => {
        await ProcessEvent(e);
        limit.Release();
    });
}
```

My client would run 10 events then wait for 1 event to finish before running the 11th.  In effect I am holding 1 thread from the pool hostage - it can't do any work or help any other process.

This is not that big a deal, but each time the client subscribes to another stream another thread is taken from the pool permanently and soon between the client api and the client's code itself the thread pool is starved and no work can get done all because of `limit.Wait()`

Another disadvantage is we are artificially limiting the client's throughput potential by using the same pool for all subscriptions.  If my application has 2 main streams to read, I would want to start 2 different subscriptions on 2 different threads for processing.

Workarounds
----------
* You may argue that as a client I can enqueue the events I receive into my own buffer to process on my own thread.  This is true, however at that point my consumer is consuming events instantly according to what eventstore sees and is very likely to reach max memory as eventstore will continually push messages to me to which I will continually enqueue them into memory.

The solution to that problem.. would be to put a blocking call in `eventAppeared` and we are back at the issue above.

* User could use a competing consumer pattern to spread the load among many consumers.  But there is still an issue of 1 client receiving many more events than it can handle in the case of PINNED consumers and a minority of very active streams.

Conclusions
-------------
At this point I hope I've made a good enough case that there are conditions in which the ThreadPool is a poor choice for event delivery.  So lets move on to what to do about it.

Solutions
----------
* Have a subscription option similar to autoAck or bufferSize to tell the client api to spin a new thread instead of using the thread pool.  This is my suggestion as its not too far from running a thread pool thread with `TaskCreationOptions.LongRunning` which is no longer suggested as proper use of TaskScheduler but a good comparison.

* Upgrade to C# 5.0 and modify the signature of the `eventAppeared` action to be asynchronous.  Something like `Func<Task> eventAppeared`

This would allow users to `WaitAsync` instead of a blocking `Wait` freeing the pooled thread when limits are hit.

That's all from me so far, I'll be back to respond to arguments against - hope it was concise enough.

**Comment by Salgat** [comment]
I've brought this up before but this is an issue I'm currently facing too. As of now I'm just using a TPL BufferBlock to consume events and setting the buffer large enough to try not to block for too long while my consumer can asynchronously await consumption of new events from the BufferBlock. Very frustrating that no Func<Task> interface exists for subscriptions.

**Comment by nappy** [comment]
@Salgat BufferBlock.Post does not wait. It either accepts the item for processing or not. The issue only arises when your buffer is full and Post returns false.
What happens if you throw an exception in that case, instead of synchronously waiting for the buffer to accept new input btw.?
But in general I think this is a systematic issue with this library. Its not only that you get synchronous callbacks on default thread pool threads, which leads to a predictable behavior at least. It is also the case that an async call might block a default thread pool thread under the hood (using Thread.Sleep), without you even knowing. There is not much awareness however here that this is even an issue.

**Comment by Salgat** [comment]
For blocking before adding to bufferblock, I added a semaphoreslim to address that issue.

**Comment by rodolfograve** [comment]
Issue #861 is asking for the same, using pretty much the same arguments. It would be nice to hear something back from the GetEventStore team.

**Comment by volak** [comment]
Closing as this has been fixed by other async improvements
