### ISSUE TITLE
PersistentSubscription: when message timeout is large _byTime grows large

### ISSUE THREAD

**Issue by volak** [EventStore/EventStore#1147]
The `OutstandingMessageCache` structure doesn't remove messages from `_byTime` upon ACKing.  It only removes them when the message expires causing an issue if you use a large message timeout such as #1140 

If a message "never" expires `_byTime` would just grow forever

**Comment by gregoryyoung** [comment]
The reason I moved it from #1140 as its a different issue. Whether it was 30 years or 5 years at 2000 messages/second wouldn't much matter  :+1:

**Comment by gregoryyoung** [comment]
The solution I think is to remove on read by remembering the expiry (otherwise it ends up in a scan)

**Comment by hayley-jean** [comment]
This has been fixed by #1151
