### ISSUE TITLE
ApplicationPath does not return correct path when starting EventStore from different directory

### ISSUE THREAD

**Issue by jageall** [EventStore/EventStore#1149]
https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.Common/Utils/Locations.cs#L24 attempts to guess the directory that EventStore is being loaded from for the purposes of loading config files and other resources.  but it does not resolve correctly on linux if EventStore is not started from the directory containing eventstored. 

Repro (on fresh ubuntu 16.04):
```
apt-get update
apt-get install wget
wget http://download.geteventstore.com/binaries/EventStore-OSS-Ubuntu-14.04-v3.9.3.tar.gz
tar xfv EventStore-OSS-Ubuntu-14.04-v3.9.3.tar.gz
./EventStore-OSS-Ubuntu-14.04-v3.9.3/eventstored 
```

related to #1148 as if fixed, #1148 would not have been observed, but fixing this does not really fix #1148

**Comment by nissbran** [comment]
This seems to have something to do with the mono bundle. It works fine if you run without mono statically linked. After a some investigation, it seems like the Assembly.GetExecutingAssembly().Location only returns the FileName of the assembly and not full path if the application is bundled with mkbundle.

**Comment by gregoryyoung** [comment]
This sounds likely though I thought the bundle defaults to /etc unless explicitly told otherwise

**Comment by nissbran** [comment]
I tested this quick by creating a regular console app that prints the Assembly.GetExecutingAssembly().Location.
With mono runtime (mono 4.6.2 on ubuntu) it returns full location path (ex /bundle/Assembly.exe).
After mkbundle (mkbundle -o test Assembly.exe --static --deps), the program only returns Assembly.exe regardless of the starting directory. 

So the code in the [https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.Common/Utils/Locations.cs#L24](https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.Common/Utils/Locations.cs#L24) class will always default to Path.GetFullPath(".") if it runs as statically linked.

**Comment by gregoryyoung** [comment]
Maybe Directory.GetCurrentDirectory is better here as a default for linux though it requires it actually being set

**Comment by gregoryyoung** [comment]
Had some discussions will likely support something like:

Path GetNativeExecutablePath(Process p) {
    if(linux) //linux specific way
    if(OSX) //OSX specific way
    return Directory.GetCurrentDirectory.
}

Does this seem reasonable to people here?

**Comment by mat-mcloughlin** [comment]
closed as no longer a problem
