### ISSUE TITLE
Expose resignation of leadership over HTTP

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#1170]
To test client behaviour under failover it is useful to be able to induce leader election over HTTP. This should be a privileged operation (probably on the Admin controller).

cc: @ntl

**Comment by gregoryyoung** [comment]
:+1:

Should this also change the election behaviour to force a new master or just hold an election (both seem like reasonable options). Under most circumstances forcing an election will just result in the same master,

**Comment by jen20** [comment]
Perhaps this should be an option - it might be useful to force a new leader in order to prepare a node for removal etc.

**Comment by gregoryyoung** [comment]
Yes though we need to look closely at how that handoff might work. It would change quite a few things. As example when I have a master with 10 more writes and we prefer a slave. That is weird.

**Comment by gregoryyoung** [comment]
To be fair there is a way to make this happen now "kill"

**Comment by jen20** [comment]
@gregoryyoung we would only be throwing away uncommitted events at this point though? (so yes, while weird, it wouldn't result in unexpected data loss)

**Comment by gregoryyoung** [comment]
@jen20 yes but we already have a way of doing this over http. /admin/shutdown

**Comment by gregoryyoung** [comment]
@jen20 we can add simply the "force election" but it will almost always result in the leader staying the leader unless there is some coordinated failure. Would "kill" be what is wanted for the other cases?

**Comment by pgermishuys** [comment]
Ref: #1982
