### ISSUE TITLE
Weird format strings for some log messages

### ISSUE THREAD

**Issue by bklooste** [EventStore/EventStore#1172]
eg {0,-25} {1} (0x{1:X})    param WRITER_CHECKPOINT , 0 

this is not a valid C# format string eg string.format throws exceptions ( eg param count does not match) 

NLog swallows / supports this but other loggers eg the net .NET logging framework Microsoft.Extentions.Logging via     LogManager.SetLogFactory(xyz );  does not.

**Comment by pgermishuys** [comment]
Hey @bklooste, closing this for now as there have been a lot of work done on cleaning up the log messages. Please reopen if there are any more of these.
