### ISSUE TITLE
Inconsistent checking for IDEMPOTENT WRITE if same event GUID in several streams

### ISSUE THREAD

**Issue by vmsgsp** [EventStore/EventStore#1173]
1. Write an event to a first stream "StreamA" 
2. Write the same event with the same GUID to a second stream "StreamB" 
3. Write same event GUID to "StreamA" again => IDEMPOTENT WRITE reported by Event Store
4. Write same event GUID to "StreamB" again => IDEMPOTENT WRITE not reported by Event Store, even though the event is already contained in StreamB as well.

Is this a bug or a feature?

The Event Store docs say that "Idempotence is not guaranteed if ExpectedVersion.Any is used. The chance of a duplicate event being written is small, but it does exist." But how can it be explained that ES behaves differently in this scenario without any concurrency involved?

```
var settings = ConnectionSettings.Create().KeepReconnecting();
connection = EventStoreConnection.Create(settings, new IPEndPoint(IPAddress.Parse(eventStoreAddress), eventStorePort));
connection.ConnectAsync().Wait();
Guid guidA = Guid.NewGuid();
Guid guidB = Guid.NewGuid();
Guid guidC = Guid.NewGuid();

connection.AppendToStreamAsync("StreamA", ExpectedVersion.Any, new EventData(guidA, "EventXY", false, null, null)).Wait();
connection.AppendToStreamAsync("StreamA", ExpectedVersion.Any, new EventData(guidB, "EventXY", false, null, null)).Wait();
connection.AppendToStreamAsync("StreamA", ExpectedVersion.Any, new EventData(guidC, "EventXY", false, null, null)).Wait();

//Write same event with guidA to a second stream B
connection.AppendToStreamAsync("StreamB", ExpectedVersion.Any, new EventData(guidA, "EventXY", false, null, null)).Wait();

//For the following 3 statements ES reports 3 "IDOMPOTENT WRITE TO STREAM"
connection.AppendToStreamAsync("StreamA", ExpectedVersion.Any, new EventData(guidA, "EventXY", false, null, null)).Wait();
connection.AppendToStreamAsync("StreamA", ExpectedVersion.Any, new EventData(guidB, "EventXY", false, null, null)).Wait();
connection.AppendToStreamAsync("StreamA", ExpectedVersion.Any, new EventData(guidC, "EventXY", false, null, null)).Wait();

//For the following 3 statements Event Store DOES NOT report any "IDOMPOTENT WRITE TO STREAM"
connection.AppendToStreamAsync("StreamB", ExpectedVersion.Any, new EventData(guidA, "EventXY", false, null, null)).Wait();
connection.AppendToStreamAsync("StreamB", ExpectedVersion.Any, new EventData(guidB, "EventXY", false, null, null)).Wait();
connection.AppendToStreamAsync("StreamB", ExpectedVersion.Any, new EventData(guidC, "EventXY", false, null, null)).Wait();

Guid guidD = Guid.NewGuid();
Guid guidE = Guid.NewGuid();
connection.AppendToStreamAsync("StreamB", ExpectedVersion.Any, new EventData(guidD, "EventXY", false, null, null)).Wait();
connection.AppendToStreamAsync("StreamB", ExpectedVersion.Any, new EventData(guidE, "EventXY", false, null, null)).Wait();
//Event Store reports "IDEMPOTENT WRITE TO STREAM"
connection.AppendToStreamAsync("StreamB", ExpectedVersion.Any, new EventData(guidD, "EventXY", false, null, null)).Wait();
```

Event Store Client API 3.9.3.0
EventStore-OSS-Win-v3.9.3

**Comment by gregoryyoung** [comment]
why are you writing events with the same id? The id of an event is meant to uniquely identify it. ES is saying "I have seen this write before" and not doing it a second time.

**Comment by vmsgsp** [comment]
In the happy path, of course, we do not write the same event to the same stream twice. In our scenario we forward events from one system to another one. And sometimes it can happen that an event gets forwarded again (by error). Anyway, Event Store detects this nicely (even if not guaranteed, I know). And contrary to what you are saying, Event Store detects the IDEMPOTENT WRITE every time and again, you write the same event to the same stream (not only at the first time you write to the same stream).

The strange thing is that it behaves differently as soon as the event with the same id is also written to a different stream (so that the same event id lives in two different streams). The Event Store documentation about Idempotency says "It is possible to reuse an EventId across streams whilst maintaining idempotence.". Therefore I assume it is a valid use case to put the same event into different streams (but always with the same event id in different streams).

Why should Event Store now not detect that the event is written to the same (second) stream again? I would expect that Event Store detects that the Event Id is existing, no matter whether you re-write it to the first stream again or to the second stream again.

**Comment by gregoryyoung** [comment]
Idempotency is assured when you write to a stream using an expected version. In all other scenarios it is "best attempt". 

"The strange thing is that it behaves differently as soon as the event with the same id is also written to a different stream"

We try to maintain the last million or so event ids to give idempotency for those who wish to write without specifying an expected version. Using the same id for multiple events is not a good idea. It is not that uuids are a precious resource.

**Comment by vmsgsp** [comment]
We are not using the same event id for multiple (different) events. It is the very same event, which by error gets pushed several times into the same stream (this is what the code example above shall illustrate to reproduce the issue). So Event Store checks back the million event ids, which is fine. Why can't it do this check also for the second stream where the same event lives in?
Event Store docu says: "It is possible to reuse an EventId across streams whilst maintaining idempotence.".

**Comment by ylorph** [comment]
Closing as this is a really unusual way of using the API .
Suggestion : The original IDs of the the imported events could be stored in metadata.
