### ISSUE TITLE
Projection updated event

### ISSUE THREAD

**Issue by PaulGrimshaw** [EventStore/EventStore#1174]
Is there a way to subscribe to a projection, and receive the state each time it updates, or at least be notified of when it has updated?  Ideally it woud have the event id that triggered the update too.

This would be useful for an async app, where a form is submitted, storing an event.  The app then waits till it knows the projection has seen this specific event before showing the next screen (e.g. a "create invoice" form leading to an "invoice summary" view.

I know I could emit my own event to a "projectionUpdates-xxx" stream, but that would muddy the logic for the projection.  Wondered if there was anything built in for this?

**Comment by pgermishuys** [comment]
Yes,
Just add `outputState()` as a method call at the end of your projection.
For Example
```
fromStream('myStream')
.when({
  $init:function(s,e){
    return { count: 1 }
  },
  $any:function(s,e){
    s.count += 1;
  }
}).outputState();
```
This will produce a stream called `$projections-{your-projection-name}-result` and the body of the event will contain the state.

**Comment by PaulGrimshaw** [comment]
Great, will do that.  Thanks
