### ISSUE TITLE
4.0 Position on Stream Read

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#1186]
We have been holding off on this change but 4.0 is the time to do it. We should add Position (Prepare/Commit) to a stream read.

**Comment by gregoryyoung** [comment]
This is already there it is on ResolvedEvent https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/Protos/ClientAPI/ClientMessageDtos.proto#L46 closing.

**Comment by jageall** [comment]
seems to be an issue with the embedded client
