### ISSUE TITLE
Stats Stream Problem

### ISSUE THREAD

**Issue by peter-miroshnikov** [EventStore/EventStore#1187]
Hello,
This is more of a question since i couldn't find my way around it.
I am sorry if its in the wrong place.

Our Status stream  of our Cluster Nodes generate too much data and fills the hard-drives too fast.
Is there a way to reduce the stats data or turn it off if needed ?

Best Regards
Peter

**Comment by pgermishuys** [comment]
Set `$maxAge` or `$maxCount` on the statistics stream and run a scavenge on a schedule to reclaim the space.

[See](http://docs.geteventstore.com/server/4.0.0/metadata-and-reserved-names/) for more information on the above mentioned metadata.

**Comment by pgermishuys** [comment]
Going to close the issue for now, please feel free to reopen if you have any further questions.

**Comment by ChrisMcKee** [comment]
As all the links have changed and been broken https://eventstore.org/docs/server/metadata-and-reserved-names/index.html
