### ISSUE TITLE
It seems the liveProcessingStarted does not get raised for SubscribeToAllFrom [netcoreclient]

### ISSUE THREAD

**Issue by AndreSteenbergen** [EventStore/EventStore#1189]
I have the following code in my project which works fine:
```
_connection.SubscribeToStreamFrom("Projection", _latestPosition, new CatchUpSubscriptionSettings(int.MaxValue, 10, false, true), HandleEvent, CaughtUp);
```

But this code never gets to CaughtUp:
```
_connection = EventStoreConnectionWrapper.Connect();
            _connection.SubscribeToAllFrom(
                _latestPosition,
                new CatchUpSubscriptionSettings(int.MaxValue, 10, true, true),
                HandleEvent,
                CaughtUp);
```

Am I missing something?

**Comment by pgermishuys** [comment]
Subscribing to $all requires administrative rights and as such you have to provide the connection or the call itself with the credentials for a user that has those rights.

**Comment by AndreSteenbergen** [comment]
I get the events without any issue. It just never sees the CaughtUp event.

**Comment by pgermishuys** [comment]
Ah! It wasn't clear from the code snippet that you were passing the credentials. Will investigate and get back to you.

**Comment by AndreSteenbergen** [comment]
Thx, to bemore complete, I am using the nuget package (0.0.1 alpha)

**Comment by pgermishuys** [comment]
👍

**Comment by AndreSteenbergen** [comment]
Sorry to bother again. It was something totally different. In my handle I had a blocking piece of code. The debug logging didn't go all the way to the end.

**Comment by pgermishuys** [comment]
Would you like us to close this issue then?
