### ISSUE TITLE
Compete Consume + TruncateBefore

### ISSUE THREAD

**Issue by charlessolar** [EventStore/EventStore#1195]
Just started an interesting use case where I write certain overflowing events back to the store during times of peak load and have my consumers compete consume from the stream eventually draining the backed up events.  

And it seems like there could be a neat additional feature for ES to automatically set TruncateBefore when it does checkpointing on the stream so the events are deleted next scavenge.  Since once I ack a delayed message I'm never going to need it again.  

I was going to do this myself, but I realized as a consumer I don't get info about checkpointing do I?  Unless I subscribe to the checkpoint stream I guess

**Comment by oskardudycz** [comment]
@jageall, @condron, @hayley-jean, that's an interesting use case for using ESDB as a messaging/streaming platform. I'm not sure if that's the direction we'd like to go, but if we do, then it's worth considering if we plan to clean automatically consumed messages (e.g. like RabbitMQ). My guess is that could be useful even for some of our customers.

**Comment by hayley-jean** [comment]
At the moment the way to do this would be to subscribe to the checkpoint stream yourself and truncate as the checkpoints are written. It is an interesting use case, but I don't know that we'll be looking at it in the near future

**Comment by condron** [comment]
I don't think there is enough information to provide useful checkpointing information on the events as they are delivered. This is compounded by issues of retries and multiple consumers. 
Consuming the checkpoint stream is the only way this would really work.
We might consider adding a metadata update capacity to the projection engine to automate this. That would need to go in the backlog for consideration after the other projection changes.
