### ISSUE TITLE
Projections are unresponsive until restart

### ISSUE THREAD

**Issue by kstrauss** [EventStore/EventStore#1218]
I've updated to the latest source (as of yesterday https://github.com/EventStore/EventStore/commit/8df56dfe844bd3d583ab17f7b461e13a076fa17b ), and have put in place on a test server. I'm still seeing a single projection that will not complete. It moves forward after every restart. The projections webscreen still shows it running but it hasn't progressed in hours:
![image](https://cloud.githubusercontent.com/assets/3475426/23022488/1bce5c54-f41f-11e6-9632-e584ed354e97.png)

could it be that #1056 is not fixed? or is it something wrong with my particular projection? I can't stop and recreate using this projection easily unless there is a way to create a projection starting from a set of particular positions (hmmm enhancement for #328 )? 

As another note (and perhaps it should be another issue), but I am also not seeing all the $et streams being up to date, but the Projections screen shows $by_event_type as being 100% and running.
![image](https://cloud.githubusercontent.com/assets/3475426/23025728/e4d5bd9c-f42c-11e6-8b75-fc5bb5a9c5c4.png)

vs.
![image](https://cloud.githubusercontent.com/assets/3475426/23025758/f54ee266-f42c-11e6-8680-9215f8914f21.png)

What further details can I provide to help? I do not see anything to my untrained eye in the logs.
[10.0.0.76-2113-cluster-node.txt](https://github.com/EventStore/EventStore/files/780458/10.0.0.76-2113-cluster-node.txt)

**Comment by pgermishuys** [comment]
I see you have a number of projections, what are their statuses?
The reason I ask is because I am seeing some very slow messages regarding reads up to 12 seconds for a single read.
The particular projection that has stopped processing silently, what's it's definition?

**Comment by kstrauss** [comment]
All except the one highlighted above are all reported as 100% running including the system one of $by_event_type. The definition of the never completed projection (by the report screen) is pretty generic but is below.
`
      // used for Received PackageTracking, and potentially others
      
    fromStreams(['$et-PackageIdentified', '$et-PackageDecoded', '$et-PackageDecodedWithConcerns',	'$et-PackageCreated', '$et-PackageContainerized', '$et-PackagePlaced', '$et-PackageIntegrated', '$et-PackageIgnored', '$et-PackageConcernsAddressed', '$et-PackagePublished', '$et-ItemDecoded', '$et-ItemConcernsAddressed'])
		.when({
			$init: function (s, e) {
				return {
					countReceived: 0,
					lastEventSeen: 'notSet'
				};
			},
			$any: function (s, e) {
				linkTo('Xi::' + e.eventType, e);
				s.lastEventSeen = e.eventType;
			}
		});
`

**Comment by kstrauss** [comment]
I built this commit and have tried using it on an existing database. I however am still seeing the same behaviour.

**Comment by pgermishuys** [comment]
@kstrauss we will then continue to pursue the quest of finding out what your particular issue is.

**Comment by mmuller99** [comment]
seeing [#789](https://github.com/EventStore/EventStore/issues/789) on regular intervals + some more errors, maybe it helps on the quest intime for 4.0.0.

@pgermishuys [Logs.zip](https://github.com/EventStore/EventStore/files/841357/Logs.zip)

**Comment by pgermishuys** [comment]
We have identified and fixed another issue which would have caused projections to get stuck. PR : https://github.com/EventStore/EventStore/pull/1255

**Comment by hayley-jean** [comment]
Closing this due to a number of fixes having been done around this issue. If anyone sees this again, please open a new issue.
