### ISSUE TITLE
Embedded Client .nuspec Include required files for Projections to work

### ISSUE THREAD

**Issue by milkshakeuk** [EventStore/EventStore#1220]
When running the embedded client nuget package v3.9.4 and you want to create and run an EventStore Projection  `js1.dll` and `Prelude` folder are required otherwise you get the following error: 

```The projection subsystem failed to load a libjs1.so/js1.dll/... or one of its dependencies.  The original error message is: Unable to load DLL 'js1': The specified module could not be found. (Exception from HRESULT: 0x8007007E)```.

Currently although these items are packed into the nuget package they are not automatically added to your bin folder on compile, this could possibly be fixed by updating the .nuspec file know about these content files [see nuspec reference](https://docs.microsoft.com/en-us/nuget/schema/nuspec#including-content-files).

**Comment by bklooste** [comment]
This works on windows with 3.94/4 so its a linux only issue

**Comment by milkshakeuk** [comment]
This is not a Linux only issue,  when I raised this it was  because I was having problems on Windows.

**Comment by bklooste** [comment]
Strange I did see the error before but not recently for some new projects,  2 changes though we have gone to 4 and we now just use the default projections.

**Comment by regularcoder** [comment]
I faced a similar problem. js1.dll and Prelude were already automatically placed inside the bin folder. In my case the root-cause was that js1.dll is a 64-bit DLL and my project file had:

`<PlatformTarget>AnyCPU</PlatformTarget>`
`<Prefer32Bit>true</Prefer32Bit>`

When I changed platform target to x64 it ran fine.

**Comment by jageall** [comment]
32 bit builds are no longer supported, so this issue is being closed
