### ISSUE TITLE
eventstore 4.0.0-rc1 crash (sounds libjs1 related)

### ISSUE THREAD

**Issue by shouze** [EventStore/EventStore#1232]
Here's the captured stack trace:
https://gist.github.com/shouze/b2bd530252674eabed4f1178dedfced3

Unfortunately `Debug info from gdb` is empty 😭 

It's the ubuntu xenial distribution, haven't tried to reproduce with the trusty one ATM.

As libjs1 is somehow a deprecated technology... what's needed to remove it from the project? As you already embed v8... I guess it can replace it no?

**Comment by pgermishuys** [comment]
Thanks for logging this issue @shouze. Will investigate.
