### ISSUE TITLE
Internal error on Projections with eventstore 4.0.0-rc1

### ISSUE THREAD

**Issue by shouze** [EventStore/EventStore#1233]
maybe related to #683?

Eventstore don't crash but the projection is then inconsistent.

```
[00001,20,11:16:53.233] Resetting 'translations_orders_in_progress' projection
[00001,20,11:16:53.235] Error while processing message EventStore.Projections.Core.Messages.ProjectionManagementMessage+Command+Reset in queued handler 'Projections Master'.
Specified method is not supported.
[00001,27,11:16:55.059] SLOW QUEUE MSG [MonitoringQueue]: GetFreshStats - 159ms. Q: 0/0.
[00001,20,11:16:58.255] Resetting 'translations_orders_in_progress' projection
[00001,20,11:16:58.256] Error while processing message EventStore.Projections.Core.Messages.ProjectionManagementMessage+Command+Reset in queued handler 'Projections Master'.
Internal error: projection definition must be saved before forced updating version
```

**Comment by hayley-jean** [comment]
Thanks for reporting this @shouze 

Could you please provide a little bit more information :
What caused these errors to start happening?
What do you mean by the projection being "inconsistent?" Is it still running and processing events?

**Comment by shouze** [comment]
@hayley-jean I need to reproduce it again, was occuring on CI so didn't had more details at this time except this log extract.

The only thing I can tell you is that on CI during our test suites execution we reset projections sometimes by doing in that order, with HTTP api:
1. deleting the stream related to a projection:
```
curl -x DELETE http://domain.tld/streams/{streamName}
```
2. Then immediately after reseting the projection:
```
curl -x POST` -H 'Content-Length: 0' -H 'Content-Type: application/json' http://domain.tld/{projectionName}/command/reset
````

Does this help?

**Comment by pgermishuys** [comment]
@shouze when you say "deleting the stream related to a projection". Are you talking about the stream that the projection wrote to? If so, you can skip step 1. By resetting a projection, it will soft delete the streams it wants to write to.

**Comment by shouze** [comment]
Ok will try it & give you a feedback soon.

**Comment by hayley-jean** [comment]
Hi @shouze, do you have any feedback about this? Have you seen this issue again on the latest release?

**Comment by shouze** [comment]
It's ok now, can't reproduce, it can probably occur though when eventstore is not yet ready but it's a very rare race condition.
