### ISSUE TITLE
Choco install puts the Event Store executables in the Chocolatey bin

### ISSUE THREAD

**Issue by eric-swann-q2** [EventStore/EventStore#1246]
Choco install puts the Event Store executables in the Chocolatey bin with the chocolatey executables.  It should place these in the EventStore folder.

**Comment by Gentlehag** [comment]
ist this the official choco ? https://chocolatey.org/packages/eventstore-oss/4.0.0.1

**Comment by pgermishuys** [comment]
No, the official release is https://chocolatey.org/packages/eventstore-oss/4.0.0

**Comment by pgermishuys** [comment]
The releases that are public and visible are
```
EventStore 4.0.0
EventStore 4.0.0-rc3
EventStore 4.0.0-rc2
EventStore 4.0.0-rc1
EventStore 4.0.0-alpha3
EventStore 4.0.0-alpha2
EventStore 4.0.0-alpha1
```

**Comment by Gentlehag** [comment]
Btw can the default parameters be passed to the cocolatey package like `--run-projections=ALL`

**Comment by hayley-jean** [comment]
The chocolatey packages have changed since version 20.6. If anyone is still having these issues after 20.6, please reopen this or make a new issue.
