### ISSUE TITLE
Persistent subscriptions on projection stream with no events seems broken

### ISSUE THREAD

**Issue by philipkaare** [EventStore/EventStore#1252]
I get an AccessDenied exception when I 
1) create a persistent subscription for an event type projection ($et-), when no events of that type have been appended to any streams. 
2) try to subscribe to said subscription

It's of course possible to work around this issue, but it's annoying. Is this a known requirement for subscribing to event type projection streams or a bug? The issue goes away as soon as a single event exists of that type.

**Comment by hayley-jean** [comment]
Hi @philipkaare 

What credentials are you using to connect to and create the persistent subscription?
`$et-<type>` streams are considered system streams, so by default you can only read or write to them using admin credentials.

If the above isn't the issue, could you please provide us with the full error message?

**Comment by philipkaare** [comment]
Hi @hayley-jean 

First, thanks for your quick reply and a great product! I was connecting with operations credentials, and changing to admin credentials does seem to have solved the problem. I still suspect a bug, as I was getting inconsistent behavior depending on whether the stream was empty or not. 

In any case it would be nice to have a section on permissions in the documentation, I don't think that's very clear right now. 

Thanks.

**Comment by hayley-jean** [comment]
Great, we'll have a look at what could be causing the inconsistencies depending on whether there were items in the stream.

As for more documentation around permissions, I've added an issue on our docs repo for it.

**Comment by philipkaare** [comment]
Sounds good! By the way I am working on a little library to make it a bit easier to use Event store with F#, maybe it would be interesting for you: https://github.com/rehfeldmedical/EventStoreFsExt.

**Comment by Eranikid** [comment]
I am still getting similar behavior, was this issue fixed?
