### ISSUE TITLE
Unsafe download of binaries 

### ISSUE THREAD

**Issue by perjahn** [EventStore/EventStore#1253]
Your site links to binaries at http, when instead trying to download from https://download.geteventstore.com/..., I recieve a certificate failure when using Chrome, first time before accepting it.

Can you please fix this, because it prevents automated script from downloading the binaries in a secure way.

**Comment by ChrisMcKee** [comment]
@perjahn https://eventstore.org/downloads/ looks like its been fixed.

**Comment by shaan1337** [comment]
@ChrisMcKee thanks! closing this.
