### ISSUE TITLE
External Ip Resolved in BadRequest Invalid Hostname

### ISSUE THREAD

**Issue by Gentlehag** [EventStore/EventStore#1254]
When I try to access the eventstore with the Private LAN IP of a machine (instead of localhost or 127.0.0.1) I get a Bad Request  back

Is this intended behavior  ? Do I have to extend a binding config somewhere?

**Comment by pgermishuys** [comment]
By default when Event Store starts up, it will attempt to set HTTP Prefixes for `http://localhost:{ext-http-port}` as well as `http://127.0.0.1:{ext-http-port}`.

For example, in the logs you will see
```
[24441,15,08:28:25.701] Starting HTTP server on [http://127.0.0.1:2113/,http://localhost:2113/]...
[24441,15,08:28:25.706] HTTP server is up and listening on [http://127.0.0.1:2113/,http://localhost:2113/]
```

You can change this behaviour by setting the prefixes to accept any request on a designated port
e.g.
`--ext-http-prefixes=http://*:2113/`
