### ISSUE TITLE
Wipe all the streams for testing

### ISSUE THREAD

**Issue by BroiSatse** [EventStore/EventStore#1256]
Hi all,

I was wondering, is it possible to complete reset the entire EventStore? I have a couple of small unit tests which I would expect to run on a clear-state stream, however I cannot wrap my head around on how to reset the EventStore after the test.

**Comment by pgermishuys** [comment]
The in memory mode is made specifically for this. By using running Event Store with `--mem-db=true`.

**Comment by BroiSatse** [comment]
@pgermishuys - Oh wow, that was super quick. Thanks for that! How do you then reset the database though. I assume I need to restart the event store process?

**Comment by pgermishuys** [comment]
If you want a complete wipe, just clear the data directory. The default directory for each of the operating systems can be found here. http://docs.geteventstore.com/server/4.0.0/default-directories/.
In short
- Stop your event store process
- Clear out the data directory
- Start the event store process with `--mem-db`

**Comment by BroiSatse** [comment]
That's great, would you mind if I make a PR to docs? I think that is quite useful stuff to know. :)

Still not sure, how would I then wipe the state between tests? I assume since it will be running in-memory  restart will do. I don't think there is an API endpoint to wipe in-memory streams?

**Comment by pgermishuys** [comment]
Can't you just have a stream per test?
e.g.
```
test_stream = `can_read_last_event-{uuid}`
```

**Comment by BroiSatse** [comment]
@pgermishuys - Ha, sometimes the easiest solutions are just the hardest to spot. This would be ideal as I could run those tests concurrently. I will need to add some mechanism to register streams that has been used per test but it shouldn't be too difficult.

Once again thanks for all the help!
