### ISSUE TITLE
EventStore 4.0 Where is "WhenAny" Gone?

### ISSUE THREAD

**Issue by Gentlehag** [EventStore/EventStore#1257]
Previously I used the following subscription to have a subscrible stream of all Event with the given prefix

Now in EventStore 4.0 There seems to be not anymore a whenAny function ?

How to convert this ?

```
fromCategory('myPrefix')
                  .whenAny(function(s, e) {
                        linkTo('PrefixStream', e);
            }); 
```

PS: Is there a document about breaking changes somewhere?

**Comment by pgermishuys** [comment]
@Gentlehag apologies, this breaking change was missed in the blog post. Having `whenAny` and `$any` was redundant and a decision was made to remove `whenAny`.

You can convert it to
```
fromCategory('myPrefix')
.when({
	$any:function(s,e){
		linkTo('PrefixStream', e);
	}
})
```

PS: We will update the blog post and the release notes. Apologies for this being missed.

**Comment by Gentlehag** [comment]
Many thanks !

**Comment by pgermishuys** [comment]
There is a workaround if you like and that is to add the function back into your `1Prelude.js` file.
```
    function whenAny(handler) {
        eventProcessor.on_any(handler);
        return {
            $defines_state_transform: $defines_state_transform,
            transformBy: transformBy,
            filterBy: filterBy,
            outputState: outputState,
            outputTo: outputTo,
        };
    }
```

**Comment by Gentlehag** [comment]
i'm fine with the new syntax as long as it is working :-)
