### ISSUE TITLE
Questions: Event Store 4.0 for OSX & Mono

### ISSUE THREAD

**Issue by davidgoate** [EventStore/EventStore#1269]
Hi,

I have two questions regarding Event Store for OSX.

1. Is there a reason why Event Store 4.0 doesn't seem to be available specifically for OSX whereas previous versions such as 3.9.3 are on the [downloads page](https://geteventstore.com/downloads/). Just curious as to whether the intention to support OSX for the most recent versions is there longer term?
2. I'm not from a .NET background, but from some very brief searching I understand that Mono is a runtime & set of tools that allows .NET applications be run and compiled cross platform. What is not so clear to me is the different between the OSX download that is named with the suffix (Mono) and the distribution that doesn't have this suffix. Are there any fundamental differences one should be aware of when deciding which version to run?

**Comment by pgermishuys** [comment]
1. We have not decided to terminate the OSX binaries for Event Store, there is an issue we need to resolve before publishing them, however for development purposes (which the OSX libraries are intended for) you can use the [docker image](https://hub.docker.com/r/eventstore/eventstore/).

2. The binaries you see in the download section of Event Store labelled with the Mono is where the Mono runtime has not been embedded in the package and you are required to have Mono installed to run that particular Event Store package using something along the lines of 
```
mono EventStore.ClusterNode.exe
```
whereas the versions that have Mono embedded you don't have to have Mono installed and can download and run Event Store using
```
./eventstored
```

**Comment by davidgoate** [comment]
Thanks for the response.

**Comment by drozzy** [comment]
Any update on MacOS binaries for Eventstore 4? @pgermishuys

**Comment by jen20** [comment]
Hi @drozzy, we should have them back soon as part of #1710. I successfully have everything building and running on OS X now, and am adding OS X targets for CI shortly.

**Comment by rickardoberg** [comment]
We are currently looking at moving from 3.9.x to 4.x, but not having an OSX package for dev is painful. Any progress on this? @pgermishuys

**Comment by shaan1337** [comment]
@rickardoberg yes, we're going to have OS X downloads available for the next release of EventStore. Not sure yet if we will have self-contained binaries (we need to test), in the worst case it'll require an installation of mono.

**Comment by ChrisChinchilla** [comment]
And @jen20 and I plan to resurrect Homebrew packages soon!
