### ISSUE TITLE
Issues found by PVS-Studio

### ISSUE THREAD

**Issue by VasilievSerg** [EventStore/EventStore#1274]
Hello,
I have found a few issues using PVS-Studio analyzer. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

Analyzer warnings:

- V3021 There are two 'if' statements with identical conditional expressions. The first 'if' statement contains method return. This means that the second 'if' statement is senseless EventStore.Projections.Core PartitionStateCache.cs 57
[A link to the source code.](https://github.com/EventStore/EventStore/blob/52cf1cdd34caa04ee14497d694082d5cf64a681c/src/EventStore.Projections.Core/Services/Processing/PartitionStateCache.cs#L59)
- V3095 The 'msg.Events' object was used before it was verified against null. Check lines: 158, 161. EventStore.Core Convert.cs 158
[A link to the source code.](https://github.com/EventStore/EventStore/blob/52cf1cdd34caa04ee14497d694082d5cf64a681c/src/EventStore.Core/Services/Transport/Http/Convert.cs#L158)
- V3083 Unsafe invocation of event 'EnsureTickPending', NullReferenceException is possible. Consider assigning event to a local variable before invoking it. EventStore.Projections.Core StagedProcessingQueue.cs 213
[A link to the source code.](https://github.com/EventStore/EventStore/blob/52cf1cdd34caa04ee14497d694082d5cf64a681c/src/EventStore.Projections.Core/Services/Processing/StagedProcessingQueue.cs#L213)
- V3083 Unsafe invocation of event 'Completed', NullReferenceException is possible. Consider assigning event to a local variable before invoking it. EventStore.ClientAPI AsyncStreamCopier.cs 85
[A link to the source code.](https://github.com/EventStore/EventStore/blob/52cf1cdd34caa04ee14497d694082d5cf64a681c/src/EventStore.Transport.Http/AsyncStreamCopier.cs#L85)

In addition, I suggest having a look at the emails, sent from @pvs-studio.com.

Best regards,
Sergey Vasiliev

**Comment by gregoryyoung** [comment]
I am surprised a static analysis tool found so few issues in such a large code base!

Thanks @VasilievSerg

**Comment by VasilievSerg** [comment]
@gregoryyoung , perhaps, I didn't state it clearly enough. There aren't all the issues found by the analyzer, just several of them. There were many more in the analysis. It would be much better if the developers had a look at the warnings themselves, because I am not familiar with the code. :)

**Comment by pgermishuys** [comment]
To which email address was the report sent @VasilievSerg ?

**Comment by VasilievSerg** [comment]
@pgermishuys , I haven't sent the log to anybody. In general, this is not the best idea. I described in this [article](https://www.viva64.com/en/b/0449/) why.

**Comment by pgermishuys** [comment]
Couple of the issues identified by this tool have been resolved. The tool needs to be run and the other issues investigated and resolved.

Closing this issue for now.
