### ISSUE TITLE
Update docs to reflect v4's 64-bit support.

### ISSUE THREAD

**Issue by michielboekhoff** [EventStore/EventStore#1276]
Hey,

In the docs right now, functions such as:

`Task AppendToStreamAsync(string stream, int expectedVersion, IEnumerable<EventData> events)`

still have an `int` as the `expectedVersion`, whereas this has been replaced by `long` for 64-bit support. The docs should be updated to reflect that. I'd be willing to do it sometime this week, if no one else is interested. 

Thank you.

**Comment by Narvalex** [comment]
Well, you are more than welcome to make a pull request here [Event Store Docs Repo](https://github.com/EventStore/docs.geteventstore.com)

**Comment by pgermishuys** [comment]
You are more then welcome to open the issue on the [docs repo](https://github.com/EventStore/docs.geteventstore.com). Thanks for raising the issue and some of these have been addressed in the following [PR](https://github.com/EventStore/docs.geteventstore.com/pull/225).
