### ISSUE TITLE
In the ResolvedEvent class, expose the position of the next event after calling ReadAllEventsForwardAsync

### ISSUE THREAD

**Issue by salfab** [EventStore/EventStore#1283]
I have a routine that processes elements from a slice (for a projection).
It may not be all elements from a slice (i.e. the next element might not be processed)

I need to persist the offset of the next element to process (i.e. ``ResolvedEvent.Position + 1``) in a DB so I know from where I should resume my projection.

Would it be possible to expose the "NextEventPosition" as a property of the ``ResolvedEvent`` ?

**Comment by hayley-jean** [comment]
You can take the position from the event after the one you have processed in the slice and use that to continue from. Otherwise use the `NextPosition` provided by the slice.
You should not be adding anything or changing these positions, as that would give you an invalid read.

**Comment by pgermishuys** [comment]
Closing this for now, @salfab please reopen if you have any further questions.
