### ISSUE TITLE
InvalidOperationException: Collection was modified when running projections (EventByTypeIndexEventReader )

### ISSUE THREAD

**Issue by jwalls89** [EventStore/EventStore#1291]
"System.InvalidOperationException: Collection was modified" appears when running built in projections.  Exception is thrown in EventByTypeIndexEventReader (attached error log).  It appears to happen on start up but doesn't happen every time but has happened 3 times in the last 24 hours.

Environment: Windows 8.1
EventStoreVersion: 4.0.0.7

Mode: SingleNode --run-projections=all

[127.0.0.1-2113-cluster-node-err.log.txt](https://github.com/EventStore/EventStore/files/961720/127.0.0.1-2113-cluster-node-err.log.txt)

**Comment by pgermishuys** [comment]
Thanks for raising this @jwalls89. This should be resolved in 4.0.2

**Comment by jwalls89** [comment]
Awesome - thanks @pgermishuys
