### ISSUE TITLE
Allow configuration of event size limit.

### ISSUE THREAD

**Issue by jezovuk** [EventStore/EventStore#1295]
According to comment in #899 (and confirmed after some source code inspection) event size limit is hard-coded to 16mb. Is it possible to make this limit configurable? Are there any practical limitations somewhere in the system (UI, projections, file layout on disk) which require this exact size limit, or is 16mb an arbitrary choice?

Our concrete use case is as follows: we're using EventStore for storing various types of time-series data downloaded from external sources (and propagating that data to various aggregators/calculators/read models). Main "data" events contain only changed values upon each reading, but in order to be able to detect changes, we must have aggregated previous state/data. In order to avoid having to aggregate those from incremental events each time (or on each app startup), we store "snapshot" events in separate streams (with maxCount set to 1 for each snapshot stream). External data is published in files (csv/xls) with forward-rolling time-windows. Hence, we tend to have snapshots that cover same amount of time as published file (thus rolling forward themselves). While data/incremental/diff events are mostly relatively small, snapshots in some cases can be quite large (over 10mb). We've recently hit the 16mb limit with some of our snapshots. (Also, we haven't seen this anywhere in the docs and were caught by surprise a bit.)

Although there are several ways to work around this problem (store snapshots in different store, break them up somehow, use compression etc., even give up tracking/keeping less relevant parts of data), it would be nicer and simpler/easier for us to be able to simply change the limit. We would get to keep JSON event structure (readability/projections), have only one (main) data store etc. Some performance degradation and similar problems are perfectly fine as long as things do work in general.

**Comment by gregoryyoung** [comment]
The size is already too big in practice unless you really are careful. The problem arises when you try to read a page of an event stream say 200 events. It makes a huge difference whether they are 5mb each or 500 bytes. This can lead to unpredictable behaviours such as not being able to read within timeout a given page.

I don't have any objection to this idea (and it is trivial to implement) but it will likely cause confusion as opposed to limiting confusion in most use-cases/

**Comment by jezovuk** [comment]
Thanks for quick reply. I'm aware of potential pagination problems (you've mentioned similar issues in google group discussion earlier), but with proper error messages/codes, that is ok for our use case. (For reference, we're using https://github.com/msemys/esjc as client library.) As for confusion, explicit warning in documentation should be enough :)

Now, if this could be released as minor release in 3.9.x train...

Thanks again,
Marko

**Comment by gregoryyoung** [comment]
It is relatively simple basically just adding an argument in favour of a constant. Will look at internally.

**Comment by jageall** [comment]
No further requests have been made since this time, and as pointed out, the 16Mb limit is already too big

**Comment by jezovuk** [comment]
I'm sorry to see this closed. We worked around this limitation quite some time ago, but still, it would be nice to have the ability to change the limit. Thanks for considering, anyway.

**Comment by gregoryyoung** [comment]
What benefit would changing the limit have for you? What use case would it enable?

**Comment by jezovuk** [comment]
As already mentioned in original issue description above, we use ES for storing diff events representing changes in external timeseries-based files (electrical energy production/consumption histoty&forecast). Files contain data in rolling time windows. Also, we store one 'snapshot event' for each file, containing last known content of that file (for diffing upon next check / external file read). Essentially, we poll the files and propagate diffs through series of calculations, while using one large 'event' per file as diffing reference. Since we only ever store one 'snapshot' event per stream, pagination and/or propagation is not a concern for these large events. Diffs are much smaller, of course. The limit can be circumvented by some redesign (some of which we already did), but I think event size configurability would make sense for this and similar use cases (at least as temporary measure).
