### ISSUE TITLE
Prompt user for confirmation before closing projection create/edit browser tab

### ISSUE THREAD

**Issue by iamkoch** [EventStore/EventStore#1306]
Small niggle. I was just crafting a new projection in the browser when I mindlessly hit Ctrl+W to expand selection resharper-style, when the browser tab closed and I lost my work. Obviously it's my own fault, however a prompt of "you will lose unsaved data" would have been very useful

**Comment by hayley-jean** [comment]
Thank you for the issue @iamkoch, I can see how this would be useful.
Because this is to do with the UI, I have opened an issue for this on the UI repo rather than here.

You can track it at https://github.com/EventStore/EventStore.UI/issues/151
