### ISSUE TITLE
Subscription WithReadBatchOf  >= WithBufferSizeOf results in no delivered events

### ISSUE THREAD

**Issue by volak** [EventStore/EventStore#1313]
Found a small configuration issue with persistent subscriptions.
If a silly user sets ReadBatchSize greater or equal to BufferSize the subscription will never deliver events to clients.

Seems like the line at https://github.com/EventStore/EventStore/blob/release-v4.0.2/src/EventStore.Core/Services/PersistentSubscription/PersistentSubscription.cs#L118

is the culprit.  It just gives up trying to deliver events if the buffer size can't accept the read size.

It would probably be nice for the client api to throw an exception if we specify such a configuration as the server code makes sense to me but it took a long while to figure out why my clients weren't receiving events.

Example https://github.com/volak/EventStoreProjectionIssue/blob/readbatch/EventStoreIssue/Program.cs

**Comment by sanderdegroot** [comment]
Thank you for filing this issue. It took me a while to track the cause of this issue down and it would have taken me even longer had I not come across this issue. Perhaps the relationship between ReadBatchSize and BufferSize could be documented as it was not clear to me from reading the documentation that BufferSize has to be less than ReadBatchSize in order for clients to be able to read events from a subscription.
