### ISSUE TITLE
Unsafe event raising could cause null reference exceptions

### ISSUE THREAD

**Issue by rodolfograve** [EventStore/EventStore#1315]
Hi.
This is a very low level issue but since I have been recently working on the code base for a PR I noticed there are a few places where raising events is done like:

`if (xxxx != null) xxxx(...)`

which is known to cause issues because subscribers can unsubscribe in between the null check and the invocation.

The solution is even easier now with the conditional operator:

`xxxx?.Invoke(...)`

I have spent a few hours replacing several if (yyy != null) yyy.F(), including the ones that cause the issue above.

I can submit the full PR if the team would take it, which would be a step towards using C# 6 features in your code, helping with readability, and ultimately, maintenability.

These are some of the places I have detected:

1. https://github.com/EventStore/EventStore/blob/release-v4.0.2/src/EventStore.ClientAPI/EventStoreCatchUpSubscription.cs#L250
1. https://github.com/EventStore/EventStore/blob/release-v4.0.2/src/EventStore.ClientAPI/EventStorePersistentSubscriptionBase.cs#L249-L252
1. https://github.com/EventStore/EventStore/blob/56c5680f51325cf0e99846da72ae313402c63c2d/src/EventStore.Transport.Http/AsyncStreamCopier.cs#L85-L86
1. https://github.com/EventStore/EventStore/blob/56c5680f51325cf0e99846da72ae313402c63c2d/src/EventStore.Transport.Http/AsyncStreamCopier.cs#L85-L86

This is not a full list. There are a few more.

**Comment by hayley-jean** [comment]
Thank you @rodolfograve 
You are more than welcome to submit a PR

**Comment by Narvalex** [comment]
Hi @rodolfograve! How do you know that the conditional operator is thread safe? After reading thoroughly [this conversation in Stackoverflow](https://stackoverflow.com/questions/35784874/is-c-sharp-6-elvis-op-thread-safe-if-so-how) I am curious about how this operator is not just a shortcut of the tradicional 
`if (event is not null) event.raise()`

**Comment by rodolfograve** [comment]
@Narvalex 

From https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators:

> Another use for the null-condition member access is invoking delegates in a thread-safe way with much less code

And

> The new way is thread-safe because the compiler generates code to evaluate PropertyChanged one time only, keeping the result in a temporary variable.

So, to be accurate, this operator is just a shortcut of the traditional correct form

```
var temp = eventHandler;
if (temp != null) temp(...);
```

**Comment by Narvalex** [comment]
I dit a test to verify this... And you are correct! Thanks @rodolfograve!

**Comment by rodolfograve** [comment]
PR #1317 ready

**Comment by Faq** [comment]
@rodolfograve can you split PRs with smaller changes so it would be easier to review code?

**Comment by rodolfograve** [comment]
Hi. I'm afraid I lost the environment I had already setup for #1310 and I won't be able to work on this PR anytime soon.

Sorry

**Comment by oskardudycz** [comment]
Closing it because of the inactivity.
