### ISSUE TITLE
Question on stream delete -> events of type "$>"?

### ISSUE THREAD

**Issue by akaegi** [EventStore/EventStore#1322]
When deleting a stream (hard delete) I get an event of type "$>" in the $et-$deleted stream as well as linked into the corresponding $cg-... stream. 

1. Can I use events of this type safely to e.g. update a read model? 
2. How to better obtain the stream id from the event?
a. from the data which has the form number@streamId
b. from the event metadata where it is stored as property "$o"

**Comment by hayley-jean** [comment]
1. Yes, it's safe to use events of this type.
2. Both of these are valid options.
