### ISSUE TITLE
Why no automatic reconnect for persistent subscriptions?

### ISSUE THREAD

**Issue by vmsgsp** [EventStore/EventStore#1324]
It seems that persistent subscriptions do not support automatic reconnect when event store server goes down and is restarted again. This is different from what we know for the catch-up subscriptions.
So for persistent subscriptions the KeepReconnecting() setting seems to be useless.
Is there any reason why the persistent subscriptions do not support the reconnecting feature out-of-the box? Do I need to implement it myself, or is there even a reason why I should not do so?

    var settings = ConnectionSettings.Create().KeepReconnecting();
    var connection = EventStoreConnection.Create(settings, new System.Net.IPEndPoint(IPAddress.Parse("127.0.0.1"), 1113));
    //Catch-up subscription
    connection.SubscribeToStreamFrom("StreamX", null, CatchUpSubscriptionSettings.Default, EventAppeared);
    //Persistent subscription
    connection.ConnectToPersistentSubscription("MyStreamY", "GroupY", PersistentEventAppeared);

When shutting down the EventStore server (stopping EventStore.ClusterNode.exe) and restarting it, the catch-up subscription processes the events again, whereas the persistent subscription does not.

EventStore & .NET Client API **Version 4.0.0**

**Comment by hayley-jean** [comment]
`KeepReconnecting()` only affects the connection itself, not the subscription. If your client loses connection to Event Store, it will keep on trying to re-establish a connection as opposed to retrying a set number of times before giving up.

Currently, you need to handle resubscribing yourself if the persistent subscription gets dropped. You can do this by specifying a `subscriptionDropped` handler and resubscribing in there.

This is different to catchup subscriptions, which are the only subscription to resubscribe. There is actually a bug around catchup subscriptions resubscribing that has not yet been fixed, which you can find here https://github.com/EventStore/EventStore/issues/929.
