### ISSUE TITLE
Official EventStore image needed

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#1327]
The current eventstore image states:

> Note: This container is for development purposes only

I'd like to use EventStore for my Kubernetes deployment; thus it would be preferable if the image is official both in README, intention and even if you'd make Docker Inc. turn your image into an official one.

I've created the F# image as an official image and I'd be happy to help you go all the way.

**Comment by Narvalex** [comment]
I think that the reason is this #1251

**Comment by haf** [comment]
I think I can decide about performance myself though – which seems to be the only issue mentioned in the thread that's tangible. Complexity itself is what we're building as developers and in my experience, limiting degrees of freedom, like Kube does is exactly the sort of complexity handling mechanism I want.

**Comment by pgermishuys** [comment]
@haf more than happy to work with you regarding the docker image.

**Comment by pgermishuys** [comment]
@haf, I am closing this issue in favour of the one I created on the docker repository (https://github.com/EventStore/eventstore-docker/issues/34)
