### ISSUE TITLE
Missing 4.0.1-rc1 pre-release for EventStore.Client.Embedded

### ISSUE THREAD

**Issue by rodolfograve** [EventStore/EventStore#1332]
You have recently released version 4.0.1-rc1 of the EventStore.Client API (thank you!), but didn't release the corresponding EventStore.Client.Embedded package.

Because the EventStore.Client.Embedded package has a dependency on EventStore.Client (=4.0.0) it is not possible to combine both in the same project using NuGet.

Could you please release EventStore.Client.Embedded 4.0.1-rc1, with a dependency on EventStore.Client 4.0.1-rc1?

**Comment by pgermishuys** [comment]
done.

**Comment by rodolfograve** [comment]
Lightning speed. Thanks!

I can confirm it's all working now.
