### ISSUE TITLE
Feature request: drop database 

### ISSUE THREAD

**Issue by kmalakoff** [EventStore/EventStore#1335]
In https://github.com/EventStore/EventStore/issues/1328, I started to make a case for drop database across all backing storage types for Event Store.

Drop Database would provided me in development and test environments the ability and flexibility to nicely solve various scenarios such as unit testing, integration testing, seeding to a known state, etc.

**Comment by kmalakoff** [comment]
@gregoryyoung I recently did a hackathon and not having drop database was a big pain when demo time came. We set up a room where people would visit each hackathon entry, we would demo them, and then they could vote. I wanted to reset to a specific state with each demo, but needed other workarounds to reset the demo. 

Also, as we were developing, the eventstore kept having stale data so each developer needed to keep stopping their eventstore, deleting the data directory, and restarting their cluster of services.

I would love to see drop database in eventstore. 🤞

**Comment by jen20** [comment]
Hi @kmalakoff! I don't think we'll ever implement a Drop Database that works on the on-disk format - it's simply too risky to have that functionality exposed, and rather defeats the object of immutability.

If you're in an "in-memory" Event Store, perhaps a restart function which could be invoked via the client API would be sufficient?

**Comment by kmalakoff** [comment]
Hi @jen20. Sure, a restart for in-memory via client API could work. I could use that from one DOcker container to another.

An acceptance criteria on this would be to know when the event store has completed its resetting and is ready to use again since end of reset would trigger the next round of tests.

**Comment by jageall** [comment]
The in memory system uses a virtual file system and suffers the same issues as the file based system. This won't get implemented
