### ISSUE TITLE
Sign assemblies with strong name

### ISSUE THREAD

**Issue by Wiesenwischer** [EventStore/EventStore#1337]
It would be nice if the assemblies could be signed with a strong name (especially the ClientAPI assembly) It is one requierement i have to use GetEventStore and it would be nice not to be forced to build them on my own, but be able to use them as they are from nuget.

**Comment by simendsjo** [comment]
We just got bit by this. Without a strong name, we cannot reference this from a strong named assembly. Without a strong name, it's not possible to create binding redirects. If you thus have several libraries built with different versions of a dependency, you cannot use both in the same project.

For example:
- E = EventStore.ClientAPI
- A is built with E 1.0, requires >= 1.0
- B is built with E 1.1, requires >= 1.0
- E is currently at 1.2

You cannot use both A and B in your project as it's not possible to add an assembly redirect for E.
It's not possible to use E 1.2 with either libraries. You have to use A and E 1.0, B with E 1.1 or only E 1.2. No other combination is possible.

Not adding a strong name to EventStore will hamper adoption as you cannot use any extensions in other libraries unless all stars align and everything is built with using the same assemblies.

It's dll-hell without assembly redirects.

**Comment by oskardudycz** [comment]
@jageall, do we plan to support that in the future?

**Comment by alexeyzimarev** [comment]
@oskardudycz anyway it's for the client. Also, binding redirects are not a thing with .NET Core and .NET 5+, so I am not sure how relevant it is.

**Comment by oskardudycz** [comment]
I was more referring to if we're planning to sign .NET client packages in the future, in general.

**Comment by ylorph** [comment]
closing as this is no longer recommended : 
https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md
