### ISSUE TITLE
Use of fromStreamsMatching selector in a projection throws an error

### ISSUE THREAD

**Issue by RyanMelenaNoesis** [EventStore/EventStore#1342]
Use of the fromStreamsMatching selector in a projection returns the error 'catalogStream is not supported in the projections mode' and puts the projection into the faulted state.

**Comment by hayley-jean** [comment]
Currently, `fromStreamsMatching` can only be used in a OneTime projection.

**Comment by pblachut** [comment]
Is there any plan for the nearest releases to enable it also for continous projections?
