### ISSUE TITLE
Replace NLog with Serilog

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#1352]
Upgrading NLog will also do since they have with 4.5 provided structured logging. This is so that tools like https://getseq.net/ can be used.

**Comment by SeanFarrow** [comment]
Hi,

I'm potentially interested in taking this on, do we want ot do this in both the server/client?

**Comment by gregoryyoung** [comment]
The client is less important but ideally yes.

**Comment by SeanFarrow** [comment]
Ok, I’m happy to take this.
What branch should I use as my base?
Cheers
Sean.

**Comment by hayley-jean** [comment]
Thanks @SeanFarrow!
The current dev branch is `release-v4.1.1`, you can use this as a base

**Comment by SeanFarrow** [comment]
Should we split the logging in to different packages? I ask given that Serilog splits it’s sinks, so if we leave things as-is, it would mean taking dependencies on several sinks. I can imagine extensions on ConnectionSettingsBuilder.
Or should we just have a UseLogger method on ConnectionSettings that takes a serilog logger, leaving the creation of the logger to the user. This is what most libraries do.

**Comment by bartelink** [comment]
Solely wrt the Client, my personal views if this was greenfield would be:
+1 for using Serilog (but not coupling to any Sinks) in the client (layout of packages and general project health is good, I've used it to good effect in low dependency library in this space)
-1 for coupling to NLog (more likely to cause trouble in real world code bases).

However I would point out that this does bring diamond dependencies into play; unless there are going to be significant shifts in terms of the logging being semantic in nature (which I'd argue is a pretty big breaking change and should hence wait), it's hard to see the win from including a shim or rebasing on Serilog's `ILogger` being enough of a gain to warrant taking the dependency with all the attendant diamond dependency fun one brings to the world as a result.

It's also worth bearing https://github.com/damianh/LibLog/ in mind in this space.

On balance given all the considerations and codebases I'm aware of, I find I have to point out that given the widespread set of context within which the client will find itself used  in practice, either coupling to a logging or substantially revising a public logging API is bad news. For me an ideal logging interface would fulfill the following:
- allow me to wire it to Serilog easily (expose an interface in the client that's close enough, and then add example, wiki article or even a link to a gist)
- no compromise one's ability to continue to provide similar output to what one already has in place (i.e. breaking ILogger and or it's main message layouts would cause lots of busywork around the world ;) )

**Comment by bartelink** [comment]
See also https://github.com/svenschelfaut/EventStore.SerilogAdapter

**Comment by bartelink** [comment]
Another thing to bear in mind in this space is the tradeoffs between having an `EnableVerboseLogging` config switch vs an IsDebugEnabled on the external `ILogger` (as most loggers offer) - again this would potentially simplify the config DSL (with the proviso that that's potentially breaking in a pretty important area)

**Comment by SeanFarrow** [comment]
Hi,

Relooking at this, I'm thinking it would be better to use Microsoft.Extensions.Logging as this would give the widest log framework support and allow us to keep the API the same.

Are there any plans to upgrade the .net framework used to 4.6.1/4.6.2? This would allow us to use .net standard 2.0? if not, we can use the .net standard 1.x versions of these packages, but when the .net framework changes and the packages are upgraded, there may be breaking changes in terms of the logging API.

What are peoples thoughts?

**Comment by shaan1337** [comment]
Structured logging has been introduced as from version 5.
