### ISSUE TITLE
JS projections get corrupted data from binary events

### ISSUE THREAD

**Issue by aikoven** [EventStore/EventStore#1353]
I have a binary event that looks like this (bytes):
```
255,255,255,255,1,1,0,0,0,0,34,58,58,...
```
When I try to process it inside Projection, `eventEnvelope.bodyRaw` is a string with following char codes:
```
65533,65533,65533,65533,1,1
```
The body seems to be trimmed to the first zero byte. The first four bytes are not encoded correctly as well.

JavaScript strings are utf-8, so the code unit is 16 bits wide, it would be natural to pack two bytes to each char. Otherwise, I'd expect all chars to be ascii.

I use the following function to get char codes:
```js
function strtoa(str) {
    const a = [];
    
    for (let i = 0; i < str.length; i++)
        a.push(str.charCodeAt(i))
        
    return a;
}
```

**Comment by jageall** [comment]
Closing for now as no further issues have been raised with this
