### ISSUE TITLE
Configuration option to write pid file

### ISSUE THREAD

**Issue by firehooper** [EventStore/EventStore#1376]
A nice to have for monitoring would be a configuration option to write a parent pid file to a specified location (e.g. /var/run/eventstore.pid )

**Comment by bsmaldon** [comment]
I can't speak for windows but in linux this can be done at the service level. Unluckily for me I'm stuck in the stone age using Upstart on Ubuntu 1404 but I still got it working using an upstart configuration file like this
```
start on runlevel [2345]

setgid eventstore
setuid eventstore

stop on shutdown

limit nofile 16384 32768
respawn

script
    echo $$ > /var/run/eventstore/eventstore-XXX.pid
    exec /usr/bin/eventstored --config=/etc/eventstore/XXX-eventstore.conf
end script

pre-stop script
    rm /var/run/eventstore/eventstore-XXX.pid
end script
```
I think there will probably be a more bulletproof way to do it in system d too.

I'm not really sure how to go about building and testing from scratch nor what operating systems you want to target so I can't put together a pull request unfortunately.
