### ISSUE TITLE
Enable projections on slave UI

### ISSUE THREAD

**Issue by mlouage** [EventStore/EventStore#1377]
Hello,
I have an empty cluster with 3 nodes. When I try to enable the projections in the UI, it fails with message:
$by_category: null, $by_event_type: null, $stream_by_category: null, $streams: null
I was logged in on the UI of a slave node.

Is it so that enabling projections only works on the master node? By chance I logged in on another which happened to be the master and then it succeeded.

**Comment by avish0694** [comment]
@mlouage, You should now be able to enable projections from slave node UI. Thanks.
