### ISSUE TITLE
 Failed to start Event Store for Ubuntu VM Scale Set

### ISSUE THREAD

**Issue by arj060892** [EventStore/EventStore#1378]
I'm trying to configure Event Store on my Azure VM [Ubuntu] via the following [shell script](https://raw.githubusercontent.com/arj060892/AzureExt/master/Framework%20Installation/eventstoreinit.sh).
Every thing gets installed sucessfully but when i try to check the service status via 
_**sudo systemctl status eventstore**_
I get following error 
**_eventstore.service: Start request repeated too quickly.
systemd[1]: Failed to start Event Store Open Source._**

Detailed screenshot is attached
![error](https://user-images.githubusercontent.com/19621934/28874208-789f6a8c-77ae-11e7-9f40-5fdaf9f84423.png)

Also please let me know apart from these changes is their any thing else needs to be configured , i have opened the ports : 2113 & 1113 from my Network Security Group

Thank you

**Comment by pgermishuys** [comment]
Your external or internal http prefixes are incorrect.
Your prefixes should end with a `/`
e.g.
```
ExtHttpPrefixes: http://*:2113/
```

**Comment by jen20** [comment]
More generally - the service restarting too quickly means there is some kind of configuration - it starts, fails and the systemd supervisor restarts it up to a limit which is being reached in this case. The `journald` output contains the message which allowed @pgermishuys to diagnose this.

**Comment by arj060892** [comment]
Thank you @jen20  for the explanation.
I have made the change stated by @pgermishuys and the status is active and running now but if i'm trying to access the EventStore outside my VM with  "http://IPofVM:2113" , browser can't reach the server is their anything else that i have to take in consideration

**Comment by hayley-jean** [comment]
What http prefixes are you using? The one @pgermishuys used as an example makes use of a wild card, configuring Event Store's http listener to service any request on that port.

**Comment by jen20** [comment]
@arj060892 Are your running behind a load balancer?

**Comment by arj060892** [comment]
@jen20 yes i'm using a load balancer in the  front , I'm trying to implement IaC on Azure from our deployment pipe line , so i have to automate all the configuration and connection opening from the script or ARM templates .
@hayley-jean following are the prefixes
**_IntHttpPrefixes: http://*:2112/
ExtHttpPrefixes: http://*:2113/_**

**Comment by jen20** [comment]
@arj060892 Can you describe your network configuration - IP addresses, Virtual Networks, Availability Zones etc

**Comment by arj060892** [comment]
@jen20 [path ](https://raw.githubusercontent.com/arj060892/ARMLinuxVMSSwithEventStore/master/LinuxVirtualMachineScaleSet.json) to my ARM template which contains all the required details

**Comment by shaan1337** [comment]
@arj060892 hello, please note that we're closing this issue since it's a bit old and related to your specific configuration. please feel free to reopen if issue is still persisting.
