### ISSUE TITLE
Multiple Non Clustered EventStores

### ISSUE THREAD

**Issue by houseme-brandon** [EventStore/EventStore#1384]
Hi, I am trying to run 5 single node EventStores on a single VM
Below is the config I am using for one node:
```
---
Log: "/home/admin/ES/"
IntHttpPort: 2118
ExtHttpPort: 2118
IntTcpPort: 1118
ExtTcpPort: 1118
ExtHttpPrefixes: http://*:2118
ExtIp: 10.0.0.4
AdminOnExt: True
AddInterfacePrefixes: False
DisableHTTPCaching: True
MemDb: True
---
```
I am running 
```
ES VERSION:               4.0.1.4 (HEAD/d5e09181aa4c6bb43cad56e7c15400abfcd8cb44, Fri, 4 Aug 2017 15:43:48 +0200)
[83057,01,09:01:20.743] OS:                       Linux (Unix 4.4.0.87)
```

I get the following error:
```
[83250,01,09:06:27.659] Quorum size set to 1
[83250,01,09:06:27.673] Cannot find plugins path: plugins
[83250,01,09:06:27.728] INSTANCE ID:              c51d05bd-c107-406b-b0bd-47ca4d7eb7e4
[83250,01,09:06:27.729] DATABASE:                 /tmp/EmbeddedEventStore/2017-08-10_09.06.27.662011-EmbeddedNode
[83250,01,09:06:27.729] WRITER CHECKPOINT:        0 (0x0)
[83250,01,09:06:27.729] CHASER CHECKPOINT:        0 (0x0)
[83250,01,09:06:27.729] EPOCH CHECKPOINT:         -1 (0xFFFFFFFFFFFFFFFF)
[83250,01,09:06:27.729] TRUNCATE CHECKPOINT:      -1 (0xFFFFFFFFFFFFFFFF)
[83250,01,09:06:27.895] MessageHierarchy initialization took 00:00:00.1280001.
[83250,01,09:06:27.994] Unhandled exception while starting application:
No path specified.
[83250,01,09:06:28.001] No path specified.
No path specified.
```

I am not sure what path is not specified. I am starting the server using the following:
`#eventstored -Config config.yml`

I would appreciate any help regarding what I am doing wrong. For the other nodes I was planning on changing the ports specified in the config above. Is this a feasible approach or is there something else I need to be doing?

**Comment by pgermishuys** [comment]
Please can you provide us with the startup log which will provide us with the effective configuration?

**Comment by houseme-brandon** [comment]
`[83250,01,09:06:27.620]
ES VERSION:               4.0.1.4 (HEAD/d5e09181aa4c6bb43cad56e7c15400abfcd8cb44, Fri, 4 Aug 2017 15:43:48 +0200)
[83250,01,09:06:27.642] OS:                       Linux (Unix 4.4.0.87)
[83250,01,09:06:27.646] RUNTIME:                  4.6.2 (Stable 4.6.2.16/ac9e222) (64-bit)
[83250,01,09:06:27.646] GC:                       2 GENERATIONS
[83250,01,09:06:27.646] LOGS:                     /home/admin/ES/
[83250,01,09:06:27.653] MODIFIED OPTIONS:

        CONFIG:                   ES1.yml (Command Line)
        LOG:                      /home/admin/ES/ (Config File)
        INT HTTP PORT:            2118 (Config File)
        EXT HTTP PORT:            2118 (Config File)
        INT TCP PORT:             1118 (Config File)
        EXT TCP PORT:             1118 (Config File)
        EXT HTTP PREFIXES:        http://*:2118 (Config File)
        EXT IP:                   10.0.0.4 (Config File)
        ADMIN ON EXT:             True (Config File)
        ADD INTERFACE PREFIXES:   False (Config File)
        DISABLE HTTP CACHING:     True (Config File)
        MEM DB:                   True (Config File)

DEFAULT OPTIONS:

        HELP:                     False (<DEFAULT>)
        VERSION:                  False (<DEFAULT>)
        DEFINES:                  <empty> (<DEFAULT>)
        WHAT IF:                  False (<DEFAULT>)
        START STANDARD PROJECTIONS: False (<DEFAULT>)
        MONO MIN THREADPOOL SIZE: 10 (<DEFAULT>)
        INT IP:                   127.0.0.1 (<DEFAULT>)
        INT SECURE TCP PORT:      0 (<DEFAULT>)
        EXT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        EXT SECURE TCP PORT:      0 (<DEFAULT>)
        EXT IP ADVERTISE AS:      <empty> (<DEFAULT>)
        EXT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        EXT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT IP ADVERTISE AS:      <empty> (<DEFAULT>)
        INT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT TCP HEARTBEAT TIMEOUT: 700 (<DEFAULT>)
        EXT TCP HEARTBEAT TIMEOUT: 1000 (<DEFAULT>)
        INT TCP HEARTBEAT INTERVAL: 700 (<DEFAULT>)
        EXT TCP HEARTBEAT INTERVAL: 2000 (<DEFAULT>)
        GOSSIP ON SINGLE NODE:    False (<DEFAULT>)
        FORCE:                    False (<DEFAULT>)
        CLUSTER SIZE:             1 (<DEFAULT>)
        NODE PRIORITY:            0 (<DEFAULT>)
        MIN FLUSH DELAY MS:       2 (<DEFAULT>)
        COMMIT COUNT:             -1 (<DEFAULT>)
        PREPARE COUNT:            -1 (<DEFAULT>)
        STATS ON EXT:             True (<DEFAULT>)
        GOSSIP ON EXT:            True (<DEFAULT>)
        DISABLE SCAVENGE MERGING: False (<DEFAULT>)
        SCAVENGE HISTORY MAX AGE: 30 (<DEFAULT>)
        DISCOVER VIA DNS:         True (<DEFAULT>)
        CLUSTER DNS:              fake.dns (<DEFAULT>)
        CLUSTER GOSSIP PORT:      30777 (<DEFAULT>)
        GOSSIP SEED:              <empty> (<DEFAULT>)
        STATS PERIOD SEC:         30 (<DEFAULT>)
        CACHED CHUNKS:            -1 (<DEFAULT>)
        READER THREADS COUNT:     4 (<DEFAULT>)
        CHUNKS CACHE SIZE:        536871424 (<DEFAULT>)
        MAX MEM TABLE SIZE:       1000000 (<DEFAULT>)
        HASH COLLISION READ LIMIT: 100 (<DEFAULT>)
        DB:                       /var/lib/eventstore (<DEFAULT>)
        INDEX:                    <empty> (<DEFAULT>)
        SKIP DB VERIFY:           False (<DEFAULT>)
        WRITE THROUGH:            False (<DEFAULT>)
        UNBUFFERED:               False (<DEFAULT>)
        RUN PROJECTIONS:          None (<DEFAULT>)
        PROJECTION THREADS:       3 (<DEFAULT>)
        WORKER THREADS:           5 (<DEFAULT>)
        INT HTTP PREFIXES:        <empty> (<DEFAULT>)
        ENABLE TRUSTED AUTH:      False (<DEFAULT>)
        CERTIFICATE STORE LOCATION: <empty> (<DEFAULT>)
        CERTIFICATE STORE NAME:   <empty> (<DEFAULT>)
        CERTIFICATE SUBJECT NAME: <empty> (<DEFAULT>)
        CERTIFICATE THUMBPRINT:   <empty> (<DEFAULT>)
        CERTIFICATE FILE:         <empty> (<DEFAULT>)
        CERTIFICATE PASSWORD:     <empty> (<DEFAULT>)
        USE INTERNAL SSL:         False (<DEFAULT>)
        DISABLE INSECURE TCP:     False (<DEFAULT>)
        SSL TARGET HOST:          n/a (<DEFAULT>)
        SSL VALIDATE SERVER:      True (<DEFAULT>)
        AUTHENTICATION TYPE:      internal (<DEFAULT>)
        AUTHENTICATION CONFIG:    <empty> (<DEFAULT>)
        PREPARE TIMEOUT MS:       2000 (<DEFAULT>)
        COMMIT TIMEOUT MS:        2000 (<DEFAULT>)
        UNSAFE DISABLE FLUSH TO DISK: False (<DEFAULT>)
        BETTER ORDERING:          False (<DEFAULT>)
        UNSAFE IGNORE HARD DELETE: False (<DEFAULT>)
        INDEX CACHE DEPTH:        16 (<DEFAULT>)
        GOSSIP INTERVAL MS:       1000 (<DEFAULT>)
        GOSSIP ALLOWED DIFFERENCE MS: 60000 (<DEFAULT>)
        GOSSIP TIMEOUT MS:        500 (<DEFAULT>)
        ENABLE HISTOGRAMS:        False (<DEFAULT>)
        LOG HTTP REQUESTS:        False (<DEFAULT>)
        ALWAYS KEEP SCAVENGED:    False (<DEFAULT>)

[83250,01,09:06:27.659] Quorum size set to 1
[83250,01,09:06:27.673] Cannot find plugins path: plugins
[83250,01,09:06:27.728] INSTANCE ID:              c51d05bd-c107-406b-b0bd-47ca4d7eb7e4
[83250,01,09:06:27.729] DATABASE:                 /tmp/EmbeddedEventStore/2017-08-10_09.06.27.662011-EmbeddedNode
[83250,01,09:06:27.729] WRITER CHECKPOINT:        0 (0x0)
[83250,01,09:06:27.729] CHASER CHECKPOINT:        0 (0x0)
[83250,01,09:06:27.729] EPOCH CHECKPOINT:         -1 (0xFFFFFFFFFFFFFFFF)
[83250,01,09:06:27.729] TRUNCATE CHECKPOINT:      -1 (0xFFFFFFFFFFFFFFFF)
[83250,01,09:06:27.895] MessageHierarchy initialization took 00:00:00.1280001.
[83250,01,09:06:27.994] Unhandled exception while starting application:
No path specified.
[83250,01,09:06:28.001] No path specified.
No path specified.
`

**Comment by houseme-brandon** [comment]
And here are the log files..
[Logs.zip](https://github.com/EventStore/EventStore/files/1214526/Logs.zip)

**Comment by pgermishuys** [comment]
What distro?

**Comment by houseme-brandon** [comment]
I am using Ubuntu 16.04 from Azure

**Comment by pgermishuys** [comment]
And how did you install Event Store?

**Comment by houseme-brandon** [comment]
I followed the package cloud instructions and did:
```
$curl -s https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/script.deb.sh | sudo bash
$sudo apt install eventstore-oss
```

**Comment by pgermishuys** [comment]
1. Your http prefixes is missing a trailing slash
e.g.
`ExtHttpPrefixes: http://*:2118` vs `ExtHttpPrefixes: http://*:2118/`

**Comment by pgermishuys** [comment]
As an aside, specifying the internal tcp and http ports in a single node is redundant as those as the relevant services don't start when the cluster size is less than 2. However, if you do set the cluster size to anything greater than 1, the bindings will fail as it will report that the port is already in use. You need 4 distinct ports.

Going to close this issue for now, please don't hesitate to reopen if you require any further assistance relating to this particular issue.

**Comment by houseme-brandon** [comment]
It starts now. Thanks so so much!

**Comment by puco** [comment]
What about improving the log message or fixing the parsing instead of just closing the issue?
