### ISSUE TITLE
ClientAPI EmptyStream Value in Documentation Does Not Match Value

### ISSUE THREAD

**Issue by seancarroll** [EventStore/EventStore#1385]
Documentation within the remark states 

> ExpectedVersion.EmptyStream (0) says the stream should exist but be empty when doing the write.

However code has

`public const int EmptyStream = -1;`

**Comment by gregoryyoung** [comment]
Can you put this on the documentation repository. Also expected version 0 and expected version -1 are synonyms for each other.

If I expect version 0 that means there are no previous events. If I expect empty stream I expect no previous events. Both mean the same thing.

**Comment by seancarroll** [comment]
Moved to EventStore/docs.geteventstore.com#243
