### ISSUE TITLE
EventStore does not listen on --int-http-port in a single node cluster

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#1390]
**Version:** release-v4.0.2 from git (Pulled this morning)
**Reproduction steps:**
./EventStore/bin/clusternode/EventStore.ClusterNode.exe --int-http-port=2113 --ext-http-port=2114

EventStore will listen only on port **2114**.

**Logs show only:**
Starting HTTP server on [http://127.0.0.1:2114/,http://localhost:2114/]

However if you add **--cluster-size** parameter with value **greater than 1**, it listens on both ports:
./EventStore/bin/clusternode/EventStore.ClusterNode.exe --int-http-port=2113 --ext-http-port=2114 --cluster-size=2

**Now, logs show:**
Starting HTTP server on [http://127.0.0.1:2114/,http://localhost:2114/]
Starting HTTP server on [http://127.0.0.1:2113/,http://localhost:2113/]...

**Comment by gregoryyoung** [comment]
Why would it?

**Comment by pgermishuys** [comment]
This is not an issue and expected behaviour.

**Comment by gregoryyoung** [comment]
I can see a use case for this though. Run admin on internal only.

**Comment by jageall** [comment]
Closing for now, current behaviour is expected and no one external appears to have asked for this
