### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by PaulGrimshaw** [EventStore/EventStore#1405]
We are getting this error on our production eventstore all of a sudden.  We have changed the file system limits (ubuntu) and verified these are applied for all users.  However the eventstore process refuses to use this limit, and uses 1024/4096 soft / hard limits.

We urgently need to up this limit. The eventstore software appears to be setting it somewhere when the service starts.  How can we override this?  We are using the event.conf, so ideally the correct parameter for this would be useful.

Any other suggestions?  This is causing a complete system outage at the moment.

**Comment by gregoryyoung** [comment]
EventStore does not control file limits in any way shape or form, they are completely controlled by the OS.

**Comment by PaulGrimshaw** [comment]
Ok, after battling with this on and off for a few days, found the solution, hopefully it can help others:

First, check the limits on the running process:
- Run `top` to get handle of eventstore process
- Run `cat /proc/[processid]/limits`

This example ups the limit to `64,000` from the default `1,024`.

- Set the limits globally by adding the following lines to `/etc/security/limits.conf`:
```
*              hard    nofile          64000
*              soft    nofile          64000
root           hard    nofile          64000
root           soft    nofile          64000
```

- Add the following line to  `/etc/pam.d/common-session`:
`session required        pam_limits.so`

- Add the following line to `/etc/pam.d/common-session-noninteractive`:
`session required        pam_limits.so`

- Now, **specific to the eventstore**.  Add the following line to `/etc/init/eventstore.conf`:
`limit nofile 64000 64000` (I added this line second from last, prior to `exec /usr/bin/eventstored`)

Reboot the server, and check the limits have been applied to the running process by following the instructions at the top.
