### ISSUE TITLE
Multiple projections emitting to the same stream detected. Internal stream edition.

### ISSUE THREAD

**Issue by AlekseiOhotnik** [EventStore/EventStore#1411]
This one unlike its output stream counterpart is conflicting on internal '$projections-testproj-order stream'.

Multiple projections emitting to the same stream detected. Stream: '$projections-testproj-order'. Last event projection: '40'. Emitting projection: '48'

Projection name "testproj".

fromStreams(
    '$ce-testcat1',
    '$ce-testcat2',
    '$ce-testcat3',
    '$ce-testcat4')
.when({
        $any : function(state, evnt)
        {
            linkTo("testproj", evnt);
        }
})

Continuous type, all emit/track options on.

1) Create projection with any name
2) Linkto some events to some output stream
3) Delete projection and output stream
4) Go back to point 1 and use same name

Our setup is a 3-node cluster running 4.0.2.2. Restart doesn't help. This is unrecoverable unless new projection name is used.

Should those internal streams have survived deletion of projection?

**Comment by hayley-jean** [comment]
Thank you for reporting this. This does appear to be an issue - the `$projections-{projectionName}-order` stream needs to be deleted when deleting a projection and its emitted streams.

As a workaround, you can soft delete the order stream after deleting the projection.

**Comment by regularcoder** [comment]
I'm interested in taking a crack at this.

**Comment by hayley-jean** [comment]
@regularcoder You are more than welcome to 👍 

To get you started, the deletion of a projection's additional streams starts off [here](https://github.com/EventStore/EventStore/blob/release-v4.0.3/src/EventStore.Projections.Core/Services/Management/ManagedProjection.cs#L489)
Let us know if you need any help or run into any issues

**Comment by regularcoder** [comment]
@hayley-jean thank you for the pointer. I could replicate the issue locally and have a couple of questions:

1) Should $projections-....-order be deleted only if the user has opted to delete emitted streams and not otherwise?

2) Should $projections-....-partitions be deleted as well when user opts to delete emitted streams? I have yet to confirm but I think this internal stream might not get deleted either.

**Comment by hayley-jean** [comment]
You can delete both of those streams when a projection is deleted.
Neither of those streams really server any purpose after the projection is gone.

**Comment by regularcoder** [comment]
@hayley-jean I submitted pull request #1418 to delete the projection-...-order stream.

**Comment by Faq** [comment]
This can be closed as #1418 was merged.
