### ISSUE TITLE
Resetting system projections causes projections with multi stream selectors to brick.

### ISSUE THREAD

**Issue by AlekseiOhotnik** [EventStore/EventStore#1412]
After resetting all system projections while trying to fight some other issue I discovered that all projections having multiple streams defined in selectors such as 'fromStreams', 'fromCategories' stopped working. Projections will freeze at positions -1 for all streams (if new or reset). No errors are displayed on admin UI when starting/stopping them.
Worth noting that they do work if only one stream is specified in selectors. All system projections are completed 100% during occurrence of this problem. Restarting cluster didn't help which makes this issue unrecoverable.
Version used 4.0.2.2, 3 node cluster.

**Comment by hayley-jean** [comment]
This issue appears to be the same as the one reported here: https://github.com/EventStore/EventStore/issues/1333

If the source streams for a multi-stream projection have been truncated or otherwise had events removed, the projection will get stuck.

**Comment by jasonmitchell** [comment]
We have also seen something similar on 4.0.1. 

Would switching to `fromAll` rather than `fromStreams` to possibly work around it?  It seems to make a difference to our stuck projection.

**Comment by shaan1337** [comment]
@AlekseiOhotnik Thanks for reporting this. Would you mind sending me your EventStore logs to shaan [at] geteventstore.com ? This will help identify the root cause faster

**Comment by shaan1337** [comment]
@jasonmitchell Yes, I've done some tests and it seems that fromAll() is not affected since $all keeps a pointer to the stream events. The pointer is not deleted when an event is deleted.
