### ISSUE TITLE
Hard delete one steam of many in category causes LinkTo to emit nothing into target stream.

### ISSUE THREAD

**Issue by AlekseiOhotnik** [EventStore/EventStore#1413]
Hard deleted a stream in a category. Projection that was merging some categories started producing empty stream (after reset or if new). If category that has hard deleted steam is removed from multi stream selector fixes this problem and outputs links properly. It seems that selecting only affected category stream also works fine, its the combination with others is when the problem occurs. Cluster restart has no effect. 

fromCategory(
    'category1',
    'category2', <--- hard deleted stream in category, projection breaks
    'category3',
    'category4')
.when({
        $any : function(state, evnt)
        {
            linkTo("output_stream)", evnt);
        }
})

Works fine when:

fromCategory(
    'category1',
    'category3',
    'category4')
or 
fromCategory(
    'category2')

Version 4.0.2.2, 3 node cluster.

**Comment by AlekseiOhotnik** [comment]
Deals with aged events instead of deleted streams, still could be same issue #1333

**Comment by shaan1337** [comment]
@AlekseiOhotnik can you please confirm if in the case above, your streams contained events with $maxAge?

**Comment by shaan1337** [comment]
@AlekseiOhotnik kindly also confirm if you have done a soft or hard delete:
soft delete: curl -v -X DELETE http://127.0.0.1:2113/streams/stream1
hard delete: curl -v -X DELETE http://127.0.0.1:2113/streams/stream1 -H "ES-HardDelete:true"

I can reproduce the issue with a soft delete but not with a hard delete.

**Comment by AlekseiOhotnik** [comment]
I believe it was soft delete followed by hard delete, cause I realized
there was no header option set first time. Also did scavenge after that.
