### ISSUE TITLE
Projection incomplete - buffer empty but more events to process

### ISSUE THREAD

**Issue by jwalls89** [EventStore/EventStore#1416]
Hi,

I have an issue with a custom projection.  I suspect the projection itself has a performance issue (which I'm investigating separately) but it the event store behaviour in this scenario I'm seeing is that is concerning me.  The behaviour is this

- Start projection
- Put in 10000 events that will go through the projection
- Projection starts processing
- Buffered events go up till  circa 5000 events
- Projection state changes from Running to Running/Paused
- Buffered events get processed till buffered event 0
- Buffered events stay at 0 (even though there are more that haven't gone through the projection yet) and Projection stays at <100%.  It stays in this state for ever unless the projection is stopped and started again in which case the steps repeat.

I obviously have an issue with my projection performance but I would expect EventStore to continue replenishing the buffer without having to do a projection restart.  I'm assuming this is a bug?  Also is there a way to tune the max buffer size for a custom projection?

Using Event Store 4.0.1 and projection is using fromStreams, partitions and emitting events

**Comment by pgermishuys** [comment]
@jwalls89 
1. Is this in a test environment (could we ask you to try with Event Store 4.0.2)?
2. Do you have logs? If the logs contains sensitive information, please don't hesitate to forward them to pieter at geteventstore)
3. Do you have a reproduction?

**Comment by jwalls89** [comment]
Hi @pgermishuys.  Upgrade to 4.0.2.2 has solved the buffering issue.  Buffer is now refilling.  Thanks

**Comment by pgermishuys** [comment]
No worries @jwalls89. Thanks for raising the issue and please don't hesitate to reach out to us in the future.
