### ISSUE TITLE
Feature request: Ability to retrieve multiple partition states in a single call.

### ISSUE THREAD

**Issue by cchmbrln** [EventStore/EventStore#1419]
We have a use-case that we want to use projection partition states to validate some requests. We're ok with the eventual consistency of the projection, but would like to be able to batch up the fetches of the state by partition.

This may be a good feature on the server-side. For example:

```
GET /projections/{name}/state?partitions={partition1},{partition2},{partition3}

Response:

{
    "{partition1}": {
        ...state
    },
    "{partition2}": {
        ...state
    },
    "{partition3}": {
        ...state
    }
}
```

This'd cut down (for our use-case anyway) the number of requests to eventstore for partitions.

**Comment by RemcoBlok** [comment]
+1, but how is this going to work for retrieving the state for a 1000 partitions in a single call?

**Comment by jageall** [comment]
Closing for now as nobody else has requested this in 2 years
