### ISSUE TITLE
Feature Request: Add retry status to persistent subscriptions

### ISSUE THREAD

**Issue by jageall** [EventStore/EventStore#1428]
There are a number of scenarios I have come across now where it would be extremely useful to know if the event the subscriber is receiving is being retried or not.  Some are easy enough to guess, but some protocols require that a flag is set if a message is possibly being sent a second time. 

It would be possible to do this by writing to a secondary store before and after transmission, but the persistent subscription on the server already has this information, and the secondary store opens up additional failure possibilities.

**Comment by gregoryyoung** [comment]
I can see the use, I will look at this today or tomorrow.
