### ISSUE TITLE
Client has a 64 MB frame limit, server does not

### ISSUE THREAD

**Issue by Yspadadden** [EventStore/EventStore#1437]
When parsing frames the client enforces a frame length of [0, 64MB]. The server does not seem to enforce any frame length. This means the server can send perfectly valid frames to the client that the client will reject. 

Here's an example application that shows this behaviour: 
[EventStoreTooLongBufferTest.zip](https://github.com/EventStore/EventStore/files/1324312/EventStoreTooLongBufferTest.zip)

I usually use the java client from [esjc](https://github.com/msemys/esjc) so the .net client is new to me. I just wanted to make sure it behaves in a similar way as the esjc client. I think it does, as reading the batch of events fails as expected. The underlying reason for the failure seems to be missing, however, which would make it impossible to handle this kind of error using the .net client at all. 

As far as I can tell from studying [LengthPrefixMessageFramer.cs](https://github.com/EventStore/EventStore/blob/ec8ec115d14ca59ec3677209fb81942ce81d314b/src/EventStore.Transport.Tcp/Framing/LengthPrefixMessageFramer.cs), only the client side uses the _maxPackageSize. 

Questions: 
1. Why is there a limit on the client side at all, if the server side doesn't have one? 
2. If the limit on the client side is desirable, why does the server not enforce the same limit? 
3. What is the proposed way of handling this kind of error on the client side?

**Comment by jageall** [comment]
This was fixed a while ago
