### ISSUE TITLE
Projection are failing/stalling

### ISSUE THREAD

**Issue by regis-leray** [EventStore/EventStore#1439]
We discover recently our server had some issue, some projection were failing both  **$by_category** and **$by_event_type** were faulted with this message

```
Failed to write events to $ce-healthcheck. Retry limit of 5 reached. Reason: CommitTimeout. Checkpoint: C:25146300306/P:25146300306.

Failed to write events to $et-EventStoreHealthChecked. Retry limit of 5 reached. Reason: CommitTimeout. Checkpoint: C:25170182852/P:25170182852.
```

### Projections

![screen shot 2017-09-22 at 10 54 50 am](https://user-images.githubusercontent.com/534387/30750465-9fe19f18-9f84-11e7-9866-4f934a9ff10e.png)

i endup by restarting the projection from the UI (stop/start) and it seems it was able the projections recovered

### setup

Current EventStore version: 4.0.2
It is running on Ubuntu 14.04 on top of docker 1.6.2

Host: 
```
Ubuntu 14.04.4 LTS
Linux ip-10-210-0-198 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Docker image: 
```
Ubuntu 14.04.3 LTS
Linux eventstore 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Here the logs of the server
[eventstore.log.tar.gz](https://github.com/EventStore/EventStore/files/1324867/eventstore.log.tar.gz)

The current machine is not on a SSD drive, a regular one !
I do think if we are stressing the database (io resources / memory) enough we can get some timeout issue. I remember with docker we can play with this settings. 

On the same machine we have bunch of database like kafka / 1x couchdb / 3x mongodb / 1x zookeeper / 1x elastic search / 1x GetEventstore. **only evenstore** is begin to be unresponsive.

Also on other notes on production we didnt see the problem, GetEventstore it is on is own machine. But we do think if we would stress the system, we will endup with projections faulted,we can play with docker settings to reproduce  this stress environnment locally
https://docs.docker.com/engine/admin/resource_constraints/

PS: we already opened a bug concerning this issue before some were fixed but it looks it came back agin
https://github.com/EventStore/EventStore/issues/1097
https://github.com/EventStore/EventStore/issues/1330

**Comment by pgermishuys** [comment]
@regis-leray, thanks for opening the issue. As with the previous issues where projections were silently failing, the issue you are facing now should be surfaced to the UI and the projection's should have a status of faulted and a message indicating as to why it faulted.

The projection's that faulted in this manner can be started again safely via the UI or by issuing an http POST request to /projection/{projection-name}/command/enable.

The reason the projection is faulting is because it exhausted the number of retries, which is 5. Previously projections would just silently continue retrying forever and in a lot of cases, never get past the retry and the projection would appear to be stuck.

1. How often is this happening?
2. What are your Event Store configuration settings?

**Comment by regis-leray** [comment]
1. How often is this happening?

it is random. But this week it appears two times.

2. What are your Event Store configuration settings?

/etc/config/evenstore

**Comment by pgermishuys** [comment]
@regis-leray, would you mind sharing your effective configuration? e.g. the contents of `/etc/config/eventstore`. If you don't want to share it on github, you are more than welcome to send it to us via email. (pieter at geteventstore)

**Comment by regis-leray** [comment]
@pgermishuys i share it :)

**Comment by regis-leray** [comment]
@pgermishuys the commit timeout could appear if the system is overloaded ?

**Comment by pgermishuys** [comment]
@regis-leray Commit Timeouts can occur for a number of reasons. Network related issues between nodes in a cluster or the storage chaser lagging behind trying to commit pending transactions etc.

Looking at what you are running on that box you might benefit from adjusting your `CommitTimeoutMs` to something higher than the default which is currently set to `2000`.

**Comment by Faq** [comment]
@regis-leray any feedback?

**Comment by regis-leray** [comment]
@Faq i didnt change the settings of the machine. since last time it didnt crash. There is something wrong for sure. But didnt have any other informations to share...

**Comment by regis-leray** [comment]
i m going to upgrade to eventstore 4.0.3 and also to upgrade ubuntu image 16.04 (latest). to have the latest kernel currently i have `3.19.0-32-generic` and eventstore supports 

```
Some known good versions of the Kernel are

3.13.0-54
3.13.0-63
3.16.0-39
3.19.0-20
3.19.0-64
3.19.0-66
>= 4.4.27
```

**Comment by shaan1337** [comment]
@regis-leray hello, please note that we're closing this issue since it's related to an old version of EventStore. if you're still experiencing the same problem with latest version of EventStore please feel free to reopen.
