### ISSUE TITLE
Question: How can I get a list of all categories in GetEventStore?

### ISSUE THREAD

**Issue by Narvalex** [EventStore/EventStore#1445]
Sorry if it is a stupid question. What I want is:

From streams like these:
- sales-sale102
- sales-sale103
- sales-sale104
- users-8989
- users-8990

Get somethig like this:
`[ "sales", "users"]`

I already asked this in [the Google Groups](https://groups.google.com/forum/#!topic/event-store/BkkBd_PTbJA) and even in [Stackoverflow](https://stackoverflow.com/questions/46406996/how-can-i-get-a-list-of-all-categories-in-geteventstore), but with no response.

**Comment by nissbran** [comment]
It is possible to write a transient projection (Query), or a regular projection in EventStore. This might be a good starting point: 
```
fromAll().
when({
    $init: function() {
        return {
            categories : []
        }
    },
    $any: function(s, e) {
        var category = e.streamId.split("-")[0];
        
        if (s.categories.includes(category))
            return;
        
        s.categories.push(category);
    }
})
```

**Comment by Narvalex** [comment]
I thought that thre is a built in thing like $ce-category stuff. But thanks @nissbran!

**Comment by Narvalex** [comment]
Would be faster to go 
`fromStream('$streams')`
instad of going 
`fromAll()`?

**Comment by nissbran** [comment]
That is faster. Good idea :)

**Comment by devcrafting** [comment]
Hi, I implemented the same projection, but having truncated events, these events do not have any streamId property. I can check if streamId is defined, but still if first event of all streams of a category have been truncated, I do not get the category in the projection.

I tried looking at event object for truncated events, everything is null or empty...but we can still see a Name (nothing else) when looking at $streams in the UI. Also, we can get the Name string with C# API, from ResolvedEvent.Event.Data. why is there nothing in parameters given to handle functions ?

Thanks for your feedbacks.

**Comment by devcrafting** [comment]
Hello, sorry I tried with `fromStream('$streams')`...it works with fromAll(). Still, I don't understand why there is some properties in events with fromAll and nothing with fromStream('$streams') ?
Also, looks like fromAll return only events from non system streams, right ? (a bit vague in doc "Selects events from the $allstream")
I would be happy to PR docs with answers :).
