### ISSUE TITLE
Projection stalled in Running and Running/StateLoaded states.

### ISSUE THREAD

**Issue by mscmorris** [EventStore/EventStore#1453]
**Eventstore 4.0.1.0**

We're getting intermittent failures of projections on our three machine cluster. The projections either say Running (100%), however haven't fully updated, or they're stuck in Running/StateLoaded. In either case, a restart of the cluster fixes the issue.

Here is is a log snapshot of the only odd entries we're seeing to the most recent failed projection...the commonality between the projections that are failing seems to be the use of 'linkTo'.

`/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.538 INFO  CoreProjectionCheckp] Failed to write events to stream $projections-billing-customer-partition-v1-order. Error: WrongExpectedVersion
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.538 INFO  ProcessingStrategySe] Projection 'billing-customer-partition-v1'(c04f50c2-2a45-4347-9c2e-35bd51be9fbb) restart has been requested due to: 'The '$projections-billing-customer-partition-v1-order' stream has been written to from the outside'
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.547 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.560 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.567 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.578 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.586 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.614 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.648 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.656 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.668 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.
/var/log/eventstore/2017-10-04/0.0.0.0-2114-cluster-node.log:[PID:29688:028 2017.10.04 14:38:59.691 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler 'Projection Core #2'.`

**Comment by hayley-jean** [comment]
Hi @mscmorris, what version of Event Store is this on?

**Comment by mscmorris** [comment]
Eventstore 4.0.1.0

**Comment by hayley-jean** [comment]
From the logs, it looks like you are running into the issue solved by #1303 
There have also been some fixes in version 4.0.3 around running projections in a cluster.

How easily reproducible is the issue? Would you be able to test on a later version to see if it is resolved?

**Comment by mscmorris** [comment]
It seems pretty intermittent right now but it's happening with enough frequency that I believe we can try upgrading and see if it goes away quickly.

**Comment by hayley-jean** [comment]
Hi @mscmorris, have you had a chance to test this with an upgrade?
