### ISSUE TITLE
Doc: Database Backup/restore not clear.

### ISSUE THREAD

**Issue by lktslionel** [EventStore/EventStore#1457]
Hi,
I'm trying to do the database backup process of eventstore. I read he [doc](https://eventstore.org/docs/server/4.0.0/database-backup/) and it is a bit confusing for me. 

So, I need to know if a got it right. Suppose, I'm running `evenstored` and the current content of my database in `/var/lib/eventstore` is : 
```
root@26901fb02290:/var/lib/eventstore# ls -al
total 32
drwxr-xr-x 3 eventstore eventstore      4096 oct.   9 17:42 .
drwxr-xr-x 1 root       root            4096 oct.   9 17:35 ..
-rw-r--r-- 1 root       root               8 oct.   9 17:42 chaser.chk
-rw-r--r-- 1 root       root       268439552 oct.   9 17:42 chunk-000000.000000
-rw-r--r-- 1 root       root               8 oct.   9 17:42 epoch.chk
drwxr-xr-x 2 root       root            4096 oct.   9 17:42 index
-rw-r--r-- 1 root       root               8 oct.   9 18:00 truncate.chk
-rw-r--r-- 1 root       root               8 oct.   9 17:42 writer.chk
```

The doc says that to backup database : 
```
# 1. Copy all *.chk files to the backup location (/backup/)
$: cp /var/lib/eventstore/*.chk /backup/

# 2. Copy the remaining files and directories to the backup location
$: cp -r /var/lib/eventstore/{chunk-000000.000000,index}
```

The doc says that to restore the database : 
```
# 1. Create a copy of chaser.chk and call it truncate.chk.
$: cp /backup/chaser.chk  /var/lib/eventstore/truncate.chk

# 2. Copy all files to the desired location.
$: cp /backup/*  /var/lib/eventstore/
```

It is what you meant in the doc ? 

Thanks in advance

**Comment by hayley-jean** [comment]
Hi @lktslionel that is almost entirely correct.

The only thing that should change is the way you are copying the chaser.chk to the truncate.chk. If you copy that to the backup location first and then restore all the files, the truncate.chk could get overwritten.

You could either copy chaser.chk to truncate.chk in the backup directory and then restore all files, which would change your last two lines to:

```
# 1. Create a copy of chaser.chk and call it truncate.chk.
$: cp /backup/chaser.chk  /backup/truncate.chk

# 2. Copy all files to the desired location.
$: cp /backup/*  /var/lib/eventstore/
```

Or you could copy them over the same way you are currently doing, but as the last step :

```
# 1. Copy all files to the desired location.
$: cp /backup/*  /var/lib/eventstore/

# 2. Copy chaser.chk over truncate.chk.
$: cp /backup/chaser.chk  /var/lib/eventstore/truncate.chk
```

What changes would make the backup/restore documentation clearer? Would a step-by-step example like the one you have here help?

**Comment by lktslionel** [comment]
Thanks for you help.
Yes a step-by-step example will be better. I could make a pull request if needed.
Let me know.

**Comment by hayley-jean** [comment]
A pull request is always appreciated, otherwise you could open an issue on the [docs](https://github.com/EventStore/docs.geteventstore.com) repository and we'll update it when we are able.

**Comment by tomazstrukeljdlabs** [comment]
I use these commands to do the backup:
```
rsync -a /data/eventstore/db/*.chk /backup/eventstore/db/
rsync -a /data/eventstore/db/index /backup/eventstore/db/
rsync -a /data/eventstore/db/*.0* /backup/eventstore/db/
```
Opened a Pull Request at https://github.com/EventStore/docs.geteventstore.com .

**Comment by ChrisChinchilla** [comment]
Looks like this was completed.
