### ISSUE TITLE
Add support for dotnet core (2.0)

### ISSUE THREAD

**Issue by m-jepson** [EventStore/EventStore#1458]
Please write a version of the library for use in dotnet core, preferably 1.x and 2.0, but just 2.0 would do.

**Comment by andrii-litvinov** [comment]
I am working on a proof of on concept project and simple use-case like read and write events work fine on Linux in .NET Core 2.0 application. Both regular and [NetCore](https://www.nuget.org/packages/EventStore.ClientAPI.NetCore/4.0.2-rc) clients. I would expect more advanced use-cases to work as well, but haven't tried yet.

**Comment by mattgi** [comment]
Are you referring to moving away from mono and on to Core 2.0 in its entirety or just the client library? I'd love to be able to just get EventStore up and running on a Mac using Core 2.0.

**Comment by andrii-litvinov** [comment]
@mattgi if the question was addressed to me, I am talking about client library only. I use ES inside Docker for development which runs on on Mono on Linux. Same cam be done on MacOS. For sure it would be great to have it ported .NET Core 2.0 and run it on bare metal. .NET Core 2.0 has wider API coverage and should be way easier to migrate server to it.

**Comment by m-jepson** [comment]
I'm mainly talking about the client library. The server we can run on any machine(s), and leave it at that. But we write most of our software in .Net Core nowadays and are looking into containerized deployment. Would be great if we could continue doing that when using EventStore in those applications.

**Comment by ryanstinson** [comment]
I am interested in the server components being migrated to .Net Core 2.0 as well. We are embedding ES in our microservices and would be able to move away from mono easier.

**Comment by mattgi** [comment]
https://www.nuget.org/packages/EventStore.ClientAPI.NetCore/ exists and is working well for me. To add via Nuget be sure to include `pre-release packages`, a rookie error I made initially. Via VS for Mac that looks like this:

<img width="420" alt="screenshot 2017-10-21 09 59 36" src="https://user-images.githubusercontent.com/1043906/31845661-9717e288-b646-11e7-8d23-144467cce17a.png">

I currently run the server in docker and probably always will; just feel that Core 2.0 is the future, not mono.

**Comment by m-jepson** [comment]
I found the pre-release package ... makes me feel just a tiny bit stupid :)
But, it works like a charm. All the funcationality I have tested / require seems to be working as expected. Any idea when this package is going to be marked as stable?

**Comment by jageall** [comment]
I just released the 4.0.3-rc, if i get feedback that it is working well, I will release it on Sunday as stable

**Comment by iaincatt** [comment]
4.0.3-rc is still the latest version on pre-release. No stable 4.0.3 Core client yet?

**Comment by ahjohannessen** [comment]
Any news with respect to the backend?

**Comment by shaan1337** [comment]
As from version 5, client now targets netstandard 2.0.
