### ISSUE TITLE
Expected number was expected, but different event number received.

### ISSUE THREAD

**Issue by MCPx** [EventStore/EventStore#1468]
We have a couple of streams with max-age set to 7 days and run scavenge daily on a cron job on Ubuntu 16.04 running in Azure. There are a few projections that run over these streams and emit links to other streams. These having been running fine on version 4.0.0 of EventStore, but this morning I noticed that they were faulted with the following exception and causing ES to freeze:
```
[PID:44717:066 2017.10.16 06:23:22.779 ERROR ProjectionManager   ] The '<projection_name>' projection faulted due to 'Object reference not set to an instance of an object'
```

I then upgraded EventStore to version 4.0.3, which does not crash and allows me to access the UI while the projections were faulted and saw the following exception on most of the projections:
```
Event number 1221 was expected in the stream <stream_name>, but event number 1251 was received. This may happen if events have been deleted from the beginning of your stream, please reset your projection.
```

In this example, the last event that has not expired due to max age, is 1251. I have tried resetting and recreating those projections, but it still faults with the same error. Any idea how this situation could occur or be resolved? The max-age and projection code has not changed in months. 

I see there were a bunch of exceptions like this one:
```
[PID:38256:027 2017.10.16 05:18:37.176 DEBUG MonitoringService   ] Could not get free mem on linux, received memory info raw string: []
System.ComponentModel.Win32Exception (0x80004005): ApplicationName='free', CommandLine='-b', CurrentDirectory='', Native error= Out of memory
```

Could that have caused ES to lose track of where the next expected event should be?

I have since cleared the data (we archived it in table storage) and they are working fine now, but I'm concerned that this issue could occur again with expired events.

**Comment by hayley-jean** [comment]
@MCPx would you be able to provide us with a projection definition for us to test this our side?

When you reset the projections, did the error change at all, or was it stuck expecting event number 1221?

The projections keep track of the event number they expect next and validate each new event that comes through to ensure that it is what they expect. When the projection is reset, this expected event number should return to the first available event number in the source stream.

**Comment by MCPx** [comment]
@hayley-jean When resetting the error went away and reappeared on the UI, again expecting the same event number. Since recreating that environment, we haven't seen it happen again though, so you can close this issue.

The projections all faulted with the same error (expecting the last event number that expired from their tracked streams), so I'm not sure if the actual projection matters, but heres one of the simple ones:

```
var streamName = 'dev-instruction-api';

var splitToInstructionApiStream = function (state, ev) {
	linkTo(streamName + '-' + ev.metadata.MessageId, ev);
};

fromStream(streamName)
	.when({
		$any: splitToInstructionApiStream
	});
```

**Comment by hayley-jean** [comment]
Thank you @MCPx 

We will close this issue, but if you see this happen again, please reopen or create a new issue.

**Comment by MCPx** [comment]
@hayley-jean Sorry about that, I spoke too soon. Got the issue again now.

![image](https://user-images.githubusercontent.com/4311476/33166628-95b79962-d043-11e7-9ebb-da11c64092fa.png)

The projection:
```
/*
	For event sequencing.
*/
var streamName = 'qa-instruction-processing';

/*
	Emits if endpoint is CommandExecuter
*/
var emitIfPipelineCompletedEventInCommandExecuter = function (state, ev) {
	if (ev.metadata.EndpointName === "CommandExecuterEndpoint")
		linkTo(streamName + '-completed', ev);
};

/*
	Checks wether a message has gone into a pipeline error handler.
	CommandExecuter is excluded as errors will be included in the 
	'instruction-processing-completed' projection already. Error endpoints
	are excluded as they have no effect on sequencing.
*/
var emitIfErrorPipelineContextCreatedEvent = function (state, ev) {
	if (ev.metadata.EndpointName !== "CommandExecuterEndpoint" &&
		!ev.metadata.EndpointName.startsWith("Error"))
		linkTo(streamName + '-completed', ev);
};

fromStream(streamName)
	.when({
		PipelineCompletedEvent: emitIfPipelineCompletedEventInCommandExecuter,
		ErrorPipelineContextCreatedEvent: emitIfErrorPipelineContextCreatedEvent
	});
```

Resetting it makes the error message not show for a bit (but no events are processed) and then after a few minutes the message re-appears.

Please let me know what information you require to investigate.

**Comment by hayley-jean** [comment]
I've reopened the issue, would you be able to send us your Event Store logs?
If you don't want to share them here, you can email them to hayley at geteventstore.com.

Is this the same as it was previously where resetting the projection resulted in the same error message, with the same expected event number?

**Comment by MCPx** [comment]
Same behaviour, but this is a new projection and different event number. We recreated EventStore last time when all the previous ones were failing, so they all started from event 0 again and were fine. This one was faulted when it was created and I turned it on today and got that message. We have another projection that targets the same streams on the same eventstore, but with the 'dev-' prefix and that one was recreated today and is working.

I've attached the last 3 days worth of logs. 

[logs.zip](https://github.com/EventStore/EventStore/files/1498904/logs.zip)

**Comment by MCPx** [comment]
Hi @hayley-jean any news on this? I cleared out the eventstore database after this, but I am getting the error again on another stream (same projection code as above, but with streamName = 'int-instruction-processing' at the top).

I have attached the last 3 days logs again for your attention.

The error message is:
`Event number 2664 was expected in the stream int-instruction-processing, but event number 2699 was received. This may happen if events have been deleted from the beginning of your stream, please reset your projection.`

[logs.zip](https://github.com/EventStore/EventStore/files/2025176/logs.zip)

**Comment by azazi-sa** [comment]
We are facing the exact same error.

We have a stream (Currencies) of currency rates with each event having the max age of 28 days and we have a scavenging process scheduled daily. We have a few simple projections running on this stream which creates links to other streams. 

They used to work fine but we noticed that recently all the projections on this stream have gone into "Faulted (Enabled)" state and stopped working with the following error.

> Event number 555 was expected in the stream Currencies, but event number 658 was received. This may happen if events have been deleted from the beginning of your stream, please reset your projection.

Here is the sample projection definition.

```
fromStream('Currencies').when({   
                
            'CurrenciesUpdated' : function(state, evnt) { 
                linkTo("OurTargetStreamName", evnt); 
            }
        }); 
```

We have noticed that this is happening on multiple envs (dev / qa etc..) with only this stream and its projections. We have a lot of other projections but all of them run on streams created by $by_category projection and we have never experienced this error with any of them.

We have tried replicating the exact scenario locally with the same data without any success. Any help with this is much appreciated. 

We are using eventstore 4.1.1.0

**Comment by azazi-sa** [comment]
Update:

We were able to replicate it on our local machine in the following way.
1) Set Max Age to 2 seconds for source stream.
2) Seed events to the source stream on ~5 seconds of interval.
3) Let the projection run for a while and then stop it. But keep on seeding events to source stream.
4) When there is a significant difference (more than ~100) in the head of the source stream and projection's current position, start the projection.

At this point, your projection will go into the faulted state.

**Comment by filidorwiese** [comment]
Same issue here. Is there a way to recover from a faulty projection with this error?
