### ISSUE TITLE
Event is deleted from emitted stream.

### ISSUE THREAD

**Issue by amondnet** [EventStore/EventStore#1470]
ES: 3.9.4
OS: Ubuntu 14.04.5 LTS
Kernel: 3.19.0-66

1. I have a stream that is emitted stream from projection.

```
fromCategory('SubOrder')
    .when({
        $any: function( state, event ) {
            linkTo( 'Order-' +  event.metadata.correlationId, event, {} );
        }
    })
```

2. append event to that stream.

3. event is deleted

![2017-10-20 15 13 12](https://user-images.githubusercontent.com/1964421/31807452-35583194-b5a9-11e7-9634-58b9242456cd.png)

```
{
  "$tb": 8,
  "$acl": {}
}
```

**Comment by hayley-jean** [comment]
Hi @amondnet 

Are you doing anything like resetting the projection after it has run?
What happens if you write more events to the source stream? Are those emitted events truncated as well?

**Comment by amondnet** [comment]
@hayley-jean 

> Are you doing anything like resetting the projection after it has run?

Yes, I reset the projection once(or twice), because the projection had not been started.

> What happens if you write more events to the source stream? Are those emitted events truncated as well?

I will try once. Currently I don't write events to that stream. 
When events was written to the source stream, those events remained for a while and truncated.

**Comment by hayley-jean** [comment]
Are you in a position to try this on Event Store 4.0.3? There have been a lot of changes around projections, and this may have been something that was fixed.

When you say the projection has not been started, did it fail to start, or was it stopped at the time?

**Comment by amondnet** [comment]
@hayley-jean
The projection was stopped at the time.

**Comment by hayley-jean** [comment]
@amondnet Going back to your first comment about this issue, you mention that the stream has been truncated:

```
{
  "$tb": 8,
  "$acl": {}
}
```
Which stream has been truncated? Is it the `StorefarmOrder-{guid}` stream?

**Comment by amondnet** [comment]
@hayley-jean
Yes, StorefarmOrder stream has been truncated.

**Comment by hayley-jean** [comment]
This would be expected behaviour then.
If the original event is deleted, then the linked event will no longer have an event to point to.

If you want the linked event to remain after deleting the original event, you could look at using `emit` rather than `linkTo`.
`emit` rewrites the whole event to the new stream, rather than just writing an event that points to the original.
