### ISSUE TITLE
Projections & Momentjs

### ISSUE THREAD

**Issue by abdomohamed** [EventStore/EventStore#1473]
I'm wondering if we can import http://momentjs.com/docs/ to JS projecitons ?

**Comment by abdomohamed** [comment]
It seems it was applicable before to do so, but now it's not because we load JS modules from assembly. It that something we can revert back ? or at least is there away to import a common code between projections, instead of copy & paste ?

**Comment by MrBretticus** [comment]
There was discussion around this and using streams, but for now I use Browserify to compile and Grunt to deploy. I believe the problem about referencing files had to do with inconsistencies between nodes in a cluster.

**Comment by gregoryyoung** [comment]
Yes. There has been some discussion about allowing dependencies to be put into a stream (thus it exists within the cluster). Just using a folder as example runs the risk of a node becoming master then not having said dependency or perhaps even worse a different version of the dependency.
