### ISSUE TITLE
Question: Why the ProjectionsManager API has the parameter UserCredentials as optional?

### ISSUE THREAD

**Issue by Narvalex** [EventStore/EventStore#1477]
I ask this since it looks like that you can never do any projection management without the credentials

**Comment by hayley-jean** [comment]
Credentials are only required for updating, deleting or disabling/enabling projections.
Doing things like listing projections and reading their state can be done without providing credentials.

Apart from that, credentials can be provided when doing any of the calls on the projection manager, allowing users to provide them on a case-by-case basis

**Comment by Narvalex** [comment]
Thanks @hayley-jean!
