### ISSUE TITLE
Current read/write IO monitoring

### ISSUE THREAD

**Issue by drauly** [EventStore/EventStore#1492]
Hello,

Currently working on an eventstore cluster monitoring.

I would like to track current disk I/O usage based on ```/stats``` endpoint.
It seems that ```proc.diskIo.readOps``` and ```proc.diskIo.writeOps``` are cumulative field (always growing up).

Is their a way to get the current disk usage  ?

(eventstore version is 4.0.3)

Thank you

**Comment by alexeyzimarev** [comment]
These are performance counters, showing the correct _current_ values requires rating and sampling, which is not something performance counters designed to do. You can use Prometheus with the community-driven exporter, you can get any metric you need.
