### ISSUE TITLE
Error while collecting stats

### ISSUE THREAD

**Issue by Narvalex** [EventStore/EventStore#1493]
Windows Server 2012 R2 on a Virtual Machine hosted on prem

![image](https://user-images.githubusercontent.com/11648387/33086709-3d3f6670-cec7-11e7-8870-ab7be92e92dc.png)

**Comment by hayley-jean** [comment]
Hi @Narvalex 

This looks like this may be an issue with corrupt reading performance counters. You can find discussions on it on google groups, for example [here](https://groups.google.com/forum/#!searchin/event-store/error$20while$20collecting$20stats|sort:date/event-store/aIhlZkujS9Y/xWW8V18XggYJ) and [here](https://groups.google.com/forum/#!searchin/event-store/error$20while$20collecting$20stats|sort:date/event-store/IL6tNUqCM-I/oWamdNvpID4J).

Usually, this can be resolved by running the following command:
```
lodctl /r
```

**Comment by Narvalex** [comment]
Did you mean lodctr /r?

Will give that a try and if that solves the issue I will close this.

Thanks @hayley-jean !

**Comment by Narvalex** [comment]
After an hour or so it happens again. I have to restart event store if I want to see the UI Daschboard working.

**Comment by Narvalex** [comment]
Does the fact that I set `--stats-period-sec=86400` have any influence on this? I set that in order to not worry about scavenging so often...

**Comment by Narvalex** [comment]
It looks like this pull request #1417 fixes the problem... I will try and let you know

**Comment by Narvalex** [comment]
The pull request #1417 did fix this issue.
