### ISSUE TITLE
Windows: Archive bit is cleared when a chunk is set to ReadOnly

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore#1494]
When a chunk file is completed and becomes read only, Event Store sets the file attributes to ReadOnly, e.g. [here](https://github.com/EventStore/EventStore/blob/release-v4.0.4/src/EventStore.Core/TransactionLog/Chunks/TFChunk/TFChunk.cs#L504).
This overwrites the existing attributes of the file, including the Archive bit.

**Comment by gregoryyoung** [comment]
We set it because on some filesystems it changes caching behaviour. It should be pretty easy to retain other settings.

**Comment by jageall** [comment]
Closing as no further requests have been made for 2 years
