### ISSUE TITLE
Change master/slave/readreplica terminology to leader/follower/readreplica

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#1499]
After discussions internally, we intend to change the `master`, `slave`, `clone` terminology used for node state in Event Store 5.0.0. The new terminology respectively will be `primary`, `synchronous replica` and `asynchronous replica`, which better describe each role at a glance without having to refer to additional documentation, as well as being unoffensive.

This involves a few strands of work:

- [ ] Change server internals to reflect new terminology, paying attention to log messages and string references.
- [ ] Implement compatibility shims for:
    - [x] `ES-RequireMaster` in HTTP (which must continue to work for at least one major version, likely longer)
    - [ ] Node state in gossip in order that a rolling cluster upgrade can succeed from a version using the old terminology (which likely must continue to work for more than one major version)
- [x] Change .NET client API `requireMaster` parameter to `requirePrimary`. This needs careful thought as it could break consumer code if explicit parameter naming has been used.
- [ ] Compatibility testing for both upgrade to a v5.0.0 cluster and downgrade back to a v4.0.0 cluster (this may need a point release of v4.0.x which recognises the new terminology in gossip). 
- [ ] Update documentation on cluster management.

Work is underway on several of these items. If other areas of concern or strands of work to make this change appear, please link them to _this issue_.

**Comment by ahjohannessen** [comment]
Please don't forget document necessary changes to client libs such as https://github.com/EventStore/EventStore.JVM /cc @t3hnar

**Comment by jen20** [comment]
Work is underway on this. #2284 starts by renaming "master" to "leader", and a subsequent PR will address "slave". This is a convenient time to do this since the replication system already changed between v5 and v6.
