### ISSUE TITLE
Show eventId on web UI.

### ISSUE THREAD

**Issue by jezovuk** [EventStore/EventStore#1507]
On page showing single event (i.e. http://localhost:2113/web/index.html#/streams/mystream/123) there is no eventId (UUID/GUID). It shows event stream id, event number, event type, timestamp, data and metadata, but not eventId. I suppose it should not be problematic to add it, since it is exposed via HTTP API.

**Comment by hayley-jean** [comment]
This feature was added by https://github.com/EventStore/EventStore.UI/pull/187
