### ISSUE TITLE
re-sending  persistent subscription events to subscribers

### ISSUE THREAD

**Issue by rm2k** [EventStore/EventStore#1508]
Is possible to re send saved and processed events in persistent subscription? I noted in the web UI you can only replay parked messages, but in my case I want to reprocess the events from the beginning.

**Comment by gregoryyoung** [comment]
Yes you can reset the subscription during recreation it will start over.

**Comment by rm2k** [comment]
wow! that's great, I was thinking rocket science. Thanks @gregoryyoung
