### ISSUE TITLE
408 timeout when access stats and stats/tcp

### ISSUE THREAD

**Issue by zhuzhenguang** [EventStore/EventStore#1513]
There is a timeout problem when access dashboard of Event Store UI, and no data in dashboard section and in the console, the following error message shows up. 

Do you have any idea? Many Thanks!

![image](https://user-images.githubusercontent.com/512924/33818095-046c8640-de7e-11e7-9f8f-0cca330a343e.png)

**Comment by zhuzhenguang** [comment]
Event Store has been upgraded to 4.0.3.3, and no more cluster-node-stats.csv file has been generated since the error occurred.

**Comment by hayley-jean** [comment]
Hi @zhuzhenguang 

Are there any errors in the Event Store logs?
What configuration are you using for the node?

**Comment by zhuzhenguang** [comment]
Hi @hayley-jean 
1. No, have not any error logs, and I also find no cluster-node-stats.csv output.
2. the config file as follow
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="eventStore" type="EventStore.Service.EventStoreServiceConfiguration, EventStore.Service, Version=1.0.0.0, Culture=neutral" />
  </configSections>
  <eventStore executable="D:\EventStore-OSS-Win-v4.0.3-hotfix1\EventStore.ClusterNode.exe">
    <instance name="eventstore"
  		add-interface-prefixes="false"
   		int-http-prefixes="http://127.0.0.1:2113/"
    	ext-http-prefixes="https://172.21.14.109:2114/,http://127.0.0.1:2113/"
		ext-ip="172.21.14.109"
		int-ip="127.0.0.1"
		int-tcp-port="2111"
		ext-tcp-port="2112"
		int-http-port="2113"
		ext-http-port="2114"
		db="D:\data"
		log="D:\Services\EventStoreService\eslogs"
		certificate-store-location="LocalMachine"
		certificate-store-name="My"
		certificate-thumbprint="xxx"
		ext-secure-tcp-port="2115"
		int-secure-tcp-port="2116"
		use-internal-ssl="true"
		ssl-target-host="xxx.local"
		ssl-validate-server="true"
		run-projections="all"
		/>
  </eventStore>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  <appSettings>
    <add key="EventStore_UserName" value="admin"/>
    <add key="EventStore_Password" value="changeit"/>
  </appSettings>
</configuration>

**Comment by zhuzhenguang** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="eventStore" type="EventStore.Service.EventStoreServiceConfiguration, EventStore.Service, Version=1.0.0.0, Culture=neutral" />
  </configSections>
  <eventStore executable="D:\EventStore-OSS-Win-v4.0.3-hotfix1\EventStore.ClusterNode.exe">
    <instance name="eventstore"
  		add-interface-prefixes="false"
   		int-http-prefixes="http://127.0.0.1:2113/"
    	ext-http-prefixes="https://172.21.14.109:2114/,http://127.0.0.1:2113/"
		ext-ip="172.21.14.109"
		int-ip="127.0.0.1"
		int-tcp-port="2111"
		ext-tcp-port="2112"
		int-http-port="2113"
		ext-http-port="2114"
		db="D:\data"
		log="D:\Services\EventStoreService\eslogs"
		certificate-store-location="LocalMachine"
		certificate-store-name="My"
		certificate-thumbprint="xxx"
		ext-secure-tcp-port="2115"
		int-secure-tcp-port="2116"
		use-internal-ssl="true"
		ssl-target-host="xxx.local"
		ssl-validate-server="true"
		run-projections="all"
		/>
  </eventStore>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  <appSettings>
    <add key="EventStore_UserName" value="admin"/>
    <add key="EventStore_Password" value="changeit"/>
  </appSettings>
</configuration>
```

**Comment by zhuzhenguang** [comment]
I think there is some problem with $stats. because $stats-[server address] stream not updated recently.

**Comment by shaan1337** [comment]
@zhuzhenguang from which version where you upgrading to 4.0.3.3?

**Comment by zhuzhenguang** [comment]
Hi, @shaan1337 , from 4.0.3

**Comment by Narvalex** [comment]
It happened to me. Windows 10 restart from cold solved the problem

**Comment by StevenBlair123** [comment]
Slightly off topic, but that how do setup that XML configuration in the post above?
I generally just use a batch file with various switches on it, but that looks much nicer.

**Comment by Narvalex** [comment]
Check out [here](https://msdn.microsoft.com/en-us/library/2tw134k3.aspx?f=255&MSPPError=-2147217396), @StevenBlair123

**Comment by StevenBlair123** [comment]
But how would I get the Event Store to use that?

**Comment by Narvalex** [comment]
You have to manual wire up yourself... or use the[ YAML configuration](https://eventstore.org/docs/server/command-line-arguments/index.html#yaml-files) stuff that supports Event Store out of the box.

**Comment by mat-mcloughlin** [comment]
Closed as no further feedback
