### ISSUE TITLE
Projection loses state after restarting EventStore

### ISSUE THREAD

**Issue by dgchurchill** [EventStore/EventStore#1517]
After restoring a backup we noticed that our projection had reinitialized its state using the `$init` function. Checking the latest event on the `$projection-System and tenancy streams-checkpoint` stream showed that it had empty data. Our projection state changes only very sporadically meaning that at most checkpoints the state hasn't changed from the last checkpoint.

It seems that projection state is only stored in the checkpoint if it has changed since the last checkpoint. If a checkpoint is written without the state and EventStore is restarted then the projection resumes using its initial state.

/cc @mattwalkenhorst

**Comment by shaan1337** [comment]
Hi @dgchurchill 

Thanks very much for all the details.
Can you please let us know which version of Eventstore are you using?

I've tried to reproduce the issue with a projection like this (with checkpoint threshold 3):

```
fromStream('x')
.when({
    '$init':function(){
      return {count: 0};
    },
    '$any':function(s,e){
        if(s.count==0){
            s.count = s.count + 1;
        }
    }
})
```

So basically, `s.count` should remain 1 as soon as an event is written.

After adding a few events, I can see from `$projections-x-checkpoint` that the state is stored in the last 2 checkpoint events although it's the same state: `[{"count":1},{"count":1}]`

Am I missing any step in the above reproduction?

Thanks,
Shaan

**Comment by shaan1337** [comment]
Can you please also give up more details about your projection (a sample would help us a lot):
1) Is it a multi-stream projection?
2) Does it use fromCategory() or foreachStream()?

**Comment by dgchurchill** [comment]
Hi @shaan1337, thanks very much for your quick response. The EventStore was created on v4 (I think v4.0.2.0 but I will confirm tomorrow). We took a backup and restored it and noticed in the restore that the projection had no state. The restore was done on v4.0.3.3 and I believe we also replicated the issue on this version by writing an event which didn’t affect the state of the projection and then stopping the projection to force a checkpoint.

Our projection is very similar to your repro although we use `fromAll`. The full code of our projection is below, I’ve just replaced a few guids with the string <guidn>. The projection has all the default settings including default of 4000 events between checkpoints.

```
fromAll().when({
    $init: function() {
        return {
            tenancies: {
                // These pre-populated ids are a bit of a dirty hack, just here because the
                // integration tests don't write TenancyCreatedEvents for the test tenancies yet.
                '<guid1>': 'Test',
                '<guid2>': 'TestAuth',
                '<guid3>': 'SmokeTest'
            }
        };
    },

    $any: function(state, event) {
        // Update our tenancies map for new tenancies
        if (event.eventType == 'TenancyCreatedEvent') {
            state.tenancies[event.body.TenancyId] = event.body.SystemName;
        }

        // Link !system events to the !events-!system stream
        //
        // NOTE: We specify a maximum of 4 parts because JavaScript's String.split doesn't return the
        //       remainder of the string in the last part. If we want to be sure there are no more than
        //       3 parts then we need to allow at least 4.
        var streamIdParts = event.streamId.split('-', 4);
        if (streamIdParts.length == 3 && streamIdParts[0] == '!system') {{
            linkTo('!events-!system', event);
        }

        // Link tenancy events to the !events-<tenancy> stream
        if (event.metadata) {
            var tenancyName = state.tenancies[event.metadata.TenancyId];
            if (tenancyName) {
                linkTo('!events-' + tenancyName, event);
            }
        }
    }
});
```

Please let me know if I’ve missed anything or can provide more info.

**Comment by shaan1337** [comment]
Thanks @dgchurchill I've been able to reproduce the "empty state" being stored by just stopping the projection and starting it again. `fromAll` and `fromStream` are both affected, so it could be a bug in the checkpoint manager itself.

Steps:
1. Create a projection named **test**:
```
fromStream('x')
.when({
    '$init':function(){
      return {count: 0};
    },
    '$any':function(s,e){
        if(s.count==0){
            s.count = s.count + 1;
        }
    }
})
```

2. Stop the projection and edit the config, set the max checkpoint threshold to a small value (3 for example)

3. Write a few events (e.g. 10) to stream 'x'

4. Stop the projection, check **$projections-test-checkpoint**, there should be two events with data: `[{"count":1},{"count":1}]`

5. Start the projection again

6. Write a few more events to trigger another checkpoint.

7. Check **$projections-test-checkpoint** again, the newly generated checkpoint's data should be : `[]`

**Comment by shaan1337** [comment]
Example updated showing that the previous state is lost

**Comment by dgchurchill** [comment]
Thanks!
