### ISSUE TITLE
4.4.1 error in libMonoPosixHelper.so after upgrade, no login screen

### ISSUE THREAD

**Issue by pvcon13** [EventStore/EventStore#1530]
Been running 4.0.2 on ubuntu 16.0x.0x. Did a apt-get dist-upgrade, stopped eventstore;reboot.
System came up and started rebuilding indexes (according to service eventstore status and logs.
When index rebuilding was complete, could not get a login prompt on port 2113 anymore.
Command line Version reported was 4.4.1 now. Downgraded to 4.0.2. Restarted service.
It rebuilt indexes again and now I can log back in.
Error in logs for failed attempts Error while handling HTTP request <address:port>
libMonoPosixHelper.so

1) so bug in 4.4.1
2) how can you prevent it from rebuilding indexes on an orderly restart?

**Comment by hayley-jean** [comment]
Hi @pvcon13 

Would you be able to share your logs with us? If you don't want to add them here, you can email them to hayley at geteventstore.com.

**Comment by hayley-jean** [comment]
Hi @pvcon13 

The http error is caused by a missing file in the package.
As a workaround until we can update the packages, you can install mono on the Event Store node.

With regards to the index rebuild, I have not been able to reproduce this.
1. Was there any reason in the logs as to why the rebuild happened? Corruption etc?
2. Was there an index backup folder created?

**Comment by pvcon13** [comment]
E-mail with procedures and log files sent earlier.
Thank you

**Comment by pvcon13** [comment]
I included 1) how the system was originally built  2) how the unintended upgrade happened  3) how the system was downrev'ed.  I assume the dist-upgrade process had something to so with this. you have all the logs. now

**Comment by pvcon13** [comment]
Question: was the index rebuild a result of the upgrade? If not, how do we reboot systems without triggering and re-indexing?

**Comment by pvcon13** [comment]
Can I add a parameter to the startup config to NOT re-index unless its really corrupted?

**Comment by pvcon13** [comment]
Where on a ubuntu system would the data files and thus the index backups be located?

**Comment by jen20** [comment]
The index will only ever be written to disk if it's hit a million entries (or the number of `--max-memtable-size`) - but the default if installed from packages for both data and indicies is: `/var/lib/eventstore`

**Comment by pvcon13** [comment]
ok, 19 chunk files total. one index folder (empty), no index backup. 8 bytes in each chaser, epoch, truncate and writer files. Nothing else there. What and where else should I look?

**Comment by jen20** [comment]
If the index directory is empty, this suggests you haven't hit the threshold for writing the index to disk versus holding it in memory yet. You can adjust this number downwards from the default of 1000000 using the `--max-memtable-size` option if you want to write the index more frequently.

**Comment by pvcon13** [comment]
I might do that thank you. I still like to know why shutting down and rebooting and restarting is causing a full 4 minute reindexing? and if there is a way I can procedurally prevent that.

**Comment by shaan1337** [comment]
@pvcon13 there have been some index improvements in v4.0.4 rc 1: https://eventstore.org/blog/20171219/event-store-4.0.4-release-candidate-1/

The index files created by this new version (PTables V4) are not backward compatible.

The following scenario is possible: after upgrading to v4.0.4rc1, if you have ingested enough events (1 million entries by default), a new PTable version 4 index file must have been created.

When you downgraded to v4.0.2, these new (non backward compatible) index files were detected as "corrupt", triggering an index rebuild.

Normally, once the index rebuild has reached 100%, it should not occur again on the next reboot. Did it reach 100% in your case?

**Comment by hayley-jean** [comment]
Hi @pvcon13,

The scenario that James mentioned is the case here - your db doesn't have enough entries for an index to have been created yet. By default, it would require 1,000,000 entries, but your index only contains 653,988:

```
.. ReadIndex rebuilding done: total processed 653988 records, time elapsed: 00:03:32.1040420.
```

You are correct that it will need to recalculate the index in memory on each restart if the indexes aren't written. As James mentioned, you can set the `--max-memtable-size` to a lower value to force records to be written to disk and make this rebuild take less time.

**Comment by shaan1337** [comment]
Hi @pvcon13 

We've fixed the libMonoPosixHelper.so packaging issue in the release candidate.

You can follow the steps on the link below to get the updated version:
https://packagecloud.io/EventStore/EventStore-OSS-PreRelease/packages/ubuntu/xenial/eventstore-oss_4.0.4-rc1-2_amd64.deb

Kindly let us know if you can now access the login screen.

Thanks!
