### ISSUE TITLE
Want per-node and per-cluster health checks

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#1537]
As discussed on the mailing list, we should likely add health checking endpoints which can be used with a load balancer (although this is suboptimal, it might be ok for HTTP use cases). These could be on (for example) `/health/node` and `/health/cluster`, and use the HTTP status code to communicate the result.

**Comment by ylorph** [comment]
http://localhost:2113/health/live 
https://github.com/EventStore/EventStore/blob/master/Dockerfile#L91
