### ISSUE TITLE
Backup options non-cluster 

### ISSUE THREAD

**Issue by frederiksf** [EventStore/EventStore#1540]
How safe is it to just backup the data files while the eventstore is running or do we need to shut it down first? 

Thank you!

regards 
Frits

**Comment by gregoryyoung** [comment]
This is covered in documentation but its completely safe. https://eventstore.org/docs/server/4.0.2/database-backup/

**Comment by vmsgsp** [comment]
- Please explicitly mention in the documentation that Event Store can stay running while copying the files in the specified order
- Please make the "Restoring the database" section more precise. It says to copy the chaser.chk to truncate.chk. Is this in the backup location? Do I overwrite the exiting backupfolder/truncate.chk with the backupfolder/chaser.chk contents then? And then overwrite all files in the working folder with all files from the backup folder (while event store is running)?

https://eventstore.org/docs/server/database-backup/index.html#restoring-a-database
