### ISSUE TITLE
Numeric values in JSON events stored as double precision floating point values.

### ISSUE THREAD

**Issue by jezovuk** [EventStore/EventStore#1541]
Trying to store event like this:
```
{
    "a" : 0.1234567890123456789
}
```
produces following result:
```
{
    "a" : 0.12345678901234568
}
```

Similar happens for integer values. For exaple, 12345678901234567890 ends up as 12345678901234567000.
Also, rounding being applied upon this loss of precision seems inconsistent (or at least I could not detect the pattern).
First observed via Java client communicating over TCP (using esjc client lib) and later repeated it via web UI (using built-in "Add Event" feature).
Using latest ES version (4.0.3 Hotfix 1 for Windows).

I did not see this limitation mentioned  anywhere in the docs.

**Comment by Narvalex** [comment]
I asume that is not the case if the value is stored as a string, right?

**Comment by jezovuk** [comment]
Works ok as string.

**Comment by Narvalex** [comment]
![image](https://user-images.githubusercontent.com/11648387/35218423-57dce744-ff4d-11e7-9040-ad06e5ab3b6a.png)
A simple test in Chrome Dev Tools shows the same behavior. This may be related to the javacript engine itself, in this case the V8 engine. In the Microsoft´s Chakra the same behavior can be seen. I guess this is related to the javacript specification itself and not about EventStore

**Comment by jezovuk** [comment]
Went with strings. Still, this should at least be documented.

**Comment by oskardudycz** [comment]
Unfortunately, that's how JSON and JavaScript works. Besides the decimal precision, there might be differences in the maximum number size, etc. I think that as it's clear that we're using JavaScript processing then JavaScript limitations/specifics should be taken into an account.
We recommend using strings if you want to have the full precision.
