### ISSUE TITLE
"JSON" link for in-page event view in Stream Browser (Web UI) ignores DisableHTTPCaching config parameter.

### ISSUE THREAD

**Issue by jezovuk** [EventStore/EventStore#1549]
As the title says, event data shown via in-page expansion ("JSON" link in stream events listing table in Stream Browser in Web UI) seems to ignore HTTP caching being disabled. Stale data is shown after entire event store re-import. Separate page view of event data works as expected (link in "Name" column in stream events listing table).

**Comment by MetaFight** [comment]
I was bit by this today.  Wasted plenty of time :/

**Comment by shaan1337** [comment]
This seems similar to caching issues in #1569

**Comment by jageall** [comment]
If the correct headers are being set and the browser is ignoring them, this issue will be closed

**Comment by avish0694** [comment]
@jezovuk The correct is headers is being sent by the server when requesting a stream from UI. We are closing this issue but if you get a reproduction step, Please do include it here. Thanks.
