### ISSUE TITLE
Stats Stream

### ISSUE THREAD

**Issue by ghost** [EventStore/EventStore#1551]
Hello, 

I'm wondering if the stats stream gets replicated between nodes? Currently we have a cluster of 3 and Event-store is Fully Locked Down behind a HTTP Proxy, The only downside to this is the stats stream is named 127.0.0.1. We read this stream and send the data to graphite, Does this stream include all cluster nodes? 

Thanks

**Comment by shaan1337** [comment]
@ghost yes, system streams are also replicated across nodes like normal streams.
The stream name is $stats-<node's external http endpoint>, so it'll be usually be different for different nodes of the cluster.

Alternatively, you can also tail the stats files from each node and send to your monitoring system - as from version 5 structured logging has been introduced which saves the stats in JSON format.
