### ISSUE TITLE
StreamCheckpoint.StreamStart type does not match IEventStoreConnection.SubscribeToStreamFrom

### ISSUE THREAD

**Issue by sjmelia** [EventStore/EventStore#1552]
The type of `StreamCheckpoint.StreamStart` is `int?` but `IEventStoreConnection.SubscribeToStreamFrom` takes a `long?`. I propose modifying `StreamCheckpoint.StreamStart` to match; making it a bit easier to use something like the following pattern when subscribing:

```
bool wantToResume = <some value>;
Nullable<long> mySavedCheckpoint = <some value>;
Nullable<int> start = StreamCheckpoint.StreamStart;
if (wantToResume)
{
    start = mySavedCheckpoint;
}
```

**Comment by hayley-jean** [comment]
Hi @sjmelia Thank you for the PR and for pointing this out
Unfortunately, this change may break compatibility for existing clients that are working under the assumption that `StreamStart` is an `int?` and not a `long?`.

As such, this change can only be introduced in the next major version. I have added a note to our backlog and labelled this issue so we don't forget
