### ISSUE TITLE
Please update the EventStore docker image

### ISSUE THREAD

**Issue by smatsson** [EventStore/EventStore#1554]
We have recently updated to 4.1.0 to get the perks of the new index verification feature (the skipping of index verification). In our ci/test/prod environments we run multi node clusters but locally we use the Docker image found at https://hub.docker.com/r/eventstore/eventstore/

This image has not been updated and since the index in 4.1.0 is not backwards compatible according to the release notes we would very much like to run the same version locally and in our other environments.

Thank you!

**Comment by hayley-jean** [comment]
Thanks for the reminder! The new version is now available on dockerhub

**Comment by smatsson** [comment]
Thank you! :)

**Comment by puco** [comment]
Why is the `latest` tag older than the `release-4.1.0` version?
