### ISSUE TITLE
Publish 1000 messages to stream SubscribeToStreamFrom returns 999 messages

### ISSUE THREAD

**Issue by DR9885** [EventStore/EventStore#1556]
Publish 1000 messages to stream SubscribeToStreamFrom returns 999 messages

**Comment by jen20** [comment]
It's zero based. You need to start from -1. There are constants for it in client libraries.

**Comment by DR9885** [comment]
I was using the constants, StreamPosition.Start, which is actually 0 

/// <summary>Constants for stream positions</summary>
  public static class StreamPosition
  {
    /// <summary>The first event in a stream</summary>
    public const int Start = 0;
    /// <summary>The last event in the stream.</summary>
    public const int End = -1;
  }
