### ISSUE TITLE
Streams Projections no data

### ISSUE THREAD

**Issue by hanxinimm** [EventStore/EventStore#1558]
Persistent Subscriptions error

![z7 2ru y21b8i9c3 w1qg](https://user-images.githubusercontent.com/13499426/35798943-336ed72a-0a9f-11e8-8991-a4f8531ef1c9.png)

![q5l92uf9tnp1834 d gekf](https://user-images.githubusercontent.com/13499426/35798941-315217b8-0a9f-11e8-8d3f-333b5d55acb5.png)

![e6 e07z u7md0r v_w0zj_u](https://user-images.githubusercontent.com/13499426/35798931-2ef5229e-0a9f-11e8-93f2-5aad29cc84e8.png)

![_ _qr am4 t 33l4r9q7eku](https://user-images.githubusercontent.com/13499426/35798923-2a4319b8-0a9f-11e8-9ffa-d1671d96b228.png)

**Comment by hayley-jean** [comment]
Hi @hanxinimm,
Do you have the `$by_event_type` projection enabled?

**Comment by hanxinimm** [comment]
@hayley-jean 
$ArgumentList = "--db D:\EventStore\db\"+ $n +" --log D:\EventStore\logs\"+ $n +" --run-projections=all --start-standard-projections=true

**Comment by hayley-jean** [comment]
Thanks, could you also please check if there are any streams for the event types?
For example, does the stream `$et-Labor-Security-Account-ThirdPartyWeiXinAppCreateEvent` exist?
Have the projections processed any events? You can see this on the `Projections` screen in the UI

**Comment by jageall** [comment]
closing due to lack of feedback
