### ISSUE TITLE
fromStreams doesn't work

### ISSUE THREAD

**Issue by dimaip** [EventStore/EventStore#1568]
This projection displays no state and no results:
```js
fromStreams(['payments', 'subscriptions'])
.when({
    $init: function(){
        return {
            debug: []
        };
    },
    $any: function handle(s, e) {
        s.debug.push(e);
        return s;
    }
});
```

This works:
```js
fromStreams(['payments'])
.when({
    $init: function(){
        return {
            debug: []
        };
    },
    $any: function handle(s, e) {
        s.debug.push(e);
        return s;
    }
});
```

This works: 

```js
fromStreams(['subscriptions'])
.when({
    $init: function(){
        return {
            debug: []
        };
    },
    $any: function handle(s, e) {
        s.debug.push(e);
        return s;
    }
});
```

How could this be?

I'm running 4.1.0 version from docker.

![image](https://user-images.githubusercontent.com/837032/36593099-759ae004-18a9-11e8-87f0-badd968bd9cc.png)

**Comment by hayley-jean** [comment]
Hi @dimaip,

Are there any errors in Event Store or the console log? Given that the projections panel isn't showing any of the stats, it may be that there's an error communicating with the server.

**Comment by dimaip** [comment]
Hey @hayley-jean, thanks for your response!

Nothing bad in console: 
![image](https://user-images.githubusercontent.com/837032/36596871-3dd8f2fa-18b8-11e8-8eba-229bee764fef.png)

Output from docker logs of the container:

```
eventstore_1  | [00001,26,13:41:43.164] Resetting 'test' projection
eventstore_1  | [00001,26,13:41:43.164] PROJECTIONS: Scheduling the writing of $stop to $projections-$663feb0b-f220-4cf2-8d97-b824a06b865c. Current status of Writer: Busy: False
eventstore_1  | [00001,26,13:41:43.175] PROJECTIONS: Finished writing events to $projections-$663feb0bf2204cf28d97b824a06b865c: $stop
eventstore_1  | [00001,29,13:41:43.175] PROJECTIONS: Command received: 21356@$stop
eventstore_1  | [00001,29,13:41:43.175] PROJECTIONS: Scheduling the writing of $stopped to $projections-$master. Current status of Writer: Busy: True
eventstore_1  | [00001,29,13:41:43.189] PROJECTIONS: Finished writing events to $projections-$master: $stopped
eventstore_1  | [00001,26,13:41:43.194] PROJECTIONS: Response received: 177344@$stopped
eventstore_1  | [00001,26,13:41:43.194] PROJECTIONS: Scheduling the writing of $dispose to $projections-$663feb0b-f220-4cf2-8d97-b824a06b865c. Current status of Writer: Busy: False
eventstore_1  | [00001,26,13:41:43.195] PROJECTIONS: Scheduling the writing of $create-and-prepare to $projections-$663feb0b-f220-4cf2-8d97-b824a06b865c. Current status of Writer: Busy: True
eventstore_1  | [00001,26,13:41:43.200] PROJECTIONS: Finished writing events to $projections-$663feb0bf2204cf28d97b824a06b865c: $dispose
eventstore_1  | [00001,29,13:41:43.200] PROJECTIONS: Command received: 21357@$dispose
eventstore_1  | [00001,26,13:41:43.210] PROJECTIONS: Finished writing events to $projections-$663feb0bf2204cf28d97b824a06b865c: $create-and-prepare
eventstore_1  | [00001,29,13:41:43.210] PROJECTIONS: Command received: 21358@$create-and-prepare
eventstore_1  | [00001,29,13:41:43.302] SLOW BUS MSG [bus]: CreateAndPrepare - 90ms. Handler: ProjectionCoreService.
eventstore_1  | [00001,29,13:41:43.302] SLOW QUEUE MSG [Projection Core #2]: CreateAndPrepare - 91ms. Q: 1/12.
eventstore_1  | [00001,29,13:41:43.302] PROJECTIONS: Scheduling the writing of $prepared to $projections-$master. Current status of Writer: Busy: True
eventstore_1  | [00001,29,13:41:43.330] PROJECTIONS: Finished writing events to $projections-$master: $prepared
eventstore_1  | [00001,26,13:41:43.330] PROJECTIONS: Response received: 177348@$prepared
eventstore_1  | [00001,26,13:41:43.345] 'test' projection source has been written
eventstore_1  | [00001,26,13:41:43.345] PROJECTIONS: Scheduling the writing of $start to $projections-$663feb0b-f220-4cf2-8d97-b824a06b865c. Current status of Writer: Busy: False
eventstore_1  | [00001,26,13:41:43.360] PROJECTIONS: Finished writing events to $projections-$663feb0bf2204cf28d97b824a06b865c: $start
eventstore_1  | [00001,29,13:41:43.360] PROJECTIONS: Command received: 21359@$start
eventstore_1  | [00001,29,13:41:43.362] PROJECTIONS: Scheduling the writing of $started to $projections-$master. Current status of Writer: Busy: True
eventstore_1  | [00001,29,13:41:43.389] PROJECTIONS: Finished writing events to $projections-$master: $started
eventstore_1  | [00001,26,13:41:43.389] PROJECTIONS: Response received: 177351@$started
eventstore_1  | [00001,19,13:41:45.262] SLOW QUEUE MSG [MonitoringQueue]: GetFreshStats - 882ms. Q: 0/0.
```

**Comment by dimaip** [comment]
For now I went with `fromAll`, but it feels slower, takes about 10s to rebuild the projection.

**Comment by hayley-jean** [comment]
Could you try requesting the projection information from something like curl?
For example: 
```
curl -i http://localhost:2113/projection/test
```

**Comment by dimaip** [comment]
@hayley-jean 

```
curl -i http://localhost:2113/projection/test 
HTTP/1.1 200 OK
Access-Control-Allow-Methods: GET, DELETE, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Forwarded-Host, X-Forwarded-Prefix, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTos
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position, ES-CurrentVersion
Cache-Control: max-age=0, no-cache, must-revalidate
Vary: Accept
Content-Type: application/json; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Fri, 23 Feb 2018 14:47:15 GMT
Content-Length: 958
Keep-Alive: timeout=15,max=100

{
  "coreProcessingTime": 0,
  "version": 27,
  "epoch": 27,
  "effectiveName": "test",
  "writesInProgress": 0,
  "readsInProgress": 0,
  "partitionsCached": 1,
  "status": "Running",
  "stateReason": "",
  "name": "test",
  "mode": "Continuous",
  "position": "payments: -1; subscriptions: -1; ",
  "progress": -1.0,
  "lastCheckpoint": "payments: -1; subscriptions: -1; ",
  "eventsProcessedAfterRestart": 0,
  "statusUrl": "http://localhost:2113/projection/test",
  "stateUrl": "http://localhost:2113/projection/test/state",
  "resultUrl": "http://localhost:2113/projection/test/result",
  "queryUrl": "http://localhost:2113/projection/test/query%3Fconfig=yes",
  "enableCommandUrl": "http://localhost:2113/projection/test/command/enable",
  "disableCommandUrl": "http://localhost:2113/projection/test/command/disable",
  "checkpointStatus": "",
  "bufferedEvents": 0,
  "writePendingEventsBeforeCheckpoint": 0,
  "writePendingEventsAfterCheckpoint": 0
}
```

**Comment by hayley-jean** [comment]
@dimaip Does the projection process events if you write them to those streams?
If the stats still do not appear in the UI, could you send us the projection information again?

**Comment by nissbran** [comment]
There is a possibility that this is UI related, if you have many events(around 2000+) in your javascript array it takes a long time to render the projections page, because of the large JSON structures that have to render _twice_ (state and result). 
If you run:
http://localhost:2113/projection/test/state or 
http://localhost:2113/projection/test/result
Does it give you a result?

**Comment by dimaip** [comment]
@nissbran @hayley-jean 
you can see from the curl above, that REST endpoints output empty results as well.
Also if you look at the output here, you see that the test projection has 0 processed events.
![image](https://user-images.githubusercontent.com/837032/36677831-416d4726-1b20-11e8-87e5-76e75de4b253.png)

Also I don't have any default projections running, but I guess that shouldn't be related, right?

**Comment by dimaip** [comment]
> @hayley-jean Does the projection process events if you write them to those streams?
No.

> If the stats still do not appear in the UI, could you send us the projection information again?
What does it mean? What is the projection information?

**Comment by hayley-jean** [comment]
@dimaip You can see the projection information by clicking through to the projection in the UI, on the projection edit screen.

What version of Event Store are you running?
Also, are there any events in the `payments` or `subscriptions` streams?

**Comment by dimaip** [comment]
@hayley-jean this screen?

![image](https://user-images.githubusercontent.com/837032/36744687-847acca8-1bfe-11e8-80ea-fa8f0be8d0d8.png)

As said, I'm running version 4.1.0 from the official docker image.
Both streams have events, ~400 in each.

**Comment by dimaip** [comment]
If you try to run my projection with any two streams, does it work for you?

**Comment by hayley-jean** [comment]
Hi @dimaip 

The projection works on my side using the docker image.

Could you give us a sample of the events in the `payments` or `subscriptions` streams?
Were these streams perhaps deleted at some stage, or are these events link to events?
When you have tried testing this with other streams, did you create a new projection, or just update the existing one?

**Comment by dimaip** [comment]
@hayley-jean hey sure. There are no linked events, just plain events, e.g. smth like:

```
{
  "TransactionId": "40441033",
  "Amount": "100.00",
  "Currency": "RUB"
...
}					
```

> When you have tried testing this with other streams, did you create a new projection, or just update the existing one?

Both.

Even more so, I tried running the same projection on our production server, and there got exactly the same result.

Perhaps I should build up projections myself via subscriptions...

**Comment by mscmorris** [comment]
I'm experiencing this same behavior on 4.0.3 while trying to do `fromStreams(['$et-invoice.created', '$et-invoice.updated'])`

**Comment by mscmorris** [comment]
Here's the API output.

`{
    "coreProcessingTime": 0,
    "version": 37,
    "epoch": 37,
    "effectiveName": "billing.invoicereport.events",
    "writesInProgress": 0,
    "readsInProgress": 0,
    "partitionsCached": 0,
    "status": "Running",
    "stateReason": "",
    "name": "billing.invoicereport.events",
    "mode": "Continuous",
    "position": "$et-invoice.created: -1; $et-invoice.updated: -1; ",
    "progress": -1,
    "lastCheckpoint": "$et-invoice.created: -1; $et-invoice.updated: -1; ",
    "eventsProcessedAfterRestart": 0,
    "statusUrl": "http://test-eventstore:2114/projection/billing.invoicereport.events",
    "stateUrl": "http://test-eventstore:2114/projection/billing.invoicereport.events/state",
    "resultUrl": "http://test-eventstore.com:2114/projection/billing.invoicereport.events/result",
    "queryUrl": "http://test-eventstore:2114/projection/billing.invoicereport.events/query%3Fconfig=yes",
    "enableCommandUrl": "http://test-eventstore:2114/projection/billing.invoicereport.events/command/enable",
    "disableCommandUrl": "http://test-eventstore:2114/projection/billing.invoicereport.events/command/disable",
    "checkpointStatus": "",
    "bufferedEvents": 0,
    "writePendingEventsBeforeCheckpoint": 0,
    "writePendingEventsAfterCheckpoint": 0
}`

**Comment by alec-anikin** [comment]
Hi @hayley-jean ,

I have the same issue on my test environment with 4.1.1-hotfix. I can share my database and logs with broken streams/projections. Please let me know if you need it.

**Comment by tonyvanriet** [comment]
Hi @hayley-jean et al,

Has there been any new progress on this issue? We've started noticing this behavior with our 4.1.0 EventStore instance and it does appear to be specific to the case where you have multiple `fromStreams` where any one of those streams have been deleted at some point in the past.

To restate that:
* When we have a projection with multiple `fromStreams`, if any of those streams have been deleted in the past, the projection _does not_ build and sits at Done % -1. 
* If we limit fromStreams to a single stream that has been deleted before, then the projection _does_ build.
* If we have multiple `fromStreams` where none of them have been deleted, then the projection _does_ build.

We've also fallen back to fromAll to work-around this issue for the time being.

**Comment by theofanis** [comment]
I can see the same behavior on 4.1.1.0 as well. I deleted some streams that were participating in a `fromStreams` and now the project is not doing anything.

Creating test projections with a single value in `fromStreams` or just reading from the specific stream with `fromStream` works.

**Comment by jageall** [comment]
closing in favour of #1872
