### ISSUE TITLE
Eventstore shows cached data to users without read permissions

### ISSUE THREAD

**Issue by xLasercut** [EventStore/EventStore#1569]
Eventstore will display cached stream data to any user instead of only users with permission
1. Set ACL of any stream to $admin only (I created a test stream for this - url: http://127.0.0.1:2113/web/index.html#/streams/test, but this works with any stream)
2. View the data of that stream as admin user (e.g. http://127.0.0.1:2113/web/index.html#/streams/test)
3. log out of admin and login to non admin user
4. Go to the url of the same stream that you viewed as admin (searching for the stream does not work but visiting the url does) 
5. The normal user should now see the cached data (If the browser requests username and password, keep clicking cancel)

The normal user can view all the cached data (if the admin user paged through results, the normal user can see all pages)

**Comment by gregoryyoung** [comment]
This is not sounding like an eventstore issue but as a cache issue ;-) You are not supposed to by default cache data with username/password and serve it. Likely its a configuration setting of whatever you are using.

Can you reproduce the same thing with curl and eventstore directly?

**Comment by xLasercut** [comment]
Curl does not have this issue since nothing is cached. But this works on both firefox and chrome (with default settings for the browser). The cached data displays even when the browsers ask for credentials which is very strange.

**Comment by gregoryyoung** [comment]
web browsers cache credentials.
