### ISSUE TITLE
Provide option to ensure scavenge always removes data

### ISSUE THREAD

**Issue by arobinson-alcumusgroup** [EventStore/EventStore#1570]
In order to comply with GDPR article 17 we have to ensure that we are able to remove a customer's personal information on request. This will include removing the data from all events.

We can achieve this by deleting entire streams of data, however as the scavenge only removes data from disk if it results in a smaller chunk it does not guarantee that the data is actually removed.

I request the ability to specify that this size check is bypassed and the scavenge always removes the data.

**Comment by gregoryyoung** [comment]
@shaan1337 @hayley-jean this is just adding a flag to check whether the chunk is smaller (as example --always-scavenge)

**Comment by hayley-jean** [comment]
There is a flag, `--always-keep-scavenged`, currently available that should achieve this.
This flag ensures that the scavenged chunks are kept even when they are larger than the original chunks.

Note that this can't affect the current chunk, as only closed chunks are scavenged

**Comment by arobinson-alcumusgroup** [comment]
We have tried it and it achieves what we need. Thanks for the help both.

**Comment by Narvalex** [comment]
Does @hayley-jean statement means that there is no way to delete a requested data from disk if the requested data belongs to a the current chunk?

**Comment by arobinson-alcumusgroup** [comment]
@Narvalex my understanding is that when the chunk containing the data is no longer the current chunk it can then be scavenged. Would be good to get confirmation on this.

**Comment by hayley-jean** [comment]
@Narvalex, @arobinson-alcumusgroup That is correct

If you have any data in the current chunk that is deleted, it will not be scavenged away.
Only when the current chunk has been completed and a new chunk is created will the data be removed by a scavenge.

You can find a bit more information about this in the scavenge docs [here](https://eventstore.org/docs/server/scavenging/).

**Comment by Narvalex** [comment]
Thanks @arobinson-alcumusgroup, @hayley-jean!
