### ISSUE TITLE
.net client api and netstandard

### ISSUE THREAD

**Issue by gingters** [EventStore/EventStore#1573]
Hello,

have you had a look at providing netstandard support for the client api as of yet?

I plan writing some .net core services and want to give EventStore a try, but the currently available nuget package is targeted at the full framework only, and while I did not test it on Linux yet, even if it would work, having a compiler warning all the time isn't that nice.

If you'd say it's okay, I'd give it a try and check what is required to bring the client over to netstandard, which can then be consumed by .net core libraries, applications and, of course, from the full framework as it is now.

Would you be willing to accept a PR on this?

**Comment by StevenBlair123** [comment]
We have been using it for months without any issues (Windows and Linux)

https://www.nuget.org/packages/EventStore.ClientAPI.NetCore/

**Comment by gingters** [comment]
Great. Thanks. I probably was confused because the full framework package is named `EventStore.Client` and not `EventStore.ClientAPI`, so I did not see that. In this case, all is good ;)
