### ISSUE TITLE
throw "Cannot access a disposed object" after restarted server

### ISSUE THREAD

**Issue by Julian-Chu** [EventStore/EventStore#1584]
Hello,
I am new in event store and have an issue. The situation ist in the following:
-Enviroment: web api .net core 2 + eventstore
-Dependentcy injection: 
`var eventStoreConnection = EventStoreConnection.Create(ipEndPoint);
services.AddSingleton<IEventStore>(y => new EventStoreOrg(eventStoreConnection, y.GetService<Router>()));`
-Steps:
1. do http post in web api, works correctly
2. restart eventstore but keep web api running, and do http post again, then throw "Cannot access a disposed object"

I guess  EventStoreConnection should be different after restarted(if not, please correct me)
So I should create new EventStoreConnection manually after restart, or another way can handle this well l?

`Cannot access a disposed object.\r\nObject name: 'ES-4cc66703-fdaf-4b96-9456-1fc6fbf39c7b'.\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter``1.GetResult()\r\n   
at Krones.MasterDataService.Infrastructure.EventStore.EventStoreOrg.<Get>d__4.MoveNext() 
in C:\\Users\\ychu\\Documents\\Source\\Repos\\PD.Services.MasterData\\src\\MasterDataService.Infrastructure\\EventStore\\EventStoreOrg.cs:line 91\r\n
--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task  
`

**Comment by jen20** [comment]
Hi @Julian-Chu, you'll likely need to ensure that your connection _reconnects_ after the disconnect it will receive when the server restarts. Can you post a wider context of your client construction?

**Comment by Julian-Chu** [comment]
Hello @jen20 
Thanks for very quick feedback.
1. This is the code block where Evenstore dependency injection
```C#
public static void RegisterEventStoreInfrastructure(this IServiceCollection services, IConfiguration configuration) {

      IPAddress ipAddress = IPAddress.Parse(configuration.GetSection("EventStoreConfiguration:IPAddress").Value);
      int port = Int32.Parse(configuration.GetSection("EventStoreConfiguration:Port").Value);
      IPEndPoint ipEndPoint = new IPEndPoint(ipAddress, port);

      var settings = ConnectionSettings.Create();//.LimitReconnectionsTo(10).FailOnNoServerResponse();
      var eventStoreConnection = EventStoreConnection.Create(settings, ipEndPoint);
      services.AddSingleton<IEventStore>(y => new EventStoreOrg(eventStoreConnection, y.GetService<Router>()));
      services.AddSingleton<ICache, MemoryCache>();
      services.AddScoped<IRepository>(y => new Repository(y.GetService<IEventStore>()));
      services.AddScoped<ISession, Session>();
    }
```
2. Here is the code to initialize EventStore and some methods, 
The "Cannot access a disposed object" issue happens on this line when I call Get() after restarted Eventstore;
```C#
currentSlice =
          await connection.ReadStreamEventsForwardAsync(aggregateId.ToString(), nextSliceStart, 200, false);
```

```C#
  public class EventStoreOrg : IEventStore
  {
    private readonly IEventStoreConnection connection;
    private readonly IEventPublisher publisher;

    public EventStoreOrg(IEventStoreConnection con, IEventPublisher publisher)
    {
      this.publisher = publisher;
      connection = con;
      connection.ConnectAsync().Wait();
    }

    public async Task<IEnumerable<IEvent>> Get(Guid aggregateId, int fromVersion, CancellationToken cancellationToken = new CancellationToken())
    {
      List<IEvent> result = new List<IEvent>();
      StreamEventsSlice currentSlice;
      long nextSliceStart = StreamPosition.Start;
      do
      {
        currentSlice =
          await connection.ReadStreamEventsForwardAsync(aggregateId.ToString(), nextSliceStart, 200, false);

        nextSliceStart = currentSlice.NextEventNumber;
        foreach (ResolvedEvent currentEvent in currentSlice.Events)
        {
          result.Add(Deserialize(currentEvent.Event.EventType, currentEvent.Event.Data));
        }
      } while (!currentSlice.IsEndOfStream);   
      return result.Where(e => e.Version > fromVersion);
    }
```
My plain is to use try block to catch ObjectDisposedException and then create new connection
I have tried KeepReconnecting(), but it makes program waiting  and no response until successful connection.

**Comment by Julian-Chu** [comment]
@Narvalex 
You are right, the connection will be closed during restarting eventstore. The close event has been triggered when I subscribed to it. You solution looks elegant, but  I choose try-catch for eventstore shut down for long time and then create new connection when new request comes in  after eventstore restart.

**Comment by Julian-Chu** [comment]
put some links here for reference and closed this issue

[Not possible to reopen Eventstore Connection? (ClientApi))](https://groups.google.com/forum/#!topic/event-store/z0RWBnBesoU)
[IEventStoreConnection: should be used as singleton?](https://groups.google.com/forum/#!searchin/event-store/reconnect|sort:date/event-store/Ct5gAtNj4cE/z_uTnQqLOEIJ)
#1324
