### ISSUE TITLE
Connection Pool for non-subscription uses

### ISSUE THREAD

**Issue by kspeakman** [EventStore/EventStore#1586]
For request/response command APIs, where I only load a specific stream and append new events, the guidelines to use a shared connection is problematic. It becomes awkward since it makes the handler(s) responsible for managing a shared resource... recreating it if finds it disconnected, or cleaning up if the connection fails on its watch. Plus issues when multiple handlers run at the same time.

The built-in mitigations like automatic reconnects and retries compound the problem in persistent failure cases by delaying errors being surfaced. Especially delaying the response back to the user. The better experience for the user is to fail immediately, and give them notice and the ability to retry later at their option.

The documentation mentions using a flyweight pattern. But this is essentially writing my own connection pooling logic. It would be great to see this provided out of the box, so that we aren't all reinventing the same wheel in these cases. Can work on a PR if interested.

P.S. Thanks for making EventStore and providing it as open source.

**Comment by bartelink** [comment]
Your comment in #1576 is an important addendum to what you're expressing here.

I believe your ask (which is basically mine in #1576) is actually _almost_ covered at this point:
- `FailOnNoServerResponse` (see #1576)
- `KeepConnecting` (existing)
- `KeepDiscovering` (will be in 4.1.1 client)
- `SetQueueTimeoutTo`  (see #1582, will be in 4.1.1 client)
- setting a request timeout
- setting a low (0/1) retry count

These together yield a relatively predictable behavior
- if the connection drops, the rediscovery instantly kicks in, regardless of whether you're feeding requests through
- a call's time will be limited to the queue timeout + the call timeout * (1+ retries)

It would be great if you could take your request above and these suggestions and formulate a request to go there - my sense is that either a paragraph of doc or higher level DSL helper that packages a set of coordinated settings as above (e.g. `.UseRequestProcessingMode(queueTimeout, callTimeout, retries)` ?) could cover our joint requirements, but we really need to be careful to not overload the config DSL or the docs...

**Comment by kspeakman** [comment]
An additional wrinkle. It was my every intention to run the command API on AWS Lambda. That means the API process gets suspended in between executions. And then it may wake up to a half-open connection. I'm curious what would fall out of that. (Would it add to overall request latency while the connection sorts itself out?)

It seems that the HTTP API might be my best bet. Especially for the command API, I was hoping to get the last drop of perf from the TCP API rather than the overhead of HTTP and parsing XML. Ironically, the .NET HttpClient documentation recommends that you reuse the same client instance for all requests. LOL.

**Comment by kspeakman** [comment]
Thanks for responding @jen20. A gRPC endpoint sounds like a great idea for request/response styles.

Some clarifications: I wasn't thinking of HTTP being a bottleneck, just higher latency. But it probably wouldn't make much difference if the TCP connection always had to reconnect anyway... the only minor increase in latency is parsing JSON or XML as opposed to protobuf. I was thinking half-open from the client's perspective since maybe it wasn't awake to receive the disconnect notice and would have to figure it out.

As you said, it seems that the HTTP API is perfect for the Lambda case.

Thanks.

**Comment by bartelink** [comment]
@kspeakman IME if a TCP conn drops, the reconnect seems pretty efficient in my tests (i.e. I kill with tcpview in a load test, and max latency is does not go to pieces - unfortunately I dont recall the OOM but wild guess says tens of ms); It may be worth testing to see if it actually turns out to be good enough.

**Comment by kspeakman** [comment]
I'm still a couple of iterations away from implementing this in the infrastructure. So I'll try both. Thanks!
