### ISSUE TITLE
maxSubscriberCount not checked when using HTTP API

### ISSUE THREAD

**Issue by prolic** [EventStore/EventStore#1587]
When I use the HTTP API and create a persistent subscription with `maxSubscriberCount` = 1, I can still use any amount of subscribers I want to. Is this intended so I have to check the limit myself somehow? Can this be enforced by passing the connection-name f.e. ?

**Comment by gregoryyoung** [comment]
maxSubscriber count only refers to the tcp connections, this should be better documented.
