### ISSUE TITLE
Competing Consumers - impossible to checkpoint after every event

### ISSUE THREAD

**Issue by drozzy** [EventStore/EventStore#1589]
Setting `MinToCheckpoint = 1` will only checkpoint the stream every 2 events. This is because (from the docs):

> the number of messages to checkpoint is greater than MinToCheckpoint

"1 message" is not greater than "1", so it will just sit there...

![screen shot 2018-04-06 at 11 08 56 am](https://user-images.githubusercontent.com/140710/38428919-f559c04c-398a-11e8-9b29-bad559471592.png)

That means, that if I want to checkpoint after just 1 event, it is not possible.

I tried setting `MinToCheckpoint = 0` but that just reverts it back to 10.

In my case, I have very few commands and they happened occasionally. It would be great to check-point after every event.

Using docker image of eventstore/eventstore:release-4.0.1.

**Comment by gregoryyoung** [comment]
I will try building a test case however:

Why do you want to checkpoint every message? Its not really a good idea in 99.99% of cases.

**Comment by drozzy** [comment]
I'm using persistent subscription as a bounded queue for back-pressure (https://ferd.ca/handling-overload.html section entitled "Bounded queues"). Instead of using another messaging system, I'm re-using ES.

The requests take minutes to process and there are not a lot of them - client might issue one request per day.

So I don't really need high throughput, but I do need the ability to ack/nack bad commands.

Happy to hear alternatives.

**Comment by gregoryyoung** [comment]
ack/nak has nothing to do with checkpointing? checkpointing only comes into play as marking something as completed so it won't be retried. If your handlers are idempotent it shouldn't make any difference what you set it to. If they are not idempotent checkpointing on every message will just make you less likely to the inevitable issues.

**Comment by drozzy** [comment]
They are idempotent, but only after performing work. I.e. my handlers do the actual work and then write the result as an single-event to a stream with a "new stream" semantics. So if there is already a stream, the write simply gets ignored.

The reason I want check-pointing to happen, is that I don't have to waste resources, upon restart, re-doing even 1 command's worth of work.

Now that I explain it "out loud", it seems better if my handlers check for existence of result stream first, before starting work. That would solve my issue by avoiding duplicate work. Thanks!
