### ISSUE TITLE
Metadata and content types

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#1593]
Is it intentional that EventStore always returns data's content type for metadata? `TcpClientMessageDtoExtensions.cs` has this defined:

```CSharp
var isJson = eventRecord.IsJson;
DataContentType = isJson ? 1 : 0;
MetadataContentType = isJson ? 1 : 0;
```

This makes Binary/Json and Json/Binary a no go.

**Comment by ahjohannessen** [comment]
@shaan1337 @gregoryyoung Would it be possible to allow for different types?

**Comment by jageall** [comment]
EventStore currently expects metadata to be json because it is used internally. So metadata is unfortunately json only by design

**Comment by ahjohannessen** [comment]
@jageall Are there plans to add support for different types?

**Comment by jageall** [comment]
there are plans in the future to separate out ES internal metadata from customer metadata in the future, but that involves a change to the storage format and there is some ongoing design around it. It is unlikely to happen inside the next year because of that.

**Comment by ahjohannessen** [comment]
Ok, thanks for heads up @jageall
