### ISSUE TITLE
Add wireshark plugin

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#1594]
A wireshark plugin that understood the TCP data would be very useful.

https://www.wireshark.org/docs/wsdg_html_chunked/ChDissectAdd.html

**Comment by gregoryyoung** [comment]
This repo also contains the code for looking at messages https://github.com/gregoryyoung/libesclient

**Comment by taion809** [comment]
I have been using https://github.com/x-cubed/event-store-dissector sometimes to do this but an officially supported eventstore plugin would be very useful indeed.

**Comment by jageall** [comment]
We are looking at moving to GRPC in the next version and the TCP client will eventually be removed in favour of the GRPC client
