### ISSUE TITLE
GRPC support

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#1596]
How about adding grpc support to make it easier to add client support?

https://github.com/grpc/grpc/blob/master/src/csharp/README.md

**Comment by avish0694** [comment]
Hi, @ahjohannessen, we have discussed internally about adding gRPC support for ES client APIs recently, We'll probably start to work on it soon.

**Comment by ahjohannessen** [comment]
@avish0694 That is great to hear! :)

**Comment by riccardone** [comment]
This is a task that is going to be implemented. At the moment there is not a timeline defined but we'll keep this issue up-to-date.

In the first implementation we will provide support for one of the existing subscription type probably the volatile.

**Comment by gregoryyoung** [comment]
I am not sure how much easier adding a client would be with GRPC. Most of the work involved with adding a client is in the handling of things like catch up subscriptions not so much the standard things like read/write. Just doing the basic operations I can already write a basic client in a day or two.

**Comment by ahjohannessen** [comment]
Greg, don’t you get a lot free wrt tcp / multiplexing, also a battle tested client eventually. Only keeping track subscription related code is refreshing.

**Comment by gregoryyoung** [comment]
@ahjohannessen to call the current client not battle tested is a bit of a jump its been in production for quite some time (what about 5 years?)

My point was that the serialization really has nothing to do with building a client (it makes up all of about 3% of the code). I actually agree that grpc would be a good serialization format and have started work on using it. What I disagree with is that it will make it easier to build a client. The largest effort in making a client has nothing to do with serialization or basic message exchange it has to do with things like building a catchup subscription which is logic on top. Building a basic client that can write/read is a day or two of effort at most in most languages (OK it took me about a week in C but thats much lower level code :))

**Comment by ahjohannessen** [comment]
Not all of us use C# ;) serialization is trivial, multiplexing and such not so much.

**Comment by ahjohannessen** [comment]
I agree that subscription logic is the most interesting part, I’ve implemented that myself in the ES scala client.

**Comment by ahjohannessen** [comment]
But I still think gRPC is a good choice wrt implementing clients

**Comment by gregoryyoung** [comment]
It would not be a replacement it would be an *additional* protocol. At the very least the current wire format would be supported for a few years. We don't change it very often so I am not worried about the duplicated effort etc.

**Comment by gregoryyoung** [comment]
and btw @ahjohannessen I was the one pushing internally to *do* gRPC just for different reasons. Don't take what I wrote as not agreeing that its a good idea.

**Comment by gregoryyoung** [comment]
in particular the higher level of specification it provides (and the documentation that can be generated). As you likely know the ES protocol is a mix of sync and async messaging with protobufs. Being able to explicitly declare it as such is quite useful in allowing people to pick up the underlying protocol without having to go through the underlying code to discover how it works.

Because of the higher level of abstraction it also makes creating a new client quite a bit easier. Still non-trivial (think catchupsubscription) but much easier.

**Comment by ahjohannessen** [comment]
Yeah, great points :)

**Comment by gregoryyoung** [comment]
specifying where to put them is a < 1 hour change. I will put a card up for it.

**Comment by ahjohannessen** [comment]
Thanks Greg :)

**Comment by gregoryyoung** [comment]
@ahjohannessen that shouldn't be a big deal Want to put up a card for it? I would estimate the placing somewhere else (say /tmp) as an option to be a few hours at most. Likely it would be in the next release.

**Comment by lisp-ceo** [comment]
Has there been any progress? Happy to spike this out if it’s still on the roadmap?

**Comment by jen20** [comment]
There is some progress, in the wider context of the roadmap, however there is no shipping date available yet.

**Comment by mat-mcloughlin** [comment]
Closed by mistake

**Comment by jageall** [comment]
This is being added in v6

**Comment by mat-mcloughlin** [comment]
Need to think about user management calls as part of the new GRPC work

**Comment by ahjohannessen** [comment]
@mat-mcloughlin Administrative tasks like scavenging are also interesting to consider in the grpc work :)

**Comment by mat-mcloughlin** [comment]
Closed by #2012
