### ISSUE TITLE
How to get an exception if Server is not available while having KeepReconnecting activated

### ISSUE THREAD

**Issue by GibSral** [EventStore/EventStore#1599]
Hi,
i am using the .net client. 
I want to get an exception on AppendToStreamAsync if the server is not available while having KeepReconnecting active so my application knows that the events were not sent.
I tried different combinations but i get no exceptions.
`                var connectionSettings = ConnectionSettings
                    .Create()
                    .KeepReconnecting()
                    .SetOperationTimeoutTo(TimeSpan.FromSeconds(1))
                    .LimitRetriesForOperationTo(1)
                    .LimitAttemptsForOperationTo(1)
                    .FailOnNoServerResponse()
                    .UseConsoleLogger()
                    .Build();`

The only solution that i know of at the moment is to use single "throwaway" connections for the write model for each AppendToStreamAsync and reconnecting connections for my projections.
Is there a better way?

Thanks in advance 
Lars

**Comment by bartelink** [comment]
> `.LimitRetriesForOperationTo(1).LimitAttemptsForOperationTo(1) .`
these are mutually exclusive, I believe (not the problem, just saying)

I believe the feature I implemented in https://github.com/EventStore/EventStore/pull/1582 will cause it to honour the timeout if you use `SetQueueTimeoutTo` (the existing behavior only ever applied the `SetOperationTimeoutTo` setting after >1 successful trip to the server)

If that still does not accomplish your goal (for my system I need the same behavior), I'd view that as a bug in my impl and would like to fix it.

**Comment by shaan1337** [comment]
This has been fixed with https://github.com/EventStore/EventStore/pull/1769
