### ISSUE TITLE
Missing CatchUp subscription drop events

### ISSUE THREAD

**Issue by mereth** [EventStore/EventStore#1602]
Hi,

The "Catch Up" subscriptions drop event is only triggered the first time a subscription lose its connection to the EventStore. If the connection reconnect successfully, the subscription recover and a "live processing started" event is triggered, then the subscription process new incoming events successfully, but will not trigger the subscription drop event if it lose the connection again. But it will trigger the new "live processing started" events.

The problem seems located in `EventStoreCatchUpSubscription.EnqueueSubscriptionDropNotification` method, with the errorneous `Interlocked.CompareExchange` test, but I'm not sure if the bug is the missing event, or the undocumented subscription recover mecanism, unlike the "Live" subscriptions.

Regards

**Comment by jen20** [comment]
Hi @mereth! Thanks for reporting this, we'll investigate and report back on this ticket.

**Comment by hayley-jean** [comment]
This issue was fixed by #1936
