### ISSUE TITLE
Quorum is lost and does not re-elect when master node process is hung

### ISSUE THREAD

**Issue by lscpike** [EventStore/EventStore#1604]
Reproduction steps:
1. Start a 3 node cluster on your local PC.
2. Wait for a quorum to form and find the master node from the cluster status page.
3. Using process explorer (sysinternals procexp.exe) suspend a slave node process.
4. Note how the slave node is considered dead (correctly).
5. Resume the slave.
6. Suspend the master node.

Expected result:
The node should be considered dead. The remaining slaves should elect a new master.

Actual result:
The cluster status page shows the slaves in prereplica and the master is flip flopping between dead and alive.

We've had this situation occur in production when having low memory situations. See #1603. I was doing some sanity testing on 4.1 and manged to reproduce it.

**Comment by gregoryyoung** [comment]
We will try to reproduce but this smells more like a test harness failure. We have tests that do this explicitly via power pulls.

**Comment by gregoryyoung** [comment]
Logs?

**Comment by lscpike** [comment]
Sorry not as reproducible as I thought. Took a couple of attempts but it hit it in the end:

[127.0.0.1-1114-cluster-node.log](https://github.com/EventStore/EventStore/files/1931820/127.0.0.1-1114-cluster-node.log)
[127.0.0.1-2114-cluster-node.log](https://github.com/EventStore/EventStore/files/1931822/127.0.0.1-2114-cluster-node.log)
[127.0.0.1-3114-cluster-node.log](https://github.com/EventStore/EventStore/files/1931823/127.0.0.1-3114-cluster-node.log)

**Comment by lscpike** [comment]
Here's the command line I used: 
EventStore.ClusterNode.exe -Db .\data1 --log .\logs\log1 --int-ip 127.0.0.1 --ext-ip 127.0.0.1 --int-tcp-port=1111 --ext-tcp-port=1112 --int-http-port=1113 --ext-http-port=1114 --cluster-size=3 --discover-via-dns=false --gossip-seed=127.0.0.1:2113,127.0.0.1:3113 -RunProjections All -StartStandardProjections

Env:
Windows 10 Enterprise x64
.Net 4.7.1

**Comment by gregoryyoung** [comment]
Thanks will look through them.

**Comment by avish0694** [comment]
This is not reproducible on latest master. Tried on MacOS
