### ISSUE TITLE
the same event received multiple times using ConnectToPersistentSubscription 

### ISSUE THREAD

**Issue by projektsdb** [EventStore/EventStore#1605]
There is a windows service that reads events from Even Store. It uses ConnectToPersistentSubscription (.NET) to get events from Event Stream. 

```
 Connection.ConnectToPersistentSubscription(_eventStreamName, _eventGroup, 
                (subscription, resolved) => EventAppeared(subscription, resolved), SubscriptionDropped, _userCredentials, bufferSize, autoAck);
```

However, if method EventAppeared is too slow, then next time service receives the same event. Thus the same events appear multiple times.

What is the solution?

**Comment by gregoryyoung** [comment]
This is by design... There are configuration points for things like when to retry.

**Comment by projektsdb** [comment]
And what is the best practice? Just increase some timeout configuration or other solutions?

**Comment by gregoryyoung** [comment]
f(x) = f(f(x))

Handlers should be idempotent.

**Comment by gregoryyoung** [comment]
This is not just eventstore btw its pretty much every messaging system. Eventstore assure atleast-once-delivery. You are assured to receive a message but may receive it multiple times.

**Comment by shaan1337** [comment]
@projektsdb hello, kindly note that we're closing this issue since it seems resolved. please feel free to reopen if you're still facing any problems.

**Comment by VibinKesavan** [comment]
> f(x) = f(f(x))
> 
> Handlers should be idempotent.

Hi @gregoryyoung,  Is there any known pattern around idempotency of event handlers  ? "There are configuration points for things like when to retry." , may I know what are those plz ?

**Comment by gregoryyoung** [comment]
There are many patterns. As example using something from the event in an insert (event id could be useful here :-D)

The subject however is a vast one and often situational.

**Comment by mcfriend99** [comment]
I'm having the same event replaying for days with this method event after acknowledgment. I am also seeing parked events return in an eternity loop.

Please help
