### ISSUE TITLE
Wiki doc link broken

### ISSUE THREAD

**Issue by Jopie64** [EventStore/EventStore#1608]
Hi,

Currently the wiki link to the new docs location is broken, because the documentation has moved again.
"The page you are currently viewing" link should point to https://eventstore.org/docs/event-sourcing-basics/

If you'd made that wiki page a projection of the web-page aggregate, it could have handled the 'WebPageLocationChanged' event and updated the link accordingly :laughing:

**Comment by shaan1337** [comment]
@Jopie64 hello, please note that we're closing this issue since it's no longer applicable - we no longer show the Wiki pages on github. thanks!
