### ISSUE TITLE
Verifying database backups

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#1616]
An easy way to verify that a backup (or restore) is complete & usable without spinning-up a node from it

ripping out the validation code from TFChunk into a tool

custom checks
checking checkpoints compared to the log

a C# executable EventStore.Verifier.exe

**Comment by shaan1337** [comment]
This is being developed internally.

**Comment by gregoryyoung** [comment]
How is usable defined? I know we can easily do checksum checks etc but that does not mean things are usable.

**Comment by timonwalkley** [comment]
Hey @riccardone, was this ever released? We're still super interested in something like this to verify backups.
