### ISSUE TITLE
NLog AsyncWrapper configuration potentially causing synchronous logging

### ISSUE THREAD

**Issue by GojiSoft** [EventStore/EventStore#1627]
Hi @shaan1337 

I've been trouble-shooting performance issues with 4.1.1 and looking at what has changed from 4.1.0. There is a change to the NLog config to use the "AsyncWrapper" target instead of the "async" attribute. I believe that when using the AsyncWrapper wrapper target this instance must be referred to in the NLog rule, rather than the inner target which it wraps.  Referring to the inner target causes log entries to be written synchronously according to the docs:

https://github.com/nlog/NLog/wiki/AsyncWrapper-target#asyncwrapper-and-rules

The new NLog config in 4.1.1 is referring to the inner target rather than the AsyncWrapper targets.

Thanks, Tim.

**Comment by snakefoot** [comment]
Yes instead of adding asyncwrapper explicitly, then one should can use a `default-wrapper`:

```
<targets>
    <default-wrapper xsi:type="AsyncWrapper" overflowAction="Grow" />

    <target .. />
    <target .. />
</targets>
```

See also https://github.com/NLog/NLog/wiki/Performance

**Comment by shaan1337** [comment]
Hi @Gojisoft

Thanks, what you're saying looks right - we'll investigate about this urgently.

@snakefoot thanks we'll test this configuration

**Comment by GojiSoft** [comment]
Hi @shaan1337 

Thanks for the prompt reply and proposed fix. In terms of impact of the issue, we had a production system completely fail at peak time over two days as it was writing logs to relatively high-latency storage (i.e. network storage). There may be other users who could have this situation and may need notifying of the issue and risk in 4.1.1.

Thanks, Tim.

**Comment by shaan1337** [comment]
Hi @GojiSoft thanks for the details

We have just made a hotfix release: 4.1.1-hotfix1
