### ISSUE TITLE
SubscribeToStreamFromAsync as User to a not yet existing $by_category stream

### ISSUE THREAD

**Issue by Reris** [EventStore/EventStore#1630]
_Probably this counts for SubscribeToStreamAsync etc too._

I'm trying to use useraccounts to distinguish subscribers from each other and to use a minimal rights system in a CQRS/ES way with microservices. 
Thus, I need some listeners to react to all events a service is interested in. CatchUpSubscriptions to a $by_category projection stream are the perfect way to do that.

But unfortuenatly, as soon as i SubscribeToStreamFromAsync to a stream like **$ce-offers**, 
```c#
await connection.SubscribeToStreamFromAsync("$ce-offers", null, true, this.OnEventAsync, null, this.SubscriptionDropped)
```
it instantly drops the subscription with a 
_EventStore.ClientAPI.Exceptions.AccessDeniedException: Read access denied for stream '$ce-offers'_

**This only happens**
If the stream is not yet existing
_- and -_ 
the given user (both by credentials and/or in the connectionstring) is a simple user.

**It works**
As soon as we have some data
_- or -_ 
If the user is _admin_.

I'm currently in the development stage of the solution, so I can use admin as a workaround.
But this seems most likely to be a bug. 
If not, please give me a hint how to create a listener without using admin rigths or inserting dummy data.
Thx :)

Event Store 4.1.1.0
$by_category is the only projection enabled and running (otherwise it wouldnt work at all (; )

**Comment by jageall** [comment]
By Design

**Comment by Reris** [comment]
:(
