### ISSUE TITLE
Write performance: 4.0.3 vs 4.1.0 and influence of watching the stream in web UI.

### ISSUE THREAD

**Issue by jezovuk** [EventStore/EventStore#1634]
We've noticed a significant slow-down in event write speed upon upgrade from EventStore version 4.0.3 to 4.1.0.

Testing across 3 desktop workstations and one server instance shows time increase between 30% and 500% (for writing fixed number of events).

Demo project is attached (executable JAR and Eclipse project; zipped separately). It is a simple Java / Spring Boot application using [esjc](https://github.com/msemys/esjc) as client library. It writes fixed number of events to one stream, then reads those events, then reads them again and re-emits them to another stream and finally re-reads them again and create links on yet another stream. Each of those steps is timed separately. All reads and writes/appends are synchronous.

Our testing results, along with description of each machine used in tests, are in attached Excel file. Those results represent run timings (minutes/seconds) per EventStore version, per run, per machine. Timing is done for 20000 events. There was also some additional timing across 3 more PCs, and some more with smaller number of events (1000 and 4000) on one of the PCs. All show similar pattern. (Those results are not included in the workbook). All testing is done with single EventStore node run locally (always on same machine as test jar) with all default settings.

Another funny thing is that writes tend to go much faster (around 5 times faster) if target stream is watched via the web UI (auto-refreshing page displaying stream's events). It literally goes faster if you look at it. This is mostly noticeable for EventStore versions 4.1.0 and above; much less (if at all) for 4.0.3. For 4.1.0+ speed (with stream open in web UI) approaches that of 4.0.3.

Tested with 4.1.1-hotfix1 as well with same results.

Note that attached project/JAR is configured to work with 4000 events in order to reduce overall execution time (still more than enough to illustrate the behavior on our hardware).

[jar.zip](https://github.com/EventStore/EventStore/files/2027494/jar.zip)
[project.zip](https://github.com/EventStore/EventStore/files/2027495/project.zip)
[Results-20000.xlsx](https://github.com/EventStore/EventStore/files/2027501/Results-20000.xlsx)

**Comment by shaan1337** [comment]
@jezovuk thanks very much for your report and all the details, we're working on this.

**Comment by gregoryyoung** [comment]
So I spent some time reading through the tests and they aren't really valid. These tests will be completely controlled by network/disk latency as they send one request then wait on it. In other words these tests are measuring latency not throughput.

If you look in the distribution there is an application called testclient. We can reproduce (and run other tests) using it. As example when you run it

WRFL 1 5000 will write 5000 events on a single thread
WRFL 5 10000 will write 10000 events on 5 threads etc.

What do you see when running the test client? Note I would also use larger data sizes like say 100,000 events

**Comment by megakid** [comment]
Just a quick note without having seen the environment or results you’re getting, we have extensive latency and throughput metrics on our ES clusters and since upgrading to 4.1.0.X we haven’t seen any upticks in these (outside of the 4.1.1.X sync logging bug). We are running high message rates at ~400 avg and ~2,000 peak messages per second.

**Comment by shaan1337** [comment]
Hi @jezovuk 

I've run your application on my machine and it produces the following results (this is on Ubuntu).
There seems to be only around a 5-7% overhead. I'll also try on Windows.
```
oss-v4.0.3
2018-05-23 12:30:46.738  INFO 7998 --- [           main] estest.test.EventStoreTest               : StopWatch 'All': running time (millis) = 68198
2018-05-23 12:30:46.740  INFO 7998 --- [           main] estest.test.EventStoreTest               : StopWatch 'Write': running time (millis) = 21461
2018-05-23 12:30:46.741  INFO 7998 --- [           main] estest.test.EventStoreTest               : StopWatch 'Read': running time (millis) = 1193
2018-05-23 12:30:46.741  INFO 7998 --- [           main] estest.test.EventStoreTest               : StopWatch 'Read/Write': running time (millis) = 22660
2018-05-23 12:30:46.742  INFO 7998 --- [           main] estest.test.EventStoreTest               : StopWatch 'Link': running time (millis) = 22881

oss-v4.1.0
2018-05-23 12:34:28.994  INFO 11882 --- [           main] estest.test.EventStoreTest               : StopWatch 'All': running time (millis) = 75025
2018-05-23 12:34:28.996  INFO 11882 --- [           main] estest.test.EventStoreTest               : StopWatch 'Write': running time (millis) = 23556
2018-05-23 12:34:28.997  INFO 11882 --- [           main] estest.test.EventStoreTest               : StopWatch 'Read': running time (millis) = 1094
2018-05-23 12:34:28.998  INFO 11882 --- [           main] estest.test.EventStoreTest               : StopWatch 'Read/Write': running time (millis) = 24615
2018-05-23 12:34:29.000  INFO 11882 --- [           main] estest.test.EventStoreTest               : StopWatch 'Link': running time (millis) = 25755

oss-v4.1.1-hotfix1
2018-05-23 12:37:09.957  INFO 14816 --- [           main] estest.test.EventStoreTest               : StopWatch 'All': running time (millis) = 75322
2018-05-23 12:37:09.959  INFO 14816 --- [           main] estest.test.EventStoreTest               : StopWatch 'Write': running time (millis) = 23900
2018-05-23 12:37:09.961  INFO 14816 --- [           main] estest.test.EventStoreTest               : StopWatch 'Read': running time (millis) = 1140
2018-05-23 12:37:09.962  INFO 14816 --- [           main] estest.test.EventStoreTest               : StopWatch 'Read/Write': running time (millis) = 24996
2018-05-23 12:37:09.963  INFO 14816 --- [           main] estest.test.EventStoreTest               : StopWatch 'Link': running time (millis) = 25281
```

**Comment by shaan1337** [comment]
Thanks for all your tests @jezovuk We have tracked down the issue to a `Thread.Sleep` call that incurred additional latency. The actual latency differences varied a lot from system to system, probably because of the underlying implementation (< 1ms on Ubuntu to ~10ms on a Mac and 40ms on a windows vm)

**Comment by jezovuk** [comment]
That's great news. Thanks for the effort!
👍

**Comment by jezovuk** [comment]
Any news regarding this?

**Comment by jezovuk** [comment]
I've re-run the tests with version 5.0.0. My original test project shows same performance as with version 4.0.3-hotfix1, while TestClient WRFLW is somewhat slower than with 4.0.3-hotfix1, but much faster than with 4.1.1-hotfix1.

Thanks!

**Comment by shaan1337** [comment]
@jezovuk thanks for the feedback!

**Comment by shaan1337** [comment]
Do you have any numbers (just to get a rough idea)?

**Comment by jezovuk** [comment]
My test project (4000 events):

```
======================================
4.0.3-hotfix1 (without UI/YT)
======================================

---------------------------------------------------
          ms     %     Task name
---------------------------------------------------
00:00:23.873  038%  Write
00:00:01.656  003%  Read
00:00:23.436  038%  Read/Write
00:00:13.405  021%  Link

======================================
4.1.1-hotfix1 (without UI/YT)
======================================

---------------------------------------------------
          ms     %     Task name
---------------------------------------------------
00:01:03.354  033%  Write
00:00:01.640  001%  Read
00:01:02.869  033%  Read/Write
00:01:02.604  033%  Link

======================================
5.0.0 (without UI/YT)
======================================

---------------------------------------------------
          ms     %     Task name
---------------------------------------------------
00:00:24.654  039%  Write
00:00:01.703  003%  Read
00:00:23.529  037%  Read/Write
00:00:13.499  021%  Link
```

TestClient WRFLW 1 5000 (no UI/YT):

```
4.0.3-hotfix1: 5000 requests completed in 29911ms (167.16 reqs per sec, latency: 5.98 ms).
4.1.1-hotfix1: 5000 requests completed in 78714ms (63.52 reqs per sec, latency: 15.74 ms).
5.0.0:              5000 requests completed in 29357ms (170.32 reqs per sec, latency: 5.87 ms).
```

It seems that WRFLW is now also same between 4.0.3 and 5.0.0. I've based previous comment on comparison between today's run with 5.0.0 and original run on 4.0.3 (with timings posted in one of my previous comments here).

**Comment by jezovuk** [comment]
Note that I now have windows folder compression enabled for EventStore data folder (wasn't so for original runs), so that might influence numbers somewhat. OTOH, same folder is used for all ES versions, so it should not influence relative ratio of timings between versions.

**Comment by shaan1337** [comment]
@jezovuk thanks very much!
