### ISSUE TITLE
fromStreams() projection state lost when eventstore restart

### ISSUE THREAD

**Issue by patrickinminneapolis** [EventStore/EventStore#1645]
I am using EventStore 4.1.1-hotfix1 ...
My $by_category & $stream_by_category separator is \@  
-- I have two projections -- 
**SimpleExample.proj:**

```
fromStream('$ce-0..0')
.when({
    '$init':function(){
      return {count: 0};
    },
    '$any':function(s,e){
            s.count = s.count + 1;
            emit("simpleExample", "countUpdate",
		    {
		        count : s.count
		    }, {});
    }
})

```
**ComplexExample.prj:** 

```
fromStreams('$ce-0..0', 'simpleExample')
.when({
    '$init':function(){
      return {count: 0};
    },
    '$any':function(s,e){
            s.count = s.count + 1;
            emit("complexExample", "countUpdate",
		    {
		        count : s.count
		    }, {});
    }
})

```
---
I am writing events that start with 0..0@blahblah therefore $ce-0..0 is getting events.
Behavior: 
When I fire an event I get an entry in $ce-0..0, and my counter goes up by 1 (for simple) and 2 for (complex)... this is working.... but when I restart only simple has the correct counter, complex goes back to zero.

**Comment by oskardudycz** [comment]
@hayley-jean, could you have a look at that if it isn't already fixed?

**Comment by hayley-jean** [comment]
@patrickinminneapolis Thanks for the clear reproduction steps!
I think PR#2345 should have fixed the issue with loading up the state, at the very least I can't reproduce this locally any more.
Could you try this on version 20.10.5 or 21.10.1 and let me know if you're still seeing the issue?
