### ISSUE TITLE
Centralized Config handling: Add a new parameter --http-config (HttpConfig)

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#1660]
Add a new parameter --http-config (HttpConfig) to EventStore that downloads a custom config from the internet (also adjust the precedence hierarchy)

**Comment by gregoryyoung** [comment]
We should also define some information that we send UP to the httpconfig provider (including the ability for custom parameters)

**Comment by jageall** [comment]
Closing this for now as the questions and issues that might be caused by trying to secure a remote config and troubleshooting what happens when it is not available are fairly broad
