### ISSUE TITLE
Azure Continuous WebJob for persistent subscriptions not behaving... 

### ISSUE THREAD

**Issue by ppumkin** [EventStore/EventStore#1661]
I am raising an issue here since on StackOverflow its tumble weed

https://stackoverflow.com/questions/50930508/eventstore-c-sharp-client-in-azure-webjobs

I have a Full Fat .NET 4.6.1 console app that when I run it locally it will subscribe to a persistent subscription and works as expected. 

In the Azure WebJob it will connect, maybe get an event but not always, and even if it gets the event it does not ACK it.. it will just close the connection

> Close Reason: [Success] Connection close requested by client.

```
using (var conn = EvenStoreConnection.Create....)))
{
  con.ConnectAsync().Wait();

  con.ConnectToPersistentSubscription(STREAM, GROUP, (_,X) =>
  {
    int en = x.EventNumber;
   }
}
```

As soon as I converted the project to be a Azure WebJob (Continuous) everything works as expected in terms of the app starting and getting to always running state. Just for reference this is how its bootstrapped in Program.cs

```
var host = new jobHost(config);
host.Call(typeof(Functions).GetMethod("Processmethod"));
host.RunAndBlock;
```

The `host.Call()` is just a manual way to call the method in which the code with EvenStoreConnection.Create is called. Inside there, whether I have `Console.ReadLine()`, `while (true)` or nothing, since the `host.RunAndBlock()` is basically the same doesnt matter.

I enabled verbose logging and nothing special is visible there. I have a bad feeling that whatever is in ConnectToPersistentSubscription() to create a persistent connection Azure may be closing it, or ignoring whatever created this long running connection??

I added some more events today and this is the tail of the verbose logging 
I noticed my dear friend, **System.NullReferenceException** as the last message. 

```
[11,09:31:39.590,DEBUG] TcpPackageConnection: connection [0.0.0.0:1112, L192.168.1.67:51469, {b126de8b-36b9-40ac-924f-0b61b29a0957}] was closed cleanly.
[11,09:31:39.593,DEBUG] EventStoreConnection 'ES-02cf806c-ba75-4361-943e-0b48fbc2e302': enqueueing message EventStore.ClientAPI.Internal.TcpConnectionClosedMessage..
[11,09:31:39.596,DEBUG] EventStoreConnection 'ES-02cf806c-ba75-4361-943e-0b48fbc2e302': IGNORED (_state: Closed, _conn.ID: {b126de8b-36b9-40ac-924f-0b61b29a0957}, conn.ID: {b126de8b-36b9-40ac-924f-0b61b29a0957}): TCP connection to [0.0.0.0:1112, L192.168.1.67:51469] closed..
[11,09:31:39.599,INFO] EventStoreConnection 'ES-02cf806c-ba75-4361-943e-0b48fbc2e302': Closed. Reason: Connection close requested by client...
[11,09:31:39.600,DEBUG] EventStoreConnection 'ES-02cf806c-ba75-4361-943e-0b48fbc2e302': IGNORED (_state: Closed, _conn.ID: {00000000-0000-0000-0000-000000000000}, conn.ID: {b126de8b-36b9-40ac-924f-0b61b29a0957}): TCP connection to [0.0.0.0:1112, L192.168.1.67:51469] closed..
19:45:23.1900 #4 -> PersonAddressAdded' StreamID 'CustomerAggregate+d1b8d47c-e245-49e1-a417-758825bebebd

EventType = PersonAddressAdded

DATA
{"Address":{"Type":"Home,Work,Emergency,Etc","StreetLine1":"","StreetLine2":"Random Address -1","PostTown":"Chester","Locality":"Cheshire","PostCode":"SK10 1AA","Country":"United Kingdom"},"Id":"f0ef37c0-77dd-4098-9a04-584585ce8f29"}

META
{"CreatedBy":"test"}

[18,09:31:39.744,DEBUG] Persistent Subscription to leistream: dropping subscription, reason: EventHandlerException System.NullReferenceException: Object reference not set to an instance of an object.
   at EventStore.ClientAPI.ClientOperations.SubscriptionOperation`2.EnqueueSend(TcpPackage package)
   at EventStore.ClientAPI.ClientOperations.ConnectToPersistentSubscriptionOperation.NotifyEventsProcessed(Guid[] processedEvents)
   at EventStore.ClientAPI.EventStorePersistentSubscriptionBase.<ProcessQueue>d__32.MoveNext().
```

**Comment by gregoryyoung** [comment]
ConnectToPersistentSubscription just sends a message over TCP. This the Azure deciding your job is done I guess.

I do note however that your code here seems to end after creating the subscription. So your function will be considered ended (and the function over). For fun try adding a 
while(true) { Thread.Sleep(100) ;}

Does it then work normally?

**Comment by ppumkin** [comment]
I do have 
`while(true) { Thread.Sleep(100) ;}` and that makes no difference 

I had it inside the using and outside the using. I even verified that that thread was blocked before the Azxure SDK's runAndWait thing. It is inside the running inside the while loop but the connection drops, everytsingle time, straight away. I just see a small blip on the event store status but nothing changes.

**Comment by ppumkin** [comment]
_sigh_

Just for sanity I went in and put the while true inside the using... and it works now. 
I am a n00b I cannot believe this I spent a whole day on this. :(

**Comment by gregoryyoung** [comment]
Note sure what that may look like but sure we can review it.

**Comment by ppumkin** [comment]
I have added a repository here with example. Sorry I thought your source had examples in it.. I have been looking at some many things previous few weeks its all a blur now. 

Maybe can look at adding something into documentation for reference.

https://github.com/ppumkin/EventStoreAzureWebJobPersistentSubscriber

And a blog post here 

http://pkula.blogspot.com/2018/06/eventstore-persistent-subscriptions.html

**Comment by ppumkin** [comment]
@gregoryyoung here is fine or email as you prefer :)

**Comment by gregoryyoung** [comment]
Why do I prefer email?

**Comment by ppumkin** [comment]
Sorry, I meant either here or email - Your preference, I do not mind either way. 
That code has been running fine since I pushed it as a WebJob. 
The more I use and learn about EventStore the more I love it. It is difficult to find information on some topics though.

**Comment by ppumkin** [comment]
Been running for 20 days stable now. I did a few updates on the code though need to update my repo but looking good now.

**Comment by shaan1337** [comment]
@ppumkin please note that we're closing this issue since it seems resolved. if you're still facing the problem please do not hesitate to reopen it. thanks
