### ISSUE TITLE
Couldn't acquire exclusive lock on DB at '.\ESData' on Windows on a second running instance

### ISSUE THREAD

**Issue by Narvalex** [EventStore/EventStore#1665]
The issue is not about clustering. Is more about multi tenancy, like mentioned here #907. Maybe this is also related to #40 .
Steps to reproduce:
1. Unzip the latest database executables (version 4.1.1 hotfix) on two diferent directories, like
 - Instance 1: C:\Databases\FolderOne\
 - Instance 2: C:\Databases\FolderTwo\
2. Run the first instance from the cmd passing the following params, [like in the docs](https://eventstore.org/docs/server/index.html): `EventStore.ClusterNode.Exe --db .\ESData`
3. Run the second instance from cmd the same way as before  `C:\Databases\FolderTwo\EventStore.ClusterNode.Exe --db .\ESData`

**Comment by gregoryyoung** [comment]
You cant have two nodes on the same machine pointing at the same db path.

**Comment by Narvalex** [comment]
They are poiting in the same path. 
The first points to: `C:\Databases\EventStore1\` and the second to `C:\Databases\EventStore2\`

**Comment by gregoryyoung** [comment]
See above.

**Comment by gregoryyoung** [comment]
If not clear its talking about the DATA directory not where the .exe lives.

**Comment by Narvalex** [comment]
But the data directories are different, right? one points to: `C:\Databases\EventStore1\ESData` and the other to `C:\Databases\EventStore2\ESData`. These are totally different directories.

**Comment by Narvalex** [comment]
In the new docs there is a [warning tha says](https://eventstore.org/docs/server/default-directories/index.html):

> Paths beginning with "." are relative to the directory in which eventstored or EventStore.ClusterNode.exe are located. Absolute paths are as written.

**Comment by Narvalex** [comment]
If you will, you can try it and see it for yourself.

**Comment by Narvalex** [comment]
![image](https://user-images.githubusercontent.com/11648387/41980890-9cdda720-79f5-11e8-94e8-72bd4a2495da.png)
Your can see in the console of the left the database init succeeded with the params. And in the left the database failed with the same params, but on different folder

**Comment by Narvalex** [comment]
I eddited the orignal post the folder name to be more explicit, but they where different folders in my orignal post, as you can see in the post history (Github now shows to everyone the history of the posts)

**Comment by Narvalex** [comment]
But isnt the ./ESData related to the exe file?

**Comment by bklooste** [comment]
Why is it related to the exe ? In Windows that is normally a read only location ( C:\ProgFiles\) .  .. I would expect %appdata% or %temp%

**Comment by Raithybabes** [comment]
Does this depend on the point at which .\EsData. is converted to a full path?
Does your command pass the string ".\EsData" to the exe where it is converted?
Or does the command line interpret .\EsData and pass the full path to the exe?

Please try again but change your working directory before executing the second instance
i.e.
```sh
cd C:\Databases\FolderTwo\
EventStore.ClusterNode.Exe --db .\ESData
```

**Comment by Narvalex** [comment]
this is how I start event store from my executable:
```
 this.dbProcess = new Process()
            {
                StartInfo =
                {
                    UseShellExecute = false,
                    RedirectStandardOutput = !this.showLog,
                    FileName = @".\EventStore\EventStore.ClusterNode.exe",
                    Arguments = this.args,
                    Verb = "runas",
                }
            };

            this.dbProcess.Start();
```
What is exactly wrong there, please?

**Comment by Narvalex** [comment]
Thanks @nicdex  for your answer. I think that you are referring to start two instances from the same executable, if I undertood well. Sorry if is not the case or I could not explain myself well. My first language is spanish and I am strugling a lot with english... 
What I can not understand is why there is a problem when I have two differents instalations of event store (two separate executables), both obviously located in two different directories.
i.e.
C:\DbOne\EventStore.ClusterNode.exe
C:\Db2\EventStore.ClusterNode.exe

When I pass the **same relative path** parameters but with differents ports, they node that starts second crashes.
i.e.
--db .\data --int-tcp-port 1112 --ext-tcp-port 1113 --int-http-port 2112 --ext-http-port 2113
--db .\data --int-tcp-port 1122 --ext-tcp-port 1123 --int-http-port 2122 --ext-http-port 212

The last one will crash with a 'Couldnt acquire exclusive lock'. Why? I think that since the executables are located in different directories and are started with different working directories they shoulnt behave like that. I posted screenshots of that before in this same thread.

**Comment by nicdex** [comment]
Because like I explained, relative path for the data (--db) parameter is relative to the WorkingDirectory. So set the WorkingDirectory of your StartInfo class to the path of where the executable is.

In C#

for first EventStore set WorkingDirectory to "C:\DbOne"
for second EventStore set WorkingDirectory to "C:\Db2"

In a shell (cmd on windows) the equivalent is:

CD C:\DbOne
EventStore.ClusterNode.exe --db .\data

CD C:\Db2
EventStore.ClusterNode.exe --db .\data

Running C:\DbOne\EventStore.ClusterNode.exe --db .\data is NOT the equivalent of changing the working directory. Working directory is the current folder you are in, as given by ECHO %CD%

**Comment by Narvalex** [comment]
It woked. Thanks for all your patience, @nicdex !

**Comment by Narvalex** [comment]
Sorry, I forgot to pass in the parameters. I did not worked. See screenshots please.
This is before runing them. Note that they are "cd" in their own locations
![image](https://user-images.githubusercontent.com/11648387/44280573-2ef28180-a223-11e8-9dd4-038b6b3c96c0.png)

**Comment by Narvalex** [comment]
Please, try running like this. It does not work. Lockint error apperars in the last node to run
![image](https://user-images.githubusercontent.com/11648387/44280783-b50ec800-a223-11e8-8b07-f7fe39258782.png)

**Comment by nicdex** [comment]
Well you use port 1113 and 2113 on both instances so it wont work.

**Comment by Narvalex** [comment]
Fixed that, sorry. Still not working.
Before runing:
![image](https://user-images.githubusercontent.com/11648387/44281195-f94e9800-a224-11e8-91ec-1a45d7d1a703.png)
After running:
![image](https://user-images.githubusercontent.com/11648387/44281231-12574900-a225-11e8-841d-6f76e0f11464.png)

**Comment by Narvalex** [comment]
This happens only when I pass the the custom parameter ' --db .\something'. When I use defaults no problem. That is the workaround that I am using now.

**Comment by gregoryyoung** [comment]
Is it possible that you are accidentally passing the same parameter --db to both? It would be expected behaviour to get this error if you did its exactly what it is supposed to prevent.

**Comment by Narvalex** [comment]
I am passing the same parameter (--db .\) to both on porpuse, since the working directory for each of them is different, and they are two separate executables, not even the same exe file.
i.e:
--db .\data
for 1st instace  the relative path is C:\Db1
for 2nd instace the relative path is C:\Db2

so lock should be on "C:\Db1\data" for the fist instance,
and for the second the lock should be in "C:\Db2\data"

but is not.

**Comment by nicdex** [comment]
The path should be converted to an absolute path before being used as a mutex name.

**Comment by nicdex** [comment]
Actually the Windows behavior is the correct one, except that the mutex name should use absolute path instead of relative path.

In linux the lock actually doesn't work. I can run ./run-node.sh --db ./data twice in the same folder and it doesn't crash as long as I pass different tcp/http ports.

Named Mutex don't work on Mono for linux. See https://aakinshin.net/blog/post/namedmutex-on-mono/

**Comment by Narvalex** [comment]
Interesting....! Do you mean that in Linux two instances will try to write to the same file as long as you pass different ports? What is the correct approach (for someone who will try to make a PR) to solve this issue? Try to get the actual full path of the location and then aquire the named mutex?

**Comment by Narvalex** [comment]
Oh... i forgot, thanks a lot @nicdex !
