### ISSUE TITLE
No .NET Client method for resetting projections

### ISSUE THREAD

**Issue by ChrisChinchilla** [EventStore/EventStore#1671]
As far as I can tell, Event Store has an HTTP endpoint for sending the reset command to a projection when you update it's code:

```
curl -i -X POST "http://localhost:2113/projection/xbox-one-s-counter/command/reset" -H "accept:application/json" -H "Content-Length:0" -u admin:changeit
```

But I can't find anything similar in the .NET client, does it need to be added, or is there another way to reset with the .NET client?

**Comment by riccardone** [comment]
Reset method to be added in
EventStore.ClientAPI.Projections.ProjectionsManager
