### ISSUE TITLE
High latency master does not trigger re-elections

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#1674]
Any thoughts are welcome on this issue.

**Elections are currently triggered when the following conditions occur:**

* A master node becomes "unknown" and triggers elections when the number of slave subscriptions becomes lower than the quorum size (after losing TCP connections to slaves)
  [https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/Replication/MasterReplicationService.cs#L503](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/Replication/MasterReplicationService.cs#L503)
* A slave node triggers elections when it loses the TCP connection to the master
  [https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/VNode/ClusterVNodeController.cs#L701](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/VNode/ClusterVNodeController.cs#L701)
* Although the master might look dead, as long as the TCP connection is maintained, elections are not triggered:
  [https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/Gossip/GossipServiceBase.cs#L186](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/Gossip/GossipServiceBase.cs#L186)

**Consider the following scenario:**

* The latency to master has increased significantly (e.g. 500ms-1000ms) but the TCP connections remain alive
* From EventStore logs, slaves' gossip requests to the master tend to fail with the following error (exact cause of this error is not clear, but probably related to timeouts):

```
Error occurred while replying to HTTP with message EventStore.Core.Messages.GossipMessage+SendGossip: The specified network name is no longer available.
```

* Elections are not triggered since TCP connections are still alive although a potentially better master could have been elected among the 2 slaves if the latency between them is still normal.

**Proposed solution**
An option could be added: `--max-gossip-fails` to trigger elections after the specified number of failures.
Constraints:

* When choosing the best master candidate, it seems that there currently is no notion of `latency`/`previous failures` involved. So the same master might be elected again and we would end up in a loop. This notion would need to be added to `GetBestMasterCandidate`
  [https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/ElectionsService.cs#L377](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/ElectionsService.cs#L377)

<sub>[DB-365](https://linear.app/eventstore/issue/DB-365/high-latency-master-does-not-trigger-re-elections)</sub>

**Comment by shaan1337** [comment]
After some more thought, just adjusting the `internal tcp heartbeat timeout` to a reasonable value should close the connections and trigger elections again. However, the issue of the previous master being elected again still remains.

**Comment by timothycoleman** [comment]
agreed with hayley and alexey to close this for now since its quite old
