### ISSUE TITLE
Can I run EventStore with Non-Admin user?

### ISSUE THREAD

**Issue by vnextcoder** [EventStore/EventStore#1675]
hi 

I have got this command executed by my Administrator on Windows box 

netsh http add urlacl url=http://+:2113/ user=domain\user

Now coming back to my own id, I am unable to start EventStore as it continues to ask for User Elevation everytime I want to run EventStore.

pleease help

**Comment by mat-mcloughlin** [comment]
Hey, @vnextcoder is this still an issue for you or has it been resolved?

Please re-open if you are still facing this issue.
