### ISSUE TITLE
Question: Problem subscribing to $all

### ISSUE THREAD

**Issue by prolic** [EventStore/EventStore#1677]
I ported your EventStore.ClientAPI.NetCore to PHP. In the EventStoreNodeConnection there is this method `subscribeToAllAsync` which does this:
```
new StartSubscriptionMessage(source, string.Empty, resolveLinkTos, userCredentials, eventAppeared, subscriptionDropped, Settings.MaxRetries, Settings.OperationTimeout));
```

note the `string.Empty`. So if the subscription is an empty string, then the subscription is for `$all` stream. In the `VolatileSubscriptionOperation` class, the value is passed as is: `var dto = new ClientMessage.SubscribeToStream(_streamId, _resolveLinkTos);`.

So I am doing the exact same thing in PHP:

In the `subscribeToAllAsync`-method:
```
        $deferred = new Deferred();

        $this->handler->enqueueMessage(new StartSubscriptionMessage(
            $deferred,
            '',
            $resolveLinkTos,
            $userCredentials,
            $eventAppeared,
            $subscriptionDropped,
            $this->settings->maxRetries(),
            $this->settings->operationTimeout()
        ));

        return $deferred->promise();
```
and in the `VolatileSubscriptionOperation`:
```
$dto = new SubscribeToStream();
$dto->setEventStreamId($this->streamId);
$dto->setResolveLinkTos($this->resolveLinkTos);
```
Problem comes, when I try to subscribe the message, I can see the following in the event-store-server logs:

```
Error while processing message EventStore.Core.Messages.ClientMessage+SubscribeToStream in queued handler 'Subscriptions'.
Value cannot be null.
Parameter name: key
```

When I subscribe to any other stream (not empty string), then the subscription works as expected. Did I miss something? Any help is really appreciated.

**Comment by gregoryyoung** [comment]
There is a different message for subscribe to all than subscribe to stream.

**Comment by prolic** [comment]
@gregoryyoung I was looking for that already, and there is only `https://github.com/EventStore/ClientAPI.NetCore/blob/master/src/EventStore.ClientAPI.NetCore/Messages/ClientMessage.cs#L1053` which is also used here: https://github.com/EventStore/ClientAPI.NetCore/blob/master/src/EventStore.ClientAPI.NetCore/ClientOperations/VolatileSubscriptionOperation.cs#L17-L24

**Comment by prolic** [comment]
see also this: https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Messages/ClientMessage.cs#L1270-L1276

there is even the comment about empty string for subscription to all stream. In TcpCommand enum there is also no other entry for another command.

**Comment by prolic** [comment]
ping @gregoryyoung any ideas?

**Comment by gregoryyoung** [comment]
reviewing now.

**Comment by prolic** [comment]
@gregoryyoung I found it!

The problem comes indeed from me using protobuf 3 while event store uses protobuf 2. The field `event_stream_id` is required, but when an empty string is given (and everything is optional in protobuf 3), the value is null and not empty string.

I think a solution to support protobuf 3 for clients as well, is to make the field optional instead of required (but I didn't compile event-store for testing this, yet).

At least downgrading to protobuf 2 works for me (although not officially supported by google for PHP, I need to use another library for that).

What would you think about making the value `event_stream_id` optional?

**Comment by gregoryyoung** [comment]
@prolic when would event_stream_id ever not be included? That's why its not optional :)

**Comment by prolic** [comment]
In protobuf 3 everything is optional, there are no required fields. An empty string will not get included, hence the error.

**Comment by prolic** [comment]
@gregoryyoung

**Comment by prolic** [comment]
@gregoryyoung To sum up. As is, it's not possible to use protobuf 3 in the client with EventStore. The reason is, that there are no required fields in proto3 format and when you try to submit an empty string, it's just omitted. Using proto3 format will produce an error when subscribing to `$all` stream:

```
Error while processing message EventStore.Core.Messages.ClientMessage+SubscribeToStream in queued handler 'Subscriptions'.
Value cannot be null.
Parameter name: key
```

All other commands work without any problem, because there is no other place where an empty string is a requirement of the message. Just because of this single command, everyone is forced to use proto2 format (which in PHP f.e. is not officially supported by Google devs, so we have to use other libraries). A possible solution to allow proto3 format for the client would be, to make the `event_stream_id` an optional field. This way I can submit a message without this field and the server should interpret this as empty string then. If you are not willing to change this, this would mean noone can use proto3 (for the client) for even store communication.

**Comment by shaan1337** [comment]
@prolic we have added a simple workaround in the above PR. can you please test it with your proto3 php client (i've also done some internal tests by simulating the scenario). If you need a custom build, please let me know. thanks!

**Comment by prolic** [comment]
@shaan1337 @jageall Sorry for coming back to it this late. I can confirm this is working like a charm now. Good job!
