### ISSUE TITLE
Backups with corrupted chunks

### ISSUE THREAD

**Issue by matteo-guindani** [EventStore/EventStore#1683]
Greetings,
we have an ES installation (ver. 3.9.4) which undergo a scheduled backup every hour.
We check regularly these backups and too often they contain corrupted chunks:

```
[01048,01,12:09:01.295] Unhandled exception while starting application:
Corrupt database detected.
 Chunk file '.\ESData\chunk-000241.000000' should be completed, but is not.
Corrupt database detected.
[01048,01,12:09:01.327] Exiting with exit code: 1.
Exit reason: Corrupt database detected.
 Chunk file '.\ESData\chunk-000241.000000' should be completed, but is not.
```

In theory, we shouldn't need to stop ES to execute a backup but it seems that these chunks change during the process, making them unusable. For your information, ES files are copied in the correct order (.chk first, then chunks, then indexes).

Is there a way to avoid these corrupted chunks? Thanks in advance for your help.

**Comment by ahjohannessen** [comment]
What kind of filesystem are your storing backup chunks on? 

We do the following to avoid corruption: Use ZFS with snapshots and transfer these with ZFS send/recv to backup servers also running ZFS. Reason being is that it protects against bit flips and so on.

**Comment by ahjohannessen** [comment]
@gregoryyoung @jen20 I think you guys should advice people in the docs to use ZFS for ES data as it is awesome. As @jen20 once said, if you care about your data use ZFS.

**Comment by ahjohannessen** [comment]
Our setup is a bit crazy and paranoid, we have a 3-way ES cluster, where each Linux server is bare metal with SSD data ZFS mirrors and HDD storage ZFS mirrors, then we have a bare metal backup server with HDD ZFS mirrors that gets snapshots frequently, similarly we also have a VM backup server with a storage ZFS mirror from two vdisks.

We use a tool called znapzend with the following retention setup:

```
SRC         '4h=>5min,7d=>1h,30d=>6h' -- SSD mirror
DST:storage '4h=>5min,7d=>1h,30d=>4h,90d=>1d' -- HDD mirror
DST:remote1 '4h=>5min,7d=>1h,30d=>4h,90d=>1d' -- HDD mirror
DST:remote2 '4h=>5min,1d=>1h' -- virtual disk mirror
```

We also mount last ZFS snapshots for source servers each 15 minute on the VM backup server and rsync to a local EXT4 vdisk and have VEEAM take backup of that VM each 4 hour, 14 days retention. 

When we get green light from regulations to ship data to AWS, we are going to kill the VM and have servers send zfs snapshots to AWS Linux.

**Comment by matteo-guindani** [comment]
We finally found the source of the problem: the corruption was caused by a problem during the unzip phase of the backup. Thank you everybody for your help :)
