### ISSUE TITLE
Cannot manage projections with URL unsafe characters from UI

### ISSUE THREAD

**Issue by willg1983** [EventStore/EventStore#1684]
I created a projection using a base64 encoded string as a name, the projection was created successfully but it appears to have created problems in the UI (or eventstore itself) such that I cannot manage or delete the projection:

![image](https://user-images.githubusercontent.com/12110310/43384840-1bafe84c-93d7-11e8-9b63-c4ac3dd055ac.png)

The projection cannot be opened:

![image](https://user-images.githubusercontent.com/12110310/43384866-30cc7f56-93d7-11e8-84d6-0108789672e0.png)

and no actions can be performed on it:

![image](https://user-images.githubusercontent.com/12110310/43385016-944e419a-93d7-11e8-9d65-cead491919ab.png)

I'm guessing its URL unsafe characters in the base64 encoding, but I'm not sure what the problem is exactly. 

I would expect it to either encode it in a way that does not break the UI or to refuse to create the projection.  I would not expect it to create the projection but leave it in an unmanageable state.

**Comment by mat-mcloughlin** [comment]
Closing this in favour of #804
