### ISSUE TITLE
EventStore.ClientAPI.Embedded for .net core

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#1685]
It would be great if you could join this and the netcore client repos together, to enable cross compilation of the embedded event store and the client.

**Comment by bartelink** [comment]
See aso https://github.com/EventStore/EventStore/pull/1680

**Comment by haf** [comment]
I've compiled that PR locally and looked at it:

 1. I can't find the netcore code in it
 2. It doesn't do netcore for embedded es at all
 3. Even when I cross-compile the netcore client repo, everything works both for net471 and netstandard2.0 targeting, so having a separate compilation unit is probably just legacy that should be removed.

**Comment by chillitom** [comment]
Not having a way to connect an embedded store from netcore projects is the only thing holding us back from upgrading many projects to dotnet core as all of our test suites rely on it.  Would be great to see the connectors converge and include support for embedded stores.

**Comment by jen20** [comment]
We now have an internal plan to move to .NET Core. This will proceed in three phases:

1) unification of the .NET Core and existing client codebase and packages (in progress now)
2) port of the server to .NET Core as is
3) optimisation for .NET Core.

The embedded client will not be done until phase 2 - we don’t have a timescale on that yet.

**Comment by jen20** [comment]
I'm going to close this out in favour of #1716 which will track progress of Event Store on .NET Core, in order that we have a single place to discuss and report progress on that issue. Please feel free to subscribe to #1716 to keep track of it.

**Comment by haf** [comment]
What's the state of the embedded client on .net core?

**Comment by jen20** [comment]
It will be supported in version 6. A release candidate of this should be available around the end of November, with a target of shipping at the end of this year or the start of the following year.
