### ISSUE TITLE
Add embedded client method for scavenge

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#1689]
Its a pretty small task but useful for people who may not expose tcp/http interfaces. Looking in the http client the message needed can be seen we just need a wrapper to raise the same message iternally from the embedded client.

**Comment by alexeyzimarev** [comment]
If the embedded version is deprecated forever, we need to consider closing this issue.

**Comment by oskardudycz** [comment]
As there is no work currently done in this area, I'm closing the issue. We can reopen it if the Embedded client is revived.
