### ISSUE TITLE
HTTPS Admin Interface with Proxy

### ISSUE THREAD

**Issue by MadKat13** [EventStore/EventStore#1691]
Hello together

Is it possible to run Eventstore in a configuration that allows us to get on it via HTTPS (admin-interface). 

So basically we have a Google load balancer with a self signed certificate that redirects traffic from https:443 to http:2113 on the Eventstore-VM.

When I set the option ExtHttpPortAdvertiseAs: 443, the UI gets loaded but the credential entry doesn't work. Any experience how to setup HTTPS for the Admin-Interface would be appreciated. 

Edit: It's a single node cluster on Linux

**Comment by MadKat13** [comment]
Ok It was resolved. For everyone reading:

I had configure Eventstore to use a different external port:
```
ExtHttpPort: 443
ExtHttpPrefixes: http://*:443/
```

The loadbalancer is also running on 443 but with https.

In addition I had to allow the service to bind to a low port with:
`sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/eventstored`

**Comment by itninja-hue** [comment]
@Mad-Kat  hey !! i am encountering the same problem , i have a elb with ssl termination and an ingress controller that handles ingress resources on eks, i used helm chart to install eventstore release-4.1.1-hotfix1,  if i navigate to https://pathtoeventstore.com i get redirected to http://pathtoeventstore.com.
Any leads ??
