### ISSUE TITLE
Branching with event store?

### ISSUE THREAD

**Issue by t3dodson** [EventStore/EventStore#1693]
Hello,

A feature of eventsourcing is the ability to branch your graph. I'm not seeing the way to do this using eventstore.

My thoughts were to use different streams to make different branches. Or capture the branch information in the events themselves.

Is this a problem solved by eventstore? Any help is appreciated.

**Comment by gregoryyoung** [comment]
There are multiple ways of doing timelines you mention two of them. Another common one is to write an event in the original stream pointing to a "new timeline" as of that point (note it can retroactively change things as well).

This is not really an eventstore question. I have yet to see an event sourcing timeline pattern it can't support (though I can think of some interesting ways to *better* support some).

**Comment by t3dodson** [comment]
Thanks for clarifying
