### ISSUE TITLE
Replace EventStore.ClientAPI internal queues with a System.IO.Pipelines based impl

### ISSUE THREAD

**Issue by bartelink** [EventStore/EventStore#1694]
[This article by @mgravell](https://blog.marcgravell.com/2018/07/pipe-dreams-part-3.html) describes  a scheme it seems can be applied pretty directly to replace the series of queues and timer threads being used in `EventStore.ClientAPI` at present - while the code is non trivial, it's nonetheless simple in terms of its protocols and likely would yield a significant efficiency boost under load from parallel threads (e.g. in a web serving context where lots of request threads all talk to a common EventStore connection over the same ultimate socket).

While this is not quite an up-for-grabs thing, from having worked in there a few months back, the current layout of the code around this queue management / dispatching is in pretty good shape to facilitate such a seemingly massive change without as much drama as one might imagine based on the length of the article in question.

I don't have capacity to take this on at present and hence thought I'd put the suggestion here in case anyone else fancies it as a very interesting programming challenge (I have a testbed that can be used to verify any improved perf which I'm going through some red tape to open source atm - if anyone does end up doing this, I'm up for testing it if I have not yet released that by the time it happens).

**Comment by bklooste** [comment]
Doesn't this work hand in hand with Zero copy buffers /  MemoryPool<T> and hence require a replacement or addition of buffers / memory management ( At least for the incoming messages) .

**Comment by jen20** [comment]
We have plans to do this internally post-Core CLR port.

**Comment by jageall** [comment]
The current plan is to phase out support for the current incarnation of the .net client and move to grpc. The new client will be available in the next release and the old client will be available for a period after.
