### ISSUE TITLE
.NET Client API method to update projection configuration

### ISSUE THREAD

**Issue by sadegr** [EventStore/EventStore#1695]
I am trying to programmatically set the configuration settings listed on the projections [Config](https://eventstore.org/docs/projections/projections-config/index.html) page for a user defined projection. Specifically, I am trying to set the [Checkpoint Handled Threshold](https://eventstore.org/docs/projections/projections-config/index.html#checkpoint-handled-threshold). The aforementioned page states
> These options are accesible [sic] through the admin UI from the Config tab when editing a projection.

I have not been able to find a way to set this particular option (Checkpoint Handled Threshold) programmatically, however.

The [projections HTTP API](https://eventstore.org/docs/projections/api/index.html) allows a user to create a projection and define only the following parameters for it: `name`, `type`, `enabled`, `checkpoints`, `emit`, and `trackemittedstreams`.

The [User Defined Projections](https://eventstore.org/docs/projections/user-defined-projections/index.html#options) page lists only the following options that can be defined as part of the projection definition: `resultStreamName`, `$includeLinks`, `reorderEvents`, and `processingLag`.

There is also the .NET API's [`EventStore.ClientAPI.Projections.ProjectionsManager`](https://eventstore.org/docs/code/EventStore.ClientAPI.Projections.ProjectionsManager.html) class, but it doesn't seem to have a way to provide a custom value for the Checkpoint Handled Threshold setting, either. Neither does the [`EventStore.ClientAPI.Projections.ProjectionDetails`](https://eventstore.org/docs/code/EventStore.ClientAPI.Projections.ProjectionDetails.html) class.

Am I just missing something or is there no way to set the Checkpoint Handled Threshold (and several of the other options listed on the projections [Config](https://eventstore.org/docs/projections/projections-config/index.html) page) for a projection programmatically?

**Comment by sanderdegroot** [comment]
Just as I suspected, I was in fact just missing something. Here is the HTTP API method I need to use:
[Update Projection Config](https://eventstore.org/docs/http-api/swagger/Projections/Update%20projection%20config.html)

I would like to note that I find it very unhelpful that several parameters are listed in the Projections section of the documentation with no mention of how to set them, other than a page buried deep inside the HTTP API section of the documentation.

**Comment by sanderdegroot** [comment]
I am actually going to reopen this issue as I would like to see a similar method to update projection config in the .NET API.

**Comment by riccardone** [comment]
@ChrisChinchilla is improving/rewriting the documentation 
It will not be difficult to add a method in the api to update projections.

**Comment by shaan1337** [comment]
@sadegr Ability to get/update projection config from the C# client has been added in the above PR. thanks

**Comment by sadegr** [comment]
Thank you!

**Comment by cdavernas** [comment]
Hello everyone!
I have the need to update the options of system projections when my client boots up, and the feature added by [#1885](https://github.com/EventStore/EventStore/pull/1885) seem to be missing from the GRPC ProjectionManagement client v22.

Am I missing something?
