### ISSUE TITLE
Unit test debug assert issue in debug builds

### ISSUE THREAD

**Issue by jageall** [EventStore/EventStore#1701]
There are some tests that don't use a thread safe publisher causing this https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Messaging/PublishEnvelope.cs#L20 assertion to fail.

an example of a test:
https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core.Tests/Helpers/IODispatcherTests/ReadEventsTests/async_read_stream_events_backward_with_cancelled_read.cs#L28

the build process is only building release, so the CI build never sees this problem. on windows it manifests itself as dozens of "do you want to debug" popups...

**Comment by jen20** [comment]
We should adjust AppVeyor to build and test Debug builds also.
