### ISSUE TITLE
Where is the run-node.sh shell script ?

### ISSUE THREAD

**Issue by kgrosvenor** [EventStore/EventStore#1734]
Just want to enable projections in ubuntu 18.04 :D

For LD_LIBRARY_PATH i have "/usr/lib/", what should this be then?

Few pointers would be of great use but i also think the documentation for set up could be a little more detailed to explain this more, i've tried a couple paths but with failure so far!

**Comment by jen20** [comment]
Hi @kgrosvenor - you shouldn't need a script to do this - If you install from the Ubuntu packages, you should be able to set `--run-projections=all` as part of the command in the systemd unit or the equivalent in the configuration file.

The various `run*` scripts are in the process of being removed by #1710, so using them is discouraged.

I'll go ahead and close this issue out - if you have further problems please post to the mailing list (see https://eventstore.org for a link) - we try to keep the issue tracker to bugs and feature development.
