### ISSUE TITLE
Large Index Merge to be triggered manually

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#1738]
During an Index Merge operation, writes can be slowed down

To avoid this issue, we can call merges manually. In this way it will be possible to schedule a job at midnight

There will be a command line option (--no-automerge-index or similar) then an http endpoint that forces a merge to happen

**Comment by ChrisChinchilla** [comment]
@riccardone Let me know when docs needed :)

**Comment by riccardone** [comment]
This is solved by
https://github.com/EventStore/EventStore/pull/1638

**Comment by shaan1337** [comment]
Fixed with: https://github.com/EventStore/EventStore/pull/1842
