### ISSUE TITLE
Stream soft "undeletion" is not done in a single transaction

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#1744]
### Scenario:
Consider the following scenario:
1. Soft delete a stream `s`
2. Write an event to stream `s` and wait for the write acknowledgement
3. Immediately read from stream `s` or stream `$$s` (metadata stream) (of the order of milliseconds, e.g. through the Client API)

When reading metadata events from stream `$$s`, truncate before may still be set to long.MaxValue.
Thus when reading from `s`, the read may result in a `StreamNotFound`.

This is because soft "undeletion" is not done in the [same transaction](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/Storage/StorageWriterService.cs#L298) as the event write.

The event write may be acknowledged without the metadata being updated on the stream yet.

### Potential issues:
- A node/network failure occurs after the event write but before the metadata update event (to update `truncateBefore`), resulting in the metadata event not being written to disk. The client will receive the write acknowledgement for the event and assume that the write was successful. When the node is back online, it will appear that the stream is still soft deleted (contains no events)

(Note: This failure scenario has not been tested but `EventStore.Core.Tests.ClientAPI.soft_delete` tests confirm the above behaviour)

**Comment by oskardudycz** [comment]
Based on discussion with @hayley-jean, that won't be probably fixed for the current log, it may be included in the Log V3. We also haven't seen that as an issue from customers (so far).

**Comment by condron** [comment]
This will be addressed with the new log features.
