### ISSUE TITLE
MaxAge can be set "too high".

### ISSUE THREAD

**Issue by jbradford** [EventStore/EventStore#1748]
During reading a stream, scavenging (and likely other operations), the ES server calculates `DateTime.UtcNow - metadata.MaxAge.Value`, for example.

https://github.com/EventStore/EventStore/blob/7e98bd4206d5b0aec0cbc24d12002dfe195643fe/src/EventStore.Core/Services/Storage/ReaderIndex/IndexReader.cs#L104

If the MaxAge value in the metadata is larger than `DateTime.UtcNow - DateTime.MinValue` then this will throw `System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.`

It would be useful to either guard against this exception in the code, OR to prevent setting the metadata that high in the first place.

**Comment by pgermishuys** [comment]
Hey @jbradford. How did you come across this issue? Closing this for now due to the issue being old. Please reopen if you believe it's something crucial that needs fixing.
