### ISSUE TITLE
NLog throwExceptions=true should not be used in production

### ISSUE THREAD

**Issue by snakefoot** [EventStore/EventStore#1766]
https://github.com/EventStore/EventStore/blob/7e98bd4206d5b0aec0cbc24d12002dfe195643fe/src/EventStore.Common/Log/log.config#L5

It is only intended for unit-testing, and last-resort troubleshooting.

Instead replace it with:

`throwConfigExceptions="true"`

**Comment by shaan1337** [comment]
@snakefoot thank you for the tip, we're going to add `throwConfigExceptions="true"` to this PR:
https://github.com/EventStore/EventStore/pull/1678

**Comment by snakefoot** [comment]
Resolved with  #1678
