### ISSUE TITLE
An event emitted in recovery for stream differs from the originally emitted event. Existing('$>', 'C:8246386847/P:8246386847'). New('$>', 'C:8204724375/P:8204724375')

### ISSUE THREAD

**Issue by hanxinimm** [EventStore/EventStore#1768]
![image](https://user-images.githubusercontent.com/13499426/48486956-d6e60e00-e857-11e8-8e57-605cdf950c1d.png)

I think the projection is fragile.
There have been frequent problems recently.

**Comment by shaan1337** [comment]
@hanxinimm thanks for your report. can you please confirm the eventstore version you were using at that time?

**Comment by MrJoe** [comment]
Just to chime in, we just got this same error "An event emitted in recovery for stream $et-$metadata differs from the originally emitted event. Existing('$>', 'C:311748690227/P:311748690227'). New('$>', 'C:311748682179/P:311748682179')" on the projections on version 4.1.1.0 (linux).

**Comment by pgermishuys** [comment]
@shaan1337 given that @MrJoe got this on 4.1.1.0 means that there is another cause for this issue. Might require further investigation.

**Comment by oldskool** [comment]
Confirming that this issue still exists on v5.0.5-1 (commercial) for Linux as well.
We managed to recover it with help from [this post](https://groups.google.com/forum/#!msg/event-store/QjeDTKoCMbQ/6tKDscoAAQAJ) on the Google Groups page.

By going to the checkpoint stream of crashed projections (through the web UI using the `/streams/$projections-<projection_name>-checkpoint` endpoint), then look at the last event there, click the "Add New Like This" button and change the event number(s) for `$c` and/or `$p` to the ones mentioned in the error message (in the "Existing" part of it). Then re-starting the projection, it seemed to gradually move along. We needed to repeat this process a few times for most projections, but eventually all of them are now running again and processing events.

**Comment by aaron-0** [comment]
@YoEight did this fix end up making it into a 5.0.x release or only a 20.x release?

I tried looking through the release notes and couldn't find it. We are currently running 5.0.5 and getting this error.

**Comment by YoEight** [comment]
@aaron-0 I double checked and indeed while we did backported many projections fixes https://github.com/EventStore/EventStore/pull/2592, that specific patch wasn't in the mix.

**Comment by YoEight** [comment]
The reason being it was harder to backport because of other changes made to projections prior that patch.

**Comment by aaron-0** [comment]
@YoEight no worries, thanks for the reply

**Comment by vietkute02** [comment]
@hayley-jean thank for your support. This error not repeat, i will keep my eye on this. But with me, error from Eventstore hard to know reason :(
