### ISSUE TITLE
TLS support limitations on EventStore node

### ISSUE THREAD

**Issue by davehl7** [EventStore/EventStore#1770]
Setup of SslProtocols statically selects used TLS versions. This causes:
a. Higher (future) standards will not be used automatically.
b. Older (risky) protocols aka TLS 1.0 are always supported which causes security downgrade.

TLS setup is done using the following code fragment:
(see EventStore.Transport.Tcp.TcpConnectionSsl class, InitServerSocket method)
    var enabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Default;

Using SslProtocols.Default is problematic -- see See “Transport Layer Security (TLS) best practices with the .NET Framework” on https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

It would be also great if the TLS setup can be done manually via configuration (command line + yaml). This would allow application to comply with higher security requirements, eg. to suppress (deprecated) TLS 1.0.

**Comment by jageall** [comment]
We are going to switch to grpc which will only operate over the newer protocols in the long term so this will go away
