### ISSUE TITLE
$et-$metadata stream contains incorrect links

### ISSUE THREAD

**Issue by rcknight** [EventStore/EventStore#1772]
$by_event_type projection does not produce a $et-* stream for most system event types, but $metadata events do ($et-$metadata exists in our production instance).

The links in that stream are wrong (pointing to the correct event number but in the actual stream, not the metadata stream).

![screenshot 2018-11-15 at 10 52 41](https://user-images.githubusercontent.com/548432/48548357-ac7e6a00-e8c4-11e8-95cb-56f20b14f3ba.png)

Presumably it is hitting this codepath:
https://github.com/EventStore/EventStore/blob/master/src/EventStore.Projections.Core/Standard/StreamDeletedHelper.cs#L39

**Comment by Robbert** [comment]
We have encountered this issue too: we wanted to subscribe to `$et-$faulted` for logging in New Relic, but we had to listen to the `$projections-$master` stream instead.

**Comment by oskardudycz** [comment]
I'm closing it due to inactivity.
