### ISSUE TITLE
Projection not faulted when difference between projection checkpoint and head of stream is large (> ~100)

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#1776]
Creating this issue for followup, this is a bit different but related to #1468 

This bug has been reported and tested consistently with the following components:
- StreamEventReader (confirmed) `fromStream('singlestream')`
- MultiStreamEventReader (confirmed) `fromStreams('stream1','stream2')`
- AllStreamsCatalogReader (untested) `$streams projection`

Reproduction steps (for single stream, similar steps for multistream):
1. Create a stream `test`, write 10 events
2. Create a projection that reads from stream `test` and start it
3. Stop the projection, it should checkpoint at last event (event 9)
4. Set a $maxCount of 2 on `test`
5. Write 1000 events to `test` (the last event should be event 1009)
6. Start the projection

**Expected Result:**
The projection should fault with the error message:
`Event number 10 was expected in the stream test, but event number 1008 was received. This may happen if events have been deleted from the beginning of your stream, please reset your projection`

(because the last event processed is 10 and the next event being processed is  1008)

**Actual Result:**
The projection does not fault

**Reason:**
Initial investigation and fix in #1773 shows that the root cause is that the first read will return no events and the stream reader will assume that it's an end of stream - this messes up the next expected event check.

Fixes are in progress:
StreamEventReader - #1773
MultiStreamEventReader - wip
AllStreamsCatalogEventReader - wip

**Comment by jageall** [comment]
@shaan1337 does #2447 fix this?

**Comment by ylorph** [comment]
Closing as this is now a valid case and fixed by #2447
