### ISSUE TITLE
Add "Ensure strict event ordering" projection option

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#1777]
This is related to the error in #1468 

Currently the expected behaviour is that a projection should fault if it is processing non-contiguous events. (due to deleted events with $maxAge/$maxCount) However due to #1776 this does not work properly.

The proposal is to add a per projection UI checkbox setting: "Ensure strict event ordering" that will be set to `false` by default.

Depending on the use case, some projections may need to ensure strict event ordering (e.g. if doing an operation that depends on each event in the stream like a sum). However some do not require strict event ordering (e.g. a stateless projection that just needs the last event from the stream to update its state)

The default behaviour will be set to `false` since we expect that most users adding a $maxAge or $maxCount and running a projection on this stream will expect that some events may be deleted and they probably do not require strict event ordering.

**Comment by shaan1337** [comment]
Partially fixed with: https://github.com/EventStore/EventStore/pull/1774 (this is a global option instead of a per-projection setting proposed in this issue)

**Comment by oskardudycz** [comment]
It's possible that `$maxAge/$maxCount` stuff is fixed by the recent maxAge handling for reads. `Ensure strict event ordering` is not. The issue should stay open for now.

**Comment by ylorph** [comment]
we're unlikely to do this.
- if $maxage / $maxcount , there are bound to be gaps and there is no way to fix that after the fact.
Also this would require to enable on a projection level that users to actually knows 
1) they are deleting events 
2) they need to set such flag to true.
- and still when the condition of $maxage / $maxcount  is passed, it's too late . 
this is also not really an ordering problem, it's a gap detection between 2 events .
