### ISSUE TITLE
Not prompted for auth when using HTTP API

### ISSUE THREAD

**Issue by daniellittledev** [EventStore/EventStore#1778]
It appears as though a number of endpoints on the HTTP API don't prompt for authentication.

Routes pointing to the UI do prompt for auth.
`http://localhost:2113/`

Routes for the HTTP API don't prompt for auth
`http://localhost:2113/users/`

This was confirmed by running the latest version of eventstore `release-4.1.1-hotfix1` via a docker container.

**Comment by bsvveen** [comment]
we also detected this security leak our self, is this going to be fixed soon??
