### ISSUE TITLE
Projection will not run when reseted and input stream uses maxAge

### ISSUE THREAD

**Issue by Feuerschwinge** [EventStore/EventStore#1779]
This issue is related to EventStore 4.1.1.0 for Windows. The EventStore is running in a three machine cluster mode.

I have a projection which reads from a single stream:
`fromStream('SingleMessageOperationsLog')`
The projection works fine until I set the $maxAge of the metastream $$SingleMessageOperationsLog and reset the projection, so it has to run right from the start. The projection will then simply not progress as seen here even when waiting for minutes:

![image](https://user-images.githubusercontent.com/45352689/49004623-f426b080-f164-11e8-8a77-668200905d5c.png)

The EventStore log states nothing special:

> [PID:05040:026 2018.11.26 09:01:02.040 INFO  ProjectionManager   ] Enabling 'SingleMessageOperationsQueueEmitter' projection
[PID:05040:026 2018.11.26 09:01:02.040 DEBUG MultiStreamMessageWr] PROJECTIONS: Scheduling the writing of $dispose to $projections-$86bc8158-66eb-49fe-ba43-868fcb04d6c9. Current status of Writer: Busy: False
[PID:05040:026 2018.11.26 09:01:02.040 DEBUG MultiStreamMessageWr] PROJECTIONS: Scheduling the writing of $create-and-prepare to $projections-$86bc8158-66eb-49fe-ba43-868fcb04d6c9. Current status of Writer: Busy: True
[PID:05040:026 2018.11.26 09:01:02.071 DEBUG MultiStreamMessageWr] PROJECTIONS: Finished writing events to $projections-$86bc815866eb49feba43868fcb04d6c9: $dispose
[PID:05040:019 2018.11.26 09:01:02.071 DEBUG ProjectionCoreServic] PROJECTIONS: Command received: 888@$dispose
[PID:05040:026 2018.11.26 09:01:02.102 DEBUG MultiStreamMessageWr] PROJECTIONS: Finished writing events to $projections-$86bc815866eb49feba43868fcb04d6c9: $create-and-prepare
[PID:05040:019 2018.11.26 09:01:02.102 DEBUG ProjectionCoreServic] PROJECTIONS: Command received: 889@$create-and-prepare
[PID:05040:019 2018.11.26 09:01:02.180 TRACE InMemoryBus         ] SLOW BUS MSG [bus]: CreateAndPrepare - 78ms. Handler: ProjectionCoreService.
[PID:05040:019 2018.11.26 09:01:02.180 TRACE QueuedHandlerMRES   ] SLOW QUEUE MSG [Projection Core #1]: CreateAndPrepare - 78ms. Q: 1/6.
[PID:05040:019 2018.11.26 09:01:02.180 DEBUG ResponseWriter      ] PROJECTIONS: Scheduling the writing of $prepared to $projections-$master. Current status of Writer: Busy: True
[PID:05040:019 2018.11.26 09:01:02.227 DEBUG ResponseWriter      ] PROJECTIONS: Finished writing events to $projections-$master: $prepared
[PID:05040:026 2018.11.26 09:01:02.227 DEBUG ProjectionManagerRes] PROJECTIONS: Response received: 1437623@$prepared
[PID:05040:026 2018.11.26 09:01:02.243 INFO  ProjectionManager   ] 'SingleMessageOperationsQueueEmitter' projection source has been written
[PID:05040:026 2018.11.26 09:01:02.243 DEBUG MultiStreamMessageWr] PROJECTIONS: Scheduling the writing of $start to $projections-$86bc8158-66eb-49fe-ba43-868fcb04d6c9. Current status of Writer: Busy: False
[PID:05040:026 2018.11.26 09:01:02.258 DEBUG MultiStreamMessageWr] PROJECTIONS: Finished writing events to $projections-$86bc815866eb49feba43868fcb04d6c9: $start
[PID:05040:019 2018.11.26 09:01:02.258 DEBUG ProjectionCoreServic] PROJECTIONS: Command received: 890@$start
[PID:05040:019 2018.11.26 09:01:02.258 DEBUG ResponseWriter      ] PROJECTIONS: Scheduling the writing of $started to $projections-$master. Current status of Writer: Busy: True
[PID:05040:019 2018.11.26 09:01:02.305 DEBUG ResponseWriter      ] PROJECTIONS: Finished writing events to $projections-$master: $started
[PID:05040:026 2018.11.26 09:01:02.305 DEBUG ProjectionManagerRes] PROJECTIONS: Response received: 1437626@$started

Interestingly using $tb or $maxCount instead of $maxAge for the source stream of the projection, then the projection will work flawlessly. Only the $maxAge is causing this problematic behaviour.

Please let me know any workaround to work with $maxAge or if you need further information.

**Comment by Feuerschwinge** [comment]
Additional info. When waiting a while the projection faults as seen here:

![image](https://user-images.githubusercontent.com/45352689/49096197-5e754900-f26a-11e8-9ba2-b23982cd190d.png)

**Comment by hayley-jean** [comment]
This should be fixed in version 20.10 or 21.10. If you're still experiencing this issue then feel free to reopen this
