### ISSUE TITLE
Warn about setting maxAge or maxCount when using outputState

### ISSUE THREAD

**Issue by Robbert** [EventStore/EventStore#1780]
The code example in the documentation page "[User defined projections](https://eventstore.org/docs/projections/user-defined-projections/index.html)" caused us quite a few headaches when we started using EventStore. We started out by copying the code snippet and adapting it to our needs, and we didn't realise an event was written to disk in the `$projections-{projection-name}-result ` stream for every event processed by our projections.

We didn't actually need to `outputState()`, but using it caused massive disk usage and wasn't really straightforward to find out what was causing the disk usage.

I suppose there are multiple ways to address this issue. Adding a separate page about wisely using `maxAge` and `maxCount` would be one. Not casually including `outputState` in first the example would help. Adding a link to the output stream from the projection detail page in the EventStore UI would increase visibility of these events. Maybe adding a column with the number of emitted events in the Projection overview page would help.

Anyway, I wouldn't want others to experience the same pitfall.

<sub>[DB-55](https://linear.app/eventstore/issue/DB-55/warn-about-setting-maxage-or-maxcount-when-using-outputstate)</sub>

**Comment by ChrisChinchilla** [comment]
@Robbert Do you think this needs a docs change at all?

**Comment by Robbert** [comment]
Yeah, I feel the current code-snippet on the "User defined projections" page is partly nonsensical. Best to remove the `transformBy` and `outputState` from that example and explain those methods using a separate and meaningful usecase.

Also, a separate page explaining that `maxAge` or `maxCount` need to be configured for basically every stream to keep disk usage in check, especially when dealing with large amounts of real-time (sensor) data, would be quite useful.

**Comment by alexeyzimarev** [comment]
\[Private\]

@yves.lorphelin do we plan on improving custom projections docs in general?

**Comment by alexeyzimarev** [comment]
The current docs contain a clear warning saying that projections cause write amplification.
