### ISSUE TITLE
Use of 'localeCompare' in a projection causes hard crash

### ISSUE THREAD

**Issue by ChrisBallard** [EventStore/EventStore#1784]
Noticed my dev ES instance crashing with the following error whilst developing a new projection:
```
#
# Fatal error in , line 0
# Failed to create ICU collator, are ICU data files missing?
#
```

After distilling down the projection a little bit, I discovered this is down to using the localeCompare function. The following projection code will reproduce:
`"hello".localeCompare("Hello");
`

The resolution is to restart ES with only System projections, delete or fix the bad projection, and then restart normally. In my case the above function can be worked around using a manual string comparison, but flagging here as the consequences in a production system could be quite severe.

Version info:
```
[15472,01,10:13:26.173]
ES VERSION:               4.1.1.0 (oss-v4.1.1-hotfix1/cd0eafec71baffbcc0b9a4bb7c58e996cf290d34, Wed, 16 May 2018 11:08:07 +0400)
[15472,01,10:13:26.184] OS:                       Windows (Microsoft Windows NT 6.2.9200.0)
[15472,01,10:13:26.184] RUNTIME:                  .NET 4.0.30319.42000 (64-bit)
[15472,01,10:13:26.184] GC:                       3 GENERATIONS
[15472,01,10:13:26.184] LOGS:                     C:\Apps\EventStore\logs
[15472,01,10:13:26.184] MODIFIED OPTIONS:

        DISABLE HTTP CACHING:     true (Command Line)
        START STANDARD PROJECTIONS: true (Command Line)
        RUN PROJECTIONS:          All (Command Line)
        INT TCP HEARTBEAT TIMEOUT: 1000000 (Command Line)
        EXT TCP HEARTBEAT TIMEOUT: 1000000 (Command Line)
```

**Comment by shaan1337** [comment]
Confirming this still occurs on 5.0.0.

**Comment by jen20** [comment]
We'll fix this in the preview of V6.

**Comment by pgermishuys** [comment]
Moved to Event Store 6 RC.

**Comment by oskardudycz** [comment]
@hayley-jean @jageall, do you know if that was actually fixed?

**Comment by condron** [comment]
Obsolete. The new parser has replaced V8 for projection processing.
