### ISSUE TITLE
Internal SSL-connection: not mutually authenticated?

### ISSUE THREAD

**Issue by annekebr** [EventStore/EventStore#1790]
Hey there, 

I am running a (3-node) test cluster. 
When establishing an SSL - connection between the eventstore nodes, it seems that only the Master's certificate is validated but not the ones of the Slave nodes. Although I configured the cluster size to 3, I was able to connect a fourth node with a self-signed certificate to the cluster, which, as Clone, updated its complete chunk and thus got all the data. In case I'm not mistaken, is it possible to make 2-way TLS available as soon as possible? 

Many Thanks in advance!

**Comment by jen20** [comment]
We'll address this before the next version - thanks for the report.

**Comment by jageall** [comment]
Added breaking change label as the certificates will need to be reissued to support client authentication and will probably require cluster downtime to enable
