### ISSUE TITLE
Transient query gets deleted too quickly

### ISSUE THREAD

**Issue by lscpike** [EventStore/EventStore#1794]
Looks like there is no default value set on ClusterNodeOptions.ProjectionsQueryExpiry so it ends up being 0 minutes. Even if polling the result it always fails the last accessed check and gets deleted.

**Comment by shaan1337** [comment]
Hello @lscpike 

Thanks for this bug report.
This has been fixed with #1921 available in versions 5.0.1 and 4.1.3.
