### ISSUE TITLE
eventstore.org docs pages polling for toc continuously

### ISSUE THREAD

**Issue by Poimen** [EventStore/EventStore#1803]
Hi,

Not sure where to log this but the url:
https://eventstore.org/docs/

is sending out continuous requests for `toc.html` which causes 100% CPU usage as well as consuming horrendous data usage. In the time it took to write this issue it has downloaded 105MB of `toc.html`.

regards,
Richard

**Comment by ChrisChinchilla** [comment]
@Poimen Argh, dammit, yes I know what caused this, will fix asap. Thought that bug was fixed and I could revert my horrible hard fix of it. :(

**Comment by ChrisChinchilla** [comment]
OK, fixed, will fathom how to fix this properly :(
