### ISSUE TITLE
Question : For projection handlers - use .body or .data?

### ISSUE THREAD

**Issue by Poimen** [EventStore/EventStore#1804]
Hi -

We are busy digging into the projection side of ES. We currently relied on the streaming with our own projection handling. However, we are now investigation projecting out state of streams using the JS projector.

Using the JS API, the event handlers are provided `.body` and `.data`. We have seen examples on blogs and documentation sites whereby the authors have used `.body` and `.data` almost interchangeably.

From the ES documentation site we have used `.body`. `.data` looks like `.body` as well.

So, the questions are:
* should we be using `.body` rather than `.data`? 
* Is there any side effect of using the one or the other?

Thanks,
Richard

**Comment by oskardudycz** [comment]
I think that you can use them interchangeably, but we recommend using `data` (as Steven suggested).
