### ISSUE TITLE
5.0.0-rc1 Release Notes

### ISSUE THREAD

**Issue by megakid** [EventStore/EventStore#1806]
Hi - thanks for the special mention in the release notes for 5.0.0-rc1.  Looking forward to testing it out in the new year.

One thing I noticed was the mention of #1638 did not mention the new multi-threading capability to the scavenge operation which was merged in as part of that PR e.g.

**Add ability to specify number of threads (maximum 4) used to perform a database scavenge by doing an HTTP POST request to** `/admin/scavenge?threads=2`.  Can be combined with #1636 e.g.  `/admin/scavenge?threads=numOfThreads&startFromChunk=chunkNumber`.

Merry Christmas all!

**Comment by shaan1337** [comment]
@megakid thanks very much for the tip! we've updated the blog post

Merry Christmas to you too :)
