### ISSUE TITLE
Reading from $all stream via HTTP API does not expose prepare- & commit position

### ISSUE THREAD

**Issue by prolic** [EventStore/EventStore#1809]
It would be nice to have this available.

**Comment by prolic** [comment]
Without this, a captch up subscription on $all stream via HTTP API is not possible at all, because I cannot check the last processes position in order to ask for the next batch of events.

**Comment by prolic** [comment]
prev/next is present on almost all requests, except when I reach the end of the stream. When end of stream is reached, there is no previous link anymore and then I don't have any information from where to ask for more events one second later.

**Comment by prolic** [comment]
Well, thinking about it again, when I reach the end of the stream, on next the try I could read from HEAD backwards first, to see if there is something new. But as there is no position stored on the event itself, how can I make sure I don't process it twice? I could check for eventId, but there is no uniqueness guarantee. Is there another possibility I didn't think of, yet?

**Comment by ylorph** [comment]
Won't fix as the HTTP AtomPub feed is deprecated
