### ISSUE TITLE
Es-LongPoll header has no effect on persistent subscriptions via HTTP API

### ISSUE THREAD

**Issue by prolic** [EventStore/EventStore#1811]
This would be a nice to have.

**Comment by gregoryyoung** [comment]
So basically you want it to work the same on persistent as on a stream? This is actually feasible.

Can I ask what your goal is with this? Is it to reduce latency?

The reason I ask is that right now you get back a concrete answer "nothing available" then poll which is a quite reasonable http way of doing things. Hanging a connection should be ok in most situations but why not use tcp at this point?

**Comment by prolic** [comment]
If the response returns empty immediately, I would need to call it again in a loop, which leads to high CPU usage. A possibility is to sleep for a while, but then finding the "correct" sleep value becomes the next problem.

As you may know, async programming in PHP is not widely used, therefore I am offering a synchronous blocking solution via HTTP as well (I'm building a TCP and an HTTP client for Event Store in PHP right now). I personally use TCP connections in PHP.

**Comment by dnagir** [comment]
Samne use-case as -  I second the OP.
Using it from Ruby and have without `Es-LongPoll` support we'd have to be flooding the network or otherwise introducing `sleep`.

**Comment by gregoryyoung** [comment]
"If the response returns empty immediately, I would need to call it again in a loop, which leads to high CPU usage. A possibility is to sleep for a while, but then finding the "correct" sleep value becomes the next problem."

Making a http request is IO bound not CPU bound so you should *not* end up with high cpu usage unless you had sub millisecond response times which seems highly unlikely (the operation is primarily network wait, no?).

As for the "correct" sleep value its relatively easy in most scenarios. Back off. Try say the first 3 instantly then back off up to say 500-1000ms over the next few (say add a 100ms to pause for each of the next 5 iterations would put you at 500 ms ... 10 would make it 1 second which is still quite reasonable for a medium->slow moving stream obviously with 50ms slas even using http would not make sense :)) ... 

I do however think that this would be a useful feature and will be looking at implementing it this week (even have time in my calendar for it :O)

**Comment by gregoryyoung** [comment]
I have not forgotten this!

**Comment by prolic** [comment]
ping @gregoryyoung I know you have much to do, but it's already a year old :)

**Comment by ylorph** [comment]
closing as AtomPub being depcreated
