### ISSUE TITLE
Last message not being sent to subscribers

### ISSUE THREAD

**Issue by ppumkin** [EventStore/EventStore#1822]
I have been chasing an error on our Read store which turns out to be something strange on EventStore.

It seems that for some reason the last saved/published event is not being pushed to any subscribers or even when viewing the projection via the web GUI. It is like its always 1 behind. 

It is very strange because this issue just showed up randomly one day and I have no idea why it happened or how to fix it?

So when a new message comes in, the last one we expected shows up on the GUI and all subscribers. But the latest one doesn't until a new message comes in.

**Comment by shaan1337** [comment]
@ppumkin can you please confirm the EventStore version you're using? Are you subscribing to a persistent subscription?

The symptoms you're seeing are similar to the following: #1560

**Comment by jageall** [comment]
Closed due to no response
