### ISSUE TITLE
Aws s3 bucket

### ISSUE THREAD

**Issue by ekjuanrejon** [EventStore/EventStore#1825]
Hello

how can i set the db to be an s3 bucket?

**Comment by jen20** [comment]
Hi @ekjuanrejon. There is no way to use S3 as a storage back end for Event Store - it requires disks with POSIX or Windows file API semantics, not object storage. Backups can be made to S3 however, either manually, or using the backup tool included with the commercial edition.

**Comment by gregoryyoung** [comment]
To be fair it *can* be done... But you likely don't want to.

https://cloud.netapp.com/blog/amazon-s3-as-a-file-system
