### ISSUE TITLE
The node crash when detached from network

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#1827]
Given you run nodes in a cluster 
When you detach a node from the network
Then it crashes
(Fatal unhandled null reference ex... TcpClientConnector-> HandleBadConnect->RemoveFromConnecting)

tested on: pre-rel v5, 4.1.1-hotfix1, Linux Ubuntu 18.04, latest mono

**Comment by gregoryyoung** [comment]
What is the NRE on in terms of accessing?
