### ISSUE TITLE
cluster behaviour

### ISSUE THREAD

**Issue by stt106** [EventStore/EventStore#1832]
In a 3-node cluster, when one node is down, then writing to the cluster, does it write to the remaining two nodes? What's the expected behaviour? Does it depend on which node is down?

I tried to test this but got different results. Sometimes it did write to the remaining two nodes. Sometimes it throws with retries limit reached exception.

**Comment by Salgat** [comment]
Only the master can write events, so all write requests are forwarded to the master and then propagated to the connected slaves after the write is successful. A "down" node can receive new events if it's in catchup mode, but it shouldn't be able to write events itself. This is how Event Store maintains consistency.

**Comment by stt106** [comment]
Sorry I wasn’t clear. When I said additional nodes, I meant I’ll stop the existing cluster and its nodes then create a new cluster with additional new nodes plus the original nodes (with data written from the initial cluster). 
With this, when writing to the new cluster, it only writes to the new nodes not the original nodes.

**Comment by stt106** [comment]
@gregoryyoung we’re about to go live with event store and want to validate certain behaviours of cluster mode hence the question which is really about what happens when upgrading a cluster to one with more nodes; the initial cluster was stopped before adding more nodes. 
Hope this makes sense.

**Comment by gregoryyoung** [comment]
The new cluster will not have the data from the old cluster unless it is brought over in some way (backups etc). Adding new nodes to a cluster is fairly straight-forward. Bring nodes in as a clone (or bring data from a backup) then add them to the cluster. Going from 3->5 as example:

1) bring up nodes so they have data (joining as clones to 3 node cluster is ideal)
2) once caught up take down nodes and restart changing cluster size from 3->5 in config
3) the original 3 nodes will form a "5 node" cluster (3 = n/2+1) so 1 M 2 S
4) bring up new nodes. They should join and begin replicating (you can see statuses in UI)
5) once caught up killing any M/S node one of the new nodes should get promoted as a slave.

**Comment by gregoryyoung** [comment]
Note you dont *have* to bring them up as clones at the beginning you can also just give them a backup to come up off of. I was just giving the least-moving-parts answer.

**Comment by stt106** [comment]
@gregoryyoung thanks for help.
