### ISSUE TITLE
Multiple projections writing to the same stream

### ISSUE THREAD

**Issue by jbroenstrup** [EventStore/EventStore#1833]
I am sorry if this is a stupid question, but I did not find anything about this in the documentation. I created two projections, that are both emitting events to the same stream but with different ids, like so:

```javascript
fromStream("onoffevents")
    .when({
        $init: () => {
            return {
		id = 1
                running: false
            }
        },
        "on": (s, e) => {
	    if (e.id == s.data.id) {
	        s.running = true
	    }
            return s;
        },
        "off": (s, e) => {
            if (s.id == e.data.id) {
                if (s.running) {
                    s.running = false;
                    emit("RunInfo", "RunCompleted", {id: e.data.id}, {});
                }
                else {
                    emit("Errors", "ConsecutiveOn", { causingEvent: e }, {})
                }
            }
            return s;
        }
    }).outputState()
```

So there are different instances that produce on/off events, but whenever a run of one of those instance is complete, I want a "RunCompleted"-event to be emitted to the "RunInfo"-Stream.

But I get an error-message `Multiple projections emitting to the same stream detected. Stream: 'RunInfo'.`

I did not find any information in the documentation that suggested that it is prohibited to write from multiple projections into one stream ...

PS: I am using EventStore 4.1.1.0 and the .NET-Api.

PPS: I could obviously just combine the two projections to get the same effect, but it would be a problem since the IDs might change and I don't want to always update the projection, but instead just remove them or add new ones, if new IDs come into the system ...

**Comment by cuddlecake** [comment]
+1

Got the same problem, where I write manually and via a projection to the same stream.

I understand why a projected stream should not be written to by other streams, but is there any way to do it, despite the obvious problems?

**Comment by jbroenstrup** [comment]
I solved it so that all my projections just emit to an individual stream, that are generated with a guid, like "runinfo_<guid>". Then I wrote a meta projections that takes all "RunCompleted"-events from all streams and writes them to a "RunInfo"-stream.

**Comment by oskardudycz** [comment]
@jbroenstrup, projections should be writing to the dedicated streams. It's not supported to have multiple projections writing to the same stream, we also do not support manual appends to the projections streams.
