### ISSUE TITLE
Question : Are Clusters and SSL mutually exclusive?

### ISSUE THREAD

**Issue by neildanson** [EventStore/EventStore#1836]
I have a 3 node cluster (3 separate machines) which works perfectly if I do not provide a cert / enable SSL.

If I run as single node I can enable SSL and everything works perfectly over the secure external tcp port. 

However when I try to apply the SSL settings *and* run as a cluster, then the 3 nodes cannot keep a connection to each other and end up constantly trying to re-elect. 

Is it possible to have security on *and* run as cluster?

**Comment by jen20** [comment]
Hi @neildanson, the TLS stack has been considerably improved in version 5, partly by virtue of a framework update. Version 5-rc2 should do what you need. There will be another RC on Monday, hopefully followed by a final release the following week assuming no regressions are found. We don’t plan to back port this work to v4 as the framework upgrade meant substantial changes - v5 is where you want to be for this.

**Comment by neildanson** [comment]
Thanks for the update @jen20 - slightly sad face as I'm stuck on .net 4.6 for the near future due to external constraints. Off the top of your head - would it be difficult for me to form and re-target or are the framework changes deep cuts?

**Comment by neildanson** [comment]
I've pulled latest and changed target version - apart from runtime information (which is always Windows for me, so is a n easy fix) it seems all quite agnostic. I may designate some time towards this next week......
