### ISSUE TITLE
read last deleted event from stream

### ISSUE THREAD

**Issue by Zetanova** [EventStore/EventStore#1845]
The last event of a soft deleted stream will not be scavenge/removed.
It is possible to query the event with the EventStore browser interface
but i cant find any method in the .net client to query it.

connection.ReadEventAsync result in "NotFound"
Is there some undocumented feature/flag somewhere?

**Comment by ChrisChinchilla** [comment]
@Zetanova I'm slightly confused by this one, and I'm not sure it's a docs issue.

I tried reading a deleted event with the HTTP API and the .NET API and had the same problem you had, but I can also read the event from the Web UI. One thing is that with the web admin UI you're logged in as admin, but I even tried that with the HTTP API and still got a 404.

So I'm going to have to pass this to @shaan1337 or @avish0694 as I think this is more of an admin peculiarity than a docs issue. The docs highlight the ways you can recreate soft deleted events, but I wonder if there's some caching, or extra headers set in the web admin UI.

**Comment by gregoryyoung** [comment]
I don't believe this is an "admin permissions" thing. I think its more likely a browser caching thing.

The information is likely in the browser cache.

If you go through the same steps but *don't* open in the browser first I am betting the browser won't allow viewing. A similar test could be done clearing browser cache on an existing one you have.

**Comment by Zetanova** [comment]
Yes, it was the browser cache. 
But still is there any possibility to read the metadata of the tombstone event?

The akka.net EventStore is injecting the akka.net SeqNr into the metadata of the event
and if the stream gets deleted then it will lose the info of the LastSeqNr. 

Most likely, a stream delete, happens only under development.

**Comment by gregoryyoung** [comment]
As a suggestion instead of *DELETING* here use $tb : current- 1 (deleting by default does $tb : current). This will mark all previous events as being able to be scavenged and leave the stream with just that event in it (the "event" is often StreamDeleted" with information about what the stream was :)). This pattern is often known as tombstoning.

**Comment by Zetanova** [comment]
thx, yes this event, i want to read.

I didn't think about to write write my own tombstone.

**Comment by gregoryyoung** [comment]
Note that you may or may not want to delete after the tombstone. Its common as well just to use it to close but still leave all events...

**Comment by Zetanova** [comment]
I want only to fix the behavior in https://github.com/AkkaNetContrib/Akka.Persistence.EventStore/issues/6
On a stream delete the behavior lead to a not recoverable situation.
