### ISSUE TITLE
Cannot delete a stream

### ISSUE THREAD

**Issue by dnagir** [EventStore/EventStore#1852]
It looks I'm having trouble deleting a stream from UI (hope I'm doing something wrong though). Steps:

- the stream was created from a projection that emits events with `linkTo`
- delete the projection (from UI)
- try to delete the stream manually from UI

**Expected:**
- no JavaScript errors in the browser
- the stream is deleted

**Actual:**
- JavaScript error in the browser
- the stream is still available despite the success (204) response

Using the version of EventStore that corresponds to docker image `9cfd470745a9`:

```
docker images |grep eventstore
eventstore/eventstore           latest              9cfd470745a9        8 months ago        199MB
```

See the screenshot attached:
<img width="1674" alt="gyes-cannot-delete-stream" src="https://user-images.githubusercontent.com/195035/52475553-f048ed00-2bef-11e9-8766-81b78480ebe4.png">

**Comment by mehdihadeli** [comment]
Hi,
I have a problem with deleting stream in Opera browser, but it works in chrome
