### ISSUE TITLE
Created time

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#1865]
Right now when dealing with a linked event over the http api there does not appear to be (just checked quickly) a way to get both the time of the link event and the time of the linked event. This is likely useful in some scenarios.

**Comment by gregoryyoung** [comment]
https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/Transport/Http/Convert.cs#L323 is related code.

**Comment by ylorph** [comment]
Consuming Events through Atom PUB  is deprecated
So this will not get fixed
