### ISSUE TITLE
Deploying and migrating many projections

### ISSUE THREAD

**Issue by LaylBongers** [EventStore/EventStore#1868]
I've been trying to figure out how to do this, and I can't find any documentation on this.
I'm developing a system that will use EventStore as its primary way of storing data.
Two use cases I can't figure out how to do:

* When the system is deployed on a brand new cluster, all the projections need to be created on the EventStore, can this be done automatically in some way, and if so what's the general recommended way to set this up to happen automatically?
* When a deployment is updated, projections need to be updated as well. I want to avoid re-uploading projections that already exist. Preferably it would remove ones that don't exist anymore, add new ones, and modify changed ones. I can't figure out how to do this automatically either.

Is there a tool to do these things?

<sub>[DB-373](https://linear.app/eventstore/issue/DB-373/deploying-and-migrating-many-projections)</sub>

**Comment by dimaip** [comment]
You can deploy projections via ES' HTTP API, e.g. https://github.com/kolotree/EventModelingJobProcessing/blob/main/src/core-packages/docker/eventstore-projection-creator/create-projection.sh#L18

**Comment by StevenBlair123** [comment]
@LaylConway - we use Powershell, which checks a folder for projections. If found, we post up to Eventstore, then simply move the .js file to a "processed" folder.

**Comment by alexeyzimarev** [comment]
We plan to make dev experience with custom projections better (realising that it's almost non-existent today). It depends on our current plans regarding custom projections in general, so, I think, we can address it somewhere mid next year. We'll handle it internally, and consider this issue as an input.
