### ISSUE TITLE
Add cancellation token as an argument on async methods

### ISSUE THREAD

**Issue by poulad** [EventStore/EventStore#1869]
Hi

I am surprised that there is no [`CancellationToken`] on the `async` methods of [`IEventStoreConnection`]. And searching `CancellationToken` on this repo returns no results.

Is there a reason for not having them? If the tokens are simply omitted, I can make a PR for that.

[`CancellationToken`]: https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=netcore-2.2
[`IEventStoreConnection`]: https://github.com/EventStore/ClientAPI.NetCore/blob/119a94c95c70bf778525063e04e9536b10b7191f/src/EventStore.ClientAPI.NetCore/IEventStoreConnection.cs

**Comment by jen20** [comment]
As of version 5.0.0, Event Store's .NET Client API (in the main EventStore/EventStore repository) targets .NET Frameworks 4.5.2 and 4.6.0, and .NET Standard 2.0.0, and consequently this repository is being archived.

I've transferred this issue to the main repository for tracking further.

**Comment by oskardudycz** [comment]
TCP client was taken out from the main repository and moved to https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy/. We recommend using the gRPC client, the TCP client is obsolete (no new features will be added for that).

Nevertheless, it's a valid suggestion. If someone is willing to extend TCP API with a cancellation token, we'd be happy to take it as Pull Request. I created a dedicated issue for that https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy/issues/26.
