### ISSUE TITLE
UI subscriptions page cached in browser

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#1870]
If your navigating to....
 http://<<<UI host and port>>>/web/index.html#/subscriptions

You are never going to want a copy of this page your browser may have cached, your always going to want its current state regardless of if your running with the –disable-http-caching command line option or not.

It could be worth always disable http caching for this view

**Comment by avish0694** [comment]
Unable to reproduce, Reproduction steps tried: 

1. Create a few new persistent subscription. For example: stream name:  
2. Read from them. 
3. Delete them. 
4. Create persistent subs with same name. 
5. Noticed that their values are different. 

- [ ] Firefox

- [ ] Chrome

**Comment by riccardone** [comment]
Hey @avish0694 how are you? I remember this was based on a ticket. Maybe you can find it to see more info
