### ISSUE TITLE
Usage of Correlation Id

### ISSUE THREAD

**Issue by StuartFergusonVme** [EventStore/EventStore#1871]
Looking at using the new By Correlation Id functionality in ES v5 and wanted to check what I am doing is correct.

1) Started Up ES v5.0.0 in memory mode with all system projections running.
2) Added a few events to a new stream using the Add Event screen in the UI, with a correlation Id in the event data (tried using "correlationId" and "$correlationId")
3) Tried to browse to the By Correlation Id stream with the name "$bc-MyCorrelationId"  but the stream is not found.

Is there something additional I need to do when starting up my event store or am I missing something when adding the events to my test stream.

Any pointers would be appreciated.

**Comment by StuartFergusonVme** [comment]
Just realised this should actually be in the meta data :|

**Comment by burmajam** [comment]
Just to summerize for future reads, use `$correlationId` key in metadata in order to have "$bc-some_correlation_id" stream.
