### ISSUE TITLE
ISO date string is mutated inside projection

### ISSUE THREAD

**Issue by MarcinKasprowicz** [EventStore/EventStore#1883]
Hi, I sending following payload in event:

```
$ curl -H "Content-Type: application/json" -X PUT -d @testevent.json http://localhost:8080/events
```
```
{
  "events": [
    {
      "id": "${UUID}",
      "timestamp": "2019-03-18T10:10:00+03:00",   <-------------
      "event_type": "checkin",
      "event_description": "New player registered at the moment!",
      "user_id": 1,
      "site_id": 1
    }
  ]
}
```

Where field `timestamp` is an ISO date with an offset, however inside projection I receive ISO date in UTC time zone, which causing losing information about timezone. 

![screenshot 2019-03-05 at 13 38 34](https://user-images.githubusercontent.com/9901471/53806019-155d2100-3f4c-11e9-887a-d867de5d6f23.png)

Can somebody check why the string is mutated? I suppose this can have something to do with a deserializing and following issue: https://github.com/EventStore/EventStore/pull/866

Environment: Docker in UTC timezone
Version: 4.1.0

**Comment by pgermishuys** [comment]
Fixed via https://github.com/EventStore/EventStore/pull/2063
