### ISSUE TITLE
Keep repeating ReadIndex building

### ISSUE THREAD

**Issue by hanxinimm** [EventStore/EventStore#1891]
![image](https://user-images.githubusercontent.com/13499426/54183023-09d6a080-44de-11e9-8f79-76668e2fc92b.png)
I have 3 nodes ,but each time it restart, it will ReadIndex building long times~ i use 1 node it work better,i try it 3 node in production environment ,it Very bad. now I'm under a lot of pressure. I'm starting to think about changing the plan.
[10.0.0.13-2114-cluster-node-err.log](https://github.com/EventStore/EventStore/files/2955656/10.0.0.13-2114-cluster-node-err.log)

**Comment by gregoryyoung** [comment]
So there are a few things here.

A portion of the index is generally rebuilt on startup. When the amount reaches a certain size it is written to disk (note the size here is configurable). This means it does not need to be regenerated.

The amount of time to build an index of even 1,000,000 items (the default) is usually (should be) negligible. What are you running on? You appear to only be able to process a few hundred items/second. This is not a normal situation. My laptop can rebuild +- 1m in +- 2-3 seconds.

**Comment by hanxinimm** [comment]
I don't know what happens, when 3 node all  readIndex building finish, it  auto shutdown,
when i restart its , ReadIndex building again. now its write 20GB files~ but we just use it write a little data. 
in the last ,I shutdown 3 node, and delete node 1,node 2 data/log  file,only keep node 3 ,restart node 3, then restart node 1 node 2 , node1 node 2 start catch up data,when its  finish,it better~

**Comment by gregoryyoung** [comment]
Can you include your regular log not your error log...

**Comment by hanxinimm** [comment]
[logs-node3.zip](https://github.com/EventStore/EventStore/files/2959873/logs-node3.zip)
[logs-node1.zip](https://github.com/EventStore/EventStore/files/2959874/logs-node1.zip)

**Comment by shaan1337** [comment]
@hanxinimm can you please try specifying the gossip seed endpoints in each node (with `--gossip-seed` and `--discover-via-dns=false`) instead of using cluster DNS ? please let us know if this makes any difference.

**Comment by gregoryyoung** [comment]
The processing is going *ridiculously* slowly... Only 100 or so are being done per second (this is something like two orders of magnitude off). Something is wrong in the machine setup. What kind of drives etc are being run on? Could iops limits etc be being hit?

{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:16.578665Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 237483, "resultPosition": 43.626359508683286 } }
{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:21.584807Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 238089, "resultPosition": 43.7283081209494 } }
{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:26.589312Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 238691, "resultPosition": 43.829605055765974 } }
{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:31.591911Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 239299, "resultPosition": 43.931916262954473 } }
{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:36.625333Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 239909, "resultPosition": 44.03453672097789 } }
{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:41.626762Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 240516, "resultPosition": 44.136649494369827 } }
{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:46.632631Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 241124, "resultPosition": 44.238957524713541 } }
{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:51.644125Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 241732, "resultPosition": 44.341267293526066 } }
{ "PID": "2748", "ThreadID": "11", "Date": "2019-03-12T06:05:56.649042Z", "Level": "Debug", "Logger": "IndexCommitter", "Message": "ReadIndex Rebuilding: processed {processed} records ({resultPosition:0.0}%).", "EventProperties": { "processed": 242338, "resultPosition": 44.443228778739773 } }

**Comment by oskardudycz** [comment]
Closing because of the inactivity.
