### ISSUE TITLE
ArgumentNullException: while reconnecting, the connection would never be restored again

### ISSUE THREAD

**Issue by ninjaboy** [EventStore/EventStore#1896]
It is probably something new to the EventStore v5 as we haven't faced this when using v4:

![image](https://user-images.githubusercontent.com/275925/54535075-a806b280-4985-11e9-8830-86b41b154d22.png)

Having a brief look on the code in github:
https://github.com/EventStore/EventStore/blob/07b52038106794814eb40a645792c292c03cdd4f/src/EventStore.ClientAPI/Internal/EventStoreConnectionLogicHandler.cs#L558

Any reconnect attempt will lead to a situation when the _conneciton object is null and ConnectionState.Connecting.

At the same time TimerTick callback has the following code:
https://github.com/EventStore/EventStore/blob/07b52038106794814eb40a645792c292c03cdd4f/src/EventStore.ClientAPI/Internal/EventStoreConnectionLogicHandler.cs#L325

This looks like a bug, please advise whether it is better to rollback or if there are known ways to handle such situation?

**Comment by shaan1337** [comment]
@ninjaboy thanks for your report. this bug has been fixed in EventStore.Client 5.0.1. Can you please confirm you are using client version 5.0.0?

**Comment by ninjaboy** [comment]
@shaan1337, confirming that we have used 5.0.0. 

We will try 5.0.1. I will close the issue for now then.

Thanks!
