### ISSUE TITLE
First action on EventStoreConnection of dotnet tcp Client aways very slow

### ISSUE THREAD

**Issue by ivankoster** [EventStore/EventStore#1899]
I found this issue while investigating why my integration tests were suspiciously slow.
It looks like the first action taken on a freshly opened connection is very slow, almost 1000 times slower than the 2nd action. I also found out if a Task.Delay is inserted right after opening the connection, the first action taken is magically faster.
At first I thought i was hallucinating, but I confirmed this with multiple colleagues and they see this happening as well.

Reproduce scenario:
Running latest EventStore in docker like this:
`docker run --name eventstore-node -d -p 2113:2113 -p 1113:1113 eventstore/eventstore`

Running a dotnet core 2.2 app with nuget package EventStore.Client 5.0.1

Reproduce code:
```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using EventStore.ClientAPI;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var s = new Stopwatch();
            s.Start();

            var timeSpans = new List<TimeSpan>();

            await OpenConnectionAndDoTwoThings(timeSpans, s);
            await OpenConnectionAndDoTwoThings(timeSpans, s);
            await OpenConnectionAndDoTwoThings(timeSpans, s);
            s.Stop();

            foreach (var timeSpan in timeSpans)
            {
                Console.WriteLine(timeSpan.TotalMilliseconds);
            }
        }

        private static async Task OpenConnectionAndDoTwoThings(List<TimeSpan> timeSpans, Stopwatch s)
        {
            using (var conn = EventStoreConnection.Create(new Uri("tcp://admin:changeit@localhost:1113")))
            {
                timeSpans.Add(s.Elapsed);
                await conn.ConnectAsync();
                timeSpans.Add(s.Elapsed);
                //await Task.Delay(100); // If this is uncommented, the test is suddenly a lot faster, makes no sense!
                await conn.ReadEventAsync("$all", 0, false);
                timeSpans.Add(s.Elapsed);
                await conn.ReadEventAsync("$all", 1, false);
                timeSpans.Add(s.Elapsed);
            }
        }
    }
}
```

Output:
```
148,3801
153,6274
1178,9976
1181,9888
1182,8148
1183,0194
2198,8026
2200,3714
2200,9416
2200,9555
3203,3163
3204,7783
```

Output with the Task.Delay(100) after opening the connection:
```
143,7108
149,819
292,9342
294,9005
295,6365
295,7411
398,3556
400,1168
400,7453
400,7641
510,1563
512,5461
```

**Comment by CumpsD** [comment]
I can reproduce this on AWS Lambda.

Here is some very elaborate code, without this snippet my code always takes 1.2seconds to do the first ReadStreamEventsForwardAsync, with this snippet it takes 1.1ms:

https://github.com/CumpsD/aws-try/blob/es/src/Exira.Functions/HelloWorld.fs#L203-L207

**Comment by CumpsD** [comment]
With a Task Delay of 10ms I am getting much better times:

![screenshot-2020-01-28-24_1873x770](https://user-images.githubusercontent.com/1201644/73300310-1278b800-4211-11ea-97c2-db38107901e5.png)

**Comment by CumpsD** [comment]
Seems related to this issue: https://github.com/EventStore/EventStore/issues/1975

He is also getting around 1 second on first action

The problem with Lambda's, I dont think there is a way to keep a connection active, every invocation is a fresh connection instance.

**Comment by CumpsD** [comment]
@gregoryyoung sorry for another question, but would the gRPC client in ES 6 solve this by chance?

**Comment by CumpsD** [comment]
For reference, I converted all my code to sync, except the calls to Eventstoreclient, since they are only async. Without a delay and everything sync, it is identical, 1.2 sec. With a delay it is fine:

![image](https://user-images.githubusercontent.com/1201644/73306982-9cc71900-421d-11ea-816e-7fc669fefaa2.png)

Sync code at: https://github.com/CumpsD/aws-try/tree/5e833655674758fee9f78ffbd1c44036422b99a9

**Comment by CumpsD** [comment]
For RDS amazon now released RDS Proxy: https://aws.amazon.com/blogs/compute/using-amazon-rds-proxy-with-aws-lambda/

Basically a proxy doing the connection pool. I'm wondering if something like this exists for ES
