### ISSUE TITLE
Persistent subscription to stream, created by $by_event_type projection, not resolving links

### ISSUE THREAD

**Issue by Eranikid** [EventStore/EventStore#1901]
I have following code:

```
var eventType = "myTestEventType";
var streamName = $"$et-{eventType}";
var groupName = "myService";
var json = JsonConvert.SerializeObject(new
{
    SomeProp1 = 1,
    SomeProp2 = "Hello"
});
var eventToPublish = new EventData(
    eventId: Guid.NewGuid(),
    type: eventType,
    isJson: true,
    data: Encoding.UTF8.GetBytes(json),
    metadata: new byte[0]
);
connection.AppendToStreamAsync("myTestStream", ExpectedVersion.Any, eventToPublish);
connection.ConnectToPersistentSubscription(
    streamName,
    groupName,
    async (subscription, @event) =>
    {
        Console.WriteLine(Encoding.UTF8.GetString(@event.Event.Data));
        subscription.Acknowledge(@event);
    }
);
```

I expect event to be published to `myTestStream`, picked up by `$by_event_type` projection, link to event stored in `$et-myTestEventType`, subscription to fire, resolve link and return original JSON. However `@event` in my event handler has following properties:
```
{
    "IsResolved": false,
    "Link": null,
    "OriginalEvent": {
        "Data (after decoding)": "3@myTestStream",
        "EventId": "Different Id from what I see in Web UI for my event",
        "EventStreamId": "$et-myTestEventType",
        "EventType": "$>",
        "IsJson": false
    }
}
```

In Web UI for I see my event both at `/web/index.html#/streams/myTestStream/3`, and at `/web/index.html#/streams/$et-myTestEventType/3`. It has same Id in both places, and it is different from what I get in .NET client.

 If I subscribe directly to `myTestStream`, I am getting my original event with JSON body.

Is default projection `$et-myTestEventType` not resolving links? Can I enable it do to so? If not, should I create my own projection, or should I resolve them manually from .NET app?

**Comment by gregoryyoung** [comment]
$>

This is a linkTo event, if you resolve linktos you will get the event its pointing to not this event.

**Comment by jageall** [comment]
by default linkto events are not resolved in subscriptions or reads, you need to pass true in to the resolveLinkTos parameter

**Comment by shaan1337** [comment]
@Eranikid hello, kindly note that we're closing the issue since it seems resolved. Please feel free to reopen if you have any doubts. thanks!
