### ISSUE TITLE
Event time in HTTP API response has inconsistent format

### ISSUE THREAD

**Issue by enumag** [EventStore/EventStore#1903]
When I read events from the HTTP API each event has an `updated` field with time, for example:

```
"updated": "2019-02-14T07:59:26.83966Z",
```

So in PHP we're parsing it using this:

```php
return DateTimeImmutable::createFromFormat('Y-m-d\TH:i:s.uP', $dateTimeString);
```

Recently this started to fail in some cases and after some debugging I found out that one event had time like this: `"2019-03-28T11:39:53Z"`. As you can see the format is different - the microseconds near the end are missing. I'm not sure why, possibly it is cut off when the number of microseconds is 0?

**Comment by burzum** [comment]
I probably have a related issue, I'm getting microtimes with 7 digits back instead with 6... The format is clearly inconsistent. :(

**Comment by ylorph** [comment]
Closing as consuming events through the  Atom Pub is deprecated
