### ISSUE TITLE
Build eventstored on linux

### ISSUE THREAD

**Issue by daMupfel** [EventStore/EventStore#1909]
Hi guys,

I'm trying to build the eventstore project on linux. I am succeeding in the sense that i can build the project and i'm ending up with Eventstore.ClusterNode.exe files and all its dll (which i can run). However there used to be a package-linux.sh script which turns that into eventstored (which i presume is everything packaged up with an embedded mono runtime?). The packagecloud packages still seem to be built this way but i can't find any documentation on how to do that. 

I would be very happy about a hint and hope that i have not missed anything in the project and the already existing issues.

**Comment by shaan1337** [comment]
@daMupfel hello, we no longer keep the packaging scripts in the public repository. however, the behaviour you see when running with the correct version of mono should be almost exactly the same.

Is there any reason you would need the packaging scripts, is it to run your own custom builds in production/pre-production?

thanks

**Comment by daMupfel** [comment]
Hi, thanks for the response.

We currently use some custom logic to do server side filtering for $all streams.

Pull requests can be found here:
https://github.com/EventStore/EventStore/pull/1821

I wanted to upgrade our docker image to the latest eventstore release but found out that the build script was not here anymore. We could as you said, just run eventstore with mono, but i wanted it to be as close to the release version you guys do as possible.

**Comment by shaan1337** [comment]
@daMupfel hello sure, I've extracted the relevant parts from the script that should give you enough information to make the build on Ubuntu (needs to be executed in the directory where the executable is located):
```
monoPosixHelperLib=$(ldconfig -p|grep libMonoPosixHelper|awk {'print $4'})
monoSystemNativeLib=$(ldconfig -p|grep 'libmono-system-native.so '|awk {'print $4'})
monoBtlsSharedLib=$(ldconfig -p|grep 'libmono-btls-shared.so'|awk {'print $4'})

machineConfig="/etc/mono/4.5/machine.config"
monoConfig="/etc/mono/config"

tmpMonoConfig="/tmp/mono.config.tmp"
sed 's/\$mono_libdir\///' $monoConfig > $tmpMonoConfig

mkbundle -o eventstored --env "MONO_ENV_OPTIONS=-O=inline" --simple --deps --library $monoPosixHelperLib --library $monoSystemNativeLib --library $monoBtlsSharedLib --machine-config $machineConfig --config $tmpMonoConfig EventStore.ClusterNode.exe *.dll

rm "$tmpMonoConfig"
```

You need to run the above on the same version of Ubuntu you're targeting for the Docker image with the following version of mono installed:
```
apt-get install -y mono-devel=5.16.0.220-0xamarin4+ubuntu1604b1 msbuild=1:16.0+xamarinxplat.2018.09.26.17.53-0xamarin3+ubuntu1604b1 dotnet-sdk-2.1
```

You can obtain some more information about the required mono/dotnet repositories here:
https://github.com/EventStore/eventstore-ci-ubuntu-16.04/blob/master/Dockerfile

**Comment by daMupfel** [comment]
@shaan1337 Thank you very much, i will try this 👍
