### ISSUE TITLE
export stream from one event store to another

### ISSUE THREAD

**Issue by ekjuanrejon** [EventStore/EventStore#1916]
Hello

How can I export a stream from one event store to the other?

**Comment by gregoryyoung** [comment]
open a catchupsubscription with a handler to write (its +- 10 loc) it will then continue working into the future as well...

**Comment by ekjuanrejon** [comment]
@gregoryyoung thanks for the feedback. Is this somethin that can be done via the REST api.

what you have explain seems to be trivial. correct me if I am wrong

**Comment by ekjuanrejon** [comment]
I suppose like if I want to export a stream into a json file and import it to another eventstore

**Comment by mat-mcloughlin** [comment]
Hey, @ekjuanrejon you can do this via the HTTP API by reading the stream forwards. See https://eventstore.org/docs/http-api/reading-streams/index.html for more information. If you have any more questions please re-open this issue.
