### ISSUE TITLE
Slave restart can lead to master re-elections (most common in 5 node cluster)

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#1917]
Thanks to @megakid for reporting this.

Restarting a slave node can lead to master re-elections.
This can lead to some instability since the previous master (and maybe some slaves too) very likely needs to truncate if writes were ongoing since uncommitted data is written immediately to chunk files causing a few more elections when these truncated nodes are back up.

*Reproduction steps:*
Here's an instance of how it can occur:
1. Node X (a slave) is restarted
2. Node X triggers elections process
3. Node X is selected as the leader of the current elections
4. Node X waits for a quorum number of `PREPARE_OK` messages from other nodes before choosing the best master candidate. It does not receive a `PREPARE_OK` from the original master.
5. At this point in the code https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Services/ElectionsService.cs#L338 , Node X does not have the `_lastElectedMaster` value since it was restarted. Based on the current algorithm, a different master will be elected.

So far this has been reported only on 5-node clusters and a reproduction on 3-node clusters has not been successful.

*Potential solution 1:*
 If a node has been selected as leader of elections and does not have a `_lastElectedMaster` value check in gossip if there is at least one slave/master nodes. If yes, let the elections time out since we know that these nodes will have a `_lastElectedMaster` value.

*Potential solution 2:*
If a node has been selected as leader of elections and does not have a `_lastElectedMaster` value, let the elections time out X times where X = 1 or 2. This will lead to a few more elections (particularly when all nodes are being started for first time) but could make the cluster more stable for single node restarts.

Ticket no: 1314

**Comment by pgermishuys** [comment]
This particular issue requires further testing and investigation as there are 2 issues. One where the TCP being lost caused elections to take place which is what #2103 attempts to remedy and another where 2 nodes accepted a new master proposal even though they both had knowledge of the previous master being elected and that master still being alive.

The other 2 nodes outright rejected the proposal as both of them knew that the previously elected master node is still alive.

**Comment by gregoryyoung** [comment]
"This can lead to some instability since the previous master (and maybe some slaves too)"

Can you provide an example of a slave needing to truncate in this case? This should not be anything resembling a normal case...

**Comment by pgermishuys** [comment]
Having a had a look at this closer, the above case is already covered whereby the nodes in the cluster should reject the master proposal from the restarting slave if the current master of the nodes that need to accept the proposal is still alive.

Looking at a couple of scenarios we have identified the root cause of this issue and documented it in the following issue https://github.com/EventStore/EventStore/issues/2213.
