### ISSUE TITLE
A way to remotely admin ACL groups

### ISSUE THREAD

**Issue by Ryan-Palmer** [EventStore/EventStore#1943]
I am not sure if this is already possible, or whether it isn't needed for some other reason that I don't understand yet as I am new to event sourcing and ES.

I am going to need to restrict access to streams based on group membership, which of course ES supports based on ACLs in metadata.

I can add / remove users and / or groups to an ACL over the HTTP API as per the docs.

What I cannot see is a way to CRUD the groups themselves without logging into the web console?

I will need this as I will have users who create and manage teams through a website, they won't have access to the ES portal directly.

Is this possible? If not, is there an alternative suggestion I could read up on?

Cheers :)

**Comment by RyanBuzzInteractive** [comment]
I have posted a question in the Google Group before I came here as well, so if there is a solution I will copy it over there for others to see.

**Comment by mat-mcloughlin** [comment]
Hey, @Ryan-Palmer it looks from the google group question that your issue has been resolved. If you need any more help feel free to re-open the issue
