### ISSUE TITLE
Projection state inside other projections

### ISSUE THREAD

**Issue by manocha-aman** [EventStore/EventStore#1946]
This question was asked in [here](https://github.com/EventStore/EventStore/issues/976) but was not answered as a use-case was not provided. It might be helpful to be able to fetch current state of a projection inside another projection. Here is a use-case : 

A simple application where users can purchase products. There are two category of streams : Users (one stream per user) and Products (one stream per product).
User streams keeps getting Purchased(productId) events.

I want to build a projection which will accept user id and return all products purchased along with details of the product (not just id) which are present in Product projection. Is there a way to build this kind of projection?

If there is a way to fetch current state of a projection with something like `projections.products-{productId}.state` then I will be able to build it.

**Comment by gregoryyoung** [comment]
Why are you not doing this in a read model?

**Comment by amanmanocha** [comment]
Thanks @gregoryyoung for quick reply. My other views which are simple so far are served with projections only. I have been able to avoid any application for read model. Wanted to understand if there is a way to do this from projections.

**Comment by StevenBlair123** [comment]
We have a similar use case, but just accepted we couldn't do it.
The partition we have is extremely useful for us for live system monitoring, but, if we could read another partition to grab some extra info it would be good.

I could post up an example if it helps.

**Comment by oskardudycz** [comment]
@manocha-aman, I think that your use case won't be supported in the EventStoreDB projections. It's pretty hard to provide an efficient, generic way to support such needs. We have to remember that EventStoreDB projections are, in fact, transformations. They're taking the set of events and changing it to another one. To support your case, it'd need to join and load data from multiple streams, which may require reading a lot of events. The other aspect is that keeping projections dependant on each other and doing a critical path of necessary changes may be hard to maintain. For instance, if you'd like to rebuild projections, then you cannot do it autonomously for the specific one. You need to run rebuilds in a particular order. 

As Greg and Steven explained, the best is to use external read models for that. I wrote longer on potential strategies: https://event-driven.io/en/how_to_create_projections_of_events_for_nested_object_structures/.
