### ISSUE TITLE
Improve client side handling of subscription overflows

### ISSUE THREAD

**Issue by jageall** [EventStore/EventStore#1947]
Currently when a subscription inbound queue is overloaded the subscription is dropped and the consuming app has to re-subscribe. 

A preferred method would be for the subscription to unsubscribe from the server pushing events and fall back to catch up mode until it is caught up again. 

Originally this was done because clients might be slow processing incoming messages, but it can also happen if the server processes a lot of events very quickly.

When events arrive on the client it is possible to tell the depth of the live queue.  
When the length of the live queue is going to be breached, the client can unsubscribe from the server and drop any further messages until the client has processed the queue. then the normal catch up process can just happen again.

An additional optional delegate to be called when this happens should be provided so that consumers can monitor for it happening.

This issue is related to updating the server side subscription manager to add a flag to EventAppeared messages to switch back to catch up mode when the connection is close to being overwhelmed from the server side.

This is related to #1948.

To avoid the case where a client switches repeatedly between live and catchup, the client should incrementally backoff attempting to switch to live processing and instead just poll for events on a timer, switching back to live after not receiving new events within a window to be determined. Both the backoff and the window should be configurable in the subscription settings.

**Comment by alexeyzimarev** [comment]
I believe we've done it, subscriptions are now seamlessly switch between live and catch up, so a subscription will switch to catch up mode if it doesn't cope (slow consumer) and then back when the lag closes

https://www.eventstore.com/blog/esdb-24.2-release-announcement#catch-up-subscription-mode-change-without-drops
