### ISSUE TITLE
Duplicated EventId on same stream with ExpectedVersion

### ISSUE THREAD

**Issue by smartcodinghub** [EventStore/EventStore#1949]
**Describe the bug**
Trying and playing with Idempotency using the docs (https://eventstore.org/docs/dotnet-api/optimistic-concurrency-and-idempotence/index.html), I understand that if use ExpectedVersion.Any but with the same EventId and json only one should be persisted (although a small chance). But every time I retry the same Event I get a new event on the stream.

I don't know if this is a bug, an error on the docs or a misunderstanding (problably a mix of the last options).

**To Reproduce**
With the Same EventData, call multiple times to AppendToStreamAsync with the same stream id and ExpectedVersion.Any.

**Expected behavior**
Only one event (with a little chance of a duplicate). As stated in the docs: "All events have been committed already - the write is acknowledged as successful, but no duplicate events written."

**Actual behavior**
Duplicated event.

**Comment by hayley-jean** [comment]
Are you sending the events with the same Event Id?

The idempotency check is based solely on the Event Id, regardless of the actual body of the event.
So if you send multiple requests but each has a unique Id, Event Store will see those as new events and you will see 'duplicated' events.

If this is not the case and you are seeing duplicate events with the same Event Id, would you be able to provide us with more details on how to reproduce this.

**Comment by smartcodinghub** [comment]
I cleaned up the example I was using and I couldn't see the issue again. So I close this.

**Comment by nicdex** [comment]
I found a way to reproduce this.
For some reason when using expected version any and using an eventId that exists in the target stream and also exists in another stream the event will be saved every time.

You can reproduce with this

```
[Test]
        public void Test_passing_append_same_event_with_expected_version_any() {
            var failures = 0;
            //var eventId = Guid.NewGuid();
            for (var i = 0; i < 2; i++) {
                var stream = Guid.NewGuid().ToString();
                var eventId = Guid.NewGuid();
                var eventData = new EventData(eventId, "MyEvent", true, Encoding.Default.GetBytes("{\"a\":1}"), new byte[0]);
                _sut.AppendToStreamAsync(stream, -1, eventData).Wait();
                var result = _sut.AppendToStreamAsync(stream, ExpectedVersion.Any, eventData).Result;
                if (result.NextExpectedVersion != 0) {
                    failures++;
                    Console.WriteLine("Failed #{0} {1} {2}", i, stream, eventId);
                }
            }
            Assert.AreEqual(0, failures);
        }

[Test]
        public void Test_failing_append_same_event_with_expected_version_any() {
            var failures = 0;
            var eventId = Guid.NewGuid();
            for (var i = 0; i < 2; i++) {
                var stream = Guid.NewGuid().ToString();
                //var eventId = Guid.NewGuid();
                var eventData = new EventData(eventId, "MyEvent", true, Encoding.Default.GetBytes("{\"a\":1}"), new byte[0]);
                _sut.AppendToStreamAsync(stream, -1, eventData).Wait();
                var result = _sut.AppendToStreamAsync(stream, ExpectedVersion.Any, eventData).Result;
                if (result.NextExpectedVersion != 0) {
                    failures++;
                    Console.WriteLine("Failed #{0} {1} {2}", i, stream, eventId);
                }
            }
            Assert.AreEqual(0, failures);
        }
```
The difference in the tests being one re-use the same eventId across mutiple streams and the other does not.

**Comment by smartcodinghub** [comment]
That could be the error, as I was testing and is possible that I used many different streams. I'll check it again the next time.
