### ISSUE TITLE
Add api to set stream metadata from a projection

### ISSUE THREAD

**Issue by drewschaeffer** [EventStore/EventStore#195]
Add a function to the projection api to set stream metadata. A use case for this would be in projection that indexes a stream by some key I would like only the most recent event in my indexed streams.

for example, 

$init: function () {
    setStreamMetaData("some_stream", 0, { maxCount = 1 });
    return { ... };
}

alternatively this could optionally be added to emit, linkTo or copy functions.

linkTo("new_stream", e, { maxCount = 1 });

**Comment by xGouley** [comment]
Hello !
Does this feature available now ?

**Comment by loupiz** [comment]
Same question here. Or is there a workaround ?

**Comment by jageall** [comment]
This is probably best dealt with using some kind of policy rather than emitting directly from projections into metadata streams, see #1057
