### ISSUE TITLE
ExpectedVersion class has the wrong values for NoStream and EmptyStream 

### ISSUE THREAD

**Issue by smartcodinghub** [EventStore/EventStore#1950]
**Describe the bug**
The code in [ExpectedVersion](https://github.com/EventStore/EventStore/blob/master/src/EventStore.ClientAPI/ExpectedVersion.cs) have different values to the ones [here](https://eventstore.org/docs/http-api/optional-http-headers/expected-version/index.html?tabs=tabid-1%2Ctabid-3%2Ctabid-5).

NoStream and EmptyStream have the same -1 value.

**Comment by jason-daniels** [comment]
In reading the documentation and code comments, the error is EmptyStream should be 0.

From docs.

- **0, the stream should exist but be empty when writing.**
- -1, the stream should not exist when writing.
- -2, the write should not conflict with anything and should always succeed.
- -4, the stream or a metadata stream should exist when writing.

From code (abbreviated and reordered to make it clear)
```c#
	public static class ExpectedVersion {
		// EmptyStream should be ZERO
		public const int EmptyStream = -1; /// The stream should exist but be empty when writing. ...
		public const int NoStream = -1; /// The stream should not yet exist. ...
		public const int Any = -2; /// The write should not conflict with anything and should always succeed.		
		public const int StreamExists = -4; /// The stream should exist. ...
	}

```

**Comment by smartcodinghub** [comment]
So the client have to be updated, right?

**Comment by jason-daniels** [comment]
Correct. 
I plan on making a pull request for this. I'm just swamped with work.
In the meantime, since it's an int, you can create your own implementation of ExpectedVersion with the correct values.

**Comment by simonlaroche** [comment]
I think the doc is wrong in this case. It goes back to version 1 when you had to explicitly create a stream.
