### ISSUE TITLE
Declarative user defined projections

### ISSUE THREAD

**Issue by JustinLovinger** [EventStore/EventStore#1957]
**Is your feature request related to a problem? Please describe.**
Deploying EventStore with user defined projections is over-complicated due to the reliance on an imperative api for creating user defined projections. The user must start EventStore, then push user defined projections to EventStore. This is a minor issue for manual deployments, but poses several issues in automated deployments and containers like Docker. First, the automated deployment must ensure that the EventStore instance is fully running and prepared to receive requests before pushing the user defined projections, or else the connection will be refused and the projections not deployed. Second, depending on the specifics of the deployment, it may need to determine if the projection already exists and issue a different request depending on whether it exists or not.

**Describe the solution you'd like**
It should be possible to declaratively define user defined projections. In practice, this may take the form of a configuration file with the source and configuration of each user defined projection. When EventStore starts, it should read this configuration file and create or update projections as necessary.

**Describe alternatives you've considered**
The currently best alternative is a custom start-up script that performs the operations described in "Is your feature request related to a problem? Please describe.", starting EventStore then adding new and updating existing projections.

**Additional context**
A little investigation shows that users have had issues regarding deploying EventStore with projections for years.

https://github.com/EventStore/EventStore/issues/1094
https://github.com/EventStore/EventStore/issues/755
https://groups.google.com/forum/#!searchin/event-store/docker$20projection|sort:date/event-store/h5IXC8PhAxU/bwJPHQH2AAAJ
https://groups.google.com/forum/#!searchin/event-store/docker$20projection|sort:date/event-store/H0QsRGv7OIc/COvas2BqBwAJ

**Comment by oskardudycz** [comment]
@jageall, @hayley-jean do we plan to tackle that soon? This seems to be valid case, even for our CI.

**Comment by condron** [comment]
We have replaced the projection engine in the current version and
a full overhaul of the projection engine API is on the roadmap.

While I don't think this suggestion will be incorporated directly 
as the new API will not work in the same way the core desire to 
allow straightforward automated loading of projections will be supported.
