### ISSUE TITLE
Allow for non-administrator accounts to manage projections

### ISSUE THREAD

**Issue by sawatzkylindsey** [EventStore/EventStore#1966]
**Is your feature request related to a problem? Please describe.**
We use special accounts for various levels of access control, such as readers and writers.
However, it appears that only administrator accounts are allowed to manage projections, which means that any custom account must be in the `$admins` group to automatically setup its own projections.

**Describe the solution you'd like**
We would like for accounts without full administrative access to still be able to manage projections.
This would still allow for some degree risk mitigation so that these accounts still cannot manage general administrative settings, such as users themselves, but still be able to manage projections.

**Describe alternatives you've considered**
The alternative is to allow these custom accounts, such as readers and writers, full administrative control - completely defeating the purpose of access control to begin with.

**Comment by shaan1337** [comment]
@sawatzkylindsey hello! This has been fixed in #1962 which will be out soon in version 5.0.2.
$ops users will now be able to manage projections
