### ISSUE TITLE
Persistent Subscription endpoint

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#1973]
**Is your feature request related to a problem? Please describe.**
When we create a persistent subscription, we had to write a custom piece of software to actually deliver events to an endpoint.

**Describe the solution you'd like**
When creating a Persistent Subscription, have an option of specifying an HTTP endpoint to post the events to.

**Describe alternatives you've considered**
Continue using a custom piece of software.

**Additional context**
I am guessing each user of an Event Store that works with Persistent Subscriotions has had to build a piece of software to actually pick up and deliver the events. Would be nice if this was part of the core Event Store.

**Comment by hayley-jean** [comment]
Hi @StevenBlair123, could you please clarify what you mean by delivering events to an endpoint?

**Comment by StevenBlair123** [comment]
So, having the event store POSTing events to an endpoint.
Imagine creating a new persistent subscription, and having the option to add a URL(s) to POST to.
That way the event delivery could be standard for all Event Store users.

Unless I am missing something, I suspect all Event Store users who use persistent subscriptions have a custom piece of software that connects to a group and then posts the events to an endpoint?

**Comment by alexeyzimarev** [comment]
Persistent subscriptions were never designed to do push-based delivery over HTTP. We only implemented it now in HTTP connector sink (since 24.2). https://developers.eventstore.com/connectors
