### ISSUE TITLE
Disable technical streams when SubscribeToAllFrom

### ISSUE THREAD

**Issue by dmitribodiu** [EventStore/EventStore#1985]
I'm using connection.SubscribeToAllFrom to rebuild my readmodels in a cqrs application. I'm getting too much useless events from streams I'm not interested in, i.e stats..

Is there any way to disable getting events from technical streams, but getting all events from all streams I've created?

**Comment by gregoryyoung** [comment]
$all works differently than other subscriptions you would not filter in the subscription itself but on the client (eg (e) -> if(!e.EventType.StartsWith("$")) return e. $all is designed to return all events. There are some varying ways of achieving what you are asking but you probably don't want to do them.

**Comment by dmitribodiu** [comment]
I could do:
SubscribeToStreamAsync("Holders")
SubscribeToStreamAsync("Accounts")
SubscribeToStreamAsync("AccountTransactions")
but that wouldn't guarantee the order? Or SubscribeToAllFrom doesn't guarantee the messages order too?

**Comment by Narvalex** [comment]
SubscribeToAllFrom does guarantee order. There are [efforts](https://github.com/EventStore/EventStore/pull/1972) to achieve what you want though.

**Comment by dmitribodiu** [comment]
I solved my problem creating a new projection which collects events from separate aggregate streams (Holders, Accounts, AccountTransactions) and emits them into a new $allAggregates stream. 

fromStreams(["$ce-Holders", "$ce-Accounts", "$ce-AccountTransactions"])
    .when({
       $any: function(s, e) {
           emit("$allAggregates", e.eventType, e.data)
       } 
    });

**Comment by Narvalex** [comment]
> I solved my problem creating a new projection which collects events from separate aggregate streams (Holders, Accounts, AccountTransactions) and emits them into a new $allAggregates stream.
> 
> ```
> fromStreams(["$ce-Holders", "$ce-Accounts", "$ce-AccountTransactions"])
>     .when({
>        $any: function(s, e) {
>            emit("$allAggregates", e.eventType, e.data)
>        } 
>     });
> ```
That projection does not guarantee order AFAIK

**Comment by Narvalex** [comment]
If you are good with having lots of link events, this projection will help you to get a stream with all your domain events only, with order guaranteed

```
fromAll()
    .when({ 
        $any: (s, e) => {
            if (e.streamId.substring(0, 1) === '$')
                return;

            linkTo('all', e);
       }
})
```

**Comment by dmitribodiu** [comment]
> If you are good with having lots of link events, this projection will help you to get a stream with all your domain events only, with order guaranteed
> 
> ```
> fromAll()
>     .when({ 
>         $any: (s, e) => {
>             if (e.streamId.substring(0, 1) === '$')
>                 return;
> 
>             linkTo('all', e);
>        }
> })
> ```

I did exactly this but then .SubscribeToAllFrom didn't return any events...Are you sure my implementation doesn't guarantee the order? I think I saw a projection param related to ordering precision...

**Comment by Narvalex** [comment]
The ordering precision in is a best effort approach as far as I know. Only $all is order guarantee since it is like the transaction log itself. I have like 3 years running subscriptions to projections like the above one without issues

**Comment by oskardudycz** [comment]
You can use filtered subscriptions to all and ignore system events both in TCP and gRPC clients. See gRPC client docs for more information: https://developers.eventstore.com/clients/grpc/subscriptions.html#filtering-out-system-events.
