### ISSUE TITLE
Investigate possibility of an Event Store Testing Library?

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#1986]
Related to a [PR](https://github.com/EventStore/EventStore/pull/1625) from @megakid

**Comment by rhwilburn** [comment]
This was something that hit me quite quickly too when wanting to test azure functions by submitting mocks. The `RecordedEvent`, ResolvedEvent and IResolvedEvent all had Internal parts preventing simple mocks being made

**Comment by rhwilburn** [comment]
Here is the code I used to get around this issue (in case others require it). It took a bit longer than I expected:

            var recordedEvent = (RecordedEvent)FormatterServices.GetUninitializedObject(typeof(RecordedEvent));
            var resolvedEvent = (ResolvedEvent)FormatterServices.GetUninitializedObject(typeof(ResolvedEvent));

            var recordedEventDataField = typeof(RecordedEvent).GetField(nameof(RecordedEvent.Data), BindingFlags.Instance | BindingFlags.Public);
            byte[] eventDataBytes = Encoding.UTF8.GetBytes(eventData);
            recordedEventDataField.SetValue(recordedEvent, eventDataBytes);

            var recordedEventEventTypeField = typeof(RecordedEvent).GetField(nameof(RecordedEvent.EventType), BindingFlags.Instance | BindingFlags.Public);
            recordedEventEventTypeField.SetValue(recordedEvent, eventType.Name);

            var recordedEventMetaDataField = typeof(RecordedEvent).GetField(nameof(RecordedEvent.Metadata), BindingFlags.Instance | BindingFlags.Public);
            byte[] eventMetadataBytes = Encoding.UTF8.GetBytes(sessionId);
            recordedEventMetaDataField.SetValue(recordedEvent, eventMetadataBytes);

            //TODO: Fix issue where the OriginalEvent isn't populated from this field.
            var resolveEventEventField = typeof(ResolvedEvent).GetField(nameof(ResolvedEvent.Event), BindingFlags.Instance | BindingFlags.Public);
            //The line below is explained here: https://www.productiverage.com/trying-to-set-a-readonly-autoproperty-value-externally-plus-a-little-benchmarkdotnet
            resolveEventEventField.SetValueDirect(__makeref(resolvedEvent), recordedEvent);

**Comment by StevenBlair123** [comment]
We had a similar problem.
