### ISSUE TITLE
Connection/Socket leak under linux dotnet2.2

### ISSUE THREAD

**Issue by Zetanova** [EventStore/EventStore#2010]
**Describe the bug**
Under dotnet2.2 linux the Socket does not get propertly closed
and open connection stack up until HttpClients and other network components fail with "address already in use" 

related: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/273

**To Reproduce**
Using the healthcheck from https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.EventStore/EventStoreHealthCheck.cs
```
using (var connection = EventStoreConnection.Create(
                    connectionSettings,
                    eventStoreUri,
                    CONNECTION_NAME))
                {
                    await connection.ConnectAsync();
                }
```

**Expected behavior**
TCP connection and the socket getting fully closed under linux

**Actual behavior**
TCP connection and socket count  stack up until system limit. 

**Config/Logs/Screenshots**
single node, default docker image config

**EventStore details**
 - EventStore server version:
5.0,1

 - Operating system:
CentOS 7, dotnet2.2

 - EventStore client version (if applicable):
5.0.1

**Comment by Zetanova** [comment]
The sockets of the tcp connection (port 1113) in the state CLOSE-WAIT are pilling server and client site up.  Checked with ss of iproute2 package.

Restarting the client process are closing the tcp connection on the server.

My suspicion is that the socket instance is leaking and dont get closed/disposed in 
https://github.com/EventStore/EventStore/blob/master/src/EventStore.ClientAPI/Transport.Tcp/TcpClientConnector.cs

The socket instance under linux need to be explicitly closed/disposed
the finalizer is not enough.

**Comment by Zetanova** [comment]
The PR https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/277 fixed the issue for the other project.

But it still happens when then connection is just created, connect is called and immediately disposed,
before awaiting an event Connected, Closed or ErrorOccurred

This is working, like in the UnitTests
```csharp
using (var connection = EventStoreConnection.Create(connectionSettings, eventStoreUri, "name"))
{
   var tcs = new TaskCompletionSource<string>();

  //connected
  connection.Connected += (s, e) => tcs.TrySetResult("success");
   //connection closed after configured amount of failed reconnections
   connection.Closed += (s, e) => tcs.TrySetFailue(new Exception(e.Reason));
    //connection error
   connection.ErrorOccurred += (s, e) => tcs.TrySetException(e.Exception));

    await connection.ConnectAsync();

    //await to fully connect and dispose to not leak the connection after dispose
    await tcs.Task;
}
```

**Comment by shaan1337** [comment]
This could be linked to: https://github.com/EventStore/EventStore/pull/2062

**Comment by shaan1337** [comment]
@Zetanova thanks very much for the report.

I can confirm that this bug still affects version 6.0.0-preview 2 of the server with the 6.0.0-preview2 client. Also successfully reproduced on version 5.0.5 with client 5.0.5.
