### ISSUE TITLE
Remove Internal/External designation for network interfaces

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#2018]
As part of ES6 we are rationalising the client protocols, and it is strictly worse to have internal/external traffic split in the current manner. Instead we should replace it with a single socket for everything.

**Comment by pgermishuys** [comment]
See #2094

**Comment by oskardudycz** [comment]
There is no separation between internal and external interfaces now. The external TCP interface will be removed when fully deprecates the TCP client.
