### ISSUE TITLE
Issue Starting EventStore

### ISSUE THREAD

**Issue by StuartFergusonVme** [EventStore/EventStore#2023]
I am experiencing an issue starting my Event Store where looking at the logs everything appears to be running and I am able to telnet to the TCP port and also can get to the login screen on the UI.

Data File Size: ~44GB.
Event Store Version: 5.0.2

I have attached the latest log file from the Event Store startup where is seems to have stuck on the Index Rebuild.

I have also set the following values in the config to try and speed up the rebuild as suggested on this thread (https://groups.google.com/forum/#!topic/event-store/NrQMnyT42nU)

EVENTSTORE_OPTIMIZE_INDEX_MERGE: "True"
EVENTSTORE_SKIP_INDEX_VERIFY: "True"
EVENTSTORE_SKIP_DB_VERIFY: "True"

Any help on this issue would be appreciated.

Stuart

[10.0.1.231-2113-cluster-node.log](https://github.com/EventStore/EventStore/files/3733624/10.0.1.231-2113-cluster-node.log)

**Comment by mat-mcloughlin** [comment]
Hey @StuartFergusonVme sorry we didn't get to this one earlier. Did you find the problem?
