### ISSUE TITLE
Azure appservice support ?

### ISSUE THREAD

**Issue by iangregsondev** [EventStore/EventStore#2032]
Hi,

I would like to deploy the eventstore to an appservice on azure, does anyone have any experience with this?

I would prefer to use .net core

Any help really appreciated

Thanks.

**Comment by mat-mcloughlin** [comment]
Hey, @iangregsondev we are currently working on .net core support here https://github.com/EventStore/EventStore/issues/1716

**Comment by iangregsondev** [comment]
Ok - thank you. I will close this then and follow that. Thanks!
