### ISSUE TITLE
AppendToStreamAsync CommitPosition -1

### ISSUE THREAD

**Issue by p0onage** [EventStore/EventStore#2033]
**Describe the bug**
I am calling AppendToStreamAsync like below 
`      var writeResult = await connection.AppendToStreamAsync(someid, ExpectedVersion.Any, eventToPost);`

there is no exception being thrown but the` writeResult.LogPosition.CommitPosition` and `writeResult.LogPosition.PreparePosition` are both -1 

An event is not being written to the Event store. 

**To Reproduce**
I can't reproduce this, another similar event went through fine multiple times

**Expected behavior**
I expect the event to get written to the event store and return back a positive commit position 

**Actual behavior**
I've had to add extra code as a workaround to see if the events are being saved 
` var eventSaved = writeResult.LogPosition.CommitPosition != -1 && writeResult.LogPosition.PreparePosition != -1;`

**EventStore details**
Event Store 5.0.2.0 

 - Operating system:
Windows 10 

 - EventStore client version (if applicable):
EventStore.ClientAPI 5.0.2

**Comment by ylorph** [comment]
Closing because of older DB version that is not supported anymore
Please reopen if you see this again.
