### ISSUE TITLE
Your public website with the link to version 5.0.4 for Windows is not resolving, just redirecting to home page

### ISSUE THREAD

**Issue by stoepa** [EventStore/EventStore#2043]
**Describe the bug**
Can't download the lates version for your Windows client.
https://eventstore.org/downloads/win/EventStore-OSS-Win-v5.0.4.zip

**To Reproduce**
1. Open the site.
2. Click on downloads.
3. Click on the link that says Windows 64-bit (.NET 4.7.1+)

**Expected behavior**
That the download starts.

**Actual behavior**
It redirects back your public site home address.

**Additional context**
Not related to eventstore self, but rather your public site.

**Comment by bartelink** [comment]
as a workaround, change 5.0.4 to 5.0.3 (that released about a week ago)

**Comment by pgermishuys** [comment]
@stoepa thanks for raising this. We are working on getting this resolved ASAP. Thanks @bartelink for providing a work around in the meantime.

**Comment by pgermishuys** [comment]
@stoepa this issue has been resolved. Please don't hesitate to reopen if you run into any further issues related to this.
