### ISSUE TITLE
PTable WorkItem ObjectPool is not scaled up according to number of reader threads

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2044]
**Describe the bug**
This is a bug similar to the one this PR fixes:
https://github.com/EventStore/EventStore/pull/1737/files

Basically, the PTable work item object pool is not scaled up according to the number of reader threads:
https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Index/PTable.cs#L105

Like it's done here for the `readerPool`:
https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/ClusterVNode.cs#L204

Instead the default parameter `maxReaders` is used which is equal to `ESConsts.PTableMaxReaderCount`, currently 17:
https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Index/PTable.cs#L84

If the number of reader threads is set to a value greater than `ESConsts.PTableMaxReaderCount` (which is currently 17) and there is a high volume of reads (making use of all reader threads), the object pool limit will be reached and it will throw `ObjectPoolMaxLimitReachedException`.

It appears there's also a similar issue with the TFChunk constructor which uses the `ESConsts.TFChunkMaxReaderCount` constant as `maxReaderCount` parameter in several places.

**EventStore details**
 - EventStore server version:
5.0.3

 - Operating system:
All

 - EventStore client version (if applicable):
N/A

**Comment by condron** [comment]
please coordinate with me before starting work on this.

**Comment by hayley-jean** [comment]
Fixed by https://github.com/EventStore/EventStore/pull/2069
