### ISSUE TITLE
Default password admin user

### ISSUE THREAD

**Issue by frederiksf** [EventStore/EventStore#2045]
Which options does EventStore offer for this matter. We are using Eventstore 5.2 (docker container) and we would like to change the default password "changeit" programmatically.

**Comment by mat-mcloughlin** [comment]
Hey @frederiksf there are two options for programmatically changing the default admin password.

You can either use the .net client where the follow code snippet will change the password to "test123":

```
var usersManager = new UsersManager(new ConsoleLogger(), new IPEndPoint(IPAddress.Loopback, 2113), TimeSpan.FromSeconds(30));
await usersManager.ChangePasswordAsync("admin", "changeit", "test123", new UserCredentials("admin", "changeit"));
```

Or you can do it via HTTP with the following http command

```
POST /users/admin/command/change-password HTTP/1.1
Host: localhost:2113
Content-Type: application/json
Authorization: Basic YWRtaW46Y2hhbmdlaXQ=

{
    "currentPassword": "changeit",
    "newPassword": "test123"
}
```

**Comment by mat-mcloughlin** [comment]
Closed due to no further feedback
