### ISSUE TITLE
Reading from $et-{event_type} doesn't return proper event data

### ISSUE THREAD

**Issue by swilgosz** [EventStore/EventStore#2054]
**Describe the bug**

When I read events using projection based on event type and subscription - the returned entries do not have all data properly filled in

**To Reproduce**

1. Enable projection based on event type
2. Publish Event to a stream: "newstream" with type: "SomethingHappened"
3. Subscribe to 'newstream  ` curl -i "http://127.0.0.1:2113/subscriptions/newstream/default?embed=body" -H "Content-Type:application/json" -u admin:changeit -X PUT -d $'{"startFrom": 0,"resolveLinktos": false}'`
4. Subscribe to "$et-SomethingHappened": ` curl -i "http://127.0.0.1:2113/subscriptions/%24et-SomethingHappened/default?embed=body" -H "Content-Type:application/json" -u admin:changeit -X PUT -d $'{"startFrom": 0,"resolveLinktos": false}'`
5. Read from `newstream/default` : `curl -i "http://127.0.0.1:2113/subscriptions/newstream/default?embed=body" -H "Accept:application/vnd.eventstore.competingatom+json" -u admin:changeit -X GET`
6. Read from `$et-SomethingHappened/default`: `curl -i "http://127.0.0.1:2113/subscriptions/%24et-SomethingHappened/default?embed=body" -H "Accept:application/vnd.eventstore.competingatom+json" -u admin:changeit -X GET`

**Expected behavior**

I expect both of the responses to be pretty the same. The $et-SomethingHappened groups the events based on the type - so with `embed=body` should return the event type and data in the consistent way.

**Actual behavior**

When reading the subscription `$et-SomethingHappened/default` updates, we get wrong event details: 

- eventType set to `$>`
- no data entry

When reading the subscription `newstream/default` we get expected response.

**Config/Logs/Screenshots**

```shell
# Example entry response $et-SomethingHappened/default

{
      "eventId": "69918928-7524-4d8d-bb3a-e141c9e58d21",
      "eventType": "$>",
      "eventNumber": 19,
      "metaData": "{\"$v\":\"4:-1:1:3\",\"$c\":12443363,\"$p\":12443363,\"$causedBy\":\"cbe3ff39-c31e-4943-90ec-59aaa877ef35\"}",
      "streamId": "$et-SomethingHappened",
      "isJson": false,
      "isMetaData": true,
      "isLinkMetaData": false,
      "positionEventNumber": 19,
      "positionStreamId": "$et-SomethingHappened",
      "title": "19@$et-SomethingHappened",
      "id": "http://127.0.0.1:2113/streams/%24et-SomethingHappened/19",
      "updated": "2019-11-14T10:30:16.663586Z",
      "author": {
        "name": "EventStore"
      },
      "summary": "$>",
      "links": [
        {
          "uri": "http://127.0.0.1:2113/streams/%24et-SomethingHappened/19",
          "relation": "edit"
        },
        {
          "uri": "http://127.0.0.1:2113/streams/%24et-SomethingHappened/19",
          "relation": "alternate"
        },
        {
          "uri": "http://127.0.0.1:2113/subscriptions/%24et-SomethingHappened/default/ack/69918928-7524-4d8d-bb3a-e141c9e58d21",
          "relation": "ack"
        },
        {
          "uri": "http://127.0.0.1:2113/subscriptions/%24et-SomethingHappened/default/nack/69918928-7524-4d8d-bb3a-e141c9e58d21",
          "relation": "nack"
        }
      ]
    }
```

```shell
# Example entry response for newstream/default

{
      "eventId": "620d86b3-a7c3-4167-a68b-950a52c3e358",
      "eventType": "SomethingHappened",
      "eventNumber": 1,
      "data": "{\n  \"user_id\": \"6eca5570-9758-4c37-8818-3e84cefe12fd\",\n  \"title\": \"Something happened\"\n}",
      "metaData": "{\n  \"created_at\": \"2019-11-13 19:47:28 +0100\"\n}",
      "streamId": "newstream",
      "isJson": true,
      "isMetaData": true,
      "isLinkMetaData": false,
      "positionEventNumber": 1,
      "positionStreamId": "newstream",
      "title": "1@newstream",
      "id": "http://127.0.0.1:2113/streams/newstream/1",
      "updated": "2019-11-13T18:47:28.437459Z",
      "author": {
        "name": "EventStore"
      },
      "summary": "SomethingHappened",
      "links": [
        {
          "uri": "http://127.0.0.1:2113/streams/newstream/1",
          "relation": "edit"
        },
        {
          "uri": "http://127.0.0.1:2113/streams/newstream/1",
          "relation": "alternate"
        },
        {
          "uri": "http://127.0.0.1:2113/subscriptions/newstream/default/ack/620d86b3-a7c3-4167-a68b-950a52c3e358",
          "relation": "ack"
        },
        {
          "uri": "http://127.0.0.1:2113/subscriptions/newstream/default/nack/620d86b3-a7c3-4167-a68b-950a52c3e358",
          "relation": "nack"
        }
      ]
    }

```

If applicable, please attach your node configuration, logs or any screenshots.

**EventStore details**
 - EventStore server version: 5.0.4.0

 - Operating system: Max OS

 - EventStore client version (if applicable): Docker image

**Comment by StevenBlair123** [comment]
swilgosz,

Could it be this:

"resolveLinktos": false

Shouldn't that be true so it resolves the event for you, rather than the link?

**Comment by swilgosz** [comment]
Yes, you are right! It works perfectly now!

Thank you!
