### ISSUE TITLE
Eventstore Crashing With "object.__icall_wrapper_mono_gc_alloc_vector"

### ISSUE THREAD

**Issue by Koreander** [EventStore/EventStore#2059]
**Describe the bug**
We have a 3 node cluster with a 4th node set as clone. The master node crashed twice this week with a "object.__icall_wrapper_mono_gc_alloc_vector" exception. The first time it also corrupted our $by_category projection, which couldn't continue after electing another node as master.

Additional:
- We're running scavenges on all 4 nodes, maybe that has an impact.
- Memory usage at the time of the crash (as per Eventstore stats) wasn't particularly high.

**To Reproduce**
Havn't been able to reproduce it.

**Expected behavior**
The Eventstore doesn't crash with this exception or can recover from it.

**Actual behavior**
Eventstore crashes with an exception and doesn't recover from it.

**Config/Logs/Screenshots**
[ES01-crash-stacktrace.txt](https://github.com/EventStore/EventStore/files/3868488/ES01-crash-stacktrace.txt)

**EventStore details**
 - EventStore server version: 5.0.4-1
 - Operating system: Google Cloud VM with ubuntu-1604-xenial

**Comment by oskardudycz** [comment]
Closing, as we're not supporting:
- Mono,
- v5,
- Ubuntu 16.04
anymore.
