### ISSUE TITLE
Official Chocolatey package for event store

### ISSUE THREAD

**Issue by mastoj** [EventStore/EventStore#208]
It would be really nice if Event Store was installable as a chocolatey package. This would also make it easier to set things up with puppet on Windows. I don't mean that it should be a package that creates a service etc. the package should be kept simple just putting Event Store on the machine. Then it is up to everyone to decide how to run it.

**Comment by jen20** [comment]
Now we have Linux packages it makes sense to also have a Windows one for the open source product and potentially a commercial feed as well. Let's look at this for 3.3.0.

**Comment by thefringeninja** [comment]
So maybe two new chocolatey packages that you guys control, eventstore-oss
and eventstore-commercial? IIRC the package version of the eventstore choco
package does not follow your versioning when it probably should.

On Mon, Sep 7, 2015 at 6:16 PM, James Nugent <notifications@github.com>
wrote:

> Now we have Linux packages it makes sense to also have a Windows one for
> the open source product and potentially a commercial feed as well. Let's
> look at this for 3.3.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/208#issuecomment-138334429>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by jen20** [comment]
Seems like a reasonable idea. We'll probably call `eventstore-commercial` by the name `eventstore-ha` like on the Debian distribution, and host it on a private authenticated feed (again like the Debian distribution).

**Comment by ferventcoder** [comment]
Note my comments here from back in November. https://chocolatey.org/packages/eventstore/3.0.1.0

I'd consider this package maintainer as abandoned, although he was active on one package as late as May this year.

> like the Debian distribution
@jen20 I like the way you think. I think we think alike in package naming, making cross platform naming matches.


> package version doesn't match event store version
That's easy enough to fix. It definitely should match.



When you guys are ready to take over the existing package, just let me know your Chocolatey user names.

**Comment by jen20** [comment]
Thanks @ferventcoder, we'll let you know when there's some progress on this internally.

**Comment by jen20** [comment]
@ferventcoder is there any reason not to extract to `%ChocolateyInstall%\lib\eventstore-oss`? Are there any standards you've seen adopted for config/data/log locations? (e.g. an equivalent to `/etc/eventstore`, `/var/lib/eventstore` and `/var/log/eventstore`) in order that we can set defaults that chocolatey users will be expecting?

**Comment by ferventcoder** [comment]
@jen20 as the software owners, you can just put the bits right into the package. That should make it somewhat simpler. If you prefer, you can point to your official download distribution if you want to keep track of downloads in a central location.

> Are there any standards you've seen adopted for config/data/log locations?

There is not a standard set by Chocolatey. I've seen it done in the following ways:

- local machine location (app run as admin) - `C:\ProgramData\<appname>\{etc,var}`
- local user context - `c:\Users\<username>\LocalAppData\<appname>\{logs,etc,var}
- choco package - `<pkg location>\<subfolder(s)\{logs,etc,var}`

You could adopt the same thing that Puppet does, which is to keep those in a subfolder under a `C:\ProgramData\PuppetLabs\puppet` directory. That the same as the first option above.

**Comment by jen20** [comment]
Thanks. I don't care about tracking downloads (presumably we can see the stats through the Chocolatey gallery anyway?) so will put the bits in the package. I forgot it works differently to apt where you specify the entire filesystem layout.

We'll follow the example set by Puppet and go with the first option I think.

Thanks!

**Comment by hayley-jean** [comment]
Chocolatey packages for Event Store are [now available](https://chocolatey.org/packages/eventstore-oss)
