### ISSUE TITLE
Decide on default protocols for V6

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#2094]
V6 now supports three client protocols:

- gRPC
- Atom over HTTP
- Old protobuf over TCP

While we can't completely get rid of (3) because of replication at this point, there is no need to accept client requests via it necessarily.

IMO we should only enable gRPC for client requests by default in V6 of Event Store, and allow users to opt into Atom and Protocol Buffers over TCP with flags.

**Comment by pgermishuys** [comment]
As discussed with @jageall. We can add the flags for disabling atom and external tcp (we still need internal TCP for replication) but they won't do anything as of yet apart from the warnings described below.

In addition to the flags, we need to display a deprecation warning in the logs if the "features" are enabled.

**Comment by jen20** [comment]
We don't have time to do this as part of preview 2, but should document it in the release notes. See #2222 for the documentation part of this.
