### ISSUE TITLE
HTTPS by default or not?

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#2097]
When starting up Event Store, we listen on `HTTPS`. We have no way to toggle this on or off from what I can tell.
- What do we want our default protocol to be?
- How do we deal with certificates?

**Comment by mat-mcloughlin** [comment]
- We are not going to provide an option to disable https
- Allow kestrel to use the dev cert, provide a `--dev` option

**Comment by mat-mcloughlin** [comment]
@jageall Does this actually need to go into preview?

**Comment by mat-mcloughlin** [comment]
close by #2134
