### ISSUE TITLE
Add EventStore image as official Docker image

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#2146]
**Is your feature request related to a problem? Please describe.**
Make the Docker image for EventStore official

**Describe the solution you'd like**
There is already a PR open on the Docker repository for official images that need to be completed.
There are some suggestions on it that souldn't be difficult to apply
https://github.com/docker-library/official-images/pull/5327

**Comment by oskardudycz** [comment]
@thefringeninja, @hayley-jean, do we plan to make it an official Docker image?

**Comment by thefringeninja** [comment]
@oskardudycz don't think it's going to happen

docker-library/official-images#5327

**Comment by oskardudycz** [comment]
Ok, then I'm closing it for now. We can reopen it or create a new issue if we want to revive this idea in the future.
