### ISSUE TITLE
Update of stored Events after code updates

### ISSUE THREAD

**Issue by andronachev** [EventStore/EventStore#2147]
Hi,

This is not really an issue, it's more like a discussion, because it clearly says here: https://eventstore.org/blog/20130528/why-cant-i-update-an-event/   that Events can't and shouldn't be Updated. And I agree with the arguments (in theory) but now we have the following situation:

We are currently using EventStore.org as our (shockingly) event store. So far we've gone on with the following approach: 
                         1) Each aggregate has it's own Stream, with the naming convention: "AggregateName-AggregateId" 
                         2) The Event Type is set to the Assembly Fully Qualified name , so later when we get the event's back we know the Type and can deserialize the json Data and reconstitute.  

However we recently decided for other reasons, to change our Event Type in from the fully qualified name to the simple type name... since the EventType property is in our BaseEvent class, the change got propagated everywhere, including all the way to EventStore, so now our new Streams have the new Event Type. This leaves us with thousands of "old" aggregates / streams, which have the EventType in the old form. 

So how should we go about updating (migrating) these old Events ? The article above states that the only option would be to create a new Stream and delete the old one. I've tried to do that using the .NET API, it works, but the following thing happens below: (screenshot is of a really old migrated aggregate, please ignore the fact that there are 5 "PartnerRegistered" events, I was doing debugging, and this is the QA environment )

![image](https://user-images.githubusercontent.com/16139612/70866199-7ef46c00-1f6f-11ea-95d3-0383aa4bf62b.png)

You can see the Event's numbering has not been reset, it goes on from 5, whereas previously it was 0... also the more worrying thing for me is the Created Date, as you see it's been reset (of course, as this is a new Stream, with new events...). What are the implications to this approach ? I.e. having all the streams reset like this, with the Creation Date probably identical for all Events in them ... it doesn't seem like a good idea to me, to practice this kind of migration on all aggregates. For us internally, we use a "CreationDateUtc" that we store in the Data payload, so not a problem for us, but I am not sure what the implications are in Event Store (if we were to decide later to use the Projections functionality, or anything else). 

Here is a screenshot of a not-migrated aggregate, so you see what I am talking about, the Type column: 

![image](https://user-images.githubusercontent.com/16139612/70866238-ead6d480-1f6f-11ea-97c4-64881a8372b7.png)

So how would you get around this, should should we continue on with deleting and creating of new Streams ? But also, thinking in the future.... I understand the theortical arguments of not letting Update operations happen... but maybe we change our classes' structure (that we deseralize the event's JSON into.... so then we would need the event's JSON migrated too, how would you get around that ?) 

Looking forward to your opinion,
Vlad

**Comment by pgermishuys** [comment]
Hey @andronachev, we see you have asked the [same question](https://groups.google.com/forum/#!topic/event-store/HObfHhViDoU) in the google groups which @gregoryyoung replied to. Closing this issue in favor of the one in the google groups as that's the more appropriate platform for discussions.

Please don't hesitate to reach out if you require any further help.
