### ISSUE TITLE
Cluster Internal SSL SocketClosed

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [EventStore/EventStore#2170]
**Describe the bug**
After setting up SSL following [the docs](https://eventstore.org/docs/server/setting-up-ssl/index.html?tabs=tabid-6%2Ctabid-8#setting-up-ssl-on-linux) on a three node cluster, and enabling internal SSL, the replica nodes throw `OPENSSL_internal:CERTIFICATE_VERIFY_FAILED` when connecting to the master. The client then does a socket hangup and elections begin again. 

The certificate is trusted by the machine mono store, and as a debugging step I added it to the `eventstore` user's mono store as well, but got the same results. Setting `SslValidateServer: false` doesn't seem to prevent the validation error. 

**To Reproduce**
1. Generate a self signed RSA cert on one node and p12 bundle
2. Copy this cert and p12 bundle to each node
3. Update the OS and mono trust stores according to the docs [the docs](https://eventstore.org/docs/server/setting-up-ssl/index.html?tabs=tabid-6%2Ctabid-8#setting-up-ssl-on-linux)
4. Enable cluster internal SSL, and set `SslTargetHost` to the CN of the RSA cert and bring `eventstored` up

**Expected behavior**
A successful master election, followed by a healthy cluster

**Actual behavior**
Failed certificate verification and continual failed elections

**Config/Logs/Screenshots**
* [Node configuration](https://gist.github.com/01100010011001010110010101110000/7c12b12a2494e6c7b41d4f871261dfa5)
* [Client error log sample](https://gist.github.com/01100010011001010110010101110000/33ab5ec1658ad711f9e5c3b22080e420)

**EventStore details**
 - EventStore server version: `release-5.0.5`

 - Operating system: Ubuntu 18.04, installed via the `.deb`

 - EventStore client version (if applicable): N/A

**Comment by hayley-jean** [comment]
Hi @01100010011001010110010101110000, what version of Mono is installed on the Event Store server?

Event Store version 5 requires Mono 5.16.0 to be installed when using SSL.
We have updated the docs to include the mono version, but the changes aren't reflecting just yet.

**Comment by 01100010011001010110010101110000** [comment]
The mono version is `5.16.0.220`

**Comment by 01100010011001010110010101110000** [comment]
Thanks for updating the docs, the version of `mono-devel` was incompatible with the `mono` version packaged with the ES `.deb`. This works after installing the correct `mono-devel` from the updated docs
