### ISSUE TITLE
ES6: `stream.proto` rename options oneof's to use singular

### ISSUE THREAD

**Issue by LucioFranco** [EventStore/EventStore#2173]
In trying to get `tonic` to compile the new ES6 proto there is a conflict with names with the `oneof` options and the enum option. The fix is to rename the `oneof` to `*_option` instead of `*_options`. 

```
diff --git a/protos/es6/streams.proto b/protos/es6/streams.proto
index 1bd3210..15bbee5 100644
--- a/protos/es6/streams.proto
+++ b/protos/es6/streams.proto
@@ -13,17 +13,17 @@ message ReadReq {
        Options options = 1;

        message Options {
-               oneof stream_options {
+               oneof stream_option {
                        StreamOptions stream = 1;
                        AllOptions all = 2;
                }
                ReadDirection read_direction = 3;
                bool resolve_links = 4;
-               oneof count_options {
+               oneof count_option {
                        int32 count = 5;
                        SubscriptionOptions subscription = 6;
                }
-               oneof filter_options {
+               oneof filter_option {
                        FilterOptions filter = 7;
                        Empty no_filter = 8;
                }
@@ -41,7 +41,7 @@ message ReadReq {
                        }
                }
                message AllOptions {
-                       oneof all_options {
+                       oneof all_option {
                                Position position = 1;
                                Empty start = 2;
                                Empty end = 3;
```

cc @jen20

**Comment by YoEight** [comment]
This is something that is causing me trouble there: https://github.com/YoEight/eventstore-rs/pull/32

Thanks for reporting that issue!

**Comment by jen20** [comment]
@thefringeninja I thought we had resolved all these but apparently not. This looks good to me, but I'll defer to you. If we're going to do this (which I think we should), now (early in the release cycle) is a good time.

**Comment by LucioFranco** [comment]
This also seems like its not an isolated incident https://twitter.com/ahjohannessen/status/1208718807478493184?s=20

**Comment by jen20** [comment]
No, I was fairly sure there was an issue describing some other changes for Scala but I can't find it now.

**Comment by jen20** [comment]
Ah, it's linked to in that tweet, for some reason I thought that was a PR on this repo. https://github.com/ahjohannessen/sec/commit/494e6ed4a5f4520b6fc75c4095c7c1016ff38e2d for future readers.
