### ISSUE TITLE
Cosmos 

### ISSUE THREAD

**Issue by ekjuanrejon** [EventStore/EventStore#2174]
What is the possibility of Event Store using cosmos db or some cloud persistence that is easier to geo replicate

**Comment by gregoryyoung** [comment]
EventStore is a database. How would it *use* cosmos db?!

You can also fairly trivially georeplicate eventstore nodes ...

What problem are you trying to solve?

**Comment by ekjuanrejon** [comment]
We've been using eventstore for a good while now. We are planning to go live and we are looking into DR and RPO and we feel event store does not quite meet those demands. Cosmos has better support

**Comment by gregoryyoung** [comment]
What demands? You have not said what they are? 

It sounds like what you want is higher availability at the cost of consistency is that correct? This is a fundamental tradeoff in distributed systems ... it can be achieved.... 

Without knowing what precisely you want its hard to actually give you an answer though.

**Comment by ekjuanrejon** [comment]
How can even store use azure storage account to persist the data. Storage accout seems to support geo replication

**Comment by Narvalex** [comment]
> We've been using eventstore for a good while now. We are planning to go live and we are looking into DR and RPO and we feel event store does not quite meet those demands. Cosmos has better support

Did you meant "Disaster Recovery" (DR) and "Recovery Point Objective" (RPO)?

**Comment by ekjuanrejon** [comment]
@Narvalex yes

**Comment by pgermishuys** [comment]
Event Store is a database and doesn't rely on any other technology to provide the storage mechanism for example https://github.com/jet/equinox.
This feature request is out of the scope of this project.
