### ISSUE TITLE
[ES 6 Preview] Event type property is missing from RecordedEvent in streams protobuf contract.

### ISSUE THREAD

**Issue by YoEight** [EventStore/EventStore#2175]
Greetings,

It's no longer possible to know an event's type from a `RecordedEvent`.

https://github.com/EventStore/EventStore/blob/master/src/Protos/Grpc/streams.proto#L87-L96

Thanks for your time.

**Comment by jageall** [comment]
I believe it is available through "type" and "isJson" are avalaible from metadata. we need to do some work on documenting it and figuring out how we make a map(string/string) work somewhat better. #2124 is related to this in the other direction

**Comment by YoEight** [comment]
Thanks for the pointer!

**Comment by ahjohannessen** [comment]
@YoEight You can look at how I am mapping types here https://github.com/ahjohannessen/sec/blob/master/core/src/main/scala/sec/api/mapping/streams.scala - Might be helpful :)

**Comment by YoEight** [comment]
Thanks for your insight!
