### ISSUE TITLE
Is there a way like ExpectedVersion.ExistedStream

### ISSUE THREAD

**Issue by SpeedVan** [EventStore/EventStore#2188]
I don't want to auto create stream if not exist while send event. How?

**Comment by gregoryyoung** [comment]
Just to clarify: so you want to say that you expect *something* to already exist EG >= 0

Or in other words ExpectedVersion.Any where version >= 0?

Is this correct?

**Comment by gregoryyoung** [comment]
btw here are existing ones (have explanations) in case its already covered and saves time...

https://github.com/EventStore/EventStore/blob/master/src/EventStore.ClientAPI/ExpectedVersion.cs#L18

**Comment by hayley-jean** [comment]
@SpeedVan Does `ExpectedVersion.StreamExists` included in the link provided by Greg do what you want?

**Comment by SpeedVan** [comment]
@hayley-jean @gregoryyoung  Yes, great. Because of the old version golang sdk, i missed it.

**Comment by pgermishuys** [comment]
@SpeedVan which golang sdk are you referring to out of curiosity?

**Comment by SpeedVan** [comment]
@pgermishuys [https://github.com/jdextraze/go-gesclient](https://github.com/jdextraze/go-gesclient)
