### ISSUE TITLE
New tool for Event Store - Subscription Service

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#2198]
Apologies for posting here, but thought it would be useful to let users here know about this new tool:

https://www.nuget.org/packages/EventStore.SubscriptionService/1.0.0

This is a simple service which allow you to configure persistent subscriptions, along with a designated endpoint to deliver the events to.
We have been using this in Production for a few years and decided to open it up to the world to use.

Here os the url for our repository:

https://github.com/vmeretail/subscriptionservice

**Comment by jen20** [comment]
Thanks @StevenBlair123! I'll close this issue in order to keep the repo focused on development, but would you be interested in writing a guest blog post about the library?

**Comment by StevenBlair123** [comment]
@jen20  - sure thing.
Any particular format / size?
Who should I send it to?
