### ISSUE TITLE
Use native methods for collecting CPU and Memory statistics on Unixes

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#2208]
We need to find a suitable replacement for the `sys.cpu` (System CPU %) cross platform.
Once https://github.com/EventStore/EventStore/pull/2204 is merged, the `sys.cpu` will only be available via Windows as it still uses Performance Counters there.

**Comment by jen20** [comment]
Two statistics need replacing: system CPU usage (useful for support) and system memory usage (also useful for support). Currently system memory usage is implemented by shelling out to a variety of CLI tools and parsing the output, which is not ideal. Furthermore, instantaneous CPU usage percentage is calculated in a variety of different ways and is not really that useful - especially given that many operators will compare it with `top`, find it to be different and assume it to be wrong. 

Consequently I propose we do the following _for Unix_ OSs:

- Replace CPU with 1, 5 and 15 minute load averages (easily obtainable via `libc`)
- Use the native approaches to gather statistics about memory use - reading from and parsing `/proc/meminfo` on Linux, and `host_statistics64` on MacOS.
