### ISSUE TITLE
Rename `EventStoreGrpcClient` to `EventStoreClient`

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#2228]
Since gRPC is the future of client protocols, we should not embed the protocol in the name. It is already in the namespace, and if people need to use both they can use alias imports.

**Comment by bartelink** [comment]
>and if people need to use both they can use alias imports.

people will often need to mix new and old during transitions - I've always hated the shouting API in the namespace - maybe that can segment can be removed? (disclaimer, have not actually looked!)
