### ISSUE TITLE
V8 projection creation timeout test CI only failures

### ISSUE THREAD

**Issue by condron** [EventStore/EventStore#2240]
Test `EventStore.Projections.Core.Tests.Services.v8.when_creating_v8_projection.long_post_processing_times_out`
Is sometimes failing during CI

update: this is only an issue on Ubuntu and it looks like the test was never meant to run with CI as it is attributed with both Category == Manual and Explicit attributes.

Normal success produces output like 
```
Calling a callback in 5000ms
Calling a callback in 5000ms
Calling a callback in 5000ms
Calling a callback in 5000ms
Calling a callback in 5000ms
Calling a callback in 5000ms
1
```

Fails on occasion with the test output

```
1
Calling a callback in 5000ms
Calling a callback in 5000ms
Calling a callback in 5000ms
Calling a callback in 5000ms
Calling a callback in 5000ms
Calling a callback in 5000ms

 
```

This would seem to indicate that under the thread pool load of the CI process the thread pool callback are getting out of order.

The fix is likely to refactor the test to be more deterministic under thread pool load or more resilient to callback sequencing.

**Comment by tambeau** [comment]
This is being closed. V8 has been rendered obsolete in LTS release of ES.
