### ISSUE TITLE
users.proto time encoding

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#2242]
The `last_updated` field below could be a `int64` representing ticks since unix epoch as it is done for `created` metadata field on streams:

```proto
message DetailsResp {
	UserDetails user_details = 1;
	message UserDetails {
		string login_name = 1;
		string full_name = 2;
		repeated string groups = 3;
		string last_updated = 4;
		bool disabled = 5;
	}
}
```

**Comment by ahjohannessen** [comment]
@thefringeninja

**Comment by jen20** [comment]
We should definitely do this one and make time encoding consistent across all service definitions.
