### ISSUE TITLE
Investigate whether we still need `MONO_GC_DEBUG=clear-at-gc`

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#225]
Now that the fix for the segfaulting GC in mono is public, it may be that we no longer need to set `MONO_GC_DEBUG=clear-at-gc` in the `run-node.sh`. Investigate this and remove if possible.

**Comment by jen20** [comment]
It appears we actually do need it.

**Comment by gregoryyoung** [comment]
Possibly not in 4.x? We should bring up some testing on that.

On Mon, Jul 20, 2015 at 6:45 AM, James Nugent <notifications@github.com>
wrote:

> It appears we actually do need it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/225#issuecomment-122760144>
> .
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
The static linking scripts now hack at the mkbundle generated C code to do this by default and fix some others. We should investigate in future whether it's still necessary but the overwhelming answer on Mono 3.12.1 and Ubuntu 14.04 is yes.
