### ISSUE TITLE
Projection out of order (within same stream)

### ISSUE THREAD

**Issue by thomai-d** [EventStore/EventStore#2262]
I'm sorry. This issue can be closed.

For the record:

- Ordering for projections when using `fromAll` is perfectly kept.
- Ordering for projections when using `fromStreams` is not guaranteed.
- If using `fromStreams(event-A, event-B)` by definition the ordering is not guaranteed - even if the origninal events are from the same stream.

**Comment by jen20** [comment]
That's a good summary of the guarantees of projections, @thomai-d. Thanks for updating!

**Comment by mat-mcloughlin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/WLAigtZz/1-test)
