### ISSUE TITLE
[Preview] Unable to load shared library 'runtimes/linux/native/libhoststat.so'

### ISSUE THREAD

**Issue by YoEight** [EventStore/EventStore#2265]
Greetings,

**Describe the bug**
I got this message popping regularly when the server is started:
```
[26391,29,20:56:38.886] Error while collecting stats
EXCEPTION OCCURRED
Unable to load shared library 'runtimes/linux/native/libhoststat.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: runtimes/linux/native/libhoststat.so: cannot open shared object file: No such file or directory
```
Note that `runtimes/linux/native/libhoststat.so` exists.

**To Reproduce**
1. Run EventStore server from the master branch.
2. Start the server as mentioned in the README.md

I can connect to the Web UI however some tabs failed with an exception (`An error occurred`). I don't know how deeply this exception prevents the server from running correctly.

**Expected behavior**
I should be able to start the server without that exception.

**Actual behavior**
I keep having that message every few seconds:
```
[26391,29,20:56:38.886] Error while collecting stats
EXCEPTION OCCURRED
Unable to load shared library 'runtimes/linux/native/libhoststat.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: runtimes/linux/native/libhoststat.so: cannot open shared object file: No such file or directory
```
I can connect to the Web UI however some tabs failed with an exception (`An error occurred`). I don't know how deeply this exception prevents the server from running correctly.

**Config/Logs/Screenshots**
![screen-loaded](https://user-images.githubusercontent.com/144545/73615493-931c2780-4608-11ea-97a6-2ed3ca5c9be7.png)
![web-ui](https://user-images.githubusercontent.com/144545/73615502-adee9c00-4608-11ea-8ac7-7b710b1e80c2.png)

**EventStore details**
 - EventStore server version: EventStore Server from master a535f08ef610a89778e0020be51dfa4991b2cb08

 - Operating system: Ubuntu 19.10

 - EventStore client version (if applicable):

**Additional context**
If I start the server from Jetbrains Rider, **I don't have that behaviour**. I only got that exception if I start the server as mentioned in the README.md.

**Comment by pgermishuys** [comment]
Thanks for reporting this issue @YoEight
