### ISSUE TITLE
Duplicate EventId same stream

### ISSUE THREAD

**Issue by tautvydasversockas** [EventStore/EventStore#2274]
**Describe the bug**

Whenever I send two events with the same eventId (AppendToStreamAsync) to the same stream (event store is local and clean - no other streams) they boh get written. As far as I understand the second one should be ignored. 

**To Reproduce**
1. Download Event Store  and launch on local machine.
2. Save two events to Event Store by calling AppendToStreamAsync.

**Expected behavior**
Second event ignored.

**Actual behavior**
Both events written with the same EventId.

**EventStore details**
 - EventStore server version: 5.0.5

 - Operating system: Windows 10

 - EventStore client version (if applicable): EventStore.Client nuget package 5.0.5

**Comment by bartelink** [comment]
The objective of the functionality is to deduplicate (handle idempotently) _concurrent_ appends - you'll find it does work if you run them on competing writers
(This e.g. allows you to e.g. tag your events with an single incoming requestid)

**Comment by tautvydasversockas** [comment]
@bartelink I found this in Event Store documentation:

"Appends to streams are idempotent based upon the EventId assigned in your post. If you were to re-run the last command it returns the same value again.

This is important behaviour as it's how you implement error handling. If you receive a timeout, broken connection, no answer, etc from your HTTP POST then it's your responsibility to retry the post. You must also keep the same UUID that you assigned to the event in the first POST."

Correct me if I am wrong, but what you are saying is that if I post an event with Id "40fe9e14-7760-4312-ae39-1d5ca67cb28c" to the Event Store and I receive a timeout I would get that event duplicated (now 2 events in Event store with Id "40fe9e14-7760-4312-ae39-1d5ca67cb28c") whenever I try to repost it?

**Comment by bartelink** [comment]
> to the event

should be "to the event(s)"

In other systems, this has been termed a `CommitId`

I am absolutely not saying duplicates will happen - it explicitly deduplicates; the point is that within a single append request, you're allowed to produce multiple events; each one can bear an EventId, and they do not need to be unique within that request

**Comment by tautvydasversockas** [comment]
##@bartelink,

Sorry, I probably did not express myself clearly enough in my issue. I am trying to send two events with multiple requests, like this:

- Save eventId "40fe9e14-7760-4312-ae39-1d5ca67cb28c" to stream A - Success
- Save eventId "40fe9e14-7760-4312-ae39-1d5ca67cb28c" to stream A - Success (should be ignored, right?)

Those are two separate calls, not one call with two events.

I think that's the way Greg Young explained it in the issue #1970

**Comment by tautvydasversockas** [comment]
Appearantly, If I try to add events using Event Store Admin panel (which posts via HTTP) it behaves as expected. For some reason it is not the case with .NET nuget package.

**Comment by hayley-jean** [comment]
Hi @tautvydasversockas Are you seeing both events when you read the stream afterwards?
And are you appending with an expected version?

**Comment by tautvydasversockas** [comment]
@hayley-jean yes, I can see both events. Yes, I am sending with expected version. Expected version is different both times.

**Comment by tautvydasversockas** [comment]
@hayley-jean ,

these are the tests I did: 

- Save eventId "40fe9e14-7760-4312-ae39-1d5ca67cb28c" expected version 4 to stream A - Success
- Save eventId "40fe9e14-7760-4312-ae39-1d5ca67cb28c" expected version 5 to stream A - Success 

Even though the expected version is different - it should not matter, since eventId is the same, which should result in one request ignored, right?

- Save eventId "5bce1e14-7760-4317-ae38-1d5ca67cb28i" expected version Any to stream A - Success
- Save eventId "5bce1e14-7760-4317-ae38-1d5ca67cb28i" expected version Any to stream A - Ignored (idempotent)

**Comment by hayley-jean** [comment]
What use case are you testing or running into?
Idempotent writes are meant to be used to ensure retries of writes don't result in the same event written twice.

We do not guarantee that you can't write an event with the same ID twice if you are using different expected versions, or writing the same event far apart.

If you write an event and the client responds with a timeout, it's possible that the write actually succeeded, but it timed out getting back to the client.
In this case, you would retry the exact same request with the same ID and expected version.
If the write had succeeded originally, you will get an idempotent write.

However, if you try to write an event and it fails due to a Wrong Expected Version, there should be no chance that the write succeeded.
This means that you can retry the write with the same ID and an updated expected version, and should still only see one write as the first attempt actually failed.

**Comment by tautvydasversockas** [comment]
@hayley-jean let me try to explain what I want to achieve. I have an application that uses Event Store for persisting my aggregates (in a form of events). Whenever my application receives a request it restores my aggregate (from persisted events), updates it (which results in additional events) and store the updated version (new events) to the Event Store. Now supposedly a client calls my application with a request to update my aggregate via HTTP. For some reason the request gets executed (persisted in the Event Store) but the client receives unsuccessful HTTP result or timeout. The client is not sure whether the request was executed or not. The client retries the request (my application restores my aggregate and so on) and it succeeds. 

Now upon the receival of the second request my aggregate had a new version (since it was updated by the first request which result was successfully persisted in a form of events) therefore the expected aggregate version was different yet the request Id was the same. I can use the request Id to deterministically gerenrate resulting event Ids. If these Ids are ensured to be unique I can be safe that my application is not going to store them twice (not execute my request twice). 

As far as I can tell from your responses, this is not supported out of the box by Event Store, correct?

**Comment by dt665m** [comment]
> @hayley-jean let me try to explain what I want to achieve. I have an application that uses Event Store for persisting my aggregates (in a form of events). Whenever my application receives a request it restores my aggregate (from persisted events), updates it (which results in additional events) and store the updated version (new events) to the Event Store. Now supposedly a client calls my application with a request to update my aggregate via HTTP. For some reason the request gets executed (persisted in the Event Store) but the client receives unsuccessful HTTP result or timeout. The client is not sure whether the request was executed or not. The client retries the request (my application restores my aggregate and so on) and it succeeds.
> 
> Now upon the receival of the second request my aggregate had a new version (since it was updated by the first request which result was successfully persisted in a form of events) therefore the expected aggregate version was different yet the request Id was the same. I can use the request Id to deterministically gerenrate resulting event Ids. If these Ids are ensured to be unique I can be safe that my application is not going to store them twice (not execute my request twice).
> 
> As far as I can tell from your responses, this is not supported out of the box by Event Store, correct?

If you must have this behavior, you could also attach the expected aggregate/event version in the http request along with the deterministic id no?

**Comment by tautvydasversockas** [comment]
@dt665m  , you are right - I could. Yet that would force me to always know the latest state (aggregate version) which sometimes could be not the most optimal solution. As far as I understand, Event Store doesn't support functionality similar to unique Ids (which you could benefit from if you were using MSSQL, etc.) therefore I ended up attaching "causation" Ids to my events. If any of the aggregate events have a "causation" Id which is the same as the received command Id I know that is most likely a duplicate command. You could argue whether that's what you should use a causation Id for yet in this case the naming "causation" illustrates the solution clearly. Maybe there are some brighter solutions but this seems to work just fine.

**Comment by alexeyzimarev** [comment]
> Event Store doesn't support functionality similar to unique Ids (which you could benefit from if you were using MSSQL, etc.)

It does but on the stream name + stream revision level. That pair is unique.
