### ISSUE TITLE
EventStore ClientAPI Subscription issue

### ISSUE THREAD

**Issue by VibinKesavan** [EventStore/EventStore#2307]
I don't know what i am doing wrong here while creating a subscription in my projection manager. Initially, I logged the issue stackoverflow, so I thought of copying the link here. Could you please help ?

[https://stackoverflow.com/questions/60357269/eventstore-clientapi-subscription-issue](https://stackoverflow.com/questions/60357269/eventstore-clientapi-subscription-issue).

If you require the eventstore logs , please let me know. and I am pretty sure I am doing someting stupid here, very unlikely a bug.

**Comment by gregoryyoung** [comment]
I do not believe this is a bug and it should not be labeled as such or else literally anyone building a read model would be unable to :-D

Run a test for me? Run your subscription from the beginning (default argument) and print out all events. My guess is you will see them all

**Comment by gregoryyoung** [comment]
btw I don't mean to come off as dismissive on this but can see how it might be read that way, if you want add me gregoryyoung1@gmail.com and we can chat though it.

**Comment by VibinKesavan** [comment]
Hi @gregoryyoung thanks for your quick response, and it's been just a few weeks I started writing my first app with event-sourcing using eventstore. I have added you to the repo, if you can just have a quick look on that, especially in the projection manager.

**Comment by VibinKesavan** [comment]
Sorry, it's started working. I was receiving those events and get unhandled. sorry for the confusion. anyway it's a great tool. liked it and appreciate your help @gregoryyoung

**Comment by gregoryyoung** [comment]
What is the link? Am back to this and cant seem to find it
