### ISSUE TITLE
Document canonical usage patterns of subscriptions

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#231]
Document the canonical usage patterns for regular and catch-up subscriptions in the .NET client API and how they interact with the connection options in terms of reconnecting etc.

**Comment by pgermishuys** [comment]
There is some documentation around this.
http://docs.geteventstore.com/introduction/subscriptions/
http://docs.geteventstore.com/introduction/competing-consumers/
http://docs.geteventstore.com/dotnet-api/3.6.0/competing-consumers/
http://docs.geteventstore.com/http-api/3.6.0/competing-consumers/
and the samples for each
https://github.com/EventStore/EventStore.Samples.Dotnet
We could do some work around reorganising the documentation which is currently underway.
