### ISSUE TITLE
Question on using EventStore v6 preview under docker

### ISSUE THREAD

**Issue by StuartFergusonVme** [EventStore/EventStore#2311]
I am attempting to use the EventStore v6 Preview 1 docker image (6.0.0-preview1-buster-slim) as part of our integration testing.

The image is run under docker with port 2113 being mapped for all the HTTP traffic.

Previous to v6 this setup has been working successfully however since attempting to using v6 I am now getting SSL Connection Errors when doing a GET on the ping route (https://127.0.0.1:2113/ping).  I have also tried to access the UI via a web browser with no joy either (The site cannot be reached).

I have set the container to run Event Store in dev mode with the --dev flag.

Is there anything I am missing in my setup to allow me to talk to the ES container from outside docker over HTTPS?

Any help on this would be much appreciated.

Stuart

**Comment by StuartFergusonVme** [comment]
Some additional information for above:

Tried running the ES v6 image under docker using production mode and the same issue was observed.  I am also unable to access the User Interface under either development or production mode.

**Comment by StevenBlair123** [comment]
Anyone help on this?
We can't quite work out if it's pilot error, or somethign up the with image.

**Comment by mat-mcloughlin** [comment]
Are you using `-e EVENTSTORE_DEV=true` to run EventStore in dev mode?

**Comment by StuartFergusonVme** [comment]
Thanks for the reply @mat-mcloughlin.

I was appending --dev onto the docker command which seemed to be setting the devmode flag successfully as got the dev mode warning in the docker console.

Just changed it to using the environment variable and I can now access the UI on localhost:2113.

Thanks for your help.

A quick question though, when will the docker image on docker hub be updated again to either preview 2 or preview 3?

**Comment by mat-mcloughlin** [comment]
We didn't push preview 2 to docker hub but you can get it here https://github.com/EventStore/EventStore/packages/68255

We should be releasing preview 3 soon

**Comment by StuartFergusonVme** [comment]
Do I just log in with my github credentials to be able to pull this image ?

**Comment by mat-mcloughlin** [comment]
yep 

`docker login docker.pkg.github.com --username <xxxx>`

**Comment by jen20** [comment]
Note that the XXX should be a PAT with appropriate scopes rather than your password, and that it should be entered interactively when prompted rather than as part of the command line.
