### ISSUE TITLE
EventStore 5.0.6 stops accepting connections after some time [Potential bug]

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2318]
The issue was originally reported here by Zvjezdan Tomičević:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/event-store/a1e0qAAg3vc/uawiRYYnGgAJ

Quoting from the google groups link:
```
Hi. We have updated our staging server from 5.0.5 to 5.0.6, and have started to experience strange behavior.
After a while, server rejects all new connections from .NET client. All write or read attempts end up in ConnectionClosed exception.
Restarting the apps does not help.
Normal operation resumes only after we restart server instance.

We are running on bare metal, WIN 2016 server, 250GBSSD, 64GB RAM.
Any pointers as to what can saturate and block server in this way? Our code has not changed, and it worked until last update.
BR
```

**To Reproduce**
No reproduction steps yet.

**Expected behavior**
Server should be able to accept new connections from clients.

**Actual behavior**
After some time, it appears that the server no longer accepts  connections from clients. Restarting the clients does not make any difference, so the issue must be server-side.

**EventStore details**
 - EventStore server version: 5.0.6

 - Operating system: Windows

**Additional context**
This could be a regression due to the multiple TCP connection/socket fixes applied in 5.0.6.
https://eventstore.com/blog/event-store-5.0.6-release/

**Comment by SMMMN** [comment]
I have the same problem when I use the EventStore in version 5.0.6

**Comment by shaan1337** [comment]
@SMMMN hello, thank you for the report.
can you please let us know if you're running the server on linux or windows? (and which version specifically)

**Comment by shaan1337** [comment]
@SMMMN if you can send us your server log files as well, it would be great! you can attach them to this github issue. thank you

**Comment by SMMMN** [comment]
I am using the latest docker version of [Docker Hub](https://hub.docker.com/layers/eventstore/eventstore/latest/images/sha256-54e42f001c8880cfb54356a10c062f4f181e905cc7bcb82199789f7b74058361?context=explore)

here's my log: [logs.zip](https://github.com/EventStore/EventStore/files/4307643/logs.zip)

**Comment by zeko77** [comment]
Hi. It happened again today. I had to restart whole instance. Here are logs.
[2020-03-09.zip](https://github.com/EventStore/EventStore/files/4311023/2020-03-09.zip)

**Comment by shaan1337** [comment]
@SMMMN @zeko77 thanks very much for the logs, we've been able to reproduce the issue after going through them. It occurs when there's a TCP framing error, for example if you do an HTTP request on the TCP port:
`curl http://localhost:1113/`
