### ISSUE TITLE
Review .proto 

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#232]
Should favour using optionals instead of required
Should write some docs so other people know the scheme

**Comment by graste** [comment]
Please notice this from the proto3 release notes:

> We recommend that new Protocol Buffers users use proto3. However, we do not generally recommend that existing users migrate from proto2 from proto3 due to API incompatibility, and we will continue to support proto2 for a long time.

and a significant change in proto3:

> Explicit "optional" keyword are disallowed in proto3 syntax, as fields are optional by default; required fields are no longer supported.

**Comment by gregoryyoung** [comment]
@pgermishuys if we do this we might as well do the int32->int64 version change as this I believe will require upgrades to all clients.

**Comment by jen20** [comment]
It might be worth considering a switch to custom msgpack serialisation vs
protobuf if there are going to be breaking changes anyway.

>

-- 
James

**Comment by ChrisChinchilla** [comment]
@jen20 and @gregoryyoung Is this still needed?
