### ISSUE TITLE
Keep only one internal and external TCP endpoint and a flag to denote if it's secure or not

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2329]
PR #2267 removes the ability to launch a node from a command-line with both a secure/non-secure internal or external TCP endpoint. In tests, it's still possible to launch it with both secure/non-secure TCP endpoints on.

Based on the value of `DisableInternalTls` or `DisableExternalTls`, the values of `InternalTcpEndpoint`, `InternalSecureTcpEndpoint`, `ExternalTcpEndpoint` and `ExternalSecureTcpEndpoint` may now be null throughout the code and this increases the risk of null reference exceptions.

As suggested by @hayley-jean here: https://github.com/EventStore/EventStore/pull/2267#pullrequestreview-367048085 we can keep only one endpoint and a boolean.

`ExternalTcp` endpoint can still be null, but not `InternalTcp`. This will greatly reduce the risk for null reference exceptions.

**Comment by tambeau** [comment]
Has this been resolved in testing ... if anything it should be tagged as a negative test.

**Comment by hayley-jean** [comment]
@tambeau This is a code change that still needs to be done in the core database.
