### ISSUE TITLE
Further Problems in using ES v6 under Docker

### ISSUE THREAD

**Issue by StuartFergusonVme** [EventStore/EventStore#2344]
Following on from issue number #2311 I still have an outstanding question.

In the testing we do we spin up multiple concurrent event stores and therefore allow docker to control the port mappings.

From this I have discovered that if the port mapping is 2113 -> 2113 all the HTTP operations work fine from the host PC (like the UI), however if the port mapping is auto assigned (xxxxx -> 2113) then the HTTP operations fail on the host PC.

My guess is this is to do with the HTTP operations all being over SSL now but cant work out what the issue is.

@mat-mcloughlin are you able to provide anymore help on this for me?

**Comment by avish0694** [comment]
@StuartFergusonVme  Can you please confirm if skipping the SSL verification when doing HTTPS operations works?

**Comment by StuartFergusonVme** [comment]
I ended up using the later version of the ES 6 preview from Docker Hub when it became available and this was resolved.
