### ISSUE TITLE
Resolving LinkTos for Multi-Stream projection does not work.

### ISSUE THREAD

**Issue by swilgosz** [EventStore/EventStore#2371]
**Describe the bug**

I cannot resolve linkTos for projection built from multiple streams event when passed the `"ES-ResolveLinkTos: true"` header.

**To Reproduce**

1. Enable Projection "By Type"
2. Create Projection: "default-DummyHandler" with the code snippet below:

```javascript
fromStreams(["$et-Foo", "$et-Bar"])
```

3. Create subscription for: $projections-default-DummyHandler-order
![image](https://user-images.githubusercontent.com/8088317/76902590-a45d8280-689c-11ea-9bb2-600c9831eca2.png)

4. Publish Events with types: `Foo` and `Bar`.
5. Try to consume feed from the projection, or read events

**Expected behavior**

I expect that events returned will have EventType set to `Foo` and `Bar`, when `ResolveLinkTos` header is passed. Also I expect that the links will be resolved and Data of those events will be returned

**Actual behavior**

I get unresolved list of events: 

```
{
  "title": "Event stream '$projections-default-DummyHandler-order'",
  "id": "http://127.0.0.1:2113/streams/%24projections-default-DummyHandler-order",
  "updated": "2020-03-12T22:56:46.213643Z",
  "streamId": "$projections-default-DummyHandler-order",
  "author": {
    "name": "EventStore"
  },
  "headOfStream": true,
  "selfUrl": "http://127.0.0.1:2113/streams/%24projections-default-DummyHandler-order",
  "eTag": "43;-1955838367",
  "links": [
    {
      "uri": "http://127.0.0.1:2113/streams/%24projections-default-DummyHandler-order",
      "relation": "self"
    },
    {
      "uri": "http://127.0.0.1:2113/streams/%24projections-default-DummyHandler-order/head/backward/20",
      "relation": "first"
    },
    {
      "uri": "http://127.0.0.1:2113/streams/%24projections-default-DummyHandler-order/0/forward/20",
      "relation": "last"
    },
    {
      "uri": "http://127.0.0.1:2113/streams/%24projections-default-DummyHandler-order/23/backward/20",
      "relation": "next"
    },
    {
      "uri": "http://127.0.0.1:2113/streams/%24projections-default-DummyHandler-order/44/forward/20",
      "relation": "previous"
    },
    {
      "uri": "http://127.0.0.1:2113/streams/%24projections-default-DummyHandler-order/metadata",
      "relation": "metadata"
    }
  ],
  "entries": [
    ...
    {
      "title": "12@$et-Foo",
      "id": "http://127.0.0.1:2113/streams/%24et-Foo/12",
      "updated": "2020-03-12T22:54:56.039763Z",
      "author": {
        "name": "EventStore"
      },
      "summary": "$>",
      "links": [
        {
          "uri": "http://127.0.0.1:2113/streams/%24et-Foo/12",
          "relation": "edit"
        },
        {
          "uri": "http://127.0.0.1:2113/streams/%24et-Foo/12",
          "relation": "alternate"
        }
      ]
    }
  ]
}% 

```

**Config/Logs/Screenshots**

I work with Default installation of Event store:

- Version: Event Store 5.0.6.0 
- Docker Image
- All Projections enabled

**EventStore details**
 - EventStore server version:  5.0.6.0 

 - Operating system: Docker Image

 - EventStore client version (if applicable): 5.0.6.0

**Additional context**

**My goal:** 

My subscribers needs to listen to multiple types of events. When I'll just listen to multiple `byType` projections, I am able to resolve links without problems, BUT I get events in the wrong order.

To solve it, I need to have a projection that merges multiple `byType` streams into one and ensures the correct order.

**Comment by hayley-jean** [comment]
The `$projections-default-DummyHandler-order` stream is internal to projections and shouldn't be relied on for any development.

In order to create a projection to join the two streams you should create something that links events to another stream, such as:

```
fromStreams("$et-foo", "$et-bar")
.when({
    $any:function(s,e) {
        linkTo("otherstream", e)
    }
})
```

In this case your persistent subscription would subscribe to the `otherstream` stream.

You will also need to request the events with `embed=TryHarder`, so:

```
curl -i https://localhost:2113/subscriptions/{streamName}/{groupName}/?embed=tryharder -u admin:changeit -H "accept:application/vnd.eventstore.competingatom+json" -k
```

**Comment by swilgosz** [comment]
Everything works, thank you @hayley-jean fro your support!
