### ISSUE TITLE
Catchup subscription list on UI

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#2381]
**Is your feature request related to a problem? Please describe.**
If we run Catchup subscriptions, we currently have to check log files for  a status no whether they are still connected / LiveProcessing etc

**Describe the solution you'd like**
The UI to have a screen similar to persistent subscriptions which show catchup subscriptions (name), along with number of events until caught up / live status.

**Describe alternatives you've considered**
Continue monitoring our log files.

**Additional context**
Nothing at this time.

**Comment by gregoryyoung** [comment]
So the reason these aren't **in** eventstore is that they live on the outside and would generally be hooked into whatever monitoring you are using.

There are metrics that can be consumed by other tools etc for a catchupsubscription. This should be able to be tied into whatever you happen to be using relatively easily.

What if I provided you today a little piece of code that lifted metrics out to say WMI would that meet your needs?

**Comment by StevenBlair123** [comment]
Sounds good to me.

**Comment by alexeyzimarev** [comment]
We'll add an API for that in the next LTS version, and then it should be available in Navigator.
