### ISSUE TITLE
ES 6: provide default serilog configuration in .json instead of hardcoding in the code

### ISSUE THREAD

**Issue by slav** [EventStore/EventStore#2400]
**Is your feature request related to a problem? Please describe.**
I'd like to change the logger configuration in ES 6 preview. However, default configuration is hardcoded in the code, including filtering and so on, which makes it a bit more complex to just do small changes to the configuration.

**Describe the solution you'd like**
Move default configuration from the code into json file, allowing anyone update existing configuration instead of having to write the whole configuration from scratch.

**Comment by mat-mcloughlin** [comment]
Hey @slav moving default configuration from code to a json file proved to be incredibly complex. Rather than use a lot of time on making the logging more easily configurable we have parked this issue for now.

**Comment by slav** [comment]
Gotcha. Ok, thank you.
