### ISSUE TITLE
Improve the reporting of persistent subscription status when the checkpoint is > 1

### ISSUE THREAD

**Issue by umut-ulutas-v** [EventStore/EventStore#2411]
**Describe the bug**
I use C# client and use Persistent Subscriptions to subscribe to streams and manually acknowledge events. `autoAck` is set to false, events are manually read on EventAppeared method and get acknowledged.

On Dashboard/Persistent Subscriptions tab, number of messages dont decrease after sending manual Acknowledgement to an event by calling `eventStorePersistentSubscriptionBase.Acknowledge(my_event)` in EventAppeared method.

**To Reproduce**
1. Have a stream with events.
2. Projections should be enabled.
2. Subscribe to event type projection ($et-) by Persistent Subscription, that includes your events.
4. Read the event on client `EventAppeared` method.
5. Send manual Acknowledgement to that resolved event.

**Expected behavior**
On Dashboard/Persistent Subscriptions tab, number of messages of stream/group(s) going down as processing and manually acknowledging the events.

**Actual behavior**
Number of messages stays same on the Dashboard/Persistent Subscriptions. 

After manually acknowledging the event, it actually appears to be resolved as it doesnt reappear in `EventAppeared` function again later, however in Dashboard number of messages of that stream/group(s) never go down. Different consumer strategies also didnt help.

Also after sending manual acknowledment, in the Dashboard for a flicker of a second `_In Flight_` number increases and the indicator turns green, after a short while `_In Flight_` number becomes zero and the indicator turn red again, and stays that way.

**Config/Logs/Screenshots**
This is after those two events are read and manually acknowledged in `EventAppeared` function. 
![resim](https://user-images.githubusercontent.com/63104926/78360727-e5a1a200-75bf-11ea-8292-a7dd37d1b24f.png)

**EventStore details**
 - EventStore server version: 5.0.8.0

 - Operating system: Windows 10 64 bit

 - EventStore client version (if applicable): 5.0.5

**Additional context**
Thank you for taking the time of reading this.

**Comment by Archanian** [comment]
I don't think this is a bug, its related to the way subscription checkpoints are written. It will only update this number every time a checkpoint is recorded, to test this you can change the minimum checkpoint count to 1, and see if your problem persists.

Via the UI: Edit setting > "Min CheckPoint Count"
Via the C# API: `PersistentSettingsSubscriptionBuilder.MinimumCheckpointCountOf(1)`
