### ISSUE TITLE
A projection error on v5.0.7

### ISSUE THREAD

**Issue by zhuzhenguang** [EventStore/EventStore#2414]
**Describe the bug**
System.FormatException When a projection stream link a another linked stream and the another linked stream link some original streams which have expire events by set MaxAge.

**To Reproduce**
1. We have some some stream(MyStream-1, MyStream-2, MyStream-3...) and $by_category projection will link them to $ce-MyStream. This is Eventstore normal behavior.
2. Set MaxAge for MyStream-1, MyStream-2, MyStream-3...
3. Waiting for expiring...
3. Create a new custom projection named $CustomStream which watch $ce-MyStream and link all events from $ce-MyStream to $CustomStream and start the new projection.
4. Many exceptions will throw:
_[PID:14952:024 2020.04.06 12:44:00.572 ERROR StorageReaderWorker ] Error while resolving link for event record: EventNumber: 2249, LogPosition: 101459708, CorrelationId: 8c237053-2409-40bd-a917-513609856ffb, EventId: bc13ef4a-c318-489d-953c-c6d65231933b, TransactionPosition: 101414552, TransactionOffset: 194, EventStreamId: $CustomStream, ExpectedVersion: 2248, TimeStamp: 2020/4/6 12:39:17 PM, Flags: Data, IsCommitted, EventType: $>
EXCEPTION OCCURRED
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at EventStore.Core.Services.Storage.StorageReaderWorker.ResolveLinkToEvent(EventRecord eventRecord, IPrincipal user, Nullable`1 commitPosition) in C:\Sources\EventStore\src\EventStore.Core\Services\Storage\StorageReaderWorker.cs:line 471_
......

**Expected behavior**
$CustomStream should skip all expired events and no exception

**Actual behavior**
I guess $CustomStream will read the linked events from $ce-MyStream, but the linked events not  exist.

**EventStore details**
 - EventStore server version: 5.0.7

 - Operating system: Windows Server 2012

**Additional context**
I know a new configuration item named **--fault-out-of-order-projections**. I have tested it. But it will working well when a projection stream watch some original streams and not working for a projection stream watch another projection stream. And all of the projections use **LinkTo** function

**Comment by hayley-jean** [comment]
Thank you for reporting this issue.

We're still looking into the cause, but have identified a workaround for the moment.
You can prevent the error by checking if the event data is null before linking the event.

As an example, a projection that links from the `$ce-MyStream` stream would look like this:

```
fromStream("$ce-MyStream")
.when({
    $any: function(s,e) {
        if (e.data) {
            linkTo("CustomStream", e);
        }
    }
})
```
