### ISSUE TITLE
Due time too large error in logs

### ISSUE THREAD

**Issue by AndreSteenbergen** [EventStore/EventStore#2431]
**Describe the bug**

I have the following error in my logs

{ "PID": "86064", "ThreadID": "16", "Date": "2020-04-10T11:36:22.704371Z", "Level": "Error", "Logger": "QueuedHandlerThreadPool", "Message": "Error while processing message {message} in queued handler '{queue}'.", "Exception": {"Message":"Due time too large\nParameter name: dueTime", "ParamName":"dueTime", "Data":{}, "TargetSite":"Boolean Change(Int64, Int64, Boolean)", "StackTrace":"  at System.Threading.Timer.Change (System.Int64 dueTime, System.Int64 period, System.Boolean first) [0x00006] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0 \n  at System.Threading.Timer.Change (System.Int64 dueTime, System.Int64 period) [0x00000] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0 \n  at (wrapper remoting-invoke-with-check) System.Threading.Timer.Change(long,long)\n  at EventStore.Core.Services.Monitoring.MonitoringService.Handle (EventStore.Core.Messages.SystemMessage+SystemInit message) [0x0001c] in <ffdaa9c02a2240379a159e9f8153c003>:0 \n  at EventStore.Core.Bus.MessageHandler`1[T].TryHandle (EventStore.Core.Messaging.Message message) [0x00014] in <ffdaa9c02a2240379a159e9f8153c003>:0 \n  at EventStore.Core.Bus.InMemoryBus.Publish (EventStore.Core.Messaging.Message message) [0x00100] in <ffdaa9c02a2240379a159e9f8153c003>:0 \n  at EventStore.Core.Bus.InMemoryBus.Handle (EventStore.Core.Messaging.Message message) [0x00000] in <ffdaa9c02a2240379a159e9f8153c003>:0 \n  at EventStore.Core.Bus.QueuedHandlerThreadPool.ReadFromQueue (System.Object o) [0x0006c] in <ffdaa9c02a2240379a159e9f8153c003>:0 ", "Source":"mscorlib", "HResult":-2146233086}, "EventProperties": { "message": "EventStore.Core.Messages.SystemMessage+SystemInit", "queue": "MonitoringQueue" } }

 - Operating system:
Ubuntu Xenial

 - EventStore client version (if applicable):
5.08

**Comment by jageall** [comment]
Could you confirm what the statistics gathering interval has been set to? it should be in the log files on startup

**Comment by AndreSteenbergen** [comment]
Ah  STATS PERIOD SEC: 9999999 is too large I guess ...

**Comment by AndreSteenbergen** [comment]
This issue can be closed, as user error I guess.
