### ISSUE TITLE
How implement exactly once processing like for example in kafka? Stream API in EventStore

### ISSUE THREAD

**Issue by ura3462246** [EventStore/EventStore#2433]
What is the best way to implements exactly one processing with just EventStore and some stream function?
My guess is this: use catch-up subscription and send message like EventNumberChanged in one "transaction" with others messages.
Please advise how to solve this problem in EventStore

**Comment by alexeyzimarev** [comment]
Duplicate https://github.com/EventStore/documentation/issues/431
