### ISSUE TITLE
Add average waiting time on queues

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2438]
The current `avgProcessingTime` metric on queues also includes the time spent waiting on the queue: https://github.com/EventStore/EventStore/blob/master/src/EventStore.Core/Bus/QueueStatsCollector.cs#L146

It would be great to add an `averageWaitingTime` metric to help distinguish between the actual work done and the amount of time spent waiting on the queue.

The metrics could then be defined as follows:
```
WaitTime - time spent waiting on the queue before being processed
ProcessTime - time spent doing the actual work
TotalTime - WaitTime + ProcessTime
```

For example, this can help to know if I/O saturation is occurring or if there are not enough threads to do the work:
- If we see a high `ProcessTime` on storage reader threads, it is an indication of I/O saturation since the disk is taking time to send us back a reply.
- If we see a high `WaitTime` but low `ProcessTime`, it is an indication that there are not enough threads to process the items.

**Comment by alexeyzimarev** [comment]
I believe it's available in metrics: https://developers.eventstore.com/server/v24.2/metrics.html#queues

Metrics | Type | Desc
-- | -- | --
`eventstore_queue_queueing_duration_max_seconds{name=<QUEUE_GROUP>,range=<RANGE>}` | `RecentMax` | Recent maximum time in seconds for which any item was queued in queues belonging to the QUEUE_GROUP. This is essentially the length of the longest queue in the group in seconds
