### ISSUE TITLE
Expired reads of projection definition streams are not retried

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore#2469]
There is no mechanism to retry reads of a projection's definition stream (e.g. `$projections-$streams`)

The projection does not fail when this read times out, but will rather not run and will not be shown in the UI.
It will still be present in the response from the `/projections/any` endpoint with all default values, for example:

```
{
  "coreProcessingTime": 0,
  "version": -1,
  "epoch": -1,
  "effectiveName": "$streams",
  "writesInProgress": 0,
  "readsInProgress": 0,
  "partitionsCached": 0,
  "status": "Loading",
  "name": "$streams",
  "mode": "Transient",
  "position": "",
  "progress": 0.0,
  "eventsProcessedAfterRestart": 0,
  "statusUrl": "https://localhost:2113/projection/$streams",
  "stateUrl": "https://localhost:2113/projection/$streams/state",
  "resultUrl": "https://localhost:2113/projection/$streams/result",
  "queryUrl": "https://localhost:2113/projection/$streams/query%3Fconfig=yes",
  "enableCommandUrl": "https://localhost:2113/projection/$streams/command/enable",
  "disableCommandUrl": "https://localhost:2113/projection/$streams/command/disable",
  "bufferedEvents": 0,
  "writePendingEventsBeforeCheckpoint": 0,
  "writePendingEventsAfterCheckpoint": 0
},
```

**To Reproduce**

Force a read of a definition stream (e.g. `$projections-$streams`) to time out.
This can be done either with the debugger, or adding a check in the StorageWriterService that returns immediately when trying to read the stream backwards.

**Expected behavior**

The expired read is retried, and the projection eventually recovers.

**Actual behavior**

The projection remains in a default state and does not run.

**EventStore details**

 - EventStore server version: <= v6.0.0-preview3
 - Operating system: Any

**Comment by timothycoleman** [comment]
This is fixed in 23.10.4 and 24.10.0
