### ISSUE TITLE
Cannot delete Stream

### ISSUE THREAD

**Issue by gmiejski** [EventStore/EventStore#2472]
**Describe the bug**

Cannot delete a stream using a web UI.

**To Reproduce**
1. create a new stream by creating new Event from UI (works both with stream created via UI and through Java library)
2. go to `StreamBrowser` -> select newly created stream -> click `Delete` -> confirm

**Expected behavior**
Stream is deleted

**Actual behavior**
Nothing happens, no error showed. Error displayed in JS console:

**Config/Logs/Screenshots**
![Screenshot 2020-05-08 at 15 47 24](https://user-images.githubusercontent.com/3779045/81411852-3d917280-9143-11ea-9d3a-3dd874284369.png)

No logs on server logs. 

**EventStore details**
 - EventStore server version: Event Store 5.0.8.0

 - Operating system: MacOS

**Comment by StevenBlair123** [comment]
Did you clear the browser cache?
Assuming the stream is only visible on the UI and not via  GET
