### ISSUE TITLE
.partitionBy function does not catch elements form event metadata

### ISSUE THREAD

**Issue by soloveichik** [EventStore/EventStore#248]
when creating a projection that reads a category and tries to partition by some metadata - it doesn't work. It fails when tries to read an element form metadata in partitionBy function.

There is a workaround - by moving that element from metadata to the body. In this case partitionBy works just fine.
 fromCategory('my_category')
    .partitionBy(function (e) { return e.metadata.fileId; }) // debugger shows that javascript fails here
    .when({ ... });

This works: .partitionBy(function (e) { return e.data.fileId; })

Latest version of event store is used: EventStore-OSS-Win-v3.0.0

**Comment by pgermishuys** [comment]
From https://github.com/EventStore/EventStore/issues/845, the partitionBy function had an argument mismatch. This issue has now been resolved.
