### ISSUE TITLE
EventStore.Client.Embedded Package Reports No Dependencies

### ISSUE THREAD

**Issue by thefringeninja** [EventStore/EventStore#2494]
![missing-deps](https://user-images.githubusercontent.com/495495/82042798-cc097500-96aa-11ea-9f3f-7e057a9b39a5.png)

**Comment by jageall** [comment]
is this missing things like hdrhistogram still?

**Comment by thefringeninja** [comment]
Yes. It is including the es libs but none of their dependencies!
