### ISSUE TITLE
ConnectionSettings.UseCustomHttpClient has no effect in EventStore client 5.0.8

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2497]
The http client is not being passed as parameter to the ClusterDnsEndpointDiscoverer here:
https://github.com/EventStore/EventStore/blob/v5-master/src/EventStore.ClientAPI/EventStoreConnection.cs#L212

This change was made to be able to connect to a v6 server with gossip seeds.
Related PRs:
https://github.com/EventStore/EventStore/pull/2388
https://github.com/EventStore/EventStore/pull/1959

**Comment by pgermishuys** [comment]
Fixed by https://github.com/EventStore/EventStore/pull/2553 and https://github.com/EventStore/EventStore/pull/2487
