### ISSUE TITLE
Event Store v6 Preview 3 AtomPub not working

### ISSUE THREAD

**Issue by prolic** [EventStore/EventStore#2499]
I'm starting the server like this (using Ubuntu 18.04 tarball):

```
./run-node.sh --run-projections=all --mem-db --dev --enable-external-tcp --enable-atom-pub-over-http
```

However `localhost:2113` is not available in the browser. Running the test-suite for [event-store-client](https://github.com/prooph/event-store-client/) also fails with tons of tests, so far I think mostly related to AtomPub not available.

**Some of the error messages I see:**
```
Receiving the response headers for 'http://localhost:2113/subscriptions/4153ad883547d448b0a04d2a4ebae063/existing/info' failed, because the socket to 'localhost:2113' @ '127.0.0.1:2113' closed early with 0 bytes received within 0 milliseconds
```

```
Receiving the response headers for 'http://localhost:2113/users/' failed, because the socket to 'localhost:2113' @ '127.0.0.1:2113' closed early with 0 bytes received within 0 milliseconds
```

**Comment by YoEight** [comment]
Hi @prolic,

Please use ‘https’ instead.

**Comment by prolic** [comment]
stupid me, of course, thanks.
