### ISSUE TITLE
Projection does not start processing events

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#2507]
**Describe the bug**
Truncate a stream (but leave some events after $tb), then start a projection on this stream.
Position remains at -1 and no events processed.

The metadata for stream is (we have 32305553 events on the stream):

```
{
  "$tb": 32300000
}
```

**To reproduce**

1. add some events to two streams
2. Start a projection listening to the streams
3. Truncate one of the streams (via tcp or http)
4. Reset projection

```
fromStreams('$ce-Stream1','$ce-Stream2') //fromStream * fromCategory refuse to work as well
.when({
    $init: (s,e) =>{
        return {count :0};
    },
    $any: (s, e) => {
        s.count++;
    }
});
```
**Expected behavior**
I would expected the events to start being processed from $tb value

**Actual behavior**
Position remains at -1

**Config/Logs/Screenshots**
If applicable, please attach your node configuration, logs or any screenshots.

**EventStore details**
 - EventStore server version: 4.1.1, 5.0.2 & 5.0.8

 - Operating system: Windows and Linux Ubuntu

 - EventStore client version (if applicable): 20.6.0-rc

**Additional context**

I have a small console application which can be run to replicate the issue:

https://github.com/StevenBlair123/eventstore-projections

**Comment by StevenBlair123** [comment]
I have replicated this on different streams.
Ran the query counting up two streams.
Truncated one stream (via postman):

[
  {
    "eventId": "00000000-0000-0000-0000-000000000005",
    "eventType": "help",
    "data": { "$tb": 10000 }
  }
]

Re-ran query, no events

Brought the events back (I haven't scavenged)

[
  {
    "eventId": "00000000-0000-0000-0000-000000000006",
    "eventType": "help",
    "data": { "$tb": }
  }
]

Re-ran the query, and events appear from both streams again.

**Comment by StevenBlair123** [comment]
Tried another experiment.
This time I created a new stream from the UI, added some events, then truncated a few.
Query works ok from this scenario.

**Comment by StevenBlair123** [comment]
Not sure if anyone has had a look at this yet, but we have been working on writing some code to replicate this issue. Just waiting on a colleague to verify the findings.

**Comment by StevenBlair123** [comment]
Anyone had a chance to look at this?
We have projections that refuse to start now, and not a lot we can do.
Just now we are looking at a total rebuild of the system unless we can figure out a workaround.

**Comment by Lougarou** [comment]
Hi Steven, can you let us know what the checkpoint is on that projection? you can find it in this stream $projections-projectionName-checkpoint. The issue should be resolved once you move the checkpoint ahead of the truncation point...

**Comment by StevenBlair123** [comment]
Thanks for the reply.

![image](https://user-images.githubusercontent.com/13871941/83062110-07665500-a056-11ea-81e2-fb7e9f3080e1.png)

We had previously truncated at 32300000

**Comment by StevenBlair123** [comment]
![image](https://user-images.githubusercontent.com/13871941/83062230-38468a00-a056-11ea-9c25-4c5bb1ed711b.png)

**Comment by StevenBlair123** [comment]
Do you need any additional information?

**Comment by hayley-jean** [comment]
@StevenBlair123 This issue looks like it may be similar to https://github.com/EventStore/EventStore/issues/1872

Could you give the workaround mentioned there (falling back to `fromAll`) a try and see if it works?

**Comment by StevenBlair123** [comment]
hayley-jean, funnily enough, we had a play around with using fromAll on Friday, and that does seem to work.
Our team here is debating whether that is actually a cleaner solution that what we previously had using fromStreams (future proofing).

I will keep the repo code available if it helps in diagnosing the problem.

**Comment by hayley-jean** [comment]
Thank you for confirming that the workaround works! I'm going to close this to avoid duplication, please track the issue I linked earlier for updates and/or fixes
