### ISSUE TITLE
Missing event in category stream

### ISSUE THREAD

**Issue by seburgi** [EventStore/EventStore#251]
I know that projections are still in beta, but I hope this is still interesting for you. For better understanding I have to write the whole story, sorry for the long description:

EventStore version: 3.0.0 final

We provide some metadata for every event we write to EventStore. In our system events come from a couple of applications and every application adds their "appId”-Guid as metadata. In EventStore we have the appId-projection that processes every event and links to an application specific stream (eg "app-2eef789f-9030-4970-b6d0-8ab07b75a452”). So for example application one writes an event to a stream that is called like [AssemblyName]@[Hostname].Outgoing (eg ApplicationOne.Importer@MyComputer.Outgoing). Then the appId-projection links this event to the stream app-[Guid of application one]. Now we have streams per sender of an application and we have a big stream containing all events of one application. Great! 

The next thing we saw was that EventStore "magically” created a stream that contained ONLY our own events and no system events. This stream is the category stream for the category "app” ($ce-app). So what happend here? Turns out, that ES projections also process newly linked events, so when our appId-projection links to streams called "app-XXXX…” the builtin category projection gets triggered, analyzes the stream name and links the event to the stream $ce-app as app is the string before the first dash. Also really great, as we now have a more specific stream than the $all stream.

Are you still with me? I hope so, because now comes the problem: After an import of 45403 events we realized that 3 events were missing in the "$ce-app" stream. The missing events are in the senders "Outgoing”-stream, they were linked to the applications app-stream but then the category projection somehow messed up the link, as I can see the slots for the events in the category stream, but the link points to "streams//-1”.

For completeness here is our appId projection:

    fromAll()
        .when({

            $any: function (s, e) {
                if (e.eventType[0] != '$' && e.metadata && e.metadata['appId']) {
                    linkTo('app-' + e.metadata['appId'], e);
                }
            },
        })
    
And here one event in the category stream with the corrupt links:

    ...
    
    <entry>
        <title>-1@</title>
        <id>10.34.12.122:2113/streams//-1</id>
        <updated>2014-09-23T12:26:23.7915025Z</updated>
        <author>
            <name>EventStore</name>
        </author>
        <summary>$&gt;</summary>
        <link href="10.34.12.122:2113/streams//-1" rel="edit" />
        <link href="10.34.12.122:2113/streams//-1" rel="alternate" />
    </entry>
    
    ...

Regards
Sebastian

**Comment by JogoShugh** [comment]
This post was very helpful to us. We didn't know that `$ce-` streams were included in a fromCategory, so we wrapped some checks like you did around it seburgi.

**Comment by seburgi** [comment]
BTW: although we did not encounter the described behavior again, we are now reading from the $all stream. It might be a little slower, but it's safe ;-)

**Comment by pgermishuys** [comment]
@seburgi I am going to close this issue for now as we haven't seen this behaviour again when it wasn't expected (such as deleting the original stream etc).
Please feel free to open if this occurs again.
