### ISSUE TITLE
AppendToStreamAsync Incorrect Expected version : -2

### ISSUE THREAD

**Issue by mmigala** [EventStore/EventStore#2520]
**Describe the bug**
Hello,
we have a microservice application where Event store is used for transition of events.
All applications are hosted in Azure Kubernetes Services (including ES but we are migrating it to separate VM)

After last deployment of micro application events werent processed (Screen with error below)
![image](https://user-images.githubusercontent.com/24477615/83395367-70552080-a3fa-11ea-9370-63ba2d07b5f6.png)

Expected version: -2 was shown and events were parked in message queue

After restart of pod with application all events were processed correctly.

This was a one time situation but I was wondering what might be the cause ?

We use ExpectedVersion: Any for our events.

**Expected behavior**
No errors are thrown. Events are processed after deploy.

**Actual behavior**
Error shown in description is thrown

**EventStore details**
 - EventStore server version: release-5.0.6 helm chart

 - Operating system: Linux AKS VM

 - EventStore client version (if applicable): 5.0.1

**Comment by hayley-jean** [comment]
Hi @mmigala, It's possible to get a `WrongExpectedVersion` when using `ExpectedVersion.Any` if part of a batch has been committed, but not all of it.

For example, you could see this if you wrote an event to a stream with a specific EventId, and then tried to append a batch with more events in it but still containing an event with the same EventId as the previously-written event.
