### ISSUE TITLE
Boolean environment variables in 20.06 do not accept "1" to enable

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#2548]
**Describe the bug**

Setting `EVENTSTORE_DEV=1` does not enable developer mode, `true` is required instead.

**Expected behavior**

We should accept `1` and `0` to represent `true` and `false` for all boolean environment variables.

**EventStore details**
 - EventStore server version: 20.06

 - Operating system: Linux

**Comment by oskardudycz** [comment]
I'm closing this issue as we no longer support the `EVENTSTORE_DEV` setting.
