### ISSUE TITLE
More flexible logging

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#255]
I'm thinking of ways to deploy EventStore and I want a smooth way to do logging with these features:
- I want to manage cattle, so I don't really want to write logging to disk, preferably stateless logging to a logging daemon
- I don't particularly enjoy writing NLog targets (after having [written a few](https://github.com/haf/NLog.RabbitMQ/))
- I would like to have it configurable through command line or environment vars or both

I can send you a PR with support for http://logary.github.io/targets/overview/ which can be configured through command line flags or a config file (support for config file would then be in the PR, too) which supports lots of different state-less logging outputs.

You have a previous issue about the logging abstraction; I wouldn't mind implementing this abstraction as a separate lib, as long as there's a way I can get the implementation running in the latest release 3.0 or a derivative of it fairly close to now.

No matter what route we take, I'm really tired of [GROK-parsing](http://logstash.net/docs/1.4.2/filters/grok) for non-structured logging, as it just takes a lot of time away from me that I could spending writing nice code instead :) - so I really would like structured log output that I can just feed to a service of some sort.

The upside of using logary for you would be that you can output both metrics, health checks and log lines from it, instead of the rather limited log-lines only from NLog; so we can create nice samples with docker+grafana+eventstore+kibana.

What do you say?

**Comment by jageall** [comment]
This issue is now quite out of date, nlog has been updated and now supports targets and logs are now available in a structured format.  Closing this issue for now
