### ISSUE TITLE
Streams get deleted when Eventstore 20.6.0

### ISSUE THREAD

**Issue by ekjuanrejon** [EventStore/EventStore#2551]
**Describe the bug**
In docker event store 5.0 streams were not deleted when docker restarted. In the new docker eventstore the minute i restart eventstore all the streams are gone. this is a bit annoying when doing local development

**Comment by alexeyzimarev** [comment]
I don't think it's a bug. To persist data in containers, you need map the data volume. It's probably something to check in the Docker image repo https://github.com/EventStore/eventstore-docker

**Comment by ekjuanrejon** [comment]
I have mounted a volume and nothing gettings written


    volumes:
    - "./eventstore:/var/lib/eventstore"

**Comment by alexeyzimarev** [comment]
Seems you're using the compose file, mind copying its content here?

**Comment by alexeyzimarev** [comment]
also, are you running in dev mode?

**Comment by ekjuanrejon** [comment]
yes running in dev mode

**Comment by pgermishuys** [comment]
@ekjuanrejon the `dev` mode currently sets `memDb` to `true`. If you want to persist data you could set `--dev=true` and then `--mem-db=false`

**Comment by alexeyzimarev** [comment]
that's what I wanted to write too. here is the container log:

```
eventstore_1  | DEVELOPMENT MODE IS ON. THIS MODE IS *NOT* INTENDED FOR PRODUCTION USE.
eventstore_1  | WHEN IN DEVELOPMENT MODE EVENT STORE WILL
eventstore_1  |  - NOT WRITE ANY DATA TO DISK.
eventstore_1  |  - USE A SELF SIGNED CERTIFICATE.
```

**Comment by alexeyzimarev** [comment]
I think for now the only way to configure EventStoreDB in the container is either configure a volume pointing to the config file or use environment variables.
