### ISSUE TITLE
Memory usage / Good defaults - Azure ACI

### ISSUE THREAD

**Issue by inuvano-labs** [EventStore/EventStore#2552]
**Describe the bug**
We are currently evaluating Eventstore v5.0.8 running on Azure Container Instances (ACI) in the following configuration:

Image: eventstore/eventstore:release-5.0.8
OS: Linux
CPU: 1 vcore
Memory: 1gb
Storage (Data+Logs): Azure File Share
Env Vars:
- EVENTSTORE_CLUSTER_SIZE = 2
- EVENTSTORE_DISCOVER_VIA_DNS = true
- EVENTSTORE_CLUSTER_DNS = [name of dns]
- EVENTSTORE_RUN_PROJECTIONS = All
- EVENTSTORE_START_STANDARD_PROJECTIONS = true

After deployment - we navigate to the dashboard and check Cluster - everything looks in order.

However, memory usage is very strange. If we leave the cluster idle (no dashboard or API calls) the memory usage of both nodes increases steadily. I can see one of the nodes releasing memory, but then increases again:

![eventstore_node_memory](https://user-images.githubusercontent.com/25332352/84661577-77a81e00-af12-11ea-832d-57338c023cc3.PNG)

As you can see after a few days of being idle the memory is almost 100% of the container?

My questions are:

1) Is there anything to explain the behaviour of this? Perhaps additional env vars need setting, or something in the logs to look for?
2) Looking at the ES docs I can see various env vars available which mention memory? https://eventstore.com/docs/server/command-line-arguments/index.html is there a "good" or "optimised" defaults?

There aren't many memory related issues posted here, apart from https://github.com/EventStore/EventStore/issues/1516 but I'm not sure how relevant this is being Windows.

Any help much appreciated.

**Comment by ylorph** [comment]
This is on an older version.
