### ISSUE TITLE
Adjust Log Levels at runtime

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#2555]

**Comment by shaan1337** [comment]
I can confirm that this already works with Ubuntu 16.04 and EventStoreDB 20.6.0 (config file located at: /usr/share/eventstore/logconfig.json)

Link to code: https://github.com/EventStore/EventStore/blob/master/src/EventStore.Common/Log/EventStoreLoggerConfiguration.cs#L64

**Comment by hayley-jean** [comment]
This is also works on Windows already. The logconfig.json file is included in the zipped package and can be updated at runtime
