### ISSUE TITLE
Events with empty data in parked stream

### ISSUE THREAD

**Issue by xdavidnguyen** [EventStore/EventStore#2563]
**Describe the bug**

We have a worker application subscribing to a persistent subscription. Recently we found out that in the parked stream of our persistent subscription, there are quite a number of events with empty event number, type and data (which causes exception in our worker) as in picture below. We are not sure how those events going into the parked stream in the first place. It seems to happen only to parked stream, not normal stream that we are subscribing to

**To Reproduce**

It's difficult to reproduce this. So far I'm not able to post any events with empty data to eventstore

**Expected behavior**

All events in parked streams to have event id, type, data

**Actual behavior**

A large number of events in parked streams don't have event id, type, data

**Config/Logs/Screenshots**

<img width="1612" alt="eventstore" src="https://user-images.githubusercontent.com/59548494/85547156-f31b7500-b660-11ea-981c-4da8a016b442.png">

**EventStore details**
 - EventStore server version: 4.1.2

 - Operating system: Windows (Server). Alpine (Worker Application - in container)

 - EventStore client version (if applicable): 3.8.0

**Additional context**

I tried to use http api to query for those events with no event id, type and have 404 back

**Comment by gregoryyoung** [comment]
The parked stream normally has links written to it. Are these link events which maybe the original events have been deleted etc?

**Comment by xdavidnguyen** [comment]
@gregoryyoung I'm also not too sure whether it's link events or where they are from. Is there any way that I can check that from the UI or api?

**Comment by gregoryyoung** [comment]
If you read the parked stream there is an argument either over http or over tcp to resolve or not resolve linktos. If you resolve linktos you will get the pointed to events, if you do not resolve linktos you will only get the links existing in the stream.

To specify this argument you can use over http https://eventstore.com/docs/http-api/optional-http-headers/resolve-linkto/index.html?tabs=tabid-1%2Ctabid-3
or over tcp if you look the methods have a parameter whether to resolve linkTos https://eventstore.com/docs/dotnet-api/reading-events/index.html

**Comment by xdavidnguyen** [comment]
thanks @gregoryyoung , those are indeed links to events that are deleted. Our eventstore only keeps events for 3 days. Thanks
