### ISSUE TITLE
EventStoreDB 20.6 consistently crashes when deployed in Kubernetes with PVC

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/EventStore#2568]
When deploying in Kubernetes with exactly the same settings as 5.0.8 but with `--dev` and `--mem-db=false`, the server crashes after about 15 sec with this:

```
[eventstore-0 eventstore] [    1,18,18:28:07.161,WRN] Error occurred while releasing lock.
[eventstore-0 eventstore] System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
[eventstore-0 eventstore]    at System.Threading.Mutex.ReleaseMutex()
[eventstore-0 eventstore]    at EventStore.Core.ExclusiveDbLock.Release() in /build/src/EventStore.Core/ExclusiveDbLock.cs:line 52
```

**Comment by alexeyzimarev** [comment]
Worth noting that 5.0.8 works like a charm.

**Comment by alexeyzimarev** [comment]
And, although the log line is _warning_, the server shuts down

```csharp
Log.Warning(ex, "Error occurred while releasing lock.");
```

**Comment by thefringeninja** [comment]
So I ran this, I also got that warning but only after I explicitly shut it down. I don't think that error is triggering the shutdown,

**Comment by yuenm18** [comment]
I got that error too when I pulled the new image.  It looks like the issue is that the new image runs as *eventstore* now instead of *root*.  I added this to the statefulset and it seems to fix it.
```
spec:
...
  templates:
  ...
    spec:
    ...
      securityContext:
        fsGroup: 1000
```

**Comment by alexeyzimarev** [comment]
Yeah, I did the same and it works. It should be also working fine in 20.6.1, I am going to test it.

**Comment by BrunoZell** [comment]
The workaround provided by @yuenm18 doesn't work for me.

I also tried:

```yaml
apiVersion: apps/v1
kind: StatefulSet
...
spec:
  ...
  template:
    ...
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
        runAsNonRoot: true
```

With no success. It always results in the same `System.ApplicationException: Object synchronization method was called from an unsynchronized block of code. at System.Threading.Mutex.ReleaseMutex() at EventStore.Core.ExclusiveDbLock.Release() in /build/src/EventStore.Core/ExclusiveDbLock.cs:line 52`

I am using version `eventstore/eventstore:20.6.1-buster-slim`.

Have you ever validated this with 20.6.1 @alexeyzimarev ? Or can someone please share a working Kubernetes deployment I can try? This is a blocking issue for me right now.

**Comment by BrunoZell** [comment]
I got it to work. It seems the health check was failing and Kubernetes thus stopped the container. Removing the health check results in no shutdown and also no error. Seems to be related to #2514

**Comment by thefringeninja** [comment]
You can safely ignore that warning; it only happens when you shut the node down. The issue with the health check _should_ have been fixed in this PR: EventStore/EventStore#2677

**Comment by alexeyzimarev** [comment]
My issue was indeed something else. The error message is misleading since I thought it was related. Indeed the root cause was Kubernetes killing pods, so it might've been the same health endpoint issue.

I can imagine that's because the endpoint goes over https and I used http.

**Comment by BrunoZell** [comment]
Maybe a log message with the shutdown reason is a good idea? Something along the lines of _Received SIGTERM. Shutdown of node initiated_.

**Comment by alexeyzimarev** [comment]
Well, then Kubernetes kills the pod, the reason is available in the pod events log. When the pod crashes, it's crashed container, unlike it being killed due to the health check failure, which is a different kind of event. For the pod it's impossible to know why it's been shut down.
