### ISSUE TITLE
Do not verify that hostname matches in SAN when in --dev mode

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2569]
Currently the SAN in the dev certs contain localhost/127.0.0.1, so it will work only with a cluster running on a local machine. This makes it difficult to test in a cluster running on docker for example - certificates will need to be generated. We could simply ignore the `RemoteCertificateNameMismatch` SSL policy error when in --dev mode.

**Comment by shaan1337** [comment]
Can we close this? We no longer distribute dev certs and --dev does not use TLS so it's no longer applicable.

**Comment by pgermishuys** [comment]
Yes @shaan1337. Closing this as this is no longer an issue.
