### ISSUE TITLE
Not enough permission to log for user eventstore on Docker eventstore/eventstore:20.6.0-buster-slim

### ISSUE THREAD

**Issue by Lougarou** [EventStore/EventStore#2570]
**Describe the bug**
The eventstore user on the docker image eventstore/eventstore:20.6.0-buster-slim does not have enough permission to log at /var/log/eventstore. 

**To Reproduce**
1. docker pull eventstore/eventstore:20.6.0-buster-slim
2. docker run -it -p 2113:2113 -p 1113:1113 eventstore/eventstore --dev
3. docker exec -i {container_id} /bin/bash
4. ls /var/log/eventstore

**Expected behavior**
Logs should be found there

**Actual behavior**
No logs are found/folder has not been created

**EventStore details**
 - EventStore server version: eventstore/eventstore:20.6.0-buster-slim

**Additional context**
Quick workaround is to change the log path to a folder with enough permissions. For example: docker run -it -p 2113:2113 -p 1113:1113 eventstore/eventstore --dev --log /opt/eventstore/log/

**Comment by alexeyzimarev** [comment]
I already mentioned it to the dev team. The common practice is to use user ids, like `1001` (default unprivileged local user) so users get it with correct local permissions since it properly mapped to their own local account.
