### ISSUE TITLE
Documentation - for "Getting started" not aligned with version 20.6.0 (https required, parameters changed/required

### ISSUE THREAD

**Issue by JimiSweden** [EventStore/EventStore#2573]
**Describe the bug**
documentation for "Getting started" is not aligned with version 20.6.0 

https is required (http is used in documentation https://eventstore.com/docs/getting-started/index.html?tabs=tabid-1%2Ctabid-dotnet-client%2Ctabid-dotnet-client-connect%2Ctabid-4#discover-event-store-via-admin-ui) 

- parameters changed/required
new property : "TrustedRootCertificatesPath" not documented (https://github.com/EventStore/EventStore/pull/2335 ) - how do I use it? 
removed(?) property : ExtSecureTcpPort 
- throws EventStore.Rags.OptionException: The option ExtSecureTcpPort is not a known option
(ExtSecureTcpPort is used in config example at https://eventstore.com/docs/server/setting-up-ssl/index.html?tabs=tabid-6%2Ctabid-8#setting-up-ssl-on-windows

```
CertificateStoreLocation: CurrentUser
CertificateStoreName: My
CertificateThumbPrint: {Insert Thumb Print from Step 1}
CertificateSubjectName: CN=eventstore.com
ExtSecureTcpPort: 1115
```
(TrustedRootCertificatesPath with example would be nice above)

**To Reproduce**
Try "getting started# - Following https://eventstore.com/docs/getting-started/index.html for windows (and also docker)

(I had problems to understand why I could not connect to http://127.0.0.1:2113/ when following the guide. =D)

//Jimi

**Comment by Brent7788** [comment]
YES, Please I want an answer to this question??

I have tried to install evenstore 20.6 with docker using the --dev tag, it works but every time I stop the docker container, I lost all my data. So I have tried to generate certificates in docker using the evenstore docs https://eventstore.com/docs/server/setting-up-ssl/index.html?tabs=tabid-6%2Ctabid-8

Noting seems to work. The EvenStore documentation is outdated. Please fix this. I want to get EventStore 20.6 production-ready!

**Comment by pgermishuys** [comment]
@Brent7788 and @JimiSweden, your frustration is completely understandable. I can assure you that the documentation is being addressed.

@Brent7788, the `dev` flag (only meant for development purposes) also sets the `mem-db` flag which has to explicitly be set to false if you want your data to be persisted.
e.g.
`--dev --mem-db=false --db={database-path}`

**Comment by alexeyzimarev** [comment]
> I have tried to install evenstore 20.6 with docker using the --dev tag, it works but every time I stop the docker container, I lost all my data.

The `--dev` mode runs with in-memory database. When you run the container, the server gives this message to you.

> Noting seems to work. The EvenStore documentation is outdated. Please fix this.

We know that the docs are outdated. The page you were referring to is for 5.0.8. We hope to publish the 20.6 docs during the coming week.

**Comment by WhatFor** [comment]
I was able to work out the kinks with local HTTPS and a non `--dev` instance, however running into major issues with using the ClientAPI `ProjectionsManager` over HTTPS.

**Comment by alexeyzimarev** [comment]
It's time to close this issue as the dev scenario and insecure mode are documented properly now.
