### ISSUE TITLE
An unhandled exception was thrown by the application. System.AggregateException: (IFeatureCollection has been disposed. Object name: 'Collection'.)

### ISSUE THREAD

**Issue by avish0694** [EventStore/EventStore#2576]
Setting up new eventstore and let it run for some time without actually using it throws unhandled exception

**To Reproduce**
1. Start a new event store node on docker

**Expected behavior**
No exception thrown.

> **Actual behavior**
> [ 6,39,09:20:12.471,ERR] Connection id ""0HM0ORNV708F0"", Request id ""0HM0ORNV708F0:00000002"": An unhandled exception was thrown by the application.
> 
> > System.AggregateException: One or more errors occurred. (IFeatureCollection has been disposed.
> > Object name: 'Collection'.)
> >  ---> System.ObjectDisposedException: IFeatureCollection has been disposed.
> > Object name: 'Collection'.
> >  at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()
> >  at Microsoft.AspNetCore.Http.DefaultHttpContext.get_RequestAborted()
> >  at EventStore.Core.Services.Transport.Http.Authentication.HttpAuthenticationRequest.Cancel() in /build/src/EventStore.Core/Services/Transport/Http/Authentication/HttpAuthenticationRequest.cs:line 36
> >  at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
> >  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> > --- End of stack trace from previous location where exception was thrown ---
> >  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
> >  --- End of inner exception stack trace ---
> >  at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
> >  at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CancelRequestAbortedToken()
>

**Config/Logs/Screenshots**
 N/A

**EventStore details**
 - EventStore server version: 20.6.0

 - Operating system: docker image eventstore/eventstore:20.6.0-buster-slim (Debian)

 - EventStore client version (if applicable): N/A

**Additional context**
Changing the log folder causes the issue to disappear.

**Comment by hayley-jean** [comment]
Closed by https://github.com/EventStore/EventStore/pull/2682
