### ISSUE TITLE
EventStore 20.6 sends itself sigkill during elections

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [EventStore/EventStore#2579]
**Describe the bug**
I have a three nodes coming online, trying to elect a leader. It seems that after a certain period of being unable to contact other nodes, the `eventstored` process receives sigkill from itself, according to `auditd` logs. There's not a clear indication of why this is occurring in the logs, no offline truncation or anything like that. Just a series of failed elections, then `killed`. 

**To Reproduce**
1. Restore a three node cluster from backup, upgrade the nodes, and bring them online simultaneously
2. Watch the logs and observe each node eventually send itself sigkill
3. This process repeats as systemd automatically restarts the process after it exits

**Expected behavior**
All nodes to initialize, come online, and form a healthy cluster

**Actual behavior**
Failed elections -> sigkill -> systemd restart -> failed elections -> sigkill

**Config/Logs/Screenshots**
D8s_v3 Azure VMs (8 cores, 32GB RAM)
2 TiB disk for EventStore logs, index, and data
Database is around 750 GiB.

**EventStore details**
 - EventStore server version: 20.6.0

 - Operating system: Ubuntu 18.04

 - EventStore client version (if applicable): n/a

**Additional context**

**Comment by hayley-jean** [comment]
Hi @01100010011001010110010101110000 

Thank you for reporting this, could you please provide the config you are using?

**Comment by 01100010011001010110010101110000** [comment]
Certainly:
```
---
GossipSeed: 10.5.0.5:2113,10.5.0.6:2113
RunProjections: All

ClusterSize: 3
Log: /eventstore/logs
Db: /eventstore/db
DiscoverViaDns: false
IntTcpHeartbeatInterval: 5000
IntTcpHeartbeatTimeout: 2000
GossipTimeoutMs: 1000

## TCP/IP Settings
IntIp: 10.5.0.4
ExtIp: 10.5.0.4

## TLS Settings
CertificateFile: /etc/eventstore/eventstore-new.p12
CertificatePassword: '<redacted>'

SkipDbVerify: true
SkipIndexVerify: true

InitializationThreads: 8
ProjectionThreads: 6
ReaderThreadsCount: 8
ChunksCacheSize: 17179869184 # 16GiB chunk cache

#### ES6 CHANGES ####
EnableExternalTcp: true
HttpPort: 2113
HttpPortAdvertiseAs: 2113
ExtTcpPort: 1115
IntTcpPort: 1117
IntHostAdvertiseAs: 10.5.0.4
ExtHostAdvertiseAs: 10.5.0.4
TrustedRootCertificatesPath: /usr/local/share/ca-certificates
```
`/usr/local/share/ca-certificates` contains the root CA used to cut the certs used by each node. The config is identical on the other nodes other than the gossip seeds, host advertisements, and and int/ext ip.

**Comment by hayley-jean** [comment]
Thank you for the config, we haven't had any success reproducing this issue.

Would you be able to share your logs with us @01100010011001010110010101110000?

Also, the default gossip interval and timeout has been increased to 2000ms and 2500ms respectively in 20.6.0.
Could you try return these settings to their defaults and see if that helps with getting your cluster online?

**Comment by 01100010011001010110010101110000** [comment]
@hayley-jean I have the json logs and the logs from systemd's journal zipped, how should I send them to you?

**Comment by hayley-jean** [comment]
Thank you! You can send them to hayley.campbell at eventstore.com

If you can't attach them to an email, you could upload them to somewhere like google drive and share them with that email address.

**Comment by 01100010011001010110010101110000** [comment]
This was a misconfig on my part, I neglected to lower the cache size to accommodate the smaller nodes in this test env, and the cache size was larger than available memory. The sigkill seeming to be sent from ES threw me. @hayley-jean thanks for the help on this.
