### ISSUE TITLE
Add SkipCertificateValidation changes to `master`

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#2588]
The changes in the following [PR](https://github.com/EventStore/EventStore/pull/2585) needs to be made on `master`.

**Comment by shaan1337** [comment]
This is dealt with by this PR: https://github.com/EventStore/EventStore/pull/2554

**Comment by shaan1337** [comment]
The change to allow `SkipCertificateValidation=True` in connection strings was not backported to `master`
