### ISSUE TITLE
Add ability to disable per stream permissions validation

### ISSUE THREAD

**Issue by slav** [EventStore/EventStore#2607]
**Is your feature request related to a problem? Please describe.**
Whenever ES is writing event to event stream, it verifies whether current user has permissions to write into that event stream. This creates an overhead of loading stream permissions. This information is cached, however if number of streams is very large and often different streams are being written to, this results in a lot of cache misses (it seems, there's no telemetry or stats on the cache performance).

At the same time, in our environment ES is installed in closed virtual network with extremely limited access. We don't need per stream permissions and would rather not have to pay the extra cost of checking permissions per write.

**Describe the solution you'd like**
Provide a config option to disable per stream permissions validation. Another approach could be to have user global write permissions, and if user has that permission per stream validation doesn't take place.

**Describe alternatives you've considered**
Not sure what alternative solution could be? Right now this penalty is unavoidable.

**Comment by Lougarou** [comment]
Closing issue, please refer to ticket reply.
