### ISSUE TITLE
Persistent subscription lost connection

### ISSUE THREAD

**Issue by hsjalilian** [EventStore/EventStore#2610]
send create new stream request from c# with EventStore.Client to server , but recieve this error: 
"One or more errors occurred. (Connection 'ES-0d6ec852-437b-41c8-b2bc-3426e723ea42' was closed.)"

`var conn = EventStoreConnection.Create(new Uri("tcp://admin:password@server:1113"));
                conn.ConnectAsync().Wait();

                var streamName = "newstream";
                var eventType = "event-type";
                var data = "{ \"a\":\"2\"}";
                var metadata = "{}";
                var eventPayload = new EventData(Guid.NewGuid(), eventType, true, Encoding.UTF8.GetBytes(data), Encoding.UTF8.GetBytes(metadata));
                conn.AppendToStreamAsync(streamName, ExpectedVersion.Any, eventPayload).Wait();`

i can see Connection was open in Dashboard tab admin UI , but nothing happend in Stream browser tab !

**Logs/Screenshots**

2020-07-24 11:44:35.5454|INFO|TcpService|External TCP connection accepted: [Normal, 192.168.1.1:34648, L172.17.0.7:1113, {7f70f388-9f4e-4ae9-ad60-b3221e2dcab3}].
2020-07-24 11:44:40.5598|TRACE|TcpConnectionManager|Closing connection '"external-normal"""' [192.168.1.1:34648, L172.17.0.7:1113, {7f70f388-9f4e-4ae9-ad60-b3221e2dcab3}] cleanly." Reason: HEARTBEAT TIMEOUT at msgNum 1"
2020-07-24 11:44:40.5598|INFO|TcpConnection|ES "TcpConnection" closed [11:44:40.560: N192.168.1.1:34648, L172.17.0.7:1113, {7f70f388-9f4e-4ae9-ad60-b3221e2dcab3}]:Received bytes: 174, Sent bytes: 22
2020-07-24 11:44:40.5598|INFO|TcpConnection|ES "TcpConnection" closed [11:44:40.560: N192.168.1.1:34648, L172.17.0.7:1113, {7f70f388-9f4e-4ae9-ad60-b3221e2dcab3}]:Send calls: 1, callbacks: 1
2020-07-24 11:44:40.5598|INFO|TcpConnection|ES "TcpConnection" closed [11:44:40.560: N192.168.1.1:34648, L172.17.0.7:1113, {7f70f388-9f4e-4ae9-ad60-b3221e2dcab3}]:Receive calls: 2, callbacks: 1
2020-07-24 11:44:40.5598|INFO|TcpConnection|ES "TcpConnection" closed [11:44:40.560: N192.168.1.1:34648, L172.17.0.7:1113, {7f70f388-9f4e-4ae9-ad60-b3221e2dcab3}]:Close reason: [Success] "HEARTBEAT TIMEOUT at msgNum 1"
2020-07-24 11:44:40.5598|INFO|TcpConnectionManager|Connection '"external-normal"""' [192.168.1.1:34648, {7f70f388-9f4e-4ae9-ad60-b3221e2dcab3}] closed: Success.
2020-07-24 11:44:40.5598|DEBUG|PersistentSubscriptionService|Persistent subscription lost connection from 192.168.1.1:34648

**EventStore details**
 - Operating system:
  Ubuntu 18.04 -> Docker
 

**Additional context**
EventStore server is behind haproxy and nginx

**Comment by engmsaleh** [comment]
I have the same issue on Docker running on mac

**Comment by gregoryyoung** [comment]
Is this being run in a debugger?

**Comment by pgermishuys** [comment]
@hsjalilian, which version of Event Store are you running on?
If you are running on 20.6.x, you want to enable the external tcp interface as it's been disabled by default in 20.6.x. This can be done with the `EVENTSTORE_ENABLE_EXTERNAL_TCP` environment variable.

**Comment by engmsaleh** [comment]
@pgermishuys I'm running the latest from docker hub and have TCP enabled 
This is the eventstore part of the docker-compose I use

```  eventstore:
    image: eventstore/eventstore
    container_name: eventstore
    command: --dev --enable-external-tcp --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --disable-external-tcp-tls
    ports:
      - 1113:1113
      - 2113:2113
    environment:
      EVENTSTORE_POOLOPTIONS_MIN: 1
      EVENTSTORE_POOLOPTIONS_MAX: 10
      EVENTSTORE_DEV: 1
      EVENTSTORE_INT_TCP_PORT: 1112
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_INT_HTTP_PORT: 2112
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: 1
    volumes:
      - eventstore_data:/var/lib/eventstore```

Do I miss something?

**Comment by hsjalilian** [comment]
Hi, 

my Event Store version is 5.0.8.0 , and run from "docker pull eventstore/eventstore"
"EVENTSTORE_ENABLE_EXTERNAL_TCP" not work!

@pgermishuys

**Comment by alexeyzimarev** [comment]
@hsjalilian because `EnableExternalTcp` only works for 20.6. I am not sure how you run 5.0.8 when using the `eventstore/eventstore` image since it points to the latest tag (20.6). For 5.0.8 you need to use `eventstore/eventstore:release-5.0.8`

**Comment by alexeyzimarev** [comment]
@hsjalilian also, in 20.6 the AtomPub protocol is disabled by default and Admin UI uses it for the stream explorer, so you won't see anything.

I am a bit confused, is your issue that you can't write events to 20.6 or with your persistent subscription? Is there a more complete version of your code available?

**Comment by hsjalilian** [comment]
@alexeyzimarev , change image to **releae-5.0.8**  but receive error again.

**part of container inspect info** 

` "Config": {
            "Hostname": "16b2ee168684",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1112/tcp": {},
                "1113/tcp": {},
                "2112/tcp": {},
                "2113/tcp": {},
                "80/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "--enable-external-tcp",
                "--enable-atom-pub-over-http",
                "--run-projections=all",
                "--start-standard-projections=true",
                "EVENTSTORE_ENABLE_EXTERNAL_TCP=True",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ES_VERSION=5.0.8-1",
                "DEBIAN_FRONTEND=noninteractive",
                "EVENTSTORE_CLUSTER_GOSSIP_PORT=2112"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "curl -sf http://localhost:2113/stats || exit 1"
                ],
                "Timeout": 2000000000
            },
            "Image": "eventstore/eventstore:release-5.0.8",
            "Volumes": {
                "/var/lib/eventstore": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
`

**Source Code** 

` var conn = EventStoreConnection.Create(new Uri("tcp://admin:pass@domain:1113"));
                conn.ConnectAsync().Wait();
                var streamName = "newstream";
                var eventType = "event-type";
                var data = "{ \"a\":\"2\"}";
                var metadata = "{}";
                var eventPayload = new EventData(Guid.NewGuid(), eventType, true, Encoding.UTF8.GetBytes(data), Encoding.UTF8.GetBytes(metadata));
                conn.AppendToStreamAsync(streamName, ExpectedVersion.Any, eventPayload).Wait();`


**Error**

`One or more errors occurred. (Connection 'ES-927674af-81c2-47ed-a759-5c0d36eac9f7' was closed.)`

**Comment by alexeyzimarev** [comment]
Everything in 5.0.8 works fine, as well as any other 5.X release. We use it in production for years. I suggest moving to [Discuss](https://discuss.eventstore.com/) about your issues. Also, you can find some working code in my [book repository](https://github.com/PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET-Core), but the image tag there needs to be replaced to `release-5.0.8`, for the rest it works.

**Comment by hsjalilian** [comment]
my problem solve by change in source code:

**change** 

```c#
var conn = EventStoreConnection.Create(new Uri("tcp://admin:password@domain:1113"));
```

**To** 

```c#
var consetting = ConnectionSettings.Create().DisableTls().Build(); 
var conn = EventStoreConnection.Create(consetting,new Uri("tcp://admin:password@domain:1113"));
```
