### ISSUE TITLE
High memory usage during full index rebuilds

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2611]
As reported by @slav, full index rebuilds can cause a very high memory usage. The following settings brought significant improvements according to @slav (on Windows):
- Set the GC to server mode instead of the default workstation mode
- Set ReduceFileCachePressure to True

According to GC reports, the large object heap (LOH) was also using a very high amount of memory since the database probably contained large events (>85kb) which would cause them to go on the LOH. We could consider calling GC.Collect() at regular intervals in the index rebuild loop to keep the LOH usage low.

**Comment by slav** [comment]
Just to clarify:
* LOH memory usage went up during index merges. After merge completed it went back down to normal levels. During merge I have seen consumption go from 25-30GB to 55-60GB and all tho way up to 110GB. This problem might appear during normal operation when index merges take place.
* ReduceFileCachePressure is needed on Windows. It forces windows memory manager to release memory used for file caching. I'm not sure it has any effect on windows.

**Comment by hayley-jean** [comment]
Fixed by https://github.com/EventStore/EventStore/pull/2700
