### ISSUE TITLE
Feature/Enhancement Request: Make scavenge save more space.

### ISSUE THREAD

**Issue by Lougarou** [EventStore/EventStore#2626]
**Is your feature request related to a problem? Please describe.**
Some databases contain a significant number of linkTo events and delete streams. Given that scavenging does not cover linkTo streams and keeps the last event in a deleted stream; the amount of the space saved can be limited/less than expected. This issue is accentuated in a database with short lived events.

This is a feature request or enhancement request to allow more space to be saved when running the scavenge operation.

**Additional Context**
Below is a list of remnant data identified after a scavenge operation:

* LinkTo Streams are not scavenged. This includes linkTo streams with broken linkTo events where the resolved event is already deleted.
* Last event is kept in a deleted stream.
* Long stream names can also potentially contribute to remnant space in a large database as this is also kept after deletion.

**Describe alternatives you've considered**

* Identify truncate-able positions in linkTo streams (risky, error-prone and does not save much space if at least one event at the start is still resolving to an event) and truncate the linkTo streams.
* Add an empty event before deleting a stream

<sub>[DB-372](https://linear.app/eventstore/issue/DB-372/featureenhancement-request-make-scavenge-save-more-space)</sub>

**Comment by megakid** [comment]
> 
> **Describe alternatives you've considered**
> 
> - Identify truncate-able positions in linkTo streams (risky, error-prone and does not save much space if at least one event at the start is still resolving to an event) and truncate the linkTo streams.
> 
> 

We have written an external C# tool that does exactly this. 

Since the major population of our streams have TTL retention on them, the `$ce-` projections of them can be safely truncated if you linearly search from 0 upwards for dead links. As soon as you find a link that works, you set the `$tb` value to that version.

As you say, this won't work as well if the linkTo origin streams have mixed retention policies but we scavenged nearly 5 billion (!) events in a single scavenge pass after we implemented this. It saved over 100GB in index files alone.

**Comment by gregoryyoung** [comment]
"Last event is kept in a deleted stream."

OK so I believe this might just be a touch more complicated than it may initially seem.

The last event of the stream is there for ... reasons. Its needed to know where to **start from** if a stream were to be recreated (think soft-delete, hard-delete is obviously no issue) ... There is a another secondary issue involved that needs more looking at (sorry I don't remember all of the edge cases off the top of my head) ... an index hash collision :O as it will be in the index for an indeterminate period of time after deletion!!! Where this gets **REALLY NASTY** is in determining if I should return that this thing **does not exist** or whether **it was deleted**. The tombstone allows saying deterministically which case this actually is.

Adding a tiny stream deleted event on delete here (thus allowing all previous to be removed but retaining the tombstone) should be no problem but not having **any** marker would I believe not work.

**Comment by megakid** [comment]
Another issue we've faced re. ineffectual scavenging was `-result` streams from a user defined projection.  These were very numerous and due to the nature of them, we were unable to get rid of them (I believe most of this is a rehash of the re. last event kept issue).  We ended up rolling onto a new fresh database (luckily it was fairly trivial to do in this case but we have others where it would be quite difficult due to long-running streams/versioning) to get back down to a sensible size.

**Comment by gregoryyoung** [comment]
Hmm thanks @megakid let me look through the result streams. I believe these at some point had a maxCount being assigned to them but it depends on the type of result (projections have multiple types of results think .foreachStream() vs without). I am guessing this is a continuous projection not a historical?

I made a note to look at at this and hopefully will within the next 48-72 hours or so (likely tonight but don't want to give false hope :)). If nothing else it should be possible to allow something to be set here (not sure best way of exposing it ... yet).

**Comment by gregoryyoung** [comment]
@megakid was the result a .foreachStream result?

**Comment by megakid** [comment]
Yep sounds familiar. With `outputState()` too.

One thing we thought about regarding deleted streams, you could generate a tombstone event for deleted streams to provide just the necessary info for the reasons you note above. This could be especially effective (at improving space recovery) if the deleted stream payloads are large.

**Comment by TheAngryByrd** [comment]
I'd definitely be interested in this feature. I have chunks from years ago filled with linkTo's from the System Projections that reference nothing anymore.

**Comment by oskardudycz** [comment]
@timothycoleman, is it something that you plan to cover in your scavenge process improvements?

**Comment by alexeyzimarev** [comment]
We identified that most of the space in scavenged chunks in databases where streams are getting actively truncated or deleted is used for things like links. We cannot remove events from the middle of the stream, and it makes killing links almost impossible. We are looking in alternatives for links as they are, essentially, second-range indexes, but it's not related to scavenging.
