### ISSUE TITLE
How to run EventStore with TLS enabled?

### ISSUE THREAD

**Issue by AbdoDabbas** [EventStore/EventStore#2630]
**Describe the bug**
I tried to follow the documentation to setup the SSL:
https://eventstore.com/docs/server/setting-up-ssl/index.html?tabs=tabid-6%2Ctabid-8

Using the nightly build version `2020-08-09-nightly`, I faced some issues:
**1.** In the config file, "ExtSecureTcpPort: 1115" wasn't recognizable, I tried to start the EventStore and it crashed because of it.

**2.** .NET Client v20.6.0, the `UseSslConnection` method doesn't exists:
```C#
var settings = ConnectionSettings.Create().UseSslConnection("eventstore.com", true);
```
I understood it's because v20 is using SSL by default.

So I used the following to run EventStore:
```Powershell
> .\EventStore.ClusterNode.exe --db ./db --log ./logs --run-projections=all --start-standard-projections --enable-external-tcp --dev --config=config.yaml
```

I tested using the following code:
```C#
var settings = ConnectionSettings.Create();
settings.UseCustomHttpMessageHandler(new System.Net.Http.SocketsHttpHandler
{
	SslOptions = {
		RemoteCertificateValidationCallback = delegate { return true; }
	}
});

using (var conn = EventStoreConnection.Create(settings, new IPEndPoint(IPAddress.Loopback, 1115)))
{
	conn.ConnectAsync().Wait();

	var gossipEndpoint = new IPEndPoint(IPAddress.Loopback, 1113);

	var manager = new ProjectionsManager(conn.Settings.Log,
		gossipEndpoint, TimeSpan.FromSeconds(30));

	var cred = new UserCredentials("admin", "changeit");

	var res = manager.ListAllAsync(cred).Result;

	Console.WriteLine($"Projections: {res.Count}");
}
```

And got exception:
```
'One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (No connection could be made because the target machine actively refused it.)))'
```

**Comment by AbdoDabbas** [comment]
Any help ?!

**Comment by alexeyzimarev** [comment]
Do you have trouble running EventStoreDB or connecting to it?

**Comment by AbdoDabbas** [comment]
Trouble with using ProjectionManager in it, I updated my description it wasn't clear sorry.

**Comment by alexeyzimarev** [comment]
What's the content of that `config.yaml` file?

**Comment by alexeyzimarev** [comment]
If you are using the old docs code, which has this:

```
using (var conn = EventStoreConnection.Create(settings, new IPEndPoint(IPAddress.Loopback, 1115)))
{
    conn.ConnectAsync().Wait();
}
```

you can see that it uses the `IEventStoreConnection`, which is the TCP connection, so it connects to `1115`, which is the TCP port from the config.

The projection manager not using TCP. It uses the HTTP API. (maybe gRPC in 20.6, I am not sure). So, you need to connect to the TCP port.

**Comment by AbdoDabbas** [comment]
config.yaml:
```yaml
CertificateStoreLocation: CurrentUser
CertificateStoreName: My
CertificateThumbPrint: {--- CERT Fingerprint ---}
CertificateSubjectName: CN=eventstore.com
EnableAtomPubOverHttp: True
```
I'm using client v20.6.  
The code is as I wrote in the issue described above.
What exactly the code I should use? I set the port to 1113 (like the snippet above).

**Comment by alexeyzimarev** [comment]
You can use the [configurator](https://developers.eventstore.com/server/v20/server/installation/) tool and get your config sorted. It will also give you the connection string.
