### ISSUE TITLE
Catchup subscription hangs

### ISSUE THREAD

**Issue by ekjuanrejon** [EventStore/EventStore#2632]
**Describe the bug**
I am currently running eventstore 20.0.6 inside docker with a Windows 10 host. Now and then the catch up subscription hangs. meaning it no longer receive events. I have to manually restart the process. I notice that this happens when I run all my integration test all at once. If I manually run the integration test one by one it works fine. The minute I run about 15 integration test the catch subscription hangs

**To Reproduce**
1. Run multiple catch subscription and fire multiple events

**Expected behavior**
Catch-up Subscription should not hang

**Actual behavior**
Catchup Subscription hangs

**Comment by hayley-jean** [comment]
Thanks for reporting this @ekjuanrejon 

Could you please provide us with your catchup subscription code, or with a reproduction if you have one?
Also, can you please confirm the version of the client you are using, and whether you are using the TCP client?

**Comment by hayley-jean** [comment]
Hi @ekjuanrejon,

Are you still seeing this issue?
If so, could you share the client and client version you're using, and any reproduction code you have?

**Comment by pvanbuijtene** [comment]
Closing for now.
