### ISSUE TITLE
data are lost after restarting the database server

### ISSUE THREAD

**Issue by NoobDay** [EventStore/EventStore#2633]
**Describe the bug**
I'm having a problem with EventStore db **my events are lost after restarting the database server**
I added some events from admin UI but after rerunning 
`./EventStore.ClusterNode.exe --dev --enable-external-tcp --disable-external-tcp-tls --db ./db --log ./logs 
`
all events are lost 

**Expected behavior**
Normally database is for persisting 

**Actual behavior**
After Each restart stream is empty 

**Config/Logs/Screenshots**
**After restarting the database server**
![image](https://user-images.githubusercontent.com/16271638/90134890-241b4a80-dd72-11ea-8143-f608bb093d74.png)

**EventStore details**
 - EventStore server version:
   Event Store 20.6.0 
 - Operating system:
   Windows 10 (unzipped the Eventstore databse archive)

**Comment by pgermishuys** [comment]
Hey @NoobDay,
By using the `dev` (Development) flag, Event Store Db will use the in memory database. You can turn off the in memory database by setting MemDb to false (`--mem-db=false`) in addition to the other flags you specified.

**Comment by NoobDay** [comment]
Nice ! thanks @pgermishuys 
it works !
