### ISSUE TITLE
Unable to connect test client to 20.06 with TLS enabled

### ISSUE THREAD

**Issue by kpfaulkner** [EventStore/EventStore#2639]
This might be similar to https://github.com/EventStore/EventStore/issues/2630

I'm in the process of starting up a 20.06 cluster (so we can move off 5.0.8) and am having plenty of difficulties, but hoping this is more about my ES knowledge than anything else.

Currently, I can only get my test client (Go based) to connect to the cluster IF I have:

DisableExternalTcpTls: true
EnableExternalTCP : true

in my yaml file.

I have certificates setup using the keys TrustedRootCertificatesPath, CertificateFile and CertificatePrivateKeyFile. I believe these can be used instead of the CertificateStoreLocation, CertificateStoreName etc etc options (is that correct?)

At the moment I'm using the TCP client connection since our main application will still be on the 5.0.8 client for a little while before we make the move to grpc. 

If I change the configuration to be DisableExternalTcpTls: false then I can no longer connect.

When I try to connect I get the below message repeated a lot at the CLI that is running the ES node:

[ 2884,31,02:45:36.987,INF] External TCP connection accepted: [Secure, "10.1.2.101:51408", L"10.1.2.102:1113", {8de8f8e6-ae74-4f9f-8d7c-3663bf5911f7}].
[ 2884,31,02:45:37.007,INF] [S"10.1.2.101:51408", L"10.1.2.102:1113"]: Authentication exception on EndAuthenticateAsServer.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at EventStore.Transport.Tcp.TcpConnectionSsl.OnEndAuthenticateAsServer(IAsyncResult ar) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Transport.Tcp\TcpConnectionSsl.cs:line 161
[ 2884,31,02:45:37.007,INF] ES "TcpConnectionSsl" closed [02:45:37.007: N"10.1.2.101:51408", L"10.1.2.102:1113", {8de8f8e6-ae74-4f9f-8d7c-3663bf5911f7}]:Received bytes: 0, Sent bytes: 0
[ 2884,31,02:45:37.007,INF] ES "TcpConnectionSsl" closed [02:45:37.007: N"10.1.2.101:51408", L"10.1.2.102:1113", {8de8f8e6-ae74-4f9f-8d7c-3663bf5911f7}]:Send calls: 0, callbacks: 0
[ 2884,31,02:45:37.007,INF] ES "TcpConnectionSsl" closed [02:45:37.007: N"10.1.2.101:51408", L"10.1.2.102:1113", {8de8f8e6-ae74-4f9f-8d7c-3663bf5911f7}]:Receive calls: 0, callbacks: 0
[ 2884,31,02:45:37.007,INF] ES "TcpConnectionSsl" closed [02:45:37.007: N"10.1.2.101:51408", L"10.1.2.102:1113", {8de8f8e6-ae74-4f9f-8d7c-3663bf5911f7}]:Close reason: [SocketError] "Authentication failed, see inner exception."
[ 2884,31,02:45:37.007,INF] Connection '"external-secure"""' ["10.1.2.101:51408", {8de8f8e6-ae74-4f9f-8d7c-3663bf5911f7}] closed: SocketError.
TcpConnectionSsl::InitClientSocket(10.1.2.101:51409, L10.1.2.102:1113)
[ 2884,31,02:45:37.189,INF] External TCP connection accepted: [Secure, "10.1.2.101:51409", L"10.1.2.102:1113", {44512a17-cdf2-45c3-94d8-d3efb3b127bc}].

I might fire up a C# test client as well to check it's not the Go client library... but this client works perfectly fine with the 5.0.8 cluster we have.

Anything sounding obvious that I'm messing up?

**Comment by alexeyzimarev** [comment]
The 5.0.8 server, is it configured with TLS/SSL?

Are you aiming to connect to a secure cluster when moving to 20.6.X?

**Comment by dharmaturtle** [comment]
I'm a brand new user trying on ES for size. When I download and unzip v20.6.1 in Windows and run `EventStore.ClusterNode.exe --db ./db --log ./logs --insecure`, it seems to start up the server. However, the following code doesn't connect:

```
using EventStore.ClientAPI;
using EventStore.ClientAPI.SystemData;
using System;
using System.Text;

namespace ConsoleApp1 {
  class Program {
    static void Main(string[] args) {
      Console.WriteLine("hi es");
      var conn = EventStoreConnection.Create(new Uri("tcp://admin:changeit@localhost:1113"));
      conn.ConnectAsync().Wait();
      var streamName = "newstream";
      var eventType = "event-type";
      var data = "{ \"a\":\"2\"}";
      var metadata = "{}";
      var eventPayload = new EventData(Guid.NewGuid(), eventType, true, Encoding.UTF8.GetBytes(data), Encoding.UTF8.GetBytes(metadata));
      Console.WriteLine("trying to append....");
      conn.AppendToStreamAsync(streamName, ExpectedVersion.Any, eventPayload).Wait();
    }
  }
}
```

Using `<PackageReference Include="EventStore.Client" Version="20.6.1" />`

Stacktrace:

        System.AggregateException
        HResult=0x80131500
        Message=One or more errors occurred. (Connection 'ES-7d6611ec-c9cd-4ad4-9a6d-8e3020afe2db' was closed.)
        Source=System.Private.CoreLib
        StackTrace:
        at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
        at System.Threading.Tasks.Task.Wait()
        at ConsoleApp1.Program.Main(String[] args) in C:\Users\alexn\Desktop\Temptemptemp\ConsoleApp1\Program.cs:line 18

        This exception was originally thrown at this call stack:
            [External Code]

        Inner Exception 1:
        ConnectionClosedException: Connection 'ES-7d6611ec-c9cd-4ad4-9a6d-8e3020afe2db' was closed.

Video: https://www.youtube.com/watch?v=ttbZesy7GuM

Please let me know if I'm missing something obvious.

**Comment by kpfaulkner** [comment]
Just to update here... I've totally given up on secured TCP for 20.06. Switched to gRPC and it was about 1 minutes work (vs the 20+ hours to try and get TCP going). Although we didn't want to switch to gRPC yet I think it's pretty clear that gRPC is the way to go (for us at least).

**Comment by dharmaturtle** [comment]
gRPC is failing for me as well :(

    using EventStore.Client;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Text;
    
    namespace ConsoleApp1 {
      class Program {
        static void Main(string[] args) {
          var eventType = "event-type";
          var data = "{ \"a\":\"2\"}";
          var metadata = "{}";
          var eventPayload = new EventData(Uuid.NewUuid(), eventType, Encoding.UTF8.GetBytes(data), Encoding.UTF8.GetBytes(metadata));
          var settings = new EventStoreClientSettings {
            CreateHttpMessageHandler = () =>
              new HttpClientHandler {
                ServerCertificateCustomValidationCallback =
                  (sender, cert, chain, sslPolicyErrors) => true
              },
            ConnectivitySettings = {
              Address = new Uri("https://localhost:2113")
            }
          };
          var client = new EventStoreClient(settings);
          client.AppendToStreamAsync("new stream", StreamRevision.None, new List<EventData> { eventPayload }).Wait();
        }
      }
    }



    System.AggregateException
    HResult=0x80131500
    Message=One or more errors occurred. (Status(StatusCode=Internal, Detail="Error starting gRPC call: The SSL connection could not be established, see inner exception."))
    Source=System.Private.CoreLib
    StackTrace:
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.Wait()
    at ConsoleApp1.Program.Main(String[] args) in C:\Users\alexn\Desktop\Temptemptemp\ConsoleApp1\Program.cs:line 25

    Inner Exception 1:
    InvalidOperationException: Status(StatusCode=Internal, Detail="Error starting gRPC call: The SSL connection could not be established, see inner exception.")

    Inner Exception 2:
    RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: The SSL connection could not be established, see inner exception.")


There is no inner exception past 2. Getting pretty annoyed with SSL.

**Comment by hayley-jean** [comment]
@dharmaturtle If you are running Event Store with the `--insecure` flag, then that means that SSL is disabled entirely.

For gRPC, you should be able to connect over HTTP, for example:
 ```  
var settings = new EventStoreClientSettings {
    ConnectivitySettings = {
		Address = new Uri("http://localhost:2113")
	}
};
```

For connecting to TCP, you need to enable the external TCP interface in the Event Store configuration first.
You can do this by setting the `--enable-external-tcp` flag on the server. This will also not have SSL when running in Insecure mode.

From there, you can connect with the following:

```
var settings = ConnectionSettings.Create()
    .DisableTls();
var connection = EventStoreConnection.Create(settings, new Uri("tcp://localhost:1113"));
```

**Comment by dharmaturtle** [comment]
Hi @hayley-jean thanks for the attention. Unfortunately, I'm running into issues when trying to implement your advice.

When I try to connect over HTTP, it says

    System.AggregateException
    HResult=0x80131500
    Message=One or more errors occurred. (Status(StatusCode=Internal, Detail="Request protocol 'HTTP/1.1' is not supported."))
    Source=System.Private.CoreLib
    StackTrace:
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.Wait()
    at ConsoleApp1.Program.Main(String[] args) in C:\Users\alexn\Desktop\Temptemptemp\ConsoleApp1\Program.cs:line 22

    Inner Exception 1:
    InvalidOperationException: Status(StatusCode=Internal, Detail="Request protocol 'HTTP/1.1' is not supported.")

    Inner Exception 2:
    RpcException: Status(StatusCode=Internal, Detail="Request protocol 'HTTP/1.1' is not supported.")

When I try `EventStore.ClusterNode.exe --db ./db --log ./logs --insecure --enable-external-tcp` it gives me

    System.AggregateException
    HResult=0x80131500
    Message=One or more errors occurred. (EventStoreConnection 'ES-2678574e-25a1-4e4c-8e69-f2b8694c2062' is not active.)
    Source=System.Private.CoreLib
    StackTrace:
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.Wait()
    at ConsoleApp1.Program.Main(String[] args) in C:\Users\alexn\Desktop\Temptemptemp\ConsoleApp1\Program.cs:line 27

    This exception was originally thrown at this call stack:
        [External Code]

    Inner Exception 1:
    InvalidOperationException: EventStoreConnection 'ES-2678574e-25a1-4e4c-8e69-f2b8694c2062' is not active.

My code:

    using EventStore.Client;
    using EventStore.ClientAPI;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Text;
    
    namespace ConsoleApp1 {
      class Program {
        static void Main(string[] args) {
          var eventType = "event-type";
          var data = "{ \"a\":\"2\"}";
          var metadata = "{}";
    
          var eventPayload = new EventStore.Client.EventData(Uuid.NewUuid(), eventType, Encoding.UTF8.GetBytes(data), Encoding.UTF8.GetBytes(metadata));
          var settings = new EventStoreClientSettings {
            ConnectivitySettings = {
              Address = new Uri("http://localhost:2113")
            }
          };
          var client = new EventStoreClient(settings);
          client.AppendToStreamAsync("new stream", StreamRevision.None, new List<EventStore.Client.EventData> { eventPayload }).Wait();
    
          //var eventPayload = new EventStore.ClientAPI.EventData(Guid.NewGuid(), eventType, true, Encoding.UTF8.GetBytes(data), Encoding.UTF8.GetBytes(metadata));
          //var settings = ConnectionSettings.Create().DisableTls();
          //var connection = EventStoreConnection.Create(settings, new Uri("tcp://localhost:1113"));
          //connection.AppendToStreamAsync("new stream", 0, new List<EventStore.ClientAPI.EventData> { eventPayload }).Wait();
        }
      }
    }

A video demoing the code: https://youtu.be/C-a01l-ggtk

**Comment by ahjohannessen** [comment]
```
<PackageReference Include="EventStore.Client" Version="20.6.1" />
<PackageReference Include="EventStore.Client.Grpc.Streams" Version="20.6.0" />
```
Seems like you are mixing versions.

**Comment by dharmaturtle** [comment]
Hi @ahjohannessen, sadly there doesn't seem to be a 20.6.1 for Grpc.Streams. When I step EventStore.Client back down to 20.6.0, I get the following errors: 

HTTP:

    System.AggregateException
    HResult=0x80131500
    Message=One or more errors occurred. (Status(StatusCode=DeadlineExceeded, Detail=""))
    Source=System.Private.CoreLib
    StackTrace:
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.Wait()
    at ConsoleApp1.Program.Main(String[] args) in C:\Users\alexn\Desktop\Temptemptemp\ConsoleApp1\Program.cs:line 22

    Inner Exception 1:
    RpcException: Status(StatusCode=DeadlineExceeded, Detail="")

TCP:
    System.AggregateException
    HResult=0x80131500
    Message=One or more errors occurred. (EventStoreConnection 'ES-842658c3-1773-4103-9091-76bf386caf37' is not active.)
    Source=System.Private.CoreLib
    StackTrace:
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.Wait()
    at ConsoleApp1.Program.Main(String[] args) in C:\Users\alexn\Desktop\Temptemptemp\ConsoleApp1\Program.cs:line 27

    This exception was originally thrown at this call stack:
        [External Code]

    Inner Exception 1:
    InvalidOperationException: EventStoreConnection 'ES-842658c3-1773-4103-9091-76bf386caf37' is not active.

Note that this is on EventStore v20.06.1 as I can't find the v20.06.1 download and don't feel like building from source.

**Comment by hayley-jean** [comment]
Apologies for the delay, version 20.6.1 of the dotnet gRPC client should be available on nuget shortly in which case your previous gRPC code should work.

With regards to the TCP error, could you ensure that you're calling `client.ConnectAsync()` and awaiting it properly before using the connection?

**Comment by dharmaturtle** [comment]
Thanks @hayley-jean that worked! Both HTTP and TCP work for me now. I'll probably submit a PR to update your docs this weekend.

@kpfaulkner I'm fine with closing this issue if you are.
