### ISSUE TITLE
System.Exception: A TLS Certificate is required unless development mode (--dev) is set.

### ISSUE THREAD

**Issue by p0onage** [EventStore/EventStore#2643]
**Describe the bug**
An instance of the EventStore was running on a Linux machine but I had a looping issue. I uninstalled the Eventstore and attempted to install it again but I get the following error 

 System.Exception: A TLS Certificate is required unless development mode (--dev) is set.

**To Reproduce**
1. Uninstalled Eventstore 
2. Installed Eventstore 
3. Run "sudo systemctl start eventstore"

**Expected behavior**
Start the service

**Actual behavior**
Throws exception

How do I run the Eventstore on Linux passing the dev flag?

**Comment by alexeyzimarev** [comment]
The ways to configure EventStoreDB are described in the docs. v20.6 uses the same methods as v5. You can either set add `Dev=True` to the config file or set the `EVENTSTORE_DEV` environment variable.

**Comment by p0onage** [comment]
Thanks @alexeyzimarev 

Is there anything else I need to do now? for some reason, it's running but when I try and access this on port 2113 externally I can't access it? I'm getting an empty response


eventstore-oss is already the newest version (20.6.0-1).
  Active: active (running) since Wed 2020-08-19 20:02:39 UTC; 42s ago


My config now looks like this 


---
RunProjections: None
ClusterSize: 1
Dev : True

**Comment by alexeyzimarev** [comment]
It's because you are calling it with HTTP (I presume) and 20.6 is only able to use HTTPS.

**Comment by p0onage** [comment]
No that didn't work either tried with Https but I just get ERR_CONNECTION_CLOSED

**Comment by p0onage** [comment]
Issue resolved by adding in 

IntIp: 0.0.0.0
ExtIp: 0.0.0.0

Really appreciate your help @alexeyzimarev thank you

**Comment by SijmenHuizenga** [comment]
For future reference, add the following cli arguments:
```
--int-ip=0.0.0.0 --ext-ip=0.0.0.0
```
