### ISSUE TITLE
CI (containers) steps reporting tests as passed when they failed

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#2644]
The following test run indicates that the tests for `ci/github/build-buster-slim` passed but looking at the logs, they actually failed.

https://github.com/EventStore/EventStore/runs/1003464267?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1062417/90866601-72dd6b80-e394-11ea-8d68-6f2caa209abb.png)

![image](https://user-images.githubusercontent.com/1062417/90866766-a8825480-e394-11ea-8039-d7ab2b547b30.png)

**Comment by oskardudycz** [comment]
This was fixed by changes to CI made by @thefringeninja.
