### ISSUE TITLE
Configure Authentication/Users [eventstore-docker#73]

### ISSUE THREAD

**Issue by arwinneil** [EventStore/EventStore#2649]
## Originally opened by @ghandmann at [eventstore-docker#73](https://github.com/EventStore/eventstore-docker/issues/73)

> Is there a way to configure the default username/password via Environment/Configuration when using EventStore in a container?
> 
> The documentation is giving rather vague information about this.
> 
> I think this would be an important option to change the Admin-User (at least the password) instead of running with well-known default credentials. :)

[See original thread](https://github.com/EventStore/eventstore-docker/issues/73)

**Comment by cflanny** [comment]
Not sure anything is ever going to change with this.  This is how I ended up working around it:
```
    # log into vault
    echo "getting passwords from vault..."
    export VAULT_ADDR=https://vault.domain.test
    export VAULT_TOKEN=$( /opt/bin/vault login -token-only -method=aws header_value=vault.domain.test role=non-production )

    # get admin and ops pwds:
    ADMIN_PW=$( /opt/bin/vault kv get -format json \
        credentials/dev/eventstore/eventstore-admin \
        | jq -r '.data.data.password' )
    OPS_PW=$( /opt/bin/vault kv get -format json \
        credentials/dev/eventstore/eventstore-ops \
        | jq -r '.data.data.password' )
  
    # prep change payloads:
    OPS_PAYLOAD="{\"CurrentPassword\": \"changeit\", \"NewPassword\": \"${OPS_PW}\"}"
    ADMIN_PAYLOAD="{\"CurrentPassword\": \"changeit\", \"NewPassword\": \"${ADMIN_PW}\"}"
    
    # make changes:
    echo "changing ops password..."
    curl -f -k --silent --basic -u 'ops:changeit' \
        -d "${OPS_PAYLOAD}" -H 'Content-Type: application/json' \
        https://eventstore-dev.domain.test/users/ops/command/change-password
    
    echo "changing admin password..."
    curl -f --silent --basic -u 'admin:changeit' \
        -d "${ADMIN_PAYLOAD}" -H 'Content-Type: application/json' \
        https://eventstore-dev.domain.test/users/admin/command/change-password

    #because eventstore 21.10.1 bug with password changes:
    sudo docker restart eventstore_db
```

It's ugly and terrible, but works.  I guess.  Would be far better to be able to provide a password through environment variables like practically all other cloud-native docker images, but what can ya do...

**Comment by alexeyzimarev** [comment]
We have an env var for setting the default password since 23.10
