### ISSUE TITLE
Allow scavenge to be triggered without admin credentials

### ISSUE THREAD

**Issue by rcknight** [EventStore/EventStore#266]
It doesn't really feel right having to store admin credentials in a scavenging cron script. Would be nice if there was some way to create a user that is only allowed to trigger a scavenge, not touch any data.

**Comment by pgermishuys** [comment]
What do you guys think about adding an operations role that only has access to perform operation type actions?

The work involved, see branch https://github.com/EventStore/EventStore/tree/operations-user

**Comment by dnauck** [comment]
+1 @pgermishuys

**Comment by pgermishuys** [comment]
What do you guys think of this @gregoryyoung @jen20 ?

**Comment by jen20** [comment]
I think an ops role is a good idea, and should allow scavenging. :+1:
