### ISSUE TITLE
Structured logging type consistency

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2670]
**Describe the bug**
There are conflicting types in some of EventStoreDB's structured log messages which makes it hard to ship logs to external entities like ElasticSearch which expect consistent types.

**Expected behavior**
The types should be consistent

**Actual behavior**
Types are not always consistent which makes log shipping harder

**EventStore details**
 - EventStore server version: 5.0 and above (since structured logging was introduced)

 - Operating system: All

**Comment by ylorph** [comment]
closing as we move to serilog.
Reopen if something was missed ?
