### ISSUE TITLE
"Failed to retrieve replica stats: Unknown error" on Cluster Status page when using --insecure

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2689]
**Describe the bug**
Cluster status page shows error message on UI on any node when using --insecure

Similar to https://github.com/EventStore/EventStore/issues/2688 but error occurs due to the request being done over `https` instead of `http`

**To Reproduce**
1. Launch a 3 node cluster with --insecure
2. Log in to the UI on any node
3. Go to Cluster Status page
4. The error: "Failed to retrieve replica stats: Unknown error" will be displayed.

Inspecting the network requests shows that the request is being done over `https` instead of `http` and the `ERR_SSL_PROTOCOL_ERROR` is displayed in the console.

**Expected behavior**
No error

**Actual behavior**
Error message displayed

**EventStore details**
 - EventStore server version: `master` (34096c3)

 - Operating system: All

**Comment by bkulyk** [comment]
I am seeing this error quite often. "Failed to retrieve replica stats: Unknown error"

I'm using `eventstore/eventstore:20.6.1-buster-slim` version of the docker image deployed to kubernetes. I am using the `--insecure` flag.

**Comment by hayley-jean** [comment]
Thanks for reporting this @bkulyk, we've updated the UI in the docker image. Could you please try pull it again and see if it's fixed now?

**Comment by bkulyk** [comment]
@hayley-jean Thanks for the update, greatly appreciated. I deployed this to a test cluster and I'm not seeing the error message anymore.
