### ISSUE TITLE
EventStore open at https://127.0.0.1:2113/ port but not open in http://127.0.0.1:2113/ port 

### ISSUE THREAD

**Issue by wangadeketan** [EventStore/EventStore#2697]
Hi,
As per EventStore documentation EventStore open at http port 2113 .When I redirect to this URL http://127.0.0.1:2113/  my browser page throw me 503 response but when I change http to HTTPs it working fine. So anybody explain me why this happen ?

Operating System : Windows 10
Steps :
choco install eventstore-oss
EventStore.ClusterNode.exe --db ./db --log ./logs --dev
then rediret to https://127.0.0.1:2113/ (Admin UI)

**Comment by alexeyzimarev** [comment]
The documentation states that ESDB 20.6+ is secure by default https://developers.eventstore.com/server/20.6/server/installation/#security-considerations
