### ISSUE TITLE
Release new versions

### ISSUE THREAD

**Issue by dnagir** [EventStore/EventStore#2698]
**Is your feature request related to a problem? Please describe.**

We had a problem with a very high latency reading the events which was resolved in [this issue](https://github.com/EventStore/EventStore/pull/2566).

This requres us to upgrade the EventStore from `oss-v20.6.0` to `oss-v20.6.1`.
But there are a couple of problems with that upgrade:

1. There are breaking changes that we should test before the upgrade (even though it is a bugfix release)
2. [Official Docker image](https://hub.docker.com/layers/eventstore/eventstore/latest/images/sha256-3c205b8b853349fb8c0ca4318e64378231cb4a9d177b795410bedc43883db17c) has not been updated so there is no easy way for us to test it.
3. The new version of the Ubuntu package does not seem to be published.

**Describe the solution you'd like**

1. Be more accurate with versioning when breaking changes occur (maybe bump the major version).
2. Improve the release pipeline:
    - by releasing a new Docker image tagged as `latest` as well as with a specific version (e.g. `oss-v20.6.1`); these has already been requested [at least a few time](https://github.com/EventStore/EventStore/issues?q=is%3Aissue+dockerhub+)
    - publishing the Debian package
3. Make it more clear in the documentation what the release process is like (when and how the new versions are released, what guarantees we have for the backwards compatibility, etc).

**Describe alternatives you've considered**

The only alternative at this stage for us is to build the EventStore Docker image as well as the Debian package manually.

**Additional context**

This is a blocking issue for us as a significant delay with handling events is not currently acceptable.
The actual issue is fixed but we are unable to "easily" make use of it at this stage.

We would like your guidance on whether we should do it all manually or wait the EventStore `>=20.6.1` to be released.

**Comment by dnagir** [comment]
Thankfully both Debian package and docker image were released shortly after opening this issue so that at least unblocked us in this particular case.

But a more formal understanding of the process would still be extremely useful, especially around breaking changes.

**Comment by hayley-jean** [comment]
Hi @dnagir, thank you for the feedback

To first address your previous comment about testing changes before they're released, you could test this out in a nightly build. These contain the latest master from the day before and are packaged as zip and deb packages.

You can find them in the Event Store [releases](https://github.com/EventStore/EventStore/releases).

We don't currently have nightly releases being released to docker hub, but this is something we might consider.
For now if you need a docker image, the Event Store repo contains a Dockerfile and a Docker-Compose script which you can use to build and run a single node or a cluster in docker.

A more detailed explanation of the versioning scheme we have adopted can be found [here](https://eventstore.com/blog/new-version-strategy/).

With regards to breaking changes, we do our best to avoid them in minor versions.
Could you please share the changes you are concerned about, and we can see what we can do to help?

**Comment by dnagir** [comment]
> With regards to breaking changes, we do our best to avoid them in minor versions.
> Could you please share the changes you are concerned about, and we can see what we can do to help?

The [patch upgrade](https://eventstore.com/blog/event-store-5.0.2-release/) held us a bit of a hostage as it introduced a number of breaking changes. This was not major and not even minor - it was a patch release.

More recently, the [20.6.1](https://github.com/EventStore/EventStore/blob/8dfd026668be6e3e08f04ec45c03ff3f835c94ca/CHANGELOG.md#2061---2020-09-28) had a few breaking changes too.


Hopefully, this can be refined in the future.

**Comment by ylorph** [comment]
The versions number are _not_ using semantic versioning.
And yes , while we do our best to avoid breaking changes, they can occure between releases of the same major.minor versions
