### ISSUE TITLE
GRPC client in .NET 5 run against 20.6.1 in insecure mode fails with "Request protocol 'HTTP/1.1' is not supported."

### ISSUE THREAD

**Issue by Euphoric** [EventStore/EventStore#2707]
**To Reproduce**

1. Run Event Store 20.6.1 with --insecure flag
2. Use Grpc client with TLS dissabled in application running in .NET 5

Code to reproduce: https://github.com/Euphoric/EventStoreHttpError

**Expected behavior**
Works correctly.

**Actual behavior**
Throws exception with "Request protocol 'HTTP/1.1' is not supported."

**EventStore details**
 - EventStore server version: 20.6.1

 - Operating system: Windows

 - EventStore client version (if applicable): 20.6.1 in .NET 5 (5.0.100-rc.1.20452.10)

**Additional context**
Works when run against 20.6.0 in Dev mode with TLS.
Works when run in .NET Core 3.1 against 20.6.1

I haven't found any mentions of .NET 5 breaking backwards compatibility of GRPC.

**Comment by Euphoric** [comment]
I have verified this error doesn't happen when running against 20.6.1 with TLS enabled. So there must be something weird with the insecure mode.

**Comment by shaan1337** [comment]
@Euphoric thanks for the report. 

It is possible that the application is not setting the HTTP/2 prior knowledge mode properly.
Could you please try to set the following at the beginning of your main function and let us know if it works?
```
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```

**Comment by Euphoric** [comment]
@shaan1337 Setting that doesn't change the behavior.

**Comment by jamiewinder** [comment]
I've just encountered this myself. Has anyone been able to figure out a workaround?

**Comment by Euphoric** [comment]
I confirm that updating Grpc.Net.Client to 2.32.0 fixed this problem.

**Comment by mat-mcloughlin** [comment]
Just ran into this myself
