### ISSUE TITLE
Include EventId in event consumes by projections

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#2714]
**Is your feature request related to a problem? Please describe.**
I have a projection used for building enriched events. I would like to include the Event id inside the enriched events

**Describe the solution you'd like**
Inside the event consumed by the projection, included the Eventid property (which is included on a ResolvedEvent)

```
$any : function(s,e){
    s.EventId = e.EventId; //I want access to this.
}
```

**Describe alternatives you've considered**
Create a new EventId property on each of my events, which is a copy of the eventId already being persisted.

**Comment by hayley-jean** [comment]
Fixed by #2928
