### ISSUE TITLE
RDALL command on TestClient is broken

### ISSUE THREAD

**Issue by Lougarou** [EventStore/EventStore#2715]
**Describe the bug**
RDALL command on TestClient is broken. 

**To Reproduce**
1. Launch EventStoreDB (any v4.x, v5.x and v20.6.x)
2. ./testclient --command "RDALL"

**Expected behavior**
Reads forward from $all stream.

**Actual behavior**
Error during execution of command: Unexpected TCP package: ReadAllEventsForwardCompleted..

**EventStore details**
 - EventStore server version: any v4.x, v5.x and v20.6.x
 - Operating system: any

**Comment by hayley-jean** [comment]
Fixed by https://github.com/EventStore/EventStore/pull/2892
