### ISSUE TITLE
Fix CustomHttpClient in v5.0.9 client connection string

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore#2716]
The `CustomHttpClient` in the v5.0.9 connection string currently has no effect.

This is due to the fact that `CustomHttpClient` is a property on the ConnectionSettings, but the connection string requires it to be a field. (See [here](https://github.com/EventStore/EventStore/pull/2553/files#r440732273))

As a current workaround, set the CustomHttpClient in the ConnectionSettings as follows:

```csharp
_settings = ConnectionSettings.Create()
    .UseCustomHttpClient(
        new HttpAsyncClient(TimeSpan.FromMilliseconds(1000),
            new HttpClientHandler {
                ServerCertificateCustomValidationCallback = delegate { return true; }
            }))
```

**Comment by megakid** [comment]
It seems this was actually changed in #2585 so isn't a bug.
