### ISSUE TITLE
When AdvertiseHostToClientAs is set, the UI still redirects to the ExtHostAdvertiseAs hostname

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/EventStore#2722]
Although clients seem to be able to connect to the cluster using the `AdvertiseHostToClientAs` option when internal and external hostnames don't match, there is still an issue related to the setup in the Admin UI.

When opening the node UI using the `AdvertiseHostToClientAs` hostname, the UI redirects to the hostname set by `ExtHostAdvertiseAs`. It is still possible to reach the UI using the direct link `https://[AdvertiseHostToClientAs]:[AdvertiseHttpPortToClientAs]/web/index.html`

**Comment by alexeyzimarev** [comment]
It happens here: https://github.com/EventStore/EventStore/blob/c0c32714ebe5d686898942b5d08fe9894c38c6ef/src/EventStore.Core/Services/Transport/Http/Controllers/ClusterWebUIController.cs#L59

The issue can't be really fixed by sending `AdvertiseHostToClientAs` and port to the `KestrelHttpService` constructor since it will break the internal communication (I guess).

Only those redirects need to have a different target to fix the issue.

https://github.com/EventStore/EventStore/blob/c0c32714ebe5d686898942b5d08fe9894c38c6ef/src/EventStore.Core/Services/Transport/Http/Controllers/ClusterWebUIController.cs#L28-L29

**Comment by shaan1337** [comment]
Note related to this issue: The projections page does not work well when accessing the UI directly at /web/index.html. It uses the `ExtHostAdvertiseAs` host as base URL to make API calls.

**Comment by hayley-jean** [comment]
This should have been fixed by https://github.com/EventStore/EventStore/pull/3224
