### ISSUE TITLE
Grpc & WebUI only on Follower Node: Failed authorization check for "(anonymous)"

### ISSUE THREAD

**Issue by Reris** [EventStore/EventStore#2723]
**Describe the bug**
Hi, I'm currently using 2020.6.1 with a clustered configuration.
Whenever I try to use a NodePreference.Random or, due to the LoadBalancer, access the WebUI, there is a chance to get this a Failed Authentication error solely on the follower node.

Server Log:
```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at EventStore.Core.Services.Transport.Http.AuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in /build/src/EventStore.Core/Services/Transport/Http/AuthenticationMiddleware.cs:line 24
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[    1,23,16:33:29.795,ERR] Connection id ""0HM3E61EN73TK"", Request id ""0HM3E61EN73TK:00000F73"": An unhandled exception was thrown by the application.
```

**To Reproduce**
1. Create a cluster with at least 2 nodes. Try one of the following scenarios:
2. Configure the Client to NodePreference.Random or Follower
3. Try one of the following scenarios:
3.a. Open the WebUI, Hard hit F5 repetitive to abort a currently running request (HttpContext-Cancellation)
3.b. Write to a stream via Grpc
3.c. Create a Stream-Subscription

**Expected behavior**
A WebUI-refresh keeps me logged in.
A Write (AppendToStreamAsync), Subscribe (SubscribeToStreamAsync) is possible on a follower node.
If an error occurs in subscribe, the subscriptionDropped-Action gets called.

**Actual behavior**
A WebUI-refresh has a growing chance per node to cause a logout.
A Write (AppendToStreamAsync), Subscribe (SubscribeToStreamAsync) fails with an (anonymous) authentication on the follower node, even tough an authentication is provided.
If an error occurs in subscribe, the subscriptionDropped-Action is ignored, Theres only a client side log message:
```
Grpc.Net.Client.Internal.GrpcCall|Call failed with gRPC error status. Status code: 'Cancelled', Message: 'gRPC call disposed.'.
```

**EventStore details**
 - EventStore server version: 2020.6.1-buster-slim

 - Operating system: Kubernetes 1.18.8, dockerhub 2020.6.1-buster-slim

 - EventStore client version (if applicable): nuget Grpc.Streams 2020.6.1

**Comment by Reris** [comment]
Okay, there seems to be an intersection with another behavior:
SubscribeToStreamAsync runs on the follower-node. The Status 'Cancelled' seems to be related to the **OperationTimeout**. If  I use _OperationTimeout=-1_ (Infinite) it works.
Nonetheless, it doesnt call the **subscriptionDropped**-Action

**Comment by oskardudycz** [comment]
@Reris that should be fixed in the newer LTS versions. Could you check with the latest one `21.10.1`?
