### ISSUE TITLE
GRPC: No way to (easily) find one time projection name

### ISSUE THREAD

**Issue by George-Payne** [EventStore/EventStore#2733]
**Describe the bug**
Creating a one time projection:

``` proto
message CreateReq {
  Options {
    mode {
      one_time = Empty();
    }
    query = '';
  }
}
```
Returns a 

``` proto
message CreateResp {
}
```

with no details. As I can't specify a name, and it isnt returned to me, I have no way of requesting statistics for this projection.

**Expected behavior**
Allow a name to be specified, or return the given name in `CreateResp`

**EventStore details**
 - EventStore server version: `2.6.1`

**Comment by ylorph** [comment]
closing as support for one time projection is being removed in the GRPC based api
