### ISSUE TITLE
How to fix a faulty $by_event_type system projection

### ISSUE THREAD

**Issue by razvanz** [EventStore/EventStore#2740]
![faulty-projection](https://user-images.githubusercontent.com/3844203/97974357-be19ee80-1dc7-11eb-821c-e1d43453542f.png)

We managed to break the $by_event_type system projection (in the production system) by emitting an event to a `$et-*` stream. Besides the obvious fact that we need a better development practive, now we're trying to get this fixed.

Having looked over the documentation and the issues here, I couldn't find any information that could shed some light over how to get it working.

Having tried various things it a sandbox env, it seems that resetting the projection fixes the issue but it causes re-emission of events to `$et-*`, something we like to avoid.

Is there a way for the projection skip past the emitted event or to ignore it?

**Comment by alexeyzimarev** [comment]
I think such things are better addressed via support (if you are a customer) or [Discuss](https://discuss.eventstore.com)

**Comment by razvanz** [comment]
> I think such things are better addressed via support (if you are a customer) or [Discuss](https://discuss.eventstore.com)

Unfortunately, we're not a support customer. I'll try Discuss.
