### ISSUE TITLE
V5: Empty configuration throws an index out of range error

### ISSUE THREAD

**Issue by Lougarou** [EventStore/EventStore#2743]
**Describe the bug**
When EventStore v5.0.8 is run with an empty configuration file, it throws the following error.
Unhandled exception while starting application:
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

**To Reproduce**
1. Create an empty file e.g. empty.conf
2. Run Eventstore with the configuration file"./eventstored --config empty.conf"
3. This should throw the index was out of range exception mentioned above.

**Expected behavior**
No error should be thrown.

**Actual behavior**
Unhandled exception while starting application:
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

**Config/Logs/Screenshots**
None

**EventStore details**
 - EventStore server version: 5.0.8

 - Operating system: MacOS

 - EventStore client version (if applicable): None

**Additional context**
Can be worked around with a simple config like RunProjections: None

**Comment by oskardudycz** [comment]
This was fixed in 21.10. @hayley-jean tested and it works for empty file now.
