### ISSUE TITLE
maxAge/maxCount breaks new projections/queries once stream grows to a certain point

### ISSUE THREAD

**Issue by FeepingCreature** [EventStore/EventStore#2750]
**Describe the bug**

When a stream is configured with `$maxAge` or `$maxCount`, and a moderate amount of (large) events is pumped into the stream, it becomes impossible to create new projections that read the stream, or run queries on the stream.

This issue exists in at least 5.0.0, 5.0.9 and 20.6.1.

**To Reproduce**

1. Start a fresh EventStore container: `docker run --rm -p 2113:2113 eventstore/eventstore:20.6.1-buster-slim --insecure --run-projections=all --enable-atom-pub-over-http`
2. Use [send_events.sh](https://gist.github.com/FeepingCreature/2717a8e9a544ce869e8ccecebb1d8512) as such: `./send_events.sh 120` to publish 120 big events to `MyStream`.\
This also sets `$maxCount` to 10.
3. Run a query [query.js](https://gist.github.com/FeepingCreature/71cc8dfcd742f8f17a767d18a7942d5a) to confirm that queries work - it should output "10" due to `$maxCount`.
4. Publish one further event to `MyStream` with `./send_events.sh 1`.
5. Rerun the query. Note that it produces no output.

**Expected behavior**
The query should output a state object with `{count: 10}`.

**Actual behavior**
It doesn't.

**EventStore details**
 - EventStore server version: 5.x and 20.6.1.

 - Operating system: Host Ubuntu 20.08/Docker image based on Debian Buster Slim

 - EventStore client version (if applicable): REST API, but we've seen it happen on the TCP API too.

**Comment by StevenBlair123** [comment]
I think we are seeing something similar.
We have one stream with maxAge set and as soon as we try to create a projection reading this, nothing happens (no events read)

Some extra information:

- I don't think maxAge itself is causing it directly. If I hit Delete on a stream from the UI, we see the same behavior
- If you leave the projection long enough, it bursts into life (could be hours depending on the truncated stream size).
- It's almost like it still do <something> with all the deleted events (or linkTos)
- I have even tried running scavenge, but no difference
- On my new projection, if I remove the truncated stream, the projection immediately bursts into life.
- 

In my example, the stream which was **not** truncated has older events than the truncated stream, so  would have expected to start processing events from here, even if there was some other issue going on with the truncated stream

**Comment by hayley-jean** [comment]
This was fixed by https://github.com/EventStore/EventStore/pull/2979
The fix is in both 20.10.4 and 21.10.0.
