### ISSUE TITLE
Events missing in system projection after projection subsystem stopped working

### ISSUE THREAD

**Issue by stefanzueger** [EventStore/EventStore#2763]
**Describe the bug**
From time to time the projection subsystem stops working with the message: 

`PROJECTIONS SUBSYSTEM: Not stopping because subsystem is not in a started state. Current Subsystem state: Stopping`

When this happens we can only fix the behavior with a complete restart of the node (https://github.com/EventStore/EventStore/issues/2687)

After the system projections are started again we are missing all events that happened during the downtime of the projection subsystem in the system projections (e.g. $by_category)

As you see in the image below there is a gap between 2020-12-03 and 2020-12-22
![image](https://user-images.githubusercontent.com/2462052/102971312-737c3f00-44f9-11eb-9d1b-35cbaa360236.png)

If we navigate to the stream with the id config-c348ce1a-8c5f-4b4a-bac4-18d368065e8d then we see that there was an event at the 2020-12-07 that got persistet in the stream but is not visible in the system projection $ce-config
![image](https://user-images.githubusercontent.com/2462052/102971487-c655f680-44f9-11eb-98ee-ed8e4d72afd3.png)

**Expected behavior**
Every event that happened in a stream is also visible in the system projection $by_category

**Actual behavior**
The $by_category projection is missing all events that happened during the "Stopping" state of the projection subsystem.

**EventStore details**
 - EventStore server version: 20.6.1

 - Operating system: Ubuntu 16.04.7 LTS

**Comment by hayley-jean** [comment]
Hi @stefanzueger, thank you for reporting this

Could you tell us what is causing the projection subsystem to stop before you see this issue?
Is the leader node being restarted, or is the leader being resigned?

**Comment by stefanzueger** [comment]
Hi @hayley-jean 

It is not fully clear what's causing the projections to stop. 

In PROD it happened at the same time as the scavenger was running on the leader node and was scavenging a very large index table (> 140gb). I know this is probably not the best idea to scavenge on the leader but we need the scavenger constantly running, otherwise we are running out of disk space pretty fast.

On TEST we had the same issue, however, there the scavenger wasn't running and the data volume is pretty small.

**Comment by hayley-jean** [comment]
This should be fixed by https://github.com/EventStore/EventStore/pull/3233

**Comment by oskardudycz** [comment]
@stefanzueger, could you check version `21.10.1`? The fix is included there. I'm going to close this issue, but if you find out that's still the case, I'll reopen it.
