### ISSUE TITLE
Installation fails on Ubuntu Groovy (20.10)

### ISSUE THREAD

**Issue by lamafab** [EventStore/EventStore#2765]
# Problem

The [`script.deb.sh`](https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/script.deb.sh) script which is shown in the [20.10.0 Release Notes](https://www.eventstore.com/blog/20.10.0-release-notes) fails when `lsb_release -c | cut -f2` returns `groovy`. Within the script, the variable `apt_config_url` is constructed as follows:

```
apt_config_url="https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/config_file.list?os=${os}&dist=${dist}&source=script"
```

Which results in:

https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/config_file.list?os=ubuntu&dist=groovy&source=script

This URL returns a 404.

# Expected behavior

The constructed URL as seen above should resolve correctly (one should be able to download the `config_file.list` file).

# Workaround

Overwrite the value `${dist}` in `apt_config_url` to `focal`:

```
apt_config_url="https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/config_file.list?os=${os}&dist=focal&source=script"
```

Which results in a valid link:

https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/config_file.list?os=ubuntu&dist=focal&source=script

**Comment by alexeyzimarev** [comment]
We only release packages for LTS versions of Ubuntu. The latest LTS is 20.4, which is mentioned in the release notes.

The Packagecloud script prints this on the console if it can't find the package:

```
For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh
```

So, running it like this will install the package for 20.4:

```
wget https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/script.deb.sh
chmod +x ./script.deb.sh
sudo os=ubuntu dist=focal ./script.deb.sh
```
