### ISSUE TITLE
Did not find ConnectTo or GossipSeeds in the connection string ...

### ISSUE THREAD

**Issue by jkears** [EventStore/EventStore#2768]
Attempting to connect to 20.10.0. running as a single node on local host.  

At the point of client creation I receive the following exception ...  "Did not find ConnectTo or GossipSeeds in the connection string.  'esdb://127.0.0.1:2113?Tls=false' 

![image](https://user-images.githubusercontent.com/1290937/103245599-aa55b900-492e-11eb-83ad-ff13f2106294.png)

I am following this script from the QuickStart ....

![image](https://user-images.githubusercontent.com/1290937/103245845-76c75e80-492f-11eb-998b-8d625961c7c5.png)

**Comment by alexeyzimarev** [comment]
`EventStoreConnection` is the TCP client. The connection string you mentioned is for the gRPC client.

**Comment by jkears** [comment]
Whops missed that .. this code-base is from older client 5.0.8.
