### ISSUE TITLE
Extension: Translation Adapter Plugin for WebUI

### ISSUE THREAD

**Issue by Zetanova** [EventStore/EventStore#2769]
**Is your feature request related to a problem? Please describe.**
Users can not view binary events over the WebUI

**Describe the solution you'd like**
To add a custom Translation Adapter plugin to the eventstore server 
that will transform events into  human-readable data (json) and send to the WebUI

**Describe alternatives you've considered**
Writing my own WebUI to debug

**Additional context**
It is hard to develop/debug with binary event streams.

**Comment by alexeyzimarev** [comment]
It will a part of schema registry work outside of this repository.
