### ISSUE TITLE
GRPC: Reading out of bounds backwards yields cryptic error

### ISSUE THREAD

**Issue by George-Payne** [EventStore/EventStore#2781]
**Describe the bug**
Reading a stream backwards from out of bounds returns:
`Request message serialization failure: Cannot read property 'lo' of null`

**To Reproduce**
`readStream('somestream', 16, { direction: BACKWARDS, fromRevision: -1n })`

**Expected behavior**
Should return a descriptive error, or an empty success.

**Actual behavior**
`Request message serialization failure: Cannot read property 'lo' of null`

**Config/Logs/Screenshots**

![](https://uploads.linear.app/a2a29b63-594b-4491-8437-5f7f43da2367/3e14644a-8bc8-42df-b643-fe382f366796/20b038ed-27fd-49b3-aa96-c94ff978d917)

**EventStore details**

* EventStore server version: `20.6.2.0`
* Operating system: linux
* EventStore client version (if applicable): node client `alpha.12`

**Additional context**

Original issue: [https://github.com/EventStore/EventStore-Client-NodeJS/issues/117](https://github.com/EventStore/EventStore-Client-NodeJS/issues/117)

> In one of my tests I apparently had it calling `readStream` with out of bounds values, I would expect this to either return an empty array or to at least give a somewhat useful error message.
>
> I called `readStream('somestream', 16, { direction: BACKWARDS, fromRevision: -1n })` and got the error:
>
> ```
> 13 INTERNAL: Request message serialization failure: Cannot read property 'lo' of null
> 
>       at Object.convertToCommandError (../node_modules/@eventstore/db-client/dist/utils/CommandError.js:281:12)
>       at ClientReadableStreamImpl.<anonymous> (../node_modules/@eventstore/db-client/dist/utils/handleBatchRead.js:27:38)
>       at Object.onReceiveStatus (../node_modules/@grpc/grpc-js/src/client.ts:570:18)
>       at Object.onReceiveStatus (../node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
>       at ../node_modules/@grpc/grpc-js/src/call-stream.ts:243:24
> ```
>
> If it matters, the stream did already have several elements in it.
>
> I would not say this is a bug *per se*, but the way it broke makes me wonder if there could be some other edge cases?
>
> This was tested with alpha 12.

<sub>[DB-94](https://linear.app/eventstore/issue/DB-94/grpc-reading-out-of-bounds-backwards-yields-cryptic-error)</sub>

**Comment by ylorph** [comment]
@hayley-jean : this is probably fixed already

**Comment by George-Payne** [comment]
@ylorph Still present on ci docker image.

`out-of-bounds.mjs`

```
import {
  BACKWARDS,
  EventStoreDBClient,
  jsonEvent,
} from "@eventstore/db-client";

const client = EventStoreDBClient.connectionString`
    esdb://localhost:2113?tls=false
`;

await client.appendToStream("somestream", [
  jsonEvent({
    type: "an-event",
    data: {},
  }),
]);

try {
  for await (const event of client.readStream("somestream", {
    maxCount: 16,
    direction: BACKWARDS,
    fromRevision: -1n,
  })) {
    console.log("event", event);
  }
} catch (error) {
  console.log(error);
}
```

```
docker run --env "HOME=/tmp" --rm -p 2113:2113 ghcr.io/eventstore/eventstore:ci --dev --insecure
```

```
node out_of_bounds.mjs
UnknownError: 13 INTERNAL: Request message serialization failure: Cannot read properties of null (reading 'lo')
    at convertToCommandError (/home/george/dev/temp/err-51/node_modules/@eventstore/db-client/dist/utils/CommandError.js:357:12)
    at ClientReadableStreamImpl.<anonymous> (/home/george/dev/temp/err-51/node_modules/@eventstore/db-client/dist/streams/utils/ReadStream.js:30:69)
    at ClientReadableStreamImpl.emit (node:events:525:35)
    at Object.onReceiveStatus (/home/george/dev/temp/err-51/node_modules/@grpc/grpc-js/build/src/client.js:331:28)
    at Object.onReceiveStatus (/home/george/dev/temp/err-51/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /home/george/dev/temp/err-51/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 13,
  _raw: Error: 13 INTERNAL: Request message serialization failure: Cannot read properties of null (reading 'lo')
      at Object.callErrorFromStatus (/home/george/dev/temp/err-51/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
      at Object.onReceiveStatus (/home/george/dev/temp/err-51/node_modules/@grpc/grpc-js/build/src/client.js:331:49)
      at Object.onReceiveStatus (/home/george/dev/temp/err-51/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
      at /home/george/dev/temp/err-51/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
    code: 13,
    details: "Request message serialization failure: Cannot read properties of null (reading 'lo')",
    metadata: Metadata { internalRepr: Map(0) {}, options: {} }
  },
  type: 'unknown'
}

```
