### ISSUE TITLE
Antivirus detects recent versions of EventStore.ClusterNode.exe as malware

### ISSUE THREAD

**Issue by jpsv** [EventStore/EventStore#2799]
**Describe the bug**
For my users, Bitdefender detects v20.6.0, 20.6.1, and 20.10.0 of EventStore.ClusterNode.exe as malware of type Gen:Variant.Bulz.297066

I've submitted version 20.10.0 to Bitdefender labs and hopefully that takes care of the issue. I thought the false positive would go away for my users with a new version so I used a file hash to exclude it but the false positive persists with newer versions.

**To Reproduce**
1. Use Bitdefender on Windows
2. Download the latest EventStore
3. Extract it
4. Bitdefender should detect it as type Gen:Variant.Bulz.297066

**Expected behavior**
Ideally, nothing, and the file remains.

**Actual behavior**
Bitdefender heuristics detects and quarantines the file.

**EventStore details**
 - EventStore server version: v20.6.0, 20.6.1, and 20.10.0

 - Operating system: Windows 10

**Comment by mat-mcloughlin** [comment]
Hey @jpsv. We added process to our QA build to check EventStoreDB doesn't cause a problem with anti virus, from version 21.6. Just checking to see if this is still a problem for you with later versions of the server?

**Comment by jpsv** [comment]
@mat-mcloughlin I haven't verified it yet but I haven't heard any complaints about it lately either

**Comment by oskardudycz** [comment]
@jpsv thanks for giving the heads-up, I'll close it then. If you noticed that again, please send us info and we'll check it.
