### ISSUE TITLE
TCP client: Allow DNS discovery with --insecure on v20+

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2802]
Thanks to @arwinneil for originally noticing this scenario.

The `CompatibilityMode` option (formerly `SetLegacyGossipDiscovery()`) (see #2796) allows the v20 TCP client to gossip over plain HTTP to be able to connect to a v5 cluster. 

However, v20+ servers also now support `--insecure` and gossip is done over plain HTTP.

Creating gossip seeds manually is OK since the `SetGossipSeedEndPoints()` already has a boolean parameter: `tlsTerminatedEndpoints`:
`SetGossipSeedEndPoints(bool tlsTerminatedEndpoints, params EndPoint[] gossipSeeds)`

But DNS discovery doesn't. Should an option be introduced on the cluster settings builder (along with corresponding connection string parameter) to cater for this scenario?

**Comment by megakid** [comment]
This could very easily be added to the auto compatibility mode - it might already work (?)

**Comment by YoEight** [comment]
Yes, it is! All you need is to set compatibility mode to `auto`. V20 in insecure mode is basically a V4/V5 server.
