### ISSUE TITLE
Allow disabling TLS in v5 client

### ISSUE THREAD

**Issue by colmprunty** [EventStore/EventStore#2805]
Apologies if this is already possible, but I only seem to be able to find it in the v20 client.

**Describe the solution you'd like**
Basically [this](https://github.com/EventStore/EventStore/blob/master/src/EventStore.ClientAPI/ConnectionSettingsBuilder.cs#L257) but in the .v5 client. Happy to PR if it would be accepted.

**Describe alternatives you've considered**
I would have to convice my workplace to add a certificate to production EVS.

**Comment by hayley-jean** [comment]
Hi @colmprunty, TLS is disabled by default in the v5 client and would need to be explicitly enabled by specifying the [UseSslConnection](https://github.com/EventStore/EventStore/blob/v5-master/src/EventStore.ClientAPI/ConnectionSettingsBuilder.cs#L254) option.

If you are connecting to a v20+ node, you can disable external TCP TLS on the server with the `DisableExternalTcpTls` option, or run the server in `Insecure` mode.
