### ISSUE TITLE
Having trouble connecting to GES 6 with older code

### ISSUE THREAD

**Issue by jrouaix** [EventStore/EventStore#2806]
Hello folks,

We use the EventStore client lib since a long time now, but we have trouble to upgrade the latests and greatests ...
Trying to update all :
- our old code (using `5.0.9` version of the client) can talk to EventStore 6 (latest)
- then updating to version `20.10.0` of the client and nothing works anymore.

Here are my EVENTSTORE config (i'm on windows 10 here, same behavior in a docker on windows version)
```cmd
set EVENTSTORE_CLUSTER_SIZE=1
set EVENTSTORE_RUN_PROJECTIONS=All
set EVENTSTORE_START_STANDARD_PROJECTIONS=true
set EVENTSTORE_HTTP_PORT=2114
set EVENTSTORE_INT_TCP_PORT=1111
set EVENTSTORE_EXT_TCP_PORT=1112
set EVENTSTORE_INSECURE=true
set EVENTSTORE_ENABLE_HISTOGRAMS=true
set EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
set EVENTSTORE_ENABLE_EXTERNAL_TCP=(true/false) <= //// Tried both

EventStore.ClusterNode.exe
```

Here is the code : 
```csharp
        [Fact]
        public async Task CheckAsync_ConnectionHolder()
        {
            var str = "ConnectTo=tcp://localhost:1112; HeartBeatTimeout=1500; VerboseLogging=false; OperationTimeout=60000;";
            var con = EventStoreConnection.Create(str, "test");
            await con.ConnectAsync();
            var ok = await con.ReadStreamEventsBackwardAsync("$all", StreamPosition.End, 1, false);
        }
```

Ending with `EventStore.ClientAPI.Exceptions.ConnectionClosedException : Connection 'test' was closed.` after about 14 secs.
Those tests are running on `netcoreapp3.1` runtime.

What did I miss please ? Should I update all the existing code to the new grpc version of the api ? I think you'd have declared this api `[Obsolete]` if we shouldn't use it .... ?

**Comment by alexeyzimarev** [comment]
The 20.6+ client is secure by default, as the server. So, when connecting to an insecure server, you have to add `UseSslConnection=false` to the connection string.

**Comment by jrouaix** [comment]
Wooow, ok ! it's working. Thank you ! I really did missed it.
Should it be better with an error message a little more `self explanatory` ?

**Comment by alexeyzimarev** [comment]
The thing is that the client just doesn't get to the server if it doesn't know how to talk to it properly. That's why the message is too generic.
