### ISSUE TITLE
Writing event to EventStore projection irreparably breaks it

### ISSUE THREAD

**Issue by TAGC** [EventStore/EventStore#2807]
**Describe the bug**

If you write an event to an EventStore projection, it causes it to fault. There is no apparent way to delete the offending event or to get the projection to skip it. From what I can see, it would require the entire projection to be recreated to fix.

I've had this happen once in a test version of our EventStore instance and, after trying and failing to find a way to fix it (I had to wait for it to be restored from live), prayed that it would never happen in our live system.

Unfortunately a colleague accidentally wrote to a projection. Since we need to regularly manually raise events on various streams to resolve problems as support tickets come in, it was only a matter of time. Why would you even *allow* this to be done through the UI if it does nothing except fault the stream? This projection contains 20 million events, thousands get added each day and the longer this remains unsolved, the more people (out of the thousands that use our system) will start noticing their data becoming out of date.

This was raised as part of #2049 and never fixed, even though it is a critical problem with EventStore and perhaps the worst example of system design that I've ever seen. We're now struggling to recover from this.

**To Reproduce**
1. Go to the EventStore UI
2. Navigate directly to an event on a projection stream e.g. ../web/index.html#/streams/SomeProjection/1
3. Click "Add New Like This"
4. Click "Add" to add the event

**Expected behavior**

There should be no option to add the event directly to the stream, or at the very least a simple way to undo that action.

**Actual behavior**

The projection ends up faulting as soon as it picks up a new event from the underlying stream with the message: "The given checkpoint is invalid. Possible causes might include having written an event to the projection's managed stream. The bad checkpoint: Phase: 0"

**EventStore details**
 - EventStore server version: v4.1.3.0

 - Operating system: Windows 10

**Comment by TAGC** [comment]
For anyone else who inevitably ends up bringing down their production environment, we found the following workflow lets us resolve the issue until the developers can find the time to add the three lines of JavaScript it'd take to disable the "add event" button on projection event streams.

In our case, the faulting projection was `SO_CommissionsOrderEvents_V2`, which uses the underlying event stream `$ce-SO_Order`.

1. Open the projection event stream. The erroneous event should appear at the top. 

![image](https://user-images.githubusercontent.com/1588951/106874297-537d9500-66cd-11eb-879b-3faf8fbcea12.png)

2. The event preceding this will be the last processed event. Use the timestamp and name of that event to locate it in the underlying event stream. In this case, we would try to find the event `68@SO_Order-8439150` in `$ce-SO_Order`.

![image](https://user-images.githubusercontent.com/1588951/106874550-98093080-66cd-11eb-98ee-d76a7a3d2eb5.png)

3. Take a note of the event number of this event in the underlying stream.

4. Stop the projection.

5. Reset the projection. This will reset the “Position” and “Last checkpoint” values to -1.

![image](https://user-images.githubusercontent.com/1588951/106874757-dbfc3580-66cd-11eb-8dae-fc9cd28a0237.png)

6. Start the projection and let it run for a very short amount of time to allow it to start processing the first few events, and then stop it again. Ensure the “Position” and “Last checkpoint” values are no longer -1.

![image](https://user-images.githubusercontent.com/1588951/106874831-f0d8c900-66cd-11eb-9b77-7fe6362853f4.png)

7. Open the checkpoint stream for the projection (`$projections-SO_CommissionsOrderEvents_V2-checkpoint`). There should be two events in this stream, and the `$ce-SO_Order` value on the most recent event should match the “Last checkpoint” value from the previous step. 

![image](https://user-images.githubusercontent.com/1588951/106875037-22519480-66ce-11eb-9c1a-513504491b03.png)

8. Click the name of the most recent event and then click “Add New Like This”. Set the $ce-SO_Order value in the metadata to be the event number of the last successfully processed event from $ce-SO_Order that was determined in step 3.

![image](https://user-images.githubusercontent.com/1588951/106875091-309fb080-66ce-11eb-872d-dd37b4d5592a.png)

9. Click “Add” to add the event.

10. Go back to the projection status screen and start it. You should see that it is no longer faulted and the “Position” and “Last checkpoint” values have updated to reflect the value that you entered in the checkpoint event.

![image](https://user-images.githubusercontent.com/1588951/106875167-44e3ad80-66ce-11eb-8112-9695cd58b347.png)

---

If you store subscription checkpoints in a database and use that to let an application know where to begin processing events from, you'll need to go to the projection event stream and navigate through the events until you find the cut-off between the old events (that got reprocessed during step 6) and the recent events, and update the subscription checkpoint to be the event number of the last old event that got processed: 22124042.

![image](https://user-images.githubusercontent.com/1588951/106875239-5af16e00-66ce-11eb-9772-54ff6332ce61.png)

**Comment by alexeyzimarev** [comment]
@TAGC Great job with the workaround, thanks for sharing.

Still, like I mentioned under your comment, for urgent production issues it's better to open a support ticket.

You can also always contribute to this repository and help others to avoid this issue. There's no need to shame and blame in GitHub issues.

**Comment by alexeyzimarev** [comment]
Closing in favour of #3149 as it describes better what needs to be done
