### ISSUE TITLE
Investigate live health check

### ISSUE THREAD

**Issue by pvanbuijtene** [EventStore/EventStore#2810]
Tests of the Go client were [randomly failing](https://github.com/EventStore/EventStore-Client-Go/issues/20) on the first request after creating the test container. After some testing this was resolved by using the HTTP result of the login page instead of the `/health/live` health check which indicates the health check is not 100% accurate.

**Steps to reproduce the behavior:**
1. Checkout out the code from https://github.com/EventStore/EventStore-Client-Go/commit/2eb2093c81973898dd62ece7fec2ffbac792a03b or earlier.
2. Run the test cases a few times.
3. A timeout will appear similar as the failing [CI build](https://github.com/EventStore/EventStore-Client-Go/runs/1374996163).

**Expected behavior**
Non flaky test results.

**Actual behavior**
Flaky test results.

**Comment by oskardudycz** [comment]
@pvanbuijtene, it might be worth checking it after the fix to Healthcheck I made in: https://github.com/EventStore/TrainStation/pull/118.
