### ISSUE TITLE
Cluster config v20.x

### ISSUE THREAD

**Issue by astorath** [EventStore/EventStore#2814]
I don't get how v20.10 clusters are supposed to work with `EnableTrustedAuth`.

1. To `EnableTrustedAuth` I need an http proxy.
2. v20.10 does no allow to publish http on 127.0.0.1 and tcp on 0.0.0.0 - theres no option for that now.
3. Gossip is working over http, so (a) http interface has to be public (published on external interface), (b) it has to be directly connected (for tls auth to work).

So, I see no option to use a proxy securely. Is it a design flow, or I miss something?

**Comment by alexeyzimarev** [comment]
Cluster members as well as clients gossip internally via HTTP/gRPC gossip endpoints, and it was like this in the previous versions too (without gRPC of course). It makes binding HTTP interface to the loopback address pointless, as the gossip won't work at all. I am not sure how it could've worked in v5, for example, as it also uses HTTP gossip endpoint.

When it comes to exposing HTTP externally, it doesn't have to be a direct connection. `AdvertiseXXXToClientAs` settings let you override hostnames on which cluster members are exposed to clients. I am not sure how SSL connections will be handled by a proxy server, but I'd expect it to work if the proxy server would have the same certificate as the cluster nodes, and the certificate would also include the proxy server IP address and hostname it SAN. If you use wildcard certificates, it is not needed, but you need to [configure cluster members](https://developers.eventstore.com/server/v20/server/security/configuration.html#certificates-configuration) to accept the certificate common name accordingly. This configuration is required when using the wildcard certificates anyway.

**Comment by alexeyzimarev** [comment]
In addition, I would recommend to address such questions on our [Discuss community forum](https://discuss.eventstore.com) rather than creating an issue.
