### ISSUE TITLE
Events missing in category projection

### ISSUE THREAD

**Issue by prolic** [EventStore/EventStore#2828]
The `$by_category` projection is missing events. I could reproduce this with a fresh instance of 20.10.0-bionic.

There are no streams deleted, I post 2 screenshots here. The first shows all events in $ce-advertiser_call_campaign (this stream is created by `$by_category` projection). The second shows all events of a specific advertiser_call_campaign stream with one more event in there, than in the `$ce-advertiser_call_campaign` stream.

 - EventStore server version: 20.10.0-bionic in docker

 - Operating system: Ubuntu 19.10
 
![Screenshot_20210301_172031](https://user-images.githubusercontent.com/394428/109554069-88a1bb00-7ab2-11eb-8801-5f07311e6175.png)
![Screenshot_20210301_172047](https://user-images.githubusercontent.com/394428/109554077-8b9cab80-7ab2-11eb-9b2c-3e378f26e43a.png)

**Comment by prolic** [comment]
Server logs here https://pastebin.com/GfU7WNqb

**Comment by YoEight** [comment]
Do you also confirm you are missing events when consuming that stream using either a TCP or a gRPC client?

Could you share `$by_category` projection stats?

**Comment by YoEight** [comment]
When looking at your logs:
```
"EventStore.Projections.Core.Messaging.UnwrapEnvelopeMessage" in queued handler '"Projection Core #0"'.
[36meventstore_1                      |[0m System.Exception: Invalid JSON
```

Could you confirm that the event that is missing doesn't have a valid JSON payload?

**Comment by prolic** [comment]
I am not seeing this event when using TCP client.

Attached you'll find screenshots for the other things.

![Screenshot_20210301_183750](https://user-images.githubusercontent.com/394428/109562746-8db83780-7abd-11eb-8737-f192a8b4add3.png)
![Screenshot_20210301_183733](https://user-images.githubusercontent.com/394428/109562748-8e50ce00-7abd-11eb-8ca8-4ff9594d45af.png)
![Screenshot_20210301_183924](https://user-images.githubusercontent.com/394428/109562741-8d1fa100-7abd-11eb-9f8d-14529cb4e3c1.png)

**Comment by hayley-jean** [comment]
@prolic would you be able to try this on v21.2.0 and see if you get the same behaviour?

**Comment by Zetanova** [comment]
I upgraded no from 5.0.9 to 21.2 and i am getting an related issue

A custom projection that worked before, does no only link partialy events to the projection stream.

Events that have Json Data are successfuly linked
But Events with Empty Data (Byte[0], String.Empty) are just missing in the projection.

**Comment by alexeyzimarev** [comment]
We had a related issue @Zetanova, it should've been probably noted as a breaking change. A null string is not a valid JSON. An empty JSON object should be used instead, `{}`.

**Comment by Zetanova** [comment]
This commits makes added the enforcement
https://github.com/EventStore/EventStore/commit/682cc1d893ff558e62582dd15c56a6d1c0f260b0

**Comment by oskardudycz** [comment]
@Zetanova in the v21.2 content validation for projections were added. From the release notes (https://www.eventstore.com/blog/21.2.0-release-notes).


> We want to make sure that projections are predictable.
>
> To support coming changes, we have added content type validation for projections. This means the following:
>
>- If the event is a json event, then it must have valid non-null json data.
>- If the event is not a json event, then it may have null data.
>- Null metadata is accepted in any scenario.
>
>Events that don’t meet these requirements will be filtered out without erroring the projection.

This change only takes effect either when a projection is created on v21.2.0, or if a projection is stopped and started again. Projections that were created before the upgrade will not enforce content validation.

**Comment by Zetanova** [comment]
@oskardudycz  main issue is that  Raw-Data with Json-Metadata is currently not possible.
Custom projections are very limited without metadata, including correlationId 

Don't realy know why the EventRecord assumes null-json data to be Array.Empty<byte>()
and the projection just silently drops it.

Can the assumption not be made, that a null-json data is equal to an empty json object '{}' ?

**Comment by alexeyzimarev** [comment]
As I previously mentioned, the valid empty json is an object `{}`.

**Comment by Zetanova** [comment]
https://tools.ietf.org/html/rfc7159

json-text = ws value ws 

Following string would be valid json:
`null`
`{}`
`[]`
`0`
`false`
`""`

**Comment by Zetanova** [comment]
only json-array and json-object is currently supported as valid json-data

 Valid json-data-values: null, number, string are not supported

Source Stream
![image](https://user-images.githubusercontent.com/1385312/111210241-4c4f7e00-85cd-11eb-9d52-ee6f3f2dd83a.png)

Projection Stream / LinkTo
![image](https://user-images.githubusercontent.com/1385312/111210315-64bf9880-85cd-11eb-9c1e-c404f1c3d6b3.png)

**Comment by prolic** [comment]
Thanks everybody for the support. However note that I have an event here with some valid JSON. See the attachments above.

@hayley-jean Sorry I didn't had much time, but I will try to reproduce with your suggestion tomorrow.

**Comment by prolic** [comment]
Same behavior on 21.2.0-bionic. I still have this error in my log files:

```
eventstore_1                      | [    1,21,22:31:05.879,ERR] Error while processing message "EventStore.Projections.Core.Messaging.UnwrapEnvelopeMessage" in queued handler '"Projection Core #1"'.
eventstore_1                      | System.Exception: Invalid JSON
eventstore_1                      |    at EventStore.Projections.Core.Services.Processing.CheckpointTag.Check(JsonToken type, JsonReader reader) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CheckpointTag.cs:line 771
eventstore_1                      |    at EventStore.Projections.Core.Services.Processing.CheckpointTag.FromJson(JsonReader reader, ProjectionVersion current, Boolean skipStartObject) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CheckpointTag.cs:line 626
eventstore_1                      |    at EventStore.Projections.Core.Services.Processing.CheckpointTagExtensions.ParseCheckpointTagJson(ReadOnlyMemory`1 source) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/CheckpointTagExtensions.cs:line 43
eventstore_1                      |    at EventStore.Projections.Core.Services.Processing.ResolvedEvent..ctor(ResolvedEvent resolvedEvent, Byte[] streamMetadata) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/ResolvedEvent.cs:line 35
eventstore_1                      |    at EventStore.Projections.Core.Services.Processing.TransactionFileEventReader.DeliverEvent(ResolvedEvent event, Int64 lastCommitPosition, TFPos currentFrom) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/TransactionFileEventReader.cs:line 166
eventstore_1                      |    at EventStore.Projections.Core.Services.Processing.TransactionFileEventReader.Handle(ReadAllEventsForwardCompleted message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Processing/TransactionFileEventReader.cs:line 86
eventstore_1                      |    at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Bus/MessageHandler.cs:line 30
eventstore_1                      |    at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Bus/InMemoryBus.cs:line 290
eventstore_1                      |    at EventStore.Core.Bus.QueuedHandlerMRES.ReadFromQueue(Object o) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Bus/QueuedHandlerMRES.cs:line 119
eventstore_1                      | [    1,20,22:31:05.879,ERR] Error while processing message "EventStore.Projections.Core.Messaging.UnwrapEnvelopeMessage" in queued handler '"Projection Core #0"'.
```

As I just tried this again and found the same error in the event-log, I figured let's see what is in my event streams, so I have this little piece of code (written in PHP):

```
yield $eventStore->connectAsync();

    /** @var AllEventsSlice $slice */
    $slice = yield $eventStore->readAllEventsForwardAsync(Position::start(), 4096, true);

    while (! $slice->isEndOfStream()) {
        foreach ($slice->events() as $event) {
            $e = $event->event();

            if (null === $e || \substr($e->eventStreamId(), 0, 1) === '$') {
                continue;
            }

            echo 'EVENT: ' . $e->eventStreamId() . ' @ ' . $e->eventNumber() . PHP_EOL;
            echo 'DATA: ' . $e->data() . PHP_EOL . PHP_EOL;
        }

        $slice = yield $eventStore->readAllEventsForwardAsync($slice->nextPosition(), 4096, true);
    }
```

As expected this outputs all my events recorded and as the database is mostly empty, it's not much there, so let's have a look (I just replaced my real email address with "*****"):

```
EVENT: application_roles @ 0
DATA: {"Admin":"rol_AW2Qf5QQ8tg57oya","AdvertiserManager":"rol_hAtDW7vvCvxktLFA","AffiliateManager":"rol_qOko8EJvSj7xKJyo","BillingAccess":"rol_OZg0Jz27f4qvv7uB","CompanyContact":"rol_EvfGXyJf4ha27czJ","Reporting":"rol_V93Q4XO71nxgcukB","ReportingAccess":"rol_jy13mRzpz9ayZBtV"}

EVENT: user-c03bf46f-a529-dc4d-b318-2ac560479a48 @ 0
DATA: {"authId":"auth0|5f88c6d78a4c970076bffadc","firstName":"Sascha-Oliver","lastName":"Prolic","email":"****","roles":["Admin"],"phoneNumber":"","blocked":false,"emailVerified":true}

EVENT: migrations @ 0
DATA: {"migration":"0001_affiliate_campaign_has_product.php","executed":"2021-03-24T22:30:58.167084+00:00"}

EVENT: migrations @ 1
DATA: {"migration":"0002_drop_column_deletable_from_user_table.php","executed":"2021-03-24T22:30:58.168939+00:00"}
```

I don't see any invalid JSON here at all. So where does this error in the logs come from? Why is my event missing in the $by_category projection?

**Comment by prolic** [comment]
I try to create something reproducible using only curl commands this weekend.

**Comment by prolic** [comment]
I found the problem, not a bug on your side.
