### ISSUE TITLE
Consider supporting components contrib for dapr

### ISSUE THREAD

**Issue by springe2004** [EventStore/EventStore#2848]
Dapr is a portable, event-driven runtime that makes it easy for any developer to build resilient, stateless and stateful applications that run on the cloud and edge and embraces the diversity of languages and developer frameworks.

Dapr uses a modular design where functionality is delivered as a component. Each component has an interface definition. All of the components are pluggable so that you can swap out one component with the same interface for another.

However, only persistent state components are available now, but no event behavior is published. Eventstore should be able to meet this condition.

[dapr](https://github.com/dapr/dapr)

**Comment by alexeyzimarev** [comment]
@springe2004 I don't think the issue description sound right. Please fix it.

**Comment by springe2004** [comment]
@alexeyzimarev  Thank you for your reply. I have fixed the description
If you can submit the state component of eventstore, it should be a meaningful thing. We can build a system based on event scoring.

**Comment by alexeyzimarev** [comment]
I believe this must be resolved first: https://github.com/dapr/dapr/issues/915

For example, [Proto.Actor](https://proto.actor/) natively supports persistence with events, which makes it trivial to implement an ESDB persistence provider (and I've done it). It is also [possible](https://www.eventstore.com/blog/event-store-orleans) for Orleans for the same reason.

**Comment by mdg215199** [comment]
by chance, is there any plans to extend the ability to choose various types of actor infrastructure?  I'm not sure if proto.actor and also  orleans, refers it to virtual grains... though, it would be awesome if we could choose proto.actor (obviously, there is nothing that would prevent us from running proto.actor, but it wouldn't be the dapr actor layer (and I'm sure there's be gotchas in trying to allow a generic actor layer infrastructure that could then allow swapping out different actor components.

**Comment by alexeyzimarev** [comment]
Unless Dapr support event-sourced state, I don't think we can do it. I thought we can support pub/sub but it's still a bit awkward. I am closing this now as we have no current plans for that. We might consider looking into Dapr when we extend our integrations surface.
