### ISSUE TITLE
Feature: Extended Content-Type description

### ISSUE THREAD

**Issue by Zetanova** [EventStore/EventStore#2855]
**Is your feature request related to a problem? Please describe.**
Events with Empty-Data/Empty-String and Metadata as Json 
briking the LinkTo function in Projections
https://github.com/EventStore/EventStore/issues/2828#issuecomment-799049722

If RAW eventdata is used then the metadata is forcefully raw too.
Only json metadata can not be used in projections

**Describe the solution you'd like**
.) **Minimal** to split the IsJson Flag into two: IsJsonData and/or IsJsonMetadata
.) Optimal would be to set a content-type-Id for data and metadata field, optional seperatle
This would be the base for an Translation-Adapter-Plugin
https://github.com/EventStore/EventStore/issues/2770

**Describe alternatives you've considered**
.) Just using Json for Data and Metadata, including Empty Data Events with '{}' +2Bytes
.) Store Raw for Data and Metadata and losing WebUI and Projections feature because they cant performant access the metadata anymore. 
.) Going raw and writing my own Debug-WebUI and Projection-Service

**Additional context**
I made some test with msgpack 
.) The size of small json metadata is reduced to 50-70% (from ~178Bytes to ~86Bytes)
.) A Learned LZ4-Dictionary from a Stream/Projection can reduce the saved data and metadata very much.

**Comment by mat-mcloughlin** [comment]
As of 20.10 this is no longer applicable. For more information on how we handle empty json data in projections see the release notes here (under Content Type Validation for Projections)

https://www.eventstore.com/blog/20.10.2-lts-release-notes

**Comment by Zetanova** [comment]
The only problem with the description:
`If the event is a json event, then it must have valid non-null json data.`

I made here a test with all "valid" json data: https://github.com/EventStore/EventStore/issues/2828#issuecomment-799690350

the eventstore description should say:
`If the event is a json event, then it must have a valid json object or a valid json array.`
because valid json would include: 'null', '0', 'false' and '"string"'

**Comment by oskardudycz** [comment]
@Zetanova, at the moment, we're only supporting a valid JSON object in the JSON event. Thank you for sending the RFC. We'll review it again. Still, this behaviour probably won't change soon. Could you provide us with context on how this issue hits you? Maybe we could give some guidance or at least understand better your perspective?

**Comment by Zetanova** [comment]
@oskardudycz  Both issues hitting in the projection feature:
1) If someone uses RAW event data, he/she is forced to use RAW metadata too and the projection feature is lost to them 
2) If someone wants to store a simple valid json Number or json String (or did so in the past), 
then new or reset projections are broken

Of course I workaround/fixed the issues with a custom migration program.
But this looked not pretty to write view GB of eventdata again to eventstore 
only to include "{}" as payload instead of an empty event payload.
After the migration new projections worked on the rewritten and truncated streams. 


Too include a `payload-content-id` and a `meta-content-id` would solve the issues
and prepare for more features in the future.

Example:
payload-content-id: 0 => 0 bytes payload
meta-content-id: 0 => 0 bytes metadata
payload-content-id: 1 => RAW payload
meta-content-id: 1 => RAW  metadata
payload-content-id: 2 => JSON payload
meta-content-id: 2 => JSON metadata

Someone could then use for empty payload:
payload-content-id: 0 => 0 bytes payload
meta-content-id: 2 => JSON metadata

and for events with raw payload
payload-content-id: 1 => RAW payload
meta-content-id: 2 => JSON metadata

and for events with json payload
payload-content-id: 2 => JSON payload
meta-content-id: 2 => JSON metadata

**Comment by oskardudycz** [comment]
That's a fair point around migration from the older database versions. @hayley-jean @jageall, thoughts?

**Comment by alexeyzimarev** [comment]
Following up in #4283
