### ISSUE TITLE
Developer documentation Incomplete

### ISSUE THREAD

**Issue by zizhongzhang** [EventStore/EventStore#2864]
**Describe the bug**
Am checking out the developer docs page relating to paging and see there is no code sample just yet 

**To Reproduce**
1. Visit https://developers.eventstore.com/server/v5/http-api/reading-streams.html#feed-paging
2. The code block has default content of "// Make sure to add code blocks to your code group"

**Expected behavior**
A working example is provided

**Actual behavior**
Dummy comment is provided

**Config/Logs/Screenshots**
If applicable, please attach your node configuration, logs or any screenshots.

**EventStore details**
 NA

 - Operating system:
NA

 - EventStore client version (if applicable):
NA

**Additional context**
Thanks team!

**Comment by alexeyzimarev** [comment]
Wrong repository. I will open it int he docs.

It is not a "dummy example", it's a broken path to the code file. Thanks for reporting.
