### ISSUE TITLE
Provide the timestamp of the last metastream update

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/EventStore#2872]
**Is your feature request related to a problem? Please describe.**

When replicating events from one ESDB instance to another, I need to know when the stream meta has been updated last. It would allow me to understand whether to propagate certain events to the target.

**Describe the solution you'd like**
I'd like to have a property on the `StreamMetadataResult`, which would contain the creation date of the last event in the metastream.

**Comment by oskardudycz** [comment]
It was fixed by https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy/pull/3.
