### ISSUE TITLE
Loading stream suddenly stops

### ISSUE THREAD

**Issue by ElkeRenard** [EventStore/EventStore#2874]
We have an .NET CORE project in which we use Eventstore. Recently we've been experiencing problems with 3 out of the 10.000+ streams. Those 3 streams have already 100+ events and have been working fine until last week. We can't add any new event to the stream, we get a wrong expected version error. We first thought it was because we had been cleaning up some of the unused events, but after we turned back our code to the not cleaned up version, we still had the same problem. If we try to just load the stream to view it, the returned json is suddenly breaked down in the middle of the json body. All 3 of the streams break down at a different event and those events have been working fine for months and have not been changed or deleted during the code clean up. We are using EventStore Client v5.0.9. Currently we are out of ideas on where or how to look for the problem.

**Comment by hayley-jean** [comment]
Hi @ElkeRenard, are you seeing any errors logged on the server when you try to read these streams?
What version of Event Store are you running?

**Comment by oskardudycz** [comment]
Closing because of the inactivity.
