### ISSUE TITLE
Delay when using catch-up subscription

### ISSUE THREAD

**Issue by JosephPhillips1991** [EventStore/EventStore#2890]
On 21.2.0/windows server 2019 using the tcp client we are getting a long 3/4 second delay between batches of events when using 'SubscribeToStreamFrom'. This has only started to happen since upgrading to 21.2 (server and client). We assumed the issue may be due to us using a large database backup from our production environment but we get the same behaviour on a fresh database. The behaviour is consistent across our environments. 

Using the noddy code (v21.2 client) below we can see the issue after writing 100,000 simple/small events using another program
```
static async Task Main()
{
	var eventstoreFacade = new EventStoreFacade();
	await eventstoreFacade.Connect();
   	eventstoreFacade.CatchupEventStream("CellSourceFilesRetrieved");
	Console.WriteLine("Done");
	Console.ReadLine();
}

public class EventStoreFacade
{
	private IEventStoreConnection _connection;
	private long? _streamCheckpoint = StreamCheckpoint.StreamStart;
	private int _count;
	private Stopwatch _stopwatch;
	private int _writeLogEvery = 500;
	private int _batchSize = 500;

	public EventStoreFacade()
	{
		_stopwatch = new Stopwatch();
	}

	private static readonly ConnectionSettingsBuilder _baseSettings = ConnectionSettings.Create()
		.SetReconnectionDelayTo(TimeSpan.FromSeconds(5))
		.WithConnectionTimeoutOf(TimeSpan.FromMinutes(20))
		.SetHeartbeatInterval(TimeSpan.FromMinutes(1))
		.SetHeartbeatTimeout(TimeSpan.FromMinutes(10))
		.SetGossipTimeout(TimeSpan.FromMinutes(1))
		.EnableVerboseLogging()
		//.UseConsoleLogger()
		.SetMaxDiscoverAttempts(5)
		.KeepReconnecting()
		.PreferRandomNode();


	public async Task Connect()
	{
		_baseSettings.SetGossipSeedEndPoints(
		new EndPoint[]
			{
				new DnsEndPoint("HOSTNAMEHERE",443)
			});
		_connection = EventStoreConnection.Create(_baseSettings.Build());
		
		await _connection.ConnectAsync();
		_connection.Connected += (sender, args) => { Console.WriteLine("Connected"); };
		_connection.Disconnected += (sender, args) => { Console.WriteLine("Disconnected"); };
		_connection.Reconnecting += (sender, args) => { Console.WriteLine("Reconnecting"); };
		_connection.Closed += (sender, args) => { Console.WriteLine("Closed"); };
		_connection.ErrorOccurred += (sender, args) => { Console.WriteLine("ErrorOccurred"); };
		_connection.AuthenticationFailed += (sender,args) => { Console.WriteLine("authenticationFailed"); };
		
		
		Console.WriteLine("Called connect");
		_stopwatch.Start();
	}
	
	public void CatchupEventStream(string stream)
	{
		var settings = new CatchUpSubscriptionSettings(1000,_batchSize,true,true);

		_connection.SubscribeToStreamFrom(stream, _streamCheckpoint, settings, EventAppearedWrapper, (cachupSub) => { }, (sub, dropreason, exception) => { Console.WriteLine("SubDropped");});
	}
	
	private bool _switch;
	
	private Task EventAppearedWrapper(EventStoreCatchUpSubscription unused, ResolvedEvent resolvedEvent)
	{
		Interlocked.Increment(ref _count);
		if(_switch)
		{
			_switch = false;
// Write a log after the first event seen in a new batch
			Console.WriteLine($"EventsSeen = {_count}. Time taken since starting catchup {_stopwatch.Elapsed.TotalSeconds:0.##}s");
		}
		if((_count % _writeLogEvery) == 0)
		{
			Console.WriteLine($"EventsSeen = {_count}. Time taken since starting catchup{_stopwatch.Elapsed.TotalSeconds:0.##}s");
			_switch = true;
		}
		
		return Task.CompletedTask;
	}
}

```
By uncommenting the line //.UseConsoleLogger() you can see more verbose info.

Expected behavior
This is the output of the same script against v5.0.1 using v5.0.1 client. As you can see there is very little time between batches being picked up.
```
EventsSeen = 500. Time taken 1.09s
EventsSeen = 501. Time taken 1.09s
EventsSeen = 1000. Time taken 1.12s
EventsSeen = 1001. Time taken 1.12s
EventsSeen = 1500. Time taken 1.16s
EventsSeen = 1501. Time taken 1.16s
EventsSeen = 2000. Time taken 1.21s
EventsSeen = 2001. Time taken 1.21s
EventsSeen = 2500. Time taken 1.26s
EventsSeen = 2501. Time taken 1.26s
EventsSeen = 3000. Time taken 1.33s
EventsSeen = 3001. Time taken 1.33s
EventsSeen = 3500. Time taken 1.4s
EventsSeen = 3501. Time taken 1.4s
EventsSeen = 4000. Time taken 1.49s
EventsSeen = 4001. Time taken 1.49s
EventsSeen = 4500. Time taken 1.59s
EventsSeen = 4501. Time taken 1.59s
EventsSeen = 5000. Time taken 1.99s
EventsSeen = 5001. Time taken 1.99s
EventsSeen = 5500. Time taken 2.18s
EventsSeen = 5501. Time taken 2.18s
EventsSeen = 6000. Time taken 2.32s
EventsSeen = 6001. Time taken 2.33s
EventsSeen = 6500. Time taken 2.45s
EventsSeen = 6501. Time taken 2.45s
EventsSeen = 7000. Time taken 2.59s
EventsSeen = 7001. Time taken 2.59s
EventsSeen = 7500. Time taken 2.74s
EventsSeen = 7501. Time taken 2.74s
EventsSeen = 8000. Time taken 2.89s
EventsSeen = 8001. Time taken 2.89s
EventsSeen = 8500. Time taken 3.05s
EventsSeen = 8501. Time taken 3.06s
EventsSeen = 9000. Time taken 3.24s
EventsSeen = 9001. Time taken 3.24s
EventsSeen = 9500. Time taken 3.42s
EventsSeen = 9501. Time taken 3.42s
EventsSeen = 10000. Time taken 3.61s
```

Actual behavior
This is the output of the same script against v21.2 using v21.2 tcp client. As you can see there is a delay of a few seconds between receiving batches.
```
EventsSeen = 500. Time taken 3.97s
EventsSeen = 501. Time taken 7.98s
EventsSeen = 1000. Time taken 7.98s
EventsSeen = 1001. Time taken 12s
EventsSeen = 1500. Time taken 12s
EventsSeen = 1501. Time taken 16.03s
EventsSeen = 2000. Time taken 16.03s
EventsSeen = 2001. Time taken 20.03s
EventsSeen = 2500. Time taken 20.03s
EventsSeen = 2501. Time taken 24.05s
EventsSeen = 3000. Time taken 24.05s
EventsSeen = 3001. Time taken 28.06s
EventsSeen = 3500. Time taken 28.06s
EventsSeen = 3501. Time taken 32.08s
EventsSeen = 4000. Time taken 32.08s
EventsSeen = 4001. Time taken 36.11s
EventsSeen = 4501. Time taken 40.13s
EventsSeen = 5000. Time taken 40.13s
EventsSeen = 5001. Time taken 44.15s
EventsSeen = 5500. Time taken 44.15s
EventsSeen = 5501. Time taken 48.17s
EventsSeen = 6000. Time taken 48.17s
EventsSeen = 6001. Time taken 52.19s
EventsSeen = 6500. Time taken 52.19s
EventsSeen = 6501. Time taken 56.21s
EventsSeen = 7000. Time taken 56.21s
EventsSeen = 7001. Time taken 60.23s
EventsSeen = 7500. Time taken 60.23s
EventsSeen = 7501. Time taken 64.24s
EventsSeen = 8000. Time taken 64.24s
EventsSeen = 8001. Time taken 68.3s
EventsSeen = 8500. Time taken 68.3s
EventsSeen = 8501. Time taken 72.27s
EventsSeen = 9000. Time taken 72.27s
EventsSeen = 9001. Time taken 76.27s
EventsSeen = 9500. Time taken 76.27s
EventsSeen = 9501. Time taken 80.28s
EventsSeen = 10000. Time taken 80.28s
```

Here is a snippet of the same using the console logger setting in our connection settings.
```
[07,08:57:11.843,DEBUG] Catch-up Subscription  to CellSourceFilesRetrieved: processed event (CellSourceFilesRetrieved, 496, CellSourceFilesRetrieved @ 496).
[07,08:57:11.843,DEBUG] Catch-up Subscription  to CellSourceFilesRetrieved: processed event (CellSourceFilesRetrieved, 497, CellSourceFilesRetrieved @ 497).
[07,08:57:11.843,DEBUG] Catch-up Subscription  to CellSourceFilesRetrieved: processed event (CellSourceFilesRetrieved, 498, CellSourceFilesRetrieved @ 498).
EventsSeen = 500. Time taken 4.15s
[07,08:57:11.843,DEBUG] Catch-up Subscription  to CellSourceFilesRetrieved: processed event (CellSourceFilesRetrieved, 499, CellSourceFilesRetrieved @ 499).
[07,08:57:11.843,DEBUG] EventStoreConnection 'ES-2f82ebc9-7cb4-4652-bf90-6c7ffef216e5': enqueueing message EventStore.ClientAPI.Internal.StartOperationMessage..
[13,08:57:11.843,DEBUG] EventStoreConnection 'ES-2f82ebc9-7cb4-4652-bf90-6c7ffef216e5': StartOperation schedule ReadStreamEventsForwardOperation, Stream: CellSourceFilesRetrieved, FromEventNumber: 500, MaxCount: 500, ResolveLinkTos: True, RequireLeader: True, 10, 00:00:07..
[13,08:57:11.843,DEBUG] EventStoreConnection 'ES-2f82ebc9-7cb4-4652-bf90-6c7ffef216e5': ExecuteOperation package ReadStreamEventsForward, efc46bcd-cf23-4741-abd8-1287aaf0e6df, Operation ReadStreamEventsForwardOperation (efc46bcd-cf23-4741-abd8-1287aaf0e6df): Stream: CellSourceFilesRetrieved, FromEventNumber: 500, MaxCount: 500, ResolveLinkTos: True, RequireLeader: True, retry count: 0, created: 08:57:11.843, last updated: 08:57:11.843..
[19,08:57:15.845,DEBUG] EventStoreConnection 'ES-2f82ebc9-7cb4-4652-bf90-6c7ffef216e5': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
[20,08:57:15.845,DEBUG] EventStoreConnection 'ES-2f82ebc9-7cb4-4652-bf90-6c7ffef216e5': HandleTcpPackage connId b0152524-7410-41ca-9f1e-50d84ab18c4a, package ReadStreamEventsForwardCompleted, efc46bcd-cf23-4741-abd8-1287aaf0e6df..
[19,08:57:15.845,DEBUG] EventStoreConnection 'ES-2f82ebc9-7cb4-4652-bf90-6c7ffef216e5': enqueueing message EventStore.ClientAPI.Internal.HandleTcpPackageMessage..
[20,08:57:15.846,DEBUG] EventStoreConnection 'ES-2f82ebc9-7cb4-4652-bf90-6c7ffef216e5': HandleTcpPackage OPERATION DECISION EndOperation (Success), Operation ReadStreamEventsForwardOperation (efc46bcd-cf23-4741-abd8-1287aaf0e6df): Stream: CellSourceFilesRetrieved, FromEventNumber: 500, MaxCount: 500, ResolveLinkTos: True, RequireLeader: True, retry count: 0, created: 08:57:11.843, last updated: 08:57:11.843.
[20,08:57:15.846,DEBUG] EventStoreConnection 'ES-2f82ebc9-7cb4-4652-bf90-6c7ffef216e5': RemoveOperation SUCCEEDED for Operation ReadStreamEventsForwardOperation (efc46bcd-cf23-4741-abd8-1287aaf0e6df): Stream: CellSourceFilesRetrieved, FromEventNumber: 500, MaxCount: 500, ResolveLinkTos: True, RequireLeader: True, retry count: 0, created: 08:57:11.843, last updated: 08:57:11.843.
EventsSeen = 501. Time taken 8.15s
[13,08:57:15.846,DEBUG] Catch-up Subscription  to CellSourceFilesRetrieved: processed event (CellSourceFilesRetrieved, 500, CellSourceFilesRetrieved @ 500).
[13,08:57:15.846,DEBUG] Catch-up Subscription  to CellSourceFilesRetrieved: processed event (CellSourceFilesRetrieved, 501, CellSourceFilesRetrieved @ 501).
```
Is it possible we are missing a setting either server side or client side?

**Comment by JosephPhillips1991** [comment]
Sorry if it's not clear "Time taken" is the time taken from the start of subscribing. It's not getting exponentially larger each time it subscribes/receives another batch.

**Comment by elerivaliant** [comment]
Added a bit of extra info and formatting to the statistics to make them hopefully more helpful.

5.0.1:
| EventsSeenAtStart | StartTime | EventsSeenAtEnd | EndTime | BatchProcessTime | TimeToNextBatchStart
|--|--|--|--|--|--|
| 0 | 0s | 500 | 1.09s | 1.09s | 0.0s |
| 501 | 1.09s | 1000 | 1.12s | 0.03s | 0.0s |
| 1001 | 1.12s | 1500 | 1.16s | 0.04s | 0.0s |
| 1501 | 1.16s | 2000 | 1.21s | 0.05s | 0.0s |
| 2001 | 1.21s | 2500 | 1.26s | 0.05s | 0.0s |
| 2501 | 1.26s | 3000 | 1.33s | 0.07s | 0.0s |
| 3001 | 1.33s | 3500 | 1.4s | 0.07s | 0.0s |
| 3501 | 1.4s | 4000 | 1.49s | 0.09s | 0.0s |
| 4001 | 1.49s | 4500 | 1.59s | 0.1s  | 0.0s |
| 4501 | 1.59s | 5000 | 1.99s | 0.4s  | 0.0s |
| 5001 | 1.99s | 5500 | 2.18s | 0.19s | 0.0s |
| 5501 | 2.18s | 6000 | 2.32s | 0.14s | 0.0s |
| 6001 | 2.33s | 6500 | 2.45s | 0.12s | 0.0s |
| 6501 | 2.45s | 7000 | 2.59s | 0.14s | 0.0s |
| 7001 | 2.59s | 7500 | 2.74s | 0.15s | 0.0s |
| 7501 | 2.74s | 8000 | 2.89s | 0.15s | 0.0s |
| 8001 | 2.89s | 8500 | 3.05s | 0.16s | 0.0s |
| 8501 | 3.06s | 9000 | 3.24s | 0.18s | 0.0s |
| 9001 | 3.24s | 9500 | 3.42s | 0.18s | 0.0s |
| 9501 | 3.42s | 10000 | 3.61s | 0.19s |  |

21.2:
| EventsSeenAtStart | StartTime | EventsSeenAtEnd | EndTime | BatchProcessTime | TimeToNextBatchStart
|--|--|--|--|--|--|
|  | 500 | 3.97s | 3.97s | 4.01s |
| 501 | 7.98s	| 1000 | 7.98s	| 0s | 4.02s |
| 1001 | 12s	| 1500 | 12s	| 0s | 4.03s |
| 1501 | 16.03s	| 2000 | 16.03s	| 0s | 4s    |
| 2001 | 20.03s	| 2500 | 20.03s	| 0s | 4.02s |
| 2501 | 24.05s	| 3000 | 24.05s	| 0s | 4.01s |
| 3001 | 28.06s	| 3500 | 28.06s	| 0s | 4.02s |
| 3501 | 32.08s	| 4000 | 32.08s	| 0s | 4.03s |
| 4001 | 36.11s	| | | ? | ? |
| 4501 | 40.13s	| 5000 | 40.13s	| 0s | 4.02s |
| 5001 | 44.15s	| 5500 | 44.15s	| 0s | 4.02s |
| 5501 | 48.17s	| 6000 | 48.17s	| 0s | 4.02s |
| 6001 | 52.19s	| 6500 | 52.19s	| 0s | 4.02s |
| 6501 | 56.21s	| 7000 | 56.21s	| 0s | 4.02s |
| 7001 | 60.23s	| 7500 | 60.23s	| 0s | 4.01s |
| 7501 | 64.24s	| 8000 | 64.24s	| 0s | 4.06s |
| 8001 | 68.3s	| 8500 | 68.3s 	| 0s | 3.97s |
| 8501 | 72.27s	| 9000 | 72.27s	| 0s | 4s    |
| 9001 | 76.27s	| 9500 | 76.27s	| 0s | 4.01s |
| 9501 | 80.28s	| 10000 | 80.28s | 0s | |

**Comment by JosephPhillips1991** [comment]
It's worth also noting we don't see this issue when we've got a 20.10.0 server and client either.

**Comment by Zetanova** [comment]
@JosephPhillips1991 Did u found the issue
I updated now the client to 21.2 and `ReadStreamEventsForwardAsync` takes strangely long for multiple streams (read in seq)
PendingSend on the server this then always 215kb for couple of sec.

**Comment by ahjohannessen** [comment]
@JosephPhillips1991 Do you have the same issue with 20.10.2?

**Comment by hayley-jean** [comment]
@JosephPhillips1991 @Zetanova Thanks for reporting this!
We are aware of a regression in TCP performance in 21.2.0, see https://github.com/EventStore/EventStore/pull/2834 for more information.

As @ahjohannessen said, could you try run the same tests on 20.10.2?
This release contains most of the changes in 21.2.0 as well as the regression fix, so we recommend you use this version instead.

**Comment by JosephPhillips1991** [comment]
@hayley-jean we've tried 20.10.2 now and have similar performance issues. SubscribeToStreamFrom is sometimes quicker/sometimes as slow but now we are also seeing an issue with ReadStreamEventsBackwardAsync. Do you know if there is any workaround beyond sticking on v5? I'm reluctant to do so as in our project timeline it's unlikely we will get around to upgrading until the end of the year, risking going out of support.

**Comment by Zetanova** [comment]
@JosephPhillips1991 for me is working
But i am using a custom algo to catch up with `ReadStreamEventsForwardAsync` with a boundary of 500 events
if the offset is 11234 then it will read 266 events and after 500 until it catched up and then the `SubscribeToStreamFrom` is used.

**Comment by JosephPhillips1991** [comment]
@Zetanova we've managed to refactor in a similar fashion. Happy to close this as it's tracked by [#2834](https://github.com/EventStore/EventStore/pull/2834)
