### ISSUE TITLE
Failed to connect with version 21.2.0 but with 5.0.11 this is working.

### ISSUE THREAD

**Issue by vitorafgomes** [EventStore/EventStore#2891]
**Describe the bug**
Failed to connect with version 21.2.0 but with 5.0.11 this is working.

**Actual behavior**
When executing the code below, in version 5.0.11 it works but in version 21.2.0 and returns the exception below.

namespace Gateways.EventStore.Tests
{
    using global::EventStore.ClientAPI;
    using System;
    using System.Text;
    using System.Threading.Tasks;
    using FluentAssertions;
    using Xunit;

    public class EventStoreTests : IDisposable
    {
        private readonly IEventStoreConnection connection;

        private readonly string stream;

        public EventStoreTests()
        {
            connection = EventStoreConnection.Create(
                "ConnectTo=tcp://admin:changeit@fenix.local.docker:1113; DefaultUserCredentials=admin:changeit;",
                ConnectionSettings.Create().KeepReconnecting(),
                "Smart.Admin.Identity");
            connection.ConnectAsync().Wait();
            stream = Guid.NewGuid().ToString();
        }

        [Fact]
        public async Task TestStreamDoesNotExists()
        {
            var events = await connection.ReadStreamEventsForwardAsync(stream, StreamPosition.Start, 1, false);

            Assert.Equal(SliceReadStatus.StreamNotFound, events.Status);
        }

        [Fact]
        public async Task TestStreamExists()
        {
            await AppendEventToStreamAsync();

            var events = await connection.ReadStreamEventsForwardAsync(stream, StreamPosition.Start, 1, false);

            Assert.Equal(SliceReadStatus.Success, events.Status);
            Assert.Single(events.Events);
        }

        [Fact]
        public async Task TestPerformance()
        {
            for (var i = 0; i < 100; i++)
            {
                await connection.AppendToStreamAsync(stream,
                    i - 1,
                    new EventData(Guid.NewGuid(), "test", true, Encoding.UTF8.GetBytes("{Test:EventStoreTests}"), StreamMetadata.Create().AsJsonBytes()));
            }
        }

        private async Task AppendEventToStreamAsync()
        {
            await connection.AppendToStreamAsync(stream,
                ExpectedVersion.NoStream,
                new EventData(Guid.NewGuid(), "test", true, Encoding.UTF8.GetBytes("{Test:EventStoreTests}"), StreamMetadata.Create().AsJsonBytes()));
        }

        public void Dispose()
        {
            connection.DeleteStreamAsync(stream, ExpectedVersion.Any).Wait();
            connection.Dispose();
        }
    }
}

One thing I noticed that in version 21.2.0 even though I send it in the name of the Client Connection Name, it stays as N/A

![image](https://user-images.githubusercontent.com/5174765/113449858-a4bcb300-93f6-11eb-8032-8d12dfcb2361.png)

**Config/Logs/Screenshots**
Gateways.EventStore.Tests.EventStoreTests.TestStreamDoesNotExists

System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instan...

System.AggregateException
One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
  Exception doesn't have a stacktrace

System.NullReferenceException
Object reference not set to an instance of an object.
   at Gateways.EventStore.Tests.EventStoreTests.TestStreamDoesNotExists() in /home/vitorafgomes/WorkSpace/Customer/VGCTechnology/Smart.Admin.Identity/tests/Gateways.EventStore.Tests/EventStoreTests.cs:line 54
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

System.NullReferenceException
Object reference not set to an instance of an object.
   at Gateways.EventStore.Tests.EventStoreTests.Dispose() in /home/vitorafgomes/WorkSpace/Customer/VGCTechnology/Smart.Admin.Identity/tests/Gateways.EventStore.Tests/EventStoreTests.cs:line 90
   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 31
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass47_0.<RunAsync>b__1() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 216
   at Xunit.Sdk.ExceptionAggregator.Run(Action code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 73

**EventStore details**
 - EventStore server version: 5.0.9.0

 - Operating system: 
   -  lxc container Docker 
OS: Ubuntu 20.04.2 LTS x86_64 
Host: Serval WS serw12 
Kernel: 5.11.0-7612-generic 
Uptime: 7 hours, 23 mins 
Packages: 590 (dpkg), 4 (snap) 
Shell: bash 5.0.17 
Resolution: 3440x1440 
CPU: AMD Ryzen 9 3900 (4) @ 3.100GHz 
GPU: NVIDIA GeForce GTX 1660 Ti Mobi 
Memory: 472MiB / 3814MiB 

   - The machine where I'm running the source code.
OS: Pop!_OS 20.10 x86_64 
Host: Serval WS serw12 
Kernel: 5.11.0-7612-generic 
Uptime: 1 day, 11 hours, 5 mins 
Packages: 2710 (dpkg), 35 (flatpak),  
Shell: bash 5.0.17 
Resolution: 3440x1440, 1920x1080 
DE: GNOME 3.38.3 
WM: Mutter 
WM Theme: Material-Black-Plum-3.38 
Theme: Material-Black-Plum-3.38 [GTK2 
Icons: ubuntu-mono-dark [GTK2/3] 
Terminal: tilix 
CPU: AMD Ryzen 9 3900 (24) @ 3.100GHz 
GPU: NVIDIA GeForce GTX 1660 Ti Mobil 
Memory: 14067MiB / 64271MiB 
           
 - EventStore client version:  5.0.11 and 21.2.0

**Comment by Zetanova** [comment]
To get the same behavior as v5 
use UseSslConnection=false and start the server with `--insecure --enable-external-tcp`

ConnectionString: `"tcp://admin:changeit@fenix.local.docker:1113;UseSslConnection=false;DefaultUserCredentials=admin:changeit;"`

**Comment by vitorafgomes** [comment]
Thank you for your help.
