### ISSUE TITLE
Grpc connection names missing in overview

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#2925]
Grpc clients do not show up under ES dashboard under connections when doing a subscribeToAll or subscribeToStream? Not sure if other scenarios are missing.

I believe the only case it shows up is when one uses persistent subscriptions.

/cc @oskardudycz

**Comment by oskardudycz** [comment]
@ahjohannessen, thank you for adding this issue. @hayley-jean FYI - this is the case I've been asking about recently.

**Comment by hayley-jean** [comment]
Thanks @ahjohannessen

We could potentially show live subscriptions in the UI, but other gRPC requests are currently stateless, so a bit harder to track.

One thing we could consider is showing stats about gRPC connections in an interval - such as the connections that were made in the past 5 minutes, and how much data they transferred

**Comment by ahjohannessen** [comment]
>We could potentially show live subscriptions in the UI, but other gRPC requests are currently stateless

With grpc we use channel(s) - is that not enough?

**Comment by alexeyzimarev** [comment]
We won't be able to show clients that are making RPC calls (reads and appends). We plan to have an API to list catch-up subscriptions, it should be there in 24.10. But, we won't be updating the old UI, so it will go to the Navigator app.
