### ISSUE TITLE
NotHandled is NotHandled

### ISSUE THREAD

**Issue by vtajzich** [EventStore/EventStore#2943]
**Describe the bug**
Use NodeJS client (currently using version 1.2.1).
When an application is starting, it tries to create a persistent subscription and connect to it (when subscription already exists, it handles the error code and continue).

Specific method used: ```createPersistentSubscription(streamName: string, groupName: string, settings: PersistentSubscriptionSettings, options?: BaseOptions): Promise<void>;```

Sometimes it returns weird error:

```
Error: 2 UNKNOWN: Envelope callback expected either PersistentSubscriptionConfirmation or NotHandled, received NotHandled instead at Object.convertToCommandError (node_modules/@eventstore/db-client/dist/utils/CommandError.js:282:12) at ClientDuplexStreamImpl.<anonymous> (node_modules/@eventstore/db-client/dist/utils/TwoWaySubscription.js:34:38) at ClientDuplexStreamImpl.emit (events.js:315:20) at Object.onReceiveStatus
```

**To Reproduce**
1. Use NodeJS client
2. Try to create subscription (even it already exists)
3. Sometimes it returns error code 2 and error `NotHandled, received NotHandled instead`

**Expected behavior**
It returns no error when subscription doesn't exists or error code 6 (ALREADY_EXISTS) when subscription exists.

**Actual behavior**
Return error code 2 (see description)

**Config/Logs/Screenshots**
```
Error: 2 UNKNOWN: Envelope callback expected either PersistentSubscriptionConfirmation or NotHandled, received NotHandled instead at Object.convertToCommandError (node_modules/@eventstore/db-client/dist/utils/CommandError.js:282:12) at ClientDuplexStreamImpl.<anonymous> (node_modules/@eventstore/db-client/dist/utils/TwoWaySubscription.js:34:38) at ClientDuplexStreamImpl.emit (events.js:315:20) at Object.onReceiveStatus
```

**EventStore details**
 - EventStore server version: 21.2.0-buster-slim
 - Operating system: Docker
 - EventStore client version (if applicable): NodeJS, 1.2.1

**Comment by YoEight** [comment]
Hi @vtajzich , this is not the right repo. Could you create a ticket in the NodeJS client repo please?  https://github.com/EventStore/EventStore-Client-NodeJS

**Comment by vtajzich** [comment]
Not sure if it is issue with client or server itself. Created issue in client repo as you requested: https://github.com/EventStore/EventStore-Client-NodeJS/issues/160
