### ISSUE TITLE
 EventStore.Client hangs on Azure DevOps Pipelines

### ISSUE THREAD

**Issue by albertocorrales** [EventStore/EventStore#2948]
**Describe the bug**
When executing integration tests on Azure Pipelines, the pipeline hangs when it executes AppendToStreamAsync. 

**To Reproduce**
1. Run this example project on Azure Pipelines: https://github.com/albertocorrales/esdb_test_hangs
2. When the build runs, it hangs. 

**Expected behavior**
The build passes, so we can have integration tests in our pipelines.

**Actual behavior**
The build hangs. I've noticed this happens when I have in my tests try to read/write to ESDB. In addition, this happens most of the time, but some builds pass.

**Config/Logs/Screenshots**
Locally from Windows, with command "dotnet test" it works 100% 
![image](https://user-images.githubusercontent.com/33038414/117583633-87bb8400-b108-11eb-91dd-7a27b649d0a5.png)

From Azure Devops the pipeline hangs most of the executions
![image](https://user-images.githubusercontent.com/33038414/117583651-a4f05280-b108-11eb-97b0-7a2de36cc3e6.png)

**EventStore details**
 - EventStore server version:  20.10.2 running on docker
 - Operating system: ubuntu-latest on Azure DevOps agent.
 - EventStore client version (if applicable):  EventStore.Client 20.10.0

**Comment by OssWhisperer** [comment]
No good solution, but a workaround ...
... insert a short sleep after starting the container:
`System.Threading.Thread.Sleep(5000);`

You may also want to disable all retries when doing integration tests:
```
var settings = ConnectionSettings.Create()
                .DisableTls()
                .FailOnNoServerResponse()
                .LimitReconnectionsTo(0)
                .Limit...
```

It may also be helpfull to pull the image before starting the container in seperate YAML task:
```
- task: CmdLine@2
  inputs:
    script: |
      docker pull eventstore/eventstore:20.10.2-bionic
```

**Comment by albertocorrales** [comment]
> No perfect solution, but a workaround ...
> ... insert a short sleep after starting the container:
> `System.Threading.Thread.Sleep(5000);`
> 
> You may also want to disable all retries when doing integration tests:
> 
> ```
> var settings = ConnectionSettings.Create()
>                 .DisableTls()
>                 .FailOnNoServerResponse()
>                 .LimitReconnectionsTo(0)
>                 .Limit...
> ```
> 
> It may also be helpfull to pull the image before starting the container in seperate YAML task:
> 
> ```
> - task: CmdLine@2
>   inputs:
>     script: |
>       docker pull eventstore/eventstore:20.10.2-bionic
> ```
> 
> Edit: Indeed, it seems like there may be a situation where retry-logic hangs itself, when connecting very short after the start of EventStoreDB, but i am no expert ...

Thanks for your answer @OssWhisperer. It feels like a workaround, but adding a timeout of 5 seconds seems to work. So the problem might be in the container, since it is not ready when docker run finishes, right?

**Comment by OssWhisperer** [comment]
I was digging a bit deeper and found a better one.
Try the following command to start the docker container:
```
            new Builder()
            .UseContainer()
            .WithName("esdb-tests")
            .UseImage("eventstore/eventstore:20.10.2-bionic")
            .Command("--insecure --enable-external-tcp")
            .ReuseIfExists()
            .ExposePort(tcpPort, tcpPort)
            .ExposePort(2113, 2113)
            .WaitForHttp("http://localhost:2113/health/live", continuation: (resp, cnt) => {
                // if HTTP status is 2xx, ESDB is healty, else wait for 500ms and check again
                return ((int)resp.Code >= 200) && ((int)resp.Code <= 299) ? 0 : 500;
            })
            .Build()
            .Start();
```
I replaced .WaitForPort() with WaitForHttp() on the healthcheck-url of eventstore.

.WaitForHealthy() would be nice, but HEALTCHECK inside the defined dockerfile does not work because curl is not available within the docker container:

```
# docker inspect (...)
(...)
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 119,
                "Log": [
                    {
                        "Start": "2021-05-12T15:24:07.5696373Z",
                        "End": "2021-05-12T15:24:07.6449371Z",
                        "ExitCode": 1,
                        "Output": "/bin/sh: 1: curl: not found\n/bin/sh: 1: curl: not found\n"
                    },
(...)
```

PS: You may also want to keep a ref to the Builder-Result, as in theory, the returned IDockerService could be disposed before the actual unit-test runs. --mem-db might also be a good option here to start ESDB.

**Comment by oskardudycz** [comment]
@albertocorrales @OssWhisperer I apologise for the late answer. Indeed our Healthcheck inside Dockerfile was broken. We were missing the preinstalled `curl`... That was already fixed. Images from the 20.10.2 above should already contain the fix.

Could you try again and confirm if it works correctly?

I'm closing the issue, but if it appeared that it's still not working, I'll reopen it.
