### ISSUE TITLE
uris in client

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#295]
basic things like /streams/foo have changed and no longer work with ui (3.0.1)

**Comment by seburgi** [comment]
Not sure if you folks are aware, but the current behavior in 3.1.0 is to redirect from http://127.0.0.1:2113/streams/$stats-127.0.0.1:2113/231 
to
http://127.0.0.1:2113/web/index.html#/streams/$stats-127.0.0.1:2113 

Which means that the event number is lost in translation.

**Comment by pgermishuys** [comment]
Thanks @seburgi 
Will take a look and get this in the next release.

Here is the culprit.
https://github.com/EventStore/EventStore/blob/release-v3.1.0/src/EventStore.Core/Services/Transport/Http/Controllers/AtomController.cs#L837

**Comment by gregoryyoung** [comment]
Makes sense.

On Wed, Aug 12, 2015 at 10:40 AM, Pieter Germishuys <
notifications@github.com> wrote:

> Thanks @seburgi <https://github.com/seburgi>
> Will take a look and get this in the next release.
>
> Here is the culprit.
>
> https://github.com/EventStore/EventStore/blob/release-v3.1.0/src/EventStore.Core/Services/Transport/Http/Controllers/AtomController.cs#L837
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/295#issuecomment-130203396>
> .
>



-- 
Studying for the Turing test
