### ISSUE TITLE
SubscribeToStreamOrdered

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#2971]
**Is your feature request related to a problem? Please describe.**
Subscriptions give us the choice of concurrent processing, but no order guarantee, or one at a time with order guaranteed.
It would be nice if Eventstore could ship with a "SubscribeToStreamOrdered"

**Describe the solution you'd like**
I asked the question on slack, and @oskardudycz  suggested we build queue in our consumer.
We would read <n> events, then reduce this list, then attack it concurrently.
Our consumer then writes the checkpoint once all <n> events have been processed.
This will work, and greatly speed up our processing, but consider the situation where we don't quite receive <n> events.
We would not want to hang around, therefore, our checkpoint would would need also need to be based on a time elapsed.

For me, this sounds exactly what Eventstore is doing anyway in a Persistent Subscription.

What we would like to see:

1. Eventstore supports a new "SubscribeToStreamOrdered"
2. Eventstore builds a queue  of ordered events (n) and then publishes them to the client
3. Client registers a new method called EventsAppeared where it receives ResolvedEvents\[\]
4. When this method exits cleanly, Eventstore can send the next batch
5. Internally, the Eventstore does the heavy lifting for checkpoint (number of events or time elapsed)

**Describe alternatives you've considered**

Either we build this locally, or continue to process 1 event at a time

<sub>[DB-378](https://linear.app/eventstore/issue/DB-378/subscribetostreamordered)</sub>

**Comment by alexeyzimarev** [comment]
I just want to clarify that this is about persistent subscriptions aka competing consumers.

**Comment by StevenBlair123** [comment]
@alexeyzimarev  - not specifically.
I would like to harness some of the power of a persistent subscription (the checkpoint writing specifically) inside a new type of subscription (similar to SubscribeToStreamAsync) but instead of receiving 1 event in EventAppeared, we would get ResolvedEvent[] events.

These would be ordered, and Evenstore would be doing the heavy lifting (i.e. reading 1 event at a time until <n>) and publishing to the client.
The Evenstore would be responsible for writing the checkpoint in the same manner a a persistent subscription does (number of events or time elapsed, whatever comes first) rather than a client having to write this.

It's really about batching the next <n> events, and allowing the client to receive this in a single EventsAppeared method.

Hope that makes sense!

**Comment by Narvalex** [comment]
SubscribeToABatchOrOrderedEvents maybe?

**Comment by StevenBlair123** [comment]
I have managed to get a client side version of this working (the code is not pretty) harnessing https://github.com/Eventuous/eventuous. 
I think having this at the server would be nicer, but technically, the client side can be done.

@alexeyzimarev - not sure if this is something you would be interested in including into Eventuous.

**Comment by alexeyzimarev** [comment]
We are going to address it, but outside of the current usual server-client pair.
