### ISSUE TITLE
Subscription heartbeat events

### ISSUE THREAD

**Issue by JoeMarkov** [EventStore/EventStore#2975]
**Is your feature request related to a problem? Please describe.**

As a read-side/projection, I would like to regularly receive a heartbeat event, every x seconds, so that I as a a read-side know that I am still operational and all is go. 

Having a heartbeat would allow my read side to stop accepting queries (or alert the users that the data is a bit old) when it detects that the EventStore is no longer sending data to it.

It could either be sent in case there is no new event in the EventStore for the last x seconds or just sent every x seconds regardless of events in the event store. 

This heartbeat event should not be added to the $all stream of events. Optionally could contain the position of the last event in the EventStore.

This would simplify a lot of the resilience that a projection needs to consider.

**Comment by oskardudycz** [comment]
@JoeMarkov, what type of client are you using, a gRPC one? I think that we won't be exposing heartbeat events for this particular case. We're thinking about adding a similar feature to the gRPC client as it's on TCP client, so getting information when subscription caught up. There's no set deadline for that yet.

**Comment by JoeMarkov** [comment]
I am using the gRPC client in .NET Core. 

I just want as a read side to know that I am still connected to the EventStore and that I am "in the loop" with the eventstore. 

I guess I should try to, like once every x seconds just ping the eventstore to see that I am still good... somehow...  

I just want to make sure that my read-side knows that I am still good and should keep accepting queries.
