### ISSUE TITLE
Want to tune cache autosizing

### ISSUE THREAD

**Issue by timothycoleman** [EventStore/EventStore#2977]
Continues on from https://github.com/EventStore/EventStore/pull/2902

Need to tune the figures and discuss the thread pool min/max threads

**Comment by hayley-jean** [comment]
We should also remember to port any changes done here to 20.10: https://github.com/EventStore/EventStore/issues/2977

**Comment by hayley-jean** [comment]
We have decided to leave the reader thread auto-configuration as-is. The reader thread counts are generally correctly set for the size of the machine, provided that the machine is set up in line with the guidance.

**Comment by tambeau** [comment]
During performance testing against 21.6 with the M8, M16 & M32 instances (based on Sizing rough estimates sent by Chris) we had issue with the test client failing (Preload step). In order to get the test client to run in those instances we had to change the ReaderThreadsCount setting from 6 to 4.

**Comment by hayley-jean** [comment]
We also need to take other caches into account when configuring the streamInfoCache rather than just basing it on the available memory. For example, if you change the chunk cache, there is less memory available to the EventStore process.

**Comment by hayley-jean** [comment]
@timothycoleman and @shaan1337 does https://github.com/EventStore/EventStore/pull/3569 cover this issue?

**Comment by timothycoleman** [comment]
Nah i think the new dynamic sizing is just part of it - preventing it from running out of memory. But it may still be far larger by default than would be optimal for a tyical use case
