### ISSUE TITLE
Add a filter option when reading from a stream

### ISSUE THREAD

**Issue by JoeMarkov** [EventStore/EventStore#2980]
**Is your feature request related to a problem? Please describe.**

When I want to read the last event in the event store (to measure the "gap/lag" from my read side), I use something like this:

`var events = client.ReadAllAsync(Direction.Backwards, Position.End, 1);`

Great! But, that will also include internal $EventStore events.

I want to be able to include a filter, to avoid getting the internal $xxx events to be included when I query for the last event. So that I in a more correct way can estimate the true "gap" between my read-side projection and the head of the eventstore.

Right now just reading the last event will "corrupt" my estimations.

Adding a filter option like we have for subscriptions would be useful here (SubscriptionFilterOptions).

**Comment by MJSanfelippo** [comment]
I would LOVE filters on reading event streams the same way that we can server side filter subscriptions. It would save me a lot of pain and increase performance a lot!
