### ISSUE TITLE
No warning if NLog.config is not found

### ISSUE THREAD

**Issue by LarsKemmann** [EventStore/EventStore#299]
I'm guessing I won't be the only EventStore user who hasn't worked with NLog and thus isn't aware of the requirement for NLog.config to be in the working directory, so could a warning to that effect be added (via stdout or stderr)? Something like: `NLog.config file could not be found in the current working directory.` Hopefully it'll save the next poor chap a few hours of pain. :)

**Comment by dnauck** [comment]
This is added in commit a2780425fcb5050e0757c9cbfc80b4163e671e0a at some parts.

Also related: PR #551
 
@pgermishuys: Like my issue with the not found log.config you should at least enable console logging if nothing (no config file) is found at all

**Comment by jen20** [comment]
This was in 3.1.0 (and subsequently 3.2.0), should have closed this issue earlier.
