### ISSUE TITLE
Unable to build docker image on windows

### ISSUE THREAD

**Issue by pvanbuijtene** [EventStore/EventStore#3013]
Building the docker image on Windows, using Docker Desktop 3.5, results in an error:
```
error from sender: readdir: open src\*: The filename, directory name, or volume label syntax is incorrect.
```

This is caused by `buildkit` and is a known issue: https://github.com/moby/buildkit/issues/1900

A workaround is to set the `DOCKER_BUILDKIT=0` environment variable.

PowerShell:
```
$env:DOCKER_BUILDKIT=0; docker build .
```

**Comment by oskardudycz** [comment]
@pvanbuijtene, @hayley-jean, @ylorph, maybe we could just describe that in README and docs?
