### ISSUE TITLE
Docker Compose example does not work

### ISSUE THREAD

**Issue by zcox** [EventStore/EventStore#3018]
**Describe the bug**

The [`Insecure single node` Docker Compose example](https://developers.eventstore.com/server/v20.10/docs/installation/docker.html#use-docker-compose) does not work.

**To Reproduce**
1. Copy example to docker-compose.yml file
2. Run `docker-compose up`
3. Fail

**Expected behavior**

EventStoreDB should run in a docker container.

**Actual behavior**

```
$ docker-compose up -d
Creating network "eventstoredb-test_default" with the default driver
Creating volume "eventstoredb-test_eventstore-volume-data" with default driver
Creating volume "eventstoredb-test_eventstore-volume-logs" with default driver
Pulling eventstore.db (eventstore/eventstore:20.10.1-buster-slim)...
ERROR: manifest for eventstore/eventstore:20.10.1-buster-slim not found: manifest unknown: manifest unknown
```

After changing the image to `eventstore/eventstore:21.6.0-buster-slim` (this version does [exist in docker hub](https://hub.docker.com/r/eventstore/eventstore/tags?page=1&ordering=last_updated)) the image pulls and tries to run, but fails with this:

```
$ docker-compose logs -f eventstore.db
Attaching to eventstoredb-test_eventstore.db_1
eventstore.db_1  | [    1, 1,14:13:40.261,FTL] Error while parsing options: The option ExtHttpPort is not a known option. (Parameter 'ExtHttpPort')

eventstoredb-test_eventstore.db_1 exited with code 1
```

**Comment by zcox** [comment]
Looks like changing this env var gets it to start up:

```
- EVENTSTORE_HTTP_PORT=2113
```

**Comment by ekjuanrejon** [comment]
Having the same issue

**Comment by grafixen** [comment]
It also seems to work by removing these 2 lines:
` - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113`

**Comment by illegitimis** [comment]
See [this comment](https://github.com/EventStore/EventStore/issues/3146#issuecomment-910531012) for a workaround.

**Comment by timothycoleman** [comment]
This seems to have been fixed somewhere along the way, although the relevant doc is now here https://developers.eventstore.com/server/v20.10/installation.html#use-docker-compose

I'll close this for now, feel free to re-open if you have further problems
Thanks!
