### ISSUE TITLE
Allow subscribing to cluster status over gRPC

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore#3025]
It would be useful if gRPC clients could subscribe to the cluster gossip and receive updates when the cluster changes, for example, if a new leader is elected.

This would reduce the number of retries a client may have to do due to leader changes, and could serve as a way to monitor cluster health.

**Comment by hayley-jean** [comment]
The cluster status will likely send control messages to the streams API as part of RFC https://github.com/EventStore/home/issues/551

**Comment by alexeyzimarev** [comment]
I think we have a PR open for that.
