### ISSUE TITLE
Type unknown in subscription when application/json as content type is not explicit set in append

### ISSUE THREAD

**Issue by ThomasBoettcherHolschen** [EventStore/EventStore#3029]
Hi Eventstore-Team,

When I append Events to a stream and subscribe to a $ce-projection containing that stream I'm currently in trouble deserializing the Contend of the Data-Property from the resolved Event.
ContendType-Property is "application/octet-stream"
EventType-Property is "$>"

**To Reproduce**
1. Create an empty Eventstore from [Docker](https://hub.docker.com/layers/eventstore/eventstore/21.6.0-bionic/images/sha256-ba12c90b904d9c3c9b7d4fa7ca2966e7f4e771dc496801a3c1b0e8ef6b6ea03a?context=explorel) Version 21.6.0
2. Run this litte [Gist](https://gist.github.com/ThomasBoettcherHolschen/9a30815946d1ddc55d7338466ef57369)

**Expected behavior**
I would expect that the class ist serialzed as "application/json" and that both Contend- and EventType Properties are set with 

- ContendType-Property is "application/json"
- EventType-Property is "TestProjection.Dto"

**Actual behavior**
![grafik](https://user-images.githubusercontent.com/2284286/125330403-01f5c800-e347-11eb-965c-901f42d8d301.png)

**Config/Logs/Screenshots**
[    1, 1,17:42:39.805,INF] 
"ES VERSION:"             "21.6.0.0" ("tags/oss-v21.6.0"/"1f713a407", "Thu, 24 Jun 2021 11:49:23 +0400")
[    1, 1,17:42:39.816,INF] "OS:"                     Linux ("Unix 5.4.72.2")
[    1, 1,17:42:39.817,INF] "RUNTIME:"                ".NET 5.0.7" (64-bit)
[    1, 1,17:42:39.818,INF] "GC:"                     "3 GENERATIONS"
[    1, 1,17:42:39.818,INF] "LOGS:"                   "/var/log/eventstore"
[    1, 1,17:42:39.836,INF] MODIFIED OPTIONS:

     START STANDARD PROJECTIONS:              true (Environment Variables)
     INSECURE:                                true (Environment Variables)
     CLUSTER SIZE:                            1 (Environment Variables)
     INT IP:                                  0.0.0.0 (Yaml)
     EXT IP:                                  0.0.0.0 (Yaml)
     HTTP PORT:                               2113 (Environment Variables)
     ENABLE EXTERNAL TCP:                     true (Environment Variables)
     ENABLE ATOM PUB OVER HTTP:               true (Environment Variables)
     RUN PROJECTIONS:                         All (Environment Variables)

DEFAULT OPTIONS:

     HELP:                                    False (<DEFAULT>)
     VERSION:                                 False (<DEFAULT>)
     LOG:                                     /var/log/eventstore (<DEFAULT>)
     LOG CONFIG:                              logconfig.json (<DEFAULT>)
     LOG LEVEL:                               Default (<DEFAULT>)
     CONFIG:                                  /etc/eventstore/eventstore.conf (<DEFAULT>)
     WHAT IF:                                 False (<DEFAULT>)
     DISABLE HTTP CACHING:                    False (<DEFAULT>)
     STATS PERIOD SEC:                        30 (<DEFAULT>)
     WORKER THREADS:                          0 (<DEFAULT>)
     ENABLE HISTOGRAMS:                       False (<DEFAULT>)
     LOG HTTP REQUESTS:                       False (<DEFAULT>)
     LOG FAILED AUTHENTICATION ATTEMPTS:      False (<DEFAULT>)
     SKIP INDEX SCAN ON READS:                False (<DEFAULT>)
     MAX APPEND SIZE:                         1048576 (<DEFAULT>)
     AUTHORIZATION TYPE:                      internal (<DEFAULT>)
     AUTHORIZATION CONFIG:                    <empty> (<DEFAULT>)
     AUTHENTICATION TYPE:                     internal (<DEFAULT>)
     AUTHENTICATION CONFIG:                   <empty> (<DEFAULT>)
     DISABLE FIRST LEVEL HTTP AUTHORIZATION:  False (<DEFAULT>)
     TRUSTED ROOT CERTIFICATES PATH:          <empty> (<DEFAULT>)
     CERTIFICATE RESERVED NODE COMMON NAME:   eventstoredb-node (<DEFAULT>)
     CERTIFICATE FILE:                        <empty> (<DEFAULT>)
     CERTIFICATE PRIVATE KEY FILE:            <empty> (<DEFAULT>)
     CERTIFICATE PASSWORD:                    <empty> (<DEFAULT>)
     CERTIFICATE STORE LOCATION:              <empty> (<DEFAULT>)
     CERTIFICATE STORE NAME:                  <empty> (<DEFAULT>)
     CERTIFICATE SUBJECT NAME:                <empty> (<DEFAULT>)
     CERTIFICATE THUMBPRINT:                  <empty> (<DEFAULT>)
     STREAM INFO CACHE CAPACITY:              0 (<DEFAULT>)
     NODE PRIORITY:                           0 (<DEFAULT>)
     COMMIT COUNT:                            -1 (<DEFAULT>)
     PREPARE COUNT:                           -1 (<DEFAULT>)
     DISCOVER VIA DNS:                        True (<DEFAULT>)
     CLUSTER DNS:                             fake.dns (<DEFAULT>)
     CLUSTER GOSSIP PORT:                     2113 (<DEFAULT>)
     GOSSIP SEED:                             <empty> (<DEFAULT>)
     GOSSIP INTERVAL MS:                      2000 (<DEFAULT>)
     GOSSIP ALLOWED DIFFERENCE MS:            60000 (<DEFAULT>)
     GOSSIP TIMEOUT MS:                       2500 (<DEFAULT>)
     READ ONLY REPLICA:                       False (<DEFAULT>)
     UNSAFE ALLOW SURPLUS NODES:              False (<DEFAULT>)
     DEAD MEMBER REMOVAL PERIOD SEC:          1800 (<DEFAULT>)
     QUORUM SIZE:                             1 (<DEFAULT>)
     PREPARE ACK COUNT:                       1 (<DEFAULT>)
     COMMIT ACK COUNT:                        1 (<DEFAULT>)
     MIN FLUSH DELAY MS:                      2 (<DEFAULT>)
     DISABLE SCAVENGE MERGING:                False (<DEFAULT>)
     SCAVENGE HISTORY MAX AGE:                30 (<DEFAULT>)
     CACHED CHUNKS:                           -1 (<DEFAULT>)
     CHUNKS CACHE SIZE:                       536871424 (<DEFAULT>)
     MAX MEM TABLE SIZE:                      1000000 (<DEFAULT>)
     HASH COLLISION READ LIMIT:               100 (<DEFAULT>)
     DB:                                      /var/lib/eventstore (<DEFAULT>)
     INDEX:                                   <empty> (<DEFAULT>)
     MEM DB:                                  False (<DEFAULT>)
     SKIP DB VERIFY:                          False (<DEFAULT>)
     WRITE THROUGH:                           False (<DEFAULT>)
     UNBUFFERED:                              False (<DEFAULT>)
     CHUNK INITIAL READER COUNT:              5 (<DEFAULT>)
     PREPARE TIMEOUT MS:                      2000 (<DEFAULT>)
     COMMIT TIMEOUT MS:                       2000 (<DEFAULT>)
     WRITE TIMEOUT MS:                        2000 (<DEFAULT>)
     UNSAFE DISABLE FLUSH TO DISK:            False (<DEFAULT>)
     UNSAFE IGNORE HARD DELETE:               False (<DEFAULT>)
     SKIP INDEX VERIFY:                       False (<DEFAULT>)
     INDEX CACHE DEPTH:                       16 (<DEFAULT>)
     OPTIMIZE INDEX MERGE:                    False (<DEFAULT>)
     ALWAYS KEEP SCAVENGED:                   False (<DEFAULT>)
     REDUCE FILE CACHE PRESSURE:              False (<DEFAULT>)
     INITIALIZATION THREADS:                  1 (<DEFAULT>)
     READER THREADS COUNT:                    0 (<DEFAULT>)
     MAX AUTO MERGE INDEX LEVEL:              2147483647 (<DEFAULT>)
     WRITE STATS TO DB:                       False (<DEFAULT>)
     MAX TRUNCATION:                          268435456 (<DEFAULT>)
     CHUNK SIZE:                              268435456 (<DEFAULT>)
     STATS STORAGE:                           File (<DEFAULT>)
     DB LOG FORMAT:                           V2 (<DEFAULT>)
     KEEP ALIVE INTERVAL:                     10000 (<DEFAULT>)
     KEEP ALIVE TIMEOUT:                      10000 (<DEFAULT>)
     INT TCP PORT:                            1112 (<DEFAULT>)
     EXT TCP PORT:                            1113 (<DEFAULT>)
     EXT HOST ADVERTISE AS:                   <empty> (<DEFAULT>)
     INT HOST ADVERTISE AS:                   <empty> (<DEFAULT>)
     ADVERTISE HOST TO CLIENT AS:             <empty> (<DEFAULT>)
     ADVERTISE HTTP PORT TO CLIENT AS:        0 (<DEFAULT>)
     ADVERTISE TCP PORT TO CLIENT AS:         0 (<DEFAULT>)
     EXT TCP PORT ADVERTISE AS:               0 (<DEFAULT>)
     HTTP PORT ADVERTISE AS:                  0 (<DEFAULT>)
     INT TCP PORT ADVERTISE AS:               0 (<DEFAULT>)
     INT TCP HEARTBEAT TIMEOUT:               700 (<DEFAULT>)
     EXT TCP HEARTBEAT TIMEOUT:               1000 (<DEFAULT>)
     INT TCP HEARTBEAT INTERVAL:              700 (<DEFAULT>)
     EXT TCP HEARTBEAT INTERVAL:              2000 (<DEFAULT>)
     GOSSIP ON SINGLE NODE:                   <empty> (<DEFAULT>)
     CONNECTION PENDING SEND BYTES THRESHOLD: 10485760 (<DEFAULT>)
     CONNECTION QUEUE SIZE THRESHOLD:         50000 (<DEFAULT>)
     DISABLE ADMIN UI:                        False (<DEFAULT>)
     DISABLE STATS ON HTTP:                   False (<DEFAULT>)
     DISABLE GOSSIP ON HTTP:                  False (<DEFAULT>)
     ENABLE TRUSTED AUTH:                     False (<DEFAULT>)
     DISABLE INTERNAL TCP TLS:                False (<DEFAULT>)
     DISABLE EXTERNAL TCP TLS:                False (<DEFAULT>)
     PROJECTION THREADS:                      3 (<DEFAULT>)
     PROJECTIONS QUERY EXPIRY:                5 (<DEFAULT>)
     FAULT OUT OF ORDER PROJECTIONS:          False (<DEFAULT>)
     PROJECTION RUNTIME:                      Interpreted (<DEFAULT>)
     PROJECTION COMPILATION TIMEOUT:          500 (<DEFAULT>)
     PROJECTION EXECUTION TIMEOUT:            250 (<DEFAULT>)

[    1, 1,17:42:39.838,WRN] DEPRECATED
The Legacy TCP Client Interface has been deprecated as of version 20.6.0. It is recommended to use gRPC instead.
AtomPub over HTTP Interface has been deprecated as of version 20.6.0. It is recommended to use gRPC instead

[    1, 1,17:42:39.838,WRN] 

INSECURE MODE IS ON. THIS MODE IS *NOT* RECOMMENDED FOR PRODUCTION USE.
INSECURE MODE WILL DISABLE ALL AUTHENTICATION, AUTHORIZATION AND TRANSPORT SECURITY FOR ALL CLIENTS AND NODES.

[    1, 1,17:42:39.934,DBG] MessageHierarchy initialization took 00:00:00.0894660.
[    1, 1,17:42:39.943,INF] Cannot find plugins path: "/usr/share/eventstore/plugins"
[    1, 1,17:42:39.978,INF] Quorum size set to 1.
[    1, 1,17:42:39.989,INF] ReaderThreadsCount set to 8. Calculated based on processor count of 4 and configured value of 0
[    1, 1,17:42:39.990,INF] WorkerThreads set to 10. Calculated based on a reader thread count of 8 and a configured value of 0
[    1, 1,17:42:39.990,INF] StreamInfoCacheCapacity set to 1,770,114. Calculated based on 2,740,228,096 bytes of free memory and configured value of 0
[    1, 1,17:42:39.991,INF] "INSTANCE ID:"            b8b8353c-7ed1-41a6-918e-422201537d2a
[    1, 1,17:42:39.991,INF] "DATABASE:"               "/var/lib/eventstore"
[    1, 1,17:42:39.991,INF] "WRITER CHECKPOINT:"      0 (0x0)
[    1, 1,17:42:39.991,INF] "CHASER CHECKPOINT:"      0 (0x0)
[    1, 1,17:42:39.991,INF] "EPOCH CHECKPOINT:"       -1 (0xFFFFFFFFFFFFFFFF)
[    1, 1,17:42:39.991,INF] "TRUNCATE CHECKPOINT:"    -1 (0xFFFFFFFFFFFFFFFF)
[    1, 1,17:42:40.023,DBG] CACHED TFChunk "#0-0 (chunk-000000.000000)" in 00:00:00.0007689.
[    1, 1,17:42:40.095,INF] Starting MiniWeb for "/web/es/js/projections" ==> "/opt/eventstore/projections"
[    1, 1,17:42:40.095,INF] Starting MiniWeb for "/web/es/js/projections/v8/Prelude" ==> "/opt/eventstore/Prelude"
[    1, 1,17:42:40.101,INF] Starting MiniWeb for "/web" ==> "/opt/eventstore/clusternode-web"
[    1,13,17:42:40.142,INF] ========== ["0.0.0.0:2113"] SYSTEM INIT...
[    1,13,17:42:40.146,INF] Starting "Normal" TCP listening on TCP endpoint: "0.0.0.0:1113".
[    1,18,17:42:40.149,INF] TableIndex initialization...
[    1,13,17:42:40.152,INF] ========== ["0.0.0.0:2113"] Service '"StorageReader"' initialized.
[    1,13,17:42:40.153,INF] ========== ["0.0.0.0:2113"] Service '"StorageWriter"' initialized.
[    1,18,17:42:40.153,INF] ReadIndex building...
[    1,18,17:42:40.154,DBG] ReadIndex rebuilding done: total processed 0 records, time elapsed: 00:00:00.0006143.
[    1,13,17:42:40.157,INF] CLUSTER HAS CHANGED ""
Old:
["Priority: 0 VND {b8b8353c-7ed1-41a6-918e-422201537d2a} <LIVE> [Unknown, Unspecified/127.0.0.1:1112, n/a, Unspecified/127.0.0.1:1113, n/a, Unspecified/127.0.0.1:2113, (ADVERTISED: HTTP::0, TCP::0)] -1/0/0/E-1@-1:{00000000-0000-0000-0000-000000000000} | 2021-07-11 17:42:40.151"]
New:
["Priority: 0 VND {b8b8353c-7ed1-41a6-918e-422201537d2a} <LIVE> [Unknown, Unspecified/127.0.0.1:1112, n/a, Unspecified/127.0.0.1:1113, n/a, Unspecified/127.0.0.1:2113, (ADVERTISED: HTTP::0, TCP::0)] -1/0/0/E-1@-1:{00000000-0000-0000-0000-000000000000} | 2021-07-11 17:42:40.151"]
[    1,13,17:42:40.165,INF] ========== ["0.0.0.0:2113"] Service '"StorageChaser"' initialized.
[    1,13,17:42:40.165,INF] ========== ["0.0.0.0:2113"] SYSTEM START...
[    1,13,17:42:40.166,INF] ========== ["0.0.0.0:2113"] IS UNKNOWN...
[    1,20,17:42:40.168,DBG] Persistent subscriptions received state change to Unknown. Stopping listening
[    1,13,17:42:40.172,INF] ELECTIONS: STARTING ELECTIONS.
[    1,13,17:42:40.172,INF] ELECTIONS: (V=0) SHIFT TO LEADER ELECTION.
[    1,13,17:42:40.173,INF] ELECTIONS: (V=0) VIEWCHANGE FROM ["Unspecified/127.0.0.1:2113", {b8b8353c-7ed1-41a6-918e-422201537d2a}].
[    1,13,17:42:40.174,INF] ELECTIONS: (V=0) MAJORITY OF VIEWCHANGE.
[    1,13,17:42:40.174,INF] ELECTIONS: (V=0) SHIFT TO PREPARE PHASE.
[    1,13,17:42:40.175,INF] ELECTIONS: (V=0) PREPARE_OK FROM "[Unspecified/127.0.0.1:2113,{b8b8353c-7ed1-41a6-918e-422201537d2a}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000} (L={00000000-0000-0000-0000-000000000000}),Priority=0)".
[    1,13,17:42:40.176,INF] ELECTIONS: (V=0) SHIFT TO REG_LEADER.
[    1,13,17:42:40.180,DBG] ELECTIONS: (V=0) Proposing node: {b8b8353c-7ed1-41a6-918e-422201537d2a} as best leader candidate
[    1,13,17:42:40.183,INF] ELECTIONS: (V=0) SENDING PROPOSAL CANDIDATE: "[Unspecified/127.0.0.1:2113,{b8b8353c-7ed1-41a6-918e-422201537d2a}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000} (L={00000000-0000-0000-0000-000000000000}),Priority=0)", PROPOSAL NUMBER 0, ME: "[Unspecified/127.0.0.1:2113,{b8b8353c-7ed1-41a6-918e-422201537d2a}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000} (L={00000000-0000-0000-0000-000000000000}),Priority=0)".
[    1,13,17:42:40.184,INF] ELECTIONS: (V=0) ACCEPT FROM ["Unspecified/127.0.0.1:2113",{b8b8353c-7ed1-41a6-918e-422201537d2a}] M=["Unspecified/127.0.0.1:2113",{b8b8353c-7ed1-41a6-918e-422201537d2a}]).
[    1,13,17:42:40.184,INF] ELECTIONS: (V=0) DONE. ELECTED LEADER = "[Unspecified/127.0.0.1:2113,{b8b8353c-7ed1-41a6-918e-422201537d2a}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000} (L={00000000-0000-0000-0000-000000000000}),Priority=0)". ME="[Unspecified/127.0.0.1:2113,{b8b8353c-7ed1-41a6-918e-422201537d2a}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000} (L={00000000-0000-0000-0000-000000000000}),Priority=0)".
[    1,13,17:42:40.186,INF] CLUSTER HAS CHANGED "Elections Done"
Old:
["Priority: 0 VND {b8b8353c-7ed1-41a6-918e-422201537d2a} <LIVE> [Unknown, Unspecified/127.0.0.1:1112, n/a, Unspecified/127.0.0.1:1113, n/a, Unspecified/127.0.0.1:2113, (ADVERTISED: HTTP::0, TCP::0)] -1/0/0/E-1@-1:{00000000-0000-0000-0000-000000000000} | 2021-07-11 17:42:40.168"]
New:
["Priority: 0 VND {b8b8353c-7ed1-41a6-918e-422201537d2a} <LIVE> [Leader, Unspecified/127.0.0.1:1112, n/a, Unspecified/127.0.0.1:1113, n/a, Unspecified/127.0.0.1:2113, (ADVERTISED: HTTP::0, TCP::0)] -1/0/0/E-1@-1:{00000000-0000-0000-0000-000000000000} | 2021-07-11 17:42:40.185"]
[    1,13,17:42:40.186,INF] ========== ["0.0.0.0:2113"] PRE-LEADER STATE, WAITING FOR CHASER TO CATCH UP...
[    1,20,17:42:40.186,DBG] Persistent subscriptions received state change to PreLeader. Stopping listening
[    1,22,17:42:40.186,DBG] PROJECTIONS SUBSYSTEM: Not stopping because subsystem is not in a started state. Current Subsystem state: Ready
[    1,13,17:42:40.188,INF] ========== ["0.0.0.0:2113"] IS LEADER... SPARTA!
[    1,21,17:42:40.191,DBG] Persistent subscriptions Became Leader so now handling subscriptions
[    1,13,17:42:40.193,DBG] Searching for incomplete scavenges on node "0.0.0.0:2113".
[    1,22,17:42:40.194,INF] PROJECTIONS SUBSYSTEM: Starting components for Instance: dac7e8ab-c117-45d6-85c1-7863ab577480
[    1,22,17:42:40.195,DBG] PROJECTIONS: Projection Core Coordinator component starting. Correlation: dac7e8ab-c117-45d6-85c1-7863ab577480
[    1,22,17:42:40.197,DBG] PROJECTIONS: Starting Projections Core Coordinator
[    1,22,17:42:40.201,DBG] PROJECTIONS: Starting Projections Manager. Correlation: dac7e8ab-c117-45d6-85c1-7863ab577480
[    1,22,17:42:40.203,DBG] PROJECTIONS: Reading Existing Projections from "$projections-$all"
[    1,13,17:42:40.205,DBG] Setting max age for the "$scavenges" stream to 30.00:00:00.
[    1,13,17:42:40.205,DBG] Setting $ops read permission for the "$scavenges" stream
[    1,22,17:42:40.211,DBG] PROJECTIONS SUBSYSTEM: Component '"ProjectionManager"' started for Instance: dac7e8ab-c117-45d6-85c1-7863ab577480
[    1, 1,17:42:40.229,WRN] Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
[    1,13,17:42:40.231,DBG] No incomplete scavenges found on node "0.0.0.0:2113".
[    1,22,17:42:40.232,DBG] PROJECTIONS: SubComponent Started: "EventReaderCoreService"
[    1,22,17:42:40.232,DBG] PROJECTIONS: SubComponent Started: "ProjectionCoreService"
[    1,22,17:42:40.232,DBG] PROJECTIONS: SubComponent Started: "EventReaderCoreService"
[    1,22,17:42:40.232,DBG] PROJECTIONS: SubComponent Started: "ProjectionCoreService"
[    1,22,17:42:40.232,DBG] PROJECTIONS: SubComponent Started: "EventReaderCoreService"
[    1,22,17:42:40.232,DBG] PROJECTIONS: SubComponent Started: "ProjectionCoreService"
[    1,22,17:42:40.232,DBG] PROJECTIONS SUBSYSTEM: Component '"ProjectionCoreCoordinator"' started for Instance: dac7e8ab-c117-45d6-85c1-7863ab577480
[    1,22,17:42:40.232,INF] PROJECTIONS SUBSYSTEM: All components started for Instance: dac7e8ab-c117-45d6-85c1-7863ab577480
[    1,13,17:42:40.233,INF] ========== ["0.0.0.0:2113"] Sub System '"Projections"' initialized.
[    1,22,17:42:40.242,DBG] PROJECTIONS: No projections were found in "$projections-$all", starting from empty stream
[    1,10,17:42:40.279,DBG] === Writing E0@0:{fae22dce-5740-4b4e-b519-72f3b98ba5c4} (previous epoch at -1). L={b8b8353c-7ed1-41a6-918e-422201537d2a}.
[    1,10,17:42:40.289,DBG] === Cached new Last Epoch E0@0:{fae22dce-5740-4b4e-b519-72f3b98ba5c4} (previous epoch at -1) L={b8b8353c-7ed1-41a6-918e-422201537d2a}.
[    1,22,17:42:40.367,DBG] PROJECTIONS: Found the following new projections in "$projections-$all": ["$streams", "$stream_by_category", "$by_category", "$by_event_type", "$by_correlation_id"]
[    1,22,17:42:40.368,DBG] PROJECTIONS: Caught up with projections registration. Next expected version: 5
[    1,22,17:42:40.369,DBG] Adding projection 73e03d7c-6d80-4423-97c4-1dba41596473@"$streams" to list
[    1,22,17:42:40.371,DBG] Adding projection 899c1f03-e638-4453-8490-a0006780af8d@"$by_category" to list
[    1,22,17:42:40.371,DBG] Adding projection 9f43c102-0d58-42db-b77c-781109c8367c@"$stream_by_category" to list
[    1,22,17:42:40.371,DBG] Adding projection 4851c33c-d96a-4017-913e-a012662559f7@"$by_event_type" to list
[    1,22,17:42:40.371,DBG] Adding projection 752f753f-8e13-421a-9221-af3387c97270@"$by_correlation_id" to list
[    1,22,17:42:40.412,INF] '"$stream_by_category"' projection source has been written
[    1,22,17:42:40.414,INF] '"$streams"' projection source has been written
[    1,22,17:42:40.414,INF] '"$by_event_type"' projection source has been written
[    1,22,17:42:40.414,INF] '"$by_category"' projection source has been written
[    1,22,17:42:40.414,INF] '"$by_correlation_id"' projection source has been written
[    1,22,17:42:40.421,INF] Enabling '"$stream_by_category"' projection
[    1,22,17:42:40.422,INF] Enabling '"$streams"' projection
[    1,22,17:42:40.422,INF] Enabling '"$by_event_type"' projection
[    1,22,17:42:40.422,INF] Enabling '"$by_category"' projection
[    1,22,17:42:40.422,INF] Enabling '"$by_correlation_id"' projection
[    1,22,17:42:40.427,INF] '"$streams"' projection source has been written
[    1,22,17:42:40.429,INF] '"$stream_by_category"' projection source has been written
[    1,22,17:42:40.429,INF] '"$by_event_type"' projection source has been written
[    1,22,17:42:40.429,INF] '"$by_category"' projection source has been written
[    1,22,17:42:40.429,INF] '"$by_correlation_id"' projection source has been written
[    1,27,17:43:08.122,INF] Catch-up subscription 0b310b3e-7a34-433d-b0f0-5e7fe3b10885 to "$ce-test"@"0" running...
[    1,27,17:43:08.194,INF] Live subscription 0b310b3e-7a34-433d-b0f0-5e7fe3b10885 to "$ce-test" running from "1"...
[    1,20,17:43:29.292,INF] Live subscription 0b310b3e-7a34-433d-b0f0-5e7fe3b10885 to "$ce-test" disposed.

**EventStore details**
 - EventStore server version: 21.6.0.0

 - Operating system: Windows 10

 - EventStore client version (if applicable): 21.2.0

**Comment by StevenBlair123** [comment]
Might be this:

IsResolved is false, you are only getting the linkTo.
When you create the subscriptino, you should be able to indicate ResolvedTo to true.

**Comment by dnauck** [comment]
@ThomasBoettcherHolschen use the ResolveLinkTos and just ignore events that starts with a `$`

**Comment by ThomasBoettcherHolschen** [comment]
Jupp, my bad. Puzzled arround with it and could not get my head arround it.
Thanks 4 help!
