### ISSUE TITLE
Authorization fails when the users password contains a double point ':'

### ISSUE THREAD

**Issue by michael-hein** [EventStore/EventStore#3058]
**Describe the bug**
Authorization fails when the password of the user contains a double point ':'.

With ES 5.x it was possible to choose a password containing ':' and it works in all other parts of ES. 
With ES 21.6 it can be used in the password but the authentication afterwards fails.
![image](https://user-images.githubusercontent.com/51996054/126306231-2bab2019-f95a-4b33-8855-29f6a1949cb1.png)
![image](https://user-images.githubusercontent.com/51996054/126303988-20bea75a-f854-4fd7-9001-e5708368e02f.png)

**To Reproduce**
1. create a new user over the UI as an admin and add a ':' to the password. E.g '123:'
2. login with the new user and try to go to "Persistent Subscriptions" or "Users".

**Expected behavior**
If the password contains some special chars like ':' and it is possible to login with this credentials, that all other function which should be allowed by this user, can be used with these credentials.

**Actual behavior**
Some functions can't be used. ("Persistent Subscriptions" or "Users",  reading some streams...)

**EventStore details**
 - EventStore server version: 21.6
 - Operating system: docker

**Comment by StevenBlair123** [comment]
@michael-hein  - I had a quick look at this and the code for parsing up the username and password is split on a ":" delimiter.
if the Evenstore code does not get 2 elemens (name and password) it defaults to annoymous user (hence the authentication errors)
The function in question is TryDecodeCredential in BasicHttpAuthenticationProvider.

I am unsure if this value can be posted up differently, or whether the UI should block the "::" or alternatively, the function could be tweaked to say >= 2 and just take the [0] as name, and [1] as password.

@hayley-jean - I would be happy enough doing this server change if you think it makes sense.

**Comment by michael-hein** [comment]
@StevenBlair123 thanks for your quick look.

The solution to tweak the implementation, so that any char can be used for the password would be the best solution.

But when the UI would block the ":" in the password, that would be fine too. 
I didn't tested it out, but does the client-library then treats it the same way and block the ":"? https://developers.eventstore.com/clients/dotnet/5.0/security/users.html#create-a-user

**Comment by StevenBlair123** [comment]
Yeah, the UI should have blocked the password imo.
I suspect either change is straight forward.
Can wait and see what the ES staff think.

**Comment by hayley-jean** [comment]
Thanks for reporting this! A password should be allowed to have `:` in it, so we would want to fix the server implementation rather than preventing it in the UI

**Comment by StevenBlair123** [comment]
I can sort this.

**Comment by hayley-jean** [comment]
Fixed by https://github.com/EventStore/EventStore/pull/3070
Thanks @StevenBlair123!
