### ISSUE TITLE
Required `TrustedRootCertificatesPath` for windows hosted ESDB

### ISSUE THREAD

**Issue by milkshakeuk** [EventStore/EventStore#3068]
**Is your feature request related to a problem? Please describe.**
We have been using ESDB since 2017, we are currently running version 5.0.10 hosted on windows server, we would like to upgrade to 21.6 however since version 20.X there is a new required server configuration setting `TrustedRootCertificatesPath` if you want to run ESDB securely, I understand why this configuration option might have been added to make running ESDB more portable i.e. good for docker etc and makes sense for Linux hosts since the `ca_certs` file has a path, but typically when hosting using windows the Certificate store is used for storing the Trusted Root Certificates, also there is the problem that there might be more than one trusted root certificate (we have 19 in our certificate store under `Trusted Root Certification Authorities\Certificates`).

This leaves us in a bit of a pickle where we are blocked from upgrading.

**Describe the solution you'd like**
There is probably more than one way this could be solved but my suggestion would be:

Bring back as a configurable option the ability to point to the `Trusted Root Certification Authorities\Certificates` certificate store path when ESDB is hosted on windows where it could check all the available CA certs until there is a match (presumably as it did before).

Or some other configurable way that works with the above scenario.

**Describe alternatives you've considered**
Create a custom CA_CERTS file? but I'm not sure what the repercussions of that would be. 
JIRA server as an example comes with its own CA_CERTS file when you install it, perhaps ESDB could ship with a CA_CERTS file? and you can add any missing certificates to it yourself?

**Additional context**
This is currently blocking is from upgrading to ESDB 21.6

**Comment by alexeyzimarev** [comment]
I believe that `TrustedRootCertificatesPath` should not be a required setting, particularly when the `CertificateReservedNodeCommonName` is set to a non-default value, which means that most probably the certificate used is not a self-signed cert. In this case, the server should assume the certificate is trusted and the root CA certificate is in the OS certificate store, so there's no need to engage with an additional store or location.

**Comment by alexeyzimarev** [comment]
@milkshakeuk could you please clarify if you use self-signed certificates and add the root CA certificate to the store on the server, or you use the certificate signed by the trusted CA?

**Comment by milkshakeuk** [comment]
@alexeyzimarev the certificates we use for the ESDB nodes are not self-signed they are signed by a Trusted Root CA, also they are however wildcard certs *.madeupdomain.org which was user like so node1.madeupdomain.org, node2.madeupdomain.org etc, not sure if that makes a difference.

**Comment by shaan1337** [comment]
For simplicity, i suggest that we should support 2 mutually exclusive modes for loading certificates: either from the store or from a directory/file path but not both.

We can add a `TrustedRootCertificatesStoreName` parameter which allows loading of trusted root certs from the windows store, then:

If the `CertificateFile` parameter is present, then the `TrustedRootCertificatesPath` parameter becomes mandatory
If the `CertificateSubjectName` parameter or the `CertificateThumbprint` parameter is present (which are used only for loading from store), then the `TrustedRootCertificatesStoreName` parameter becomes mandatory

**Comment by alexeyzimarev** [comment]
@shaan1337 it is still unclear for me why `CertificateFile` would require `TrustedRootCertificatesPath`. Certificates signed by a trusted CA are trusted by the OS, there's no need to add the path in such cases. `TrustedRootCertificatesPath` should only be required for self-signed certificates.

**Comment by oskardudycz** [comment]
I talked with @hayley-jean, and I'll try to work on that. Currently, the assumption is that we won't be requiring a path, but a windows store name. The idea is to "double" current path settings. I'll try to draft a solution in the next week or two, and provide RFC to discuss the details.

**Comment by alexeyzimarev** [comment]
Basically, between the versions something got broken. Before, pointing the `TrustedRootCertificatesPath` setting to `/etc/ssl/certs` worked as the server loaded all the certificates there (seems like). With the latest version, it tries to load **only the first one** available there, and then it fails since the first loaded root certificate doesn't match the actual certificate (the root cert is there in the directory, but it's not the first one, obviously).

I have to copy the root certificate to a separate directory, then change the `TrustedRootCertificatesPath` to point there, and then it works. It's very strange, as I never experienced such behaviour from any other software that uses certificates signed by a trusted authority.

```
{"@t":"2021-12-12T13:52:31.7464611+01:00","@mt":"Loading trusted root certificate. Subject: {subject}, Thumbprint: {thumbprint}","@l":"Information","@i":1874726621,"subject":"CN=Starfield Services Root Certificate Authority - G2, O=\"Starfield Technologies, Inc.\", L=Scottsdale, S=Arizona, C=US","thumbprint":"925A8F8D2C6D04E0665F596AFF22D863E8256F3F","SourceContext":"EventStore.Core.ClusterVNode","ProcessId":196296,"ThreadId":1}
{"@t":"2021-12-12T13:52:31.7489960+01:00","@mt":"Certificate with thumbprint 'A053375BFE84E8B748782C7CEE15827A6AF5A405' does not appear to be a valid root certificate since it is not self-signed (subject = CN=R3, O=Let's Encrypt, C=US, issuer = CN=ISRG Root X1, O=Internet Security Research Group, C=US). If you have intermediate certificates, please bundle them with the node's certificate (in PEM or PKCS #12 format).","@l":"Error","@i":3403168325,"SourceContext":"EventStore.Core.ClusterVNode","ProcessId":196296,"ThreadId":1}
{"@t":"2021-12-12T13:52:31.7501088+01:00","@mt":"Invalid Configuration: Aborting certificate loading due to verification errors.","@l":"Fatal","@i":2441781601,"ProcessId":196296,"ThreadId":1}
```

**Comment by shaan1337** [comment]
> it is still unclear for me why `CertificateFile` would require `TrustedRootCertificatesPath`. Certificates signed by a trusted CA are trusted by the OS, there's no need to add the path in such cases. `TrustedRootCertificatesPath` should only be required for self-signed certificates.

@alexeyzimarev there are a couple of reasons why we require the `TrustedRootCertificatesPath` parameter:
- the majority of users use certificates generated by a private CA since they run EventStoreDB in a private network and they do not have the need to expose EventStoreDB over the public internet. IMHO, the configuration options should be designed for the majority first, but we should still provide the ability to have public CA-based setups by tweaking the configuration params.

- For security reasons, we want to stay away from requiring the user to make changes to the operating system's trusted root certificates - EventStoreDB should be able to function independently. This also helps for testing on CI.

- When a node connects to another node in the cluster, one of them is the server and the other one the client. The connection is mutually authenticated on both sides.  The node acting as the server needs to be able to verify the certificate from the node acting as the client. When the "server" node builds the chain, it trust only root certificates present in the `TrustedRootCertificatesPath` directory - otherwise an arbitrary certificate signed by a public CA could have been provided by the "client" node and it would have been happily accepted (which would be a security flaw)

**Comment by alexeyzimarev** [comment]
@shaan1337 I am not sure about the first point. Event Store Cloud runs in a private VPC but it uses a trusted root CA. There's nothing that forces people to use self-signed certificates when running behind firewalls and using private IPs. I checked CockroachDB as a reference and they have a setting for a "custom CA", which is optional. They use the OS root certificates by default.

MongoDB as another example [_discourages_](https://docs.mongodb.com/manual/tutorial/configure-ssl/) people from using self-signed certificates, and they only require to specify the certificate file, then use the OS trusted root CAs to verify the certificate.

**Comment by oskardudycz** [comment]
@shaan1337 @alexeyzimarev, side note, the case you're discussing here, is different from the one that @milkshakeuk posted. This issue is about setting on Windows machines. They quite often have certificates distributed through the certification store via Active Directory. That's a valid case, and we should not be required to provide the path, as that's not recommended on Windows.

**Comment by oskardudycz** [comment]
@shaan1337, on the other hand, shouldn't just nodes have public certs from the other nodes and use them to decrypt connections? If each node has its own private/public certs pair and all the others had public, wouldn't it be the preferable option? That wouldn't require CA at all.

**Comment by shaan1337** [comment]
@oskardudycz @alexeyzimarev just summarizing the current state of the discussion before we continue:

| Scenario ID | Public/Private CA | Certificate Loaded From | Trusted Root Certs Loaded From | Supported?                                                                                                                                                                                                                                                                                                                                                                                                                     | Status                  | Suggested changes                                                                                                                                            |
|-------------|-------------------|-------------------------|--------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1           | Private           | File                    | Path                           | - Supported with CertificateFile and TrustedRootCertificatesPath                                                                                                                                                                                                                                                                                                                                                               | Fully supported         | No issue here                                                                                                                                                |
| 2           | Private           | Store                   | Store                          | - Loading certificate from store supported with CertificateSubjectName or CertificateThumbprint but there's still this issue to be fixed: https://github.com/EventStore/EventStore/pull/2990<br>- Loading trusted root certificates from store not yet supported.                                                                                                                                                              | Not supported           | (Shaan) Fix issue #2990<br>(Shaan) Add new option: TrustedRootCertificatesStoreName                                                                          |
| 3           | Public            | File                    | OS                             | - Supported with CertificateFile, TrustedRootCertificatesPath and CertificateReservedNodeCommonName.<br>- Linux: TrustedRootCertificatesPath needs to be set to /etc/ssl/certs or the public root CA can be extracted to a directory<br>- Windows: TrustedRootCertificatesPath needs a directory with the public root CA extracted                                                                                             | Supported but not ideal | (Alexey) Remove the need for TrustedRootCertificatesPath when CertificateReservedNodeCommonName is set                                                       |
| 4           | Public            | Store                   | OS                             | - Loading certificate from store supported with CertificateSubjectName or CertificateThumbprint but there's still this issue to be fixed: https://github.com/EventStore/EventStore/pull/2990<br><br>- Linux: TrustedRootCertificatesPath needs to be set to /etc/ssl/certs or the public root CA can be extracted to a directory<br>- Windows: TrustedRootCertificatesPath needs a directory with the public root CA extracted | Supported but not ideal | (Shaan) Fix issue #2990<br>(Shaan) Add new option: TrustedRootCertificatesStoreName which would need to be set to the name of the default trusted root store |

**Comment by shaan1337** [comment]
@alexeyzimarev @oskardudycz 

I have another suggestion which covers scenarios 2,3 and 4 in a single change:

What if we add support for some special values that `TrustedRootCertificatesPath` can take:
- `OS` - this would cause EventStoreDB to trust the default operating system CA certs.
- `cert:\LocalMachine\MyCustomStore` - allows the use of a custom trust store on Windows (see format details [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-7.2#creating-certificate-stores))

For usability:
- the [configurator](https://configurator.eventstore.com/) could be updated to cater for above scenarios
- error messages related to `TrustedRootCertificatesStoreName` need to be changed to give a hint to the user that `OS` is also possible value.

**Comment by milkshakeuk** [comment]
@shaan1337 @oskardudycz @alexeyzimarev has there been any progress on this?
