### ISSUE TITLE
Establish gRPC Client base as the Minimum Viable Tier

### ISSUE THREAD

**Issue by tambeau** [EventStore/EventStore#3084]
### Minimum Viable Tier
This is the minimum required to write an application connecting to Event Store. Not all features are available, but the ones that are most commonly used are.

We will support these clients, but users must accept that some features are not going to be available to them.

**References**:
- [Client Tiers](https://github.com/EventStore/architecture-and-planning/blob/main/phase-planning/2021-phase-3-planning/grpc-client-tiers.md)
- [Current apis](https://github.com/EventStore/architecture-and-planning/blob/main/phase-planning/2021-phase-3-planning/current-grpc-client-apis.md)

**List of clients supported at this tier**:
- .Net
- Rust
- Java
- Node
- GoLang

The Go client is still in early development and should meet the Minimum Viable Tier but may take a tad longer to achieve.

**Note**: 
We will need to put in the code for those calls that are to be retired a warning that can be published to the log. This is to remind users that the call is subject to change, temporary in nature and that they will need to be prepared to change it in the near future.

This allows us to warn them of coming change, to use caution and to have a plan for when we do change it ... depreciation warning

**Connectivity**:
Covered by RFC: [#574](https://github.com/EventStore/architecture-and-planning/blob/main/rfcs/574-connectivity-in-grpc-clients.md)

- Cluster connection with NodePreferences Leader, Follower, Random, ReadOnlyReplica
- Use NodePreference Leader as default
- Reconnection after the loss of a node
- ~Timeout after configured, to be determined in RFC: [Home#477](https://github.com/EventStore/home/issues/477)~
- Fully supported connection string, with sensible warnings where some settings don't make sense
- Ability to set RequiresLeader header

**Streams API:**
~This should eventually be defined in the RFC: [Home#551](https://github.com/EventStore/home/issues/551)~

- AppendToStream (Using both Append and BatchAppend)
- SoftDelete - To Be Renamed to Delete
- Tombstone
- ReadAll
- ReadStream
- SubscribeToAll (with filter)
- SubscribeToStream
- GetStreamMetadata (using the streams API)
- SetStreamMetadata (using the streams API)

**Persistent Subscriptions API:**
As defined in RFC: [#022](https://github.com/EventStore/architecture-and-planning/blob/main/rfcs/022%20-%20gRPC%20Persistent%20Subscriptions.md)

- CreateToStream
- CreateToAll
- Update
- UpdateToAll
- Delete
- DeleteToAll
- ReplayParkedMessages
- GetInfo
- RestartPersistentSubscriptionSubsystem
- ListAll
- ListForStream
- Subscribe
- SubscribeToAll

**Samples for documentation:**

- Appending Events
- Connecting to a cluster
- Connecting to a single node
- Persistent Subscriptions
- Quick Start
- Reading Events
- Secure with TLS
- Server-side Filtering
- Subscribing to Streams

**Change log**:
- Automated changelog updates based on PRs
- The changelog is tied to each version

**Comment by alexeyzimarev** [comment]
I think we should add the connection string support across all the clients.

Also, we need to explain how to use gossip for connecting, depending on the node preference.

**Comment by tambeau** [comment]
Note: The following server protocols have been added:
 ReplayParkedMessages
 GetInfo
 RestartPersistentSubscriptionSubsystem
 ListAll
 ListForStream
 SubscribeToAll
