### ISSUE TITLE
How to stop reply all events when bumping the endpoint version number

### ISSUE THREAD

**Issue by AbdoDabbas** [EventStore/EventStore#3106]
**Describe the bug**
I'm using a library [Aggregates.NET](https://github.com/charlessolar/Aggregates.NET/) to build an endpoint that registers a "Persistent Subscriptions", but each time I change the assembly version number of the endpoint it registers a new **Persistent Subscription** with the version number and EventStore replays ALL events that already reached this endpoint starting from the first event.

How can I disable this (if I can).

**EventStore details**
 - EventStore server version: v20.6.1.0

 - Operating system: Windows 10 x64

**Comment by AbdoDabbas** [comment]
Any response?

**Comment by hayley-jean** [comment]
Hi @AbdoDabbas, if you don't want to replay all of the events that you have already seen then you need to make sure that your consumers subscribe to the Persistent Subscription that originally handled those events.

If you create a new Persistent Subscription it won't have any checkpoints and will therefore start from the beginning (or whatever the `StartFrom` property was set to).

I don't know how the Aggregates.NET library works, or whether it handles the Persistent Subscription creation for you, but is there a reason that a new one is created every time the version changes?

**Comment by AbdoDabbas** [comment]
Hi @hayley-jean,
Aggregates.NET creates Projections, those projections if I added new event or changed a name of an old event, it throws and exception (maybe ES does) saying this version has projection but not with the same events (the Source of the projection is not the same as the one generated after adding the event to the system).

**Comment by ylorph** [comment]
Some small targetd reproduction would be helpfull

**Comment by oskardudycz** [comment]
Closing it because of inactivity.
