### ISSUE TITLE
SubscribeAsync to set autoAck to false as default

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3113]
What would be your thoughts on on setting autoAck default to false in _EventStorePersistentSubscriptionClient.SubscribeAsync_
We had recently went through an upgrade in some of our code, and we stopped passing this (appreciate this is a code problem from our side) but the impact was events were failing, but still being ACK'd.

This got me thinking that maybe the safer approach would be to force the ACK incase the developer has made a mistake here.
At least if they set the wrong value (or none at all) the events are still sitting in the parked queue.

From our mistake, we have a lot of events now ACK'd and no easy way of replaying them (it's a very big stream, and we don't want to replay it)

Just a thought.

**Comment by StevenBlair123** [comment]
@hayley-jean - thanks. Didn't think about changing the checkpoint!

**Comment by oskardudycz** [comment]
@StevenBlair123, fix should be available in the next .NET client release.
