### ISSUE TITLE
"Hidden" streams

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3150]
**Is your feature request related to a problem? Please describe.**
We have a projection which emits enriched events and do not want them picked up by fromAll() (the original events have already been processed). To prevent fromAll from processing the events, our enricher writes to a stream prepended with "$projections-".

This could cause problems with Evenstore as I don't think it was intended for developers to use the system streams in such a way.

**Describe the solution you'd like**
A new idea of a "hidden" stream where developers can write events to, but won't be picked up by fromAll (but would be picked up if you explictly reference the stream). 

For example:

`$hidden-myprojection-result`

This would **not** get processed by `fromAll()`

but **would** get processed by `fromStream('$hidden-myprojection-result')`

**Describe alternatives you've considered**
Continue to use $projection-

**Additional context**

@ylorph - thanks for assistance on this

**Comment by oskardudycz** [comment]
@StevenBlair123, I think that this idea is valid, currently, you could filter that out in the projection handling code. For sure we do not recommend using `$` stream name, as those are internal ESDB streams and the handling may change. Still, I think that we should support such feature eventually, I'm not sure tho about when we could work on that.

**Comment by StevenBlair123** [comment]
@oskardudycz  - thanks for the reply.
We have stopped using the $ stream name and filter at the server side for those unwanted events (which unfortunately is millions of events)

**Comment by alexeyzimarev** [comment]
I think using filters is a good approach, hopefully we'll introduce something better soon.
