### ISSUE TITLE
Issue certificate with cloudflare and esdb - DeadlineExceeded

### ISSUE THREAD

**Issue by MinhMit** [EventStore/EventStore#3152]
Hello,
I'm new developer for eventstore
I try setting certificate to eventstore.
With admin UI it work, but when i request from my code it not working

i'm using nginx to pass_proxy to eventstore

I have eventstore.conf

![eventstoreconf](https://user-images.githubusercontent.com/5819667/132124519-bc0b789b-8576-453b-949e-74f3b824868a.png)

nginx config

![nginxconf](https://user-images.githubusercontent.com/5819667/132124533-bf7ac31c-fcbf-4d61-a45c-148c120c7cce.png)

and appendstream code as:

![codeCore](https://user-images.githubusercontent.com/5819667/132124543-ba45e278-5a3a-42a4-b464-e5ea43287513.png)

i config eventstore with code

`services.AddEventStoreClient("esdb://admin:changeit@esdb.megiservices.com:2113?tls=true");`
or
`services.AddEventStoreClient("esdb://admin:changeit@esdb.megiservices.com?tls=true");`
or
`services.AddEventStoreClient("esdb://admin:changeit@96.9.211.102?tls=true");`

in cloudflare i add an dns record 

![cloudflare](https://user-images.githubusercontent.com/5819667/132124632-ffb24685-889e-4de4-a88a-8488ead7ce0c.png)

it's working when i request to https://esdb.megiservices.com/

but i retrieve error when call eventstore via code. Message:

Status(StatusCode="DeadlineExceeded", Detail="")

What can i do to fix this issue?

I using:

EventStore.Client.Grpc.Streams : 20.10.0
Grpc.Net.Client: 2.38.0

Thanks for your support

**Comment by hayley-jean** [comment]
Hi @MinhMit, the Deadline Exceeded error usually means that the request took too long to complete.

How many domain events are on your aggregate and being appended to the stream in Event Store? And how large are the events?
Do you see this issue with a later version of the gRPC streams client? For example, with version 21.2?

**Comment by MinhMit** [comment]
> Hi @MinhMit, the Deadline Exceeded error usually means that the request took too long to complete.
> 
> How many domain events are on your aggregate and being appended to the stream in Event Store? And how large are the events?
> Do you see this issue with a later version of the gRPC streams client? For example, with version 21.2?

Thanks for your support,
My aggregate has only one domain event. 
In my case is only CreatedDomainEvent in aggregate.
Yess, i'm tried use client 21.2.0 but same error.

once again, thanks for your support.

**Comment by MinhMit** [comment]
> h
