### ISSUE TITLE
Cannot login via web UI with any other user than "admin" ( v.5.* )

### ISSUE THREAD

**Issue by JulianMay** [EventStore/EventStore#3191]
**Describe the bug**
When attempting to login with a user different from admin, nothing visually happens. 
Inspecting the browser debugger, the GET request for `http://localhost:2113/users/{username}` returns **401 Unauthorized**, with no content.

The users permissions (set in the default ACL) works via the API, and the UI "works" if you access specific URL, f.eks http://localhost:2113/web/index.html#/streams/testing, after a "failed" login. 

Tried giving the user every permission in the default-ACL, this has no effect.

Yes, I'm super certain I'm not typing the wrong password.

Verified that it works as expected in v. 4.1.0.0

Verified that the problem persists across browsers (tested in Chrome, Firefox and Edge)

**To Reproduce**
1. Create a new user via the UI ( log in as admin -> Users -> New user ), let's say we call this user _**ajoursupport**_
2. Give the user read-permissions in the default ACL, by posting the following **update-default-acl** -event to the _**$settings**_ stream:
```
{
  "$userStreamAcl": {
    "$r": [
      "$admin",
      "$ops",
      "ajoursupport"
    ],
    "$w": [
      "$admin",
      "$ops"
    ],
    "$d": [
      "$admin",
      "$ops"
    ],
    "$mr": [
      "$admin",
      "$ops",
      "ajoursupport"
    ],
    "$mw": [
      "$admin",
      "$ops"
    ]
  },
  "$systemStreamAcl": {
    "$r": [
      "$admins",
      "ajoursupport"
    ],
    "$w": "$admins",
    "$d": "$admins",
    "$mr": [
      "$admins",
      "ajoursupport"
    ],
    "$mw": "$admins"
  }
}
```

3. In a browser, go to `{http-uri for eventstoreDb}/web`

4. Try to login with the new user

**Expected behavior**
I expect the user to be redirected to the "Streambrowser"-page (or the "Dashboard"-page), without any **401 Unauthorized** responses

**Actual behavior**
No visual feedback. Backend returns 401 Unauthorized to client

**Config/Logs/Screenshots**
![image](https://user-images.githubusercontent.com/1412348/134628932-30c97aad-171b-4882-9720-5ff1724fe613.png)

The UI request/response when clicking “Sign in” looks like this (no content):

  ```
  Request URL: http://localhost:2113/users/ajoursupport
  Request Method: GET
  Status Code: 401 Unauthorized
  Remote Address: [::1]:2113
  Referrer Policy: strict-origin-when-cross-origin
  
Request headers:
	  Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Forwarded-Host, X-Forwarded-Prefix, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTos
	  Access-Control-Allow-Methods: GET, PUT, DELETE, OPTIONS
	  Access-Control-Allow-Origin: *
	  Access-Control-Expose-Headers: Location, ES-Position, ES-CurrentVersion
	  Content-Encoding: gzip
	  Content-Length: 0
	  Date: Thu, 02 Sep 2021 08:16:16 GMT
	  Server: Microsoft-HTTPAPI/2.0
	  WWW-Authenticate: BasicCustom realm="ES",Basic realm="ES"
	  
  Response headers:
	  Accept: application/json
	  Accept-Encoding: gzip, deflate, br
	  Accept-Language: da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7
	  Authorization: Basic YWpvdXJzdXBwb3J0OlExMjN3MjM0
	  Cache-Control: no-cache
	  Connection: keep-alive
	  DNT: 1
	  ES-LongPoll: 5
	  Host: localhost:2113
	  Pragma: no-cache
	  Referer: http://localhost:2113/web/index.html
	  sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"
	  sec-ch-ua-mobile: ?0
	  Sec-Fetch-Dest: empty
	  Sec-Fetch-Mode: cors
	  Sec-Fetch-Site: same-origin
	  sec-gpc: 1

```

***Story: Can access streams after failed login (basic-auth headers in request works):***

_With no authentication, stream cannot be read:_
![image](https://user-images.githubusercontent.com/1412348/134629413-a429354b-cb73-4f1b-be2e-227237dd4548.png)

_Failed login:_
![image](https://user-images.githubusercontent.com/1412348/134629615-3fbe2a84-88ca-4860-b1ab-e5ddc74a5f88.png)

_Stream can now be read (note the Authorization request-header in this an previous):_
![image](https://user-images.githubusercontent.com/1412348/134629816-3b0a5a07-48aa-40ea-b18d-0ba9af9bf4f2.png)

**EventStore details**
 - EventStore server version:
    - 5.0.9.0
    - 5.0.10.0
    - 5.0.11.0

 - Operating system:
    - Windows 10 Pro ( 20H2, not sure about which specific version for the other computers we've tested it on )

 - EventStore client version (if applicable):
    - Not applicable

**Additional context**
I might be missing something obvious, but nothing came up in https://discuss.eventstore.com/t/cannot-login-to-ui-with-any-user-besides-admin/3498 , so I'm suspecting it's a regression error

**Comment by hayley-jean** [comment]
Hi @JulianMay this should be fixed in versions 20.10 and 21.10. I'm going to close this issue for now, but if you still experience this on later versions then please reopen
