### ISSUE TITLE
Batch append response returns corelation id as structured UUID instead of string

### ISSUE THREAD

**Issue by pivonroll** [EventStore/EventStore#3218]
**Is your feature request related to a problem? Please describe.**
In all other GRPC methods uuids are returned as string UUID but in batch append, correlation id is returned as structured UUID.

**Describe the solution you'd like**
Make correlation id returned as string UUID for batch append response.

**Describe alternatives you've considered**
None.

**Additional context**
Issue is in file ~/EventStore/src/EventStore.Core/Services/Transport/Grpc/Streams.BatchAppend.cs at line 
batchAppendResp.CorrelationId = Uuid.FromGuid(correlationId).ToDto();

**Comment by oskardudycz** [comment]
@hayley-jean @YoEight, do you know if that wasn't fixed already?

**Comment by hayley-jean** [comment]
Hi @pivonroll, I believe that this should have been fixed by https://github.com/EventStore/EventStore/pull/3255
Could you let us know if you're still seeing this on later versions?
