### ISSUE TITLE
Starting and Stopping Embedded Server rapidly causes hang

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#322]
This is still an issue, opening new issue because last one #312 was closed without solution.

Repro: Start and stop the embedded vnode server in a loop.

[Or run these tests, replacing `with_real_es` with `with_embedded_es`](https://github.com/haf/EventStore.Client.FSharp/blob/feature/readmodels/src/EventStore.ClientAPI.FSharp.Tests/ProjectionsTests.fs#L34).

These tests also are relevant to the other 404-status-code issue I filed today.

Trace:

```
mono src/EventStore.ClientAPI.FSharp.Tests/bin/Debug/EventStore.ClientAPI.FSharp.Tests.exe
starting embedded EventStore
... waiting for server to get ready ...
stopping embedded EventStore
stopped embedded EventStore
starting embedded EventStore
Exiting with exit code: 1.
Exit reason: Http async server failed to start listening at [http://127.0.0.1:2113/, http://localhost:2113/].
Segments count: 1, buffers count: 512, should be when full: 512
stopping embedded EventStore
stopped embedded EventStore
starting embedded EventStore
^C
```

**Comment by gregoryyoung** [comment]
closing as PR is accepted. If you have issues just drop a note here

**Comment by haf** [comment]
Thanks, when do you publish a pre-release that I can use? I want to target nuget packages against something official. Years in the castle project taught me that it's a pain in the ass to custom-build all your dependencies.

**Comment by gregoryyoung** [comment]
There is 3.0.2 which is in the pipeline. My guess is it will be out in the
next week or two on a pre basis as I don't know any pressing changes in
progress on it. There are nightly or weekly builds of dev in process

On Tuesday, January 6, 2015, Henrik Feldt <notifications@github.com> wrote:

> Thanks, when do you publish a pre-release that I can use? I want to target
> nuget packages against something official. Years in the castle project
> taught me that it's a pain in the ass to custom-build all your dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/322#issuecomment-68842073>
> .
>


-- 
Studying for the Turing test

**Comment by haf** [comment]
Would be great to get it next week ;)
