### ISSUE TITLE
Projection -> UI & "Cluster status" > "Show website" 

### ISSUE THREAD

**Issue by ylorph** [EventStore/EventStore#3221]
**Describe the bug**
Exposed URL  to go to the details of a projections does not use the external dns name , but the internal dns name 
whe using the administration UI through the external dns name.

*The same for "Show Website" on the cluster status page* 

**To Reproduce**
1. create a cluster with different External & Internal DNS Names
2. go to UI > Projection through the external address
3. click on one of the projection to see the details 

**Expected behavior**
THe URL list  exposed by the server should use the same base URL used to browse  / GET the list of projections 

**Actual behavior**

**Config/Logs/Screenshots**

![image](https://user-images.githubusercontent.com/10076395/136807164-fcc017a4-20c8-4067-8090-00bcfe40eef9.png)

https://localhost:42113/web/index.html#/projections/https%253A%252F%252Fcluster-node-2.es%253A42113%252Fprojection%252F%2524by_category

in the url above `localhost` is the external dns address , `cluster-node-2.es` is the internal dns address

it should be 
https://localhost:42113/web/index.html#/projections/https%253A%252F%252Flocalhost %253A42113%252Fprojection%252F%2524by_category

![image](https://user-images.githubusercontent.com/10076395/136807834-f24cce4b-29c5-4eb0-87a8-cac19a582b90.png)

**EventStore details**
 - EventStore server version: 21.10

 - Operating system: / 

 - EventStore client version (if applicable): /

**Additional context**
QA cycle

**Comment by oskardudycz** [comment]
@ylorph, it might be fixed in 21.10 or 20.10.5. It's worth double-checking.
