### ISSUE TITLE
actual version is not included in delete/tombstone stream WrongExpectedVersion error

### ISSUE THREAD

**Issue by the-mikedavis** [EventStore/EventStore#3226]
**Describe the bug**

The actual version of a stream is not included in the WrongExpectedStreamRevision rpc error when making a DeleteStream or TombstoneStream gRPC request with an expectation that does not match the reality.

**To Reproduce**

1. write an event to a stream
2. attempt to delete or tombstone the stream with expected version being anything other than 0, Exists, or Any

Using the Elixir client (should be possible with any gRPC client, I'm just too lazy to learn the others :)

```elixir
iex> [Spear.Event.new("test-event", %{})] |> Spear.append(conn, "test-stream")
:ok
iex> Spear.stream!(conn, "test-stream") |> Enum.count()
1
# so the expected version is 0
# now we delete with an incorrect expectation
iex> Spear.delete_stream(conn, "test-stream", expect: 4)
{:error,
 %Spear.Grpc.Response{
   data: "",
   message: "Append failed due to WrongExpectedVersion. Stream: test-stream, Expected version: 4, Actual version: ",
   status: :failed_precondition,
   status_code: 9
 }}
# here's another incorrect expectation
iex> Spear.delete_stream(conn, "test-stream", expect: :empty)
{:error,
 %Spear.Grpc.Response{
   data: "",
   message: "Append failed due to WrongExpectedVersion. Stream: test-stream, Expected version: -1, Actual version: ",
   status: :failed_precondition,
   status_code: 9
 }}

# but it works to delete with a correct expectation
iex> Spear.delete_stream(conn, "test-stream", expect: :exists) # or :any
:ok
```

**Expected behavior**

I'd expect the error message to include the actual version of the stream at time-of-deletion-attempt. Super ideally it'd be great if it would return a data structure like [WrongExpectedVersion in AppendResp](https://github.com/EventStore/EventStore/blob/1933349fa4e7099bc9e99855b8b587590752d8de/src/Protos/Grpc/streams.proto#L179-L200), but that's a little out of scope of this bug report.

**Actual behavior**

The actual version is the empty string.

**Config/Logs/Screenshots**

Using the [nightly build](https://github.com/EventStore/EventStore/pkgs/container/eventstore/8864450?tag=21.10.1-alpha.0.6-focal) with no extra config.

**EventStore details**

 - EventStore server version: nightly from 2021-10-14

 - Operating system: Ubuntu

 - EventStore client version (if applicable): [spear](https://github.com/NFIBrokerage/spear) on main, but it should work with all gRPC clients

**Additional context**

It looks like the `RpcExceptions.WrongExpectedVersion` being created [here](https://github.com/EventStore/EventStore/blob/08633f0b1a42083dd7a5d7df711e1ed66597e7c4/src/EventStore.Core/Services/Transport/Grpc/Streams.Delete.cs#L134-L137) doesn't pass in `actualVersion` which is [optional](https://github.com/EventStore/EventStore/blob/08633f0b1a42083dd7a5d7df711e1ed66597e7c4/src/EventStore.Core/Services/Transport/Grpc/RpcExceptions.cs#L74). It looks like that doesn't get set because that info isn't kept track of in the `ClientMessage.DeleteStreamCompleted` class.

As a workaround, one may read the stream before attempting to deleted it to determine the current version, although that data could possibly become stale in between the read and the deletion attempt.

This was brought up [on the slack](https://ddd-cqrs-es.slack.com/archives/C0K9GBSSG/p1634269016426400).

**Comment by hayley-jean** [comment]
It looks like this is still an issue, thanks for reporting it @the-mikedavis
