### ISSUE TITLE
ES client (re)connection cycle breaks when it attemps to connect with starting ES

### ISSUE THREAD

**Issue by robvdlv** [EventStore/EventStore#323]
### Summary
Given a running ES client, while a target EventStore is not yet running
When the EventStore is started
Then the ES client throws a NotAuthenticatedException, caused by the EventStore responding with a ServerNotReady response while its becoming ready. This breaks the (re)connection cycle of the ES client, which will not (re)connecting at all as a consequence.

The issue manifests itself with versions:
```
- EventStore Client v3.0.1
- EventStore, v3.0.1.0 (release-oss-v3.0.1/7fa876c111888dd5980dbd86d126e6abe13b05ab, Thu, 23 Oct 2014 22:27:04 +0100)
```

### Reproduction steps
* Checkout the Sklaida sample [https://github.com/EventStore/Sklaida]
* Update its ES client 
* Start the Sklaida sample
* Only when the app runs, then start the ES
* The issue manifests itself

### Stacktrace
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> EventStore.ClientAPI.Exceptions.NotAuthenticatedException: Server not ready
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BackendServices.OuroSellerEndpointAdapter.StartListening() in c:\Users\rob\dev\github.com\Sklaida\backend\src\BackendServices\OuroSellerEndpointAdapter.cs:line 44
... (and then some) ...
Press any key to continue . . .
```

**Comment by jen20** [comment]
This should be fixed by #349. Expect the fix in 3.1.0!
