### ISSUE TITLE
Admin Web Stream Browser shows cached value for events

### ISSUE THREAD

**Issue by NangiDev** [EventStore/EventStore#3250]
**Describe the bug**
As I was testing writing to eventstore deployed inside docker I though I had missmatching values from what was printed in my logs and what was shown inside the Admin Web Dashboard, Stream browser view.

I used Google Chrome. I tries open it in incognito mode and it then updated the value once. Then I Microsoft Edge and that seems to be working better.

**To Reproduce**
1. Deploy Evenstore/evenstore:latest in a docker container (No volume attached)
2. Write event to eventstore db
3. Look at it in Event Browser -> Event-<id> (Page 0)
4. Keep Event Browser open as you restart docker container. 
5. Now eventstore db should be empty.
6, In Event Browser there should be no events
7, Write same event with different values
8, Refresh Dashboard and go to Event Browser -> Event-<id> (Page 0)

**Expected behavior**
Always show last written event. Page 0 should not be persistent between container reboots unless volume attached

**Actual behavior**
Cache seems to be persistent event though it's a new container instance

**EventStore details**
 - EventStore server version: latest docker image (oss-v5.0.11 ?)

 - Operating system: Windows 10 host

 - EventStore client version (if applicable): eventstore.client.grpc.streams-21.2.0 (nuget)

**Additional context**
When noticing this problem I where manipulating GUID values inside the events. I haven't noticed it with other values, but that could be due to GUIDs regenerates everytime and the other values does not.

**Comment by hayley-jean** [comment]
Hi @NangiDev, this is expected behaviour for the UI

Events in EventStoreDB are immutable, so the UI will aggressively cache them to save looking them up from the server each time you view the streams.

You'll need to clear the cache in your browser when you bring up a new docker container with different data

**Comment by NangiDev** [comment]
Okay. Thanks for expenation.
When you put it that way it makes sense.
If it is expected then I close this issue.

**Comment by oskardudycz** [comment]
@NangiDev as an addition, ESDB docker image also automatically creates volumes. If you want to clean data fully, you have to remove the image with its volumes.

**Comment by NangiDev** [comment]
@oskardudycz Yes :) that's what I have been doing during development, but now we getting so much data that it would be nice to just remove specific streams.

Maybe a way of getting a snapshot of the database to be able to revert back to a stable state during development would be nice :)

**Comment by oskardudycz** [comment]
For that, you could try to perform a backup and restore it. If you need that for automated tests, I'd suggest using random ids, plus a prefix. See example: https://github.com/EventStore/samples/blob/main/CQRS_Flow/.NET/Core/Core/Events/StreamNameMapper.cs.

If that's used consistently, you could have data isolation for your tests.

**Comment by NangiDev** [comment]
@oskardudycz For testing we use an inmemory inmplementation. We are still pretty early in development. For bigger integration testing it makes sense using random ids and prefix. Especially if we wipe the db afterwards or when needed.

I might look into the backup idea though. Could be nice for when we are experimenting. The whole team is still pretty new at eventstore and best practices. So having the possibility to go back to a stable state could be nice.
From a philosophical stand point it might be bad though 🤔 Being forced to handle f*ck-ups we might create a more stable product? 🤷 😄
