### ISSUE TITLE
Web UI bugs and issues

### ISSUE THREAD

**Issue by eulerfx** [EventStore/EventStore#327]
- When viewing a category projection stream and attempting to navigate to a specific event, the event's position in the category stream is used rather than the sequence number of the event in its own stream. You always have to correct the URL and remember the actual position.

- When attempting to navigate to the URL of a particular stream without being authenticated, the authentication screen comes up however after authentication, it does not redirect back to the originally specified URL.

- JSON in the event can cause the display area to overflow to the right hiding the JSON view toggle button forcing one to scroll back and forth.

- The navigation menu is misaligned on IE.

- The UI seems to drain resources, often behaving very slowly or crashing both Chrome and Firefox. On Chrome it often gets into a state where you can't view events with a message "attempting to open socket connection...". When left alone, the CPU/memory for Chrome and Firefox can go through the roof.

- When the UI is viewing a stream and the EventStore instance is shutdown or restarted, a highly intrusive modal dialog comes up that diverts attention from anything else. A simple banner message would do.

**Comment by jen20** [comment]
To my knowledge, all of these fixes are in v3.0.4.

With respect to IE, support there is a "best effort" type thing, we don't actively test in IE.
