### ISSUE TITLE
Projections Recovery Tools

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#328]
Need better tooling for emergency scenarios recovering projections for whatever reason.

EG on an incorrect emit attempt during takeover to be able to diagnose easily the checkpoints etc and possibly be able to recover it in place without a replay if possible

This is a good one for ext people as well cc @ascjones as I know you have dealt with this before.

**Comment by pgermishuys** [comment]
The CLI will have these built in.
