### ISSUE TITLE
Want to improve scavenge algorithm

### ISSUE THREAD

**Issue by timothycoleman** [EventStore/EventStore#3305]
Want to improve:
- Scavenge chunks faster
- Scavenging the index without applying so much load onto the system

In particular it is hoped/expected that we could have a logical process that reads through the log once (not once per scavenge) accumulating data necessary to scavenge more efficiently

**Comment by timothycoleman** [comment]
Added to master here https://github.com/EventStore/EventStore/pull/3520

**Comment by hayley-jean** [comment]
@timothycoleman can this be closed following the release of 22.10?

**Comment by timothycoleman** [comment]
yeps
