### ISSUE TITLE
Persistent Subscription unable to resolve events to correct type, parks them with type '$>'

### ISSUE THREAD

**Issue by lakshdeepsingheventstore** [EventStore/EventStore#3307]
A peculiar behavior has been observed wherein the parked events' event type is labelled as '$>' instead of the original event type.
We have tried to reproduce this issue on our end on different Event Store versions but have not been able to reproduce this issue on our end. The only instance when we were able to reproduce this issue on our end was when in the Persistent Subscription settings, we did not checkmark the "Resolve Link Tos" option. We then asked the client to ensure that the "Resolve Link Tos" is enabled or not. On investigating the screenshots provided by the client, we observed that the "Resolve Link Tos" was enabled. Ever since then we have been trying to reproduce the issue but have failed to do so on our end.
Attached are some of the screenshots demonstrating the issue.
Note: screenshots will be reuploaded again soon.

[Internally Reported Version](https://github.com/EventStore/home/issues/597)

**Comment by gregoryyoung** [comment]
$> is a "link to" event.

If you resolve it, it will give you your original event. Think of it ... as a pointer.

There is a reason for this ... what if you were to delete the original event ... do you still want it delivered later?
