### ISSUE TITLE
Potential bug causing read-only replicas to fail to accept new connections

### ISSUE THREAD

**Issue by rmfaheem** [EventStore/EventStore#3319]
**Description**
Read-Only Replicas fail to accept new connections at some point. A restart fixes the problem

**To Reproduce**
Unclear at the moment.

**Expected behavior**
Continue accepting new connections.

**Actual behavior**
Connections dropped and logs below are shown.

**Logs**
```
[50029,50,23:58:57.973,INF] ES "TcpConnectionSsl" closed [23:58:57.973: N"10.1.0.1:65256", L"10.0.0.2:2115", {35f61c7c-db6e-4e7d-be2f-18ff6d3dc49e}]:Close reason: [SocketError] "Exception during EndRead."
[50029,50,23:58:57.973,INF] Connection '"external-secure"":projection-a"' ["10.1.0.1:65256", {35f61c7c-db6e-4e7d-be2f-18ff6d3dc49e}] closed: SocketError.
TcpConnectionSsl::InitClientSocket(10.1.0.1:17431, L10.0.0.2:2115)
```

**EventStore details**
 - EventStore server version: 20.10.4
 - Operating system: Ubuntu 18.04

**Additional context**
Support ticket: #109963

**Comment by shaan1337** [comment]
Additional info received in support ticket related to client:
- Clients are long-running and maintain one or more connections to the EventStoreDB server
- .NET TCP client 20.6.1
- Host: Ubuntu 18.04, in kubernetes 1.21.7, with the containerd runtime.
- Container image is based on Ubuntu 18.04 also.

**Comment by oskardudycz** [comment]
@rmfaheem  @shaan1337 any update on this? If we don't have more reproduce steps then we should close it.
