### ISSUE TITLE
Nodes do not restart elections when gossip continually fails if the TCP connection does not get disconnected

### ISSUE THREAD

**Issue by Lougarou** [EventStore/EventStore#3322]
**Describe the bug**
Nodes do not restart elections when gossip continually fails if the TCP connection does not get disconnected. This lasts until the Leader node is restarted.

**To Reproduce**
This could happen when there are network issues causing the TCP handshake to be incomplete. 

**Expected behavior**
The cluster should recover from this.

**Actual behavior**
During this time the Leader node would not show any activity in the logs and appear "stuck".

**EventStore details**
 - EventStore server version: 20.10.2
 - Operating system: Windows
 - Host: Azure

**Additional context**
Ticket 109817

**Comment by hayley-jean** [comment]
This looks like it's related to https://github.com/EventStore/EventStore/issues/1674

**Comment by oskardudycz** [comment]
Closing it as a duplicate of #1674

**Comment by oskardudycz** [comment]
It was something else and fixed by https://github.com/EventStore/EventStore/pull/3343.
