### ISSUE TITLE
Stream names with @ in them seems to break the system projections 

### ISSUE THREAD

**Issue by ylorph** [EventStore/EventStore#3323]
**Describe the bug**

https://discuss.eventstore.com/t/persistent-subscription-linktos-are-not-resolved-for-live-events/3693
**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Config/Logs/Screenshots**
If applicable, please attach your node configuration, logs or any screenshots.

**EventStore details**
 - EventStore server version:

 - Operating system:

 - EventStore client version (if applicable):

**Additional context**

**Comment by YoEight** [comment]
I can't reproduce this issue. We definitely need more information:

* If possible, the server logs when the issue happened/is happening.
* Complete information about the events we are dealing with.
* Complete persistent subscription settings being used.

**Comment by YoEight** [comment]
Turned out I was able to reproduce it :sweat_smile:
