### ISSUE TITLE
Error when using eventstore in k8s when service is named eventstore

### ISSUE THREAD

**Issue by werenskjold** [EventStore/EventStore#3324]
**Describe the bug**
k8s will create an environment variables that are prefixed with the service name. This causes the strict env variable checking introduced in 21.6.0 to fail
https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables

**To Reproduce**
Apply this gist to a k8s cluster and check logs
https://gist.github.com/werenskjold/3841b246620dd7830d6d02682a528ace

**Expected behavior**
I Want eventstore to be able to run in Kubernetes with a service named "eventstore"

**Config/Logs/Screenshots**
[ 1, 1,10:59:31.582,FTL] Error while parsing options: The option ServicePort is not a known option. (Parameter 'ServicePort')
[ 1, 1,10:59:31.601,INF] Options:

**EventStore details**
 - EventStore server version: 21.6.0, 21.10.0

**Comment by alexeyzimarev** [comment]
Hey Øyvind, we are aware of the issue. It might feel weird, but we experienced lots of issues with people complaining that some of their config options don't work only to find out that the options they use aren't supported by the server version they use. Therefore, from 21.2 the server fails if it finds a setting that is not known to it, be it the yaml file setting, env variable, or command-line option.

Maybe there's some solution to it, like ignoring environment variables, in particular, I feel that the best solution atm is not to name your service `eventstore`, as this is something you control and can change.
