### ISSUE TITLE
Enable use of JavaScript modules inside projections.

### ISSUE THREAD

**Issue by brian-scb** [EventStore/EventStore#3353]
**Is your feature request related to a problem? Please describe.**

Projection code is often more complicated than needed because of lack of access to reusable modules.  Finding some way to allow usage of some prebuilt javascript modules would be extremely helpful.

**Describe the solution you'd like**
Ability to add static javascript files available to use in projections, or a package.json file with modules that could be installed.

**Describe alternatives you've considered**
- package json to declare modules EventStore should startup with
- clear instructions on how to add static modules that could be loaded
- a more dynamic system to upload static modules

**Additional context**
N/A

**Comment by StevenBlair123** [comment]
Would really like this feature as well.

**Comment by oskardudycz** [comment]
I think that getting full NPM packages support will be hard to achieve, as they are usually taking a lot of space and it's hard to set a hard limit for that. Loading all of that to the database engine may be costly. I think that more probable is to provide guidance on how to use bundlers (e.g. webpack, parcel, etc.) to support generating the bundled JS file.

**Comment by oskardudycz** [comment]
@jageall, @condron, do we plan to support NPM packages for projections in the future?

**Comment by condron** [comment]
The security risks of running dynamically loaded and unverified packages inside the DB seem to be significant, and there are challenges with being able to provide a deterministic performance profile with such a variable execution set.

We are committed to improving the programing experience in projections and consider them to be a key feature.

It does not seem at this time that loading NPM packages into the running DB is going to be the first choice here.

**Comment by brian-scb** [comment]
Yes, it makes sense to not allow NPM packages for security! Still feel like it could be useful to install a javascript file and make it available for use in projections.

**Comment by oskardudycz** [comment]
@brian-scb, @condron I think that we could try to handle that by giving guidance on how to bundle files and potentially npm modules into a single file using tools like WebPack or so.

**Comment by oskardudycz** [comment]
@ylorph, this may be worth documenting. I think that we could close these issues in favour of issues in documentation, thoughts?
