### ISSUE TITLE
EventFilter does not asppear to work for serverside filtering

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3392]
**Describe the bug**
I created an EventTypeFilter.Prefix for my Persistent Subscription.
After conencting to the subscription, no events appeared.

**To Reproduce**

_var filter = EventTypeFilter.Prefix("OrganisationCreatedEvent");  
await client.CreateToAllAsync(groupName,
                                          filter,
                                          settings);

await client.SubscribeToAllAsync(groupName, EventAppeared, SubscriptionDropped, null, 500);_

**Expected behavior**
Only events matching the string should be returned.

**Actual behavior**
No events appeared.

**EventStore details**
 - EventStore server version: 21.6

 - Operating system: Ubuntu

 - EventStore client version (if applicable): 21.2.1-alpha.0.28"

**Additional context**
Tried the following regular expression as well "^OrganisationCreatedEvent"

**Comment by oskardudycz** [comment]
@StevenBlair123, could you try to check version `21.10.1` and confirm if it's still appearing? Persistent subscriptions to `$all` are supported officially from the version `21.10`.

**Comment by oskardudycz** [comment]
@StevenBlair123, I'm going to close this issue because of the inactivity. I'll reopen it if you find out that's still happening in the `21.10.1` 👍
