### ISSUE TITLE
Serverside filtering to allow chained ExcludeSystemEvents and Prefix

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3393]
**Is your feature request related to a problem? Please describe.**
When building a server side filter, I would like to be able to do the following:

`var filter = EventTypeFilter.ExcludeSystemEvents().Prefix("Sales-");`

**Describe the solution you'd like**
I think ignoring system events **and** applying a filter would be a popular option when building a filter.

**Describe alternatives you've considered**
Apply the ExcludeSystemEvents and simply filter at the client.

**Additional context**
None at this time.

**Comment by oskardudycz** [comment]
I agree that would be good to have. Unfortunately, as I know, there are no plans to add this feature. This might change in Log V3, but there is no set time and plan for that yet.
