### ISSUE TITLE
PersistentConfig1 system event does not begin with $

### ISSUE THREAD

**Issue by timothycoleman** [EventStore/EventStore#3395]
So it shows up in, for example, $all persistent subscriptions with ExcludeSystemEvents

<sub>[DB-164](https://linear.app/eventstore/issue/DB-164/persistentconfig1-system-event-does-not-begin-with-dollar)</sub>

**Comment by StevenBlair123** [comment]
@timothycoleman - even though we shouldn't see these events, why is it the full history of the persistent subscription appears to be preserved.

In my example, I received all these events:
[PersistentConfig1.txt](https://github.com/EventStore/EventStore/files/7904884/PersistentConfig1.txt)

**Comment by timothycoleman** [comment]
@StevenBlair123 when reading from $all you get whatever is in the database, the metadata restrictions like maxage and maxcount are not applied. if a scavenge is performed only the last 2 records will be kept in this case and after that only those two would appear in the subscription

**Comment by StevenBlair123** [comment]
Would that apply for a catchup on fromAll as well?
It's maybe not a big problem, since I am constantly deleting / creating the same persistent subscription for testing.
In production, I suspect we would not see this.

**Comment by timothycoleman** [comment]
Yeah it'll be the same for $all catchup subscriptions, and $all reads, too

**Comment by hayley-jean** [comment]
We could possibly "fix" this by filtering out the `PersistentConfig1` events in the specific event type in the filter used by persistent subscriptions. We already use this to filter out the persistent subscription's checkpoint events

The name should definitely start with a `$`, but this would likely be a breaking change for persistent subscriptions.

**Comment by StevenBlair123** [comment]
[181@$persistentSubscriptionConfig.txt](https://github.com/EventStore/EventStore/files/7932601/181%40.persistentSubscriptionConfig.txt)
[182@$persistentSubscriptionConfig.txt](https://github.com/EventStore/EventStore/files/7932602/182%40.persistentSubscriptionConfig.txt)

**Comment by StevenBlair123** [comment]
[76@$persistentSubscriptionConfig.txt](https://github.com/EventStore/EventStore/files/7932894/76%40.persistentSubscriptionConfig.txt)
[77@$persistentSubscriptionConfig.txt](https://github.com/EventStore/EventStore/files/7932895/77%40.persistentSubscriptionConfig.txt)

**Comment by timothycoleman** [comment]
@hayley-jean im not sure it would break the persistent subscriptions actually, the name only appears in one place in the code (where the event is created) perhaps the subscriptions themselves just read any event in the config stream rather than filtering by event type

**Comment by hayley-jean** [comment]
Ah you're right! I can't see anywhere in the code that's checking the event type when reading it out.
Given that the config events are only written to a system stream we should be able to change the event type without it being a breaking change

**Comment by oskardudycz** [comment]
@hayley-jean, do you know if that event can have any value for the users? I'm asking because that may be behaviour breaking change if someone has some logic around that (I hope not 😉 ).

**Comment by hayley-jean** [comment]
@oskardudycz It shouldn't do, and you can get access to the subscription config through the various APIs rather than reading it from the stream. The subscription config is also written to a system stream (starting with a `$`), which we usually recommend against relying upon.

**Comment by timothycoleman** [comment]
some automation seems to have had some fun here
