### ISSUE TITLE
Allow Projections to retry which have Faulted

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3436]
**Is your feature request related to a problem? Please describe.**
Projections can fault due to a timeout. Various reasons which could cause this (in my case, too much traffic)

**Describe the solution you'd like**
When creating a projection allow the user to choose to "auto restart" or increase the timeout allowed for projection script execution.

**Describe alternatives you've considered**
Lightening the load on the server should remove this, however, there will still be spikes.
*edit* - we could also increase the ProjectionCompilationTimeout / ProjectionExecutionTimeout configuration values

**Additional context**

![](https://uploads.linear.app/a2a29b63-594b-4491-8437-5f7f43da2367/6b25f2f9-8bcf-4cff-b0f9-b6544b2a9336/ebfd2b4f-965e-4de6-a59a-9b5c55c98117)

<sub>[DB-62](https://linear.app/eventstore/issue/DB-62/allow-projections-to-retry-which-have-faulted)</sub>

**Comment by StevenBlair123** [comment]
Just my experience with this, but I find myself having to jump onto servers just to press the Start button on a faulted projection.
I don't know what else would be expected to happen in this scenario.

From my basic understanding of Projections, each event would be processed one after another, so from that perspective, it's hard to see why we couldn't just retry processing the event, rather than faulting the projection.

**Comment by StevenBlair123** [comment]
I have been digging around in the code, and can see I can easily change the ProjectionExecutionTimeout / ProjectionCompilationTimeout timeouts from the configuration. This might be a short term solution for my problem, but would be interesting to get feedback on this retry idea.

My guess is, ProjectionOptions could be updated to hold the retry criteria:

1. No retry (as it does just now)
2. Unlimited retries (keep retrying possibly with a small delay in between each retry)
3. Set number of retries (similar to replay events on subscriptions)
4. Set number of retries with growing time elapsed in between each retry

Slightly off topic, but I noticed another configuration value - _ProjectionThreads_. Which is set to 3 by default.
Is there any guidance on what this value should be set to? For example, if you have have 3 user projections, 3 would be fine, but if you had 4, potentially you would see a drop off on performance.

So if you had 4 user projections which were hammering the evenstore, it might be advisable to update this to 4 threads, whereas if you had 4 use projections, but only 2 were heavy processing, you might get away with 3.

**Comment by hayley-jean** [comment]
Hi @StevenBlair123 to answer the initial issue, increasing the `ProjectionExecutionTimeout` is currently the correct way to resolve the error you're seeing. How long the projection code takes to execute depends on what the projection is doing and the load that your system is under, so you'll need to tune that accordingly.

Having an option to retry individual events that failed is an interesting idea, and we'll discuss that internally to see if it's something we want to implement.

As a solution for now, you could create an external tool that monitors the projection status and attempts to start them up again in case of failure.

To answer your questions about `ProjectionThreads`, both system and user projections share these threads.
If you have a number of projections that are doing a lot of processing then increasing the thread count may improve performance. However there are caveats to this, mainly that this will only help if there are no other bottlenecks, such as disk or memory.
You will have to adjust the setting and monitor to see if you are getting a benefit.

**Comment by alexeyzimarev** [comment]
I added a separate issue for the timeout config, we should decide if we do anything more like retry policy.
