### ISSUE TITLE
API Gateway framework Event Sourcing feature using Event Store

### ISSUE THREAD

**Issue by VeritasSoftware** [EventStore/EventStore#3451]
Hi

I have built an API Gateway framework.

[API Gateway framework](https://github.com/VeritasSoftware/AspNetCore.ApiGateway)

I have built an Event Sourcing feature into this framework.

[Event Sourcing feature](https://github.com/VeritasSoftware/AspNetCore.ApiGateway/blob/master/Docs/README_EventSourcing.md)

I am supporting Event Store in this feature.

The API Gateway talks to the Event Store.
And, the clients talk to to the API Gateway using web sockets (SignalR).

As of now, I support

- publishing events to the downstream Event Store Server stream.
- subscribing to events from a downstream Event Store Server stream.

I wanted to know if you are interested in the concept.
Also, no other API Gateway framework supports Event sourcing.

Please let me know, if you would like to suggest ideas and be involved in my project.

Regards, Shantanu

**Comment by gregoryyoung** [comment]
A common use case is replaying old events.

How do you intend to handle this? The reason I ask is that this is something where in many situations http might even be **more** efficient than a web socket.

**Comment by VeritasSoftware** [comment]
Web sockets allow for streaming to the client.
Plus, SignalR is an industry standard.
Allowing all kinds of apps to be able to hook into event streams.

**Comment by VeritasSoftware** [comment]
what do you mean by replaying old events?

**Comment by gregoryyoung** [comment]
What if I need to say rebuild a read model? I would need to replay through possibly millions and millions of old events.

**Comment by VeritasSoftware** [comment]
The Event Store will be an back end Server. All activities, as you normally do, can be done.

The clients of the API Gateway are not interested in that.
They are users of streams only.

Eg. publishing to & subscribing to a back end stream, are activities the users might be interested in.

**Comment by VeritasSoftware** [comment]
However, I can provide an http endpoints for activities, 
which the API Gateway users are interested in, if needed.

**Comment by gregoryyoung** [comment]
OK so this is just a "live subscription" over a different protocol ... is that correct?

**Comment by VeritasSoftware** [comment]
Yes, the API Gateway feature users would require such activities.

The client of the API Gateway, could be a web app, 
which will publish/subscribe to the back end stream, 
via web sockets.

If you can think of any more, please let me know.
