### ISSUE TITLE
User Activity Monitoring

### ISSUE THREAD

**Issue by rmfaheem** [EventStore/EventStore#3457]
This feature is needed primarily to track users and connections. Because of security requirements/company policies it is necessary to rotate user passwords and seamlessly propagate the changes to clients.

The details should ideally be available via the stats or some other HTTP endpoint for easy monitoring.

<sub>[DB-39](https://linear.app/eventstore/issue/DB-39/user-activity-monitoring)</sub>

**Comment by alexeyzimarev** [comment]
We need more details. I am closing this one until we see the demand, and understand the problem clearly.
