### ISSUE TITLE
Kubernetes Operator for eventstoredb

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [EventStore/EventStore#3461]
Is there any progress on a release date for the Kubernetes Operator solution mentioned in the [official helm chart documentation 7](https://github.com/EventStore/EventStore.Charts)?

**Comment by ylorph** [comment]
As stated in the [repository](https://github.com/EventStore/EventStore.Charts) we have no immediate plan to update the helm chart.
We need to gather more information on how users are deploying & configuring EventstoreDB  in K8S  as well as typical workloads in such environment, before we can make progress on this.

Can you give a bit more info on what you're trying to achieve ?

**Comment by kodeine** [comment]
same here we are trying to use in Kubernetes, basic requirements but i think charts should be supported.

**Comment by oskardudycz** [comment]
We don't have plans to provide either Helm Chart or Operator at the moment. This may come in the future.

**Comment by rb-kurrent** [comment]
Update on this old thread: we do have an operator now, check out [our docs](https://docs.kurrent.io/server/kubernetes-operator/v1.3.1/getting-started/)!
