### ISSUE TITLE
Persist datetime when an event was published

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3465]
We have debugging a problem on one of our system where events are are being parked on a Persistent Subscription, but no errors are being thrown (99% sure no errors have happened), so we are working on the assumption that a timeout has occured.
Flooded the consuemr with trace, and the events are processed fairly quick (under 1 second)
The persistent subscription is using default timeout (10 seconds) so we are trying to understand we the Evenstore itself starts the timer ticking (10 seconds) and whether this could be persisted.

I will hopefully give you a clear example.
Our event appears in the parked queue, and has the following metadata:

_Link metadata
{
  "added": "2022-04-01T15:06:44.6822789+00:00",
  "reason": "Reached retry count of 0",
  "subscriptionEventNumber": 644875
}_

The added is when evenstore parked the message, but could we get a field called published / sent that shows when the Eventstore actually published this? We want to rule out some processing lag at Evenstore (probably caused by our lack of resources rather than any fault with the database).
When does the Evenstore start keeping track of the timeout for a published event? Is it after it's written to the socket, or could it be before that (perhaps on the message handler) and any delay there is impacting on our 10 seconds.

**Comment by gregoryyoung** [comment]
OK so this would not be very difficult _**except**_ there is a detail missing here.

What would you expect to happen in a node restart/master switch in a cluster?

**Comment by StevenBlair123** [comment]
So the event is inflight, and the node restarted during this?
I don't know for sure, but would the link metadata still be written in this scenario?

**Comment by ylorph** [comment]
The server sets an expiry time (based on the subscription's `MessageTimeout`) on each message it sends to the consumer. 
Note that if a batch of messages are sent at once, they will have _the same expiry time_ regardless of when the consumer starts processing them.

This means that it is possible for a batch of messages to be sent to the consumer and for some of them to time out because the consumer simply couldn't process the whole batch within the timeout. This needs to be taken into account when configuring the `BufferSize `of the consumer and the `MessageTimeout `of the subscription.


We need to explain that better in the documentation

**Comment by StevenBlair123** [comment]
@ylorph - I hadn't considered the batch would all have the same datetime to be sent.
I will close this off.

**Comment by ylorph** [comment]
@StevenBlair123 yeah that need better docs.

**Comment by gregoryyoung** [comment]
btw just to answer your question:

"When does the Evenstore start keeping track of the timeout for a published event? Is it after it's written to the socket, or could it be before that (perhaps on the message handler) and any delay there is impacting on our 10 seconds."

The tracking of the time starts when the message is dispatched from the competing consumer backend.

This is important to occur in this way as it also factors in things like socket problems or even ... internal issues :)
