### ISSUE TITLE
Changes to the log rotation config are not printed out at the start

### ISSUE THREAD

**Issue by rmfaheem** [EventStore/EventStore#3466]
**Description**
The effective configuration printed out at the start of EventStore does not contain the changes to the log rotation settings. Those remain in the "DEFAULT OPTIONS" category at the bottom.

Good news is that log files are being rotated successfully in the background.

**To Reproduce**
1. Configure log rotation via the ES Config options
2. Start EventStore

**Expected behavior**
The complete effective configuration should be printed out.

**Actual behavior**
Log rotation settings are missing.

**EventStore details**
 - EventStore server version: 21.10
 - Operating system: Ubuntu

**Comment by ylorph** [comment]
@rmfaheem could you add the sample config you're using ?
Thanks.

**Comment by rmfaheem** [comment]
```
MemDb: true
Log: /tmp/esdb/logs
ClusterSize: 1
RunProjections: All 
StartStandardProjections: true 
StatsPeriodSec: 1
Insecure: false
DiscoverViaDns: false
TrustedRootCertificatesPath: /usr/local/share/ca-certificates
CertificateFile: /home/.../node.crt
CertificatePrivateKeyFile: /home/...node.key
CertificateReservedNodeCommonName: eventstoredb-node
EnableAtomPubOverHttp: true
EnableExternalTcp: false
LogFileInterval: Minute
LogFileRetentionCount: 5
```

Should be something like this, but I tested it again just now and it seems to be working fine on all releases of v21.10. I've no idea why it wasn't working previously.

Can anyone else reproduce it?
