### ISSUE TITLE
HTTP 204 returned from /health/live endpoint is unsuitable for Google Kubernetes Cloud healthcheck

### ISSUE THREAD

**Issue by kodeine** [EventStore/EventStore#3468]
**Describe the bug**
Google Cloud does not allow you to configure the behavior of its health checks, other than the endpoint, it requires a 200 response. This means that the "/health/live" endpoint, which seems intended for this sort of use case, can't be used on this cloud provider. The return code should be changed to 200, either by default, or by adding a param to the endpoint.

**Expected behavior**

```
curl -i  --fail --insecure http://10.0.0.75:2113/health/live
HTTP/1.1 200 OK
```

**Actual behavior**

```
curl -i  --fail --insecure http://10.0.0.75:2113/health/live
HTTP/1.1 204 No Content
```

<sub>[DB-299](https://linear.app/eventstore/issue/DB-299/http-204-returned-from-healthlive-endpoint-is-unsuitable-for-google)</sub>

**Comment by ylorph** [comment]
Live vs readiness probes

**Comment by kodeine** [comment]
Its not for Kubernetes its for google compute instance. For kubernetes live probes can work but not for compute instance healthchecks.

**Comment by m-guesnon-pvotal** [comment]
Any plan for this to be implemented?
Sounds like a non-breaking change approach similar to what vault does would be pretty safe to implement.
i.e:
Providing an extra query parameter specifying the expected status code on health check success if the default one does not suit you.

For reference: https://developer.hashicorp.com/vault/api-docs/system/health

**Comment by alexeyzimarev** [comment]
Thanks for the heads up, we'll look into it.

**Comment by timothycoleman** [comment]
This'll be in the 24.6.0 release
