### ISSUE TITLE
Unable to start Kestrel

### ISSUE THREAD

**Issue by RauleHernandeza** [EventStore/EventStore#3469]
**Describe the bug**
Unable to perform configuration 

**To Reproduce**

1. I downloaded the 21.10 version through chocolatey
2. I proceeded to configure event store through the configuration tool (https://configurator.eventstore. com/)
3. Created the folders as indicated (C:ESDB, C:ESDB/Logs, C:ESDB/Index, C:ESDB/Data)
4. Create certificates with a certificate tool (es-gencert-cli_1.1.0_Windows-i386.zip)
5. I copied and pasted the files in the corresponding folders
6. then I proceeded to create an eventstore.conf file, for which I copied the configuration format that the tool gave me, pasted it in a text file and then changed its format to .conf
7. I used the command EventStore.ClusterNode.exe --config C:\ESDB EventStore.conf

**Expected behavior**
Event Store is started with the given configurations and certificates

**Actual behavior**
After using the event store command it recognizes the command and starts to perform it, then it gives me the error that I cannot initialize kestrel and that the given address is not valid.

**Config/Logs/Screenshots**

![p1](https://user-images.githubusercontent.com/66449632/163072828-b005632d-b949-4986-9169-f60ab7699e72.png)
![p2](https://user-images.githubusercontent.com/66449632/163072837-e62581c3-2176-4ff3-864c-03a096f804bd.png)
![p3](https://user-images.githubusercontent.com/66449632/163072850-c230dca6-be40-405d-a83c-920255bc9790.png)
![p4](https://user-images.githubusercontent.com/66449632/163072878-40942bd6-bbec-4cf3-844c-5f4edc1b1ac8.png)

**EventStore details**
 - EventStore server version: 21.10

 - Operating system: Windows 10

 - EventStore client version (if applicable): //

**Additional context**
Reviewing a similar thread in my case when I try to run the insecure mode it keeps loading, does not finish executing the action and I have to stop the process.

**Comment by oskardudycz** [comment]
@RauleHernandeza, could you make sure that you don't have another application running at the `2113` port? Is there a specific reason why did you change the Internal TCP Port to `1117`?

**Comment by RauleHernandeza** [comment]
Good, thanks for answering, yesterday I kept trying to find out why I was getting this error, it turns out that changing the TCP address to 1112 and placing files in several places I managed to overcome the problem of starting kestrel, but now it turns out that when I run the command to designate the configuration file, it keeps loading without finishing applying these changes. Here are the images of what I did:
![pp1](https://user-images.githubusercontent.com/66449632/163230725-3fc43dec-0176-494c-89c7-af285df6f38a.png)
![pp2](https://user-images.githubusercontent.com/66449632/163230748-62f7dd65-9442-4acd-bf43-6a0d478b538e.png)
![pp3](https://user-images.githubusercontent.com/66449632/163230755-ba7ff6f2-1659-4efd-a350-cae42fdf6f78.png)
![pp4](https://user-images.githubusercontent.com/66449632/163230759-32bb9355-7f30-4863-ae75-f1c576fa3ece.png)

As additional information, the same happens if I try to run the insecure mode (EventStore.ClusterNode.exe --insecure), which will load without finishing applying the changes. 

![pp5](https://user-images.githubusercontent.com/66449632/163232099-b452adfc-a5e9-406c-ac6a-40d992536109.png)

![pp6](https://user-images.githubusercontent.com/66449632/163232117-be1ab27c-92b9-4805-9d07-bb39ef0a38ca.png)

**Comment by hayley-jean** [comment]
@RauleHernandeza Thanks for the update, it's good that you got the kestrel server running

The screenshots in your last message look like everything is starting up correctly. There are no additional logs after the ones you show because the server is idle.

You can check that it's working by browsing to the admin UI at https://127.0.0.1:2113, or by connecting to it using one of the gRPC clients.

**Comment by RauleHernandeza** [comment]
ok, thanks for the information, effectively now the home page is shown, so that it is of registry to the other people, I comment that the most probable cause of the error of kestrel is that it has not placed in the correct directory the files that event store asks for to run, now a detail that leaves me curious is that to initialize event store now it is asking me for a user and password although I do not remember when it is defined, if you give me a clue about this I would appreciate it.

![image](https://user-images.githubusercontent.com/66449632/165114904-222a40c6-41f6-45a5-8593-26e2138041b8.png)

**Comment by RauleHernandeza** [comment]
very thanks!

**Comment by hayley-jean** [comment]
No problem! I'm going to close this issue for now, feel free to open a new one if you run into any other issues
