### ISSUE TITLE
Writes incorrectly acked during leader election 

### ISSUE THREAD

**Issue by timothycoleman** [EventStore/EventStore#3472]
If a leader has pending writes that have not yet been replicated, loses quorum, re-connects to the cluster, finds that a new leader has been elected, and finds that the replicated log position has been advanced by the new leader to beyond the pending writes, and those pending writes have not expired - then the old leader will (incorrectly) ack those writes back to the client before (correctly) going offline for truncation of those same writes.

Possibly these writes could appear in a subscription just before the node goes offline, too

**Comment by condron** [comment]
@timothycoleman to reproduce this requires an overloaded or unstable leader with frequent elections as a precondition. Possibly some of the older or dev configs might be able to be used, the newer dev and prod clusters have the stability fixes in place so they won't work for reproducing. Check out the new internal monitoring tools to see if you can get a system into the correct state.

**Comment by gregoryyoung** [comment]
They should not appear in a subscription etc prior as the checkpoint used was not the writer checkpoint but the replication checkpoint.

This was done for this case among others.

**Comment by timothycoleman** [comment]
For posterity, there was a another bug that caused a similar outcome: writes not fully replicated appeared in subscriptions and were subsequently truncated https://github.com/EventStore/EventStore/pull/3527
