### ISSUE TITLE
InvalidCastException - Unable to cast object of type 'System.Int64' to type 'System.Int32

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3473]
**Describe the bug**
Attempting to run a scavenge on a database, and it appears to stop (not update on the UI for a couple of hours now).
The error log has the following error:

_{"@t":"2022-04-20T05:49:24.1192449+00:00","@mt":"Error while processing message {message} in queued handler '{queue}'.","@l":"Error","@i":1948184534,"@x":"System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.\r\n   at EventStore.Core.TransactionLog.Chunks.TFChunkScavengerLogManager.<>c__DisplayClass14_0.<GatherIncompleteScavengeStats>b__0(ReadStreamEventsBackwardCompleted readResult) in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.Core\\TransactionLog\\Chunks\\TFChunkScavengerLogManager.cs:line 216\r\n   at EventStore.Core.Helpers.IODispatcher.<>c__DisplayClass20_0.<ReadBackward>b__0(ReadStreamEventsBackwardCompleted res) in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.Core\\Helpers\\IODispatcher.cs:line 290\r\n   at EventStore.Core.Messaging.RequestResponseDispatcher`2.Handle(TResponse message) in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.Core\\Messaging\\RequestResponseDispatcher.cs:line 65\r\n   at EventStore.Core.Messaging.RequestResponseDispatcher`2.EventStore.Core.Bus.IHandle<TResponse>.Handle(TResponse message) in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.Core\\Messaging\\RequestResponseDispatcher.cs:line 47\r\n   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.Core\\Bus\\MessageHandler.cs:line 30\r\n   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.Core\\Bus\\InMemoryBus.cs:line 290\r\n   at EventStore.Core.Services.VNode.VNodeFSM.Handle(Message message) in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.Core\\Services\\VNode\\VNodeFSM.cs:line 91\r\n   at EventStore.Core.Bus.QueuedHandlerMRES.ReadFromQueue(Object o) in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.Core\\Bus\\QueuedHandlerMRES.cs:line 119","message":"EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted","queue":"MainQueue","SourceContext":"EventStore.Core.Bus.QueuedHandlerMRES","ProcessId":15712,"ThreadId":10}_

**EventStore details**
 - EventStore server version: 21.10.1.0 

 - Operating system: Windows 10

We are pretty keen to get a scavenge run on this database. Any suggestions on a workaround short term?
[log-err20220420.log](https://github.com/EventStore/EventStore/files/8520265/log-err20220420.log)

**Comment by StevenBlair123** [comment]
Guessing this is the culprit:

```
if (dictionary.TryGetValue("spaceSaved", out var spaceSavedEntry)) {
	incompleteScavengeStats.SpaceSaved += (int)spaceSavedEntry;
}
```

**Comment by ssttgg** [comment]
FYI we have also seen this same error on V21.10.2, although it is not stopping us from starting scavenges. In our case it happens on startup of a node as it tries to complete unfinished scavenges.

**Comment by StevenBlair123** [comment]
I am going to make a change to my forked Eventstore, and deploy it to one of our Production servers. Will report back with the results.
