### ISSUE TITLE
Python client for grpc api

### ISSUE THREAD

**Issue by AMontagu** [EventStore/EventStore#3492]
**Is your feature request related to a problem? Please describe.**
Using the new grpc api with Python

**Describe the solution you'd like**
Having a grpc client or contribute to it

**Describe alternatives you've considered**
Developing a python client or developing a less featured event store

**Additional context**
At my company we already have open source repository https://github.com/socotecio/ and are experienced with grpc and async grpc with the grpc python client. We may be able to contribute this new python client if some other people want to contribute with us or someone in the EventStoreDB team is available to help us start on the feature needed and the design required.

**Comment by AMontagu** [comment]
@ylorph did you receive it correctly ?

**Comment by ylorph** [comment]
@AMontagu  yes, just sending you an email with my availabilites , what timezone are you in ?

**Comment by AMontagu** [comment]
Hi @johnbywater 

Thank you for the share. I will test it next week. Are you doing this work in collaboration with @ylorph ?

**Comment by johnbywater** [comment]
Hi @AMontagu, looking forward to your feedback :) yes have been discussing this with @ylorph and others quite a lot.

**Comment by gregoryyoung** [comment]
Just as a heads up you can use the persistent subscription over http as well in just a few lines of code if that is your only blocker.

Obviously getting persistent subscriptions working in general would be a **great** thing but if it is an immediate blocker there is a "let's hack this over lunch" solution around things.

**Comment by johnbywater** [comment]
@gregoryyoung if you are willing, perhaps you and I could "hack this over lunch" in Python? It would be great to understand exactly how to make this work in Python as well it was intended to work originally. Just thought I would ask!

**Comment by johnbywater** [comment]
Fabulous @gregoryyoung maybe tomorrow?

**Comment by gregoryyoung** [comment]
> Fabulous @gregoryyoung maybe tomorrow?

When is lunch for you? :-D 👍

**Comment by johnbywater** [comment]
I will DM you on Twitter, see if we can coordinate like that :)

**Comment by andriykohut** [comment]
@gregoryyoung Just seeing that I'm not the first one who tried this 🙂 

I've started my own implementation here: https://github.com/andriykohut/esdb-py

It still very much work in progress, but it supports persistent subscriptions (only reading and creating for now) and async stuff.

It's a bit tricky to guess what some of the exposed parameters do in some cases, because there's no good documentation for ES gRPC schema.

**Comment by gregoryyoung** [comment]
@andriykohut I wrote the persistent subscription implementation, I can discuss it with you if you want. I am fairly available mostly in EST hours. I can jump on a call in 15-30 if that works for you.

**Comment by andriykohut** [comment]
Thanks @gregoryyoung! I think persistent subscriptions are covered and definitely not the hardest part, I'm mostly having trouble with filtering as there's a ton of possible combinations of read request parameters. As for persistent subscriptions - I only need to add the UD part of CRUD and some of the utility methods for listing and info - we usually create subscriptions manually via UI or using ansible so the most important part - reading and acking/nacking is covered and should work. I'll keep you proposal in mind though, in case I run into some subscription-related issues.
