### ISSUE TITLE
gRPC server error when using FilterOptions and SubscriptionOptions in Streams.Read

### ISSUE THREAD

**Issue by johnbywater** [EventStore/EventStore#3501]
**Describe the bug**
In the gRPC API, the Streams.Read operation fails when a ReadReq has both SubscriptionOptions and FilterOptions. FilterOptions work without SubscriptionOptions. I'm using event_type Expression.

**To Reproduce**

Install Python client:
https://github.com/pyeventsourcing/esdbclient#developers

Change the function:
https://github.com/pyeventsourcing/esdbclient/blob/beff4e90a3cb1962aeefd14d0249b8c34e6fa3c6/esdbclient/client.py#L134
to pass filter args to the read() method rather than filter in the client.

```
    def subscribe_all_events(
        self,
        position: Optional[int] = None,
        filter_exclude: Sequence[str] = (ESDB_EVENTS_REGEX,),
        filter_include: Sequence[str] = (),
        timeout: Optional[float] = None,
    ) -> Iterable[RecordedEvent]:
        """
        Returns a catch-up subscription, from which recorded
        events in "all streams" in the database can be received.
        """
        event_generator = self.streams.read(
            commit_position=position,
            subscribe=True,
            timeout=timeout,
            filter_exclude=filter_exclude,
            filter_include=filter_include,
        )
        return CatchupSubscription(
            event_generator=event_generator,
        )
```

Start EventStoreDB.

```
make start-eventstoredb
```

Run tests:

```
python -m unittest test_client.TestEsdbClient.test_subscribe_all_events_include_filter
```

**Expected behavior**

Expect to get events filtered by type, according to the regular expression (a regular expression which otherwise works). That is, the same results as when reading "all streams" without subscription options, albeit without the event at the given commit position.

**Actual behavior**

EventStoreDB gRPC server call handler errors with gRPC status code: UNKNOWN. Error in file: src/core/lib/surface/call.cc, line 904. Error message: "Exception was thrown by handler."

```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception was thrown by handler."
	debug_error_string = "{"created":"@1654825388.640987000","description":"Error received from peer ipv6:[::1]:2113","file":"src/core/lib/surface/call.cc","file_line":904,"grpc_message":"Exception was thrown by handler.","grpc_status":2}"
>
```

**EventStore details**

Running EventStoreDB with Docker:
```
docker run -d --name my-eventstoredb -it -p 2113:2113 -p 1113:1113 eventstore/eventstore:21.10.2-buster-slim --insecure
```

**Comment by ylorph** [comment]
As weel as https://github.com/pyeventsourcing/esdbclient/issues/3

**Comment by johnbywater** [comment]
With the help of @ylorph, I fixed this by setting `checkpointIntervalMultiplier` in the read request.
