### ISSUE TITLE
Projection Fails with NRE

### ISSUE THREAD

**Issue by thefringeninja** [EventStore/EventStore#3506]
**Describe the bug**
The following event body
```
{ "x": { "y": null } }
```
when applied to the following projection:
```
fromAll()
.when({
	"$init": () => ({ }),
	"a": (s, { body: { x: { y } } }) => (y || [])
		.map(({ x }) => x)
		.filter(x => x)
		.reduce((p, x) => ({
			...p,
			[x.toLowerCase()]: ((p && p[x.toLowerCase()]) || 0) + 1
		}), s)
})
.outputState()
```

**Actual behavior**
```
The leaderboard projection failed to process an event. Handler: EventStore.Projections.Core.Services.Interpreted.JintProjectionStateHandler Event Position: C:13051/P:13051; tweet: -1; Message: Object reference not set to an instance of an object.
```

**Config/Logs/Screenshots**

**EventStore details**
 - EventStore server version: 21.10.5

**Comment by jageall** [comment]
This is down to a specific problem with the reduce function.

Unfortunately the javascript engine we are using does not currently support creating a new object with a spreader and setting the property in a single statement. The workaround is to create the new object with the spreader and assign it to a temporary variable, then set the property on the next line, then return the temporary variable.

We will see about patching the javascript engine to support this style.

**Comment by ylorph** [comment]
ping @ylorph
