### ISSUE TITLE
Packages for Ubuntu 22.04

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#3515]
Ubuntu 22.04.1 is around the corner. Would be nice to get commercial and oss packages for Ubuntu 22.04.

**Comment by ylorph** [comment]
we should also look for the other distributions 
*  Centos / CentOS Stream
* Oracle Linux 
* Amazon Linux

**Comment by ylorph** [comment]
Preview Package for Ubuntu 22.04 are available with EventStoreDB 22.6  ( interim release) 
https://www.eventstore.com/downloads#releases

If we don't find any issue it will probably be official with EventStoreDB 22.10 (next  LTS release)

Will close this issue for the time being
