### ISSUE TITLE
es-cli admin verify_db exit code

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#3516]
This issue ends up here as es-cli is in a private repo. However, just so that this is picked up by the right people.

I ended up using `es-cli` for restore tests as using esdb itself does not do what I hoped for. `/health/live` starts responding ok before chunks have been verified and, as far as I know, there is no endpoint to check that all chunks have been verified after startup.

When verifying chunks using:
```shell
es-cli admin verify_db --databasepath=...
```
and checksum errors are detected, I would expect the tool to return a non-zero exit code. It does not. 

Relying on content of `verify_db.error.log` output is not optimal and makes scripting restore tests brittle. This can be made better.

**Comment by ylorph** [comment]
Hi Alex, I've added this to the private repository of the tool as well

**Comment by ahjohannessen** [comment]
@ylorph 👍

**Comment by ylorph** [comment]
@ahjohannessen : the download is availble on the conmmecial download site .
=> `verify_db` will return non 0 when an error has been detected .

**Comment by ahjohannessen** [comment]
👍
