### ISSUE TITLE
EventStoreDB uses .NET 5 which is not supported by Microsoft

### ISSUE THREAD

**Issue by mk185147** [EventStore/EventStore#3541]
.NET 5 is out of support by Microsoft from May 10, 2022 and there isn't an EventStoreDb release with newer .NET version.

There is a risk of unfixed security vulnerability in .NET that affects EventStoreDB and solutions using EventStoreDb can have hard time being compliant with security standards and validated according to them.

**Comment by gregoryyoung** [comment]
You seem to be slightly confused ... .NET Core 5.0 is what is used.

.NET 5.0.5 was released about 90 days ago.

**Comment by Narvalex** [comment]
> .NET Core 5.0 is what is used.

[Microsoft  dropped "Core" from the name.](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-5)
[.NET 5 is out of support, indeed.](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

**Comment by ylorph** [comment]
We are aware of this and working towards a port to .net 6 
However don't forget , this is a server side product and should  not be  exposed to the outside world .
Also our own support lifecycle for the latest version ( 21.10.x) is until approximatily 2023-10, so we don't have a real choice there .
The client libraries do work on .net 6 though.

**Comment by mk185147** [comment]
What do you mean by "However don't forget , this is a server side product and should not be exposed to the outside world ."? I don't see anywhere in documentation written that it is not secure on contrary I see documentation https://developers.eventstore.com/server/v21.10/security.html with several pages talking how to secure it - but they don't tell that even if I secure it that there will be known .NET vulnerabilities in place. Several security standards, e.g. PCI SSS, requires you to have even server side products without security holes for good reasons.

Btw. I just received from Event Store Cloud an email with sentences like "All external and management traffic is encrypted in transit via TLS 1.3." and "All this provides you peace of mind that your data is kept secure." Isn't behind Event Store Cloud also the same product with .NET 5?

Regarding support lifecycle my personal opinion is that I would consider either having the lifecycle to be driven by Microsoft lifecycle or allow within minor releases a .NET upgrade to ensure the product is always secure when supported.

**Comment by ylorph** [comment]
> this is a server side product and should not be exposed to the outside world
Don't expose the database directly to internet , at least not without strong firewalls rules.
EventStore Cloud is private peering based .

Security , as you know, is a multi layered approach.

We're actively working on the upgrade, and we're not against getting it into a patch version.

**Comment by timothycoleman** [comment]
.NET 6.0 support is being added in this pr https://github.com/EventStore/EventStore/pull/3595

**Comment by ylorph** [comment]
* 20.10.x is now out of support 
* 21.10.x will remain on .net 5
* 22.10.x is on .net6 and the one you want to use if you want to be on a supported version of .net ( no breaking changes between 22.10 & 21.10)
