### ISSUE TITLE
Server should send "Server not ready" response quickly

### ISSUE THREAD

**Issue by timothycoleman** [EventStore/EventStore#3617]
At the the moment, if the server is not ready (e.g. if it is becoming leader after an election) it will respond 'Server not ready' but only after a timeout of 10s (which is likely to be considerably longer than the amount of time the server is actually not ready for). If it is not ready it should respond as such straight away.

Original report from @dpasek-senacor https://github.com/EventStore/EventStore/issues/3575#issuecomment-1268051258

> @hayley-jean @timothycoleman We reteste this issue with the newest EventStore-DB release 21.10.8.0 and observe the following behavior: The request send to the server during the reelection phase are rejected with gRPC Status `UNAVAILABLE: Server not ready`, but this response takes 10s seconds to arrive on the client. We are using the current master of the Java gRPC client and we can see that the gRPC request is sent to the server directly but failure response will arrive with this huge delay.
> 
> Client side log of gRPC-client:
> 
> ```
> Oct 4, 2022 @ 18:23:09.095	Scheduled msg: RunWorkItem[1cc4494a-5d6f-499c-9f94-aae0dbe202d2]
> Oct 4, 2022 @ 18:23:09.095	Current msg: RunWorkItem[1cc4494a-5d6f-499c-9f94-aae0dbe202d2]
> Oct 4, 2022 @ 18:23:19.099	RunWorkItem[1cc4494a-5d6f-499c-9f94-aae0dbe202d2] completed exceptionally: io.grpc.StatusRuntimeException: UNAVAILABLE: Server not ready
> ```
> 
> You can see that the work item is scheduled and immediately executed and failure response is received after exactly 10s.
> 
> As we can see the exact behavior on mulitple requests and the pretty exact value of 10s shows to me that this seems to be some kind of timeout value. As the underlying operation is a streaming operation it should not be related to the client side defined gRPC deadline (otherwise I also would have expected a DEADLINE_EXCEEDED status) but must be something on the server side.
> 
> Do have an idea why we observe these 10s of delay? We would expect an immediate response if the server is not ready.

**Comment by timothycoleman** [comment]
@dpasek-senacor
Thanks for the report
This has now been addressed in https://github.com/EventStore/EventStore/pull/3609. If you get a chance would you mind confirming that your issue is resolved? You can check in the latest nightly release https://github.com/EventStore/EventStore/releases

**Comment by dpasek-senacor** [comment]
@timothycoleman 
Thanks for preparing the fix. 

Unfortunately we will probably not be able to do a test with this nightly build as we require either a Docker image or a Debian package for integration testing. The tarball would require adaptions/preparations to our tools/processes. Our time is currently a bit limited to do this. 🤷‍♂️

**Comment by timothycoleman** [comment]
@dpasek-senacor ah right, no worries. perhaps we could do with a docker nightly image, I don't think we have one at the moment. Anyway the fix will be in the upcoming 22.10.0 release

**Comment by timothycoleman** [comment]
@dpasek-senacor the fix is in two recently released versions `22.10.0` and `21.10.9`. I'll close this ticket for now, feel free to re-open it if your issue isn't resolved
