### ISSUE TITLE
EventStore 22.6.0 legacy TCP protocol missing fields (typically event_number, also others)

### ISSUE THREAD

**Issue by FeepingCreature** [EventStore/EventStore#3625]
**Describe the bug**
When connecting with TCP to EventStore 22.6.0, required fields are often missing.

**To Reproduce**
1. Run EventStore 22.6.0 with `EVENTSTORE_ENABLE_EXTERNAL_TCP=true`
2. Connect with a TCP client, such as [node-eventstore-client](https://github.com/nicdex/node-eventstore-client)
3. Read events from a stream
4. Get errors involving missing `event_number` field
5. Observe the transaction in Wireshark with https://github.com/x-cubed/event-store-dissector loaded
6. Note that `event_number` is absent whenever it would be 0. Also note further missing fields like `result` and `is_end_of_stream`. Theorize they would also be 0.

**Expected behavior**
Required fields should be present, even if they have the default value.

**Actual behavior**
They're not.

**Config/Logs/Screenshots**
![event_number](https://user-images.githubusercontent.com/540727/196636936-9704c00a-9a1f-4652-8b43-320d7ef2f4b2.png)

**EventStore details**
 - EventStore server version: 22.6.0-bionic

 - Operating system: Linux 5.15.0

 - EventStore client version (if applicable):

**Additional context**
Maybe you're using proto3 to encode proto2 messages?

**Comment by FeepingCreature** [comment]
(Wrong PR?)

**Comment by ylorph** [comment]
as of 22.x we're using proto3 instead of proto2 so the 3d party client library needs to be updated.
https://www.eventstore.com/blog/22.10.0-release-notes


Also , the TCP api is deprecated in favor of the gRPC api.

**Comment by alexeyzimarev** [comment]
I'd be careful about "is deprecated" as it's still there.

**Comment by nicdex** [comment]
We can close this. I just deployed a fix the non-official TCP client https://github.com/nicdex/node-eventstore-client that works with 22.10.

**Comment by hayley-jean** [comment]
Thanks for the updated @nicdex !
