### ISSUE TITLE
No usable version of libssl was found when running on Ubuntu 22.04

### ISSUE THREAD

**Issue by Lougarou** [EventStore/EventStore#3639]
**Describe the bug**
.NET 5 dynamically loads OpenSSL1.0 and 1.1 but Ubuntu 22.04 comes with OpenSSL 3. Running ESDB versions between 20 - 22.6 would error with "No usable version of libssl was found".

**To Reproduce**
1. Run any ESDB version between 20 - 22.6 on Ubuntu 22.04

**Expected behavior**
It should just work

**Actual behavior**
"No usable version of libssl was found"

 Operating system: Ubuntu 22.04

**Additional context**

Workaround is to install libssl-dev package (source https://forum.unity.com/threads/workaround-for-libssl-issue-on-ubuntu-22-04.1271405/ )

**Comment by ylorph** [comment]
22.10 only ?
21.10 is not supported on ubuntu 22.04

**Comment by ylorph** [comment]
Leaving open until Ubuntu 22.04 is offically supported by the server version 22.10

**Comment by mmuller99** [comment]
Any update on this? Have the same issue running the `21.10.10` release on 22.04 Ubuntu

**Comment by hayley-jean** [comment]
Thank you for reporting this @mmuller99, those images were pushed by accident instead of bionic and buster-slim
The correct images for 21.10.10 should be available on Dockerhub now

**Comment by mmuller99** [comment]
Thanks @hayley-jean , appreciate it
