### ISSUE TITLE
Helm charts? Kubernetes operator?

### ISSUE THREAD

**Issue by dvanderveeke-hofy** [EventStore/EventStore#3670]
**Is your feature request related to a problem? Please describe.**
The Helm charts have been deprecated over 2 years ago with a statement saying it's not the right approach, and a Kubernetes operator will be developed. It's been 2 years, helm charts are still deprecated and there's no Kubernetes operator? At least I can't find it, maybe I'm missing it somehow.

**Describe the solution you'd like**
I'd like either Helm charts or a Kubernetes operator to exist. Deploying EventstoreDB on Kubernetes is currently very painful.

**Describe alternatives you've considered**
Making my own helm charts, but that's obviously not recommended.

**Additional context**
Nothing.

**Comment by alexeyzimarev** [comment]
The issue doesn't belong to the database product repository. We are working on this now; the results will be announced as soon as we test the solution(s).

**Comment by alexeyzimarev** [comment]
I mean, the issue is legit, it just doesn't belong here. That's why I closed it.
