### ISSUE TITLE
Parking an event does not check if the event is already in the parked stream 

### ISSUE THREAD

**Issue by anthonyMc11** [EventStore/EventStore#3692]
**Describe the bug**
The dead letter queue for persistent subscriptions does not check for distinctness when the event is added

**To Reproduce**
1. create a service that waits until the message timeout occurs (so it is redelivered) and then parks the message
2. run some events through
3. check the parked event stream

**Expected behavior**
The event is only parked once if there is already an unacknowledged copy in the stream

**Actual behavior**
The event can be added multiple times

**Config/Logs/Screenshots**
![image](https://user-images.githubusercontent.com/2892217/210586403-ab3efa1f-26bf-45ee-bd32-76a129b3a35a.png)

**EventStore details**
 - EventStore server version:  21.10.2.0

 - Operating system: linux 

 - EventStore client version (if applicable):
5.0.9

addition context:

In the design I'm working with, if an event has failed to process I send the event to be parked, and then a second service replays the events through the HTTP api.

The issue I have is if the event is replayed (due to timeout) before I park the event, I can end up with 2 copies of the same event in the parked event stream, meaning it will be replayed twice, where as I'd want only 1 copy in the parked queue at any one time. 

For example, the code seems to currently behave like so:

`if(parkEvent){
 AddToQueue():
}
`

where as I would expect it to do something like:

```
If(parkEvent){
     if(EventIsNotAlreadyParked(event){
      AddToQueue();
}

public bool EventIsNotAlreadyParked(ResolvedEvent event){
      var alreadyParked = queue.Where(eventId == event.eventId);
        
     if(alreadyParked.Count == 0)
     {
      return true;
     }

      if( HasBeenTruncated(alreadyParked))
      {
          return true; 
      }
      else
      {
         return false;
      }
}
```

**Comment by StevenBlair123** [comment]
Parking happens free of change, so when your event times out, ES adds to the parked queue by default,
Subsequent timeouts (say you  retry 10 tiems) will be indempotent.
If you replay the parked queue, the parked stream is truncated.

I think that's how the process works.

**Comment by gregoryyoung** [comment]
Parking an event does not check if an event has been parked previously as ... this could possibly even require millions of operations.

When you explicitly park a message it is written to the parked stream. If you timeout etc then it may or may not be added to the parked stream (depends on configuration).

There should be no problem with a parked message being replayed multiple times as your handler needs to be idempotent anyways (there are edge conditions where you can receive a message multiple times). As an example of where idempotency is already needed you process a message but then lose connection/have a slow connection/etc before the ack is sent back. The message is then retried and another subscriber receives it.

**Comment by anthonyMc11** [comment]
Thanks for getting back to me Greg. 

The task I am performing is indempotent, I can run the event multiple times as still get the same result.

The case I've got is the action is computually expensive or the system is under load, which causes the time out to be reached, in this scenario I then get multiple copies of the initial event parked.  
It's wasteful running multiple copies of the same event, which is why I've raised it as a bug.

My expectation was because the persistent subscription is bound to a stream and a consumer group, and that group has an interest in those events, you would only be able to park the same event once (excluding truncated events). 

Else the source stream might only have 1 event, but the parked have (for example ) 100 copies.

**Comment by gregoryyoung** [comment]
"My expectation was because the persistent subscription is bound to a stream and a consumer group, and that group has an interest in those events, you would only be able to park the same event once (excluding truncated events)"

Let me give a counter-situation having worked on this a bunch.

What happens when you have a consumer-group.
Group-member A receives event 2732 off the subscription, it attempts to ack but alas is disconnected (damn thai wifi!)
Timeout occurs->retry Group-member B receives event 223

What now?
Group-member B receivers event

In terms of timeouts if expensive operations, raise them.

**Comment by anthonyMc11** [comment]
Hi Greg,

I totally agree with the use case and want the functionality, if my consumer goes down for whatever reason and can't ack the message then I want it to be retried. 

My bug report is there is a scenario where I've managed to get more than 1 copy of that message parked, I have been trying to distill a code example to show the issue, I will come back when I've got a working example to show you

**Comment by ylorph** [comment]
see  #3696  as well
