### ISSUE TITLE
Projection stops processing events

### ISSUE THREAD

**Issue by puco** [EventStore/EventStore#3749]
**Describe the bug**

We have a multiple projections that stop processing incoming events once a specific event arrives. The projections emit/linkTo events from multiple streams into another stream. This is the first time we observed such behavior after running EventStore for multiple years. The logs do not show anything meaningful. We can resume processing the events by stopping and starting one of the projections. Sending event into another inbound stream might also continue processing the events further (including the stuck event).

The issue does not occur all the time. But it was observed by multiple people quite consistently. Changing the projection makes the problem go away for some time, but then it could reappear.

**To Reproduce**

Let's have original event streams: domain1-id, domain2-id, domain3-id
And projections:

p1:

```
fromStreams([
  "$ce-domain1",
  "$ce-domain2",
  "$ce-domain3"
]).when({
  $any: function (s, e) {
    var data = Object.assign({}, e.data, { _source: e.streamId });
    var metadata = Object.assign({}, JSON.parse(e.metadataRaw), {
      source: e.streamId,
    });
    var id = e.body.id || e.body.masterId;
    if (!!id) {
      emit("target1-" + id, e.eventType, data, metadata);
    }
  },
});
```

p2:

```
fromStreams(["$ce-domain2", "$ce-domain3"]).when({
  $any: function (s, e) {
    if (!!e.body.id) {
      linkTo("target2-" + e.body.id, e);
    }
  },
});
```

Then we send an event into `domain3-id`

**Expected behavior**
We expect the event to appear in `domain3-id`, `$ce-domain3`, `target1-id` (via `p1`), `$ce-target1`, `target2-id` (via `p2`) and `$ce-target2`.

**Actual behavior**
The event appears in `domain3-id` and `$ce-domain3` but not in the others.
The position in the `p1` for stream `$ce-domain3` does not change.

**Config/Logs/Screenshots**

The logs contain nothing specific.

The config for the projection is:

```
mode: Continuous
Emit Enabled: YES
Track Emitted Streams: YES
Checkpoint After (ms): 
Checkpoint Handled Threshold: 4000
Checkpoint Unhandled Threshold (bytes): 10000000
Pending Events Threshold: 5000
Max Write Batch Length: 500
Maximum Number Of Allowed Writes In Flight: 
```

**EventStore details**

* EventStore server version: eventstore/eventstore:22.10.1-buster-slim
* Operating system: Windows 11 22H2 (22621.1265) with WSL2 (5.15.79.1-microsoft-standard-WSL2), in docker v20.10.22
* EventStore client version (if applicable): EventStore.Client 21.2.2 in app running on .net6

env:

```
EVENTSTORE_INSECURE=true
EVENTSTORE_DISABLE_LOG_FILE=true
EVENTSTORE_EXT_TCP_PORT=31113
EVENTSTORE_STATS_PERIOD_SEC=36000
EVENTSTORE_HTTP_PORT=80
EVENTSTORE_LOG_LEVEL=Verbose
EVENTSTORE_RUN_PROJECTIONS=All
EVENTSTORE_ENABLE_EXTERNAL_TCP=true
EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
EVENTSTORE_START_STANDARD_PROJECTIONS=true
EVENTSTORE_CLUSTER_SIZE=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ASPNETCORE_URLS=http://+:80
DOTNET_RUNNING_IN_CONTAINER=true
LANGUAGE=en_US:en
DEBIAN_FRONTEND=noninteractive
ACCEPT_EULA=Y
```

<sub>[DB-58](https://linear.app/eventstore/issue/DB-58/projection-stops-processing-events)</sub>

**Comment by alexeyzimarev** [comment]
We have seen something similar and the issue was that the event was somewhat incorrectly formed. Is the event recent or you were running the projection over older events?

The logs should say quite clearly *where* the projection has stopped. You should be able to find that specific event. If you can, get the *raw* event content and post it here. We know that the event payload might show correctly in the UI, but the raw payload might be somewhat different.

**Comment by alexeyzimarev** [comment]
I checked what it was and the invalid character was `/u0008`, which is invalid based on the JSON spec.

**Comment by puco** [comment]
As we already implemented a workaround and refactored parts of the code that encountered this issue I need to go back and try to re-reproduce it. One thing I remember though, I didn't see anything strange in the logs. Can you help what should I turn on to get the most logging possible? And regarding the RAW event? Should I get it using the EventStore API?

**Comment by alexeyzimarev** [comment]
In our case, the projection crashed and it was an error in the log. It should be there by default.

The raw payload is what you normally get from the client (bytes).

**Comment by alexeyzimarev** [comment]
If you managed to work around the issue, it must have been something else. What was the workaround, can you share it?

**Comment by timothycoleman** [comment]
Closing for now, feel free to reopen if this is still an issue for you
