### ISSUE TITLE
Want to remove PrepareCount and CommitCount db settings and docs

### ISSUE THREAD

**Issue by timothycoleman** [EventStore/EventStore#3750]
They don't seem to do anything and the docs are confusing

<sub>[DB-57](https://linear.app/eventstore/issue/DB-57/want-to-remove-preparecount-and-commitcount-db-settings-and-docs)</sub>

**Comment by alexeyzimarev** [comment]
As a consequence, we'd need to remove them from the clients, subscribe to $all always require those two.

**Comment by ylorph** [comment]
> As a consequence, we'd need to remove them from the clients, subscribe to $all always require those two.

Those are server configuration settings, it's not removing them from the event api surface 
https://developers.eventstore.com/server/v22.10/cluster.html#acknowledgements

and the doc is wrong : "every write to the cluster needs to be acknowledged by all cluster members." , it's by a majority of the nodes ( leader & followers)
