### ISSUE TITLE
Change default on retry for connection settings

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#377]
Many people get confused when they connect and there is no node so it retries by default. No reconnections is a better default. Thoughts?

**Comment by gregoryyoung** [comment]
@all this is technically a breaking change as it changes a default there are other ways of doing it such as 

.FailOnNoConnection()

Is it worth changing the default or just add this

**Comment by 101v** [comment]
Is FailOnNoConnection() option available with V3.0.3, I cannot see it in the settings. I would vote for this option.

**Comment by gregoryyoung** [comment]
Wouldn't that just be retry 0?

On Tuesday, April 14, 2015, Vimal <notifications@github.com> wrote:

> Is FailOnNoConnection() option available with V3.0.3, I cannot see it in
> the settings. I would vote for this option.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/377#issuecomment-92867943>
> .
>


-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Eg we are only talking about adding a new wording to the builder for that.

The question is more so about the default and people getting confused with the reconnecting default

**Comment by 101v** [comment]
I tried setting retry to 0 by LimittingReconnectionTo(0). But it still does not throw any aggregate exception.
            var settings = ConnectionSettings.Create()
                .SetDefaultUserCredentials(cred)
                .SetReconnectionDelayTo(new TimeSpan(0, 0, 2))
                .LimitReconnectionsTo(0);
            var eventStoreConnection = EventStore.ClientAPI.EventStoreConnection.Create(settings, GetEndPoint(), "name of the connection");
            eventStoreConnection.ConnectAsync().Wait();

**Comment by gregoryyoung** [comment]
What does log say?

On Tuesday, April 14, 2015, Vimal <notifications@github.com> wrote:

> I tried setting retry to 0 by LimittingReconnectionTo(0). But it still
> does not throw any aggregate exception.
> var settings = ConnectionSettings.Create()
> .SetDefaultUserCredentials(cred)
> .SetReconnectionDelayTo(new TimeSpan(0, 0, 2))
> .LimitReconnectionsTo(0);
> var eventStoreConnection =
> EventStore.ClientAPI.EventStoreConnection.Create(settings, GetEndPoint(),
> "name of the connection");
> eventStoreConnection.ConnectAsync().Wait();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/377#issuecomment-92871087>
> .
>


-- 
Studying for the Turing test

**Comment by 101v** [comment]
[06,14:48:18.344,INFO] ClientAPI TcpConnection closed [14:48:18.343: N127.0.0.1:
1113, L, {46907c3b-19bb-46ee-b6c6-4aca4122d5c3}]:
Received bytes: 0, Sent bytes: 0
Send calls: 0, callbacks: 0
Receive calls: 0, callbacks: 0
Close reason: [Success] Connection establishment timeout.

[06,14:48:18.351,DEBUG] TcpPackageConnection: connection [127.0.0.1:1113, L, {46
907c3b-19bb-46ee-b6c6-4aca4122d5c3}] was closed cleanly.

**Comment by gregoryyoung** [comment]
And the rest?

On Tuesday, April 14, 2015, Vimal <notifications@github.com> wrote:

> [06,14:48:18.344,INFO] ClientAPI TcpConnection closed [14:48:18.343:
> N127.0.0.1:
> 1113, L, {46907c3b-19bb-46ee-b6c6-4aca4122d5c3}]:
> Received bytes: 0, Sent bytes: 0
> Send calls: 0, callbacks: 0
> Receive calls: 0, callbacks: 0
> Close reason: [Success] Connection establishment timeout.
>
> [06,14:48:18.351,DEBUG] TcpPackageConnection: connection [127.0.0.1:1113,
> L, {46
> 907c3b-19bb-46ee-b6c6-4aca4122d5c3}] was closed cleanly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/377#issuecomment-92888393>
> .
>


-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
You probably need to enable verbose logging to get anything useful

On Tuesday, April 14, 2015, Greg Young <gregoryyoung1@gmail.com> wrote:

> And the rest?
>
> On Tuesday, April 14, 2015, Vimal <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> [06,14:48:18.344,INFO] ClientAPI TcpConnection closed [14:48:18.343:
>> N127.0.0.1:
>> 1113, L, {46907c3b-19bb-46ee-b6c6-4aca4122d5c3}]:
>> Received bytes: 0, Sent bytes: 0
>> Send calls: 0, callbacks: 0
>> Receive calls: 0, callbacks: 0
>> Close reason: [Success] Connection establishment timeout.
>>
>> [06,14:48:18.351,DEBUG] TcpPackageConnection: connection [127.0.0.1:1113,
>> L, {46
>> 907c3b-19bb-46ee-b6c6-4aca4122d5c3}] was closed cleanly.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/377#issuecomment-92888393>
>> .
>>
>
>
> --
> Studying for the Turing test
>
>

-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Answer to original question Let's leave it and just add the new thing to builder
