### ISSUE TITLE
Provide suggestions for unknown/invalid configuration parameters

### ISSUE THREAD

**Issue by matsientst** [EventStore/EventStore#3784]
**Is your feature request related to a problem? Please describe.**
When a user makes a minor mistake passing a parameter the system doesn't provide any attempts to guide them to the correct answer. If the user enters a configuration option like `--cluster-sze` the system just ignores it and lists it as an unknown option. 

**Describe the solution you'd like**
Use the Levenshtein distance algorithm to find the closest default configuration name match. It should look to see if the distance is up to 5 characters off and provide the best suggestion. If it's wildly off we need to just let it go rather than suggesting something completely inaccurate

**Comment by hayley-jean** [comment]
Closed by https://github.com/EventStore/EventStore/pull/3785
