### ISSUE TITLE
es query bad follow uri when no projections

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#379]

**Comment by briandonahue** [comment]
@gregoryyoung Does this mean when projections aren't enabled?   I am running with projections turned on (-RunProjections All) and enabled (via the UI).  No custom projections yet.

**Comment by gregoryyoung** [comment]
im not even sure this is valid :)

-RunProjections All

I havnt run in windows regularly though can you print a --whatif?

On Tue, Jan 20, 2015 at 11:59 PM, Brian Donahue <notifications@github.com>
wrote:

> @gregoryyoung <https://github.com/gregoryyoung> Does this mean when
> projections aren't enabled? I am running with projections turned on
> (-RunProjections All) and enabled (via the UI). No custom projections yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/379#issuecomment-70742840>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
It does nevermind.

On Wed, Jan 21, 2015 at 12:01 AM, Greg Young <gregoryyoung1@gmail.com>
wrote:

> im not even sure this is valid :)
>
> -RunProjections All
>
> I havnt run in windows regularly though can you print a --whatif?
>
> On Tue, Jan 20, 2015 at 11:59 PM, Brian Donahue <notifications@github.com>
> wrote:
>
>> @gregoryyoung <https://github.com/gregoryyoung> Does this mean when
>> projections aren't enabled? I am running with projections turned on
>> (-RunProjections All) and enabled (via the UI). No custom projections yet.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/379#issuecomment-70742840>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by briandonahue** [comment]
Sorry, I'm bouncing btw google groups and here.   I did just run with the other syntax - same issue, it seems.

**Comment by briandonahue** [comment]
Exiting with exit code: 0.
Exit reason: WhatIf option specified
[06192,01,22:14:04.340] 
ES VERSION:               3.0.1.0 (release-oss-v3.0.1/7fa876c111888dd5980dbd86d126e6abe13b05ab, Thu, 23 Oct 2014 22:27:04 +0100)
OS:                       Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
RUNTIME:                  .NET 4.0.30319.18444 (64-bit)
GC:                       3 GENERATIONS
LOGS:                     c:\ESData\logs

HELP:                     False (<DEFAULT>)
VERSION:                  False (<DEFAULT>)
LOG:                      c:\ESData\logs (Command Line)
CONFIG:                   <empty> (<DEFAULT>)
DEFINES:                  <empty> (<DEFAULT>)
WHAT IF:                  True (Command Line)
INT IP:                   127.0.0.1 (<DEFAULT>)
EXT IP:                   127.0.0.1 (<DEFAULT>)
INT HTTP PORT:            2112 (<DEFAULT>)
EXT HTTP PORT:            2113 (<DEFAULT>)
INT TCP PORT:             1112 (<DEFAULT>)
INT SECURE TCP PORT:      0 (<DEFAULT>)
EXT TCP PORT:             1113 (<DEFAULT>)
EXT SECURE TCP PORT:      0 (<DEFAULT>)
INT TCP HEARTBEAT TIMEOUT: 700 (<DEFAULT>)
EXT TCP HEARTBEAT TIMEOUT: 1000 (<DEFAULT>)
INT TCP HEARTBEAT INTERVAL: 700 (<DEFAULT>)
EXT TCP HEARTBEAT INTERVAL: 2000 (<DEFAULT>)
FORCE:                    False (<DEFAULT>)
CLUSTER SIZE:             1 (<DEFAULT>)
NODE PRIORITY:            0 (<DEFAULT>)
MIN FLUSH DELAY MS:       2 (<DEFAULT>)
COMMIT COUNT:             -1 (<DEFAULT>)
PREPARE COUNT:            -1 (<DEFAULT>)
ADMIN ON EXT:             True (<DEFAULT>)
STATS ON EXT:             True (<DEFAULT>)
GOSSIP ON EXT:            True (<DEFAULT>)
DISABLE SCAVENGE MERGING: False (<DEFAULT>)
DISCOVER VIA DNS:         True (<DEFAULT>)
CLUSTER DNS:              fake.dns (<DEFAULT>)
CLUSTER GOSSIP PORT:      30777 (<DEFAULT>)
GOSSIP SEED:              <empty> (<DEFAULT>)
STATS PERIOD SEC:         30 (<DEFAULT>)
CACHED CHUNKS:            -1 (<DEFAULT>)
CHUNKS CACHE SIZE:        536871424 (<DEFAULT>)
MAX MEM TABLE SIZE:       1000000 (<DEFAULT>)
DB:                       c:\ESData\data (Command Line)
MEM DB:                   False (<DEFAULT>)
SKIP DB VERIFY:           False (<DEFAULT>)
RUN PROJECTIONS:          All (Command Line)
PROJECTION THREADS:       3 (<DEFAULT>)
WORKER THREADS:           5 (<DEFAULT>)
HTTP PREFIXES:            <empty> (<DEFAULT>)
ENABLE TRUSTED AUTH:      False (<DEFAULT>)
CERTIFICATE STORE LOCATION: <empty> (<DEFAULT>)
CERTIFICATE STORE NAME:   <empty> (<DEFAULT>)
CERTIFICATE SUBJECT NAME: <empty> (<DEFAULT>)
CERTIFICATE THUMBPRINT:   <empty> (<DEFAULT>)
CERTIFICATE FILE:         <empty> (<DEFAULT>)
CERTIFICATE PASSWORD:     <empty> (<DEFAULT>)
USE INTERNAL SSL:         False (<DEFAULT>)
SSL TARGET HOST:          n/a (<DEFAULT>)
SSL VALIDATE SERVER:      True (<DEFAULT>)
AUTHENTICATION TYPE:      internal (<DEFAULT>)
PREPARE TIMEOUT MS:       2000 (<DEFAULT>)
COMMIT TIMEOUT MS:        2000 (<DEFAULT>)
UNSAFE DISABLE FLUSH TO DISK: False (<DEFAULT>)
GOSSIP INTERVAL MS:       1000 (<DEFAULT>)
GOSSIP ALLOWED DIFFERENCE MS: 60000 (<DEFAULT>)
GOSSIP TIMEOUT MS:        500 (<DEFAULT>)

[06192,01,22:14:04.371] Exiting with exit code: 0.
Exit reason: WhatIf option specified

**Comment by briandonahue** [comment]
I just realized, I may have inserted the events with an old version of the Client.  They are there, I can see them in the stream browser, but not sure if that could have any bearing on this...

**Comment by gregoryyoung** [comment]
Try this:

https://github.com/EventStore/EventStore/tree/esquery

Greg

On Wed, Jan 21, 2015 at 12:52 AM, Brian Donahue <notifications@github.com>
wrote:

> I just realized, I may have inserted the events with an old version of the
> Client. They are there, I can see them in the stream browser, but not sure
> if that could have any bearing on this...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/379#issuecomment-70751428>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
for UI https://github.com/EventStore/EventStore.UI/issues/53

You can use a one time projection as well to query btw.

On Wed, Jan 21, 2015 at 12:57 AM, Greg Young <gregoryyoung1@gmail.com>
wrote:

> Try this:
>
> https://github.com/EventStore/EventStore/tree/esquery
>
> Greg
>
> On Wed, Jan 21, 2015 at 12:52 AM, Brian Donahue <notifications@github.com>
> wrote:
>
>> I just realized, I may have inserted the events with an old version of
>> the Client. They are there, I can see them in the stream browser, but not
>> sure if that could have any bearing on this...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/379#issuecomment-70751428>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by briandonahue** [comment]
You move at the speed of light.  Pulling this down.  Good point re: one-time projection, they just seem more permanent, and I'm just hacking around.  Actually pulled a bunch of opaque neventstore events from SQL Server into ES because it was so much easier and more fun to query there :)  Will eventually turn this into a full transition to ES, but need to do work on the app first.

**Comment by gregoryyoung** [comment]
esquery works now I left an issue on es.ui

On Wed, Jan 21, 2015 at 1:03 AM, Brian Donahue <notifications@github.com>
wrote:

> You move at the speed of light. Pulling this down. Good point re: one-time
> projection, they just seem more permanent, and I'm just hacking around.
> Actually pulled a bunch of opaque neventstore events from SQL Server into
> ES because it was so much easier and more fun to query there :) Will
> eventually turn this into a full transition to ES, but need to do work on
> the app first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/379#issuecomment-70752937>
> .
>



-- 
Studying for the Turing test
