### ISSUE TITLE
Command line parameter documentation 

### ISSUE THREAD

**Issue by ro6** [EventStore/EventStore#381]
I'm just getting started with ES 3.0.1 and many of the command line parameters specified at http://docs.geteventstore.com/server/3.0.1/command-line-arguments/ are incorrect in spelling/capitalization. Trial and error led me to a working config with everything I need in JSON, but not with YAML. In particular, the `httpPrefixes` param didn't seem to have a YAML equivalent that I could figure out. It would be nice to have a column in the table for the YAML commands too, since that's a nicer syntax to read.

**Comment by pgermishuys** [comment]
@ro6 this will be fixed in https://github.com/EventStore/docs.geteventstore.com/tree/command-line

Here is a preliminary update to the documentation that might help you a bit.
https://github.com/EventStore/docs.geteventstore.com/blob/command-line/server/3.0.2-pre/command-line-arguments.md
