### ISSUE TITLE
Lock folder

### ISSUE THREAD

**Issue by CindyLoMinChung** [EventStore/EventStore#3818]
**Describe the bug**
When i tried to run .\EventStore.ClusterNode.exe --insecure --enable-atom-pub-over-http --run-projections=all i could not get access to the folder and i keep having this error:  Couldn't acquire exclusive lock on DB at 'C:\Users\Cindy\OneDrive\Desktop\EventStore-OSS-Windows-2019-v22.10.1\EventStore-OSS-Windows-2019-v22.10.1\data'.

**To Reproduce**
1. Write the command .\EventStore.ClusterNode.exe --insecure --enable-atom-pub-over-http --run-projections=all
2. And click enter it will show this error at the end Couldn't acquire exclusive lock on DB at 'C:\Users\Cindy\OneDrive\Desktop\EventStore-OSS-Windows-2019-v22.10.1\EventStore-OSS-Windows-2019-v22.10.1\data'.

**Expected behavior**
Should have access to the dashboard of eventstore.
**Actual behavior**
Folder is lock and could not access to the dashboard of eventstore

**Config/Logs/Screenshots**
**How i solved the issue?**
I am sorry i could not paste a screenshot i clear the screen before i rerun it but to resolve this issue, i have found this commant icacls "foldername" /grant username:F/t to grant me permission to that folder. and rerun the command line. I am proposing to add it in the documentation

**EventStore details**
 - EventStore server version:

 - Operating system:

 - EventStore client version (if applicable):

**Additional context**

**Comment by CindyLoMinChung** [comment]
Thanks for reaching out. My oneDrive folder is not connected to my laptop so I think it's not sync to my laptop.

**Comment by CindyLoMinChung** [comment]
I find another way to not have this problem check if eventstore is not running in the background in the task manager.

**Comment by ylorph** [comment]
So you had 2 instances trying to get a lock to the same dB files?

**Comment by CindyLoMinChung** [comment]
i am not sure but i saw eventstore trying to run in my task manager

**Comment by alexeyzimarev** [comment]
Your folder is in OneDrive, and OneDrive seems to be willing to copy data files to the cloud.

**Comment by alexeyzimarev** [comment]
@CindyLoMinChung How did it go? Have you been able to see it resolved?

**Comment by CindyLoMinChung** [comment]
@alexeyzimarev Hi! Yes it was resolved. Thank you for your help!!!!!

**Comment by timothycoleman** [comment]
:+1: glad that resolved it
