### ISSUE TITLE
Add ability to control how assemblies are scanned for plugins detection

### ISSUE THREAD

**Issue by SlyNet** [EventStore/EventStore#382]
MessageHierarchy and maybe other classes are scanning all assemblies that are loaded into app domain. This sometimes fails and there is no ability for client to fix or exclude assemblies.

**Comment by gregoryyoung** [comment]
Note this only applies to embedded client.

**Comment by jen20** [comment]
This is actually fairly reasonable since we ILMerge all the assemblies anyway.

**Comment by jen20** [comment]
Is this still the case with 84ef2ef?

**Comment by pgermishuys** [comment]
@SlyNet is this issue still relevant?

**Comment by SlyNet** [comment]
since `LoadAvailableTypes` is catching a reflection exception it should work. Unfortunately we removed assembly that caused that exception in our code, so I can't reproduce this issue anymore.

**Comment by pgermishuys** [comment]
Going to close this issue, please reopen if this issue pops up again.
