### ISSUE TITLE
Support for CancellationToken in .net client API

### ISSUE THREAD

**Issue by SlyNet** [EventStore/EventStore#383]

**Comment by kolesnick** [comment]
+1

**Comment by jen20** [comment]
Most operations are not cancellable, what would this achieve?

**Comment by gregoryyoung** [comment]
If they havnt been yet sent they are cancellable.. id agree that setting
sane connection setings normally handles this but what if for ibstance each
operation has different requirements?

**Comment by SlyNet** [comment]
The case when we wan't to keep reconnecting, but each try should have its own timeout. Is it possible?

**Comment by gregoryyoung** [comment]
You could do this by setting reconnect = 0 and wrapping the connection with your own connection logic.
