### ISSUE TITLE
Add a `--development` mode that turns off cache headers

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#384]
Have watched a number of people get trolled by caching in the UI, I think it's worth adding a `--development` flag that sets events to non-cacheable.

On second thoughts, given the usage some of these "not for production" flags get, it probably needs to be called `--this-is-not-for-production-and-I-understand-Im-doing-a-bad-thing-but-please-dont-cache`.

**Comment by gregoryyoung** [comment]
Yes I have had a card on this for a while.

On Wed, Jan 28, 2015 at 3:43 PM, James Nugent <notifications@github.com>
wrote:

> Have watched a number of people get trolled by caching in the UI, I think
> it's worth adding a --development flag that sets events to non-cacheable.
>
> On second thoughts, given the usage some of these "not for production"
> flags get, it probably needs to be called
> --this-is-not-for-production-and-I-understand-Im-doing-a-bad-thing-but-please-dont-cache
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/384>.
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
Will take a look today and try to get it in 3.1.0
