### ISSUE TITLE
Improve documentation around projection code

### ISSUE THREAD

**Issue by rmfaheem** [EventStore/EventStore#3843]
**Issue Description**:
Currently, the documentation lacks sufficient information and clarity regarding the implementation of projection code. The purpose and usage of some functions are slightly ambiguous. This creates confusion and makes it difficult for users, especially newcomers, to implement and utilize projections effectively.

**Expected Behavior**:
The documentation would be enhanced by providing comprehensive and detailed explanations, along with practical examples, to guide users through the implementation of the projection code.

<sub>[DB-123](https://linear.app/eventstore/issue/DB-123/improve-documentation-around-projection-code)</sub>

**Comment by alexeyzimarev** [comment]
test

**Comment by alexeyzimarev** [comment]
Test

**Comment by alexeyzimarev** [comment]
It's the docs issue, will be in that repo
