### ISSUE TITLE
Make projections a separate unsupported binary distribution

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#386]
Although projections are a beta feature, they have until this release been used internally by user management, meaning that the default option for `--run-projections` has been `system` rather than `none`. This was changed in #348, which switched to writing directly into the `$users` stream instead of materialising this from a projection.

Since the vast majority of issues we see both commercially and in the open source product are with projections, we want to split builds which enable projections into a "completely unsupported" binary vs the supported version which would be equivalent to running without projections. To make the Event Store more approachable for newcomers however it would be best to do this at the build system layer rather than a feature toggle, since removing projections removes the dependency on C++, and shortens the fresh-checkout-build time from 20-25 minutes to typically less than 1 minute.

To achieve this the build script needs modifiying to accept a `--with-projections` like parameter which can be used to build the C++ and pass a token definition to the build system which can then be used in #ifdefs. Needs some investigation into conditional project references because .NET.

**Comment by gregoryyoung** [comment]
As discussed in lt i think this is best to alleviate confusion. I think its
relatively easy froma  build perspective

**Comment by jen20** [comment]
Yup, it should be straightforward. I'll work on it this evening.

**Comment by seburgi** [comment]
So, there will not be a commercial build that includes projections anymore?

**Comment by dnauck** [comment]
What about the internal projections like ```$by_category```and ```$by_event_type```, etc.? Are they also removed?

**Comment by gregoryyoung** [comment]
They are as of now not used by anything internally so we have no dependncy
on them.

**Comment by seburgi** [comment]
If there won't be a separate commercial build that includes projections, that'd be pretty bad news for us, as we would like to continue to use your Node Manager. We are already using projections and before you ask, yes, we knew that they were beta and unsupported, but to be fair, if a feature is beta I'm assuming that at some point in the not too distant future it will graduate to production quality, especially if said feature is part of the products tagline...

**Comment by scottcate** [comment]
Is there a message here that projections are going away, and will not be
supported going forward?

Is is this just a build optimization strategy?

Or something else?

@ScottCate


On Wednesday, February 4, 2015, Sebastian Burgstaller <
notifications@github.com> wrote:

> If there won't be a separate commercial build that includes projections,
> that'd be pretty bad news for us, as we would like to continue to use your
> Node Manager. We are already using projections and before you ask, yes, we
> knew that they were beta and unsupported, but to be fair, if a feature is
> beta I'm assuming that at some point in the not too distant future it will
> graduate to production quality, especially if said feature is part of the
> products tagline...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/386#issuecomment-72860698>
> .
>


-- 
@ScottCate (Mobile)
602-418-0770

**Comment by jen20** [comment]
There a few reasons. First is that the vast majority of the support burden (both open source and commercial) is related to projections, which aren't supported at all anyway. People have the idea that since it's there it should work, despite it being described as beta with known issues. This was probably not helped by our having taken a dependency on projections originally for internal authentication and therefore making the default projections mode `system` - we've now removed this and could instead make it `none`. Hopefully having to run a binary with the word "unsupported" in the name will make the distinction cleaner.

Secondly, it lowers the bar significantly to contributing on the database side (you don't need any C++ build tools available), and reduces the build from ~20 minutes (perhaps more if you have to pull down dependencies, especially on Windows) to under 1 minute.

If you want to run the unsupported binaries with the commercial tooling you could (it's just a different node binary), though support on the projections side will be very limited.

The biggest known problem right now for system projections is recovery during a master takeover in clustered operation which happens a small percentage of the time and seems to coincide with when communication via streams was introduced to allow for distribution of queries through a cluster. We're trying to decide whether to investigate the problem and stick with streams or try to revert back to in-memory comms instead at the moment.

**Comment by seburgi** [comment]
Thanks for the clarification, James. It all makes sense and as long as we are still able to use commercial tooling I am mostly good with this decision.

**Comment by pgermishuys** [comment]
Is this still something that we want to do/investigate? @gregoryyoung @jen20 ?

**Comment by gregoryyoung** [comment]
id lean towards no at this point
