### ISSUE TITLE
AtomController generates wrong UI for text/html request

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/EventStore#390]
The new UI for events browsing is available via Stream Browser menu, its URL is like http://localhost:2113/web/index.html#/streams/$users

However, when using HTTP API, the URL is like http://localhost:2113/streams/$users
This URL also generates a valid response for text/html content type, but it uses the "old UI" (from ES v2). js, css and html files from that UI are unavailable, therefore when one opens the Atom URL in their browser, they get an empty page with JS errors in the console.

"Old UI" is generated by AtuoController class. In v3.0.1 tag, it is To<T>(T value) method, line number 823.

It should either generate a "new UI" or redirect to the Stream Browser.

**Comment by gregoryyoung** [comment]
I can reproduce here.

Let's get this handled before the new release.


Greg

On Sat, Feb 7, 2015 at 6:41 PM, Alexey Zimarev <notifications@github.com>
wrote:

> The new UI for events browsing is available via Stream Browser menu, its
> URL is like http://localhost:2113/web/index.html#/streams/$users
>
> However, when using HTTP API, the URL is like
> http://localhost:2113/streams/$users
> This URL also generates a valid response for text/html content type, but
> it uses the "old UI" (from ES v2). js, css and html files from that UI are
> unavailable, therefore when one opens the Atom URL in their browser, they
> get an empty page with JS errors in the console.
>
> "Old UI" is generated by AtuoController class. In v3.0.1 tag, it is To(T
> value) method, line number 823.
>
> It should either generate a "new UI" or redirect to the Stream Browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/390>.
>



-- 
Studying for the Turing test

**Comment by alexeyzimarev** [comment]
It is HttpCodec class, not AtomController.
The URL works when being called from the UI page. There, it is properly handled by the Angular routing, but when called in isolation, it points to the old HttpCodec code.
