### ISSUE TITLE
build on windows fails (v8, due missing directory)

### ISSUE THREAD

**Issue by robvdlv** [EventStore/EventStore#392]
Attempting a from-scratch build of dev branch @87e7c77e913377ce4619e47db6b5d5e6373688b5 on Windows 8.1. AFAIK I have met all prerequisites in terms of what needs to be installed and available on path. Using powershell to build, with full rights.

See below for details.
As far as I can see, there seems to be a directory name mismatch.

The build looks for folder ```<eventstore>\v8\build\gyp_v8```.
What actually exists on disk however, is ```<eventstore>\v8\build\gyp```.

```
C:\dev\oss\EventStore [dev...origin/dev]> .\build.cmd
C:\dev\oss\EventStore\src\libs\x64\js1.dll
Cannot run a 'quick' build - js1.dll is not found at C:\dev\oss\EventStore\src\libs\x64
Running full build instead
Build Configuration
-------------------
Target: full
Platform: x64
Configuration: release
Version: 0.0.0.0
Visual Studio Version will be autodetected
Additional Defines:


All dependencies already met.

No specific version of Visual Studio provided, using 2013
C:\dev\oss\EventStore\v8\third_party\python_26\python.exe: can't open file 'C:\dev\oss\EventStore\v8\build\gyp_v8': [Errno 2] No such file or directory
Exec: (C:\dev\oss\EventStore\v8)\nFailed executing  & $pythonExecutable $gypFile $vsVersionParameter $gypPlatformParameter
At C:\dev\oss\EventStore\scripts\build-windows\build-functions.ps1:38 char:9
+         throw ("Exec: (" + $pwd + ")\n" + $ErrorMessage)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Exec: (C:\dev\o...tformParameter :String) [], RuntimeException
    + FullyQualifiedErrorId : Exec: (C:\dev\oss\EventStore\v8)\nFailed executing  & $pythonExecutable $gypFile $vsVersionParameter $gypPlatformParameter

```

**Comment by jen20** [comment]
Fairly sure I've seen this before when some of the dependencies are incomplete - we only check that there's a repository there (svn in the case of most of the dependencies), not that it's at the correct revision. Can you try deleting the entire `v8` directory from the repository root and rerunning the build?

**Comment by robvdlv** [comment]
Definitely. Will try your suggestion and let you know the outcome asap.

**Comment by robvdlv** [comment]
James you were right. Apparently SVN failed to checkout the repo successfully the first time. Cleanup and retry did the job.

Thanks!

**Comment by jen20** [comment]
This has become an increasingly frequent problem since Google seem unable to install a valid certificate on the site hosting the Chrome and V8 source... Hopefully you should be building now!

**Comment by kellyelton** [comment]
Issue moved to [EventStore/EventStore.JVM #50](https://github.com/EventStore/EventStore.JVM/issues/50) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by kellyelton** [comment]
Uhm. Whoops. :see_no_evil:
