### ISSUE TITLE
Projection faulted due to “CommitTimeout”

### ISSUE THREAD

**Issue by hh54188** [EventStore/EventStore#3933]
**Describe the bug**
Projection faulted. See message "Failed to write events to $xxxxxx. Retry limit of 5 reached. Reason: CommitTimeout."

**To Reproduce**
Unclear. It happened randomly.

**Expected behavior**
No projection faulted

**Actual behavior**
Projection faulted

**Config/Logs/Screenshots**

```
{ "PID": "5740", "ThreadID": "20", "Date": "2023-08-15T05:25:43.199132Z", "Level": "Error", "Logger": "ProjectionManager", "Message": "The '{projection}' projection faulted due to '{e}'", "EventProperties": { "projection": "$by_event_type", "e": "Failed to write events to $et-xxxxxx. Retry limit of 5 reached. Reason: CommitTimeout. Checkpoint: C:2025108315655\/P:2025108315655." } }
```

![](https://uploads.linear.app/a2a29b63-594b-4491-8437-5f7f43da2367/74f9dd23-0291-4050-bc18-fc5b73e16316/38cd07ae-abdf-4923-847d-e0d3a5c81a1d)

**EventStore details**

* EventStore server version: Event Store 5.0.7.0
* Operating system: Windows Server 2019 Datacenter
* EventStore client version (if applicable): N/A

**Additional context**

* We are using the commercial version of EventStore 5.X, is there some commercial support we can seek? We don’t have any account to login the [support portal](https://eventstore.freshdesk.com/support/login)
* It seems the 5.x version is not in the [long term support plan](https://www.eventstore.com/eventstoredb-long-term-support-and-release-schedule) anymore. Can we still get a support for this version even in the commercial support way?

<sub>[DB-347](https://linear.app/eventstore/issue/DB-347/projection-faulted-due-to-committimeout)</sub>

**Comment by ylorph** [comment]
Reached out to customer engagement.

We'll handle from there probably

Seems to be a custoemr who churned a few years back .

**Comment by rmfaheem** [comment]
Hello,

This error usually occurs when there is high load on the server and projection writes time out too many times which then leads to the projection faulting.

We recommend that you consider upgrading the version of EventStoreDB to 22.10.2 which has significant improvements to projections and to cluster stability.

Kind regards,
Faheem - Engineer In Support

**Comment by hayley-jean** [comment]
Hi @hh54188,

Just to add to @rmfaheem's response, you should be able to start the projection again through the UI or API after it has stopped with that error

To answer your other questions:

> It seems the 5.x version is not in the long term support plan anymore.

Yes, version 5.x is out of support. While you can still download the binaries and docs are still available, we aren't releasing any more fixes or patches to the OSS versions of 5.x

> Can we still get a support for this version even in the commercial support way?

Yes, we can still offer some commercial support for version 5.x if there is a reason you cannot upgrade to 22.10+, or if you need help with upgrading to a later version.

You can send an enquiry about support using [this form](https://www.eventstore.com/support) and someone will get in contact with you about commercial support options for version 5.

I'm going to close this issue for now as version 5.x is out of support in GitHub issues
