### ISSUE TITLE
EventStoreCatchUpSubscription OnSubscriptionDropped Connection was closed

### ISSUE THREAD

**Issue by csmorley** [EventStore/EventStore#394]
I have a EventStoreCatchUpSubscription that spits out events fine.

When i hit a break point in code (both within the OnEventAppeared and also with other non-related code) and even if i resume immediately (less than a second wait), more often than not my catch up subscription gets dropped.

The exception parameter = {"Connection was closed."}

The SubscriptionDropReason = ConnectionClosed

I am using VS2013 with SP4.

When running without breakpoints it whizzes along perfectly fine and no connections are dropped.

Anything to do with timeouts, something i am doing, or something else?

**Comment by gregoryyoung** [comment]
This is because you are hitting a connection timeout due to stopping all
threads in the debugger.

There are options on the connection and a command line param on the server
to adjust these timeouts.

Cheers,

Greg

On Friday, February 13, 2015, Chris Morley <notifications@github.com> wrote:

> I have a EventStoreCatchUpSubscription that spits out events fine.
>
> When i hit a break point in code (both within the OnEventAppeared and also
> with other non-related code) and even if i resume immediately (less than a
> second wait), more often than not my catch up subscription gets dropped.
>
> The exception parameter = {"Connection was closed."}
>
> The SubscriptionDropReason = ConnectionClosed
>
> I am using VS2013 with SP4.
>
> When running without breakpoints it whizzes along perfectly fine and no
> connections are dropped.
>
> Anything to do with timeouts, something i am doing, or something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/394>.
>


-- 
Studying for the Turing test

**Comment by csmorley** [comment]
Awesome, that makes perfect sense now. Many thanks

**Comment by gregoryyoung** [comment]
Good one to write a faq type doc on as I'm sure many hit this.

On Friday, February 13, 2015, Chris Morley <notifications@github.com> wrote:

> Awesome, that makes perfect sense now. Many thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/394#issuecomment-74257096>
> .
>


-- 
Studying for the Turing test

**Comment by csmorley** [comment]
`--ext-tcp-heartbeat-timeout=20000 --int-tcp-heartbeat-timeout=2000` seemed to do the trick

**Comment by gregoryyoung** [comment]
You shouldn't need Int... That's cluster comms unless you are running
embedded. Just remember that will give you 20 sec :)

On Friday, February 13, 2015, Chris Morley <notifications@github.com> wrote:

> --ext-tcp-heartbeat-timeout=20000 --int-tcp-heartbeat-timeout=2000 seemed
> to do the trick
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/394#issuecomment-74258643>
> .
>


-- 
Studying for the Turing test
