### ISSUE TITLE
Get an ConnectionSettingsBuilder Instance

### ISSUE THREAD

**Issue by Gentlehag** [EventStore/EventStore#395]
In some examples i found that with new ConnectionSettingsBuilder() i could get an isntance of the ConnectionSettingsBuilder . But as it points out that it has no public ctor ?

How should i use it?

**Comment by rcknight** [comment]
You need to use the static method ConnectionSettings.Create()

Docs here: http://docs.geteventstore.com/dotnet-api/3.0.1/connecting-to-a-server/

**Comment by jen20** [comment]
We could probably make the constructors for the builders public without a huge amount of effort too.

**Comment by gregoryyoung** [comment]
@james do we want to do that and create an issue towards it or ?
