### ISSUE TITLE
Ability to access event created date from projections

### ISSUE THREAD

**Issue by hg-jarlinghaus** [EventStore/EventStore#3959]
**Is your feature request related to a problem? Please describe.**
The created field is accessible from clients but not in projections.

**Describe the solution you'd like**
The addition of the created field to projection events. The ability to set the created field for new events inserted into the database would also be useful as it would allow migrating the events without changing this data.

**Describe alternatives you've considered**
This was [proposed before](https://github.com/EventStore/EventStore/issues/1344) but closed with the suggestion that a created timestamp should be stored in the metadata of each event to also allow migrating events. While that may be the case, this is entirely unhelpful if you're currently relying on the created field exposed in the clients as the timestamp for when the event occurred (as I am) since it requires migrating all your existing data and changing all code that makes use of this, which is a lot of trouble to use data that already exists and is freely exposed elsewhere.

<sub>[DB-415](https://linear.app/eventstore/issue/DB-415/ability-to-access-event-created-date-from-projections)</sub>

**Comment by ylorph** [comment]
The created date should not be used for business purpose , as it is just a moment in time, the one from the server and does not include any timezone that is most of the time needed . Also consider the case of when the server goes for summer or winter time , or when NTP does a time correction , this will change the time of the server in unexpected ways .

I understand it is troublesome to change, but I would go through it, to get the real business time for the application build.

**Comment by hg-jarlinghaus** [comment]
The created field seems to be handling timezones just fine? It returns the created date at the correct time in UTC-0.

**Comment by ylorph** [comment]
yeah it's essentially a unix timestamp.
In a majority of cases though it's not enough for business purposes

**Comment by alexeyzimarev** [comment]
Created date is part of system meta, and it supposes to be the actual append timestamp provided by the server. If an append timestamp is essential for the domain, it should be stored in the event. If it's essential for technical reasons, it should be stored in custom/user metadata. Server-set created date provides transparency for the technical side, so people always know when an event was actually appended to the log. We don't plan to change that.
