### ISSUE TITLE
Potential data race in .NET Client API

### ISSUE THREAD

**Issue by eulerfx** [EventStore/EventStore#396]
I was following the workflow that occurs when a TCP connection is closed and the client attempts to reconnect. The short version is that it seems accesses to `_state` and `_connectingPhase` fields in `EventStoreConnectionLogicHandler` require a memory barrier. (https://github.com/EventStore/EventStore/blob/dev/src/EventStore.ClientAPI/Internal/EventStoreConnectionLogicHandler.cs#L35)

To the extend I was able to trace it out, the connection closed to reconnect workflow is as follows:

1. `EventStoreConnectionLogicHandler.TcpConnectionClosed` is called either explicitly from `CloseTcpConnection` or via the message pump `SimpleQueuedHandler`.  It sets the fields to `ConnectionState.Connecting` and `ConnectingPhase.Reconnecting` respectively. 

2. Concurrently, a `TimerTick` is invoked checking to see if a reconnect needs to be performed. It reads the `_state` field without a memory barrier. Most cases this should be OK, but it seems like it has a potentially to read stale data. 

3. If step 2 succeeds, `DiscoverEndPoint` is called which also reads the fields and returns if they aren't in the expected state. If everything is as expected, it begins end point discovery via `_endPointDiscoverer.DiscoverAsync`. This completes via `Task.ContinueWith` which queues message `EstablishTcpConnectionMessage`.

4. The message `EstablishTcpConnectionMessage` gets handled by `EstablishTcpConnection` which also reads the fields `_state` and `_connectingPhase` and if they aren't in the expected state, the connection isn't established. However, the message  `LogDebug("EstablishTcpConnection to [{0}]", endPoint);` still gets logged because that is before the return statement.

Since `SimpleQueuedHandler` processes the queue via `ThreadPool.QueueUserWorkItem(ProcessQueue)`, despite the fact that only one thread may be running at a given time, it can be a different thread, resulting in the potential to read stale data from the fields.

**Comment by jen20** [comment]
Sounds plausible at first read. Will investigate.

**Comment by eulerfx** [comment]
@jen20 we've seen cases where it doesn't reconnect, but if the service is restarted, it will continue to work properly. I think I've also seen a case where the message `LogDebug("EstablishTcpConnection to [{0}]", endPoint);` is printed but it never reconnects.

**Comment by jen20** [comment]
OK a race condition on `_state` as you describe seems intuitive. I'll trace this one through later today and come back to it.

**Comment by eulerfx** [comment]
This (http://stackoverflow.com/questions/25123246/it-is-possible-for-a-thread-from-threadpool-to-see-a-staleprocessor-cached-val) seems to indicate that scheduling via `ThreadPool.QueueUserWorkItem` should be safe.

**Comment by pavelm** [comment]
@jen20 have you had any progress with this?

**Comment by jen20** [comment]
The reported symptom is likely fixed in 39bc2810abed27a6818a18aff0805e3b537165df, I'm going to leave this open for further investigation of a potential race though.

**Comment by eulerfx** [comment]
This may be of note. I took a snapshot of TCPView on an EventStore VM. There are a bunch of connections in the FIN_WAIT state, which looks to be due to re-connection attempts. Shortly after I took the snapshots, the connections went away.

Also, is it normal for there to be multiple connections from the same remote address and port?

![eventstore_tcpview](https://cloud.githubusercontent.com/assets/609910/6360794/e5f2248e-bc4a-11e4-987e-ac6032229499.png)

**Comment by jen20** [comment]
`FIN_WAIT2` is for when the server is waiting for the client to send a `FIN` packet which the server should acknowledge, so it's not necessarily unexpected in the case of a faulty client. I'd be interested to see if you still see this with v3.0.2-prerelease of the ClientAPI which is now on the public NuGet repository?

**Comment by jen20** [comment]
This was fixed in client API 3.0.2
