### ISSUE TITLE
ES fails to parse Accept header with multiple types

### ISSUE THREAD

**Issue by kephas** [EventStore/EventStore#3982]
**Describe the bug**
When the HTTP client sends an `Accept` header with multiple MIME types, the server answers with error 406.

**To Reproduce**

1. `curl -u user:pass -H "Accept: application/json, */*" http://eventstore/streams/foo/0`

**Expected behavior**
The server should answer with the best matching type (here, `application/json`).

**Actual behavior**
The server answer with error 406.

**EventStore details**

* EventStore server version: 21.10.1
* Operating system: Linux
* EventStore client version (if applicable): n/a

**Additional context**
This happened when using `[httpie](https://httpie.io/)`, which by default uses a list of types when doing JSON interactions (`Accept: application/json, */*;q=0.5`). When forcing an `Accept` header with just one type (with or without the `q=` argument), the request succeeds.

<sub>[DB-488](https://linear.app/eventstore/issue/DB-488/es-fails-to-parse-accept-header-with-multiple-types)</sub>

**Comment by ylorph** [comment]
@kephas : please note the the HTTP Atom pub API for reading / appending to streams is deprecated 

Do you see the same behavior on the `/metrics` endpoint on the latest 23.10 ?

**Comment by alexeyzimarev** [comment]
Should've been fixed as part of supporting text/plain for metrics, available in 23.10.

**Comment by timothycoleman** [comment]
Closing this for now since it's fixed in 23.10.0, please feel free to reopen if you have any further problems
