### ISSUE TITLE
"Undefined" entry in the recently created streams list after deleting a stream

### ISSUE THREAD

**Issue by rcknight** [EventStore/EventStore#399]
Steps to reproduce:

Create a stream
Delete it
Trigger a scavenge
Look at streams page in UI

**Comment by gregoryyoung** [comment]
This sounds like just a UI bug? IIRC recently created is just a link event
that points back to the original event (which may not be there)

On Wed, Feb 18, 2015 at 6:28 PM, Rich Knight <notifications@github.com>
wrote:

> Steps to reproduce:
>
> Create a stream
> Delete it
> Trigger a scavenge
> Look at streams page in UI
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/399>.
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
Yes, I suspect this is just the UI not handling the fact that the original event may be null and it's trying to read the name. Certainly "undefined" sounds like a very JavaScripty thing.
