### ISSUE TITLE
Metrics endpoint to accept requests in `text/plain` format

### ISSUE THREAD

**Issue by lessless** [EventStore/EventStore#4009]
**Is your feature request related to a problem? Please describe.**

I can't scrape the metrics because of EventStore doesn't accept the `"text/plain;version=0.0.4;q=1,*/*;q=0.1"` format

```
{
   "@t":"2023-10-23T12:07:00.9783203+00:00",
   "@mt":"HTTP Response\n{dateTime}\n{statusCode} {statusDescription}\n{headers}\n{body}",
   "@l":"Debug",
   "@i":4085809235,
   "dateTime":"2023-10-23T12:07:00.9783148+00:00",
   "statusCode":406,
   "statusDescription":"Requested URI is not available in requested format",
   "headers":{
      "Accept":[
         "text/plain;version=0.0.4;q=1,*/*;q=0.1"
      ],
      "Host":[
         "172.19.5.10:2113"
      ],
      "User-Agent":[
         "vm_promscrape"
      ],
      "Accept-Encoding":[
         "gzip"
      ],
      "X-Prometheus-Scrape-Timeout-Seconds":[
         "10.000"
      ]
   },
   "body":"",
   "SourceContext":"EventStore.Transport.Http.EntityManagement.HttpEntityManager",
   "ProcessId":393,
   "ThreadId":3,
   "RequestId":"0HMUJO0A93A65:0000000F",
   "RequestPath":"/metrics",
   "ConnectionId":"0HMUJO0A93A65"
}
```

**Describe the solution you'd like**
`/metrics` endpoint to accept requests in `text/plain;` format

**Additional context**
I'm using [managed metrics](https://fly.io/docs/reference/metrics/) setup based on [https://victoriametrics.com/](https://victoriametrics.com/)

<sub>[DB-457](https://linear.app/eventstore/issue/DB-457/metrics-endpoint-to-accept-requests-in-textplain-format)</sub>

**Comment by timothycoleman** [comment]
yeah something seems wrong here, we'll take a look

**Comment by timothycoleman** [comment]
yep we are juust squeezing it in - thanks for spotting it and letting us know!

**Comment by timothycoleman** [comment]
i see some automation is opening and closing this on my behalf 😅  its really me closing it this time. let us know if you have any further difficulties

**Comment by lessless** [comment]
@timothycoleman it works https://twitter.com/yevkurtov/status/1720457099451220031 !

**Comment by timothycoleman** [comment]
great! and thanks for the positive feedback :+1:
