### ISSUE TITLE
System projections faulted after "acquire exclusive lock at ..." failed.

### ISSUE THREAD

**Issue by mpielikis** [EventStore/EventStore#402]
I have a testing env with ES (latest dev branch version) running in cluster mode on three nodes (three asus vivopc with windows server 2012). Projections are used there. In the beginning of this month all system projections faulted, only now was noticed. Other projections are working fine.

The logs are telling that the problem likely started with 

```
[PID:03112:001 2015.02.02 11:30:23.315 FATAL ProgramBase`1       ] Unhandled exception while starting application:
Couldn't acquire exclusive lock on DB at 'C:\sis\DB\Events\db'.
System.Exception: Couldn't acquire exclusive lock on DB at 'C:\sis\DB\Events\db'.
   at EventStore.ClusterNode.Program.Create(ClusterNodeOptions opts)
   at EventStore.Core.ProgramBase`1.Run(String[] args) in d:\Dev\GitHub\EventStore\src\EventStore.Core\ProgramBase.cs:line 60
[PID:03112:001 2015.02.02 11:30:23.377 ERROR Application         ] Exiting with exit code: 1.
Exit reason: Couldn't acquire exclusive lock on DB at 'C:\Enersis\DB\Events\db'.
```

then the following exceptions appeared and since then system projections are in faulted state

```
[PID:03672:014 2015.02.02 11:34:11.825 ERROR ProjectionManager   ] The '$streams' projection faulted due to 'An event emitted in recovery differ from the originally emitted event.  Existing('$>', 'C:715526241/P:715520842'). New('$>', 'C:715125426/P:715123387')'
[PID:03672:014 2015.02.02 11:34:11.825 ERROR ProjectionManager   ] The '$stream_by_category' projection faulted due to 'An event emitted in recovery differ from the originally emitted event.  Existing('$@', 'C:715526241/P:715520842'). New('$@', 'C:715125426/P:715123387')'
[PID:03672:014 2015.02.02 11:34:12.044 ERROR ProjectionManager   ] The '$by_category' projection faulted due to 'An event emitted in recovery differ from the originally emitted event.  Existing('$>', 'C:715526241/P:715520842'). New('$>', 'C:715023885/P:715021389')'
[PID:03672:014 2015.02.02 11:34:12.044 ERROR ProjectionManager   ] The '$by_event_type' projection faulted due to 'An event emitted in recovery differ from the originally emitted event.  Existing('$>', 'C:715534711/P:715524994'). New('$>', 'C:715534649/P:715524433')'
```

The db with logs from three nodes is here 

https://drive.google.com/file/d/0Bwyi51hsWc-vTnlYZVZySGdnWGM/view?usp=sharing

Projection errors are reproducable.

```
EventStore.ClusterNode.exe --Db D:\DB\backup\db --run-projections=all --skip-db-verify
```

**Comment by gregoryyoung** [comment]
"
[PID:03112:001 2015.02.02 11:30:23.315 FATAL ProgramBase`1 ] Unhandled
exception while starting application: Couldn't acquire exclusive lock on DB
at 'C:\sis\DB\Events\db'. System.Exception: Couldn't acquire exclusive lock
on DB at 'C:\sis\DB\Events\db'. at
EventStore.ClusterNode.Program.Create(ClusterNodeOptions
opts) at EventStore.Core.ProgramBase`1.Run(String[] args) in
d:\Dev\GitHub\EventStore\src\EventStore.Core\ProgramBase.cs:line 60
[PID:03112:001 2015.02.02 11:30:23.377 ERROR Application ] Exiting with
exit code: 1. Exit reason: Couldn't acquire exclusive lock on DB at
'C:\Enersis\DB\Events\db'."

This isn'twhat started issues. This is what happens when you try to open
event store twice on the same db :)

The faulted projections likely happened during a takeover. We have seen
this before and are looking into it.

Greg

On Wed, Feb 25, 2015 at 3:27 PM, Mindaugas Pielikis <
notifications@github.com> wrote:

> I have a testing env with ES (latest dev branch version) running in
> cluster mode on three nodes (three asus vivopc with windows server 2012).
> Projections are used there. In the beginning of this month all system
> projections faulted, only now was noticed. Other projections are working
> fine.
>
> The logs are telling that the problem likely started with
>
> [PID:03112:001 2015.02.02 11:30:23.315 FATAL ProgramBase`1       ] Unhandled exception while starting application:
> Couldn't acquire exclusive lock on DB at 'C:\sis\DB\Events\db'.
> System.Exception: Couldn't acquire exclusive lock on DB at 'C:\sis\DB\Events\db'.
>    at EventStore.ClusterNode.Program.Create(ClusterNodeOptions opts)
>    at EventStore.Core.ProgramBase`1.Run(String[] args) in d:\Dev\GitHub\EventStore\src\EventStore.Core\ProgramBase.cs:line 60
> [PID:03112:001 2015.02.02 11:30:23.377 ERROR Application         ] Exiting with exit code: 1.
> Exit reason: Couldn't acquire exclusive lock on DB at 'C:\Enersis\DB\Events\db'.
>
> then the following exceptions appeared and since then system projections
> are in faulted state
>
> [PID:03672:014 2015.02.02 11:34:11.825 ERROR ProjectionManager   ] The '$streams' projection faulted due to 'An event emitted in recovery differ from the originally emitted event.  Existing('$>', 'C:715526241/P:715520842'). New('$>', 'C:715125426/P:715123387')'
> [PID:03672:014 2015.02.02 11:34:11.825 ERROR ProjectionManager   ] The '$stream_by_category' projection faulted due to 'An event emitted in recovery differ from the originally emitted event.  Existing('$@', 'C:715526241/P:715520842'). New('$@', 'C:715125426/P:715123387')'
> [PID:03672:014 2015.02.02 11:34:12.044 ERROR ProjectionManager   ] The '$by_category' projection faulted due to 'An event emitted in recovery differ from the originally emitted event.  Existing('$>', 'C:715526241/P:715520842'). New('$>', 'C:715023885/P:715021389')'
> [PID:03672:014 2015.02.02 11:34:12.044 ERROR ProjectionManager   ] The '$by_event_type' projection faulted due to 'An event emitted in recovery differ from the originally emitted event.  Existing('$>', 'C:715534711/P:715524994'). New('$>', 'C:715534649/P:715524433')'
>
> The db with logs from three nodes is here
>
>
> https://drive.google.com/file/d/0Bwyi51hsWc-vTnlYZVZySGdnWGM/view?usp=sharing
>
> Projection errors are reproducable.
>
> EventStore.ClusterNode.exe --Db D:\DB\backup\db --run-projections=all --skip-db-verify
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/402>.
>



-- 
Studying for the Turing test

**Comment by mpielikis** [comment]
yeah that could be the reason :)
should I leave the link to db and logs?

**Comment by mpielikis** [comment]
:) this could be the reason.
should I leave the link to db?

**Comment by gregoryyoung** [comment]
That would be great or I can pop by your office and take a look next week

On Wed, Feb 25, 2015 at 3:40 PM, Mindaugas Pielikis <
notifications@github.com> wrote:

> :) this could be the reason.
> should I leave the link to db?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/402#issuecomment-75960661>
> .
>



-- 
Studying for the Turing test

**Comment by mpielikis** [comment]
The link should work.
https://drive.google.com/file/d/0Bwyi51hsWc-vTnlYZVZySGdnWGM/view?usp=sharing

Still we would be very pleased if you would visit us :)

**Comment by pgermishuys** [comment]
Is this still relevant @mpielikis ?

**Comment by pgermishuys** [comment]
Going to close this issue as it appears it's no longer relevant.
