### ISSUE TITLE
The service does not start

### ISSUE THREAD

**Issue by ZedZipDev** [EventStore/EventStore#4020]
Ubuntu 20.04
EventStoreDB - 23.10 installed
I did not touch the config 

I start it
$ sudo systemctl start eventstore
$sudo service eventstore status
sudo service eventstore status
● eventstore.service - EventStoreDB Server
     Loaded: loaded (/lib/systemd/system/eventstore.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-10-27 15:28:54 CEST; 14s ago
    Process: 182228 ExecStart=/bin/bash -c echo $$$ > /run/eventstore/eventstore.pid; exec /usr/bin/eventstored (code=exited, stat>
   Main PID: 182228 (code=exited, status=1/FAILURE)

Okt 27 15:28:54 d-oleg-u20 systemd[1]: eventstore.service: Scheduled restart job, restart counter is at 5.
Okt 27 15:28:54 d-oleg-u20 systemd[1]: Stopped EventStoreDB Server.
Okt 27 15:28:54 d-oleg-u20 systemd[1]: eventstore.service: Start request repeated too quickly.
Okt 27 15:28:54 d-oleg-u20 systemd[1]: eventstore.service: Failed with result 'exit-code'.
Okt 27 15:28:54 d-oleg-u20 systemd[1]: Failed to start EventStoreDB Server.

**Comment by ylorph** [comment]
How did you install ?
(the 23.10 package is not yet available on package cloud )
can you share the logs & config file ?
