### ISSUE TITLE
NET 6 Web Application: Connection was closed.

### ISSUE THREAD

**Issue by ZedZipDev** [EventStore/EventStore#4021]
I am trying to run local ES and my app

1. Windows 10: 
EventStore-OSS-Windows-2019-v23.6.0

I run it
>EventStore.ClusterNode.exe --dev
It is running, dashboard works fine

2. The app code:
        public void ConfigureServices(IServiceCollection services)
        {

            var user = "admin";
            var password = "changeit";
            var host = "localhost";

            services.AddControllers();
            services.AddSwaggerGen();
            services.AddSingleton(sp =>
            {
                var connectionString = $"ConnectTo=tcp://{user}:{password}@{host}:1113;";
                var settingsBuilder = ConnectionSettings
                    .Create()
                    .DisableTls()
                    .KeepReconnecting()
                    .LimitReconnectionsTo(10);

                var con = EventStoreConnection.Create(connectionString, settingsBuilder);
                con.ConnectAsync().Wait();
                return con;
            });

            services.AddTransient<IEventsRepository, EventsRepository>();
            services.AddTransient<ITodoRepository, TodoRepository>();
        }

3. I run the app and in a few seconds receive in browser:
   1) Connection 'ES-294f0d7e-5da4-4949-a825-57fce3408de6' was closed.

How to fix it?

**Comment by ylorph** [comment]
Are you using the .Net TCP based client ? (https://www.nuget.org/packages/EventStore.Client)
IIRC ; the TCP protocol for client libraries is disabled by default .
You should really use the nexer gRPC based client : https://www.nuget.org/packages?q=EventStore.Client.Grpc

**Comment by ZedZipDev** [comment]
Yes, I use TCP client,
By the way: 
if I'll use gRPC client what connection string should be instead of 
var connectionString = $"ConnectTo=tcp://{user}:{password}@{host}:1113;";
?

**Comment by ylorph** [comment]
assuming a cluster: 
`esdb+discover:///{user}:{password}@{host}:2113` if using DNS discovery 
`esdb:///{user}:{password}@{node1}:2113,{node2}:2113,{node3}:2113` if using gossip seed 

note that the gRPC client is in another Nuget package : https://www.nuget.org/packages?q=EventStore.Client.Grpc

**Comment by alexeyzimarev** [comment]
@ZedZipDev the old client will no longer be supported. Please avoid using it.

**Comment by ZedZipDev** [comment]
@alexeyzimarev I see: need to use gRPC Client.
IMHO : may be need to add this note to FAQ: 
in case of error
Connection 'ES-294f0d7e-5da4-4949-a825-57fce3408de6' was closed.
need to do (1,2,... 107) ;-)

**Comment by ZedZipDev** [comment]
By the way: where can I find NET6 client app examples to test how to work with ESDB?

**Comment by alexeyzimarev** [comment]
Sure, https://github.com/EventStore/training-introduction-dotnet

With regards to the legacy client, we kind of highlight that you shouldn't use it on the first page in the docs https://developers.eventstore.com/clients/dotnet/21.2/

It should still work though, but we aren't planning making fixes for the legacy client at the moment
<img width="897" alt="image" src="https://github.com/EventStore/EventStore/assets/2821205/f5fee833-3e59-48fa-8b58-606fed5ba3ae">
