### ISSUE TITLE
Docs: Atomic batch writes with AppendToStream()?

### ISSUE THREAD

**Issue by wiegell** [EventStore/EventStore#4061]
The documentation explains how to do a batch write with AppendToStream():
https://developers.eventstore.com/clients/grpc/appending-events.html#append-your-first-event

Is that an atomic write, or can it fail after writing one of many events?
If it is, maybe the documentation could be improved to reflect that?

I'm using the go-client.

Thanks in advance

**Comment by alexeyzimarev** [comment]
It's transactional, all or nothing. Please use our community forums for asking questions, thank you.
