### ISSUE TITLE
SubscriptionCheckpoint event type not filtered.

### ISSUE THREAD

**Issue by ylorph** [EventStore/EventStore#4079]
**Describe the bug**

Presistent subscription checkpoint event type `SubscriptionCheckpoint ` are not taken into account when using `EventTypeFilter.ExcludeSystemEvents()` because the type is not prefixed with `$`

**To Reproduce**
N/A

**Expected behavior**
when using `EventTypeFilter.ExcludeSystemEvents()` those event type should be filtered out

**Actual behavior**

`SubscriptionCheckpoint ` are pushed to consumers when excluding system events.

**Config/Logs/Screenshots**
N/A

**EventStore details**

* EventStore server version: All
* Operating system: N/A
* EventStore client version (if applicable): Any client

**Additional context**

Could be done as additional behavior on the filter system as well as adding the correct prfix to the event type  in the databse

[https://discuss.eventstore.com/t/subscription-returning-system-events/5037/2](https://discuss.eventstore.com/t/subscription-returning-system-events/5037/2)

[latest version of code appending the event at the moment of report](https://github.com/EventStore/EventStore/blob/a3125bc11cebecd342f6421829201a9eeb8c90d6/src/EventStore.Core/Services/PersistentSubscription/PersistentSubscriptionCheckpointWriter.cs#L45C3-L45C106)

<sub>[DB-543](https://linear.app/eventstore/issue/DB-543/subscriptioncheckpoint-event-type-not-filtered)</sub>

**Comment by ylorph** [comment]
Good point, would  a filter based  on both the event type & the stream name work ?

**Comment by alexeyzimarev** [comment]
Fixed
