### ISSUE TITLE
Heartbeats

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#408]
Heartbeats are currently checking messageid instead its smarter to check a packet count as large messages will no longer conflict with heartbeats.

**Comment by amri** [comment]
Hi Greg, 

Could you explain more about Heartbeat Interval & Timeout ? especially how it works from server side. 

I saw in the documentation, the default values for them are 1000 and 700. Those are in seconds ? or miliseconds ?

Thanks

**Comment by gregoryyoung** [comment]
Those are milliseconds.

What happens is if a message has not been received over the connection in [interval] then a heartbeat message is sent. If it is not received within [timeout] then the connection is closed. 

The client API also has its own settings for these (it does its own heartbeats as well if desired as you may wish to do something like 10000/10000 on server then vary clients at say 500/500 on one and 1000/1000 on another).
