### ISSUE TITLE
Stream Subscriptions to switch between live and catchup

### ISSUE THREAD

**Issue by timothycoleman** [EventStore/EventStore#4089]
Currently gRPC subscriptions catch up and transition to live, but if their buffer of live events fills up (which can happen very easily if there is a burst of writes) then the subscription is dropped. Instead of dropping the subscription, we want to transition the subscription back to catchup when this happens. The buffer should also *probably* be bigger.

A sensible approach may be for the live events channel that the SubscriptionsService writes events into, to drop old events when the channel is full. Then the Subscription service can continue to put in new events, and the channel will always contain a contiguous window of live events. On reading from the channel, we could detect gaps and issue reads. Gaps can be detected by giving each event in the live channel a sequence number when we write it, and we can compare that sequence number to the one we last read out of the channel. Ideally the mechanism can work in a way that also works for $all and filtered $all subscriptions.

Note we do already have a control message now to indicate to the gRPC client that the subscription has transitioned back to catchup, but there is uncertainty around this API being a reasonable long term solution so do not send the FellBehind message for now.

<sub>[DB-393](https://linear.app/eventstore/issue/DB-393/stream-subscriptions-to-switch-between-live-and-catchup)</sub>

**Comment by ylorph** [comment]
Will this require client changes @timothycoleman  ?

**Comment by timothycoleman** [comment]
@yves.lorphelin no this should be invisible to the clients (except that subscriptions won't be dropped due to the buffer filling up)

however clients will be able to process the caughtup/fell behind control messages if and when they want to
