### ISSUE TITLE
TCP-proxying EventStore yields 400 Bad Request on HTTP API

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#415]
Sample:

```
$ curl --header "Content-Type: application/json" --header "Host: 127.0.0.1" -i http://172.17.8.100:2112
HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=us-ascii
Server: Mono-HTTPAPI/1.0
Date: Sun, 08 Mar 2015 23:02:28 GMT
Content-Length: 35
Connection: close

<h1>Bad Request (Invalid host)</h1>
$ curl --header "Content-Type: application/json" --header "Host: 10.1.0.25" -i http://172.17.8.100:2112
HTTP/1.1 302 Found
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTo, ES-ExpectedVersion
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position
Location: http://10.1.0.25:2112/web/index.html
Content-Type: text/plain; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Sun, 08 Mar 2015 23:04:00 GMT
Content-Length: 5
Keep-Alive: timeout=15,max=100
```

![screen shot 2015-03-09 at 00 27 56](https://cloud.githubusercontent.com/assets/193115/6548268/23a36e76-c5f3-11e4-9791-8be0455015fc.png)

**Comment by gregoryyoung** [comment]
See #414 (also from tonight)

most likely thats what you are missing

On Mon, Mar 9, 2015 at 1:28 AM, Henrik Feldt <notifications@github.com>
wrote:

> Sample:
>
> $ curl --header "Content-Type: application/json" --header "Host: 127.0.0.1" -i http://172.17.8.100:2112
> HTTP/1.1 400 Bad Request
> Content-Type: text/html; charset=us-ascii
> Server: Mono-HTTPAPI/1.0
> Date: Sun, 08 Mar 2015 23:02:28 GMT
> Content-Length: 35
> Connection: close
>
> <h1>Bad Request (Invalid host)</h1>
> $ curl --header "Content-Type: application/json" --header "Host: 10.1.0.25" -i http://172.17.8.100:2112
> HTTP/1.1 302 Found
> Access-Control-Allow-Methods: GET, OPTIONS
> Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTo, ES-ExpectedVersion
> Access-Control-Allow-Origin: *
> Access-Control-Expose-Headers: Location, ES-Position
> Location: http://10.1.0.25:2112/web/index.html
> Content-Type: text/plain; charset=utf-8
> Server: Mono-HTTPAPI/1.0
> Date: Sun, 08 Mar 2015 23:04:00 GMT
> Content-Length: 5
> Keep-Alive: timeout=15,max=100
>
> [image: screen shot 2015-03-09 at 00 27 56]
> <https://cloud.githubusercontent.com/assets/193115/6548268/23a36e76-c5f3-11e4-9791-8be0455015fc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/415>.
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
I can't bind to that, because the interface is proxied. I need ES to bind to the interface it has access to. Docker then forwards from the 172 if to the docker0-interface...

**Comment by haf** [comment]
This is what it looks like from inside the container:

![screen shot 2015-03-09 at 00 39 36](https://cloud.githubusercontent.com/assets/193115/6548327/c9c459e0-c5f4-11e4-9e37-149b1d661d39.png)

**Comment by gregoryyoung** [comment]
http-prefix is not what you bind to

You bind locally and set http prefixes for what you should accept

On Mon, Mar 9, 2015 at 1:36 AM, Henrik Feldt <notifications@github.com>
wrote:

> I can't bind to that, because the interface is proxied. I need ES to bind
> to the interface it has access to. Docker then forwards from the 172 if to
> the docker0-interface...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/415#issuecomment-77782196>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
Ah, ok, let me try that then! :)

**Comment by haf** [comment]
This ` --http-prefixes=http://172.17.8.100:2113` =>

```

System.ArgumentException: No path specified.
  at System.Net.ListenerPrefix.CheckUri (System.String uri) [0x00000] in <filename unknown>:0
  at System.Net.HttpListenerPrefixCollection.Add (System.String uriPrefix) [0x00000] in <filename unknown>:0
  at EventStore.Transport.Http.Server.HttpAsyncServer.CreateListener (IEnumerable`1 prefixes) [0x00000] in <filename unknown>:0
  at EventStore.Transport.Http.Server.HttpAsyncServer..ctor (System.String[] prefixes) [0x00000] in <filename unknown>:0
  at EventStore.Core.Services.Transport.Http.HttpService..ctor (ServiceAccessibility accessibility, IPublisher inputBus, IUriRouter uriRouter, EventStore.Core.Bus.MultiQueuedHandler multiQueuedHandler, System.String[] prefixes) [0x00000] in <filename unknown>:0
  at EventStore.Core.ClusterVNode..ctor (EventStore.Core.TransactionLog.Chunks.TFChunkDb db, EventStore.Core.Cluster.Settings.ClusterVNodeSettings vNodeSettings, IGossipSeedSource gossipSeedSource, EventStore.Core.Services.Transport.Http.Controllers.InfoController infoController, EventStore.Core.ISubsystem[] subsystems) [0x00000] in <filename unknown>:0
  at EventStore.ClusterNode.Program.Create (EventStore.ClusterNode.ClusterNodeOptions opts) [0x00000] in <filename unknown>:0
  at EventStore.Core.ProgramBase`1[EventStore.ClusterNode.ClusterNodeOptions].Run (System.String[] args) [0x00000] in <filename unknown>:0
```

**Comment by gregoryyoung** [comment]
A URI prefix string is composed of a scheme (http or https), a host, an
optional port, and an optional path. An example of a complete prefix string
is "http://www.contoso.com:8080/customerData/". Prefixes must end in a
forward slash ("/"). The HttpListener object with the prefix that most
closely matches a requested URI responds to the request. Multiple
HttpListener objects cannot add the same prefix; a Win32Exception
<https://msdn.microsoft.com/en-us/library/system.componentmodel.win32exception(v=vs.110).aspx>exception
is thrown if a HttpListener adds a prefix that is already in use.


On Mon, Mar 9, 2015 at 1:45 AM, Henrik Feldt <notifications@github.com>
wrote:

> This --http-prefixes=http://172.17.8.100:2113 =>
>
>
> System.ArgumentException: No path specified.
>   at System.Net.ListenerPrefix.CheckUri (System.String uri) [0x00000] in <filename unknown>:0
>   at System.Net.HttpListenerPrefixCollection.Add (System.String uriPrefix) [0x00000] in <filename unknown>:0
>   at EventStore.Transport.Http.Server.HttpAsyncServer.CreateListener (IEnumerable`1 prefixes) [0x00000] in <filename unknown>:0
>   at EventStore.Transport.Http.Server.HttpAsyncServer..ctor (System.String[] prefixes) [0x00000] in <filename unknown>:0
>   at EventStore.Core.Services.Transport.Http.HttpService..ctor (ServiceAccessibility accessibility, IPublisher inputBus, IUriRouter uriRouter, EventStore.Core.Bus.MultiQueuedHandler multiQueuedHandler, System.String[] prefixes) [0x00000] in <filename unknown>:0
>   at EventStore.Core.ClusterVNode..ctor (EventStore.Core.TransactionLog.Chunks.TFChunkDb db, EventStore.Core.Cluster.Settings.ClusterVNodeSettings vNodeSettings, IGossipSeedSource gossipSeedSource, EventStore.Core.Services.Transport.Http.Controllers.InfoController infoController, EventStore.Core.ISubsystem[] subsystems) [0x00000] in <filename unknown>:0
>   at EventStore.ClusterNode.Program.Create (EventStore.ClusterNode.ClusterNodeOptions opts) [0x00000] in <filename unknown>:0
>   at EventStore.Core.ProgramBase`1[EventStore.ClusterNode.ClusterNodeOptions].Run (System.String[] args) [0x00000] in <filename unknown>:0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/415#issuecomment-77782612>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
Alright, then I get:

```
2015-03-08 23:50:18.3626|FATAL|HttpAsyncServer|Failed to start http server
Exiting with exit code: 1.
Exit reason: Http async server failed to start listening at [http://172.17.8.100:2113/].
2015-03-08 23:50:18.3635|ERROR|Application|Exiting with exit code: 1.
Exit reason: Http async server failed to start listening at [http://172.17.8.100:2113/].
```

So same as the other issue, yes?

**Comment by gregoryyoung** [comment]
What is your command line?

On Mon, Mar 9, 2015 at 1:47 AM, Henrik Feldt <notifications@github.com>
wrote:

> Alright, then I get:
>
> 2015-03-08 23:50:18.3626|FATAL|HttpAsyncServer|Failed to start http server
> Exiting with exit code: 1.
> Exit reason: Http async server failed to start listening at [http://172.17.8.100:2113/].
> 2015-03-08 23:50:18.3635|ERROR|Application|Exiting with exit code: 1.
> Exit reason: Http async server failed to start listening at [http://172.17.8.100:2113/].
>
> So same as the other issue, yes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/415#issuecomment-77782725>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
```
docker run -p 172.17.8.100:1112:1112 -p 172.17.8.100:1113:1113 -p 172.17.8.100:2112:2112 -p 172.17.8.100:2113:2113 --volumes-from eventstore-data -it haaf/eventstore --cluster-dns eventstore.prod.deis.local --cluster-gossip-port 2112 --http-prefixes=http://172.17.8.100:2113/
```

Where everything after `haaf/eventstore` is appended to https://github.com/haf/dockerfiles/blob/master/eventstore/start#L34

**Comment by gregoryyoung** [comment]
This is in another issue
