### ISSUE TITLE
Menu item duplicate on site

### ISSUE THREAD

**Issue by visortelle** [EventStore/EventStore#4196]
<img width="398" alt="Screenshot 2024-03-08 at 10 39 17 AM" src="https://github.com/EventStore/EventStore/assets/9302460/210ae487-6dfd-41dd-bff4-d8bdb160a3ba">

- EventStoreDB
- EventStoreDB

Both have a link to the same page.

I didn't find the site repo.

**Comment by ylorph** [comment]
Oh thanks @visortelle , it's a CMS 
@danjamescrosby  i think it's for you

**Comment by danjamescrosby** [comment]
Thanks @visortelle - this is now fixed

**Comment by visortelle** [comment]
@danjamescrosby thank you! I'm very happy 😊
