### ISSUE TITLE
Gossip hostname and allow hostname to be set

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#420]
There are some cases where redirection may be wanted via a hostname 

An example of this might be:

Node a 192.168.1.11

Node b sees a as 10.114.10.112
Node c sees a as 192.168.15.45

By including hostname in gossip this can be redirected on other nodes. Other examples of this may be certain cloud setups.

**Comment by jen20** [comment]
Do we still need this given that we have advertise now?

**Comment by gregoryyoung** [comment]
Nope.

On Mon, Sep 7, 2015 at 6:09 PM, James Nugent <notifications@github.com>
wrote:

> Do we still need this given that we have advertise now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/420#issuecomment-138333121>
> .
>



-- 
Studying for the Turing test

**Comment by lucaswxp** [comment]
Hey guys. I came from the issue #416 and not sure how to solve the "Bad Request (Invalid host)"

I running eventstore 4.0.3 in a single machine. When accessing from 127.0.0.1 it works, but not from the public ip address.

**Comment by hayley-jean** [comment]
Hi @lucaswxp 

Could you provide us with the configuration you are using for this node?

It sounds like the http prefixes need to be configured, by default they only allow traffic on localhost.
To allow traffic from all sources, you can run Event Store with something like the following configuration:

```
ExtHttpPrefixes: http://*:2113/
IntHttpPrefixes: http://*:2112/
```

**Comment by lucaswxp** [comment]
@hayley-jean Thank you! I took a look at the docker image config and got the exact same answer. Thank you anyway!
