### ISSUE TITLE
Error while collecting stats

### ISSUE THREAD

**Issue by eulerfx** [EventStore/EventStore#421]
After upgrading server to v3.0.2 started seeing the following in error logs:

> [PID:02752:044 2015.03.12 14:12:07.454 ERROR MonitoringService   ] Error while collecting stats
System.InvalidOperationException: The Counter layout for the Category specified is invalid, a counter of the type:  AverageCount64, AverageTimer32, CounterMultiTimer, CounterMultiTimerInverse, CounterMultiTimer100Ns, CounterMultiTimer100NsInverse, RawFraction, or SampleFraction has to be immediately followed by any of the base counter types: AverageBase, CounterMultiBase, RawBase or SampleBase.
   at System.Diagnostics.CategorySample.GetCounterDefinitionSample(String counter)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at EventStore.Core.Services.Monitoring.Utils.PerfCounterHelper.GetGcStats() in c:\work\EventStore\src\EventStore.Core\Services\Monitoring\Utils\PerfCounterHelper.cs:line 119
   at EventStore.Core.Services.Monitoring.SystemStatsHelper.GetSystemStats() in c:\work\EventStore\src\EventStore.Core\Services\Monitoring\SystemStatsHelper.cs:line 66
   at EventStore.Core.Services.Monitoring.MonitoringService.CollectStats() in c:\work\EventStore\src\EventStore.Core\Services\Monitoring\MonitoringService.cs:line 127

**Comment by gregoryyoung** [comment]
try

lodctr /R

On Thu, Mar 12, 2015 at 4:15 PM, Lev Gorodinski <notifications@github.com>
wrote:

> After upgrading server to v3.0.2 started seeing the following in error
> logs:
>
> [PID:02752:044 2015.03.12 14:12:07.454 ERROR MonitoringService ] Error
> while collecting stats
> System.InvalidOperationException: The Counter layout for the Category
> specified is invalid, a counter of the type: AverageCount64,
> AverageTimer32, CounterMultiTimer, CounterMultiTimerInverse,
> CounterMultiTimer100Ns, CounterMultiTimer100NsInverse, RawFraction, or
> SampleFraction has to be immediately followed by any of the base counter
> types: AverageBase, CounterMultiBase, RawBase or SampleBase.
> at System.Diagnostics.CategorySample.GetCounterDefinitionSample(String
> counter)
> at System.Diagnostics.PerformanceCounter.NextSample()
> at
> EventStore.Core.Services.Monitoring.Utils.PerfCounterHelper.GetGcStats() in
> c:\work\EventStore\src\EventStore.Core\Services\Monitoring\Utils\PerfCounterHelper.cs:line
> 119
> at EventStore.Core.Services.Monitoring.SystemStatsHelper.GetSystemStats()
> in
> c:\work\EventStore\src\EventStore.Core\Services\Monitoring\SystemStatsHelper.cs:line
> 66
> at EventStore.Core.Services.Monitoring.MonitoringService.CollectStats() in
> c:\work\EventStore\src\EventStore.Core\Services\Monitoring\MonitoringService.cs:line
> 127
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/421>.
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
This is a well known problem with Windows. `lotctr /R` at a command line should resolve it.

**Comment by suddenelfilio** [comment]
We had this as well. My question is if this is a onetime deal or do we need to run this command regularly to ensure the stats don't fault again?

**Comment by gregoryyoung** [comment]
We have seen both.

On Wed, May 11, 2016 at 10:17 AM, suddenelfilio <notifications@github.com>
wrote:

> We had this as well. My question is if this is a onetime deal or do we
> need to run this command regularly to ensure the stats don't fault again?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/421#issuecomment-218392522>
>



-- 
Studying for the Turing test
