### ISSUE TITLE
Description Document

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#424]
Support a description document at /streams/foo

move atom generally to /streams/foo/atom

If request comes for atom to root and accepts atom use atom else give description documents.

This allows us to support multiple http protocols.

**Comment by gregoryyoung** [comment]
OK I have been thinking a lot about this issue as I am strongly of the belief we will want to support additional protocols in the future (SSE or EventSource as examples for live subscriptions). We also have competing. All of these things are being added in a hodge podge way due to us (me?) originally deciding that the /streams/{stream} uri should point to an atom feed.

In an ideal world as mentioned above /streams/{stream} would point to a description document that may look something like:

<feed>
    <link rel="atomfeed" type="application/atom+xml" href="http://mydomain.com/streams/foo/atom">
    <link rel="atomjsonfeed" type="application/atom+json" href="http://mydomain.com/streams/foo/atom">
    <link rel="ssesub" type="text/event-stream" href="http://mydomain.com/streams/foo/sse">
</feed>

A client would then choose how they wished to interact.

Obviously the issue with this is that the above change would be a very large breaking change and would break basically anyone using the HTTP api (including ourselves). I think however there is a reasonable path to implement the change.

/streams/foo no accept/unknown accept -> description document
/streams/foo Accept: vnd.eventstore.stream_description -> description document
/streams/foo Accept: application/atom+xml 301 location /streams/foo/atom
/streams/foo Accept: application/vnd.eventstore.atom+json 301 location /streams/foo/atom
/streams/foo Accept: text/event-stream 301 location /streams/foo/sse

**Impact of changes**

For people that have followed the rules (e.g. following rel links instead of building their own) their code would continue to work so long as they understood a redirect which I consider to be a reasonable assumption. They could add support for the description document at their leisure.

For people who have not followed the rules and self-build uris this would be a breaking change. I think this is actually reasonable as from the beginning the docs have been littered with warnings of "don't bookmark these uris as they may change in the future, use the rel links).

**Work Involved**
I can do most of the work around this relatively quickly. The more of a PITA part about it is that we don't necessarily follow the rules in many of our unit tests around http (for obvious reasons). As such there will likely be a few hundred broken tests as part of this change. Documentation would also need to be updated somewhat (mostly the reading streams page and http getting started doc).

At the end however we would be left with a much nicer interface overall.

**Comment by jen20** [comment]
I'd say if we were going to do this now would be a good time as competing HTTP goes in. Since we have other breaking changes on dev (e.g. non back compatible database files) we should probably consider the next stable version as a 4.0 so breaking this should be fine and as you say well-behaving clients shouldn't be that broken anyway.

The only client implemented using HTTP I know of at the moment is here: https://github.com/JustGiving/JustGiving.EventStore.Http but there might be others too.

Do we also want to roll this work up with the switch away from HttpListener?

**Comment by gregoryyoung** [comment]
@jen20 I would consider this separate from HttpListener but likely both changes will end up in 4.0

**Comment by mpraglowski** [comment]
@jen20 we also use HTTP in https://github.com/arkency/http_eventstore

**Comment by gregoryyoung** [comment]
@Miroslaw do you set an accept header?

On Mon, Jul 6, 2015 at 6:00 PM, Mirosław Pragłowski <
notifications@github.com> wrote:

> @jen20 <https://github.com/jen20> we also use HTTP in
> https://github.com/arkency/http_eventstore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/424#issuecomment-118882146>
> .
>



-- 
Studying for the Turing test

**Comment by mpraglowski** [comment]
@gregoryyoung need to check but if no then we will do it ;)

**Comment by gregoryyoung** [comment]
I think its reasonable to expect clients to pass an accept header

On Mon, Jul 6, 2015 at 6:06 PM, Mirosław Pragłowski <
notifications@github.com> wrote:

> @gregoryyoung <https://github.com/gregoryyoung> need to check but if no
> then we will do it ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/424#issuecomment-118884244>
> .
>



-- 
Studying for the Turing test

**Comment by mpraglowski** [comment]
Sure ;) No problem with that.

**Comment by pgermishuys** [comment]
Fixed by https://github.com/EventStore/EventStore/pull/737
