### ISSUE TITLE
Stream metadata empty in projections

### ISSUE THREAD

**Issue by srogovtsev** [EventStore/EventStore#427]
I'm trying to partition events in projection according to some stream metadata. The problem is, while I can easily see stream metadata in Web UI, `e.streamMetadata` in projection is always an empty object (and `e.streamMetadataRaw` - an `undefined`). Why is that?

**Comment by mat-mcloughlin** [comment]
@jageall, looking through some old tickets. Do you know the difference between `streamMetadata` and `streamMetadataRaw`

**Comment by ylorph** [comment]
Closing , we're unlikely to support stream metadata in the embedded projection engine .
