### ISSUE TITLE
Documentation on ExpectedVersion.EmptyStream does not match behaviour

### ISSUE THREAD

**Issue by srogovtsev** [EventStore/EventStore#428]
Documentation says:
> this specifies the expectation that the target stream has been explicitly created, but does not yet have any user events written in it.

In my case it checks whether stream is empty, but does not check explicit creation (i.e., works with non-existent streams):

	//this one is used for checking whether different events exist on stream,
	//but in this case there's no stream
	var slice = await c.ReadStreamEventsForwardAsync(streamId, StreamPosition.Start, 100, false).ConfigureAwait(false);
	//yes, there's no stream
	Debug.Assert(slice.Status == SliceReadStatus.StreamNotFound);

	var events = slice.Events.Select(e => e.Event)
		.GroupBy(e => e.EventType)
		.ToDictionary(gg => gg.Key, gg => gg.ToArray());

	//if we stop here in debugger, there's still no stream visible in WebGUI
	await c.AppendToStreamAsync(streamId, ExpectedVersion.EmptyStream, new EventData(session.Id, "httpSessionStart", false, null, GetMetadata())).ConfigureAwait(false);
	//previous statement should fail - there was no stream - but it worked

	//and next statement fails because stream is not empty
	await c.AppendToStreamAsync(streamId, ExpectedVersion.EmptyStream, new EventData(Guid.NewGuid(), "httpSessionSetDirection", true, GetBytes(new {direction = session.Direction.GetValueOrDefault().ToString("G")}), GetMetadata()).ConfigureAwait(false);

Why is that? Is suppose that because
> As of Event Store 2.0.0, there is no explicit stream creation operation, as there is no longer a $StreamCreated as the first event in every stream. 

that behaviour was changed, but the documentation was not updated.

**Comment by gregoryyoung** [comment]
Is is this a brand new stream or a previously deleted stream?

On Sunday, March 22, 2015, Serg Rogovtsev <notifications@github.com> wrote:

> Documentation says:
>
> this specifies the expectation that the target stream has been explicitly
> created, but does not yet have any user events written in it.
>
> In my case it checks whether stream is empty, but does not check explicit
> creation (i.e., works with non-existent streams):
>
> //this one is used for checking whether different events exist on stream,
> //but in this case there's no stream
> var slice = await c.ReadStreamEventsForwardAsync(streamId, StreamPosition.Start, 100, false).ConfigureAwait(false);
> //yes, there's no stream
> Debug.Assert(slice.Status == SliceReadStatus.StreamNotFound);
>
> var events = slice.Events.Select(e => e.Event)
>     .GroupBy(e => e.EventType)
>     .ToDictionary(gg => gg.Key, gg => gg.ToArray());
>
> //if we stop here in debugger, there's still no stream visible in WebGUI
> await c.AppendToStreamAsync(streamId, ExpectedVersion.EmptyStream, new EventData(session.Id, "httpSessionStart", false, null, GetMetadata())).ConfigureAwait(false);
> //previous statement should fail - there was no stream - but it worked
>
> //and next statement fails because stream is not empty
> await c.AppendToStreamAsync(streamId, ExpectedVersion.EmptyStream, new EventData(Guid.NewGuid(), "httpSessionSetDirection", true, GetBytes(new {direction = session.Direction.GetValueOrDefault().ToString("G")}), GetMetadata()).ConfigureAwait(false);
>
> Why is that? Did the behaviour change leaving documentation behind?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/428>.
>


-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
Brand new, on clean database.

**Comment by gregoryyoung** [comment]
I have reproduced the issue and found problem. There will be a PR later
today on this.

Cheers,

Greg

On Sun, Mar 22, 2015 at 10:45 AM, Greg Young <gregoryyoung1@gmail.com>
wrote:

> Is is this a brand new stream or a previously deleted stream?
>
>
> On Sunday, March 22, 2015, Serg Rogovtsev <notifications@github.com>
> wrote:
>
>> Documentation says:
>>
>> this specifies the expectation that the target stream has been explicitly
>> created, but does not yet have any user events written in it.
>>
>> In my case it checks whether stream is empty, but does not check explicit
>> creation (i.e., works with non-existent streams):
>>
>> //this one is used for checking whether different events exist on stream,
>> //but in this case there's no stream
>> var slice = await c.ReadStreamEventsForwardAsync(streamId, StreamPosition.Start, 100, false).ConfigureAwait(false);
>> //yes, there's no stream
>> Debug.Assert(slice.Status == SliceReadStatus.StreamNotFound);
>>
>> var events = slice.Events.Select(e => e.Event)
>>     .GroupBy(e => e.EventType)
>>     .ToDictionary(gg => gg.Key, gg => gg.ToArray());
>>
>> //if we stop here in debugger, there's still no stream visible in WebGUI
>> await c.AppendToStreamAsync(streamId, ExpectedVersion.EmptyStream, new EventData(session.Id, "httpSessionStart", false, null, GetMetadata())).ConfigureAwait(false);
>> //previous statement should fail - there was no stream - but it worked
>>
>> //and next statement fails because stream is not empty
>> await c.AppendToStreamAsync(streamId, ExpectedVersion.EmptyStream, new EventData(Guid.NewGuid(), "httpSessionSetDirection", true, GetBytes(new {direction = session.Direction.GetValueOrDefault().ToString("G")}), GetMetadata()).ConfigureAwait(false);
>>
>> Why is that? Did the behaviour change leaving documentation behind?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/428>.
>>
>
>
> --
> Studying for the Turing test
>
>


-- 
Studying for the Turing test
