### ISSUE TITLE
Offer subscription id or equivalent identification key to subscriptions

### ISSUE THREAD

**Issue by nmehlei** [EventStore/EventStore#429]
As with catch-up subscriptions it being up to the user to handle re-subscriptions etc in some cases (for example an exception inside the Event Handler), it would be very nice to have some kind of Id for the subscription accessible. 

https://groups.google.com/forum/#!searchin/event-store/nmehlei/event-store/X6AaqXzwLj0/W7tvuHbXxkAJ follows an issue where Events are sometimes skipped from being handled. This leads to the requirement of having to re-subscribe manually (to get back to a subscription state before the wrongfully skipped event number), during which time it is necessary to take care that only the EventAppeared-invocations of the "new" subscription are being handled.

Saving the return value of SubscribeToStreamFrom and just checking for reference equality inside each EventAppeared-invocation does not seem to be enough as at least once the subscription instance changed between those invocations and without a new Subscribe invocation. I guess this was the result of some auto-reconnect and re-subscription, which is fine, but if even the object can change, there is really nothing left to check which subscription should be the correct one. An identification number or string which gets transferred to a re-created subscription would solve this.

**Comment by gregoryyoung** [comment]
This is not the solution. Fixing the original problem is.

"during which time it is necessary to take care that only the
EventAppeared-invocations of the "new" subscription are being handled."

This is not true why do you care which subscription gave you the event so
long as you process it in order and once? This is actually a very common
pattern, hook up more than one subscription and basically take whichever
one comes first.

On Sun, Mar 22, 2015 at 3:12 PM, nmehlei <notifications@github.com> wrote:

> As with catch-up subscriptions it being up to the user to handle
> re-subscriptions etc in some cases (for example an exception inside the
> Event Handler), it would be very nice to have some kind of Id for the
> subscription accessible.
>
>
> https://groups.google.com/forum/#!searchin/event-store/nmehlei/event-store/X6AaqXzwLj0/W7tvuHbXxkAJ
> follows an issue where Events are sometimes skipped from being handled.
> This leads to the requirement of having to re-subscribe manually (to get
> back to a subscription state before the wrongfully skipped event number),
> during which time it is necessary to take care that only the
> EventAppeared-invocations of the "new" subscription are being handled.
>
> Saving the return value of SubscribeToStreamFrom and just checking for
> reference equality inside each EventAppeared-invocation does not seem to be
> enough as at least once the subscription instance changed between those
> invocations and without a new Subscribe invocation. I guess this was the
> result of some auto-reconnect and re-subscription, which is fine, but if
> even the object can change, there is really nothing left to check which
> subscription should be the correct one. An identification number or string
> which gets transferred to a re-created subscription would solve this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/429>.
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Its been almost a month on this issue so closing it feel free to reopen
