### ISSUE TITLE
Cannot reinstall projections

### ISSUE THREAD

**Issue by tranchis** [EventStore/EventStore#430]
Whenever I delete a projection (calling `/projection/{0}/command/disable` followed by a DELETE with `?deleteCheckpointStream=yes&deleteStateStream=yes` and POST the new projection with the same name, I get this error in the server: `Projection version and event number mismatch`, while in the GUI I get the following info:

![screen shot 2015-03-24 at 15 52 47](https://cloud.githubusercontent.com/assets/160790/6805974/dc334190-d23d-11e4-8e2e-a9f762db21ce.png)

The original projection worked perfectly, but any subsequent attempt to reinstall another version with the same name is failing all the time.

**Comment by gregoryyoung** [comment]
@pgermishuys do you want to look through this? My guess is something associated is not deleted and is still there on start up

**Comment by pgermishuys** [comment]
not a problem, will take a look at it this evening.

**Comment by FinnNk** [comment]
Was there any progress on this? - I'm seeing exactly the same behaviour (on 3.0.1 and 3.0.3)

**Comment by pgermishuys** [comment]
This was fixed in https://github.com/EventStore/EventStore/pull/517
