### ISSUE TITLE
Referencing other events

### ISSUE THREAD

**Issue by srogovtsev** [EventStore/EventStore#431]
I need a mechanism to reference one event from another: there's a `MessageReceived` and then `MessageParsed`, and I want to reference the former from the latter - i.e. I want to be able, after having read the `MessageParsed` from stream, quickly go to the `MessageReceived` it was parsed from.

What is the *recommended* way to do that?

Here are my thoughts on the subject:

1. Judging from the signature of `ReadEventAsync`, there's only one way to efficiently read a single event, which requires us to know stream id and event *number*.

2. Apparently, `AppendToStreamAsync` return a `WriteResult` containing `NextExpectedVersion`, but...

    1. There's no mention that it's an event number of a written event (although we can deduce that)

    2. What's worse, there's no guarantee that it contains the event number for the event *we* just wrote (considering concurrency scenario)

3. So it seems that after the write we have to read the stream from `NextExpectedVersion` backwards until we find our event, and the get its number for our purposes. The question is: how do we differentiate "our" event. Of course, we could add some metadata, but it'd be easier to use some already existing properties, which leads us to the next question:

4. Are event *ids* guaranteed to be unique within stream? There's a bug (#387) proving some times it's not; but is that just a bug, or is there really no guarantee that event ids are unique?

That said, I understand that it's possible to achieve my goals by using subscriptions (because `ResolvedEvent` in subscription handler already does have a number), but it means splitting some logic between two places, and I'd like to avoid that if possible.

**Comment by gregoryyoung** [comment]
1.

   What's worse, there's no guarantee that it contains the event number for
   the event *we* just wrote (considering concurrency scenario)

   It is the event you just wrote.





On Tue, Mar 24, 2015 at 9:42 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> I need a mechanism to reference one event from another: there's a
> MessageReceived and then MessageParsed, and I want to reference the
> former from the latter - i.e. I want to be able, after having read the
> MessageParsed from stream, quickly go to the MessageReceived it was
> parsed from.
>
> What is the *recommended* way to do that?
>
> Here are my thoughts on the subject:
>
>    1.
>
>    Judging from the signature of ReadEventAsync, there's only one way to
>    efficiently read a single event, which requires us to know stream id and
>    event *number*.
>    2.
>
>    Apparently, AppendToStreamAsync return a WriteResult containing
>    NextExpectedVersion, but...
>     1.
>
>       There's no mention that it's an event number of a written event
>       (although we can deduce that)
>       2.
>
>       What's worse, there's no guarantee that it contains the event
>       number for the event *we* just wrote (considering concurrency
>       scenario)
>        3.
>
>    So it seems that after the write we have to read the stream from
>    NextExpectedVersion backwards until we find our event, and the get its
>    number for our purposes. The question is: how do we differentiate "our"
>    event. Of course, we could add some metadata, but it'd be easier to use
>    some already existing properties, which leads us to the next question:
>    4.
>
>    Are event *ids* guaranteed to be unique within stream? There's a bug (
>    #387 <https://github.com/EventStore/EventStore/issues/387>) proving
>    some times it's not; but is that just a bug, or is there really no warranty
>    that event ids are unique?
>
> That said, I understand that it's possible to achieve my goals by using
> subscriptions (because ResolvedEvent in subscription handler already does
> have a number), but it means splitting some logic between two places, and
> I'd like to avoid that if possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/431>.
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
> It [`WriteResult.NextExpectedVersion`] is the event you just wrote.

That is an expected behaviour of the `AppendToStreamAsync`? And, if we call `AppendToStreamAsync` with one and only one event, we are guaranteed to receive its number?

**Comment by gregoryyoung** [comment]
Yes. That is the idea.

On Tue, Mar 24, 2015 at 9:48 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> It [WriteResult.NextExpectedVersion] is the event you just wrote.
>
> That is an expected behaviour of the AppendToStreamAsync? And, if we call
> AppendToStreamAsync with one and only one event, we are guaranteed to
> receive its number?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/431#issuecomment-85665788>
> .
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
It's great to hear that (in fact, that was my take on the problem, and it succeeded, but I didn't know if there were any concurrency issues). I suppose this point should be better documented in "Optimistic Concurrency & Idempotence".

Still, there are two questions left:

1. Is the EventId required to be unique within stream?

2. Are there any built-in mechanisms (metadata format? convention?) for implementing references between events?

**Comment by gregoryyoung** [comment]
1) Its not required but can give some interesting results if not
(idempotency)

2) There are not any conventions or formats for linking between events
though using the same format as linktos might be a good idea ###@streamid

On Tue, Mar 24, 2015 at 10:01 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> It's great to hear that (in fact, that was my take on the problem, and it
> succeeded, but I didn't know if there were any concurrency issues). I
> suppose this point should be better documented in "Optimistic Concurrency &
> Idempotence".
>
> Still, there are two questions left:
>
>    1.
>
>    Is the EventId required to be unique within stream?
>    2.
>
>    Are there any built-in mechanisms (metadata format? convention?) for
>    implementing references between events?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/431#issuecomment-85670148>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
I am closing this as it seems to be completed. If not feel free to reopen
