### ISSUE TITLE
Json containing DateTimeOffset preview in Web UI adds hours according to current timezone

### ISSUE THREAD

**Issue by Kleiboy92** [EventStore/EventStore#439]
Hi there,

Found a Web bug that cost me few hours and lots of brain power..

When posting a DataTimeOffset containing json, preview adds hours according to current timezone:
![image](https://cloud.githubusercontent.com/assets/5685084/6899591/4cdb0858-d70a-11e4-8712-ea61330c614f.png)

To reproduce:

    curl -i -d "{'time': '2015-03-29T15:45:00+00:00'}" "http://127.0.0.1:2113/streams/test" -H "Content-Type:application/json" -H "ES-EventType:TestType" -H "ES-EventId:9daa189c-356b-4ce8-9f4b-cbb3a277d6a3"

Cheers,

**Comment by gregoryyoung** [comment]
Oof good one. Its probably the deserialization that causes it. At least a
comment is deserved here in the UI cc @pieter

On Mon, Mar 30, 2015 at 6:36 PM, Kleiboy92 <notifications@github.com> wrote:

> Hi there,
>
> Found a Web bug that cost me few hours and lots of brain power..
>
> When posting a DataTimeOffset containing json, preview adds hours
> according to current timezone:
> [image: image]
> <https://cloud.githubusercontent.com/assets/5685084/6899591/4cdb0858-d70a-11e4-8712-ea61330c614f.png>
>
> To reproduce:
>
> curl -i -d "{'time': '2015-03-29T15:45:00+00:00'}" "http://127.0.0.1:2113/streams/test" -H "Content-Type:application/json" -H "ES-EventType:TestType" -H "ES-EventId:9daa189c-356b-4ce8-9f4b-cbb3a277d6a3"
>
> Cheers,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/439>.
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
This is fixed in 44a3618b4223a4f5090b35ca37c7586efb6e2b9f - good catch!

**Comment by Kleiboy92** [comment]
Found the same issue  in v3.6
![capture](https://cloud.githubusercontent.com/assets/5685084/14101544/deece72c-f59d-11e5-8245-41ed53d14176.PNG)

**Comment by pgermishuys** [comment]
@Kleiboy92 thanks for reporting this. The fix it seems wasn't brought over from the development branch into the release.

**Comment by pgermishuys** [comment]
@Kleiboy92 the commit mentioned in this issue will be brought over by https://github.com/EventStore/EventStore/pull/866
