### ISSUE TITLE
Outdated Docker run command on Docker image instructions

### ISSUE THREAD

**Issue by mitchterlisner** [EventStore/EventStore#4415]
I tried running EventStore in Docker by following video "EventStoreDB Series Part 1: Getting Started With EventStoreDB in Python" (https://www.youtube.com/watch?v=RyGGkMTM1Wg), published by EventStore in April 2024, which shows how to find the latest official EventStoreDB Docker container, and the instructions for it.  In it, latest is v23.10, and the secondary run command demonstrated is:

	docker run --name esdb-node -it -p 2113:2113 -p 1113:1113 eventstore/eventstore:latest --insecure --run-projections=All --enable-external-tcp --enable-atom-pub-over-http

Now, when I now follow the same steps, latest is v24.6.0, and the run command is identical; however, it fails with a fatal error:

	'...FTL] The option "EnableExternalTcp" is not a known option.'

I noticed this warning on the v24.6 Server Quick Start instructions for Docker (https://developers.eventstore.com/server/v24.6/installation.html#use-docker-compose):

	WARNING
	The legacy TCP client protocol is disabled by default and will no longer be available since version 24.2. To enable it in versions lower than 24.2, add the environment variable to the yaml file: EVENTSTORE_ENABLE_EXTERNAL_TCP=true

If I understand correctly, the "EnableExternalTcp" option (aka the legacy TCP client protocol) is no longer available in 24.2 or later, and the Docker image instructions are now just outdated, because that run command is now unsupported.  Do I understand correctly?  Do you want to update the Docker image instructions to remove that secondary run command?  Do you want to publish an updated video?

**To Reproduce**
Steps to reproduce the behavior [Steps shown in EventStore video]:
1. In Docker Desktop, search for eventstore image
2. Find secondary run command (with legacy protocols enabled) and copy to clipboard
3. Execute docker run command at terminal

**Expected behavior**
The Docker container runs successfully, and I can browse to the EventStore AdminUI.

**Actual behavior**
The Docker container stops/exits seconds after starting.  Error is reproducible by attempting to [re]start the container.
Logs show this error:

	2024-09-04 11:52:40 [    1, 1,17:52:40.843,FTL] The option "EnableExternalTcp" is not a known option.

**Config/Logs/Screenshots**
[esdb-node.log](https://github.com/user-attachments/files/16874940/esdb-node.log)

**EventStore details**
 - EventStore server version: 24.6
 - Operating system: Linux
 - EventStore client library and version (if applicable): N/A

(Submitting bug report here because the Docker image instructions say to submit issues here.)

**Comment by alexeyzimarev** [comment]
Good catch. That tutorial didn't need to have the legacy protocol enabled at all. As a workaround, I'd point to the latest version docs, it has the correct Docker command.

**Comment by mitchterlisner** [comment]
That tutorial continues on to demonstrate using the Stream Browser to add a stream and event.  In my understanding, the Stream Browser requires the legacy protocol, which is why that tutorial needed the legacy protocol.  (I found that tutorial via web search, just last month.  I think I read that the Stream Browser is getting replaced by ES Navigator... that's why I asked if ES wants to publish an updated video that demonstrates using ES Navigator instead of Stream Browser.)

**Comment by alexeyzimarev** [comment]
@jeanmarcjulien feedback for you :)

**Comment by alexeyzimarev** [comment]
I believe I fixed this one a while ago.
