### ISSUE TITLE
ES crash in GetStatistics

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#446]
Running $ce-CATEGORY projections.

OS X 10.9.5.

Commit https://github.com/EventStore/EventStore/commit/885611cb8e2bd6d6bce2daf4249ef133e5c7dd8a compiled according to README. (On 10.10, ES doesn't compile btw, due to warnings in V8)

This happens every approximately 40 restarts.

```
Created stats stream '$stats-127.0.0.1:2113', code = WrongExpectedVersion
10:19:02 eventstore.1   | Stacktrace:
09:01:02 eventstore.1   | Stacktrace:
09:01:02 eventstore.1   |
09:01:02 eventstore.1   |   at <unknown> <0xffffffff>
09:01:02 eventstore.1   |   at EventStore.Projections.Core.Services.Processing.CoreProjectionCheckpointManager.GetStatistics (EventStore.Projections.Core.Services.ProjectionStatistics) <0x0002e>
09:01:02 eventstore.1   |   at EventStore.Projections.Core.Services.Processing.DefaultCheckpointManager.GetStatistics (EventStore.Projections.Core.Services.ProjectionStatistics) <0x0001b>
09:01:02 eventstore.1   |   at EventStore.Projections.Core.Services.Processing.CoreProjection.GetStatistics (EventStore.Projections.Core.Services.ProjectionStatistics) <0x00060>
09:01:02 eventstore.1   |   at EventStore.Projections.Core.Services.Processing.CoreProjection.UpdateStatistics () <0x0004f>
09:01:02 eventstore.1   |   at EventStore.Projections.Core.Services.Processing.CoreProjection.GoToState (EventStore.Projections.Core.Services.Processing.CoreProjection/State) <0x003d7>
09:01:02 eventstore.1   |   at EventStore.Projections.Core.Services.Processing.CoreProjection.Handle (CoreProjectionProcessingMessage/CheckpointLoaded) <0x0014b>
09:01:02 eventstore.1   |   at EventStore.Projections.Core.Services.Processing.ProjectionCoreService.Handle (CoreProjectionProcessingMessage/CheckpointLoaded) <0x00077>
09:01:02 eventstore.1   |   at EventStore.Core.Bus.MessageHandler`1.TryHandle (EventStore.Core.Messaging.Message) <0x0008b>
09:01:02 eventstore.1   |   at EventStore.Core.Bus.InMemoryBus.Publish (EventStore.Core.Messaging.Message) <0x000d3>
09:01:02 eventstore.1   |   at EventStore.Core.Bus.InMemoryBus.Handle (EventStore.Core.Messaging.Message) <0x00017>
09:01:02 eventstore.1   |   at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (object) <0x00187>
09:01:02 eventstore.1   |   at System.Threading.Thread.StartInternal () <0x000c6>
09:01:02 eventstore.1   |   at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <0xffffffff>
09:01:02 eventstore.1   |
09:01:02 eventstore.1   | Native stacktrace:
```

**Comment by gregoryyoung** [comment]
Are you running projections?

Second question what OS/ mono version. This looks likely to be a mono regression with stack corruption etc or some unmanaged code happening elsewhere as the code there is managed and fairly straight forward.

Is this something that reproduces relatively often?

**Comment by haf** [comment]
Updated description

**Comment by gregoryyoung** [comment]
is mono compiled locally and what version?

**Comment by haf** [comment]
No, it's the official, latest:

```
Mono JIT compiler version 3.12.1 ((detached/0849ec7 Fri Mar 20 19:07:48 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-(detached/5486eb2)
	GC:            sgen
```

**Comment by gregoryyoung** [comment]
Is there a reason you are running 32bit mono?

eg mine is:

 ~/Code/GitStats   master  mono --version
Mono JIT compiler version 4.1.0 (master/48d64eb Sat Mar 21 03:42:51 EET 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by haf** [comment]
Yes: https://github.com/fsharp/fsharp/issues/378#issuecomment-85079490 and https://github.com/Homebrew/homebrew/pull/36651 and the fact that there's no recipe for getting all I need from the homebrew installer - it's very manual to set up mono in 64 bits with all the dependencies for doing development.

**Comment by gregoryyoung** [comment]
Its also odd that LLVM is enabled. Is this by default? Normally I see mono not enabling LLVM by default

**Comment by haf** [comment]
I suppose it's default.

**Comment by haf** [comment]
Quoting Michael Hutchinson's e-mail to me about it:

<blockquote>For example, On Mac, the Mono MDK pkg installer contains Mono, PCL, F#, IronPython,
IronRuby, Gtk#, GTK+, Boo, XSP, NuGet, VBNC, and more - all of which
are separately maintained projects. In the Xamarin Debian packages,
the reference assemblies ship in a package called
referenceassemblies-pcl.</blockquote>

**Comment by gregoryyoung** [comment]
I would try a few things here.

1) Use 64bit mono. We do not test with 32 binaries at all though (though
they should build/work its just not a deployment we have anyone actively
interested in. I don't think thats the issue here. When you built es I
assume you built for x86 as well?

2) Try disabling the LLVM backend on mono. As far as I know thats not
considered production as of now and default should still be built in jit.I
am going to ask on the mono devel list about this one though

What we are seeing here appears to be stack/heap corruption which is
normally caused by mismatched unmanaged code calls, unmanaged bugs (ours or
theirs), jit problems, or issues with GC.

On Thu, Apr 16, 2015 at 3:26 PM, Henrik Feldt <notifications@github.com>
wrote:

> I suppose it's default.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/446#issuecomment-93721586>
> .
>



-- 
Studying for the Turing test

**Comment by dnauck** [comment]
LLVM and x86 are the defaults for Mono's OSX packages. Same here.

**Comment by gregoryyoung** [comment]
"LLVM and x86 are the defaults for Mono's OSX packages. Same here."

Are they actually xamarin packages?

**Comment by dnauck** [comment]
From this download page afaik: http://www.mono-project.com/download/

**Comment by gregoryyoung** [comment]
OH OK

he was talking about brew install

On Thu, Apr 16, 2015 at 3:41 PM, Daniel Nauck <notifications@github.com>
wrote:

> From this download page afaik: http://www.mono-project.com/download/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/446#issuecomment-93724397>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
No, brew install is why I can't easily use x64 - I estimate a few days work to fix all dependencies so we can build our software on it...

**Comment by haf** [comment]
I've just followed the most basic readme; tried again, and ES is actually built with x86, so I suppose I have myself to blame. Since I don't think you support mixed x86 and x64 I'm closing this issue.

**Comment by gregoryyoung** [comment]
im not sure that will fix it but that likely could have something to do with it

**Comment by gregoryyoung** [comment]
Not sure if you are following on twitter but it appears brew install is
64bit without LLVM now?

On Thu, Apr 16, 2015 at 4:02 PM, Henrik Feldt <notifications@github.com>
wrote:

> I've just followed the most basic readme; tried again, and ES is actually
> built with x86, so I suppose I have myself to blame. Since I don't think
> you support mixed x86 and x64 I'm closing this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/446#issuecomment-93728621>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
Let me investigate this over the next weeks as I move things around for production.

**Comment by gregoryyoung** [comment]
You will be running production with 32bit mono on a macbook?

This would not be highly recommended :P

On Fri, Apr 17, 2015 at 3:43 PM, Henrik Feldt <notifications@github.com>
wrote:

> Let me investigate this over the next weeks as I move things around for
> production.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/446#issuecomment-93978426>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
Haha, no. I mean, I'm going to deep-dive into building EventStore properly and into rpms. And since I'll be doing that I might as well bundle this work together with that work.

**Comment by gregoryyoung** [comment]
So there has been talk about apt and rpms being supplied they are not at
all hard to create for binaries (no dependencies)

On Fri, Apr 17, 2015 at 3:46 PM, Henrik Feldt <notifications@github.com>
wrote:

> Haha, no. I mean, I'm going to deep-dive into building EventStore properly
> and into rpms. And since I'll be doing that I might as well bundle this
> work together with that work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/446#issuecomment-93978917>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
Getting it on amd64-compiled mono as well:

```
18:43:59              | [86276,18,16:43:55.806] Created stats stream '$stats-127.0.0.1:2113', code = WrongExpectedVersion
18:43:59              | Stacktrace:
18:43:59              |
18:43:59              |
18:43:59              | Native stacktrace:
18:43:59              |
18:43:59              |
18:43:59              | Debug info from gdb:
18:43:59              |
18:43:59              | /tmp/mono-gdb-commands.b9zKBO:1: Error in sourced command file:
18:43:59              | Unable to find Mach task port for process-id 86276: (os/kern) failure (0x5).
18:43:59              |  (please check gdb is codesigned - see taskgated(8))
18:43:59              |
18:43:59              | =================================================================
18:43:59              | Got a SIGSEGV while executing native code. This usually indicates
18:43:59              | a fatal error in the mono runtime or one of the native libraries
18:43:59              | used by your application.
18:43:59              | =================================================================
18:43:59              |
```

**Comment by gregoryyoung** [comment]
Set MONO_GC_DEBUG=clear-at-gc mono-sgen env var.

Cheers,

Greg

On Mon, Jul 20, 2015 at 6:46 PM, Henrik Feldt <notifications@github.com>
wrote:

> Getting it on amd64-compiled mono as well:
>
> 18:43:59              | [86276,18,16:43:55.806] Created stats stream '$stats-127.0.0.1:2113', code = WrongExpectedVersion
> 18:43:59              | Stacktrace:
> 18:43:59              |
> 18:43:59              |
> 18:43:59              | Native stacktrace:
> 18:43:59              |
> 18:43:59              |
> 18:43:59              | Debug info from gdb:
> 18:43:59              |
> 18:43:59              | /tmp/mono-gdb-commands.b9zKBO:1: Error in sourced command file:
> 18:43:59              | Unable to find Mach task port for process-id 86276: (os/kern) failure (0x5).
> 18:43:59              |  (please check gdb is codesigned - see taskgated(8))
> 18:43:59              |
> 18:43:59              | =================================================================
> 18:43:59              | Got a SIGSEGV while executing native code. This usually indicates
> 18:43:59              | a fatal error in the mono runtime or one of the native libraries
> 18:43:59              | used by your application.
> 18:43:59              | =================================================================
> 18:43:59              |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/446#issuecomment-122945296>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
Thanks, I'll try that a few days and see if it crashes. I've verified the env var is set this time with `printenv`.

**Comment by gregoryyoung** [comment]
We have seen the same and this fixes it.

Cheers,

Greg

On Mon, Jul 20, 2015 at 6:50 PM, Henrik Feldt <notifications@github.com>
wrote:

> Thanks, I'll try that a few days and see if it crashes. I've verified the
> env var is set this time with printenv.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/446#issuecomment-122947288>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Next static binaries do this for you.

On Mon, Jul 20, 2015 at 6:56 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> We have seen the same and this fixes it.
>
> Cheers,
>
> Greg
>
> On Mon, Jul 20, 2015 at 6:50 PM, Henrik Feldt <notifications@github.com>
> wrote:
>
>> Thanks, I'll try that a few days and see if it crashes. I've verified the
>> env var is set this time with printenv.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/446#issuecomment-122947288>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
Sweet! That's great! We've been scratching our heads at the behaviour here... ;) I'm closing this issue then.

**Comment by jen20** [comment]
@haf the compiled versions we're working on at the moment have the fix for this included in the bundle executable (via a slightly hacky means - see bd5858d5 - but that's about the best we can do for now).
