### ISSUE TITLE
PersistentSubscription: Retry 10 events causes subscription to block

### ISSUE THREAD

**Issue by lscpike** [EventStore/EventStore#448]
To reproduce the issue:
- Create a persistent subscription on a stream with > 10 events.
- Connect to the subscription with default buffer size of 10.
- NACK + Retry all messages received.
- You will stop receiving messages after the first 10 retries.

I actually noticed this in the code first. The code path through PersistentSubscriptionClientCollection.RemoveProcessingMessage results in the in flight message being removed form the PersistenSubscriptionClient but AvailableSlots is not incremented.

I'm happy to put together a pull request for this, but it looks suspiciously like there was a reason for this I can't see. Any comments?

**Comment by gregoryyoung** [comment]
It should be. Include tests if a pr. If not I'll be on it maybe tomorrow but likely in a week or two due to baby. If you pr don't feel bad if it sits for a bit before review.
