### ISSUE TITLE
Expired reads for the $projections-$all stream not retried

### ISSUE THREAD

**Issue by lakshdeepsingheventstore** [EventStore/EventStore#4492]
Ticket : https://eventstore.freshdesk.com/a/tickets/111306

Expired read for the **$projections-$all** was not retried, as a result of which the user was unable to get any projection to appear in the projections list in ESDB UI. As per the logs shared, the projection subsystem components started, but the projections were not listed in the logs.

**Expected behavior**
The expired read should have been retried.

**Actual behavior**
Expired read was not retried. The projections list could not be loaded in ESDB UI

**Config/Logs/Screenshots**
![image](https://github.com/user-attachments/assets/aa5922bf-fc61-4ffa-b666-f13986e0720c)

**EventStore details**
 - 23.10.3

 - Operating system: Windows Server 2019

**Workaround**
Restarting the projection subsystem fixes the issue.

**Comment by ylorph** [comment]
@lakshdeepsingheventstore : can you add the workaround or restarting the subsytem ?

**Comment by timothycoleman** [comment]
This is fixed in 23.10.4 and 24.10.0
