### ISSUE TITLE
Significant drop in free memory metric after upgrade to 24.6.0

### ISSUE THREAD

**Issue by huynhhuuloc129** [EventStore/EventStore#4507]
**Describe the bug**
After upgrading from version 23.10.1 to 24.6.0, the free memory reported by the eventstore_sys_mem_bytes{kind="free"} metric dropped significantly, now hovering around 2% of total memory. Prior to the upgrade, free memory was reported to be around 70% of total memory.

**EventStore details**
 - EventStore server version: 23.10.1 and 24.6.0
 - Operating system: Ubuntu

**Comment by timothycoleman** [comment]
Hey sorry in 24.6.0 for Linux the free memory stat was changed to be drawn from `MemFree` rather than `MemAvailable` in `/proc/meminfo`, we've reverted that change, MemAvailable is more suitable. The fix will be in 24.10.0 which will be coming out later this month
