### ISSUE TITLE
Users helper app/script

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#451]
Don't really care which it is, its just wrapping restful api.

Should support add/enable/disable/etc. This functionality is already provided in the Client API via UserManager its really just a wrapper

Ideally it would also do something with ACLs from command line

**Comment by gregoryyoung** [comment]
Go has been chosen as tool of choice for this so it would be redoing the calls to the restful api in Go

**Comment by pgermishuys** [comment]
Solved by https://github.com/EventStore/es-cli
