### ISSUE TITLE
Documentation Issue, http api

### ISSUE THREAD

**Issue by tomthetrainer** [EventStore/EventStore#4515]
This grayed out line for http, that used to be a link, should either be rem
<img width="265" alt="Screenshot 2024-10-10 at 5 51 42 PM" src="https://github.com/user-attachments/assets/d641939b-0562-4aba-ba31-54889cb9cea1">
oved, or made a link.

**Comment by coloradomorrissey** [comment]
@tomthetrainer The HTTP API grey line is a header.  You can access the docs by clicking on the relevant version under the header.
