### ISSUE TITLE
English

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#454]
There are some English issues around in exceptions/log messages etc. Cleaning these up would be quite useful.

I don't think this is a single task but more a marker for a bunch of them.

**Comment by NetChris** [comment]
Can I help?  I speak-a the English!

**Comment by gregoryyoung** [comment]
Yeah its mostly just going through code looking at exceptions/error messages for whats in them. find ./ | grep Sparta would be a good place to start :)

Or just looking through logs for oddities

**Comment by NetChris** [comment]
Oh dear.  Such cheek!  I'll see what I can do.

**Comment by jen20** [comment]
#460 and #470 go a long way towards rectifying this. Great work @NetChris, will close this ticket and treat and others on a case-by-case basis.
