### ISSUE TITLE
eventstore crashes

### ISSUE THREAD

**Issue by svalaskevicius** [EventStore/EventStore#459]
Hi, I've enabled projections via `--run-projections All` and trying to get some projections running.

So far I've experienced a few crashes with this info:
```
Stacktrace:


Native stacktrace:

	./clusternode() [0x612962]
	./clusternode() [0x5beb0b]
	./clusternode() [0x4584f3]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f5a70d59340]
	[0x404e2a09]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
```

```
[05956,08,20:32:34.423] Global Unhandled Exception occurred.
Object reference not set to an instance of an object
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at EventStore.Core.Services.TimerService.ThreadBasedScheduler.DoTiming () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
```

at all times (so far < 5 in 10 minutes) I've experienced this when the cpu load was 100% on the VM (to emit the projection events :) )

version used: `EventStore-OSS-Linux-v3.0.3`

vm info:
```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

# uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gregoryyoung** [comment]
This is happening in ubuntu 14.04 especially on vas at this point and we have not yet debugged why. It does not happen with most other forms of linux or on 14.10

**Comment by gregoryyoung** [comment]
vms*

**Comment by svalaskevicius** [comment]
thx, will get a newer VM then :)

**Comment by svalaskevicius** [comment]
should I close this issue or is it still relevant for you?

**Comment by mwalton236** [comment]
14.10 is not a long term support version of Ubuntu, 14.04 is the current LTS, wouldn't it be wise to debug this in 14.04?

**Comment by gregoryyoung** [comment]
Pretty sure it's just with binaries and not if you build locally (binaries
were built in 14.10 iirc)

On Wednesday, July 1, 2015, Martin Walton <notifications@github.com> wrote:

> 14.10 is not a long term support version of Ubuntu, 14.04 is the current
> LTS, wouldn't it be wise to debug this in 14.04?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/459#issuecomment-117678148>
> .
>


-- 
Studying for the Turing test

**Comment by mwalton236** [comment]
I've tried building and packaging locally, I still see the same error occuring.
Support for 14.10 ends in July 2105.

**Comment by gregoryyoung** [comment]
As far as I know 15.04 also does not have the issue. I also seem to
remember that upgrading the kernel on 14.04 also removed the issue.

On Thu, Jul 2, 2015 at 11:51 AM, Martin Walton <notifications@github.com>
wrote:

> I've tried building and packaging locally, I still see the same error
> occuring.
> Support for 14.10 ends in July 2105.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/459#issuecomment-117963141>
> .
>



-- 
Studying for the Turing test

**Comment by mwalton236** [comment]
I do need it to work on a long term support version however

**Comment by jen20** [comment]
Out of interest why do you need that? Are you paying Canonical for support
or something? There's no reason not to keep software up to date.

However, the next release will likely be built on Debian 7 with 2.13 of
glibc so you should be good on 14.04.

James

**Comment by mwalton236** [comment]
Maintenance costs. Ubuntu LTS versions like 14.04 trusty are supported for security patches for 5 years, where as the bleeding edge versions are only supported for 9 months. It costs less to maintain the security patches of the servers, rather than rebuild or upgrade the OS every 9 months. The testing is less extensive on the bleeding edge versions too, which means more costly testing may be required every 9 months when you need to upgrade.

**Comment by gregoryyoung** [comment]
Expect an update on this Monday.
