### ISSUE TITLE
Mono v4.0 - ES thinks it's v2.x

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#461]
<blockquote>Exit reason: It appears that we are running in Linux or MacOS with a version 2 build of Mono. This is generally not a good idea and we recommend running with Mono 3.6 or higher. If you really want to run with this version of Mono use the --force flag on Event Store to override this error.</blockquote>

**Comment by gregoryyoung** [comment]
Will update check.

On Thu, Apr 30, 2015 at 3:26 PM, Henrik Feldt <notifications@github.com>
wrote:

> Exit reason: It appears that we are running in Linux or MacOS with a
> version 2 build of Mono. This is generally not a good idea and we recommend
> running with Mono 3.6 or higher. If you really want to run with this
> version of Mono use the --force flag on Event Store to override this error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/461>.
>



-- 
Studying for the Turing test
