### ISSUE TITLE
Events do not get acked on PersistentSubscription with ResolveLinkTos=true when autoAck=false

### ISSUE THREAD

**Issue by megakid** [EventStore/EventStore#466]
To reproduce the issue:

Create a persistent subscription on a projected stream e.g. "$ce-Test" with ResolveLinkTos enabled.
Connect to the subscription with default buffer size of 10 and autoAck = false.
Post more than 10 events onto a stream that projects onto the above e.g. "Test-1".
Consume events using subscription and acknowledge all.
You will stop receiving messages after the first 10 messages (this matches the buffer size of the subscription).
This is because the client library acknowledges the wrong GUID when using linked events.

A pull request is on the way for this.

    using System;
    using System.Threading;
    using EventStore.ClientAPI;
    using EventStore.ClientAPI.SystemData;
    using NUnit.Framework;

    namespace EventStore.Tests
    {
        internal static class Util
        {
            public static readonly UserCredentials UserCredentials = new UserCredentials("admin", "changeit");

            public static IEventStoreConnection CreateConnection()
            {
                ConnectionSettings connSettings = ConnectionSettings
                    .Create()
                    .KeepReconnecting()
                    .SetDefaultUserCredentials(UserCredentials)
                    .UseConsoleLogger()
                    .Build();

                IEventStoreConnection conn = EventStoreConnection.Create(connSettings, new Uri("discover://my-cluster:30787"));

                conn.ConnectAsync().Wait();

                return conn;
            }
        }

        [TestFixture, Explicit]
        public class PersistentSubscriptionTests
        {
            private const string StreamName = "test-stream";
            private const string StreamRead = "$ce-test";
            private const string GroupName = "test-group";
            private const int BufferCount = 10;
            private const int EventWriteCount = BufferCount * 2;

            private readonly ManualResetEvent _eventsReceived = new ManualResetEvent(false);
            private int _eventReceivedCount;

            [Test]
            public void Test()
            {
                using (IEventStoreConnection conn = Util.CreateConnection())
                {
                    PersistentSubscriptionSettings settings = PersistentSubscriptionSettings
                        .Create()
                        .StartFromCurrent()
                        .ResolveLinkTos()
                        .Build();

                    conn.DeleteStreamAsync(StreamName, ExpectedVersion.Any).Wait();

                    conn.DeletePersistentSubscriptionAsync(StreamRead, GroupName);

                    conn.CreatePersistentSubscriptionAsync(StreamRead, GroupName, settings, Util.UserCredentials).Wait();

                    conn.ConnectToPersistentSubscription(StreamRead, GroupName, EventAppeared, SubscriptionDropped, bufferSize: 10, autoAck: false);

                    for (int i = 0; i < EventWriteCount; i++)
                    {
                        EventData eventData = new EventData(Guid.NewGuid(), "SomeEvent", false, new byte[0], new byte[0]);

                        conn.AppendToStreamAsync(StreamName, ExpectedVersion.Any, eventData);
                    }

                    if (!_eventsReceived.WaitOne(TimeSpan.FromSeconds(5)))
                    {
                        throw new Exception("Timed out waiting for events.");
                    }
                }
            }

            private void EventAppeared(EventStorePersistentSubscriptionBase subscription, ResolvedEvent resolvedEvent)
            {
                Console.WriteLine("Event: {0}.", resolvedEvent.Event.EventId);

                subscription.Acknowledge(resolvedEvent);

                if (Interlocked.Increment(ref _eventReceivedCount) == EventWriteCount)
                {
                    _eventsReceived.Set();
                }
            }

            private static void SubscriptionDropped(EventStorePersistentSubscriptionBase subscription, SubscriptionDropReason reason, Exception exception)
            {
                Console.WriteLine("Subscription dropped (reason:{0}, exception:{1}).", reason, exception);
            }
        }
    }

**Comment by gregoryyoung** [comment]
There is a fix for this on dev already.

I literally fixed this today. https://github.com/EventStore/EventStore/pull/465

Cheers,

Greg

**Comment by gregoryyoung** [comment]
Can you verify the fix is the same as you were referring to and resolves this issue?

**Comment by megakid** [comment]
Fix looks good.  Where are the tests? :)

**Comment by gregoryyoung** [comment]
This isn't the kind of thing you want to unit test... there are other tests
we run that are not part of the oss tests :)

That said I wouldn't mind adding a few sanity tests to the OSS suits on
this.

On Fri, May 1, 2015 at 9:36 PM, megakid <notifications@github.com> wrote:

> Fix looks good. Where are the tests? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/466#issuecomment-98201722>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
here you go!  https://github.com/EventStore/EventStore/issues/467

You can assign it. If however in the next bit its still there I will just start doing it and its not a ton of work :)

**Comment by megakid** [comment]
The test I posted above could be optimized to be a quick running test that demonstrates this issue. Would it be an issue to include it in the oss tests?

**Comment by gregoryyoung** [comment]
Nope and a couple related tests (as listed in issue) just make sure they have Category LongRunning

**Comment by megakid** [comment]
Sorry didn't see your last post referring to #467. Nice one

**Comment by gregoryyoung** [comment]
does that mean you are grabbing it? if not I am going to hit it up this afternoon just don't want to double up work :)

**Comment by megakid** [comment]
Not looking likely that I'll be able to grab that sorry.  If it's still around next week I might be able to take it on.

**Comment by gregoryyoung** [comment]
No worries. It will probably be pushed by tomorrow

On Sat, May 2, 2015 at 2:15 PM, megakid <notifications@github.com> wrote:

> Not looking likely that I'll be able to grab that sorry. If it's still
> around next week I might be able to take it on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/466#issuecomment-98348011>
> .
>



-- 
Studying for the Turing test
