### ISSUE TITLE
worker-javascript.js isn't loaded because of a redundant "/"

### ISSUE THREAD

**Issue by rradczewski** [EventStore/EventStore#471]
While trying out GetEventStore, I encountered a js error (or rather an error with the urls composed in the js sourcecode) that could lead to an application error: The url for the Worker Javascript is resolved to `http://localhost:2113/web//js/ace/worker-javascript.js` instead of `http://localhost:2113/web/js/ace/worker-javascript.js`, which yields a 404 error instead of the worker script.

## Environment:
```
Mono Version: Bundled
GetEventStore Version: v3.0.3 OSS Binary
OS: Ubuntu 14.04 64bit in Docker on Arch Linux
```

## Steps to reproduce

I used [this Dockerfile](https://raw.githubusercontent.com/rradczewski/dockerfiles/master/eventstore/Dockerfile), forked from [Andrew Browne's](https://github.com/adbrowne/dockerfiles/blob/master/eventstore/Dockerfile), to create a docker container with GetEventStore v3.0.3 running in it.

The following steps are needed to reproduce the issue:

```
$ mkdir /tmp/docker-build && curl https://raw.githubusercontent.com/rradczewski/dockerfiles/master/eventstore/Dockerfile > /tmp/docker-build/Dockerfile
$ docker build -t faulty-event-store /tmp/docker-build
$ docker run -p 1113:1113 -p 2113:2113 -it faulty-event-store
```

Then:

1. Navigate to [http://localhost:2113/](http://localhost:2113/) and login using admin:changeit as credentials
2. Navigate to Query Tab
3. The following 404 happens while loading the worker-script:
![screenshot from 2015-05-04 19-01-14](https://cloud.githubusercontent.com/assets/418117/7457866/f74ba126-f28f-11e4-8264-fe4ea828f5f5.png)

I was able to successfully load the worker script by striping the "/" from the url, although that was just a dirty workaround to see if the UI behaved *weird* (sorry for being unspecific here) because of this error.

I'll have a look at the source code this evening and see if i can spot the problem.

**Comment by jen20** [comment]
I think @pgermishuys already fixed this on dev, will investigate however.

**Comment by pgermishuys** [comment]
Yeah, this was resolved in https://github.com/EventStore/EventStore.UI/commit/23a2799bac8b3dc3fcdf8fb93b1bf004e189d28e

![image](https://cloud.githubusercontent.com/assets/1062417/7820762/89f05e84-03ea-11e5-9345-3dbf4df78049.png)
