### ISSUE TITLE
Static linking ES on CentOS doesn't work

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore#473]
I've ["just run build.sh"](https://github.com/haf/EventStore-build/blob/master/Dockerfile#L45-L46) but am having trouble running the clusternode after the fact:

```
$ ./clusternode
libmonosgen-2.0.so.1: cannot open shared object file: No such file or directory
```

It seems `clusternode` is dynamically linked:

```
../pkgbase/opt/eventstore/clusternode: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=0xd7ae0a4cbc9dcdf812d632832f13ad16eaa06718, not stripped
```

I can verify it works when installing the mono it was built with. Xamarin's repos give the amd64 version of the mono binary.

**Comment by ouro-ouroboros** [comment]
It's not statically linked after build, you'll also need to run "scripts/package-mono/package-mono.sh version" for that

**Comment by haf** [comment]
Have a look at the link: I do that already.

**Comment by ouro-ouroboros** [comment]
On phone. Will look when I'm back late next week unless someone else picks it up earlier

**Comment by haf** [comment]
Ok, thanks!

**Comment by haf** [comment]
This means that I have to change the OS X system mono, which invalidates the .targets files, too. So this means that you can't without much effort create a dev environment that doesn't crash on OS X with the latest eventstore when you want to use XS to edit code.

**Comment by gregoryyoung** [comment]
Why do you need static linking as part of this?

On Mon, May 11, 2015 at 5:07 PM, Henrik Feldt <notifications@github.com>
wrote:

> This means that I have to change the OS X system mono, which invalidates
> the .targets files, too. So this means that you can't without much effort
> create a dev environment that doesn't crash on OS X with the latest
> eventstore when you want to use XS to edit code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/473#issuecomment-100918974>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
* brew install mono -- doesn't install .targets files, installs mono in 64-bit mode
* download official installer -- install .targets files, mono in x86/32-bit mode

With static linking I could build ES for OS X with mono 64 bit statically linked and run it side-by-side with 32-bit mono required for XS and required for building my application by having the right .targets-files available.

**Comment by jen20** [comment]
You should now be able to do this - there was an error corrected in the static linking scripts which fixed static linking for Amazon Linux (and therefore I assume CentOS as well though untested). You'll still need to compile `libjs1` against an appropriate version of libc.
