### ISSUE TITLE
Get rid of test client

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#479]
Would be much nicer to just write the functionality into a .fsx and people can use from there. Also deletes the vast majority of the code associated with it (parsing etc)

Thoughts?

**Comment by jen20** [comment]
I would tend to disagree with this - especially on Linux etc it's not reasonable to expect people to set up fsi just to be able to run the performance tests. If we want to improve the experience using the tools we might be better off rebuilding them with Go (with the added benefit that we also get a client API for Go with that which would be a net win).

**Comment by jen20** [comment]
OTOH there's no harm in providing an FSX for the people that like that sort of thing.

**Comment by gregoryyoung** [comment]
I'd even say scriptcs more so (or just a series of tiny apps) just so that
we aren't building the whole repl around it

On Tue, May 19, 2015 at 5:10 PM, James Nugent <notifications@github.com>
wrote:

> OTOH there's no harm in providing an FSX for the people that like that
> sort of thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/479#issuecomment-103512779>
> .
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
Yes agreed that splitting it up into multiple commands rather than having a REPL style interface would be a good idea - bash can then be used for creating test "suites" etc

**Comment by gregoryyoung** [comment]
Yeah for me its mostly the crappy interface ...

fsx would get rid of that ... or bash + fine grained commands or clojure :P

On Tue, May 19, 2015 at 5:14 PM, James Nugent <notifications@github.com>
wrote:

> Yes agreed that splitting it up into multiple commands rather than having
> a REPL style interface would be a good idea - bash can then be used for
> creating test "suites" etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/479#issuecomment-103514589>
> .
>



-- 
Studying for the Turing test

**Comment by dnauck** [comment]
I wonder why you want to add another dependency (GO) to event store. Its hard enough to get a permission and possibility to use Mono on customers systems. Adding another runtime environment does not make life easier.

**Comment by jen20** [comment]
@dnauck Go has no user-facing runtime. It compiles to native binaries with no additional dependencies. The administration tools will also be moving to this over time (as per #451) - it will be vastly more straightforward than mono.

**Comment by forki** [comment]
>> especially on Linux etc it's not reasonable to expect people to set up fsi just to be able to run the performance tests.

Could you elaborate? 

you can run stuff with FAKE (retrieved by Nuget) or you can reference fsi from https://www.nuget.org/packages/FSharp.Compiler.Tools/

**Comment by dnauck** [comment]
@jen20 Ok, wasn't aware of that. But please bear in mind that you not depend on too many or too new system libraries. Some large environments have older (so called "stable" .. ;) ) distributions with stripped down distributions (... for security reasons...). I need to run everything in my normal user's home  directory, without root access. See also #223 

Thanks.

**Comment by jen20** [comment]
@Dnauck if you need support for older operating systems you can build and run on the mono framework itself - we only support recent builds of Ubuntu out of the box.

**Comment by jen20** [comment]
We'd also consider supporting Amazon Linux in our image builds however.

**Comment by pgermishuys** [comment]
We can build this into the CLI? @gregoryyoung @jen20?
