### ISSUE TITLE
EventStoreConnection lifecycle

### ISSUE THREAD

**Issue by srogovtsev** [EventStore/EventStore#481]
Do I have to keep a connection open during all the time I want to receive events in subscription? I.e., if I want to be subscribed for all the running time of the application, and application is a service - will I keep the connection open for several weeks or months?

Also, the docs state that
> EventStoreConnection is thread-safe, and it is recommended that only one instance per application is created.

Is that still true for web applications with a lot of concurrent users?

**Comment by gregoryyoung** [comment]
Yes. You must keep a connection open.

Yes though with huge numbers you might like a few.

The protocol does not work like say sql which is req/resp, the protocol is fully async so literally every request can talk to the same connection and not open/close every request or need connection pooling up to very high numbers.

The connection will also manage reconnecting etc in case of disconnects (controlled by the builder)
