### ISSUE TITLE
Monitoring stream creation

### ISSUE THREAD

**Issue by srogovtsev** [EventStore/EventStore#482]
I'd like to subscribe to some event that will be emitted every time a stream is created in EventStore. As far as I know, there was some kind of event like that, but it is no more, at least in documentation. What is the easiest way to do that (without manually emitting "somethingCreated" into new streams)?

**Comment by gregoryyoung** [comment]
$streams projection

On Fri, May 22, 2015 at 2:36 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> I'd like to subscribe to some event that will be emitted every time a
> stream is created in EventStore. As far as I know, there was some kind of
> event like that, but it is no more, at least in documentation. What is the
> easiest way to do that (without manually emitting "somethingCreated" into
> new streams)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/482>.
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
What exactly does it store? First event for each stream?

**Comment by srogovtsev** [comment]
Is there somewhere a description for each system projection?

**Comment by srogovtsev** [comment]
What I see from a small experiment:

`$streams` - holds first event in every stream.
`$ce-<category>` - holds every event from every stream categorized as `<category>`
`$et-<eventtype>` - holds every event of `<eventtype>`

There's one thing I don't undestand: `$category-<category>`. Instead of links (which are typed `$>` it holds something typed as `$@`, its metadata is same as link's, but it's body is stream Id.

E.g., when I push first event `createStream` into stream `picture-edc6c5793921448da85c1d0372dc1b58` I get the following:

```
Link: $> 111@$streams
Meta: {"$v":"1:-1:1:3","$c":4344406,"$p":4344406,"$causedBy":"52cb2ce6-0875-42ca-a26f-187a5c39e245"}
Data: 0@picture-edc6c5793921448da85c1d0372dc1b58
Resolved event: createStream 0@picture-edc6c5793921448da85c1d0372dc1b58
Meta:
Data: {"id":"edc6c579-3921-448d-a85c-1d0372dc1b58","category":"picture","eventType":"createStream"}
-----------
Event: $@ 26@$category-picture
Meta: {"$v":"2:-1:1:3","$c":4344406,"$p":4344406,"$causedBy":"52cb2ce6-0875-42ca-a26f-187a5c39e245"}
Data: picture-edc6c5793921448da85c1d0372dc1b58
```

It seems to me like something like `$streams` partioned by category, but why another link format?

**Comment by gregoryyoung** [comment]
No as they are still in beta they will be leaving beta shortly.

For now the best thing to do is probably read the source (they are pretty
straight forward).
https://github.com/EventStore/EventStore/blob/dev/src/EventStore.Projections.Core/Standard/IndexStreams.cs#L67
as example. If you know they JS side it should be fairly easy to read?

On Fri, May 22, 2015 at 2:45 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> Is there somewhere a description for each system projection?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/482#issuecomment-104640360>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
For second question (I responded via email and it lost threading)

The category stream has to deal with by category projections and is stream link iirc and without reading the code

**Comment by gregoryyoung** [comment]
Can we close this or is there something still outstanding?

**Comment by srogovtsev** [comment]
I think that we can (although having a doc somewhere on site would still be good).

**Comment by gregoryyoung** [comment]
There will be when projections are fully supported :)

On Mon, Jul 6, 2015 at 2:47 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> I think that we can (although having a doc somewhere on site would still
> be good).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/482#issuecomment-118829313>
> .
>



-- 
Studying for the Turing test
