### ISSUE TITLE
Native Java support

### ISSUE THREAD

**Issue by vach** [EventStore/EventStore#486]
Do we have native java support planned anytime soon?

It sucks that i'm gonna work with my own database over http...

**Comment by jen20** [comment]
There is JVM support already either via this: https://github.com/eventstore/eventstore.jvm (supported) or this https://github.com/valdasraps/esj (unsupported).

However, I am currently working on a Java 8 only client which may become supported at some point in the future, please see https://gist.github.com/jen20/f061db530ae401765aeb and the mailing list for further information if you want to influence the direction of this.

**Comment by gregoryyoung** [comment]
See ^^^

However what sucks about accessing a db over http?

There has been some talk about a vnext db. What if such db was supporting
100k transactions/second over plain ole http/2? Admin APIs were all just
plain restful services etc.

Obviously you would probably use a jvm client for such a thing but having a
http transport. Is there something wrong with it that I am missing?

Cheers,

Greg


On Wed, May 27, 2015 at 6:47 PM, James Nugent <notifications@github.com>
wrote:

> There is JVM support already either via this:
> https://github.com/eventstore/eventstore.jvm (supported) or this
> https://github.com/valdasraps/esj (unsupported).
>
> However, I am currently working on a Java 8 only client which may become
> supported at some point in the future, please see
> https://gist.github.com/jen20/f061db530ae401765aeb and the mailing list
> for further information if you want to influence the direction of this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/486#issuecomment-105968742>
> .
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
FWIW in many cases HTTP scales far better since you can scale commoditised infrastructure like caching layers.

**Comment by gregoryyoung** [comment]
yep!

On Wed, May 27, 2015 at 7:29 PM, James Nugent <notifications@github.com>
wrote:

> FWIW in many cases HTTP scales far better since you can scale commoditised
> infrastructure like caching layers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/486#issuecomment-105985529>
> .
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
https://github.com/jen20/EventStore.Java/ is the repository, feel free to check out the proposed public API.

**Comment by vach** [comment]
@jen20 as far as i can see the first (supported) repo its for scala or java but with akka framework? (i cant use it with pure java?)

@gregoryyoung not that i've tested something and dont find http fast enought but i never saw db communication over http (except firebase) but you'll know better Greg. For start i'm going to develop a microservice that shall collect many exchange orderbook data (all orders/trades etc...) and provide api to fetch historical data or getting updates realtime...
Here is why i dont think http is a good option just for my particular case, I'm using LMAX disrupter and my business logic will not work on event until it is persisted successfully, thus i need latency to be short when sending events to database... as http is quite a high level protocol i assume it will add significant overhead when frequency of updates is high but data transmitted is small... but thats not tested and thats just my assumption.
Also regarding 100k transactions/second i'm pretty sure its more than enough for 90% of projets, but the same LMAX does event persistance before processing any business logic (just like i'm about to do) and they do millions of transactions per second, maybe this is not the same transaction because they might be persisting events in batches...

Is there any benchmarks for .Net native vs HTTP client latencies? and generally how does performance differ?

@jen20 thanks, the pure java8 on TCP level is probably the max speed possible,
does it allow to persist and read events at the moment?

i'll check out EventStore more closely (havent read much yet).

**Comment by jen20** [comment]
The supported client is based on Akka and written in Scala, but you can use it from Java as well. The Java 8 client isn't yet functional, the repository is there to solicit feedback on the public API. It's a side project so will likely take a while.

Are you sure that LMAX are not batching their persistence? For lowest latency you will want TCP, agreed. HTTP is a common protocol for databases by the way - for scalability it's likely better than TCP, though not for latency. HTTP/2 on the other hand may well be just as good.

**Comment by vach** [comment]
They are batching but not all of it, batching only starts when the consumer (persisting part) is not catching up with incoming events, then it is capable to batch all that is arrived... but if it can it will proces one by one. anyway

regarding http, i guess i just never used that :), i've had an oracle that did scale out of the box but again wasnt http.

What would you recommend in that case? does it make sence to use Eventstore over http if i'm expecting something like few thousent events per second?

**Comment by jen20** [comment]
You're confusing throughput with latency: a few thousand per second over HTTP is perfectly achievable, but the latency will likely be higher than with TCP.

**Comment by vach** [comment]
Oh yes my bad, 2 AM here :(
I'll read the documentation and check out the api tomorrow, lets just keep this opened for further questions if you dont mind.

**Comment by jen20** [comment]
You'd be better off posting usage questions on the mailing list (https://groups.google.com/forum/#!forum/event-store) on on the specific repo - I'll close this one for now.
