### ISSUE TITLE
Enhance stored event data and meta data with mime type

### ISSUE THREAD

**Issue by michael-schnell** [EventStore/EventStore#493]
It would be nice to have real [mime types](http://en.wikipedia.org/wiki/Internet_media_type) (like "application/xml; encoding=utf-8; whatever=true") stored for data **and** meta data for 4.0.

Current:
```
message NewEvent {
	required bytes event_id = 1;
	required string event_type = 2;
	required int32 data_content_type = 3;
	required int32 metadata_content_type = 4;
	required bytes data = 5;
	optional bytes metadata = 6;
}
```
Proposed (being backward compatible):
```
message NewEvent {
	required bytes event_id = 1;
	required string event_type = 2;
	required int32 data_content_type = 3;
	required int32 metadata_content_type = 4;
	required bytes data = 5;
	optional bytes metadata = 6;
	optional string data_mime_type = 7;
	optional string metadata_mime_type = 8;
}
```
When the user wants to to deserialize the data for example, he can choose the appropriate deserializer by using the information from the dataContentType or metaContentType.

Of course I can put all this stuff into the meta data, but then I need to assume a fixed format (JSON, XML) for the meta content. I think having a mime-type string that describes what is inside the byte array and how it's encoded feels much more natural for both data blocks (data & meta).

See also this [issue](https://github.com/jen20/EventStore.Java/issues/5) for discussion with James.

**Comment by gregoryyoung** [comment]
Is there an actual need to have arbitrary formatted metadata? I'd be
interested in that use case.

On Saturday, May 30, 2015, Michael Schnell <notifications@github.com> wrote:

> It would be nice to have real mime types stored for data and meta data for
> 4.0.
>
> Current:
>
> message NewEvent {
>     required bytes event_id = 1;
>     required string event_type = 2;
>     required int32 data_content_type = 3;
>     required int32 metadata_content_type = 4;
>     required bytes data = 5;
>     optional bytes metadata = 6;
> }
>
> Proposed (being backward compatible):
>
> message NewEvent {
>     required bytes event_id = 1;
>     required string event_type = 2;
>     required int32 data_content_type = 3;
>     required int32 metadata_content_type = 4;
>     required bytes data = 5;
>     optional bytes metadata = 6;
>     optional string data_mime_type = 7;
>     optional string metadata_mime_type = 8;
> }
>
> When the user wants to to deserialize the data for example, he can choose
> the appropriate deserializer by using the information from the
> dataContentType or metaContentType.
>
> Of course I can put all this stuff into the meta data, but then I need to
> assume a fixed format (JSON, XML) for the meta content. I think having a
> mime-type string that describes what is inside the byte array and how it's
> encoded feels much more natural for both data blocks (data & meta).
>
> See also this issue <https://github.com/jen20/EventStore.Java/issues/5>
> for discussion with James.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/493>.
>


-- 
Studying for the Turing test

**Comment by michael-schnell** [comment]
I'm currently creating library for Java that hides the concrete event store implementation (See [planned architecture](https://raw.githubusercontent.com/fuinorg/event-store-commons/master/doc/event-store-commons.png)). I want to allow customers to choose different event store implementations based on their needs. 

Large companies in general have a high entry barrier regarding new technologies and I want to open this way a path for CQRS solutions using the EventStore: Simply switch from Oracle to EventStore by changing the implementation.

If they don't need highest performance and want to start with their standard relational DB architecture, they can for example use an implementation based on JPA & Oracle (or PostgreSQL). For higher performance a better choice might be the EventStore. 

And finally there will be a kind of "compliance test" that verifies all implementations behave the same way. At the moment there is only a single [cucumber example](https://github.com/fuinorg/event-store-commons/blob/master/test/src/test/resources/features/basic.feature) how it may look like. There are also some performance tests planned comparing the implementations (some nice bar charts). 

*Back to the problem*

While implementing the SPI for the EventStore, I faced that storing the mime type in the meta data makes the code unnecessarily complicated and I need to make some strange assumptions to get it done. This is mainly because:
- I need to assume a format (XML, JSON, Text (key=value), ...) for deserializing the meta content
- The meta data mixes now user provided content like ```{ "ip" : "127.0.0.1", "user" : "peter" }``` with the content provided by the SPI classes (like ```"mime-type":"application/json; encoding=utf-8;"```  Even worse, I learned from James you also need to do stuff with the meta data internally in the event store...

Sounds to me like there is space for improving the EventStore architecture and giving the full format choice for both data & meta back to the user. All internal processing (Projections, ...) can use the "mime_type" to choose wether to process the data/meta content or not.

**Comment by gregoryyoung** [comment]
I agree it makes sense there is just a whole lot more work than just
changing out the message for client api. As an example how should this work
over http?

On Sunday, May 31, 2015, Michael Schnell <notifications@github.com> wrote:

> I'm currently creating library for Java that hides the concrete event
> store implementation (See planned architecture
> <https://raw.githubusercontent.com/fuinorg/event-store-commons/master/doc/event-store-commons.png>).
> I want to allow customers to choose different event store implementations
> based on their needs.
>
> Large companies in general have a high entry barrier regarding new
> technologies and I want to open this way a path for CQRS solutions using
> the EventStore: Simply switch from Oracle to EventStore by changing the
> implementation.
>
> If they don't need highest performance and want to start with their
> standard relational DB architecture, they can for example use an
> implementation based on JPA & Oracle (or PostgreSQL). For higher
> performance a better choice might be the EventStore.
>
> And finally there will be a kind of "compliance test" that verifies all
> implementations behave the same way. At the moment there is only a single cucumber
> example
> <https://github.com/fuinorg/event-store-commons/blob/master/test/src/test/resources/features/basic.feature>
> how it may look like. There are also some performance tests planned
> comparing the implementations (some nice bar charts).
>
> *Back to the problem*
>
> While implementing the SPI for the EventStore, I faced that storing the
> mime type in the meta data makes the code unnecessarily complicated and I
> need to make some strange assumptions to get it done. This is mainly
> because:
>
>    - I need to assume a format (XML, JSON, Text (key=value), ...) for
>    deserializing the meta content
>    - The meta data mixes now user provided content like { "ip" :
>    "127.0.0.1", "user" : "peter" } with the content provided by the SPI
>    classes (like "mime-type":"application/json; encoding=utf-8;" Even
>    worse, I learned from James you also need to do stuff with the meta data
>    internally in the event store...
>
> Sounds to me like there is space for improving the EventStore architecture
> and giving the full format choice for both data & meta back to the user.
> All internal processing (Projections, ...) can use the "mime_type" to
> choose wether to process the data/meta content or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/493#issuecomment-107133314>
> .
>


-- 
Studying for the Turing test

**Comment by michael-schnell** [comment]
I must admit I don't know anything about the event store internal - But for HTTP it seems a very natural enhancement:

Current (from doc [example](http://docs.geteventstore.com/http-api/3.0.3/writing-to-a-stream/)):
```xml
<Events>
  <Event>
    <EventId>fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4</EventId>
    <EventType>event-type</EventType>
    <Data>
      <MyEvent>
        <Something>1</Something>
      </MyEvent>
    </Data>
  </Event>
</Events>
```
Would be something like:
```xml
<Events>
  <Event>
    <EventId>fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4</EventId>
    <EventType>event-type</EventType>
    <DataMimeType>application/xml; encoding=utf-8"</DataMimeType>
    <Data>
      <![CDATA[
      <MyEvent>
        <Something>1</Something>
      </MyEvent>
      ]]>
    </Data>
    <MetaDataMimeType>application/json; encoding=encoding= iso-8859-1"</MetaDataMimeType>
    <MetaData>
      <![CDATA[
          { "ip" : "127.0.0.1", "user" : "peter", "whatever":"Some umlauts: ÄÖÜäöüß" }
      ]]>
    </MetaData>
  </Event>
</Events>
```
Could could even do something more sophisticated:
```xml
<Events>
  <Event>
    <EventId>fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4</EventId>
    <EventType>event-type</EventType>
<DataMimeType>application/my.app.encrypted; transfer-encoding="base64"; algorithm="RSA/AES" key="peter.parker" content="application/xml"; encoding="utf-8"</DataMimeType>
<Data>
MIAGCSqGSIb3DQEHA6CAMIACAQAxgewwgekCAQAwUjBFMQswCQYDVQQGEwJBVTETMBEGA1UECBMK
U29tZS1TdGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkAgkA7oW81OriflAw
DQYJKoZIhvcNAQEBBQAEgYCfnqPK/O34DFl2p2zm+xZQ6R+94BqZHdtEWQN2evrcgtAng+f2ltIL
xr/PiK+8bE8wDO5GuCg+k92uYp2rLKlZ5BxCGb8tRM4kYC9sHbH2dPaqzUBhMxjgWdMCX6Q7E130
u9MdGcP74Ogwj8fNl3lD4sx/0k02/QwgaukeY7uNHzCABgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcE
CDRozFLsPnSgoIAEQHmqjSKAWlQbuGQL9w4nKw4l+44WgTjKf7mGWZvYY8tOCcdmhDxRSM1Ly682
Imt+LTZf0LXzuFGTsCGOUo742N8AAAAAAAAAAAAA
</Data>
    <MetaDataMimeType>application/json; encoding=encoding= iso-8859-1"</MetaDataMimeType>
    <MetaData>
      <![CDATA[
          { "ip" : "127.0.0.1", "user" : "peter", "whatever":"Some umlauts: ÄÖÜäöüß" }
      ]]>
    </MetaData>
  </Event>
</Events>
```

**Comment by gregoryyoung** [comment]
There is a whole lot more to it than this.

On Sunday, May 31, 2015, Michael Schnell <notifications@github.com> wrote:

> I must admit I don't know anything about the event store internal - But
> for HTTP it seems a very natural enhancement:
>
> Current (from doc example
> <http://docs.geteventstore.com/http-api/3.0.3/writing-to-a-stream/>):
>
> <Events>
>   <Event>
>     <EventId>fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4</EventId>
>     <EventType>event-type</EventType>
>     <Data>
>       <MyEvent>
>         <Something>1</Something>
>       </MyEvent>
>     </Data>
>   </Event>
> </Events>
>
> Would be something like:
>
> <Events>
>   <Event>
>     <EventId>fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4</EventId>
>     <EventType>event-type</EventType>
>     <DataMimeType>application/xml; encoding=utf-8"</DataMimeType>
>     <Data>
>       <![CDATA[      <MyEvent>        <Something>1</Something>      </MyEvent>      ]]>
>     </Data>
>     <MetaDataMimeType>application/json; encoding=encoding= iso-8859-1"</MetaDataMimeType>
>     <MetaData>
>       <![CDATA[          { "ip" : "127.0.0.1", "user" : "peter", "whatever":"Some umlauts: ÄÖÜäöüß" }      ]]>
>     </MetaData>
>   </Event>
> </Events>
>
> Could could even do something more sophisticated:
>
> <Events>
>   <Event>
>     <EventId>fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4</EventId>
>     <EventType>event-type</EventType>
> <DataMimeType>application/my.app.encrypted; transfer-encoding="base64"; algorithm="RSA/AES" key="peter.parker" content="application/xml"; encoding="utf-8"</DataMimeType>
> <Data>
> MIAGCSqGSIb3DQEHA6CAMIACAQAxgewwgekCAQAwUjBFMQswCQYDVQQGEwJBVTETMBEGA1UECBMK
> U29tZS1TdGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkAgkA7oW81OriflAw
> DQYJKoZIhvcNAQEBBQAEgYCfnqPK/O34DFl2p2zm+xZQ6R+94BqZHdtEWQN2evrcgtAng+f2ltIL
> xr/PiK+8bE8wDO5GuCg+k92uYp2rLKlZ5BxCGb8tRM4kYC9sHbH2dPaqzUBhMxjgWdMCX6Q7E130
> u9MdGcP74Ogwj8fNl3lD4sx/0k02/QwgaukeY7uNHzCABgkqhkiG9w0BBwEwFAYIKoZIhvcNAwcE
> CDRozFLsPnSgoIAEQHmqjSKAWlQbuGQL9w4nKw4l+44WgTjKf7mGWZvYY8tOCcdmhDxRSM1Ly682
> Imt+LTZf0LXzuFGTsCGOUo742N8AAAAAAAAAAAAA
> </Data>
>     <MetaDataMimeType>application/json; encoding=encoding= iso-8859-1"</MetaDataMimeType>
>     <MetaData>
>       <![CDATA[          { "ip" : "127.0.0.1", "user" : "peter", "whatever":"Some umlauts: ÄÖÜäöüß" }      ]]>
>     </MetaData>
>   </Event>
> </Events>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/493#issuecomment-107146153>
> .
>


-- 
Studying for the Turing test

**Comment by michael-schnell** [comment]
As said - I don't know how the event store works internally and what would be affected by such a change... From a user's perspective it allows much more flexibility.

**Comment by gregoryyoung** [comment]
What makes me hesitant is that no one else has ever wanted such a this and
it sounds like frameworky stuff. There is actually a huge amount of work
required with such a change. Also how do you make it backwards compatible?
Eg for an old event that doesn't have it set what is the content type? I'm
assuming you would also want some ability to override this default...

The other part you are missing is that http currently handles translating
between content types. Eg post in xml then ask for content in json. The
other problem with this is that you pass a single content type over http
for both metadata and data. If they are being stored in two content types
wouldn't you want to pass two content types one for data and one for
metadata? So do we now leave http content type negotiation and build our
own?

At the end of the day almost everyone uses json. Why? Because that's all
projections understands. I'm hesitant to get involved with what is likely a
1-2 month project that basically no one will use.

Greg

On Sunday, May 31, 2015, Michael Schnell <notifications@github.com> wrote:

> As said - I don't know how the event store works internally and what would
> be affected by such a change... From a user's perspective it allows much
> more flexibility.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/493#issuecomment-107146352>
> .
>


-- 
Studying for the Turing test

**Comment by michael-schnell** [comment]
> What makes me hesitant is that no one else has ever wanted such this

I cannot judge about this. New possibilities (features) may attract new user groups.

> Also how do you make it backwards compatible?
> Eg for an old event that doesn't have it set what is the content type? 
> I'm assuming you would also want some ability to override this default...

I think this one is easy - Either the new fields are filled or not. You still have the old backward compatible "int" flag for "json". If it's not JSON format the user should be able to tell what and how he stored the content.

> The other part you are missing is that http currently handles translating between content types. 
> Eg post in xml then ask for content in json. 

I don't know how this is handled in C#, but in Java it's just switching between two serializers/deserializers. This should also get easier if you distinguish clearly between user content and event store stuff.

> The other problem with this is that you pass a single content type over http for both metadata and data. 

From my point of view this is part of the problem. Because you mix up the format of the event store (application/vnd.eventstore.events+json) and the format of the user content. So the HTTP content-type should actually describe how the event store data is encoded and what type is is.

That's why in my example the content is inside a "CDATA" section. Everything inside is user content and it's described by the meta data.
```xml
<![CDATA[
    <MyEvent><Something>1</Something></MyEvent>
]]>
```
If you use pure XML, there would be two different namespaces for the Event Store XML and the user's XML to make sure they are not mixed up. 

So either you go for "Only use JSON (and a little bit of XML)" (which is a valid option) or you want to support multiple formats. In the latter case I think there are some flaws in the current design that should be fixed to properly support multiple formats.

**Comment by gregoryyoung** [comment]
On Sunday, May 31, 2015, Michael Schnell <notifications@github.com> wrote:

> What makes me hesitant is that no one else has ever wanted such this
>
> I cannot judge about this. New possibilities (features) may attract new
> user groups.
>

I don't buy it.


>  Also how do you make it backwards compatible?
> Eg for an old event that doesn't have it set what is the content type?
> I'm assuming you would also want some ability to override this default...
>
> I think this one is easy - Either the new fields are filled or not. You
> still have the old backward compatible "int" flag for "json". If it's not
> JSON format the user should be able to tell what and how he stored the
> content.
>

Ok so how do you set that? Note the feature explosion happening here. Is it
per stream? Multi-level like acls? Just saying "yes the user should be able
to say what the content type of previous events was" hides at least 1-2
weeks of work.



>  The other part you are missing is that http currently handles
> translating between content types.
> Eg post in xml then ask for content in json.
>
> I don't know how this is handled in C#, but in Java it's just switching
> between two serializers/deserializers. This should also get easier if you
> distinguish clearly between user content and event store stuff.
>

It's not so simple in Java either. Read below I think you are missing some
pretty major points of functionality.



>  The other problem with this is that you pass a single content type over
> http for both metadata and data.
>
> From my point of view this is part of the problem. Because you mix up the
> format of the event store (application/vnd.eventstore.events+json) and the
> format of the user content. So the HTTP content-type should actually
> describe how the event store data is encoded and what type is is.
>
> That's why in my example the content is inside a "CDATA" section.
> Everything inside is user content and it's described by the meta data.
>
> <![CDATA[    <MyEvent><Something>1</Something></MyEvent>]]>
>
> If you use pure XML, there would be two different namespaces for the Event
> Store XML and the user's XML to make sure they are not mixed up.
>
> So either you go for "Only use JSON (and a little bit of XML)" (which is a
> valid option) or you want to support multiple formats. In the latter case I
> think there are some flaws in the current design that should be fixed to
> properly support multiple formats.
>

I understand that I can put xml in json and vice versa. You are not
understanding some major points here. Try this. Post content type xml the
do a get accept content type json. Note that your data!!! is converted from
xml to json automatically it's not just our object that's serialized.





> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/493#issuecomment-107150815>
> .
>


-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Looking more into this I'm just going to close this as "won't do"

Other things set in metadata that we understand (acls tb max count max age
etc) all need to be in json anyways. Right now the only assumption is that
metadata is in the same format as the event so the only people who wouldn't
be supported are people who want metadata in xml and data in protobufs but
then at other random times they put metadata in protobufs and data in json.
I don't believe these people exist, beyond that I think it's a bad idea to
support this kind of derpy situation and would instead tell people "don't
do that its accidental complexity just for the sake of accidental
complexity". Doing the change makes quite a few oddities and is of little
value. You can trivially support such things on top... Just store as xml
<content Type>what Everyone</content Type>then cdata whatever.



On Sunday, May 31, 2015, Greg Young <gregoryyoung1@gmail.com> wrote:

>
>
> On Sunday, May 31, 2015, Michael Schnell <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> What makes me hesitant is that no one else has ever wanted such this
>>
>> I cannot judge about this. New possibilities (features) may attract new
>> user groups.
>>
>
> I don't buy it.
>
>
>>  Also how do you make it backwards compatible?
>> Eg for an old event that doesn't have it set what is the content type?
>> I'm assuming you would also want some ability to override this default...
>>
>> I think this one is easy - Either the new fields are filled or not. You
>> still have the old backward compatible "int" flag for "json". If it's not
>> JSON format the user should be able to tell what and how he stored the
>> content.
>>
>
> Ok so how do you set that? Note the feature explosion happening here. Is
> it per stream? Multi-level like acls? Just saying "yes the user should be
> able to say what the content type of previous events was" hides at least
> 1-2 weeks of work.
>
>
>
>>  The other part you are missing is that http currently handles
>> translating between content types.
>> Eg post in xml then ask for content in json.
>>
>> I don't know how this is handled in C#, but in Java it's just switching
>> between two serializers/deserializers. This should also get easier if you
>> distinguish clearly between user content and event store stuff.
>>
>
> It's not so simple in Java either. Read below I think you are missing some
> pretty major points of functionality.
>
>
>
>>  The other problem with this is that you pass a single content type over
>> http for both metadata and data.
>>
>> From my point of view this is part of the problem. Because you mix up the
>> format of the event store (application/vnd.eventstore.events+json) and the
>> format of the user content. So the HTTP content-type should actually
>> describe how the event store data is encoded and what type is is.
>>
>> That's why in my example the content is inside a "CDATA" section.
>> Everything inside is user content and it's described by the meta data.
>>
>> <![CDATA[    <MyEvent><Something>1</Something></MyEvent>]]>
>>
>> If you use pure XML, there would be two different namespaces for the
>> Event Store XML and the user's XML to make sure they are not mixed up.
>>
>> So either you go for "Only use JSON (and a little bit of XML)" (which is
>> a valid option) or you want to support multiple formats. In the latter case
>> I think there are some flaws in the current design that should be fixed to
>> properly support multiple formats.
>>
>
> I understand that I can put xml in json and vice versa. You are not
> understanding some major points here. Try this. Post content type xml the
> do a get accept content type json. Note that your data!!! is converted from
> xml to json automatically it's not just our object that's serialized.
>
>
>
>
>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/493#issuecomment-107150815>
>> .
>>
>
>
> --
> Studying for the Turing test
>
>

-- 
Studying for the Turing test

**Comment by michael-schnell** [comment]
> Right now the only assumption is that metadata is in the same format as the event

Hmmm... What is the ```required int32 metadata_content_type = 4;``` then good for? I think at least there is a mismatch between HTTP and PROTOBUF format...

At the end it's OK for me if you say doing the change makes quite a few oddities and is of little
value for the majority of users. Just wanted to discuss this. As I have a workaround in place (fixed meta data content type with only XML or JSON allowed) we can close this.

**Comment by gregoryyoung** [comment]
Just store content type and metadata in metadata. How would that differ?

If you look content type is a place holder it doesn't really do stuff

On Sunday, May 31, 2015, Michael Schnell <notifications@github.com> wrote:

> Right now the only assumption is that metadata is in the same format as
> the event
>
> Hmmm... What is the required int32 metadata_content_type = 4; then good
> for? I think at least there is a mismatch between HTTP and PROTOBUF
> format...
>
> At the end it's OK for me if you say doing the change makes quite a few
> oddities and is of little
> value for the majority of users. Just wanted to discuss this. As I have a
> workaround in place (fixed meta data content type with only XML or JSON
> allowed) we can close this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/493#issuecomment-107161119>
> .
>


-- 
Studying for the Turing test
