### ISSUE TITLE
Projections ClientAPI (map to objects)

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#494]
As of now the read methods are all returning string e.g.

public Task<string> ListAllAsync(UserCredentials userCredentials = null)

These should return objects as opposed to strings filled with JSON.

As projections are in beta no worries on breaking change.

Basically the change is just going through and doing the same thing the users manager does where it maps the json back to objects before returning it. This makes for an overall nicer and more discoverable API

**Comment by riccardone** [comment]
start working on this

**Comment by gregoryyoung** [comment]
:+1: thanks for claiming it.

On Wednesday, September 2, 2015, Riccardo Di Nuzzo <notifications@github.com>
wrote:

> start working on this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/494#issuecomment-137204393>
> .
>


-- 
Studying for the Turing test

**Comment by riccardone** [comment]
Do you want ...Url fields represented as Uri? (or just string)

**Comment by gregoryyoung** [comment]
I think URI would make more sense.

On Thu, Sep 3, 2015 at 2:01 PM, Riccardo Di Nuzzo <notifications@github.com>
wrote:

> Do you want ...Url fields represented as Uri? (or just string)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/494#issuecomment-137417363>
> .
>



-- 
Studying for the Turing test
