### ISSUE TITLE
Support v2 unaligned files

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#497]
As of now there is a breaking change in dev dealing with unbuffered io. In order to use unbuffered io tfchunks must be of an aligned size. At present files are an unaligned size.

As of now what happens is the system will upgrade the chunks to be aligned when it starts up. 

The only time aligned is needed is if you are running with unbuffered io. This should be an opt in thing perhaps at which point alignments are made? There is some tricky logic in quite a few places though as we check file sizes etc.

**Comment by jen20** [comment]
Yes we should probably make this opt-in - potentially remove the upgrade process out into a separate utility and fail on unbuffered if it hasn't already run?

**Comment by gregoryyoung** [comment]
There are at least 20 other places there will be varying logic

On Monday, June 1, 2015, James Nugent <notifications@github.com> wrote:

> Yes we should probably make this opt-in - potentially remove the upgrade
> process out into a separate utility and fail on unbuffered if it hasn't
> already run?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/497#issuecomment-107626637>
> .
>


-- 
Studying for the Turing test

**Comment by pgermishuys** [comment]
This work was completed as part of the unbuffered PR #1146
