### ISSUE TITLE
Enable Projection Endpoint Shouldn't Require Data to Be Posted to It

### ISSUE THREAD

**Issue by sbellware** [EventStore/EventStore#502]
The enable projection end point requires data to be posted to it, but the data (the projection name) is already represented in the URI.

The API doesn't really appear to need the data to be sent. It should likely be a post to the URI without a data payload.

Example:

## Is Now

```
name=%24by_category
curl -i -X POST -d '{"msgTypeId":251,"name":"${name}"}' http://127.0.0.1:2113/projection/${name}/command/enable -u admin:changeit
```

## Maybe Should Be

```
name=%24by_category
curl -i -X POST -d '' http://127.0.0.1:2113/projection/${name}/command/enable -u admin:changeit
```

**Comment by pgermishuys** [comment]
The API currently doesn't expect any additional information to be passed.

https://github.com/EventStore/EventStore/blob/dev/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs#L188-L207

![image](https://cloud.githubusercontent.com/assets/1062417/8103908/b802c96c-102c-11e5-9102-6a7f84452ffc.png)
