### ISSUE TITLE
Error while wrapping message EventStore.Core.Messages.ClientMessage+ReadAllEventsForwardCompleted

### ISSUE THREAD

**Issue by dnauck** [EventStore/EventStore#503]
Using EventStore 3.0.5 with the latest client lib from NuGet and get the following error message on a CatchUp Subscription in the ```$all``` stream using the ```SubscribeToAllFrom()``` method:

```
[PID:03564:014 2015.06.05 08:43:05.822 ERROR TcpDispatcher       ] Error while wrapping message EventStore.Core.Messages.ClientMessage+ReadAllEventsForwardCompleted.
System.NullReferenceException: Object reference not set to an instance of an object.
   at EventStore.Core.Messages.TcpClientMessageDto.EventRecord..ctor(EventRecord eventRecord) in c:\EventStore\src\EventStore.Core\Messages\TcpClientMessageDtoExtensions.cs:line 30
   at EventStore.Core.Messages.TcpClientMessageDto.ResolvedEvent..ctor(ResolvedEvent pair) in c:\EventStore\src\EventStore.Core\Messages\TcpClientMessageDtoExtensions.cs:line 19
   at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.ConvertToResolvedEvents(ResolvedEvent[] events) in c:\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 391
   at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.WrapReadAllEventsForwardCompleted(ReadAllEventsForwardCompleted msg) in c:\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 361
   at EventStore.Core.Services.Transport.Tcp.TcpDispatcher.WrapMessage(Message message) in c:\EventStore\src\EventStore.Core\Services\Transport\Tcp\TcpDispatcher.cs:line 64
```

Restarting the subscription again results in the same error message.

The subscription was working for the first 100.000 events and then stopped working with this error message.

**Comment by gregoryyoung** [comment]
https://github.com/EventStore/EventStore/blob/dev/src/EventStore.Core/Messages/TcpClientMessageDtoExtensions.cs#L30

I am guessing since you know where the subscription is (you have a
checkpoint) you can look what the data in the event in question is? What is
"missing" off the event? From looking these are things that should be there
but maybe there is some place we allowed the writing of bad data?

On Fri, Jun 5, 2015 at 12:47 PM, Daniel Nauck <notifications@github.com>
wrote:

> Using EventStore 3.0.5 with the latest client lib from NuGet and get the
> following error message on a CatchUp Subscription in the $all stream
> using the SubscribeToAllFrom() method:
>
> [PID:03564:014 2015.06.05 08:43:05.822 ERROR TcpDispatcher       ] Error while wrapping message EventStore.Core.Messages.ClientMessage+ReadAllEventsForwardCompleted.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at EventStore.Core.Messages.TcpClientMessageDto.EventRecord..ctor(EventRecord eventRecord) in c:\EventStore\src\EventStore.Core\Messages\TcpClientMessageDtoExtensions.cs:line 30
>    at EventStore.Core.Messages.TcpClientMessageDto.ResolvedEvent..ctor(ResolvedEvent pair) in c:\EventStore\src\EventStore.Core\Messages\TcpClientMessageDtoExtensions.cs:line 19
>    at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.ConvertToResolvedEvents(ResolvedEvent[] events) in c:\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 391
>    at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.WrapReadAllEventsForwardCompleted(ReadAllEventsForwardCompleted msg) in c:\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 361
>    at EventStore.Core.Services.Transport.Tcp.TcpDispatcher.WrapMessage(Message message) in c:\EventStore\src\EventStore.Core\Services\Transport\Tcp\TcpDispatcher.cs:line 64
>
> Restarting the subscription again results in the same error message.
>
> The subscription was working for the first 100.000 events and then stopped
> working with this error message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/503>.
>



-- 
Studying for the Turing test

**Comment by dnauck** [comment]
The error of the client is:

```
2015-06-05 12:37:53.0145 DNA-DEV-WIN8 [ERROR] EventStoreConnection[7]: EventStoreConnection 'ES-c570d121-ed5f-445e-84ce-7ccfabc21b30': operation never got response from server.
UTC now: 10:37:53.011, operation: Operation ReadAllEventsForwardOperation ({7bb0be0d-1cfa-4201-8be3-2f4f1c737912}): Position: 641363/641363, MaxCount: 500, ResolveLinkTos: True, RequireMaster: True, retry count: 0, created: 10:37:45.055, last updated: 10:37:45.055. 
```

So it is at Position: 641363/641363? How do i get the event at this position? Via WebUI ?

**Comment by gregoryyoung** [comment]
Thats one way ... try browsing to $all and you can see how the uris work.

If not we have other tools that can look at the data.

On Fri, Jun 5, 2015 at 4:08 PM, Daniel Nauck <notifications@github.com>
wrote:

> The error of the client is:
>
> 2015-06-05 12:37:53.0145 DNA-DEV-WIN8 [ERROR] EventStoreConnection[7]: EventStoreConnection 'ES-c570d121-ed5f-445e-84ce-7ccfabc21b30': operation never got response from server.
> UTC now: 10:37:53.011, operation: Operation ReadAllEventsForwardOperation ({7bb0be0d-1cfa-4201-8be3-2f4f1c737912}): Position: 641363/641363, MaxCount: 500, ResolveLinkTos: True, RequireMaster: True, retry count: 0, created: 10:37:45.055, last updated: 10:37:45.055.
>
> So it is at Position: 641363/641363? How do i get the event at this
> position? Via WebUI ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/503#issuecomment-109288841>
> .
>



-- 
Studying for the Turing test

**Comment by dnauck** [comment]
Hi,

browsing the $all stream in the browser has the following result:

```json
{
"title": "All events",
"id": "http://localhost:2113/streams/%24all",
"updated": "2015-06-08T07:24:14.9964346Z",
"author": {
"name": "EventStore"
},
"headOfStream": false,
"links": [
{
"uri": "http://localhost:2113/streams/%24all",
"relation": "self"
},
{
"uri": "http://localhost:2113/streams/%24all/head/backward/20",
"relation": "first"
},
{
"uri": "http://localhost:2113/streams/%24all/00000000000000000000000000000000/forward/20",
"relation": "last"
},
{
"uri": "http://localhost:2113/streams/%24all/0000000A569BB6EB0000000A569BB6EB/backward/20",
"relation": "next"
},
{
"uri": "http://localhost:2113/streams/%24all/0000000A56A048AC0000000A56A048AC/forward/20",
"relation": "previous"
},
{
"uri": "http://localhost:2113/streams/%24all/metadata",
"relation": "metadata"
}
],
"entries": [
{
"title": "3590@$stats-127.0.0.1:2113",
"id": "http://localhost:2113/streams/%24stats-127.0.0.1%3A2113/3590",
"updated": "2015-06-08T07:24:14.9964346Z",
"author": {
"name": "EventStore"
},
"summary": "$statsCollected",
"links": [
{
"uri": "http://localhost:2113/streams/%24stats-127.0.0.1%3A2113/3590",
"relation": "edit"
},
{
"uri": "http://localhost:2113/streams/%24stats-127.0.0.1%3A2113/3590",
"relation": "alternate"
}
]
},
...
```

Its not really clear how do i access that single event that caused the crash. Even the event entry does not contain prepare and commit position. Only the original stream and event number in the original stream.

**Comment by gregoryyoung** [comment]
UTC now: 10:37:53.011, operation: Operation
ReadAllEventsForwardOperation
({7bb0be0d-1cfa-4201-8be3-2f4f1c737912}): Position: 641363/641363,
MaxCount: 500, ResolveLinkTos: True, RequireMaster: True, retry count:
0, created: 10:37:45.055, last updated: 10:37:45.055.



Includes it "Position: 641363/641363" the event with an error is in that
read just not sure which one

Cheers,

Greg

On Mon, Jun 8, 2015 at 9:31 AM, Daniel Nauck <notifications@github.com>
wrote:

> Hi,
>
> browsing the $all stream in the browser has the following result:
>
> {"title": "All events","id": "http://localhost:2113/streams/%24all","updated": "2015-06-08T07:24:14.9964346Z","author": {"name": "EventStore"
> },"headOfStream": false,"links": [
> {"uri": "http://localhost:2113/streams/%24all","relation": "self"
> },
> {"uri": "http://localhost:2113/streams/%24all/head/backward/20","relation": "first"
> },
> {"uri": "http://localhost:2113/streams/%24all/00000000000000000000000000000000/forward/20","relation": "last"
> },
> {"uri": "http://localhost:2113/streams/%24all/0000000A569BB6EB0000000A569BB6EB/backward/20","relation": "next"
> },
> {"uri": "http://localhost:2113/streams/%24all/0000000A56A048AC0000000A56A048AC/forward/20","relation": "previous"
> },
> {"uri": "http://localhost:2113/streams/%24all/metadata","relation": "metadata"
> }
> ],"entries": [
> {"title": "3590@$stats-127.0.0.1:2113","id": "http://localhost:2113/streams/%24stats-127.0.0.1%3A2113/3590","updated": "2015-06-08T07:24:14.9964346Z","author": {"name": "EventStore"
> },"summary": "$statsCollected","links": [
> {"uri": "http://localhost:2113/streams/%24stats-127.0.0.1%3A2113/3590","relation": "edit"
> },
> {"uri": "http://localhost:2113/streams/%24stats-127.0.0.1%3A2113/3590","relation": "alternate"
> }
> ]
> },...
>
> Its not really clear how do i access that single event that caused the
> crash. Even the event entry does not contain prepare and commit position.
> Only the original stream and event number in the original stream.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/503#issuecomment-109891072>
> .
>



-- 
Studying for the Turing test

**Comment by dnauck** [comment]
Hi,

maybe my question was a bit unclear: i know that position due the error message you quoted. But how to i access that event directly (via browser?) without using the ```TcpClientMessageDto``` stuff to see its content and metadata.

**Comment by gregoryyoung** [comment]
http://localhost:2113/streams/%24all/0000000A569BB6EB0000000A569BB6EB/backward/20


Those hex numbers are the numbers you see in the above message. It
then gives you links directly to what the events are. Basically need
to find if there is something odd about one of the events in the read.
I can also send up something that includes debug code if you prefer
that.


On Mon, Jun 8, 2015 at 9:49 AM, Daniel Nauck <notifications@github.com>
wrote:

> Hi,
>
> maybe my question was a bit unclear: i know that position due the error
> message you quoted. But how to i access that event directly (via browser?)
> without using the TcpClientMessageDto stuff to see its content and
> metadata.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/503#issuecomment-109894681>
> .
>



-- 
Studying for the Turing test

**Comment by dnauck** [comment]
Send you a private email with the data of the event. 

I don't see any bad data there. All events in this database was written with the .NET 2.0.1 client using the old "https://github.com/EventStore/getting-started-with-event-store“ code.

**Comment by dnauck** [comment]
I debugged the eventstore 3.0.5 tag a bit in my visual studio.

During this failure the ```eventRecord``` parameter is null: https://github.com/EventStore/EventStore/blob/dev/src/EventStore.Core/Messages/TcpClientMessageDtoExtensions.cs#L30

Because its a linked event (stats-collected..), this code here fails: https://github.com/EventStore/EventStore/blob/release-v3.0.4/src/EventStore.Core/Messages/TcpClientMessageDtoExtensions.cs#L20

In the ```dev```branch is a fix for that afaik.

**Comment by dnauck** [comment]
The fix from ```dev``` will prevent the NRE but then the subscription stops to receive events without any error message.

The Data of the ```Data.ResolvedEvent pair``` in https://github.com/EventStore/EventStore/blob/release-v3.0.4/src/EventStore.Core/Messages/TcpClientMessageDtoExtensions.cs#L20 is the following:

* Event: null
* Link & OriginalEvent: 
 * CorrelationId: UUID
 * Data: byte[24]
 * DebugDataView: 0@stats-ipaddress:2113
 * EventNumber: 0
 * EventStreamId: $et-$stats-Collected
 * EventType: $>
 * ExpectedVersion: -1
 * Flags: Data | TransactionBegin | IsJson
 * LogPosition: 723837
 * TimeStamp: 10.12.2013 12:21:59
* OriginalEventNumber: 0
* OriginalPosition: C:733088/P:723837
* OriginalStreamId: $et-$stats-Collected
* ResolveResult: NotFound

**Comment by gregoryyoung** [comment]
I will look into it.

On Wed, Jun 10, 2015 at 9:57 AM, Daniel Nauck <notifications@github.com>
wrote:

> The fix from dev will prevent the NRE but then the subscription stops to
> receive events without any error message.
>
> The Data of the Data.ResolvedEvent pair in
> https://github.com/EventStore/EventStore/blob/release-v3.0.4/src/EventStore.Core/Messages/TcpClientMessageDtoExtensions.cs#L20
> is the following:
>
>    - Event: null
>    - Link & OriginalEvent:
>       - CorrelationId: UUID
>       - Data: byte[24]
>       - DebugDataView: 0@stats-ipaddress:2113
>       - EventNumber: 0
>       - EventStreamId: $et-$stats-Collected
>       - EventType: $>
>       - ExpectedVersion: -1
>       - Flags: Data | TransactionBegin | IsJson
>       - LogPosition: 723837
>       - TimeStamp: 10.12.2013 12:21:59
>     - OriginalEventNumber: 0
>    - OriginalPosition: C:733088/P:723837
>    - OriginalStreamId: $et-$stats-Collected
>    - ResolveResult: NotFound
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/503#issuecomment-110642242>
> .
>



-- 
Studying for the Turing test

**Comment by dnauck** [comment]
@gregoryyoung anything i can do to help you debug that problem?

The fix in d7118022a9e8ad48b1d563dab7617a52963b35d4 should be back ported to the next release to prevent that NRE. I can send a pull request if you like.

But i don't know why it stops sending new events then.

**Comment by gregoryyoung** [comment]
It stops sending because the subscription has reached a point where it's in
error. It sends in order.

On Tuesday, June 16, 2015, Daniel Nauck <notifications@github.com> wrote:

> @gregoryyoung <https://github.com/gregoryyoung> anything i can do to help
> you debug that problem?
>
> The fix in d711802
> <https://github.com/EventStore/EventStore/commit/d7118022a9e8ad48b1d563dab7617a52963b35d4>
> should be back ported to the next release to prevent that NRE. I can send a
> pull request if you like.
>
> But i don't know why it stops sending new events then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/503#issuecomment-112294204>
> .
>


-- 
Studying for the Turing test

**Comment by dnauck** [comment]
Yes, aber after applying  patch d7118022a9e8ad48b1d563dab7617a52963b35d4 there is no exception anymore. It just stops sending (i think at the same event) but without any error message or exception.

You can point me to some key parts where i can add break point to debug further or i can send you the 2.0.1 database files privately if that helps.

**Comment by pgermishuys** [comment]
@dnauck I am going to close this issue due to it being resolved by https://github.com/EventStore/EventStore/commit/d7118022a9e8ad48b1d563dab7617a52963b35d4. If you are still having issues here, please reopen so that we can address them.
