### ISSUE TITLE
3.0.5 Web UI - Errors Galore

### ISSUE THREAD

**Issue by worldspawn** [EventStore/EventStore#508]
So I've unzipped the 3.0.5 zip and started it up with

`.\EventStore.ClusterNode.exe --db ./db --log ./logs --run-projections=all`

This is in Win 8 VM (2 cores, 8GB mem) in OSX with Parallels.

I've browsed to the admin ui @ http://127.0.0.1:2113/ and I'm just getting heaps of errors. Whole tabs dont work. Sometimes I just see 404s or what ever but they dont always break the UI.

Browsing with Chrome.

### http://127.0.0.1:2113/web/index.html#/streams
- GET http://127.0.0.1:2113/streams/$streams/head/50?embed=rich 404 (Not Found)

### http://127.0.0.1:2113/web/index.html#/projections
*This page does not work at all.*
```TypeError: Cannot read property 'slice' of undefined
    at i (http://127.0.0.1:2113/web/js/app.min.js:19:28733)
    at Object.n.resume (http://127.0.0.1:2113/web/js/app.min.js:19:28934)
    at Object.n.start (http://127.0.0.1:2113/web/js/app.min.js:19:28968)
    at new <anonymous> (http://127.0.0.1:2113/web/js/app.min.js:17:13055)
    at r (http://127.0.0.1:2113/web/js/app.min.js:1:17992)
    at Object.s [as instantiate] (http://127.0.0.1:2113/web/js/app.min.js:1:18084)
    at $get (http://127.0.0.1:2113/web/js/app.min.js:2:6867)
    at compile (http://127.0.0.1:2113/web/js/app.min.js:5:22264)
    at st (http://127.0.0.1:2113/web/js/app.min.js:2:3741)
    at C (http://127.0.0.1:2113/web/js/app.min.js:1:29827) <div ui-view="" class="ng-scope">```

### http://127.0.0.1:2113/web/index.html#/query
No idea what a valid query is but I tried:
```
fromAll()
.when({
    $init: function () {
        return { "bird": "the word" }
    }
})
```

I hit Run and got:
```
SyntaxError: Unexpected token *
    at Object.parse (native)
    at V (http://127.0.0.1:2113/web/js/app.min.js:1:4642)
    at sn (http://127.0.0.1:2113/web/js/app.min.js:2:7196)
    at http://127.0.0.1:2113/web/js/app.min.js:2:7623
    at s (http://127.0.0.1:2113/web/js/app.min.js:1:784)
    at cn (http://127.0.0.1:2113/web/js/app.min.js:2:7633)
    at r (http://127.0.0.1:2113/web/js/app.min.js:2:8213)
    at l (http://127.0.0.1:2113/web/js/app.min.js:2:26175)
    at http://127.0.0.1:2113/web/js/app.min.js:2:26347
    at f.$get.f.$eval (http://127.0.0.1:2113/web/js/app.min.js:3:1464)
```

### http://127.0.0.1:2113/web/index.html#/subscriptions
*This whole page does not work*
I get a red error toast on load and in the console:

```
GET http://127.0.0.1:2113/subscriptions 404 (Not Found)
```

All in all not exactly the product demo I was hoping for.

**Comment by ouro-ouroboros** [comment]
Let's rule out the obvious here: does the OS X build do the same?

(There are known issues with the UI in 3.0.5 though around projections, you can pull the latest UI from the repo at EventStore/EventStore.UI)

**Comment by pgermishuys** [comment]
Hi @worldspawn, as @ouro-ouroboros mentioned, there are known issues with the UI in 3.0.5. 

The issues have been addressed in the 3.0.6 branch (https://github.com/EventStore/EventStore.UI/tree/oss-v3.0.6).

You can replace your ui with the one from that branch..

**Comment by worldspawn** [comment]
Oh ok. Do I build/gulp/publish that and drop the output into ./clusternode-web?

**Comment by pgermishuys** [comment]
Yes,
Once you've cloned the UI repository and you are in the correct branch (3.0.6).

You can follow the "dev" steps in the README of the UI repository.

Once you have installed the dependencies, you should be able to perform a gulp dist. Which will produce an es-dist directory and this is what you can use to replace the clusternode-web directory.

I do apologize for any inconvenience caused.

Let us know if you come across any issues.

**Comment by worldspawn** [comment]
Great that worked. I can see projections now!

One more query if I could. I have enabled `$by_category` yet I get nothing (empty string) as the state of this projection. I have "Users" with stream names like "User-{guid}" and wanted to try a by category query.

My _understanding_ is it splits on hyphens in the stream name and creates a category named with the left side of the split. So I wrote this:
```
fromCategory('User')
.foreachStream()
    .when({
        $init: function() {
            return {
                count: 0
            };
        },
        $any: function(s, e) {
            s.count = s.count + 1;
            return s;
        }
    })
```

Yet I also get an empty string as its state. I wrote this as a query in the query tab of the UI which seems to just create transient projections. Any hints?

**Comment by pgermishuys** [comment]
Hi @worldspawn,
Your understanding about splitting the dashes into categories is correct.

Your particular projection would produce a state per stream. You need to query for the state per partition which would be something like this.

```
curl -i http://localhost:2113/projection/{{your-projection-name}}/state?partition=User-{{guid}}
```

The UI will not show the state of this projection as it's been split into partitions.
The following projection will however show the state in the UI.

![image](https://cloud.githubusercontent.com/assets/1062417/8248198/4abbc738-165c-11e5-806e-f5d29882be73.png)
