### ISSUE TITLE
Updating clusternode-web

### ISSUE THREAD

**Issue by GojiSoft** [EventStore/EventStore#509]
What is the workflow to update "clusternode-web" resources for instance in the dev branch. There's a number of bug fixes on EventStore.UI dev, and at the moment I'm building this (with gulp) and then copying it over to "clusternode-web".

**Comment by pgermishuys** [comment]
The workflow is described in the README. 

Once you have installed the dependencies, which is seems you have done.

You can perform a "gulp dist" which would produce a minified version of the UI. This can be found in the es-dist folder and the contents of that directory can be copied over the contents of the clusternode-web folder.

The current branch destined for release, which is where most of the fixes are going into for now is "oss-v3.0.6".

**Comment by GojiSoft** [comment]
Hi Pieter,

I have been using "gulp dist" to build the UI distribution and then copying
it into my cluster node build. I'd like to know what the workflow is to get
this into the EvenStore repo which comes with a ready-built distribution.
Do I build it and submit a pull request - this didn't seem quite right.

Thanks.

**Comment by pgermishuys** [comment]
We take care of this at the point of preparing for a release. What you have described is the workflow that we use however.
