### ISSUE TITLE
3.0.5 "Competing Consumers"

### ISSUE THREAD

**Issue by Gentlehag** [EventStore/EventStore#510]
After installing 3.0.5 there is a new tab "competing consumers" clicking it just ends up in a red error box ( even if the databse is newly created)

**Comment by gregoryyoung** [comment]
I believe this is just something in the UI that shouldn't be there.

@Pieter is this the case?

On Wed, Jun 10, 2015 at 2:14 PM, Boas Enkler <notifications@github.com>
wrote:

> After installing 3.0.5 there is a new tab "competing consumers" clicking
> it just ends up in a red error box ( even if the databse is newly created)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/510>.
>



-- 
Studying for the Turing test

**Comment by pgermishuys** [comment]
That is correct @gregoryyoung. This has been removed in the 3.0.6 branch in the ui repository.

**Comment by Gentlehag** [comment]
Just want to mention that this could be an awesome feature for me. Is it already planned for an version ? :)

**Comment by jbradford** [comment]
It's currently planned for 3.1.0, there are some early pieces of information available on the docs pages (http://docs.geteventstore.com/introduction/competing-consumers/).
