### ISSUE TITLE
Clusternode stat "proc-cpu" value

### ISSUE THREAD

**Issue by GojiSoft** [EventStore/EventStore#521]
The value for this stat is read from the performance counter "Process -> % Processor Time" and added to the cluster node stats as is. The value is notionally a percentage, but is not scaled to 100%, it is actually scaled to the number of logical processors. For example, if there are 8 logical processors the maximum value is 800% (ish). For monitoring purposes, it would be great if this value was scaled to 100%, or perhaps the number of logical processors could be included in the stats so that it could be scaled after elsewhere.

I'm happy to make either change and make a pull request, or any other suggestions. Scaling the value to 100% seems to make most sense upstream to monitoring tools??? 

Thanks.

**Comment by gregoryyoung** [comment]
Maybe including num CPUs instead of scaling?

On Tuesday, June 16, 2015, Tim Lloyd <notifications@github.com> wrote:

> The value for this stat is read from the performance counter "Process -> %
> Processor Time" and added to the cluster node stats as is. The value is
> notionally a percentage, but is not scaled to 100%, it is actually scaled
> to the number of logical processors. For example, if there are 8 logical
> processors the maximum value is 800% (ish). For monitoring purposes, it
> would be great if this value was scaled to 100%, or perhaps the number of
> logical processors could be included in the stats so that it could be
> scaled after elsewhere.
>
> I'm happy to make either change and make a pull request, or any other
> suggestions. Scaling the value to 100% seems to make most sense upstream to
> monitoring tools???
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/521>.
>


-- 
Studying for the Turing test

**Comment by GojiSoft** [comment]
I was a little unsure of this option i.e. publishing an unscaled value and
number of logical processors, as it then puts the burden of knowing what to
do with the process stat on downstream users of the value. I'm thinking
mainly from the perspective of monitoring tools though where a 100% scaled
value makes sense - easy to configure an alert against a 0-100 bounded
value.

I have been playing around with the scaled value, and unfortunately pushed
to a branch I've got a pull request on - haven't quite got my pull request
workflow nailed :(

**Comment by gregoryyoung** [comment]
Heh well you can undo. Why not name it cpuScaled etc then and I think it's
ok to accept.

Btw in commercial there is snmp up port as well which is often better
depending on networking setup

On Tuesday, June 16, 2015, Tim Lloyd <notifications@github.com> wrote:

> I was a little unsure of this option i.e. publishing an unscaled value and
> number of logical processors, as it then puts the burden of knowing what to
> do with the process stat on downstream users of the value. I'm thinking
> mainly from the perspective of monitoring tools though where a 100% scaled
> value makes sense - easy to configure an alert against a 0-100 bounded
> value.
>
> I have been playing around with the scaled value, and unfortunately pushed
> to a branch I've got a pull request on - haven't quite got my pull request
> workflow nailed :(
>
>
> On 16 June 2015 at 08:50, Greg Young <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Maybe including num CPUs instead of scaling?
> >
> > On Tuesday, June 16, 2015, Tim Lloyd <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > The value for this stat is read from the performance counter "Process
> ->
> > %
> > > Processor Time" and added to the cluster node stats as is. The value is
> > > notionally a percentage, but is not scaled to 100%, it is actually
> scaled
> > > to the number of logical processors. For example, if there are 8
> logical
> > > processors the maximum value is 800% (ish). For monitoring purposes, it
> > > would be great if this value was scaled to 100%, or perhaps the number
> of
> > > logical processors could be included in the stats so that it could be
> > > scaled after elsewhere.
> > >
> > > I'm happy to make either change and make a pull request, or any other
> > > suggestions. Scaling the value to 100% seems to make most sense
> upstream
> > to
> > > monitoring tools???
> > >
> > > Thanks.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/EventStore/EventStore/issues/521>.
> > >
> >
> >
> > --
> > Studying for the Turing test
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EventStore/EventStore/issues/521#issuecomment-112324082
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/521#issuecomment-112325074>
> .
>


-- 
Studying for the Turing test

**Comment by GojiSoft** [comment]
Good idea - I've added "proc-cpuScaled" and pushed it to "enahancedesstats"
which has a pull request on it.

Will take a look at snmp support. We do have access to perf counters, etc,
just looking at a couple of small enhancements to the cluster stats so that
there is a single source to deal with.

Thanks.
