### ISSUE TITLE
Supported Mono Version

### ISSUE THREAD

**Issue by dnauck** [EventStore/EventStore#522]
I upgraded my environment to run Mono latest stable release Mono 4.0.2.
Now EventStore 2.0.1 and 3.0.x reports i'm running Mono version 2 and i need to use ```--force``` to override the program exit.

**Comment by dnauck** [comment]
Question: do we want to hard code to support only Mono 3 and Mono 4 or would it be better to check for Mono >= 3.x ?

if not we should add the supported Mono Versions to the error message.

**Comment by pgermishuys** [comment]
Yes, I suspect we might also want to revise that warning message to say something along the lines of not recommending running a version of mono version lower than 3.12.x.

**Comment by gregoryyoung** [comment]
Is this complete?

**Comment by dnauck** [comment]
@gregoryyoung it was reverted by @pgermishuys due uncertainly support status. Maybe you can give a statement on Mono 4.x support?

Btw, i'm running this build now nearly 20 days without problems on Mono 4.0.2.

**Comment by pgermishuys** [comment]
after chatting to @jen20, it was decided to not include 4.0 as supported.

**Comment by jen20** [comment]
We're going to hold off on Mono 4.0 for now as there are some fairly serious regressions. We'll come back to this when Core CLR looks more complete.
