### ISSUE TITLE
Consider how to integrate the new V8 build system into the ES build

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#531]
The new V8 build system (already a mess thanks to gyp) now requires you to use `depot_tools` (some google thing) even to check it out.

Upgrading (which we should probably do at some point) breaks the build script, as the workflow of checkout -> `make dependencies` -> `make x64.release` no longer works.

I can only imagine the problems this is going to cause for third parties trying to build (especially on Windows where it might not even be possible to automate the steps required to build). I can barely get this stuff to work on OS X - instead getting a host of timeout errors.

We probably should consider:

- Do we want to ever support Javascript projections at all?
- Is there something better we can use (Dart perhaps, though that may end up having the same ludicrous build system because Google)?
- If so how do we make this easy to build? Relying on the google infrastructure for this seems to not be an option (I'm seeing timeouts on a regular basis). Given the frequency with which libjs1 changes perhaps we should precompile binaries and put them on S3 to be pulled in by the build (or even into the repository).

**Comment by gregoryyoung** [comment]
I think the third option is the best.

On Monday, June 22, 2015, James Nugent <notifications@github.com> wrote:

> The new V8 build system (already a mess thanks to gyp) now requires you to
> use depot_tools (some google thing) even to check it out.
>
> Upgrading (which we should probably do at some point) breaks the build
> script, as the workflow of checkout -> make dependencies -> make
> x64.release no longer works.
>
> I can only imagine the problems this is going to cause for third parties
> trying to build (especially on Windows where it might not even be possible
> to automate the steps required to build). I can barely get this stuff to
> work on OS X - instead getting a host of timeout errors.
>
> We probably should consider:
>
>    - Do we want to ever support Javascript projections at all?
>    - Is there something better we can use (Dart perhaps, though that may
>    end up having the same ludicrous build system because Google)?
>    - If so how do we make this easy to build? Relying on the google
>    infrastructure for this seems to not be an option (I'm seeing timeouts on a
>    regular basis). Given the frequency with which libjs1 changes perhaps we
>    should precompile binaries and put them on S3 to be pulled in by the build
>    (or even into the repository).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/531>.
>


-- 
Studying for the Turing test

**Comment by jen20** [comment]
This has now been done. We still haven't upgraded V8 but at least this will only be imposed on people who need to build `js1` from source.
