### ISSUE TITLE
Gossip endpoint should work on a cluster with size = 1

### ISSUE THREAD

**Issue by litch** [EventStore/EventStore#532]
On a cluster with one node:
```
$ curl -v  10.0.0.112:2113/gossip
* Hostname was NOT found in DNS cache
*   Trying 10.0.0.112...
* Connected to 10.0.0.112 (10.0.0.112) port 2113 (#0)
> GET /gossip HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.0.0.112:2113
> Accept: */*
> 
< HTTP/1.1 408 Server was unable to handle request in time
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTo, ES-ExpectedVersion
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Location, ES-Position
< Content-Type: 
* Server Mono-HTTPAPI/1.0 is not blacklisted
< Server: Mono-HTTPAPI/1.0
< Date: Tue, 23 Jun 2015 11:18:12 GMT
< Content-Length: 0
< Connection: close
< 
* Closing connection 0
```

On a cluster with 3 nodes:

Actually, I'll spare you the paste - suffice it to say that it works as expected.

This is problematic because I am trying to develop client code that can determine which is the master node so I can route connections efficiently, but can't do so at all with a single-node cluster.  This seems broken.

**Comment by gregoryyoung** [comment]
As of now gossip is not started on a cluster size of one as no one would
talk to it. I can see why you may want it started (or perhaps half of it).

On Tuesday, June 23, 2015, Justin Litchfield <notifications@github.com>
wrote:

> On a cluster with one node:
>
> $ curl -v  10.0.0.112:2113/gossip
> * Hostname was NOT found in DNS cache
> *   Trying 10.0.0.112...
> * Connected to 10.0.0.112 (10.0.0.112) port 2113 (#0)
> > GET /gossip HTTP/1.1
> > User-Agent: curl/7.35.0
> > Host: 10.0.0.112:2113
> > Accept: */*
> >
> < HTTP/1.1 408 Server was unable to handle request in time
> < Access-Control-Allow-Methods: GET, OPTIONS
> < Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTo, ES-ExpectedVersion
> < Access-Control-Allow-Origin: *
> < Access-Control-Expose-Headers: Location, ES-Position
> < Content-Type:
> * Server Mono-HTTPAPI/1.0 is not blacklisted
> < Server: Mono-HTTPAPI/1.0
> < Date: Tue, 23 Jun 2015 11:18:12 GMT
> < Content-Length: 0
> < Connection: close
> <
> * Closing connection 0
>
> On a cluster with 3 nodes:
>
> Actually, I'll spare you the paste - suffice it to say that it works as
> expected.
>
> This is problematic because I am trying to develop client code that can
> determine which is the master node so I can route connections efficiently,
> but can't do so at all with a single-node cluster. This seems broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/532>.
>


-- 
Studying for the Turing test

**Comment by jen20** [comment]
If it's only one node it's not a cluster - things get wired up internally very differently. General good practice dictates keeping the surface area as small as possible hence not having unnecessary services running, so this is by design. It may be worth exposing the read side of gossip via a development mode flag though. Any thoughts on this @gregoryyoung?

**Comment by litch** [comment]
One could argue that it is a cluster with size = 1 (which is, incidentally, the semantics of how you get this stood up in the first place) and should behave like a cluster.

If one wanted to launch just a standalone node, they should be able to do so.  I agree that "cluster size = 1” is pretty different from “single node” - and the code is behaving as such.  I would also like to be able to launch a “cluster size = 1” in addition to “single-node that is inferred from the fact that you asked for a cluster size = 1”.

**Comment by jen20** [comment]
There is material difference between single node and cluster size = 1 (which doesn't actually work that well, and introduces a lot of extra latency vs a single node). I agree at the moment the name `clusternode` implies a cluster of 1 but that's not what you have. This will become less anachronistic as of version 3.1.0 which renames the binary to `eventstored`. The original naming dates from when there was a plan to implement partitioning in the database via the manager nodes.

For testing purposes there are a few options that don't require software changes, all of which are better than running a single node with gossip:

- run several nodes on one machine (on difference ports), as described [here](http://docs.geteventstore.com/server/3.0.5/cluster-without-manager-nodes/)
- run several nodes on one machine on production-like ports via something like Docker.
- mock the data observed by observation on a real cluster (for unit testing purposes this is likely what you want as it's the only way to assert on your client behaviour in a deterministic fashion)

The reason I see having the read side of gossip on a single node as valuable is that a monitoring agent could make use of it.

**Comment by litch** [comment]
Well if I'm running a development ES instance on my laptop, and my client uses the /gossip endpoint to determine which is the master node so that I can know what to write to, then I am forced to run three instances of ES.  Likewise for testing.  Forcing me to run multiple instances in development and test rather than enable a single-node cluster seems like just giving people that develop applications that consume ES (as opposed to people that operate the clusters) the middle finger.

**Comment by litch** [comment]
And let me state yet again that I understand and apprecitae the material difference between a single node and a cluster size = 1.  I would just like to be able to run a functioning cluster size = 1.

**Comment by jen20** [comment]
This is bad thing to rely on (the gossip isn't public contract and we reserve the right to change any of it at any time with just a patch release number change), and even if it was, testing it with a single node is meaningless as it certainly doesn't guarantee your code correctness as there'll only ever be one entry.

Supporting a cluster size of 1 is meaningless and adds no value except in very obscure edge conditions, and just provides more potential run modes for people to use by accident. This is definitely not a priority issue that we'll be working on, though we would consider accepting a pull request for it.

**Comment by litch** [comment]
Ok.  What is a better way to determine which node is master?

**Comment by jen20** [comment]
There is currently no good supported way of doing this over HTTP - all the TCP clients make use of the private API. Probably the best thing to do is add the state to the /info endpoint or something along those lines - I think there was a PR opened for this a while back.

**Comment by gregoryyoung** [comment]
@jen20 do we want to add something here to /info or?

**Comment by pgermishuys** [comment]
The PR in question here was https://github.com/EventStore/EventStore/pull/526

However, adding to /info or /state might be better.

**Comment by gregoryyoung** [comment]
It definitely is useful in statistics. Adding it to /info would not be hard as well (just listen for the state updates)

**Comment by litch** [comment]
It looks like state is now in the `/info` endpoint.
```
# curl 127.0.0.1:2113/info
{
  "esVersion": "3.2.1.0",
  "state": "master",
  "projectionsMode": "All"
}
```
Thank you.
