### ISSUE TITLE
ATOM feed with embed=body doesn't return the metadata created with the application/vnd.eventstore.events+json media type

### ISSUE THREAD

**Issue by sbellware** [EventStore/EventStore#533]
Posted metadata using the application/vnd.eventstore.events+json media type.

Retrieved using the application/vnd.eventstore.atom+json content type.

The metadata field is not included in the entries.

**Comment by jen20** [comment]
:+1: this should be at `body` embed level (it already is at `pretty` and `tryharder`). This will be in 3.1.0

**Comment by gregoryyoung** [comment]
Not sure it should be in embed=body it should be in embed=content isn't embed=body just supposed to be the event payload?
