### ISSUE TITLE
Temp files

### ISSUE THREAD

**Issue by SamNil** [EventStore/EventStore#538]
I would like to ask about the event stores temp files that's generated under \Windows\Temp\EventStore

What's the usage of this temp files to event store? will deleting them will cause any issue ?

Why it's so big, for me it's 3.6 GB till now ?

Can we change the location of the temp files?

Thanks

**Comment by jen20** [comment]
Unless you specified a different path with `--db=/some/path` that's your
actual data.

**Comment by SamNil** [comment]
Thanks Jen, you are right, looks like it's an old deployment I had before 

Cheers
