### ISSUE TITLE
HTTP Batch insert does not work (version 3.0.5 on Mac)

### ISSUE THREAD

**Issue by jsm123** [EventStore/EventStore#540]
Hi,

we're trying the batch HTTP API with the request like this one:

```
curl -i -d @myevent.json  "http://127.0.0.1:2113/streams/teststream" -H "Content-Type:application/json"
```

The content of the file myevent.json (copied from event store docu)

```
[
  {
    "eventId": "fbf4b1a1-b4a3-4dfe-a01f-ec52c34e16e4",
    "eventType": "event-type",
    "data": {

      "a": "1"
    }
  },
  {
    "eventId": "0f9fad5b-d9cb-469f-a165-70867728951e",
    "eventType": "event-type",
    "data": {

      "ba": "1"
    }
  }
]
```
and we got following results:

```
Juris-MacBook-Pro:_t$ curl -i -d @myevent.json  "http://127.0.0.1:2113/streams/teststream" -H "Content-Type:application/json"
HTTP/1.1 400 Must include an event type with the request either in body or as ES-EventType header.
Access-Control-Allow-Methods: POST, DELETE, GET, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTo, ES-ExpectedVersion
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position
Content-Type:
Server: Mono-HTTPAPI/1.0
Date: Tue, 07 Jul 2015 14:00:40 GMT
Content-Length: 0
Connection: close
```

Regards,
Juri

**Comment by gregoryyoung** [comment]
Wrong content type. application/vnd.eventstore.events+json

Cheers,

Greg

On Tue, Jul 7, 2015 at 5:11 PM, Juri Smarschevski <notifications@github.com>
wrote:

> Hi,
>
> we're trying the batch HTTP API with the request like this one:
>
> curl -i -d @myevent.json  "http://127.0.0.1:2113/streams/teststream" -H "Content-Type:application/json"
>
> The content of the file myevent.json (copied from event store docu)
>
> [
>   {
>     "eventId": "fbf4b1a1-b4a3-4dfe-a01f-ec52c34e16e4",
>     "eventType": "event-type",
>     "data": {
>
>       "a": "1"
>     }
>   },
>   {
>     "eventId": "0f9fad5b-d9cb-469f-a165-70867728951e",
>     "eventType": "event-type",
>     "data": {
>
>       "ba": "1"
>     }
>   }
> ]
>
> and we got following results:
>
> Juris-MacBook-Pro:_t$ curl -i -d @myevent.json  "http://127.0.0.1:2113/streams/teststream" -H "Content-Type:application/json"
> HTTP/1.1 400 Must include an event type with the request either in body or as ES-EventType header.
> Access-Control-Allow-Methods: POST, DELETE, GET, OPTIONS
> Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTo, ES-ExpectedVersion
> Access-Control-Allow-Origin: *
> Access-Control-Expose-Headers: Location, ES-Position
> Content-Type:
> Server: Mono-HTTPAPI/1.0
> Date: Tue, 07 Jul 2015 14:00:40 GMT
> Content-Length: 0
> Connection: close
>
> Regards,
> Juri
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/540>.
>



-- 
Studying for the Turing test

**Comment by jsm123** [comment]
thx, this worked.

Regards,
Juri

**Comment by gregoryyoung** [comment]
if you pass application/json then it assumes the body is the event itself (single even)
