### ISSUE TITLE
Projection Emit Null Stream

### ISSUE THREAD

**Issue by jbradford** [EventStore/EventStore#541]
When you try emitting to a null stream from a projection you get the below error, it would be nice to show something human readable. (I was reading the wrong variable into the stream name on emit so was trying to emit to null).

Value cannot be null. Parameter name: key at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) at EventStore.Projections.Core.Services.Processing.ProjectionCheckpoint.EmitEventsToStream(String streamId, EmittedEventEnvelope[] emittedEvents) in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\ProjectionCheckpoint.cs:line 130 at EventStore.Projections.Core.Services.Processing.ProjectionCheckpoint.ValidateOrderAndEmitEvents(EmittedEventEnvelope[] events) in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\ProjectionCheckpoint.cs:line 76 at EventStore.Projections.Core.Services.Processing.CoreProjectionCheckpointManager.EventsEmitted(EmittedEventEnvelope[] scheduledWrites, Guid causedBy, String correlationId) in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\CoreProjectionCheckpointManager.cs:line 207 at EventStore.Projections.Core.Services.Processing.ResultWriter.EventsEmitted(EmittedEventEnvelope[] scheduledWrites, Guid causedBy, String correlationId) in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\ResultWriter.cs:line 94 at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.FinalizeEventProcessing(EventProcessedResult result, CheckpointTag eventCheckpointTag, Single progress) in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\EventSubscriptionBasedProjectionProcessingPhase.cs:line 529 at EventStore.Projections.Core.Services.Processing.CommittedEventWorkItem.WriteOutput() in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\CommittedEventWorkItem.cs:line 78 at EventStore.Projections.Core.Services.Processing.StagedProcessingQueue.Process(Int32 max) in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\StagedProcessingQueue.cs:line 115 at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessOneEventBatch() in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\CoreProjectionQueue.cs:line 138 at EventStore.Projections.Core.Services.Processing.CoreProjectionQueue.ProcessEvent() in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\CoreProjectionQueue.cs:line 50 at EventStore.Projections.Core.Services.Processing.EventSubscriptionBasedProjectionProcessingPhase.Handle(ProgressChanged message) in c:\EventStore\src\EventStore.Projections.Core\Services\Processing\EventSubscriptionBasedProjectionProcessingPhase.cs:line 171

**Comment by pgermishuys** [comment]
Fixed by https://github.com/EventStore/EventStore/pull/856
