### ISSUE TITLE
Projection reset deletes entire stream.

### ISSUE THREAD

**Issue by jbradford** [EventStore/EventStore#542]
I have a projection that is designed to assign an id to an aggregate whenever it receives a created event, similar to the below.

fromCategory('agg')
.when({
    "$init": function(state, ev) {
      return { count: 0 };
    },
    "created":function(state, ev) {
        state.count++;
        var streamName = ev.streamId;
        var eventType = "idAdded";
        var id = state.count.toString();
        emit(streamName, eventType, {
            "id":id
        });
    }
});

When I hit reset on this projection it has deleted all events from the agg streams, I'm not sure if this is expected behaviour or not but the warnings in the UI only say that it will re-emit events.

**Comment by gregoryyoung** [comment]
Yes reset deletes/recreates.

**Comment by pgermishuys** [comment]
This warrants an appropriate notification in the UI. Will create an issue for it as a reminder.
