### ISSUE TITLE
Testability of RecordedEvent.

### ISSUE THREAD

**Issue by RomanoLindano** [EventStore/EventStore#543]
I want to test how my system reacts on different RecordedEvents (from subscription). I can't do that because I can't create them. How can I test this (crucial) part of my system?

**Comment by gregoryyoung** [comment]
Wrap your code and push the event in then test by pushing your events in is
what most do

On Thu, Jul 9, 2015 at 2:35 PM, RomanoLindano <notifications@github.com>
wrote:

> I want to test how my system reacts on different RecordedEvents (from
> subscription). I can't do that because I can't create them. How can I test
> this (crucial) part of my system?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/543>.
>



-- 
Studying for the Turing test

**Comment by RomanoLindano** [comment]
So how I can test, that I wrap RecordedEvent correctly? This does not resolve the problem, just moves it to different lines of code. Is there any chance that I can create ResolvedEvent in future versions of EventStore?
