### ISSUE TITLE
Configuration: TCP Binding vs Advertised

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#555]
So I am looking at an interesting situation here with TCP and I think its valid and we should support it but want others opinions.

I want to bind 0.0.0.0 for TCP. This is obviously not a routable address. When doing this gossip will gossip that I am 0.0.0.0. Do we want to add an argument for "advertise as" which would allow me to say 

--ext-ip 0.0.0.0 --ext-tcp-port 9999 --ext-tcp-advertise-as 192.168.14.96

By default you would advertise as --ext-ip unless also passed an ext-tcp-advertise-as.

Thoughts?

**Comment by jen20** [comment]
This would probably resolve a fair few issues - I think we discussed it in the past but can't remember why it wasn't done in the end. Seems like a reasonable change to me though.

**Comment by pgermishuys** [comment]
This was fixed in https://github.com/EventStore/EventStore/pull/556
