### ISSUE TITLE
Http connections

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#565]
run wrk with about 1000 connections on a node (tested AWS linux/mono 3.12 but my guess is it exists elsewhere)

**Comment by pgermishuys** [comment]
As of Event Store 3.6.0, the statically linked mono is a branch off of 3.12.1 with an additional commit (https://github.com/mono/mono/pull/2713) which takes care of the above mentioned issue.

**Comment by gregoryyoung** [comment]
This fix has also been accepted on mono master so when we upgrade it will
be there as well.

On Tue, May 3, 2016 at 2:46 PM, Pieter Germishuys <notifications@github.com>
wrote:

> As of Event Store 3.6.0, the statically linked mono is a branch off of
> 3.12.1 with an additional commit (mono/mono#2713
> <https://github.com/mono/mono/pull/2713>) which takes care of the above
> mentioned issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/565#issuecomment-216504545>
>



-- 
Studying for the Turing test
