### ISSUE TITLE
"New Projection" button does not do anything

### ISSUE THREAD

**Issue by simensen** [EventStore/EventStore#567]
I'm firing up GES for the first time and am curious to see how projections work. (I understand they are in beta and not documented very well!)

If I visit this link, I get a reasonably expected index page with no projections.

 * http://127.0.0.1:2113/web/index.html#/projections

There are Disable All, Enable All, and New Projection buttons. Clicking "New Projection" doesn't do anything.

I asked around with some people who I know use GES and they said that when they click the link, they are sent here:

 * http://127.0.0.1:2113/web/index.html#/projections/new

If I follow this link directly, it at least opens the page just fine as one might expect.

Is the "New Projection" button broken in 3.0.5.0 (Mac OS X) or disabled somehow? Or is this a bug?

**Comment by simensen** [comment]
In case it helps, I do see I get a JavaScript console error when the /projections route loads:

![image](https://cloud.githubusercontent.com/assets/191200/8876837/d5779acc-31e7-11e5-8220-12e67ad61fc8.png)

http://d.pr/i/1jh0C

**Comment by pgermishuys** [comment]
Hi, sorry that you've encountered this issue as your first experience of Event Store. Unfortunately this was a UI regression and can be resolved by replacing the UI (located in clusternode-web/) with a build (or src/) from the https://github.com/EventStore/EventStore.UI/tree/oss-v3.0.6 repository.

**Comment by simensen** [comment]
@pgermishuys oh great! thanks. :) how long will it take for 3.0.6 to make it to the release binaries page(s)? i can probably wait a bit for a binary download as opposed to building from src unless it is going to be months. :)
