### ISSUE TITLE
SubscribeToStreamFrom StreamStart fails on on empty deleted stream

### ISSUE THREAD

**Issue by davidgrenier** [EventStore/EventStore#573]
It would seem that SubscribeToStreamFrom StreamStart will not process any events if executed on an empty stream following a DeleteStreamAsync.

On the other hand, if it's a fresh new stream, SubscribeToStreamFrom StreamStart will properly process the next event that is appended.

**Comment by gregoryyoung** [comment]
My guess it is coming back as deleted not as no stream.

Either of these can be considered correct.

@jen20 @pieterg any thoughts on which is more correct?

Greg

On Sat, Aug 1, 2015 at 10:06 PM, David Grenier <notifications@github.com>
wrote:

> It would seem that SubscribeToStreamFrom StreamStart will not process any
> events if executed on an empty stream following a DeleteStreamAsync.
>
> On the other hand, if it's a fresh new stream, SubscribeToStreamFrom
> StreamStart will properly process the next event that is appended.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/573>.
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Just to be a bit more clear when reading it probably should come back as
"deleted" (consider the case that you are reading from a stream and it gets
deleted).

We could also have it come back as "no stream" which means it doesn't exist.

Both of these behaviors I think can be said to be valid and originally we
went with the first one from a consistency perspective (soft delete should
work like hard delete). This is an edge case (you can't subscribe to a hard
deleted stream).

I will bring it up internally to see what others think about it

On Sun, Aug 2, 2015 at 11:35 AM, Greg Young <gregoryyoung1@gmail.com> wrote:

> My guess it is coming back as deleted not as no stream.
>
> Either of these can be considered correct.
>
> @jen20 @pieterg any thoughts on which is more correct?
>
> Greg
>
> On Sat, Aug 1, 2015 at 10:06 PM, David Grenier <notifications@github.com>
> wrote:
>
>> It would seem that SubscribeToStreamFrom StreamStart will not process any
>> events if executed on an empty stream following a DeleteStreamAsync.
>>
>> On the other hand, if it's a fresh new stream, SubscribeToStreamFrom
>> StreamStart will properly process the next event that is appended.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/573>.
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by davidgrenier** [comment]
Maybe I failed to describe the observed behaviour as I can reconcile it with your explanation.

If you make a live subscription to a deleted stream, it'll start receiving events normally. If you subscribe from the start on a deleted stream then that is the only scenario where the CatchUpSubscription isn't converted to a live subscription.

If you create a CatchUpSubscription to a stream that never even existed it will correctly convert to a live subscription right away.

While if you delete a stream that already has subscriptions to it, they will keep receiving events as normal.

```fsharp
#r @"C:\Program Files (x86)\EventStore\EventStore.ClientAPI.dll"

open System
open System.Threading.Tasks
open EventStore.ClientAPI
open System.Net

let conn =
    let c = EventStoreConnection.Create(IPEndPoint(IPAddress.Loopback, 1113))
    c.ConnectAsync().Wait()
    c

let iter f = f conn |> Async.AwaitTask |> Async.Ignore |> Async.RunSynchronously

let saveTo name content =
    let evt = EventData (Guid.NewGuid(), "TestEvent", false, content, null)
    iter (fun c -> c.AppendToStreamAsync(name, ExpectedVersion.Any, evt))

let fromCurrent name f =
    iter (fun c -> c.SubscribeToStreamAsync(name, false, Action<_,_>(fun _ y -> f y.Event.EventNumber)))

let fromStart name f =
    iter (fun c ->
        c.SubscribeToStreamFrom(name, StreamCheckpoint.StreamStart, false, Action<_,_>(fun _ y -> f y.Event.EventNumber))
        |> Task.FromResult
    )

let name = "Stream5"

fromCurrent name (printfn "#1 from current %i")
fromStart name (printfn "#2 from start %i")

[||] |> saveTo name


iter (fun c -> c.DeleteStreamAsync(name, ExpectedVersion.Any))

fromCurrent name (printfn "#3 from current %i")
fromStart name (printfn "#4 from start %i")

[||] |> saveTo name
```

**Comment by gregoryyoung** [comment]
You are missing the difference between hard delete and soft delete. Hard
delete was how we originally deleted streams. When we brought in soft
delete we made it work like soft delete (you can't subscribe to a hard
deleted stream)

On Sun, Aug 2, 2015 at 8:09 PM, David Grenier <notifications@github.com>
wrote:

> Maybe I failed to describe the observed behaviour as I can reconcile it
> with your explanation.
>
> If you make a live subscription to a deleted stream, it'll start receiving
> events normally. If you subscribe from the start on a deleted stream then
> that is the only scenario where the CatchUpSubscription isn't converted to
> a live subscription.
>
> If you create a CatchUpSubscription to a stream that never even existed it
> will correctly convert to a live subscription right away.
>
> While if you delete a stream that already has subscriptions to it, they
> will keep receiving events as normal.
>
> #r @"C:\Program Files (x86)\EventStore\EventStore.ClientAPI.dll"
> open Systemopen System.Threading.Tasksopen EventStore.ClientAPIopen System.Net
> let conn =
>     let c = EventStoreConnection.Create(IPEndPoint(IPAddress.Loopback, 1113))
>     c.ConnectAsync().Wait()
>     c
> let iter f = f conn |> Async.AwaitTask |> Async.Ignore |> Async.RunSynchronously
> let saveTo name content =
>     let evt = EventData (Guid.NewGuid(), "TestEvent", false, content, null)
>     iter (fun c -> c.AppendToStreamAsync(name, ExpectedVersion.Any, evt))
> let fromCurrent name f =
>     iter (fun c -> c.SubscribeToStreamAsync(name, false, Action<_,_>(fun _ y -> f y.Event.EventNumber)))
> let fromStart name f =
>     iter (fun c ->
>         c.SubscribeToStreamFrom(name, StreamCheckpoint.StreamStart, false, Action<_,_>(fun _ y -> f y.Event.EventNumber))
>         |> Task.FromResult
>     )
> let name = "Stream5"
>
> fromCurrent name (printfn "#1 from current %i")
> fromStart name (printfn "#2 from start %i")
> [||] |> saveTo name
>
>
> iter (fun c -> c.DeleteStreamAsync(name, ExpectedVersion.Any))
>
> fromCurrent name (printfn "#3 from current %i")
> fromStart name (printfn "#4 from start %i")
> [||] |> saveTo name
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/573#issuecomment-127051464>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
bah when we brought in soft delete we made it work like hard delete*

On Sun, Aug 2, 2015 at 11:30 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> You are missing the difference between hard delete and soft delete. Hard
> delete was how we originally deleted streams. When we brought in soft
> delete we made it work like soft delete (you can't subscribe to a hard
> deleted stream)
>
> On Sun, Aug 2, 2015 at 8:09 PM, David Grenier <notifications@github.com>
> wrote:
>
>> Maybe I failed to describe the observed behaviour as I can reconcile it
>> with your explanation.
>>
>> If you make a live subscription to a deleted stream, it'll start
>> receiving events normally. If you subscribe from the start on a deleted
>> stream then that is the only scenario where the CatchUpSubscription isn't
>> converted to a live subscription.
>>
>> If you create a CatchUpSubscription to a stream that never even existed
>> it will correctly convert to a live subscription right away.
>>
>> While if you delete a stream that already has subscriptions to it, they
>> will keep receiving events as normal.
>>
>> #r @"C:\Program Files (x86)\EventStore\EventStore.ClientAPI.dll"
>> open Systemopen System.Threading.Tasksopen EventStore.ClientAPIopen System.Net
>> let conn =
>>     let c = EventStoreConnection.Create(IPEndPoint(IPAddress.Loopback, 1113))
>>     c.ConnectAsync().Wait()
>>     c
>> let iter f = f conn |> Async.AwaitTask |> Async.Ignore |> Async.RunSynchronously
>> let saveTo name content =
>>     let evt = EventData (Guid.NewGuid(), "TestEvent", false, content, null)
>>     iter (fun c -> c.AppendToStreamAsync(name, ExpectedVersion.Any, evt))
>> let fromCurrent name f =
>>     iter (fun c -> c.SubscribeToStreamAsync(name, false, Action<_,_>(fun _ y -> f y.Event.EventNumber)))
>> let fromStart name f =
>>     iter (fun c ->
>>         c.SubscribeToStreamFrom(name, StreamCheckpoint.StreamStart, false, Action<_,_>(fun _ y -> f y.Event.EventNumber))
>>         |> Task.FromResult
>>     )
>> let name = "Stream5"
>>
>> fromCurrent name (printfn "#1 from current %i")
>> fromStart name (printfn "#2 from start %i")
>> [||] |> saveTo name
>>
>>
>> iter (fun c -> c.DeleteStreamAsync(name, ExpectedVersion.Any))
>>
>> fromCurrent name (printfn "#3 from current %i")
>> fromStart name (printfn "#4 from start %i")
>> [||] |> saveTo name
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/573#issuecomment-127051464>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by davidgrenier** [comment]
In that case shouldn't a live subscription behave exactly the same as a subscribe from start?

**Comment by gregoryyoung** [comment]
These are very different things why would they behave the same? Catchup
subscription vs live subscription are not the same thing. On is a
subscription the other is a helper over reads + subscriptions.

I get your original question which was more about when a stream is soft
deleted vs hard deleted what is the return value for a subscription but?



On Sun, Aug 2, 2015 at 11:48 PM, David Grenier <notifications@github.com>
wrote:

> In that case shouldn't a live subscription behave exactly the same as a
> subscribe from start?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/573#issuecomment-127074780>
> .
>



-- 
Studying for the Turing test

**Comment by davidgrenier** [comment]
Hmm, no that's not what I meant. I don't think you've tried my examples because it seems obvious to me from them that the observed semantics makes little sense (as opposed to the ones you might be describing).

But that's fine, I removed the lib code deleting streams from my code. I had a haunch there's something I'm doing wrong if I feel the need to delete a stream anyway.

Amazing product.

**Comment by davidgrenier** [comment]
edit: I felt that last line might have come off as sarcastic but it wasn't.
