### ISSUE TITLE
HTTP projections API call fails with Parse Error HPE_INVALID_CONSTANT

### ISSUE THREAD

**Issue by plato-cambrian** [EventStore/EventStore#574]
Hi, I'm new to Eventstore, and I'm ready to persist my projection files in my repo and load them into Eventstore though the HTTP API.

I just sent my first requests, which failed with an unintuitive error message:

```
request(
{ uri: 'http://192.168.10.206:1113/projections/continuous',
  auth: { user: 'admin', pass: 'xxxxxxxxxx' },
  headers: { 'Content-Type': 'application/json' },
  qs: { name: 'channelsMultiplexer' },
  body: 'fromStream("channels")\n.when( ... )' }
)

{ [Error: Parse Error] bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' }
```
Googling tells me this is an HTTP protocol error (presumably sent from eventstore to node, but maybe I formed the request badly.)

My eventstore stacktrace is available at https://gist.github.com/plato-cambrian/5887b960423265a1fb08

*edit*
Since posting I realized I was making a GET request, I get the same problem after changing it to POST

**Comment by jimmymorales** [comment]
EventStore uses two different ports for their http API and TCP Server, you are using the TCP port. The Http default port is 2113 and the TCP default port is 1113.

**Comment by plato-cambrian** [comment]
thanks the error is resolved

**Comment by sigil66** [comment]
Wow, so you want them to magically detect that your are trying to issue an HTTP request to their native binary protocol port, and some how send you an HTTP response?

**Comment by plato-cambrian** [comment]
I don't know whether the handler would go in Node's TCP code or Request's error handler library, I certainly get that Eventstore's not responsible for it. But yeah, I'd love to see something like "this does not appear to be an HTTP endpoint"

**Comment by jen20** [comment]
HTTP is just a protocol (normally) transported over TCP. The error message you're seeing is *exactly* that it's not an HTTP message - it can't parse the response (in this case we just close the socket since there's nothing else sensible to do).
