### ISSUE TITLE
How to access my projection state from code?

### ISSUE THREAD

**Issue by plato-cambrian** [EventStore/EventStore#578]
I am loving eventstore as a sensible way to organize many streams of data! I'm working on refactoring my ACL code. I currently store everything in one database document but I'd like to instead keep track of the individual events that are used to assemble that document.

I have created one stream, `authAcl`, and I emit three types of events to the stream. I have made a projection that assembles a denormalized representation of my ACL rules in its state object:

    fromStream('authAcl')
    .when({
        '$init': function(state, event){
            return {
                rolePermissions: [],
                roleParents: [],
                userRoles: [],
            }
        },
        'auth.aclAddPermission': function(state, event){
            var item = [event.data.role, event.data.endpoint, event.data.action];
            state.rolePermissions.push(item);
            return state;
        },
        'auth.aclCascadePermissions': function(state, event){ ... },
        'auth.aclGrantRole': function(state, event){ ... },
    })

My web UI shows the result I expect, an object with `rolePermissions`, `roleParents`, `userRoles` arrays. Now I need to use this state and subscribe to updates from my code. The only approach I can think of now is to create a new `aclRulesFlattened` stream and emit the flattened state to it every time my projection changes it.

Is there built in functionality to get the state of a projection as a stream?
Is there an HTTP API call to get the state of a projection?
Is there an TCP API call to get the state of a projection?

**Comment by pgermishuys** [comment]
Yes there is,

**HTTP Api**
We expose an endpoint that allows you to grab the state of a projection
https://github.com/EventStore/EventStore/blob/release-v3.1.0/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs#L84
```
curl -i http://localhost:2113/projection/demoProjection/state
HTTP/1.1 200 OK
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: Content-Type, X-Requested-With, X-Forwarded-Host, X-PINGOTHER, Authorization, ES-LongPoll, ES-ExpectedVersion, ES-EventId, ES-EventType, ES-RequiresMaster, ES-HardDelete, ES-ResolveLinkTo, ES-ExpectedVersion
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ES-Position
ES-Position: {"$s":{"$stats-127.0.0.1:2113":109}}
Cache-Control: max-age=0, no-cache, must-revalidate
Vary: Accept
Content-Type: application/json; charset=utf-8
Server: Mono-HTTPAPI/1.0
Date: Wed, 05 Aug 2015 05:36:25 GMT
Content-Length: 13
Keep-Alive: timeout=15,max=100

{"count":110}%
```

**Client API**
You can use the ProjectionManager's GetStateAsync method.
https://github.com/EventStore/EventStore/blob/release-v3.1.0/src/EventStore.ClientAPI/ProjectionsManager.cs#L155

```
var projectionState = projectionManager.GetStateAsync("demoProjection", new UserCredentials("admin", "changeit")).Result;
```

**Comment by plato-cambrian** [comment]
Thanks @pgermishuys !
