### ISSUE TITLE
Client tries to connect twice on connection failure to remote node and throws "Operation already in progress" exception - mono

### ISSUE THREAD

**Issue by mjaric** [EventStore/EventStore#591]
Hi,

workstation OS: Mac OSX 
ES client API version: 3.0.2 (new 3.1.0 is still not in public NuGet repository)
```
Mono JIT compiler version 4.0.3 ((detached/d6946b4 Wed Jul 29 14:46:23 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
```

When I start connection to remote event store (server is not on same machine) and then unplug network cable, ES Client connection tries to connect twice and for some reason schedules connection task before  Close event appear.
```
			var cfg = ConnectionSettings
				.Create()
				.EnableVerboseLogging();

			_connection = EventStoreConnection.Create(cfg, _endpoint, "EventStoreStatsCollector");

                       _connection.Connected += (sender, e) => {
				_logger.Info("Connected to EventStore....SHOWTIME!!!");
			};
			_connection.Closed += (sender, e) => {
				_logger.Error("Connection to EventStore is closed!!!");
			};
			_connection.Disconnected += (sender, e) => {
				_logger.Warning("We have been disconnected from EventStore!");
			};
			_connection.ErrorOccurred += (object sender, ClientErrorEventArgs e) => {
				_logger.Error(e.Exception.Message);
			};
			_connection.Reconnecting += (sender, e) => {
				_logger.Warning("Reconnectiong to EventStore....");
			};
			_connection.ConnectAsync().Wait();
```
In log, entries appear in this order with fatal error at the end (client application shutdown since error is unhanded). In case I connect with same configuration to localhost it works well and it try to reconnect 10-times until connection closed event appear.
```
[INFO][8/19/2015 2:12:39 PM][Thread 0009] Connected to EventStore....SHOWTIME!!!
[WARNING][8/19/2015 2:12:43 PM][Thread 0009] We have been disconnected from EventStore!
[WARNING][8/19/2015 2:12:43 PM][Thread 0009] Reconnectiong to EventStore....
[INFO][8/19/2015 2:12:43 PM][Thread 0012] Connected to EventStore....SHOWTIME!!!
[WARNING][8/19/2015 2:12:46 PM][Thread 0007] We have been disconnected from EventStore!
[WARNING][8/19/2015 2:12:46 PM][Thread 0007] Reconnectiong to EventStore....
[ERROR][8/19/2015 2:12:46 PM][Thread 0007] 
Default Critical: 0 : The service threw an unhandled exception: 'EventStoreStatsCollectorService'. System.InvalidOperationException: Operation already in progress
  at System.Net.Sockets.SocketAsyncEventArgs.SetLastOperation (SocketAsyncOperation op) [0x00027] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.3/mcs/class/System/System.Net.Sockets/SocketAsyncEventArgs.cs:162 
  at System.Net.Sockets.Socket+Worker.Init (System.Net.Sockets.Socket sock, System.Net.Sockets.SocketAsyncEventArgs args, SocketOperation op) [0x000a8] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.3/mcs/class/System/System.Net.Sockets/Socket_2_1.cs:475 
  at System.Net.Sockets.Socket.ConnectAsyncReal (System.Net.Sockets.SocketAsyncEventArgs e) [0x0001f] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.3/mcs/class/System/System.Net.Sockets/Socket_2_1.cs:1606 
  at System.Net.Sockets.Socket.ConnectAsync (System.Net.Sockets.SocketAsyncEventArgs e) [0x00053] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.3/mcs/class/System/System.Net.Sockets/Socket_2_1.cs:1643 
  at EventStore.ClientAPI.Transport.Tcp.TcpClientConnector.InitConnect (System.Net.IPEndPoint serverEndPoint, System.Action`2 onConnectionEstablished, System.Action`2 onConnectionFailed, ITcpConnection connection, TimeSpan connectionTimeout) [0x0009d] in <filename unknown>:0 
  at EventStore.ClientAPI.Transport.Tcp.TcpConnection.CreateConnectingConnection (ILogger log, Guid connectionId, System.Net.IPEndPoint remoteEndPoint, EventStore.ClientAPI.Transport.Tcp.TcpClientConnector connector, TimeSpan connectionTimeout, System.Action`1 onConnectionEstablished, System.Action`2 onConnectionFailed, System.Action`2 onConnectionClosed) [0x00026] in <filename unknown>:0 
  at EventStore.ClientAPI.Transport.Tcp.TcpClientConnector.ConnectTo (ILogger log, Guid connectionId, System.Net.IPEndPoint remoteEndPoint, Boolean ssl, System.String targetHost, Boolean validateServer, TimeSpan timeout, System.Action`1 onConnectionEstablished, System.Action`2 onConnectionFailed, System.Action`2 onConnectionClosed) [0x00034] in <filename unknown>:0 
  at EventStore.ClientAPI.Transport.Tcp.TcpPackageConnection..ctor (ILogger log, System.Net.IPEndPoint remoteEndPoint, Guid connectionId, Boolean ssl, System.String targetHost, Boolean validateServer, TimeSpan timeout, System.Action`2 handlePackage, System.Action`2 onError, System.Action`1 connectionEstablished, System.Action`2 connectionClosed) [0x000e2] in <filename unknown>:0 
  at EventStore.ClientAPI.Core.EventStoreConnectionLogicHandler.EstablishTcpConnection (NodeEndPoints endPoints) [0x0008f] in <filename unknown>:0 
  at EventStore.ClientAPI.Core.EventStoreConnectionLogicHandler.<.ctor>b__9 (EventStore.ClientAPI.Core.EstablishTcpConnectionMessage msg) [0x00000] in <filename unknown>:0 
  at EventStore.ClientAPI.Core.SimpleQueuedHandler+<>c__DisplayClass1`1[EventStore.ClientAPI.Core.EstablishTcpConnectionMessage].<RegisterHandler>b__0 (EventStore.ClientAPI.Core.Message msg) [0x00000] in <filename unknown>:0 
  at EventStore.ClientAPI.Core.SimpleQueuedHandler.ProcessQueue (System.Object state) [0x00038] in <filename unknown>:0 
Stopping service: 'EventStoreStatsCollectorService'.

```

**Comment by jen20** [comment]
Interesting, that looks like a bug in the Mono socket library. We can probably handle it though. Can you repeat it by means other than unplugging the network cable?

**Comment by gregoryyoung** [comment]
This must be a bug in mono. How could an operation "already be started"?

https://github.com/EventStore/EventStore/blob/release-v3.2.0/src/EventStore.ClientAPI/Transport.Tcp/TcpClientConnector.cs#L61

Note:

1) its a new socket
2) Only one operation is called connectasync which is what is throwing the
exception that an operation is in progress.

Greg

On Wed, Aug 19, 2015 at 5:18 PM, Milan Jaric <notifications@github.com>
wrote:

> Hi,
>
> workstation OS: Mac OSX
> ES client API version: 3.0.2 (new 3.1.0 is still not in public NuGet
> repository)
> Mono JIT compiler version 4.0.3 ((detached/d6946b4 Wed Jul 29 14:46:23 EDT
> 2015)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors.
> www.mono-project.com
> TLS: normal
> SIGSEGV: altstack
> Notification: kqueue
> Architecture: x86
> Disabled: none
> Misc: softdebug
> LLVM: yes(3.6.0svn-mono-(detached/a173357)
> GC: sgen
>
> When I start connection to remote event store (server is not on same
> machine) and then unplug network cable, ES Client connection tries to
> connect twice and for some reason schedules connection task before Close
> event appear.
> var cfg = ConnectionSettings
> .Create()
> .EnableVerboseLogging();
>
>         _connection = EventStoreConnection.Create(cfg, _endpoint, "EventStoreStatsCollector");
>
>                    _connection.Connected += (sender, e) => {
>             _logger.Info("Connected to EventStore....SHOWTIME!!!");
>         };
>         _connection.Closed += (sender, e) => {
>             _logger.Error("Connection to EventStore is closed!!!");
>         };
>         _connection.Disconnected += (sender, e) => {
>             _logger.Warning("We have been disconnected from EventStore!");
>         };
>         _connection.ErrorOccurred += (object sender, ClientErrorEventArgs e) => {
>             _logger.Error(e.Exception.Message);
>         };
>         _connection.Reconnecting += (sender, e) => {
>             _logger.Warning("Reconnectiong to EventStore....");
>         };
>         _connection.ConnectAsync().Wait();
>
> In log, entries appear in this order with fatal error at the end (client
> application shutdown since error is unhanded). In case I connect with same
> configuration to localhost it works well and it try to reconnect 10-times
> until connection closed event appear.
>
> [INFO][8/19/2015 2:12:39 PM][Thread 0009] Connected to
> EventStore....SHOWTIME!!!
> [WARNING][8/19/2015 2:12:43 PM][Thread 0009] We have been disconnected
> from EventStore!
> [WARNING][8/19/2015 2:12:43 PM][Thread 0009] Reconnectiong to
> EventStore....
> [INFO][8/19/2015 2:12:43 PM][Thread 0012] Connected to
> EventStore....SHOWTIME!!!
> [WARNING][8/19/2015 2:12:46 PM][Thread 0007] We have been disconnected
> from EventStore!
> [WARNING][8/19/2015 2:12:46 PM][Thread 0007] Reconnectiong to
> EventStore....
> [ERROR][8/19/2015 2:12:46 PM][Thread 0007]
> Default Critical: 0 : The service threw an unhandled exception:
> 'EventStoreStatsCollectorService'. System.InvalidOperationException:
> Operation already in progress
> at System.Net.Sockets.SocketAsyncEventArgs.SetLastOperation
> (SocketAsyncOperation op) [0x00027] in
> /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.3/mcs/class/System/System.Net.Sockets/SocketAsyncEventArgs.cs:162
>
> at System.Net.Sockets.Socket+Worker.Init (System.Net.Sockets.Socket sock,
> System.Net.Sockets.SocketAsyncEventArgs args, SocketOperation op) [0x000a8]
> in
> /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.3/mcs/class/System/System.Net.Sockets/Socket_2_1.cs:475
>
> at System.Net.Sockets.Socket.ConnectAsyncReal
> (System.Net.Sockets.SocketAsyncEventArgs e) [0x0001f] in
> /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.3/mcs/class/System/System.Net.Sockets/Socket_2_1.cs:1606
>
> at System.Net.Sockets.Socket.ConnectAsync
> (System.Net.Sockets.SocketAsyncEventArgs e) [0x00053] in
> /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.3/mcs/class/System/System.Net.Sockets/Socket_2_1.cs:1643
>
> at EventStore.ClientAPI.Transport.Tcp.TcpClientConnector.InitConnect
> (System.Net.IPEndPoint serverEndPoint, System.Action2
> onConnectionEstablished, System.Action2 onConnectionFailed,
> ITcpConnection connection, TimeSpan connectionTimeout) [0x0009d] in :0
> at
> EventStore.ClientAPI.Transport.Tcp.TcpConnection.CreateConnectingConnection
> (ILogger log, Guid connectionId, System.Net.IPEndPoint remoteEndPoint,
> EventStore.ClientAPI.Transport.Tcp.TcpClientConnector connector, TimeSpan
> connectionTimeout, System.Action1 onConnectionEstablished, System.Action2
> onConnectionFailed, System.Action2 onConnectionClosed) [0x00026] in
> <filename unknown>:0
> at EventStore.ClientAPI.Transport.Tcp.TcpClientConnector.ConnectTo
> (ILogger log, Guid connectionId, System.Net.IPEndPoint remoteEndPoint,
> Boolean ssl, System.String targetHost, Boolean validateServer, TimeSpan
> timeout, System.Action1 onConnectionEstablished, System.Action2
> onConnectionFailed, System.Action2 onConnectionClosed) [0x00034] in :0
> at EventStore.ClientAPI.Transport.Tcp.TcpPackageConnection..ctor (ILogger
> log, System.Net.IPEndPoint remoteEndPoint, Guid connectionId, Boolean ssl,
> System.String targetHost, Boolean validateServer, TimeSpan timeout,
> System.Action2 handlePackage, System.Action2 onError, System.Action1
> connectionEstablished, System.Action2 connectionClosed) [0x000e2] in :0
> at
> EventStore.ClientAPI.Core.EventStoreConnectionLogicHandler.EstablishTcpConnection
> (NodeEndPoints endPoints) [0x0008f] in :0
> at EventStore.ClientAPI.Core.EventStoreConnectionLogicHandler.<.ctor>b__9
> (EventStore.ClientAPI.Core.EstablishTcpConnectionMessage msg) [0x00000] in
> :0
> at
> EventStore.ClientAPI.Core.SimpleQueuedHandler+<>c__DisplayClass1`1[EventStore.ClientAPI.Core.EstablishTcpConnectionMessage].b__0
> (EventStore.ClientAPI.Core.Message msg) [0x00000] in :0
> at EventStore.ClientAPI.Core.SimpleQueuedHandler.ProcessQueue
> (System.Object state) [0x00038] in :0
> Stopping service: 'EventStoreStatsCollectorService'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/591>.
>



-- 
Studying for the Turing test

**Comment by mjaric** [comment]
It looks like that this is only issue on case when none of network interfaces has connection to any network or it is disabled! So by unplugging cable or disabling all network interfaces this can be reproduced. As long as network connectivity is available reconnection will work. 

Is it possible to handle this? It is rare case to lose network interface but again .... may happen :) I will send bug note to mono team too if issue isn't open already.

**Comment by jen20** [comment]
I think we can probably catch this, it looks like a managed exception.

Looking through this it looks like you're running on Mono 4 - we've not tested anything there. I'll test to see if this is reproducible with 3.12.1 as well, it's possible it's a regression in Mono.
