### ISSUE TITLE
Log Messages

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#592]
Remove multi-line log messages.

eg: Cluster Changed (old/new printed)

I am marking this up for grabs as this is mostly just looking through logs and changing multiple line logs to multiple single line logs.

**Comment by riccardone** [comment]
is there an already existent process that can be use to "...looking through logs..."?

**Comment by gregoryyoung** [comment]
Not really.

Mostly its reading through logs etc and looking for places where we write a multiple newline log entry and replacing them with multiple single log calls.

As an example Gossip does this when it prints changes in cluster status.

A grep of "\n" will likely go a long way as well

**Comment by riccardone** [comment]
start implementing this story

**Comment by riccardone** [comment]
Which one do you prefer? ...
1. apply the change in the logger (one place) writing multiple line when a "\n" is present
2. change everywhere there is "\n" and add multiple calls to the logger

**Comment by pgermishuys** [comment]
I prefer 2.

**Comment by riccardone** [comment]
ok

**Comment by riccardone** [comment]
Following option number 2.
Just to be sure that I'm on the right, track can you confirm that this is what you expect please?

GossipController.cs

change this...
if (clusterInfo == null)
                    {
                        var msg = string.Format("Received as RESPONSE invalid ClusterInfo from [{0}]. Content-Type: {1}, Body:\n{2}.",
                                                url, response.ContentType, response.Body);
                        Log.Error(msg);
                        Publish(new GossipMessage.GossipSendFailed(msg, endPoint));
                        return;
                    }

to this...
if (clusterInfo == null)
                    {
                        var msg = string.Format("Received as RESPONSE invalid ClusterInfo from [{0}]. Content-Type: {1}, Body: {2}",
                                                url, response.ContentType, response.Body);
                        Log.Error(string.Format("Received as RESPONSE invalid ClusterInfo from [{0}]. Content-Type: {1}",
                                                url, response.ContentType));
                        Log.Error(string.Format("Body: {0}", response.Body));
                        Publish(new GossipMessage.GossipSendFailed(msg, endPoint));
                        return;
                    }

**Comment by pgermishuys** [comment]
In this case it would be nice to retain context instead of just logging "Body: ..."
Something along the lines of
```
Log.Error("Received invalid ClusterInfo from {0} with Content-Type: {1}", ...);
Log.Error("Received invalid ClusterInfo from {0} with Body: {1}", ...);
```

**Comment by riccardone** [comment]
Ok. The final implementation of this fix will be the following. 
Note the '\n' is still present for the Publish(new GossipMessage.GossipSendFailed(msg ) line

if (clusterInfo == null)
                    {
                        var msg = string.Format("Received as RESPONSE invalid ClusterInfo from [{0}]. Content-Type: {1}, Body:\n{2}.",
                                                url, response.ContentType, response.Body);
                        Log.Error(string.Format("Received as RESPONSE invalid ClusterInfo from [{0}]. Content-Type: {1}.",
                                                url, response.ContentType));
                        Log.Error(string.Format("Received as RESPONSE invalid ClusterInfo from [{0}]. Body: {1}.",
                                                url, response.Body));
                        Publish(new GossipMessage.GossipSendFailed(msg, endPoint));
                        return;
                    }

**Comment by pgermishuys** [comment]
There was some work done around this in https://github.com/EventStore/EventStore/pull/696 but requires another scan to ensure that it has been completed.

**Comment by riccardone** [comment]
As you said, this ticket was not completed. I'm doing another scan to fix other parts of the code where there is still this issue.
