### ISSUE TITLE
Add NONagles to TCP Client

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#607]

**Comment by gregoryyoung** [comment]
Basically this is a configuration flag in the client (and possibly back
end) as to whether we should use NODELAY or not on sockets. We use NODELAY
now always, we may want in some cases to use Nagles

On Mon, Aug 24, 2015 at 10:37 PM, Pieter Germishuys <
notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/607>.
>



-- 
Studying for the Turing test
