### ISSUE TITLE
stats.csv has no documentation

### ISSUE THREAD

**Issue by samkanai** [EventStore/EventStore#613]
As a customer, I'd like to know how to interpret this file.

**Comment by jen20** [comment]
At minimum we should add column headings if they are not there already.

-- 
James

**Comment by gregoryyoung** [comment]
We have the there already @jen20 currently it is being written our using a logger and the logger defaults to a rolling log as such the headers are only in the first file (or on restart)

**Comment by jen20** [comment]
We have a number of options here:

- Switch to non-rolling file and disable this by default
- Use `LayoutWithHeaderAndFooter` and hard code the headers in the config file
- Use `LayoutWithHeaderAndFooter` and set the header in monitoring service
- Use `CsvLayout` in NLog and stop doing this outselves

If we go for either of the second options we'll want a new file per run, else the headers will be repeated throughout the file on each startup with is likely to anger parsers.

**Comment by gregoryyoung** [comment]
How do you see 2 working? 

I think 3 would be a better solution (or just stop using nlog for this)

**Comment by ChrisChinchilla** [comment]
@gregoryyoung and @jen20 Is this still needed?
