### ISSUE TITLE
EventStore.Clusternode.exe throws exception and fails to start HTTP server

### ISSUE THREAD

**Issue by ylibrach** [EventStore/EventStore#621]
I'm seeing the following when trying to start the HTTP server on a Windows 10 box:

```
[07476,12,17:28:59.065] ========== [127.0.0.1:2112] SYSTEM INIT...
Exiting with exit code: 1.
Exit reason: Http async server failed to start listening at [http://127.0.0.1:2113/].
[07476,12,17:28:59.088] Starting Normal TCP listening on TCP endpoint: 127.0.0.1:1113.
[07476,15,17:28:59.101] TableIndex initialization...
[07476,15,17:28:59.118] ReadIndex building...
[07476,15,17:28:59.118] ReadIndex rebuilding done: total processed 0 records, time elapsed: 00:00:00.0010004.
[07476,12,17:28:59.126] Starting HTTP server on [http://127.0.0.1:2113/]...
[07476,12,17:28:59.126] Failed to start http server
Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
[07476,12,17:28:59.153] Exiting with exit code: 1.
Exit reason: Http async server failed to start listening at [http://127.0.0.1:2113/].
```

I've tried multiple types of configurations and even just running EventStore.Clusternode.exe without any additional params but no matter what I get this "Object accessed a disposed object" error.

I checked the ports and 2113 is not in use or anything like that.

Any ideas?

**Comment by pgermishuys** [comment]
Are you running Event Store under an Administrator account?

**Comment by ylibrach** [comment]
Yes, local admin on the machine and executing the command in PowerShell running as Administrator.

**Comment by pgermishuys** [comment]
What version of Event Store are you running?

**Comment by ylibrach** [comment]
I tried running EventStore with versions 3.0.0.0, 3.1.0.0 and 3.0.5.0, all are exiting with the same error.

**Comment by pgermishuys** [comment]
can you post the output of
```
netsh http show urlacl
```

**Comment by ylibrach** [comment]
Thanks for that suggestion, this led me in the right direction. The problem was Windows Firewall. There was a reserved URL for 127.0.0.1:2113. I deleted it and then tried to run EventStore again and this time I got a Windows Firewall dialog asking if I want to allow EventStore through. I got this dialog the very first time I ran EventStore as well, but since I checked off all the "allow" boxes, I never thought it would be Windows Firewall. Getting the dialog a second time after I removed the reserved URL made me think that it may be Windows Firewall after all.

I ended up disabling Windows Firewall altogether, restarted and now EventStore is working fine.

**Comment by jen20** [comment]
We've seen this a few times - you have a reservation which looks valid, but prevents it actually starting. It's probably enough that we should put it in an FAQ in the new documentation - will add a label accordingly.

**Comment by kspeakman** [comment]
I know this is an old issue, but ran into it today. I ran the `netsh` command from docs successfully on `http://+:2113/`. But ES still couldn't listen on 2113. It tried to run the netsh command, and afterward still wouldn't start with an access denied error. Turned out, I had an old rule explicitly for 127.0.0.1:2113. I had to run this to clear everything out, then rerun ES and it started without admin.

```
netsh http delete urlacl url=http://+:2113/
netsh http delete urlacl url=http://127.0.0.1:2113/
netsh http delete urlacl url=http://localhost:2113/
```

**Comment by andronachev** [comment]
had more or less the same issue. Event store could not start the web server, moreover the error was "NOT AUTHORIZED". after running the command netsh http show urlacl, I saw that I had 2 URL reservetions, one for http://*:2113/ and the other for http://127.0.0.1:2113/ . I deleted those using netsh http delete urlacl - afterwards it worked fine;  thanks for the tips
