### ISSUE TITLE
ReadAllEventsForward skips events when transactions are used (affects projections also)

### ISSUE THREAD

**Issue by lscpike** [EventStore/EventStore#627]
This is a duplicate of #318, but a more precise diagnosis. I've raised a separate ticket to ensure visibility and avoid extending a large thread.

The most simple description of the bug is:
When calling ReadAllEventsForward using a position that is exactly that of a transaction commit record, the events from the commit are skipped.

The real life scenario to lead to this situation is a race condition between writing a single commit to the TF and completing the transaction (writing TransactionEnd and CommitLogRecord.) When this occurs the ReadAllEventsForward can end with the single commit and nextPosition pointing to where the CommitLogRecord will be located.

As the projections rely on the same reader as ReadAllEventsForward this can lead to missing events from projections also.

**Comment by lscpike** [comment]
Here is a reproduction example of the bug. Needs .net ClientApi.
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EventStore.ClientAPI;
using EventStore.ClientAPI.SystemData;

namespace MissingReadReproduction
{
    class Program
    {
        private static string TestStream = "test1";

        static void Main(string[] args)
        {

            var connection = BuildConnection();

            var cancellationTokenSource = new CancellationTokenSource();

            var task = Start(connection, cancellationTokenSource.Token);

            Console.Out.WriteLine("Press any key...");
            Console.ReadKey();

            cancellationTokenSource.Cancel();
            try
            {
                task.Wait();
            }
            catch (OperationCanceledException)
            {

            }
        }

        private static IEventStoreConnection BuildConnection()
        {
            var connectionSettings = ConnectionSettings.Create()
                .KeepReconnecting()
                .UseConsoleLogger()
                .KeepRetrying()
                .SetHeartbeatInterval(TimeSpan.FromSeconds(10))
                .SetHeartbeatTimeout(TimeSpan.FromSeconds(120))
                .SetDefaultUserCredentials(new UserCredentials("admin", "changeit"))
                .Build();


            var connection = EventStoreConnection.Create(connectionSettings, new Uri(@"tcp:\\localhost:1113"));
            return connection;
        }

        private static async Task Start(IEventStoreConnection eventStoreConnection, CancellationToken token)
        {
            try
            {
                await eventStoreConnection.ConnectAsync();

                await ContrivedExample(eventStoreConnection);

                await RealWorldRaceCondition(eventStoreConnection, token);
                
            }
            catch (Exception e)
            {
                Console.Out.WriteLine("Error:\n" + e);
            }

        }

        private static async Task ContrivedExample(IEventStoreConnection eventStoreConnection)
        {
            using (var transaction = await eventStoreConnection.StartTransactionAsync(TestStream, ExpectedVersion.Any))
            {
                await transaction.WriteAsync(CreateEvents().Take(1));

                var writeResult = await transaction.CommitAsync();

                // Read forward from the commit record. This should include all events from the commit...
                var slice = await eventStoreConnection.ReadAllEventsForwardAsync(writeResult.LogPosition, 100, false);

                if(!slice.Events.Any(_ => _.OriginalStreamId == TestStream))
                {
                    Console.WriteLine("Where has the committed event gone?");
                }
            }
        }

        private static async Task RealWorldRaceCondition(IEventStoreConnection eventStoreConnection, CancellationToken token)
        {
            var position = Position.Start;

            while (!token.IsCancellationRequested)
            {
                using (var transaction = await eventStoreConnection.StartTransactionAsync(TestStream, ExpectedVersion.Any))
                {
                    await transaction.WriteAsync(CreateEvents().Take(1));

                    // Commit our event (async)
                    var commitAsync = transaction.CommitAsync();

                    // Write to the TF a single prepare/commit. This hopefully (and likely) will end up after the TransactionEnd but before the Commit.
                    var append = await eventStoreConnection.AppendToStreamAsync("other", ExpectedVersion.Any, CreateEvents().Take(1));

                    // Read forward. Hopefully the commit hasn't completed at this point. The returned next position will be exactly where the commit should end up.
                    var slice = await eventStoreConnection.ReadAllEventsForwardAsync(position, 100, false);

                    if (slice.Events.Any(_ => _.OriginalStreamId == TestStream))
                    {
                        Console.WriteLine("The read happened after the commit. Bad example. Loop again...");
                    }
                    
                    // Wait for the commit
                    var writeResult = await commitAsync;

                    // This is the scenario where the next read forward skips events.
                    if (slice.NextPosition == writeResult.LogPosition)
                    {
                        Console.WriteLine("Just right");

                        // Try reading the events.
                        var afterSlice = await eventStoreConnection.ReadAllEventsForwardAsync(slice.NextPosition, 100, false);

                        if (!afterSlice.Events.Any(_ => _.OriginalStreamId == TestStream))
                        {
                            Console.WriteLine("Where has the committed event gone?");
                            return;
                        }
                        else
                        {
                            Console.WriteLine("Bug has been fixed!");
                            return;
                        }
                    }

                    position = slice.NextPosition;

                }
            }
        }

        private static IEnumerable<EventData> CreateEvents()
        {
            var data = new byte[0];
            while (true)
                yield return new EventData(Guid.NewGuid(), "TestEvent", false, data, data);
        }

    }
}
```

**Comment by gregoryyoung** [comment]
:+1: looking at it.

**Comment by lscpike** [comment]
Tracked it down to the AllReader, but the complexity of being able to partially read a commit (maxCount) means I can't see a simple solution.

**Comment by gregoryyoung** [comment]
@lscpike from looking through this I think you should be reading from the prepare/commit position of the first prepare + the commit. When starting from the last commit I would expect it to read past the commit.

If you just run a loop on all reader do all events get read?

**Comment by lscpike** [comment]
Sorry it's been a while so I might be wrong, but isn't the real world test case using a loop on the all reader?

**Comment by gregoryyoung** [comment]
@lscpike I see:

var slice = await eventStoreConnection.ReadAllEventsForwardAsync(position, 100, false);

**Comment by hayley-jean** [comment]
@lscpike, in the code sample you've provided it looks like you expect the log position returned by `var commitAsync = transaction.CommitAsync()` to be the log position of the beginning of the transaction. 

That position is actually the position of the commit record for the transaction, which would be written after all the events in the transaction. So reading forwards from it _shouldn't_ return the events that were in the transaction.

**Comment by lscpike** [comment]
I _am_ expecting the commit record. I'm just demonstrating the fact that read all from the commit doesn't return the commit contents as you've stated. That behaviour means ReadAllEventsForwardAsync can result in skipping events. This is shown in the RealWorldRaceCondition. 

Again this is just a reproduction test case. I came across this when figuring out why projections were skipping events. The problem is very real and makes transactions completely unusable. We've just stopped using them as we only added their usage as an optimisation for an edge case..

**Comment by gregoryyoung** [comment]
@lscpike reading through your real world test some more. The ContrivedExample is expected behaviour. As @hayley-jean points out.

So what you are trying to get is:

StartTransaction
WriteToTransaction
WriteOutsideOfTransaction
Commit

(I am actually surprised you can reliably get the WriteOutsideOfTransaction reliably before the commit)

Then read from the commit position (checking that its the same one that was given back on the read).

If anything the issue seems to be on the position returned from the first read. We have some tests around similar and can write one around this case. EG https://github.com/EventStore/EventStore/blob/release-v3.7.0/src/EventStore.Core.Tests/Services/Storage/Transactions/when_having_two_intermingled_transactions_and_some_uncommited_prepares_in_the_end_read_index_should.cs#L124

**Comment by lscpike** [comment]
I've modified the real world scenario to fix the initial read position as that could cause a couple of incorrect loops. I'm running against a blank local node. It does indeed hit the scenario very quickly. I'll explain why.

Luckily I'm working today... I haven't gone through all your tests but it must not cover this case. Here are the details.

At a LogRecord level we're trying to get:

Prepare/BeginTransaction
Prepare/Data (in transaction)
Prepare/EndTransaction
Prepare/Begin+End+Data/IsCommited (outside transaction)
Commit (from transaction)

To achieve this isn't hard due to the 3 step nature of the CommitTrasaction and the 2 step nature of a single append. If you fire both off sequentially and without waiting for results you'll most likely end up with the client library sending both requests in the same TCP packet. The EventStore node then puts them both onto the internal bus sequentially and you'll get the following message execution:

Thread X:
Client.TransactionCommit -> StorageMessage.CheckStreamAccess
ClientMessage.WriteEvents -> StorageMessage.CheckStreamAccess
Thread R1:
StorageMessage.CheckStreamAccess -> StorageMessage.CheckStreamAccessCompleted
Thread R2:
StorageMessage.CheckStreamAccess -> StorageMessage.CheckStreamAccessCompleted
Thread X:
StorageMessage.CheckStreamAccessCompleted -> StorageMessage.WritePrepares
StorageMessage.CheckStreamAccessCompleted -> StorageMessage.WritePrepares
Thread W:
StorageMessage.WritePrepares -> Write the Prepare/EndTransaction
StorageMessage.WritePrepares -> Write Prepare/Begin+End+Data+Commited
Thread Storage Chaser:
Prepare -> StorageMessage.PrepareAck
Prepare -> StorageMessage.CommitAck
Thread X:
StorageMessage.PrepareAck -> StorageMessage.WriteCommit
StorageMessage.CommitAck -> ClientMessage.WriteEventsCompleted
Thread W:
StorageMessage.WriteCommit -> Write the Commit

I'll stop there as we have what we need to see the skipped events.

From the AllReader perspective this is what happens:

ReadAllForward -> nothing there -> returns LP1
_Write BeginTransaction at LP1_
_Write Data at LP2_
ReadAllForward -> Finds only begin and data so skips to LP3 -> returns LP1
_Write EndTransaction at LP2_
_Write Data+Committed at LP3_
ReadAllForward LP1 -> Finds begin, data, end and committed data -> returns LP4 + committed data
_Write Commit at LP4_
ReadAllForward from LP4 -> Finds commit and goes back to read from LP1. Each event in the transaction is discarded because LP4 == LP4 and LP2 < LP4. See AllReader.cs:120@7994e0fe -> returns LP5 only with no events.

AllReader has never returned the event.

You state that reading forward from the commit record log position should not return the commit contents. This may well be current expected behaviour but sounds incorrect to me. What scenario depends on this behaviour?

**Comment by gregoryyoung** [comment]
"You state that reading forward from the commit record log position should not return the commit contents. This may well be current expected behaviour but sounds incorrect to me. What scenario depends on this behaviour?"

It depends what the prepare part of the position is. If both point at the commit it should return nothing. EG:

prepare 1
prepare 2
prepare 3
commit 5

1/5 should return stuff. 5/5 should not.

**Comment by lscpike** [comment]
There's only 2 situations where 5/5 will be returned as far as I can see:

1. The commit is the last commit/committed prepare in the transaction log.
2. This scenario.

The first case seems incorrect also as it results in a re-parse of the whole transaction which will never return any data. The second scenario as I've shown causes skipped data.

Why not make 5/5 a special case meaning prepare = start of transaction and change 1 to return the commit post position?

I'm not sure what else I can add here so I'll leave this with you. I assume the issue is clear to you now?

**Comment by gregoryyoung** [comment]
@lscpike yep I can see the issue here. Will try to write up some tests around it next week (or @hayley-jean can).
