### ISSUE TITLE
Add position to Recorded Event?

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#629]
Adding the position to a recorded event would be quite easy from a client API perspective and could allow global ordering for single log systems.

What do others think?

**Comment by bmavity** [comment]
I think this could be useful. Are there any drawbacks?

**Comment by jen20** [comment]
It doesn't look like this can be done without a protocol change:

```
message EventRecord {
	required string event_stream_id = 1;
	required int32 event_number = 2;
	required bytes event_id = 3;
	required string event_type = 4;
	required int32 data_content_type = 5;
	required int32 metadata_content_type = 6;
	required bytes data = 7;
	optional bytes metadata = 8;
	optional int64 created = 9;
	optional int64 created_epoch = 10;
}
```

**Comment by gregoryyoung** [comment]
It would be a protocol change

optional int64 prepare_pos = 11;
optional int64 commit_pos = 12;


On Wed, Sep 2, 2015 at 11:31 PM, James Nugent <notifications@github.com>
wrote:

> It doesn't look like this can be done without a protocol change:
>
> message EventRecord {
>     required string event_stream_id = 1;
>     required int32 event_number = 2;
>     required bytes event_id = 3;
>     required string event_type = 4;
>     required int32 data_content_type = 5;
>     required int32 metadata_content_type = 6;
>     required bytes data = 7;
>     optional bytes metadata = 8;
>     optional int64 created = 9;
>     optional int64 created_epoch = 10;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/629#issuecomment-137250615>
> .
>



-- 
Studying for the Turing test

**Comment by ArturDorochowicz** [comment]
Is it something that - in case of a link event - would allow getting a Position of a _linked to_ event (when querying with resolveLinkTos=true)? That would be something I was looking for.

**Comment by jen20** [comment]
Not without resolving it - the links are `number@streamname` format - you would be able to get it if it was resolved though, yes (which I think is what you're asking, @ArturDorochowicz?)

**Comment by ArturDorochowicz** [comment]
@jen20 Yes, that's exactly it. We currently have ```ResolvedEvent.OriginalPosition```, but AFAIK in the case of a link it is the position of the link, not of the _linked to_ event. I'm interested in the position of the _linked to_ event, of course with resolving enabled on the querying API (like ReadAllEventsForward).

So this is great news. Any ETA? :wink:

BTW why is ```ResolvedEvent.OriginalPosition``` nullable? When can it be null?

**Comment by jen20** [comment]
It will probably be in v3.3.0 (tbd though).

It's nullable because the position isn't always available when we trigger the subscription without reasonably substantial work - I forget the exact cases it's null though.

**Comment by gregoryyoung** [comment]
So the position can be null when a link points to a deleted event.



On Thursday, September 10, 2015, James Nugent <notifications@github.com>
wrote:

> It will probably be in v3.3.0 (tbd though).
>
> It's nullable because the position isn't always available when we trigger
> the subscription without reasonably substantial work - I forget the exact
> cases it's null though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/629#issuecomment-139059834>
> .
>


-- 
Studying for the Turing test

**Comment by ArturDorochowicz** [comment]
> So the position can be null when a link points to a deleted event.

Hm.. What I'm seeing in a quick test (on 3.2.1) is that links simply all have ```OriginalPosition==null```. Not sure how it relates to your statement @gregoryyoung, though technically it stays correct.

If it's not yet clear I'm very much in favor of adding position to RecordedEvent.

For the time being, I noticed that I can dig into link event metadata and get ```$c``` and ```$p``` properties to construct the position off the pointed event. Or so it seems ...

**Comment by jen20** [comment]
We are going to add it, but it needs thought as its a protocol change which
may break other people.

>

-- 
James

**Comment by iberodev** [comment]
I'm investigating the meaning of commit and prepare position.I can see a Position in EventResolved and EventResolved contain an EventRecorded. Is this issue still open? or this has been implemented in a different way?

**Comment by jageall** [comment]
This isn't available when reading by stream unfortunately because of the design of indexes.
