### ISSUE TITLE
Indexing projection faulted with a NullReferenceException

### ISSUE THREAD

**Issue by nicdex** [EventStore/EventStore#652]
Running a simple indexing projection faulted with a NullReferenceException after 1520 events processed.

fromCategory('object')
    .foreachStream()
    .whenAny(function(s,ev){
            linkTo('objects', ev);
    });

Running EventStore 3.1.0 on Ubuntu 15.04 x64 with plenty of memory and disk space left.

I know projections are still in beta, do you have idea when they'll get stable?

Thanks

**Comment by gregoryyoung** [comment]
This autumn. What is the actual stack trace?

**Comment by gregoryyoung** [comment]
also be careful with emit and linkTo IIRC if they end up with null they can cause an issue

**Comment by gregoryyoung** [comment]
BTW this projection could just be the Category projection.

Try enabling it and accessing $ce-objects

**Comment by nicdex** [comment]
Here's a link to the error log containing the callstack.

http://nicdex.com/files/dump/192.168.1.11-2113-cluster-node-err.log

I didn't know about the $ce-objects projection, nice :) 
I'll use that instead. Does it require credentials to be used like the $all ?

**Comment by nicdex** [comment]
Sorry there's more than one error in there... search for parimutualEvents. That's the name of the projection that failed.

**Comment by pgermishuys** [comment]
There is one issue that is not related to yours but it would appear like you have upgraded to 3.1.0. the $users projection is no longer needed and can safely be deleted.

**Comment by nicdex** [comment]
Using $ce projections is working well so far.

**Comment by pgermishuys** [comment]
Quite a number of issues in this related to multiple projections emitting to the same stream, $users projection faulting and then event 1522. Is there anything special about this event?

**Comment by nicdex** [comment]
Nope just a regular event. The $users projection faulted, so maybe that crashed the projection core. Also it might have been affected by issue 678. Hard to tell when the bad kernel was introduced.

**Comment by nicdex** [comment]
Sorry just to clarify the projection was only linking to the event in a new stream, so I don't see how the content of the event could affect it. Also after a restart of the eventstore, the projection restarted and processed the event. I'll look if I can find the event, we're testing so I think we might have deleted that stream since then.

**Comment by pgermishuys** [comment]
I don't know what else could have caused it other than the original stream being deleted. The particular issue was resolved here (https://github.com/EventStore/EventStore/commit/28c2abc322927a3a5e501759cee3c716ee506379)

If this pops up again with a newer version of Event Store, please re-open the issue. Going to close this issue for now.
