### ISSUE TITLE
Connection string parsing in 3.2.0 is culture sensitive

### ISSUE THREAD

**Issue by ArturDorochowicz** [EventStore/EventStore#668]
AFAIS the connection string parsing is culture sensitive, I suspect it wasn't intended. Also the ```decimal``` case uses ```double.Parse()``` which may also be a bug?

See:
https://github.com/EventStore/EventStore/blob/512f3aff1024d77385a5b8561fb820a812d37627/src/EventStore.ClientAPI/ConnectionString.cs#L25

I can highly recommend FxCop / VS CodeAnalysis to weed such issues out.

**Comment by jen20** [comment]
Agreed this should be using `CultureInfo.InvariantCulture`.

**Comment by gregoryyoung** [comment]
My guess is it hasn't been an issue as its not used :) :+1:

**Comment by jen20** [comment]
Fixed in Event Store 3.2.1
