### ISSUE TITLE
I keep getting NullReferenceException running an instance on AWS

### ISSUE THREAD

**Issue by nicdex** [EventStore/EventStore#678]
[PID:02899:018 2015.09.12 23:23:15.466 FATAL GLOBAL-LOGGER       ] Global Unhandled Exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object
  at EventStore.Core.Services.TimerService.ThreadBasedScheduler.DoTiming () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

Will update with more details as I investigate.

**Comment by nicdex** [comment]
Still confirming this, but it looks like this happens when I have an instance with more than one core.

**Comment by gregoryyoung** [comment]
More details would be useful

what node type? are you setting threads count if a tiny?

A quick search of the list

On Sun, Sep 13, 2015 at 2:28 AM, Nicolas Dextraze <notifications@github.com>
wrote:

> [PID:02899:018 2015.09.12 23:23:15.466 FATAL GLOBAL-LOGGER ] Global
> Unhandled Exception occurred.
> System.NullReferenceException: Object reference not set to an instance of
> an object
> at EventStore.Core.Services.TimerService.ThreadBasedScheduler.DoTiming ()
> [0x00000] in :0
> at System.Threading.Thread.StartInternal () [0x00000] in :0
>
> Will update with more details as I investigate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/678>.
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Also what version? We have seen this same issue on older versions without
an environment variable set

On Sun, Sep 13, 2015 at 2:36 AM, Greg Young <gregoryyoung1@gmail.com> wrote:

> More details would be useful
>
> what node type? are you setting threads count if a tiny?
>
> A quick search of the list
>
> On Sun, Sep 13, 2015 at 2:28 AM, Nicolas Dextraze <
> notifications@github.com> wrote:
>
>> [PID:02899:018 2015.09.12 23:23:15.466 FATAL GLOBAL-LOGGER ] Global
>> Unhandled Exception occurred.
>> System.NullReferenceException: Object reference not set to an instance of
>> an object
>> at EventStore.Core.Services.TimerService.ThreadBasedScheduler.DoTiming ()
>> [0x00000] in :0
>> at System.Threading.Thread.StartInternal () [0x00000] in :0
>>
>> Will update with more details as I investigate.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/678>.
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by nicdex** [comment]
OSS cluster node with a single node.
event store versions: 3.1.0 and 3.2.1
ami: default ubuntu x64 (hvm)
machine: m4.large (2 vCPU 8Gb RAM EBS optimized SSD)
Not setting any threads count.

**Comment by gregoryyoung** [comment]
Try setting: env var MONO_GC_DEBUG=clear-at-gc



On Sun, Sep 13, 2015 at 2:42 AM, Nicolas Dextraze <notifications@github.com>
wrote:

> OSS cluster node with a single node.
> event store versions: 3.1.0 and 3.2.1
> ami: default ubuntu x64 (hvm)
> machine: m4.large (2 vCPU 8Gb RAM EBS optimized SSD)
> Not setting any threads count.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/678#issuecomment-139829145>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
As you can see here
https://github.com/EventStore/EventStore/blob/release-v3.3.0/src/EventStore.Core/Services/TimerService/ThreadBasedScheduler.cs#L46
there isn't really much opportunity for a NRE on a random iteration.

On Sun, Sep 13, 2015 at 2:43 AM, Greg Young <gregoryyoung1@gmail.com> wrote:

> Try setting: env var MONO_GC_DEBUG=clear-at-gc
>
>
>
> On Sun, Sep 13, 2015 at 2:42 AM, Nicolas Dextraze <
> notifications@github.com> wrote:
>
>> OSS cluster node with a single node.
>> event store versions: 3.1.0 and 3.2.1
>> ami: default ubuntu x64 (hvm)
>> machine: m4.large (2 vCPU 8Gb RAM EBS optimized SSD)
>> Not setting any threads count.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/678#issuecomment-139829145>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by nicdex** [comment]
I'm a bit busy getting ready for an open alpha tomorrow, for now I'll run single core 4gb ram, should be enough. I'll try that env var in the next days and update here if it fix the issue.

Thanks for your help Gregoire LeJeune :)

**Comment by nicdex** [comment]
Confirming that going back to single core is also fixing the issue. 

I have a couple of additional questions:
1) Why isn't that option (env var) enabled by default? Does it have any side-effects?
2) Also it seems that this is mono issue. Would I be better running the EventStore on Windows .Net instead?

Thanks

**Comment by gregoryyoung** [comment]
1) Why isn't that option (env var) enabled by default? Does it have any
side-effects?
2) Also it seems that this is mono issue. Would I be better running the
EventStore on Windows .Net instead?

Recent binaries set by default.

On Sun, Sep 13, 2015 at 3:35 AM, Nicolas Dextraze <notifications@github.com>
wrote:

> Confirming that going back to single core is also fixing the issue.
>
> I have a couple of additional questions:
> 1) Why isn't that option (env var) enabled by default? Does it have any
> side-effects?
> 2) Also it seems that this is mono issue. Would I be better running the
> EventStore on Windows .Net instead?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/678#issuecomment-139832022>
> .
>



-- 
Studying for the Turing test

**Comment by nicdex** [comment]
What do you mean by recent? because like I mentioned previously I also tried with v3.2.1 which is the latest via the debian repository and I still had that issue.

**Comment by jen20** [comment]
3.2.1 from the apt repository has Mono statically linked and sets that
variable so it's unlikely to be that.

Can you try setting `MONO_THREADS_PER_CPU=100`  though on the dual core box
though? It's conceivable that this isn't being detected properly (though it
should be). I often run tests on m4.large instance on Ubuntu 14.04 without
seeing this.

**Comment by nicdex** [comment]
I'll try that next week. For now I've seen a similar issue when under heavy load on a single core machine (m3.medium).

[PID:01668:024 2015.09.13 00:09:51.222 FATAL GLOBAL-LOGGER       ] Global Unhandled Exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object
  at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (System.Object o) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

Is the MONO_GC_DEBUG=clear-at-gc also set on version 3.1.0 from the debian repository?

**Comment by jen20** [comment]
Yes, I have seen that on low spec machines too. That's deep inside mono and
there is little we can do about it (we couldn't even catch it in there if
we wanted to). clear-at-gc is set on every version that has ever been in
one of our apt repositories. Do you have a script you're using to set this
up that you can share?

-- 
James

**Comment by nicdex** [comment]
Do you mean the environment setup or the data setup?

**Comment by jen20** [comment]
Environment - things like the network config, instance creation etc

-- 
James

**Comment by gregoryyoung** [comment]
Try setting the environment variable MONO_GC_DEBUG=clear_at_gc is the issue
still there with the binaries? We have seen issues like this without that
variable set. The packages should be setting it. If that fixes will look at
the debian packaging.

On Sun, Sep 13, 2015 at 3:39 AM, Nicolas Dextraze <notifications@github.com>
wrote:

> What do you mean by recent? because like I mentioned previously I also
> tried with v3.2.1 which is the latest via the debian repository and I still
> had that issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/678#issuecomment-139832137>
> .
>



-- 
Studying for the Turing test

**Comment by nicdex** [comment]
Got two of those at 3AM here while server was under no load.

[PID:01366:025 2015.09.13 00:09:33.904 FATAL GLOBAL-LOGGER       ] Global Unhandled Exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object
  at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (System.Object o) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
[PID:01668:024 2015.09.13 00:09:51.222 FATAL GLOBAL-LOGGER       ] Global Unhandled Exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object
  at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (System.Object o) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

Setting the MONO_GC_DEBUG=clear_at_gc now, I hope this fix the issue, will update at the end of the day.

**Comment by gregoryyoung** [comment]
These issues are all ones that that flag has historically corrected.
Perhaps it is not being properly set in the debian environment but it
should be being set.

On Sun, Sep 13, 2015 at 6:11 PM, Nicolas Dextraze <notifications@github.com>
wrote:

> Got two of those at 3AM here while server was under no load.
>
> [PID:01366:025 2015.09.13 00:09:33.904 FATAL GLOBAL-LOGGER ] Global
> Unhandled Exception occurred.
> System.NullReferenceException: Object reference not set to an instance of
> an object
> at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (System.Object
> o) [0x00000] in :0
> at System.Threading.Thread.StartInternal () [0x00000] in :0
> [PID:01668:024 2015.09.13 00:09:51.222 FATAL GLOBAL-LOGGER ] Global
> Unhandled Exception occurred.
> System.NullReferenceException: Object reference not set to an instance of
> an object
> at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (System.Object
> o) [0x00000] in :0
> at System.Threading.Thread.StartInternal () [0x00000] in :0
>
> Setting the MONO_GC_DEBUG=clear_at_gc now, I hope this fix the issue, will
> update at the end of the day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/678#issuecomment-139886193>
> .
>



-- 
Studying for the Turing test

**Comment by nicdex** [comment]
So I added MONO_GC_DEBUG=clear_at_gc in /etc/environment. it should be taken into account if I restart the service with sudo service eventstore stop then start.

**Comment by gregoryyoung** [comment]
Yes. Just to be sure I might also make sure that the environment variable
is set for the user event store is running as. We have seen many cases
where users have made mistakes on setting environment variables.

On Sun, Sep 13, 2015 at 6:15 PM, Nicolas Dextraze <notifications@github.com>
wrote:

> So I added MONO_GC_DEBUG=clear_at_gc in /etc/environment. it should be
> taken into account if I restart the service with sudo service eventstore
> stop then start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/678#issuecomment-139886498>
> .
>



-- 
Studying for the Turing test

**Comment by jen20** [comment]
It needs to be `clear-at-gc` not `clear_at_gc`. You may be better off editing the upstart script to include any extra flags rather than relying on the environment.

**Comment by gregoryyoung** [comment]
Sorry my bad.

On Sun, Sep 13, 2015 at 6:32 PM, James Nugent <notifications@github.com>
wrote:

> It needs to be clear-at-gc not clear_at_gc. You may be better off editing
> the upstart script to include any extra flags rather than relying on the
> environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/678#issuecomment-139887803>
> .
>



-- 
Studying for the Turing test

**Comment by nicdex** [comment]
How do I check that this environment variable is set for that user, when I do sudo su eventstore it says the user is not available.

**Comment by jen20** [comment]
It's a non-interactive user (the login shell is set to `/sbin/nologin`)

**Comment by nicdex** [comment]
Ok I confirm, I did sudo su -s /bin/bash eventstore, then echo $MONO_GC_DEBUG and I see clear-at-gc

**Comment by jen20** [comment]
[This line](https://github.com/EventStore/EventStore/blob/oss-v3.2.1/scripts/package-mono/package-ubuntu.sh#L102) does the same during the build process (we set environment variable when the bootstrapping wrapper program starts) so I am 99.999% confident this isn't going to make any difference. It would be more fruitful to play with `MONO_THREADS_PER_CPU` I think. If you can share a setup script I can take a look here - this isn't something we've seen even under heavy load testing.

**Comment by nicdex** [comment]
I'm seeing those issue with single core too, they're similar but not the same. On dual core the NRE arise in the EventStore.Core.Services.TimerService.ThreadBasedScheduler.DoTiming and in single core it arise in EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue. I know those issues are related to mono. It is very unsettling because I've been using the eventstore on a ubuntu vm for the past month in dev. Somehow on AWS it goes to hell. As for environment setup, there is not script, I just created a new m4.large instance from the AWS console, then install the eventstore following the procedure in the documentation at www.geteventstore.com. Then when the issue arise I recreated the instance, still the same issue, then I recreated a new instance, this time a m3.medium. Problem occurs less frequently with one core.

**Comment by jen20** [comment]
What AMI, region, placement etc?

>

-- 
James

**Comment by nicdex** [comment]
I confirm adding MONO_GC_DEBUG=clear-at-gc didn't fix the issue. Seeing the same error again.

[PID:03046:022 2015.09.13 17:53:23.958 FATAL GLOBAL-LOGGER       ] Global Unhandled Exception occurred.
System.NullReferenceException: Object reference not set to an instance of an object
  at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (System.Object o) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

AMI: ubuntu-trusty-14.04-amd64-server-20150325 (ami-d05e75b8)
Region: us-east
Availability zone: us-east-1b
The machine is in a VPC it has only one network interface and listen on 10.0.1.200.

**Comment by jen20** [comment]
Ok I will try to reproduce this

-- 
James

**Comment by pgermishuys** [comment]
@nicdex we have managed to replicate your issue. However, we have been using the following ami that doesn't exhibit the same behaviour we've been seeing with the one you have been using.

`ami-6889d200`
`ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-20150305`

We ran the following prior to installing event store.
```
sudo apt-get -y dist-upgrade
sudo apt-get -y update
```

Please try with the ami mentioned above and let us know if you have any further issues.

**Comment by nicdex** [comment]
Thanks a lot guy, I will try this as soon as possible. For now I have switched to a windows machine. If I can confirm that this fix the issue, I will switch back to ubuntu.

**Comment by pgermishuys** [comment]
@nicdex any feedback on those AMIs we suggested?

**Comment by nicdex** [comment]
Sorry, was busy a lot lately, will try this today.

**Comment by nicdex** [comment]
Ok just re-deployed an instance using that ami. Did the two apt-get command, but they didn't update anything, not sure if it's normal. Anyway I installed eventstore-oss and restored my old data, so far no exception. Last time it was producing exception even if it was sitting idle, so if it goes a day without exceptions I think it should be good.

**Comment by gregoryyoung** [comment]
We didn't see any exceptions on our side so I guessing it will pass.

The next thing is what is the difference between them?!?!

On Wed, Sep 16, 2015 at 7:32 PM, Nicolas Dextraze <notifications@github.com>
wrote:

> Ok just re-deployed an instance using that ami. Did the two apt-get
> command, but they didn't update anything, not sure if it's normal. Anyway I
> installed eventstore-oss and restored my old data, so far no exception.
> Last time it was producing exception even if it was sitting idle, so if it
> goes a day without exceptions I think it should be good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/678#issuecomment-140795779>
> .
>



-- 
Studying for the Turing test

**Comment by pgermishuys** [comment]
We did some further investigation regarding this issue and it appears that `3.13.0-48-generic` is a bad kernel version for `mono 3.12.1` which is what we are currently building against

We have also found however that upgrading to `3.13.0-63-generic` is good and you should be able to do this quite easily using the following commands

```
sudo apt-get update
sudo apt-get install linux-image-3.13.0-63-generic
```

**Comment by gregoryyoung** [comment]
Yep confirmed as a kernel issue:

Its here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1450584

**Comment by nicdex** [comment]
Thanks very much for your help all.

**Comment by siamak-haschemi** [comment]
I had the same problem with the current 

- **EventStore 3.9.0** 
- and Kernel **4.4.0-34-generic** 
- on **Ubuntu 14.04.5 LTS**

Switching to kernel **3.19.0-64-generic** solved my issue.

With being root:
```
$ apt-get install linux-image-3.19.0-64-generic

$ vim /etc/default/grub

...
GRUB_DEFAULT="1>2"
...

$ update-grub
$ reboot
```

Just in case someone has the same problem ...

**Comment by PaulGrimshaw** [comment]
We just recently had the same problem, and folloing @siamak-haschemi instructions solved it.
