### ISSUE TITLE
Issue with UI

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#683]
https://github.com/EventStore/docs.geteventstore.com/pull/136

I'm actually now having trouble not reproducing this error given many different scenarios, including the one above I thought had resolved it.

Log into EventStore UI
Open Developer Tools (I use F12)
Stop EventStore
Delete EventStore Data and Log directories
Clear all cookies for 127.0.0.1
Start EventStore
Navigate to http://127.0.0.1:2114 (dev tools still open)
Log into ES
(optionally) Enable all projections
(optionally) push $settings with $all everywhere
Open Query page
Run a simple query without issue (e.g. fromStream("Activity").whenAny(function(s,e) { return { Something: 0 }; }); returns state result)
Hit 'Debug'
Server shows..
[04964,27,14:08:00.941] Read Request Body Failed.
Value cannot be null.
Parameter name: token
[04964,22,14:08:02.941] Read Request Body Failed.
Value cannot be null.
Parameter name: token
[04964,08,14:08:04.941] Read Request Body Failed.
Value cannot be null.
Parameter name: token
[04964,08,14:08:06.941] Read Request Body Failed.
Value cannot be null.
Parameter name: token
[04964,09,14:08:08.941] Read Request Body Failed.
Value cannot be null.
Parameter name: token
[04964,23,14:08:09.942] Read Request Body Failed.
Value cannot be null.
Parameter name: token
[04964,21,14:08:11.942] Read Request Body Failed.
Value cannot be null.
Parameter name: token

**Comment by pgermishuys** [comment]
The problem is probably related to
https://github.com/EventStore/EventStore/blob/release-v3.3.0/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs#L322
and fails as a result of
https://github.com/EventStore/EventStore/blob/release-v3.3.0/src/EventStore.Projections.Core/Services/Management/ManagedProjection.cs#L331

This should also affect one time projections (projections that run until completion).
The debug then needs to be reworked to reset the projection at the time of debugging

**Comment by ianbattersby** [comment]
Could using a 2.x version (in particular it's UI) be a temporary alternative?

**Comment by pgermishuys** [comment]
The `debug-queries` branch (https://github.com/EventStore/EventStore.UI/tree/debug-queries) should solve this particular issue.
You can replace your current UI with the one from that branch.

If you have any issues, please don't hesitate to jot them down in here.

**Comment by ianbattersby** [comment]
Awesome, so far so good ;)

**Comment by gregoryyoung** [comment]
Great can we close down the issue? It will be in next release as well.

On Wed, Sep 16, 2015 at 6:11 PM, Ian Battersby <notifications@github.com>
wrote:

> Awesome, so far so good ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/683#issuecomment-140771985>
> .
>



-- 
Studying for the Turing test

**Comment by ianbattersby** [comment]
One more, which I can happily move to a new Issue if you wish?

* Log into http://localhost:2114
* Run query with JS that has an error: 
```
fromCategory("SomeThing").when({
    $init : function(s,e) { return { Count : 0 } },
    $ny : function(s,e) { s.Count++; return s; }});
```
* The UI doesn't return or update the state - which is understandable - but there is NO feedback in the UI that this failed. Neither does the console show anything
* Hit "DEBUG" (as you would when something doesn't work)
* Hit "Stop"
* Hit "Run Step"

Console says;
```
[32368,16,16:36:21.131] Error while processing message EventStore.Projections.Core.Messages.EventReader
intSuggested in queued handler 'Projection Core #0'.
Specified method is not supported.
```

UI says;
![image](https://cloud.githubusercontent.com/assets/185776/9911313/6da76562-5c99-11e5-82d5-95210e4318f6.png)

Log viewer:
(nothing)

I'd expect here at least the error in the console to come back to the UI, perhaps in the Log Viewer window or something!? What am I missing?

**Comment by pgermishuys** [comment]
Thanks for the feedback on the UI. For all the UI related issues, let's move that over to the UI (http://github.com/EventStore/EventStore.UI) repository.

**Comment by pgermishuys** [comment]
I've opened this issue on the UI repository as https://github.com/EventStore/EventStore.UI/issues/75

**Comment by ianbattersby** [comment]
As a small aside, if you hit "Update" more than once in debug mode, it pushes an empty query because it hasn't had time to reload the JS query back into the browser window.

**Comment by pgermishuys** [comment]
New issue created at https://github.com/EventStore/EventStore.UI/issues/77
