### ISSUE TITLE
Client API: EventStoreConnection.Create overload fails with NullReferenceException

### ISSUE THREAD

**Issue by ascjones** [EventStore/EventStore#684]
This [overload to Create](https://github.com/EventStore/EventStore/blob/release-v3.3.0/src/EventStore.ClientAPI/EventStoreConnection.cs#L45) fails with a null reference exception, because Uri is always null.

```C#
public static IEventStoreConnection Create(ConnectionSettings connectionSettings, string connectionName = null)
        {
            return Create(connectionSettings, (Uri)null, connectionName);
        }
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EventStore.ClientAPI.EventStoreConnection.GetCredentialFromUri(Uri uri)
   at EventStore.ClientAPI.EventStoreConnection.Create(ConnectionSettings connectionSettings, Uri uri, String connectionName)
```

**Comment by gregoryyoung** [comment]
Hmm will fix. Good catch

On Wed, Sep 16, 2015 at 3:54 PM, Andrew Jones <notifications@github.com>
wrote:

> This overload to Create
> <https://github.com/EventStore/EventStore/blob/release-v3.3.0/src/EventStore.ClientAPI/EventStoreConnection.cs#L45>
> fails with a null reference exception, because Uri is always null.
>
> public static IEventStoreConnection Create(ConnectionSettings connectionSettings, string connectionName = null)
>         {
>             return Create(connectionSettings, (Uri)null, connectionName);
>         }
>
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at EventStore.ClientAPI.EventStoreConnection.GetCredentialFromUri(Uri uri)
>    at EventStore.ClientAPI.EventStoreConnection.Create(ConnectionSettings connectionSettings, Uri uri, String connectionName)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/684>.
>



-- 
Studying for the Turing test
