### ISSUE TITLE
Feature Request - Examples as PostMan / Fiddler collection

### ISSUE THREAD

**Issue by BoasE** [EventStore/EventStore#685]
Hope this is the right place for a FeatureRequest
It would be great to have the examples targeting the REST api ina fiddler  / postman collection

**Comment by ianbattersby** [comment]
:+1:

We have often talking about some kind of recipe book in the office, although our thinking being around curl examples more than anything.

**Comment by jen20** [comment]
This isn't a bad way to distribute examples, potentially more obvious to people than cURL. However, we'd have to look at auto generating the collection from a git repository. The file format for Postman looks to be JSON. This is also [importable into Paw](https://luckymarmot.com/paw/doc/Import_Postman_Collections). Not sure on what Fiddler uses or whether such a thing is possible.

**Comment by Gentlehag** [comment]
Fiddler can ex and import many formats like (P)CAP, IE12 NetXML, Json HTTP Archive.

I'm not sure but isn't JsonHTTP compatible to postman ?

**Comment by FatherDougal** [comment]
I could help out writing a Postman collection.  You guys could host that collection via Postman, meaning users will always have an up to date definition of the api.

**Comment by pgermishuys** [comment]
That would be kind @FatherDougal. Thanks for the offer.

**Comment by jasonmitchell** [comment]
I'm assuming this isn't being worked on given how long ago the last update was. I already have quite a bit of the HTTP api in a Postman - I can update what I have to make them match what is in the docs and to include the projections api for 4.0

**Comment by jasonmitchell** [comment]
I spent a bit of time going through the docs updating my Postman collection.  This is what I have at the minute: https://www.getpostman.com/collections/5841d6b0bcf6b01118d4

For the requests that need data (such as reading streams and projections) I've made the assumption the verify has been run in the test client.  Some requests (like competing consumers) I have opted to keep simple in favour of people using the documentation to understand every property that can be sent in the body.  There's possibly useful scenarios I have missed but I'm happy to update based on suggestions.

What is the best way to deliver this? PR to this repository doesn't really make much sense, maybe to the docs repository?

**Comment by alexeyzimarev** [comment]
I think the UI repo should have it, not the docs repo. It then can be imported from the working instance.

**Comment by jageall** [comment]
lets get the curl commands (which can be imported into postman) collated. This will make it easier as there are a number of clients out there now that people use for testing HTTP apis such as Postman, Insomnia, Fiddler etc

**Comment by ChrisChinchilla** [comment]
We have a swagger file already that generates the docs - https://github.com/EventStore/documentation/blob/master/http-api/swagger.json

This can be used in Paw (I do it myself), or imported into Postman (I think), or converted to other API formats relatively easily.

**Comment by ChrisChinchilla** [comment]
We also have a lot of the curl commands in the docs as shell files here - https://github.com/EventStore/documentation/tree/master/code-examples

**Comment by ChrisChinchilla** [comment]
So in short, I have a testable collection of all our HTTP endpoints already and export it to a wide variety of formats, just tell me what you need.

**Comment by alexeyzimarev** [comment]
I am closing this as the current plan is to deprecate the HTTP API entirely.
