### ISSUE TITLE
Connection to localhost not working

### ISSUE THREAD

**Issue by rbanks54** [EventStore/EventStore#690]
(using v3.2.1)

I was trying to connect to localhost, but was having problems. I found the following worked

var c = EventStoreConnection.Create(new Uri("tcp://127.0.0.1:3300"))
var c = EventStoreConnection.Create(new Uri("tcp://x.localtest.me:3300"))

But these didn't
var c = EventStoreConnection.Create(new Uri("tcp://localhost:3300"))
var c = EventStoreConnection.Create(new Uri("tcp://[::1]:3300")))

Given a ping of localhost (on my machine) returns an IPv6 address, it's seems like either the server doesn't support IPv6 at this point in time, or that it only binds on IPv4 addresses.

Also, the assumption made by this line of code https://github.com/EventStore/EventStore/blob/release-v3.3.0/src/EventStore.ClientAPI/EventStoreConnection.cs#L122 would appear to be incorrect. It looks like we need to enumerate the list to find an IPv4 address when resolving names.

Or am I missing something? I could well be. :-)

**Comment by gregoryyoung** [comment]
"Given a ping of localhost (on my machine) returns an IPv6 address, it's seems like either the server doesn't support IPv6 at this point in time, or that it only binds on IPv4 addresses."

Right now I believe it only binds IPv4

**Comment by rbanks54** [comment]
Not knowing the internals, is that a big change to make?

**Comment by pgermishuys** [comment]
It would require a bit of effort I would imagine,
For example check that our URIs are properly formatted for IPv6 (The Http Server that we spin up uses this).

**Comment by pgermishuys** [comment]
Closed by #692
