### ISSUE TITLE
[Mono] Tilde expansion

### ISSUE THREAD

**Issue by ianbattersby** [EventStore/EventStore#693]
Slight gripe is that if you are not paying attention (like I was) and do `mono EventStore.ClusterNode.exe --db=~/tmp/eventStoreData --log=~/tmp/eventStoreLog` it doesn't do any tilde expansion and in fact creates a directory called "~" in the current directory (./bin for me).

Now this is obviously not desired, but more so it could be dangerous, as somebody *might* - without thinking - then try and delete this `rm -rf ~` which obviously would be disastrous wiping out their home directory. Obviously that didn't happen to me, oh no.

PS. `extundelete` works well in these scenarios ;)

**Comment by pgermishuys** [comment]
We can add a warning here when we get arguments starting with `~`. We will not be expanding `~` as that's the shell's responsibility.

**Comment by ianbattersby** [comment]
:+1:
