### ISSUE TITLE
Projection Button is gone

### ISSUE THREAD

**Issue by lepinay** [EventStore/EventStore#698]
Installed version 3.2.2,

The projection button is not there anymore
![projgonepng](https://cloud.githubusercontent.com/assets/2689930/10079798/69d0d8b6-62ec-11e5-8359-6f895945b4c1.PNG)

**Comment by jen20** [comment]
Are you running Projections? The default mode is `none` rather than `system` as of version 3.1.0.

**Comment by ianbattersby** [comment]
`--run-projections=all`

**Comment by lepinay** [comment]
Thank you, sorry for the false alarm. I couldn't find the information at first in the documentation.
