### ISSUE TITLE
--development-mode starts projections when running on disk but not in memory

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#706]
While debugging an issue with @sbellware, I discovered that `--development-mode` will run the standard projections unless `--mem-db` is specified. Probably some form of race condition that we should look into.

We should also rename and split the flag into `--disable-http-caching` and `--start-standard-projections` so as to not end up with some mode that has some of the options but not all of them.

**Comment by sbellware** [comment]
Or maybe --enable-http-caching, and defaulting it to the appropriate value

**Comment by gregoryyoung** [comment]
I think we should keep http caching on by default.

On Mon, Sep 28, 2015 at 11:26 PM, Scott Bellware <notifications@github.com>
wrote:

> Or maybe --enable-http-caching, and defaulting it to the appropriate value
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/706#issuecomment-143891423>
> .
>



-- 
Studying for the Turing test
