### ISSUE TITLE
Projections: how to search for events produced in a certain time interval ?

### ISSUE THREAD

**Issue by abrasat** [EventStore/EventStore#711]
Can anybody help with some samples about how to use projections to search for events (for instance only events having some specific event type, or even more generally, according to any other criteria present in the event data/metadata, like for example user-name and so on) which occured in a certain time interval (each event data contains a time stamp that marks when it was produced) ?
Thanks in advance.

**Comment by gregoryyoung** [comment]
Are they all in a certain stream or?

**Comment by abrasat** [comment]
It is my first try to use EventStore and I am still in the planning phase about how to organize the streams. Actually I was thinking of the "classic" approach (described in the samples I found) to define streams for each aggregate id (instance). Each stream would then contain only the events regarding a certain aggregate.
For audit purposes I need to search any analyze events produced at a certain point in the past (for instance how many orders where executed on a certain day, how many of them failed, and so on). For certain specific events (for instance in different failure scenarios), I might need to load additional event streams to get additional detailed information that should help the customer to identify what lead to the failure of some business process.

**Comment by gregoryyoung** [comment]
"For audit purposes I need to search any analyze events produced at a
certain point in the past (for instance how many orders where executed on a
certain day, how many of them failed, and so on). For certain specific
events (for instance in different failure scenarios),"


Most of this type of stuff would be done with external projections writing
to read models.

"I might need to load additional event streams to get additional detailed
information that should help the customer to identify what lead to the
failure of some business process."

If doing a stream/order just use the stream browser and put in the stream
here.



On Thu, Oct 1, 2015 at 3:12 PM, abrasat <notifications@github.com> wrote:

> It is my first try to use EventStore and I am still in the planning phase
> about how to organize the streams. Actually I was thinking of the "classic"
> approach (described in the samples I found) to define streams for each
> aggregate id (instance). Each stream would then contain only the events
> regarding a certain aggregate.
> For audit purposes I need to search any analyze events produced at a
> certain point in the past (for instance how many orders where executed on a
> certain day, how many of them failed, and so on). For certain specific
> events (for instance in different failure scenarios), I might need to load
> additional event streams to get additional detailed information that should
> help the customer to identify what lead to the failure of some business
> process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/711#issuecomment-144739757>
> .
>



-- 
Studying for the Turing test

**Comment by abrasat** [comment]
"Most of this type of stuff would be done with external projections writing
to read models."

Lets say there is a aggregate "Order", and the events for each instance of this aggregate are stored in a separate stream in the EventStore. The events for this aggregate type are something like OrderReceived, OrderValidated, OrderStarted, OrderExecutionFinished, OrderExecutionFailed and so on. To be able to find out for which "Order" aggregates the time stamp of the "OrderStarted" event is in some time-interval, I would need to load from the EventStore all streams corresponding to the "Order" aggregates that were ever produced, is that correct ?

**Comment by gregoryyoung** [comment]
Or query a read model that is following the event store if this is a query
you would want to do a lot.

Try here: http://www.ustream.tv/recorded/46673907

On Thu, Oct 1, 2015 at 3:42 PM, abrasat <notifications@github.com> wrote:

> "Most of this type of stuff would be done with external projections writing
> to read models."
>
> Lets say there is a aggregate "Order", and the events for each instance of
> this aggregate are stored in a separate stream in the EventStore. The
> events for this aggregate type are something like OrderReceived,
> OrderValidated, OrderStarted, OrderExecutionFinished, OrderExecutionFailed
> and so on. To be able to find out for which "Order" aggregates the time
> stamp of the "OrderStarted" event is in some time-interval, I would need to
> load from the EventStore all streams corresponding to the "Order"
> aggregates that were ever produced, is that correct ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/711#issuecomment-144748770>
> .
>



-- 
Studying for the Turing test

**Comment by abrasat** [comment]
Thank you for the link, I will take a look.
Just to clarify, I have two applications. The "main" application is implementing the workflow for different business processes and handles/stores directly the events that occur "live".
The second is a UI application which is started only when the customer needs to analyze the performance (or do some reporting) of the plant, by loading "offline" the events that occured in the last weeks/months.

**Comment by gregoryyoung** [comment]
When analyzing how do they analyze? What queries are they interested in
seeing?

For very common queries / dashboards etc. Use a read model (live updating).
Read models can also be in memory.

For seeing an audit trail of a given order you can view the events in that
stream.



On Thu, Oct 1, 2015 at 3:54 PM, abrasat <notifications@github.com> wrote:

> Thank you for the link, I will take a look.
> Just to clarify, I have two applications. The "main" application is
> implementing the workflow for different business processes and
> handles/stores directly the events that occur "live".
> The second is a UI application which is started only when the customer
> needs to analyze the performance (or do some reporting) of the plant, by
> loading "offline" the events that occured in the last weeks/months.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/711#issuecomment-144752306>
> .
>



-- 
Studying for the Turing test

**Comment by abrasat** [comment]
Just saw the presentation, really impressive stuff. I also found this one about querying event streams (https://www.youtube.com/watch?v=DWhQggR13u8), I think this would be the path to follow for the audit trail implementation. Could you eventually recommend some links with sample implementations of such complex event stream queries ?

**Comment by gregoryyoung** [comment]
Projections library is still in beta and coming out this fall.

For a vast portion of your queries you likely don't need them.

Can you give concrete examples of dynamic queries (run very infrequently)
that users need to run? A prime example would be in the medical industry
clinical trials. They often need to run queries that are totally dynamic
and only run once. Do you have such queries?

On Thu, Oct 1, 2015 at 5:37 PM, abrasat <notifications@github.com> wrote:

> Just saw the presentation, really impressive stuff. I also found this one
> about querying event streams (https://www.youtube.com/watch?v=DWhQggR13u8),
> I think this would be the path to follow for the audit trail
> implementation. Could you eventually recommend some links with sample
> implementations of such complex event stream queries ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/711#issuecomment-144781656>
> .
>



-- 
Studying for the Turing test

**Comment by abrasat** [comment]
As I said, I am basically prototyping an EventStore implementation, to be later used for different  industrial automation projects. As a first approach, it is required to be able to select a list of orders executed on a certain day, or even in a certain time-interval. For orders that failed or took too long to finish, it might necessary to  get and correlate (over event time stamps) with other events, for instance with those generated asynchronously from third-party embedded automation systems (that oft monitor some IO signals). Also some statistical reports regarding the order execution time (delta-time between OrderStarted and OrderFinished events), combined with the information about the hardware device (automation system) that performed the order are requested. Basically information that should help to optimize the workflow of automation processes.

**Comment by gregoryyoung** [comment]
Yes and every query you put except "For orders that failed or took too long
to finish, it might necessary to get and correlate (over event time stamps)
with other events, for instance with those generated asynchronously from
third-party embedded automation systems (that oft monitor some IO
signals)." should
be in a read model.

Be careful about overusing projections/queries in event store.

On Thu, Oct 1, 2015 at 6:25 PM, abrasat <notifications@github.com> wrote:

> As I said, I am basically prototyping an EventStore implementation, to be
> later used for different industrial automation projects. As a first
> approach, it is required to be able to select a list of orders executed on
> a certain day, or even in a certain time-interval. For orders that failed
> or took too long to finish, it might necessary to get and correlate (over
> event time stamps) with other events, for instance with those generated
> asynchronously from third-party embedded automation systems (that oft
> monitor some IO signals). Also some statistical reports regarding the order
> execution time (delta-time between OrderStarted and OrderFinished events),
> combined with the information about the hardware device (automation system)
> that performed the order are requested. Basically information that should
> help to optimize the workflow of automation processes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/711#issuecomment-144793230>
> .
>



-- 
Studying for the Turing test

**Comment by abrasat** [comment]
I was initially thinking that the implementation of an audit trail would be possible only based on the event store, but you are of course right, the read model needs to be involved.
I tried to make some analogies with an online shop, I suppose for instance that the order history (like "orders placed in the last 6 months", "orders placed in 2014", and so on) is based on the read model. I also suppose that the detailed information about some order (when were items added/items to the shopping cart during the order preparation, the price of each item at the moment the order was placed, eventually some information about the shipment tracking, ...) is get from the event storage for that order (the order aggregate identifier must be stored also in the read model).
Nevertheless, I think that the support of time-stamp information for the events/event streams in the event storage could be useful when tracking historical event information in some special audit trail cases.

**Comment by gregoryyoung** [comment]
For audit trail its totally possible to use only event store.

For a dashboard people look at 50 times/day of outstanding order states use
a read model

On Fri, Oct 2, 2015 at 1:15 AM, abrasat <notifications@github.com> wrote:

> I was initially thinking that the implementation of an audit trail would
> be possible only based on the event store, but you are of course right, the
> read model needs to be involved.
> I tried to make some analogies with an online shop, I suppose for instance
> that the order history (like "orders placed in the last 6 months", "orders
> placed in 2014", and so on) is based on the read model. I also suppose that
> the detailed information about some order (when were items added/items to
> the shopping cart during the order preparation, the price of each item at
> the moment the order was placed, eventually some information about the
> shipment tracking, ...) is get from the event storage for that order (the
> order aggregate identifier must be stored also in the read model).
> Nevertheless, I think that the support of time-stamp information for the
> events/event streams in the event storage could be useful when tracking
> historical event information in some special audit trail cases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/711#issuecomment-144882414>
> .
>



-- 
Studying for the Turing test

**Comment by abrasat** [comment]
I will probaly have to try and see what mean in terms of performance the different audit trail requirements, when using only the event store. If something like 40-50 orders are executed per hour, and each orders stores like about 10 events in the event store, I can check for instance how long does it take to load in memory all events streams for the order aggregates and parse their event data properties to get only the orders started in a certain time interval.
