### ISSUE TITLE
Scavenge Status

### ISSUE THREAD

**Issue by Dacke** [EventStore/EventStore#714]
Currently there is no way to see the status of a scavenge process once it has been started.  It would be nice to be able to see if the GetEventStore was already in the process of scavenging.  This would prevent multiple scavenge requests from being issued.

Currently the only way to see the status and percentage of a scavenge request is to run the GetEventStore as a program and watch the output.

**Comment by gregoryyoung** [comment]
Event Store will ignore future scavenge requests if scavenging but yes I
can see the desire for a UI level visualization.

On Thu, Oct 1, 2015 at 8:06 PM, Eric Dorothy <notifications@github.com>
wrote:

> Currently there is no way to see the status of a scavenge process once it
> has been started. It would be nice to be able to see if the GetEventStore
> was already in the process of scavenging. This would prevent multiple
> scavenge requests from being issued.
>
> Currently the only way to see the status and percentage of a scavenge
> request is to run the GetEventStore as a program and watch the output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/714>.
>



-- 
Studying for the Turing test
