### ISSUE TITLE
Feature Request - NewRelic Plugins

### ISSUE THREAD

**Issue by BoasE** [EventStore/EventStore#715]
It would be great to get some monitorability through newrelic

s. https://newrelic.com/plugins

**Comment by alexeyzimarev** [comment]
You can do it now by using the [Prometheus Exporter](https://github.com/marcinbudny/eventstore_exporter), and [directing metrics to NewRelic](https://blog.newrelic.com/product-news/how-to-monitor-prometheus-metrics/).
