### ISSUE TITLE
OperationsManager attempts logging illegal string.format message

### ISSUE THREAD

**Issue by JesperL27** [EventStore/EventStore#716]
In OperationsManager line 106, a timeout statement is prepared for the logger. However, this statement includes the current active OperationItem, and OperationItem's ToString method does not strip the curly braces when printing the CorrelationId guid.

Result is passing a string like this to the logger:
(...) operation: Operation ReadStreamEventsForwardOperation ({714ed376-9db6-4582-af50-942a06fdcdbd}): Stream: (...)

ILogger.Error takes a format string and args array, but this string is not a valid format string, and will cause a FormatException if passed to string.Format (as we did in our custom ILogger implementation, and as the Console and Debug logger implementations also do).

The fix should be as simple as changing the format statement in OperationsManager.cs:43 to use {1:D} instead of {1:B}.

**Comment by jen20** [comment]
@JesperL27 this will be fixed as of the next point release shortly - :+1: for reporting.
