### ISSUE TITLE
Connecting ProjectionsManager to in-memory ClusterVNode

### ISSUE THREAD

**Issue by vytautasziurlis** [EventStore/EventStore#750]
Hi,

I'm trying to write some automated tests for custom projections. Since we don't want to install EventStore on all out build infrastructure I've been trying to use in-memory instance. Currently I have the following:

```
            var node = EmbeddedVNodeBuilder.AsSingleNode()
                          .OnDefaultEndpoints()
                          .RunInMemory()
                          .RunProjections(ProjectionsMode.All)
                          .WithWorkerThreads(16)
                          .AddExternalHttpPrefix("http://*:2113/")
                          .Build();
            node.Start();
            var logger = new ConsoleLogger();
            var projectionsManager = new ProjectionsManager(logger, new IPEndPoint(IPAddress.Loopback, 2113), new TimeSpan(1, 0, 0));
            var all = projectionsManager.ListAllAsync();
            all.Wait();
```

This unfortunately throws an exception on all.Wait():

`EventStore.ClientAPI.Exceptions.ProjectionCommandFailedException : Server returned 408 (Server was unable to handle request in time) for GET on http://127.0.0.1:2113/projections/any`

I also tried to curl (curl -i http://127.0.0.1:2113/projections/any), but get `curl: (7) Failed to connect to 127.0.0.1 port 2113: Connection refused`.

Could you please let me know am I doing something wrong or is this an issue with the Event Store itself? Thanks.

**Comment by thefringeninja** [comment]
Running on windows? Try `.AddExternalHttpPrefix("http://+:2113/")`

**Comment by pgermishuys** [comment]
What is likely happening here is that the node hasn't finished starting up.
Have a look at what @thefringeninja is doing here. https://github.com/thefringeninja/EventStore.Samples.Dotnet/blob/embedded-samples/EmbeddedSetup/Program.cs

**Comment by vytautasziurlis** [comment]
@thefringeninja - yes, I'm running on Windows.Tried adding prefix as you mentioned - still the same exception.

@pgermishuys - I think you're on to something. I've taken code example and now I get different error:
`{"The server committed a protocol violation. Section=ResponseStatusLine"}`

Curl returns `Invalid TCP frame received. Error: Package size is out of bounds: 542393671 (max: 67108864)..`

**Comment by pgermishuys** [comment]
What port are you trying to send your curl requests? You'll get that error if you attempt to curl to one of the tcp ports. i.e. 1113

**Comment by vytautasziurlis** [comment]
I use `.OnDefaultEndpoints()` on the node builder, and then curl 1113. All other ports return `Connection refused`.

**Comment by thefringeninja** [comment]
The default external HTTP endpoint is on port 2113.

On Wed, Nov 11, 2015 at 3:33 PM, vytautasziurlis <notifications@github.com>
wrote:

> I use .OnDefaultEndpoints() on the node builder, and then curl 1113. All
> other ports return Connection refused.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/750#issuecomment-155798373>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by vytautasziurlis** [comment]
Right, the problem seems to be caused by missing external Http prefix. However, I still think there's a problem somewhere with projections. My code at the moment:

```
public class EventStoreProjectionTests
    {
        private static Task<int> eventStoreNodeStarted;

        private ClusterVNode eventStore;

        [TestFixtureSetUp]
        public void FixtureSetUp()
        {
            var result = CreateAndStartEventStore();
            result.Wait();
            this.eventStore = result.Result;
        }

        [SetUp]
        public void SetUp()
        {
        }

        [TestFixtureTearDown]
        public void FixtureTearDown()
        {
            this.eventStore.Stop();
        }

        [Test]
        public void Test()
        {
            using (var connection = EmbeddedEventStoreConnection.Create(this.eventStore))
            {
                connection.ConnectAsync().Wait();
                connection.AppendToStreamAsync("stream1", ExpectedVersion.Any, this.GetEvents()).Wait();
                var readEvents = connection.ReadStreamEventsForwardAsync("stream1", 0, 4096, false);
                readEvents.Wait();

                //Assert.NotNull(readEvents.Result);
                //Assert.AreEqual(2, readEvents.Result.Events.Count());
            }

            var logger = new ConsoleLogger();
            var projectionsManager = new ProjectionsManager(logger, new IPEndPoint(IPAddress.Loopback, 2113), new TimeSpan(1, 0, 0));
            var all = projectionsManager.ListAllAsync();
            all.Wait();

            Assert.IsNotEmpty(all.Result);
            Assert.AreEqual(4, all.Result.Count);
        }

        private List<EventData> GetEvents()
        {
            return new List<EventData>
                       {
                           new EventData(Guid.NewGuid(), "type", false, new byte[] { 1 }, new byte[] { }),
                           new EventData(Guid.NewGuid(), "type", false, new byte[] { 2 }, new byte[] { })
                       };
        }

        private static async Task<ClusterVNode> CreateAndStartEventStore()
        {
            var eventStore = CreateEventStore();
            eventStore.Start();
            await eventStoreNodeStarted;
            return eventStore;
        }

        private static ClusterVNode CreateEventStore()
        {
            ClusterVNode eventStoreNode = EmbeddedVNodeBuilder.AsSingleNode()
                .OnDefaultEndpoints()
                .AddExternalHttpPrefix("http://+:2113/")
                .RunProjections(ProjectionsMode.All)
                .RunInMemory();

            var eventStoreNodeStartedSource = new TaskCompletionSource<int>();
            eventStoreNodeStarted = eventStoreNodeStartedSource.Task;
            eventStoreNode.NodeStatusChanged += (_, e) =>
            {
                if (e.NewVNodeState != VNodeState.Master)
                {
                    return;
                }

                eventStoreNodeStartedSource.SetResult(0);
            };

            return eventStoreNode;
        }
    }
```

Code below works as expected. If I comment `connection.AppendToStreamAsync` I get the same error `EventStore.ClientAPI.Exceptions.ProjectionCommandFailedException : Server returned 408 (Server was unable to handle request in time) for GET on http://127.0.0.1:2113/projections/any`.
Since it breaks when trying to list projections and not when trying to read events I have a suspicion there is actually something wrong in projections.

**Comment by condron** [comment]
Hi,
It look like you re missing .StartStandardProjections() on the EmbeddedVNodeBuilder call.
-Chris

**Comment by vytautasziurlis** [comment]
Added .StartStandardProjections(), nothing changed.

**Comment by vytautasziurlis** [comment]
Any more ideas? I'm still stuck with this problem, can't do anything with projections manager unless I write some events first.

**Comment by condron** [comment]
On fail for a projection I write some events into a temp stream and then delete it. Arguably not the best approach, but it works. Look at the SessionStatsReadModel.cs  in the Eventstore Samples.Dotnet AccountBalance app.

**Comment by pgermishuys** [comment]
Is this issue related to https://github.com/EventStore/EventStore/issues/752 ?

**Comment by vytautasziurlis** [comment]
No.

**Comment by pgermishuys** [comment]
Projections only starts once certain conditions are met. In version `3.5.0` that is after the user management service has published a `UserManagementMessage.UserManagementServiceInitialized` message. 

You can subscribe to `SystemMessage.SystemReady` if you want to ensure that the subsystems have started before you attempt to perform any actions against Event Store.

**Comment by gregoryyoung** [comment]
This is correct. The reason the write worked is most likely because the
write waist for system to be ready

**Comment by pgermishuys** [comment]
@vytautasziurlis can you try with the latest client and subscribing to `SystemMessage.SystemReady`.

**Comment by pgermishuys** [comment]
@vytautasziurlis just following up on this. With the release of 3.5.0 there was an additional method (`StartAndWaitUntilReady` which returns a `Task` that can be waited on) added onto ClusterVNode which you can use to ensure that the node is ready to handle requests.

**Comment by pgermishuys** [comment]
This will be improved with a PR for https://github.com/EventStore/EventStore/issues/922

**Comment by pgermishuys** [comment]
@vytautasziurlis we have made some improvements for the Embedded Client as of late, specifically around waiting for projections to start up on calling `StartAndWaitUntilReady`.

The following test passes consistently.

```
    [TestFixture]
    public class ProjectionTest
    {
        ClusterVNode _vnode;
        IEventStoreConnection _connection;
        IPEndPoint _tcp = new IPEndPoint(IPAddress.Loopback, 1113);
        IPEndPoint _http = new IPEndPoint(IPAddress.Loopback, 2113);
        UserCredentials _creds = new UserCredentials("admin", "changeit");

        [Test]
        public async Task SubscribeAndGetCategoryCatchUpData()
        {
            await SetupEmbeddedEventStore();

            await EnableCategoryProjections();
            var stream = GenName();

            _connection = CreateConnectionToEmbeddedEventStore();
            await _connection.ConnectAsync();

            await _connection.AppendToStreamAsync("mycat-" + stream, -1, new[] {
                new EventData (Guid.NewGuid (), "myType", true, GenData (), GenData())
            });

            var waitEvent = new TaskCompletionSource<bool>();

            await _connection.SubscribeToStreamAsync(
                "$ce-mycat", true,
                (sub, evt) => waitEvent.TrySetResult(true),
                (sub, reason, ex) => {
                }).ConfigureAwait(false);

            if (await Task.WhenAny(waitEvent.Task, Task.Delay(TimeSpan.FromSeconds(20))) == waitEvent.Task)
            {
                Assert.Pass();
            }else
            {
                Assert.Fail();
            }
        }

        [TearDown]
        public void TearDown()
        {
            _vnode.Stop(TimeSpan.FromSeconds(20), true, true);
        }

        async Task SetupEmbeddedEventStore()
        {
            _vnode = EmbeddedVNodeBuilder
                .AsSingleNode()
                .RunInMemory()
                .WithExternalTcpOn(_tcp)
                .WithExternalHttpOn(_http)
                .RunProjections(EventStore.Common.Options.ProjectionType.All)
                .StartStandardProjections()
                .Build();
            await _vnode.StartAndWaitUntilReady();
        }

        IEventStoreConnection CreateConnectionToEmbeddedEventStore()
        {
            var connection = EmbeddedEventStoreConnection.Create(_vnode,
            ConnectionSettings.Create()
                .EnableVerboseLogging()
                .UseConsoleLogger()
                .SetDefaultUserCredentials(_creds)
                .Build());
            return connection;
        }

        async Task EnableCategoryProjections()
        {
            var projectionManager = new ProjectionsManager(
                new ConsoleLogger(),
                _http,
                new TimeSpan(1, 0, 0));

			var all = await projectionManager.ListAllAsync();

			Assert.IsNotEmpty(all);
            Assert.AreEqual(4, all.Count);
        }

        string GenName()
        {
            return Path.GetFileNameWithoutExtension(Path.GetRandomFileName());
        }

        byte[] GenData()
        {
            var str =
                new string[] { GenName(), GenName(), GenName() }
                    .Aggregate("", (acc, t) => acc + t);
            return Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(new
            {
                Name = GenName(),
                ThisIsGreat = str
            }));
        }
    }
```

I am going to close this issue for now. Please feel free to reopen if you are still experiencing issues with the above mentioned.
