### ISSUE TITLE
Missing Prelude js files when creating projection for in-memory ClusterVNode

### ISSUE THREAD

**Issue by vytautasziurlis** [EventStore/EventStore#751]
Hi,

I'm trying to spin up in-memory instance of ClusterVNode and then create new projection (in order to test custom projections). Code for creating projection looks something like this:
```
            var logger = new ConsoleLogger();
            var projectionsManager = new ProjectionsManager(logger, new IPEndPoint(IPAddress.Loopback, 2113), new TimeSpan(1, 0, 0));
            UserCredentials credentials = new UserCredentials("admin", "changeit");
            projectionsManager.CreateContinuousAsync("test1", "fromStream('stream1').when({ '$any': function (s, e) { linkTo('stream2', e); } })", credentials).Wait();

            var projectionsState = projectionsManager.GetStatusAsync("test1");
            projectionsState.Wait();
```

When I look at projectionsState.Result, stateReason is set to the following:
`Could not find a part of the path 'C:\\Users\\...\\AppData\\Local\\Temp\\...\\Prelude\\1Prelude.js'.`

Have I missed something here or is this error expected?
Thanks.

**Comment by pgermishuys** [comment]
If you are using the Embedded Client > v3.3.0, this commit added `/Prelude` (https://github.com/EventStore/EventStore/commit/e9196f2d8d8eaffd7e12e0fb987ec091488e4cde)

Are you running a test here using something like NUnit? If so, do you see the same behaviour if you turn shadow copying off?

What we could do here is to add Prelude as an embedded resource, which would get rid of issues like this.

**Comment by vytautasziurlis** [comment]
I'm using 3.3.1. My initial code was part of NUnit test suite. I've tried the same code in console application and now I'm getting different stateReason:
`An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)`
Any ideas how to resolve this problem?

**Comment by gregoryyoung** [comment]
This sounds like 64 bit dlls in 32 bit code or vice versa

On Thu, Nov 12, 2015 at 11:54 AM, vytautasziurlis <notifications@github.com>
wrote:

> I'm using 3.3.1. My initial code was part of NUnit test suite. I've tried
> the same code in console application and now I'm getting different
> stateReason:
> An attempt was made to load a program with an incorrect format. (Exception
> from HRESULT: 0x8007000B)
> Any ideas how to resolve this problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/751#issuecomment-156083978>
> .
>



-- 
Studying for the Turing test

**Comment by vytautasziurlis** [comment]
OK, just tried turning off shadow copy - this actually solved the problem and I can now create projection and test it's behavior.
Obviously I don't want to keep shadow copy off, at the end of the day it's there for a reason. Is there something you should do on your end to make this work with shadow copy turned on?

**Comment by pgermishuys** [comment]
We can include it as an embedded resource in the Embedded Client.

**Comment by vytautasziurlis** [comment]
That would be great, I will open a new issue to keep track of it. Thank you for your help.
