### ISSUE TITLE
Prelude javascript files should be emdedded resources

### ISSUE THREAD

**Issue by vytautasziurlis** [EventStore/EventStore#752]
Currently Prelude javascript files are not embedded resources which means automated tests only work when shadow copying is turned off.
More info here: https://github.com/EventStore/EventStore/issues/751

**Comment by gregoryyoung** [comment]
You could alternatively copy the dependencies with the shadow copy.

On Thu, Nov 12, 2015 at 12:50 PM, vytautasziurlis <notifications@github.com>
wrote:

> Currently Prelude javascript files are not embedded resources which means
> automated tests only work when shadow copying is turned off.
> More info here: #751 <https://github.com/EventStore/EventStore/issues/751>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/752>.
>



-- 
Studying for the Turing test
