### ISSUE TITLE
exception in `ReaderSubscriptionManagement`

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#753]
So we woke up to a 3-way cluster, with `by_category` enabled, having one of the nodes output the following. So what gives and how critical is this?
```
[PID:00954:030 2015.11.11 12:31:40.395 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Projections.Core.Messages.ReaderSubscriptionManagement+Unsubscribe in queued handler 'Projection Core #1'.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.Guid,System.Guid].get_Item (Guid key) [0x00000] in <filename unknown>:0
  at EventStore.Projections.Core.Services.Processing.EventReaderCoreService.Handle (EventStore.Projections.Core.Messages.Unsubscribe message) [0x00000] in <filename unknown>:0
  at EventStore.Core.Bus.MessageHandler`1[EventStore.Projections.Core.Messages.ReaderSubscriptionManagement+Unsubscribe].TryHandle (EventStore.Core.Messaging.Message message) [0x00000] in <filename unknown>:0
  at EventStore.Core.Bus.InMemoryBus.Publish (EventStore.Core.Messaging.Message message) [0x00000] in <filename unknown>:0
  at EventStore.Core.Bus.InMemoryBus.Handle (EventStore.Core.Messaging.Message message) [0x00000] in <filename unknown>:0
  at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (System.Object o) [0x00000] in <filename unknown>:0
```

**Comment by gregoryyoung** [comment]
This is a projections exception nothing else should be affected but maybe
the projection is not running?

On Thu, Nov 12, 2015 at 4:06 PM, Alex Henning Johannessen <
notifications@github.com> wrote:

> So we woke up to a 3-way cluster, with by_category enabled, having one of
> the nodes output the following. So what gives and how critical is this?
>
> [PID:00954:030 2015.11.11 12:31:40.395 ERROR QueuedHandlerAutoRes] Error while processing message EventStore.Projections.Core.Messages.ReaderSubscriptionManagement+Unsubscribe in queued handler 'Projection Core #1'.
> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>   at System.Collections.Generic.Dictionary`2[System.Guid,System.Guid].get_Item (Guid key) [0x00000] in <filename unknown>:0
>   at EventStore.Projections.Core.Services.Processing.EventReaderCoreService.Handle (EventStore.Projections.Core.Messages.Unsubscribe message) [0x00000] in <filename unknown>:0
>   at EventStore.Core.Bus.MessageHandler`1[EventStore.Projections.Core.Messages.ReaderSubscriptionManagement+Unsubscribe].TryHandle (EventStore.Core.Messaging.Message message) [0x00000] in <filename unknown>:0
>   at EventStore.Core.Bus.InMemoryBus.Publish (EventStore.Core.Messaging.Message message) [0x00000] in <filename unknown>:0
>   at EventStore.Core.Bus.InMemoryBus.Handle (EventStore.Core.Messaging.Message message) [0x00000] in <filename unknown>:0
>   at EventStore.Core.Bus.QueuedHandlerAutoReset.ReadFromQueue (System.Object o) [0x00000] in <filename unknown>:0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/753>.
>



-- 
Studying for the Turing test

**Comment by ahjohannessen** [comment]
Why only use `$by_category` and make sure that nodes are started with `all` plus issuing curls  to enable `$by_category` with our ansible playbooks. So I am not sure why it should not be running if we do those two things during bootstrap of a node.

**Comment by gregoryyoung** [comment]
I mean as a possible affect maybe the projection is in a faulted state? I
wouldn't expect it to be

On Thu, Nov 12, 2015 at 4:10 PM, Alex Henning Johannessen <
notifications@github.com> wrote:

> Why only use $by_category and make sure that nodes are started with all
> plus issuing curls to enable $by_category with our ansible playbooks. So
> I am not sure why it should not be running if we do those two things during
> bootstrap of a node.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/753#issuecomment-156150835>
> .
>



-- 
Studying for the Turing test

**Comment by ahjohannessen** [comment]
I am feeling a bit uneasy if projections like `$by_category` stop for no good reason :/ Because those are the cornerstone of our application setup wrt "reactors" and read model.

Greg, what could be a reason for `$by_category` entering into a faulted state in an otherwise healthy ubuntu node setup with each node given 4 CPUs and 8 GB RAM with 100GB of disk (using perhaps 1GB of that)?

**Comment by ahjohannessen** [comment]
Having `$by_category` stop is a bit, well, what can we as users do about that. I would understand if it was some half-assed JS code we had done that did not take null into account or similar.

**Comment by gregoryyoung** [comment]
Because projections are in beta and are not intended to be used in
production? This has been very clearly communicated.

They are getting pretty close but there are still 1-2 issues that happen
occasionally though most are worked out. Aside from that its mostly docs
before we consider them supported.



Is your projection in an stopped state? I was saying thats one *possible*
affect but don't know if it actually stopped.

On Thu, Nov 12, 2015 at 4:16 PM, Alex Henning Johannessen <
notifications@github.com> wrote:

> I am feeling a bit uneasy if projections like $by_category stop for no
> good reason :/ Because those are the cornerstone of our application setup
> wrt "reactors" and read model.
>
> Greg, what could be a reason for $by_category entering into a faulted
> state in an otherwise healthy ubuntu node setup with each node given 4 CPUs
> and 8 GB RAM with 100GB of disk (using perhaps 1GB of that)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/753#issuecomment-156152637>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
@pieterg I seem to remember this being addressed already (key not found on
unsubscribe) can you confirm this?

On Thu, Nov 12, 2015 at 4:19 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> Because projections are in beta and are not intended to be used in
> production? This has been very clearly communicated.
>
> They are getting pretty close but there are still 1-2 issues that happen
> occasionally though most are worked out. Aside from that its mostly docs
> before we consider them supported.
>
>
>
> Is your projection in an stopped state? I was saying thats one *possible*
> affect but don't know if it actually stopped.
>
> On Thu, Nov 12, 2015 at 4:16 PM, Alex Henning Johannessen <
> notifications@github.com> wrote:
>
>> I am feeling a bit uneasy if projections like $by_category stop for no
>> good reason :/ Because those are the cornerstone of our application setup
>> wrt "reactors" and read model.
>>
>> Greg, what could be a reason for $by_category entering into a faulted
>> state in an otherwise healthy ubuntu node setup with each node given 4 CPUs
>> and 8 GB RAM with 100GB of disk (using perhaps 1GB of that)?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/753#issuecomment-156152637>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by ahjohannessen** [comment]
Greg, I have to reach out for my teammate to get more details about particulars. We know that projections in general are in beta, but we have faith in built-in stuff like $by_category to work (as that stuff happens within your control). Btw, we are on latest published ES.

**Comment by ahjohannessen** [comment]
>They are getting pretty close but there are still 1-2 issues that happen
occasionally though most are worked out.

If solving the issue is a matter of rebooting a node or the cluster, we can live with that for a while. Just wish to know what to watch out for and how to rectify things.

**Comment by gregoryyoung** [comment]
is it actually in a faulted state?

On Thu, Nov 12, 2015 at 4:28 PM, Alex Henning Johannessen <
notifications@github.com> wrote:

> They are getting pretty close but there are still 1-2 issues that happen
> occasionally though most are worked out.
>
> If solving the issue is a matter of rebooting a node or the cluster, we
> can live with that for a while. Just wish to know what to watch out for and
> how to rectify things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/753#issuecomment-156156238>
> .
>



-- 
Studying for the Turing test

**Comment by ahjohannessen** [comment]
>is it actually in a faulted state?
I am not sure, sorry. It got that error log message from a teammate earlier today and started wondering why this happens when we only have `$by_category` enabled.

**Comment by gregoryyoung** [comment]
Look on the master on projections screen.

On Thu, Nov 12, 2015 at 4:33 PM, Alex Henning Johannessen <
notifications@github.com> wrote:

> is it actually in a faulted state?
> I am not sure, sorry. It got that error log message from a teammate
> earlier today and started wondering why this happens when we only have
> $by_category enabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/753#issuecomment-156157993>
> .
>



-- 
Studying for the Turing test

**Comment by ahjohannessen** [comment]
The error log does not tell us much about what subscription we are dealing with, hence a bit difficult to trace its state.

>Look on the master on projections screen.

So, I should look for all `$by_category` projection states to see if one is in faulted state?

**Comment by pgermishuys** [comment]
@gregoryyoung I found one scenario where this occurs and that's when a node has been issued with a /shutdown request.

Here is the commit in a separate branch that hasn't been merged in that will stop this from happening.
Afaik, this is a not critical issue.

https://github.com/EventStore/EventStore/commit/dc83afa4e62b938c7ed9f6b32367c6f0c832f118

**Comment by ahjohannessen** [comment]
@pgermishuys null pointers and missing keys seems like we are trying to get something that isn't there, right? Would it be possible to do a review of what is being logged when this happens in order to be better able to determine causation?

**Comment by ahjohannessen** [comment]
@pgermishuys I am almost 100% sure that a shutdown request did not happen in our case.

**Comment by pgermishuys** [comment]
@ahjohannessen are you in a position to share logs? In addition, will spend some time looking into this particular issue a little more.

**Comment by ahjohannessen** [comment]
@pgermishuys Yes, I would think so I am. I'll try to see what I can do. Thanks for helping out :+1:

**Comment by pgermishuys** [comment]
@ahjohannessen just following up regarding the logs

**Comment by ahjohannessen** [comment]
@pgermishuys I've been on vacation, sorry for the delay. Unfortunately, I cannot provide you with logs as it was in a staging environment that got reset. However, if a similar thing happens I'll make sure to provide logs. I'm closing this for now.
