### ISSUE TITLE
HTTP API / Delete stream which doesn't exists should success when passed empty stream expected version

### ISSUE THREAD

**Issue by michael-schnell** [EventStore/EventStore#756]
Deleting a non-existing stream with expected version empty stream (0) fails using HTTP API:
```
curl -X DELETE -H "ES-HardDelete: true" -H "ES-ExpectedVersion: 0" 'http://127.0.0.1:2113/streams/delete_stream_1'

400 Wrong expected EventNumber
```
In contrast to that the C# unit Test "EventStore.Core.Tests.ClientAPI.deleting_stream.cs" states:
```cs
[Test]
[Category("Network")]
public void which_doesnt_exists_should_success_when_passed_empty_stream_expected_version()
{
    const string stream = "which_already_exists_should_success_when_passed_empty_stream_expected_version";
    using (var connection = BuildConnection(_node))
    {
	connection.ConnectAsync().Wait();
	var delete = connection.DeleteStreamAsync(stream, ExpectedVersion.EmptyStream, hardDelete: true);
	Assert.DoesNotThrow(delete.Wait);
    }
}
```
Not sure if this is correct, because message and method name state the opposite:

> public void which_doesnt_exists_should_success_when_passed_empty_stream_expected_version()

vs.

> "which_already_exists_should_success_when_passed_empty_stream_expected_version"

I created a [Cucumber specification](https://github.com/fuinorg/event-store-commons/blob/master/test/src/test/resources/features/delete-stream.feature) that displays the current behaviour: EMPTY_STREAM expected version throws an Exception (Java "StreamVersionConflictException" is "WrongExpectedVersionException" in C#).

**Comment by gregoryyoung** [comment]
You are slightly off. Look at the definition of EmptyStream.

Cheers,

Greg

On Sun, Nov 22, 2015 at 9:15 AM, Michael Schnell <notifications@github.com>
wrote:

> Unit Test "EventStore.Core.Tests.ClientAPI.deleting_stream.cs" states:
>
> [Test]
> [Category("Network")]public void which_doesnt_exists_should_success_when_passed_empty_stream_expected_version()
> {
>     const string stream = "which_already_exists_should_success_when_passed_empty_stream_expected_version";
>     using (var connection = BuildConnection(_node))
>     {
>     connection.ConnectAsync().Wait();
>     var delete = connection.DeleteStreamAsync(stream, ExpectedVersion.EmptyStream, hardDelete: true);
>     Assert.DoesNotThrow(delete.Wait);
>     }
> }
>
> But deleting a non-existing stream with expected version empty stream (0)
> fails using HTTP API:
>
> curl -X DELETE -H "ES-HardDelete: true" -H "ES-ExpectedVersion: 0" 'http://127.0.0.1:2113/streams/delete_stream_1'
>
> 400 Wrong expected EventNumber
>
> Not sure if this is correct, because message and method name state the
> opposite:
>
> public void
> which_doesnt_exists_should_success_when_passed_empty_stream_expected_version()
>
> vs.
>
>
> "which_already_exists_should_success_when_passed_empty_stream_expected_version"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/756>.
>



-- 
Studying for the Turing test

**Comment by michael-schnell** [comment]
So the method name of the test is wrong? ("public void which_doesnt_exists_should_success_when_passed_empty_stream_expected_version()")

**Comment by gregoryyoung** [comment]
You are passing expected version 0 empty stream is -1

https://github.com/EventStore/EventStore/blob/release-v3.4.0/src/EventStore.ClientAPI/ExpectedVersion.cs#L35

curl -X DELETE -H "ES-HardDelete: true" -H "ES-ExpectedVersion: 0"
'http://127.0.0.1:2113/streams/delete_stream_1'


Cheers,

Greg

On Mon, Nov 23, 2015 at 6:29 PM, Michael Schnell <notifications@github.com>
wrote:

> So the method name of the test is wrong? ("public void
> which_doesnt_exists_should_success_when_passed_empty_stream_expected_version()")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/756#issuecomment-158987551>
> .
>



-- 
Studying for the Turing test

**Comment by michael-schnell** [comment]
Ah, OK - I was just looking at the documentation: http://docs.geteventstore.com/http-api/3.2.0/writing-to-a-stream/

On that page it's: "0 states that the stream should exist but should be empty"
