### ISSUE TITLE
Make interface for StreamEventsSlice to enable unit testing of event readers

### ISSUE THREAD

**Issue by tarnow74** [EventStore/EventStore#760]

**Comment by tarnow74** [comment]
StreamEventsSlice Has an internal constructor making it hard to simulate response from ReadStreamEventsForwardAsync. Returning an interface would make mocking easy.

**Comment by gregoryyoung** [comment]
StreamEventsSlice is data you generally shouldn't be mocking data.

In terms of testing what most are doing is wrapping the connection on their
own and then having a few integration tests on their wrapper (e.g. a
repository etc).

Cheers,

Greg

On Mon, Nov 30, 2015 at 12:53 PM, Thomas Tarnow <notifications@github.com>
wrote:

> StreamEventsSlice Has an internal constructor making it hard to simulate
> response from ReadStreamEventsForwardAsync. Returning an interface would
> make mocking easy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/760#issuecomment-160580101>
> .
>



-- 
Studying for the Turing test

**Comment by pgermishuys** [comment]
Closing this issue for now. If anyone feels this warrants another look.
