### ISSUE TITLE
Maintaining state w/foreachStream() against linked events

### ISSUE THREAD

**Issue by ianbattersby** [EventStore/EventStore#763]
I'm not sure if this behaviour is as-expected or by-design but wanted to double check. I've noticed that when using `foreachStream()` against a category constructed by another projection using linked events that the state doesn't seem to be maintained during a `foreachStream()` - I had to change the originating category stream construction to use `emit` instead.

For (a contrived) example;

Something-A
Something-B
Something-C

```js
// I haven't used whenAny here as I didn't in my use-case
fromCategory("Something")
  .foreachStream()
  .when({
    "EventTypeA" : function(s,e) {
      linkTo("Else-" + e.data.some_id, e);
      return s;
    },
    "EventTypeC" : function(s,e) {
      linkTo("Else-" + e.data.some_id, e);
      return s;
    });
```

Giving us (for example);
  Else-123 (containing links to A's and C's)
  Else-456 (containing links to A's and C's)
  Else-789 (containing links to A's and C's)

When I then write another `fromCategory(...).foreachStream()` projection like so;

```js
fromCategory("Else")
  .foreachStream()
  .when({
    $init: function() {
      return {
        SomeState: []
      },
      "EventTypeA": function(s,e) {
        // The state here ..
        return s;
      },
      "EventTypeB": function(s,e) {
        // .. is not the same as here?
        return s;
      });
```

So what I observed was that the above projection doesn't maintain the correct state for each of the "Else" category streams between the event-types, but if I change the "Else" streams to instead use `emit` it's all dandy.

**Comment by gregoryyoung** [comment]
I'm guessing it maintains state back to the original streams....

I would expect this.

**Comment by ianbattersby** [comment]
Cool thanks, I just wanted to check it was 'as expected' :+1:

**Comment by ianbattersby** [comment]
Just to add, *should it though?* I couldn't stop thinking about this today, or at least couldn't think of why you wouldn't want it to do this; that said my experience is limited to experimentation opposed to real-world scenarios.
