### ISSUE TITLE
Failed resolved links not handled well in projections

### ISSUE THREAD

**Issue by lscpike** [EventStore/EventStore#783]
I've committed a fix in the past to stop errors being thrown when a link is not resolved successfully in the projection system due to deleted events. It seems this just moves the errors deeper inside the projection system. 

Two issues I've hit so far whilst trying to get things working:
1. The V8ProjectionStateHandler throws NullReferenceExceptions. Caused by access to null values on the event.
2. The linkTo can output invalid links such as "-1@".

I'll attach a program which reproduces the scenario. At this point I'm giving up trying to fix things as it feels like I'm going down the wrong path. Should failed links instead be explicitly dropped? I've no idea where though.

**Comment by lscpike** [comment]
using System;
using System.IO;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using EventStore.ClientAPI;
using EventStore.ClientAPI.Common.Log;
using EventStore.ClientAPI.Projections;
using EventStore.ClientAPI.SystemData;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace UnresolveLinkProjection
{
    class FailedResolvedLinkProjectionTest
    {
        static void Main(string[] args)
        {

            var cancellationTokenSource = new CancellationTokenSource();

            var task = Start(cancellationTokenSource.Token);

            Console.CancelKeyPress += (sender, eventArgs) =>
            {
                cancellationTokenSource.Cancel();
            };

            try
            {
                task.Wait();
            }
            catch (OperationCanceledException)
            {

            }

            Console.WriteLine("Press any key...");
            Console.ReadKey();
        }
        
        private static async Task Start(CancellationToken token)
        {
            try
            {
                var userCredentials = new UserCredentials("admin", "changeit");
                var connectionSettings = ConnectionSettings.Create()
                .KeepReconnecting()
                .UseConsoleLogger()
                .KeepRetrying()
                .SetHeartbeatInterval(TimeSpan.FromSeconds(10))
                .SetHeartbeatTimeout(TimeSpan.FromSeconds(120))
                .SetDefaultUserCredentials(userCredentials)
                .Build();

                var eventStoreConnection =  EventStoreConnection.Create(connectionSettings, new Uri(@"tcp:\\localhost:1113"));

                await eventStoreConnection.ConnectAsync();

                token.ThrowIfCancellationRequested();

                await WriteDeletedData(eventStoreConnection);

                token.ThrowIfCancellationRequested();

                var projectionsManager = new ProjectionsManager(new ConsoleLogger(), new IPEndPoint(IPAddress.Loopback, 2113),
                    TimeSpan.FromSeconds(2));

                await projectionsManager.EnableAsync("$by_category", userCredentials);

                await projectionsManager.CreateContinuousAsync("Test", @"fromCategory('Test').whenAny(function(state, ev) { linkTo('Tests', ev);});", userCredentials);

                var status = await GetStatus(projectionsManager);

                while(status.Item1 == "Running" && status.Item2 < 100)
                {
                    Console.WriteLine($"Projection status: {status}");

                    token.ThrowIfCancellationRequested();

                    await Task.Delay(TimeSpan.FromSeconds(1));

                    token.ThrowIfCancellationRequested();

                    status = await GetStatus(projectionsManager);
                }

                Console.WriteLine($"Final projection status: {status}");
            }
            catch (Exception e)
            {
                Console.Out.WriteLine("Error:\n" + e);
            }

        }

        private static async Task<Tuple<string,float>> GetStatus(ProjectionsManager projectionsManager)
        {
            string statusStr = await projectionsManager.GetStatusAsync("Test");
            var deserialize = (dynamic) JsonSerializer.Create().Deserialize(new StringReader(statusStr), typeof (JObject));
            JValue status = deserialize.status;
            JValue progress = deserialize.progress;
            return Tuple.Create(status.Value<string>(), progress.Value<float>());
        }

        private static async Task WriteDeletedData(IEventStoreConnection eventStoreConnection)
        {
            var id = 0;
            var json = $"{{ Id : \"{id}\" }}";
            var jsonBytes = Encoding.UTF8.GetBytes(json);
            var streamId = $"Test-{id}";
            var writeResult = await eventStoreConnection.AppendToStreamAsync(streamId, ExpectedVersion.Any, new EventData(Guid.NewGuid(), "TestData", true, jsonBytes, null));

            await eventStoreConnection.SetStreamMetadataAsync(streamId, ExpectedVersion.Any, StreamMetadata.Create(truncateBefore: writeResult.NextExpectedVersion + 1));
        }

    }
}

**Comment by pgermishuys** [comment]
Thanks @lscpike we've had a number of these recently. Thanks for the sample code.

**Comment by pgermishuys** [comment]
@lscpike out of curiosity, have you tried this code against the latest codebase?
As mentioned previously, we had a number of these issues pop up recently and going through and fixing this. In particular https://github.com/EventStore/EventStore/commit/1450ab78802f45b467d78cc40aa23f59625f1669

**Comment by lscpike** [comment]
I was 1 commit behind that! I've retested and my scenario works fine. Thanks very much.

Worth mentioning; where this change is made doesn't affect your browser debugging UI. Therefore it will continue to receive these events.

**Comment by gregoryyoung** [comment]
That wonderful moment when someone fixed your bug a week before :+1:
