### ISSUE TITLE
Provide a nicer way to start Embedded node (for tests)

### ISSUE THREAD

**Issue by damianh** [EventStore/EventStore#784]
After upgrading from 3.0 to 3.4 and I started to get a number of failing tests with `EventStore.ClientAPI.Exceptions.NotAuthenticatedException: Authentication error`

I _was_ using this:

        private static Task<ClusterVNode> CreateClusterVNode()
        {
            ClusterVNode node = EmbeddedVNodeBuilder
                .AsSingleNode()
                .WithExternalTcpOn(s_noEndpoint)
                .WithInternalTcpOn(s_noEndpoint)
                .WithExternalHttpOn(s_noEndpoint)
                .WithInternalHttpOn(s_noEndpoint)
                .RunProjections(ProjectionsMode.All)
                .RunInMemory();

            var tcs = new TaskCompletionSource<ClusterVNode>();

            node.NodeStatusChanged += (_, e) =>
            {
                if(e.NewVNodeState != VNodeState.Master)
                {
                    return;
                }
                tcs.SetResult(node);
            };
            node.Start();

            return tcs.Task;
        }

Apparently there is some sort of initialization racy condition before`UserManagementServiceInitialized`.

After some help from @pgermishuys this has been rewitten to:

        private static Task<ClusterVNode> CreateClusterVNode()
        {
            IPEndPoint noEndpoint = new IPEndPoint(IPAddress.None, 0);

            ClusterVNode node = EmbeddedVNodeBuilder
                .AsSingleNode()
                .....

            var tcs = new TaskCompletionSource<ClusterVNode>();

            node.MainBus
                .Subscribe(new AdHocHandler<UserManagementMessage.UserManagementServiceInitialized>(
                    _ => tcs.TrySetResult(node)));

            node.Start();

            return tcs.Task;
        }

I would _never_ have been able to guess this. May I suggest that this is encapsulated is something more friendly?

Perhaps:

    internal static class ClusterVNodeExtensions
    {
        internal static Task<ClusterVNode> StartAndWaitUntilInitialized(this ClusterVNode node)
        {
            var tcs = new TaskCompletionSource<ClusterVNode>();

            node.MainBus
                .Subscribe(new AdHocHandler<UserManagementMessage.UserManagementServiceInitialized>(
                    _ => tcs.TrySetResult(node)));

            node.Start();

            return tcs.Task;
        } 
    }

Also, it wasn't obvious that I needed to set the DefaultUserCredentials. I had to change this (working in 3.0):

    var connection = EmbeddedEventStoreConnection.Create(node);

to 

    var connectionSettingsBuilder = ConnectionSettings
        .Create()
        .SetDefaultUserCredentials(new UserCredentials("admin", "changeit"))
        .KeepReconnecting();

    var connection = EmbeddedEventStoreConnection.Create(node, connectionSettingsBuilder);

I'm not really fond of the magic strings there so perhaps expose these default admin credentials on EmbeddedEventStoreConnection?

    var connection = EmbeddedEventStoreConnection.Create(
        node,
        EmbeddedEventStoreConnection.DefaultAdminConnectionSettings);

Or maybe have the EmbeddedEventStoreConnection just default to using the DefaultAdminConnectionSettings? 

Will send PR on advice :)

Cheers

**Comment by pgermishuys** [comment]
I like the idea of exposing a `WaitUntilInitialized` method for ease of use.

**Comment by gregoryyoung** [comment]
Maybe an Initialized event on VNode?

On Thu, Dec 24, 2015 at 9:55 AM, Pieter Germishuys <notifications@github.com
> wrote:

> I like the idea of exposing a WaitUntilInitialized method for ease of use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/784#issuecomment-167079763>
> .
>



-- 
Studying for the Turing test

**Comment by damianh** [comment]
What other messages need to be published to for the VNode to be considered 'Initialized'?

**Comment by gregoryyoung** [comment]
Just that one. It is initialized at that point the only waiting thing is
authorization which takes a few hundred ms after master election

On Thu, Dec 24, 2015 at 4:30 PM, Damian Hickey <notifications@github.com>
wrote:

> What other messages need to be published to for the VNode to be considered
> 'Initialized'?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/784#issuecomment-167133305>
> .
>



-- 
Studying for the Turing test
