### ISSUE TITLE
X-HTTP-Method-Override

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#785]
Support for these headers eg X-HTTP-Method-Override would be useful in some environments http://fandry.blogspot.nl/2012/03/x-http-header-method-override-and-rest.html

**Comment by jageall** [comment]
This should be possible to do with the move to .net core and kestrel using [built in middleware](https://docs.microsoft.com/en-gb/dotnet/api/microsoft.aspnetcore.builder.httpmethodoverrideextensions?view=aspnetcore-2.2) after #1996

**Comment by oskardudycz** [comment]
@jageall, can we close it per your comment above, or is it still outstanding?

**Comment by oskardudycz** [comment]
Per discussion with @condron, as there was no major activity on the ticket and HTTP API is considered legacy, I'm closing the ticket.
