### ISSUE TITLE
Provide a way to check if a persistent subscription exists

### ISSUE THREAD

**Issue by mikegore1000** [EventStore/EventStore#787]
I would like to create persistent subscriptions as part of my application startup code using the .NET client.  If the subscription already exists the CreatePersistentSubscriptionAsync method throws an InvalidOperationException.

I can work around this no problem, but it would be great if this was dealt with via the client API.  At present the only way I can see to do this is to either:
1. Read the contents of the latest event from the $persistentSubscriptionConfig stream.
2. Catch the InvalidOperationException - not that clean as I cannot determine if it's due to the subscription existing without inspecting the message content.

**Comment by gregoryyoung** [comment]
See restful API /subscriptions and /subscriptions/stream/{name}

**Comment by mikegore1000** [comment]
Thanks Greg, makes sense!
