### ISSUE TITLE
Via HTTP, an unauthenticated read against a category stream that does not exist returns a 401, not 404

### ISSUE THREAD

**Issue by ntl** [EventStore/EventStore#788]
When I perform an unauthenticated HTTP read against any individual stream that doesn't exist, I get back a 404. However, when I perform a similar HTTP read against a category stream that doesn't exist, I get back a 401. This variation is problematic for us, since our long polling subscriber can't detect that the category stream doesn't exist. If the long polling subscriber _could_ make that determination, it could simply sleep for a bit and try again later. As it stands, our long polling subscribers crash until we put the first event in a stream that will ultimately create the category stream, since we must presume that an authentication error constitutes an unrecoverable and fatal configuration error.

I'm guessing that this behavior is caused by using the HTTP API without authenticating. What's puzzling is the variation between an individual stream and a category stream. I would strongly prefer that unauthenticated reads against nonexistent category streams behave similarly to nonexistent individual streams.

**Comment by gregoryyoung** [comment]
If the non-existing stream has security they should have the same behaviour.

The reasoning behind this is sending a 404 leaks information someone could possibly use.

**Comment by gregoryyoung** [comment]
Also in the future, when discussing http api stuff, curl commands help in showing what you are describing.

**Comment by litch** [comment]
I think the confusion here is the distinction of "has security" and "doesn't have security".  Whether the stream "has security" (by default, category streams) or not (by default, all other streams) probably shouldn't affect the observe behavior for an unauthenticated request.  As implemented right now, this just seems like a leaky abstraction.  "If I know what the ES team thinks about security behavior of certain `null around certain stream types through out of band knowledge, then I can have expectations that don't get met.  If I don't then it's a surprise."

**Comment by gregoryyoung** [comment]
Try putting an ACL on "any other stream" and you will get the same behaviour.

**Comment by ntl** [comment]
If your intention is to avoid disclosing the existence of a category stream to an unauthenticated user, then why do individual streams work differently?

Some databases require authentication, others do not. What you are saying seems to imply that EventStore's HTTP API requires authentication, since a category subscriber cannot be built without sending an authenticated HTTP request. Why then is a subset of functionality exposed to unauthenticated requests?

**Comment by gregoryyoung** [comment]
They don't work differently. It all depends whether or not permissions are required on the read. If they are required you get a 401 if they are not you will get a 404. As simple as that. The same behaviour exists on regular streams if you set an ACL on them, if you take the ACL off system streams then they have the same behaviour as other streams without an ACL.

The reasoning as stated above is returning a 404 leaks information to an unauthenticated user.

**Comment by sbellware** [comment]
Ultimately, I think this "breaks the web". We can't rely on the meaning of HTTP status codes to tell the truth of what's happening.

I can see the point of a security policy where "missing" or "does not exist" is not communicated to an untrusted client, but I think that's a choice rather than a default, and shouldn't preclude the truthful representation of the status of some operation.

I would want to implement that policy in a layer above the communication with the database server.

As it stands, we have to handle an authorization error, and in some cases, we have to determine whether it's a not-found error. That's going to be fragile.

The crux of this challenge is in service coordination - starting a service that reads a stream that has not been written yet. On startup, we'll get an auth status, but we'll treat it as a not-found status, and then we'll wait and retry. Unless it's really an auth status, then we'd want to do something else - but we couldn't because we don't have the _truth_ of what happened.

I would rather that the implementation of policies governing the exposure of status codes to clients be left to me, and implemented, loosely-speaking, as an infrastructure concern. At this point though, I'm not given the choice because this opinion of representing 404 as an auth status is fundamental to the design of the protocol.

Personally, I'd like to see the protocol reconsidered such that things that don't exist are represented with a status code that means just that, and things that exist, but are not authorized are represented with a status code that means just that.

All that said, I'm not able to claim mastery over EventStore's security model, and admit that I'm insufficiently-informed. At the same time, I can't really find resources to help me get clear on it.

**Comment by litch** [comment]
Wait, we can just remove the ACL from system streams?  That's user-doable?

That seems like a reasonable solution for this.  Maybe the huge confusion here is the nature of that ACL, which seems to be "obfuscate from unauthenticated whether or not there is data in the case that there is not, but return to an unauthenticated user the data if there is some."

**Comment by ntl** [comment]
Agreed with @sbellware. If I wanted to start sending clients of my production eventstore 401s if they are unauthenticated, ignoring the HTTP semantics of the request, I'd put an HTTP gateway in front of event store and have it rewrite 404 responses to unauthenticated requests as 401.

**Comment by gregoryyoung** [comment]
Yes you can disable security from system streams. http://docs.geteventstore.com/server/3.4.0/access-control-lists/ I would highly not recommend doing it though for a publicly exposed node as it applies to all system streams (otherwise you need to manage per system stream ACLs)



@sbellware no. The behaviour is correct under the case that an authentication is required and has not been given. All requests should 401 never 404. Not sure why this causes an issue for your reader as it needs permissions to actually work anyways no?

**Comment by sbellware** [comment]
@gregoryyoung I haven't done anything on _my machine_ in terms of ACLs and authn/authz, so I've assumed that it's entirely optional.

**Comment by gregoryyoung** [comment]
@sbellware if you read the doc there you will see system streams require $admin by default but can be changed. Again this is the correct (IMO) default, why? Otherwise I can read your users if I know their usernames etc.

**Comment by ntl** [comment]
Why is `$ce-foo` the same kind of stream as the one that houses logins/credentials (e.g. "system" stream)?

**Comment by sbellware** [comment]
@gregoryyoung That makes sense in the case of `$users`

**Comment by litch** [comment]
@gregoryyoung I think that we're not suggesting necessarily that you expose the user list by default, say.  

Only that the policy of, "If there is data, I will return it.  Else, I will obfuscate whether there is data or that you need to authenticate", is surprising and seems unhelpful.  If the stream is "sensitive" (our `$ce-accounts` stream, for example) then it should require authentication whether or not there is data.

**Comment by gregoryyoung** [comment]
All system data is protected to admin users by default. $ce-whatever is an internal stream used for projections that you happen to be using as well (which is ok as creating two that do the same thing is silly, see below). It is used internally by projections to support fromCategory(), the relationships between the internal streams projections uses and their uses is being documented currently. 

You of course have control over how all of this works and permissions on everything, you can even move the projection to user space instead of system space.

fromAll().
   when({
       $any : function(s,e) {
                     linkTo(calculateCategory(e), e);
                  }
     })

"Only that the policy of, "If there is data, I will return it. Else, I will obfuscate whether there is data or that you need to authenticate", is surprising and seems unhelpful"

This is not obfuscating in any way. If authentication is required always return a 401. This is the correct handling. Returning a 401 "only if the stream exists" would be the leaky solution and opens an attack vector for an unauthorized user.

**Comment by litch** [comment]
```
This is not obfuscating in any way. If authentication is required always return a 401. This is the correct handling. Returning a 401 "only if the stream exists" would be the leaky solution and opens an attack vector for an unauthorized user.
```

^ The behavior you described is not accurate.  If the request is unauthenticated, and there *IS* data, then that data is returned.  If the request is unauthenticated and there *IS NOT* data, then we get a 401.  Which is weird.

**Comment by gregoryyoung** [comment]
If there is data the ACLs on the original data are used.

This is only in the case on links. I want to point out again you are using an internal stream for your purposes.

**Comment by gregoryyoung** [comment]
If anything, the only change that would be made here would be 401ing you on
data as well.

On Mon, Jan 4, 2016 at 5:27 PM, Justin Litchfield <notifications@github.com>
wrote:

> This is not obfuscating in any way. If authentication is required always return a 401. This is the correct handling. Returning a 401 "only if the stream exists" would be the leaky solution and opens an attack vector for an unauthorized user.
>
> ^ The behavior you described is not accurate. If the request is
> unauthenticated, and there *IS* data, then that data is returned. If the
> request is unauthenticated and there *IS NOT* data, then we get a 401.
> Which is weird.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/788#issuecomment-168743435>
> .
>



-- 
Studying for the Turing test

**Comment by ntl** [comment]
For posterity sake, this is how I disabled the restriction on reading system streams for development mode:

    curl -i -X POST -d '{ "$userStreamAcl" : { "$r" : "$all", "$w" : "$all", "$d" : "$all", "$mr" : "$all", "$mw" : "$all" }, "$systemStreamAcl" : { "$r" : "$all", "$w" : "$admin", "$d" : "$adm
in", "$mr" : "$admin", "$mw" : "$admin" } } ' http://127.0.0.1:2113/streams/%24settings -H 'Content-Type: application/json' -H 'ES-EventType: settings' -H 'ES-EventId: 9CBE1018-F3E9-44F6-954E
-A745C47203C6' -u admin:changeit

Closing.

**Comment by gregoryyoung** [comment]
The next version likely will not allow the read otherwise (it probably
shouldn't). Trying to figure out how it is being allowed.

On Mon, Jan 4, 2016 at 6:12 PM, Nathan Ladd <notifications@github.com>
wrote:

> Closed #788 <https://github.com/EventStore/EventStore/issues/788>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/788#event-505048836>.
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Projections is writing out a custom ACL for the stream:

{
  "$acl": {
    "$r": "$all",
    "$mr": "$all"
  }
}


On Mon, Jan 4, 2016 at 6:13 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> The next version likely will not allow the read otherwise (it probably
> shouldn't). Trying to figure out how it is being allowed.
>
> On Mon, Jan 4, 2016 at 6:12 PM, Nathan Ladd <notifications@github.com>
> wrote:
>
>> Closed #788 <https://github.com/EventStore/EventStore/issues/788>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/788#event-505048836>.
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by ntl** [comment]
It would be really nice if category streams could have separate access control policies from the other system streams.

**Comment by gregoryyoung** [comment]
They do. As I just said projections was outputting an ACL on them.

{
  "$acl": {
    "$r": "$all",
    "$mr": "$all"
  }
}


On Mon, Jan 4, 2016 at 7:03 PM, Nathan Ladd <notifications@github.com>
wrote:

> It would be really nice if category streams could have separate access
> control policies from the other system streams.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/788#issuecomment-168771743>
> .
>



-- 
Studying for the Turing test

**Comment by ntl** [comment]
I'm having trouble following what you mean there. This is the JSON payload I'm POSTing to `http://127.0.0.1:2113/streams/%24settings`:

```json
{                                                                                  
    "$userStreamAcl" : {                                                           
        "$r"  : "$all",                                                            
        "$w"  : "$all",                                                            
        "$d"  : "$all",                                                            
        "$mr" : "$all",                                                            
        "$mw" : "$all"                                                             
    },                                                                             
    "$systemStreamAcl" : {                                                         
        "$r"  : "$all",                                                            
        "$w"  : "$admin",                                                          
        "$d"  : "$admin",                                                          
        "$mr" : "$admin",                                                          
        "$mw" : "$admin"                                                           
    }                                                                              
}                                                                                  
```

Is it possible to modify that JSON to require `$admin` privileges to read any system stream, but `$all` privileges to read any category stream projection?

**Comment by gregoryyoung** [comment]
The category stream already has $all on it. This is why its reading without
authentication. Projections is outputting the stream level ACL on the
stream.

Try:

curl -i http://127.0.0.1:2113/streams/%24ce-{whateverforyou}/metadata

You will see there is an ACL on it. This is why you are seeing the
behaviour of being able to read the stream after its created.

As to why you are seeing the difference in behaviour before and after the
stream is created is that the ACL is written when the stream is created.

Greg

On Mon, Jan 4, 2016 at 7:09 PM, Nathan Ladd <notifications@github.com>
wrote:

> I'm having trouble following what you mean there. This is the JSON payload
> I'm POSTing to http://127.0.0.1:2113/streams/%24settings:
>
> {
>     "$userStreamAcl" : {
>         "$r"  : "$all",
>         "$w"  : "$all",
>         "$d"  : "$all",
>         "$mr" : "$all",
>         "$mw" : "$all"
>     },
>     "$systemStreamAcl" : {
>         "$r"  : "$all",
>         "$w"  : "$admin",
>         "$d"  : "$admin",
>         "$mr" : "$admin",
>         "$mw" : "$admin"
>     }
> }
>
> Is it possible to modify that JSON to require $admin privileges to read
> any system stream, but $all privileges to read any category stream
> projection?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/788#issuecomment-168773136>
> .
>



-- 
Studying for the Turing test

**Comment by ntl** [comment]
Right, if I understand that correctly, there is an ACL for each category stream. However, the `$systemStreamAcl` appears to govern the response code when reading category streams that do not exist (is this the case for any stream that begins with a `$`?).

I expect individual streams to also have their own ACL. However, when reading an individual stream that doesn't exist, the `$userStreamAcl` ultimately governs the response code.

The behavior of the system makes sense now. Category streams are considered internal to EventStore and are used to drive projections. My application can either depend on them directly or depend on a "user" projection that mirrors it. The former choice has fewer moving parts, but requires privileges not vested in unauthorized users by default. The latter choice has all of the downsides you might expect when duplicating a stream, and additionally requires explicitly creating a projection that mirrors the category stream before use, but works with an unauthenticated user "out of the box."

It would be nice if the documentation made this clear. It would be even nicer if, by default, all category streams could be accessed through a user stream with a consistent naming pattern similar to `$ce-`. It could just be a "symlink" of sorts, but with a separate ACL. That way, from my application's perspective, the security policies for both category streams and individual streams can be made consistent for all types of streams that do not yet exist.

**Comment by gregoryyoung** [comment]
"It would be nice if the documentation made this clear. It would be even
nicer if, by default, all category streams could be accessed through a user
stream with a consistent naming pattern similar to $ce-. It could just be a
"symlink" of sorts, but with a separate ACL. That way, from my
application's perspective, the security policies for both category streams
and individual streams can be made consistent for all types of streams that
do not yet exist."

The documentation will make this clear, projections are a beta feature.

OK what about byType streams? What about competing consumer statuses?
Projection by category statuses? what about by stream-category? Very
quickly the configuration becomes unwieldy. I understand that you want what
works for your scenario but it would come at a large cost to many other
scenarios.



On Mon, Jan 4, 2016 at 8:05 PM, Nathan Ladd <notifications@github.com>
wrote:

> Right, if I understand that correctly, there is an ACL for each category
> stream. However, the $systemStreamAcl appears to govern the response code
> when reading category streams that do not exist (is this the case for any
> stream that begins with a $?).
>
> I expect individual streams to also have their own ACL. However, when
> reading an individual stream that doesn't exist, the $userStreamAcl
> ultimately governs the response code.
>
> The behavior of the system makes sense now. Category streams are
> considered internal to EventStore and are used to drive projections. My
> application can either depend on them directly or depend on a "user"
> projection that mirrors it. The former choice has fewer moving parts, but
> requires privileges not vested in unauthorized users by default. The latter
> choice has all of the downsides you might expect when duplicating a stream,
> and additionally requires explicitly creating a projection that mirrors the
> category stream before use, but works with an unauthenticated user "out of
> the box."
>
> It would be nice if the documentation made this clear. It would be even
> nicer if, by default, all category streams could be accessed through a user
> stream with a consistent naming pattern similar to $ce-. It could just be
> a "symlink" of sorts, but with a separate ACL. That way, from my
> application's perspective, the security policies for both category streams
> and individual streams can be made consistent for all types of streams that
> do not yet exist.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/788#issuecomment-168788363>
> .
>



-- 
Studying for the Turing test

**Comment by ntl** [comment]
From the perspective of my application, a subscription to the family of streams that start with `foo` ought to behave exactly like a subscription to `foo-1234`, except where those subscriptions are inherently different. That includes the case where those streams do not exist.

I get why a different ACL is in play when accessing a non-existent category stream vs. a non-existent individual stream. It's chiefly used internally by EventStore, and I'm merely wanting to tag along. If I'm hitchhiking, the driver gets to choose the radio station.

The answer for my issue is to either live with the inherent complexity, or cause my application to depend on a 1:1 projection of the category stream. For that reason, I closed my issue (it's resolved). Still, I think EventStore might be improved by providing separate interfaces for system and user streams (e.g. slightly different URI path). That way, some internal streams like category streams that are also inherently useful to applications could be exposed by both interfaces. It's a bit weird to serve a single resource via two distinct URIs, but I believe the `Content-Location` header can specify which is canonical. The win would be that applications can depend on an interface where purely system streams like the one housing user accounts are simply impossible to reach. Perhaps the benefit wouldn't merit the effort, but I thought I'd leave this with my $0.02.
