### ISSUE TITLE
Setting ExtIp to 0.0.0.0 breaks HTTP server

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStore#790]
I have a 3 instance cluster. If I set ExtIp to 127.0.0.1 in all instances (because clients are all local on the same machine), it works. If I change ExtIp to 0.0.0.0 (meaning, bind to all interfaces), then the internal HTTP server doesn't come up, and the cluster breaks.

With ExtIp set to 0.0.0.0 the startup log looks like this:

```
[PID:30530:024 2016.01.12 03:34:53.791 INFO  HttpAsyncServer     ] Starting HTTP server on [http://*:2113/]...
[PID:30530:024 2016.01.12 03:34:53.826 INFO  HttpAsyncServer     ] HTTP server is up and listening on [http://*:2113/]
[PID:30530:024 2016.01.12 03:34:53.849 TRACE InMemoryBus         ] SLOW BUS MSG [MainBus]: SystemInit - 251ms. Handler: HttpService.
[PID:30530:024 2016.01.12 03:34:53.849 INFO  HttpAsyncServer     ] Starting HTTP server on []...
```

Note the empty [] where the address normally goes. This causes gossip to fail, and the whole cluster fails, with constant reelection attempts.

Also note that it is the external IP config that breaks the internal HTTP server, which is weird, but there you go.

**Comment by pgermishuys** [comment]
1. What OS are you running on?
2. What version of Event Store?
3. What does your configuration look like? i.e. are you setting `--add-interface-prefixes=false`?

**Comment by rickardoberg** [comment]
1:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

2: 
```
3.3.0.0 (release-v3.3.0/4923f4c0f427a85a275f362402e62645bca38c07, Wed, 7 Oct 2015 07:37:39 +0200)
```

3:
```
---
RunProjections: None
ClusterSize: 3
Db: /var/opt/eventstore
IntIp: 172.31.33.229
ExtIp: 0.0.0.0

IntTcpHeartbeatTimeout: 2000
ExtTcpHeartbeatTimeout: 2000
IntTcpHeartbeatInterval: 5000
ExtTcpHeartbeatInterval: 5000
GossipTimeoutMs: 2000

AdminOnExt: false
DiscoverViaDns: false
GossipSeed: 172.31.33.228:2112,172.31.36.140:2112
```

**Comment by pgermishuys** [comment]
Ok, the issue is not the 0.0.0.0 but rather the internal HTTP prefixes that haven't been specified for the internal http service which is what the http service uses to listen on/bind to.

Can you try the following configuration?

```
---
RunProjections: None
ClusterSize: 3
Db: /var/opt/eventstore
IntIp: 172.31.33.229
ExtIp: 0.0.0.0
ExtHttpPrefixes: http://*:2113/
IntHttpPrefixes: http://*:2112/
AddInterfacePrefixes: false

IntTcpHeartbeatTimeout: 2000
ExtTcpHeartbeatTimeout: 2000
IntTcpHeartbeatInterval: 5000
ExtTcpHeartbeatInterval: 5000
GossipTimeoutMs: 2000

AdminOnExt: false
DiscoverViaDns: false
GossipSeed: 172.31.33.228:2112,172.31.36.140:2112
```

**Comment by rickardoberg** [comment]
Fantastic, this did the trick! Is this in the docs? If not, please add it.

**Comment by gregoryyoung** [comment]
The whole concept of http prefixes is thankfully going away soon :)

On Wed, Jan 13, 2016 at 5:12 AM, Rickard Öberg <notifications@github.com>
wrote:

> Fantastic, this did the trick! Is this in the docs? If not, please add it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/790#issuecomment-171160370>
> .
>



-- 
Studying for the Turing test

**Comment by lassebn** [comment]
Can you elaborate on the state of http prefixes? I just got my cluster up and running by the help of this issue thread and setting `ExtHttpPrefixes` in my configuration files.

Is there another preferred way or does `ExtHttpPrefixes` live on?
