### ISSUE TITLE
408 response code on /projections/all-non-transient

### ISSUE THREAD

**Issue by mindriven** [EventStore/EventStore#797]
I'm runnung latest release, that is oss-v3.4.0 on Windows 7. When I go to URL /web/index.html#/projections and wait a moment (few seconds) I get error notificarion shown (btw. error message is way to generic). Using web debugger I see that this is most likely caused by call to /projections/all-non-transient that is made in the background and ends with 408.
Also: why is link to projections not present in main menu? Are they getting deprecated?
![408](https://cloud.githubusercontent.com/assets/4957654/12711153/c23fe046-c8bd-11e5-8bc0-8a1600b86181.png)

**Comment by gregoryyoung** [comment]
--run-projections=all is set?

**Comment by pgermishuys** [comment]
As @gregoryyoung has suggested. The menu item for projections will not be present if projections aren't enabled by any one of the configuration options (command line, config file, environment variable). This is likely why you are seeing the error as you are probably navigating to the url directly.

**Comment by mindriven** [comment]
@gregoryyoung no, it was not set and that was the cause. Thanks for help and sorry for confusion. Still, should the projections url be available at all when this functionalisy is not enabled? I assume it's a minor issue, but still something to consider.

**Comment by pgermishuys** [comment]
You should be seeing a 404 here if projections aren't enabled. We'll take a look at it if that's not the case.
