### ISSUE TITLE
Can't seem to find documentation on data_content_type

### ISSUE THREAD

**Issue by tbug** [EventStore/EventStore#805]
I can't find any documentation on the possible values for `data_content_type`.
( in https://github.com/EventStore/EventStore/blob/release-v3.4.1/src/Protos/ClientAPI/ClientMessageDtos.proto#L18 ) 

I _did_ find this thread
https://groups.google.com/forum/#!topic/event-store/ID3_ksintKE
with `json=1` `xml=2`.

Are the docs hidden somewhere, or is the .NET client the best place to look for these things?

 (I'm currently using https://github.com/exponentially/extreme to connect to EventStore)

**Comment by gregoryyoung** [comment]
Right now its just json/xml. It was originally a bit flag but was made into
a number to allow for future expansion

On Wed, Feb 17, 2016 at 11:51 AM, Henrik Tudborg <notifications@github.com>
wrote:

> I can't find any documentation on the possible values for
> data_content_type.
> ( in
> https://github.com/EventStore/EventStore/blob/release-v3.4.1/src/Protos/ClientAPI/ClientMessageDtos.proto#L18
> )
>
> I *did* find this thread
> https://groups.google.com/forum/#!topic/event-store/ID3_ksintKE
> with json=1 xml=2.
>
> Are the docs hidden somewhere, or is the .NET client the best place to
> look for these things?
>
> (I'm currently using https://github.com/exponentially/extreme to connect
> to EventStore)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/805>.
>



-- 
Studying for the Turing test

**Comment by tbug** [comment]
The client lib I'm using use `data_content_type=0` in it's example,
with a custom serialization (erlang's `erlang:term_to_binary`).

Is it a sensible assumption that
```
0 == unknown
1 == json
2 == xml
```
and that we can implement enums in our clients with those values?
Or will the values change in a future versions of EventStore?

**Comment by gregoryyoung** [comment]
They will not be changing though this is not even exposed in the .NET
client (only a flag "isjson"). The only thing that uses this is projections
(its a flag that lets projections know it can deserialize the data of an
event)

On Wed, Feb 17, 2016 at 12:02 PM, Henrik Tudborg <notifications@github.com>
wrote:

> The client lib I'm using use data_content_type=0 in it's example,
> with a custom serialization (erlang's erlang:term_to_binary).
>
> Is it a sensible assumption that
>
> 0 == unknown
> 1 == json
> 2 == xml
>
> and that we can implement enums in our clients with those values?
> Or will the values change in a future versions of EventStore?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/805#issuecomment-185172335>
> .
>



-- 
Studying for the Turing test

**Comment by tbug** [comment]
Alright :+1:
I'll add that functionality to the Elixir client as well.
What happens in a projection if the type is something else than json?

**Comment by gregoryyoung** [comment]
the projection won't try to deserialize it as an object in v8 (it will only
have the raw data set)

On Wed, Feb 17, 2016 at 12:09 PM, Henrik Tudborg <notifications@github.com>
wrote:

> Alright [image: :+1:]
> I'll add that functionality to the Elixir client as well.
> What happens in a projection if the type is something else than json?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/805#issuecomment-185173525>
> .
>



-- 
Studying for the Turing test

**Comment by tbug** [comment]
Aight. Thanks :+1:
