### ISSUE TITLE
Redirects to 0.0.0.0 makes HTTP access impossible

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStore#810]
For EventStore 3.4.0, Ubuntu 14.04, running on EC2

Our cluster with 3 instances have this config:
```
ExtIp: 0.0.0.0
ExtHttpPrefixes: http://*:2113/
IntHttpPrefixes: http://*:2112/
AddInterfacePrefixes: false
```

We have an AWS ELB fronting these, and when we access the cluster using http://ourdnsname:2113/streams/$all, we get a redirect to http://0.0.0.0:2113/streams/$all.

This makes it impossible for us to access the cluster using HTTP. We tried using the public IP of a particular instance, but with same result.

Please turn off these redirects, or make it possible to configure EventStore so that they don't occur.

**Comment by pgermishuys** [comment]
@rickardoberg I'm assuming that the above configuration, you accidentally left out the host part in the prefixes?
```
ExtIp: 0.0.0.0
ExtHttpPrefixes: http://*:2113/
IntHttpPrefixes: http://*:2112/
AddInterfacePrefixes: false
```
Also, are you saying that accessing the Event Store HTTP api via the public ip is giving you a redirect to 0.0.0.0?

Out of curiosity what does a curl give you to for instance the stats?
e.g.
`curl -i http://{public-ip}:2113/stats -H "accept:application/json"`

**Comment by rickardoberg** [comment]
@pgermishuys I'm using the configuration that you told me to use, remember: https://github.com/EventStore/EventStore/issues/790#issuecomment-170801379

So yeah, if I do this:
`wget --password=xxx --user=xxx --header "Accept: application/vnd.eventstore.atom+json" http://ourdnsname:2113/streams/%24all`
Then I get this:
```
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: http://0.0.0.0:2113/streams/%24all [following]
--2016-02-23 14:37:13--  http://0.0.0.0:2113/streams/%24all
Connecting to 0.0.0.0:2113... failed: Connection refused.
```

If I do a curl on the stats, as per above, it gives me the correct response, i.e. no redirect and JSON data.

**Comment by pgermishuys** [comment]
Is there any particular reason why you aren't specifying the ip address in your ES configuration? i.e. not 0.0.0.0 but the address of the instance? I recall in the original issue that you were specifying the int ip address?

**Comment by rickardoberg** [comment]
@pgermishuys yes, there are three types of communication going on here. The cluster instances need to talk to each other, so we set the int ip to the real IP's and generate configuration for each EventStore instance. Each EventStore server also hosts the actual app, and they should all do "localhost" connections to EventStore. If I bind to 0.0.0.0 that works, if I specify the actual IP for ext ip, then I need to configure each instance of the app with that same IP for the local server, which I want to avoid (unnecessary complexity). The third is that we have external readers of the streams (for ELK integration specifically), and they need to be able to use the public IPs in EC2. We don't mind generating configuration for those external readers, but we're really trying to avoid having to generate config for the localhost application instances, if possible. If binding to 0.0.0.0 worked as expected it shouldn't be a problem. No?

**Comment by pgermishuys** [comment]
Ok, let me have a look at it and get back to you. Apologies for the delay.

**Comment by pgermishuys** [comment]
@rickardoberg you can still bind to 0.0.0.0 but then Event Store requires an additional bit of configuration set which is the `ExtIpAdvertiseAs`. ( more on the advertise parameters can be found here http://docs.geteventstore.com/server/3.4.0/command-line-arguments/ )
Example configuration.
```
RunProjections: None
ClusterSize: 3
Db: /var/opt/eventstore
IntIp: 172.31.33.229
ExtIp: 0.0.0.0

ExtIpAdvertiseAs: 172.31.33.229

IntTcpHeartbeatTimeout: 2000
ExtTcpHeartbeatTimeout: 2000
IntTcpHeartbeatInterval: 5000
ExtTcpHeartbeatInterval: 5000
GossipTimeoutMs: 2000

AdminOnExt: false
DiscoverViaDns: false
GossipSeed: 172.31.33.228:2112,172.31.36.140:2112
```

Let me know if this solves the problem.

**Comment by rickardoberg** [comment]
@pgermishuys yes, that seems to work. So if I understand it correctly, the reason for the redirect is to ensure that the call goes to the master, correct? So what happens now is that our ELK input plugin can call to ourdnsname:2113/streams/$all, which is a load balancer, which then goes to any of the backing EventStore instances. If it is a slave, then a redirect happens, but to the public IP, which then works. So, in this setup we do not have to configure out ELK client with all IPs, just ourdnsname that points to the load balancer, and it's all good.

I would say the main remaining issue here is to improve the docs. They are incredibly sparse on what the settings actually do, not to mention that the formatting is bizarre (the last column needs scrolling in the browser to see). Would have saved lots of time!

In any case, thanks for your help!

**Comment by pgermishuys** [comment]
@rickardoberg you are correct in that the redirect is to forward the request to master.
On your point with regards to the documentation, you are spot on, the documentation needs improving.

Thank you for your patience.
