### ISSUE TITLE
Projection has events out of order

### ISSUE THREAD

**Issue by kstrauss** [EventStore/EventStore#814]
We are running on a single node of GES (3.0.3.0) and we are seeing events that are out of order. from reading https://geteventstore.com/blog/20130309/projections-7-multiple-streams/ I see the phrase 

> If you are running in a single node group (not partitioned, either the replicated group or single node) then this projection will have assurances that the events will come in perfect order (even when being processed in real time). 

We have a projection of:

``` javascript
//
// Collects all the Package events in a single stream
// known major consumer is the readmodel service
//
fromStreams(
    ['$et-PackageIdentified',
'$et-PackageDecoded',
'$et-PackageDecodedWithConcerns',
'$et-PackageCreated',
'$et-PackageContainerized',
'$et-PackagePlaced',
'$et-PackageIntegrated',
'$et-PackageIgnored',
'$et-PackageConcernsAddressed',
'$et-PackagePublished',
'$et-ItemDecoded',
'$et-ItemConcernsAddressed',
'$et-ItemEventsPublished']
    )
    .when({
        $init: function (s, e) {
            return {
                countReceived: 0,
            };
        },
        $any: function (s, e) {
            linkTo('Xi::AllPackageEvents', e);
            s.countReceived += 1;
            return s;
        }
    });
```

In some cases we are seeing events written to the Xi::AllPackageEvents come out of order. For example:
![image](https://cloud.githubusercontent.com/assets/3475426/13293888/98978e30-daef-11e5-846b-6aa40b474fe9.png)

Should we instead of written our projection something along the lines of:

``` javascript
//
// Collects all the Package events in a single stream
// known major consumer is the readmodel service
//
var $destStream = 'tst::AllPackageEvents';
fromAll()
.when({
    $init : function (s, e) {
        return {
            countReceived : 0,
        };
    },
    'PackageIdentified' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackageDecoded' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackageDecodedWithConcerns' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackageCreated' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackageContainerized' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackagePlaced' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackageIntegrated' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackageIgnored' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackageConcernsAddressed' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'PackagePublished' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'ItemDecoded' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'ItemConcernsAddressed' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    },
    'ItemEventsPublished' : function (s, e) {
        linkTo($destStream, e);
        s.countReceived += 1;
        return s;
    }
});
```

When I do this I do not get an identical output stream:
![image](https://cloud.githubusercontent.com/assets/3475426/13295297/2cc23320-daf6-11e5-9b39-e3312b5cd11b.png)

I had thought that these two projection definitions were functionally identical, that it would not matter if I used $et. Is this actually the case?

**Comment by gregoryyoung** [comment]
fromStreams does not have perfect ordering IIRC between streams but has
perfect ordering within each stream.

In your two examples above it does not seem to be talking about the same
events?

On Wed, Feb 24, 2016 at 8:05 PM, Karl Strauss <notifications@github.com>
wrote:

> We are running on a single node of GES (3.0.3.0) and we are seeing events
> that are out of order. from reading
> https://geteventstore.com/blog/20130309/projections-7-multiple-streams/ I
> see the phrase
>
> If you are running in a single node group (not partitioned, either the
> replicated group or single node) then this projection will have assurances
> that the events will come in perfect order (even when being processed in
> real time).
>
> We have a projection of:
>
> //// Collects all the Package events in a single stream// known major consumer is the readmodel service//fromStreams(
>     ['$et-PackageIdentified','$et-PackageDecoded','$et-PackageDecodedWithConcerns','$et-PackageCreated','$et-PackageContainerized','$et-PackagePlaced','$et-PackageIntegrated','$et-PackageIgnored','$et-PackageConcernsAddressed','$et-PackagePublished','$et-ItemDecoded','$et-ItemConcernsAddressed','$et-ItemEventsPublished']
>     )
>     .when({
>         $init: function (s, e) {
>             return {
>                 countReceived: 0,
>             };
>         },
>         $any: function (s, e) {
>             linkTo('Xi::AllPackageEvents', e);
>             s.countReceived += 1;
>             return s;
>         }
>     });
>
> In some cases we are seeing events written to the Xi::AllPackageEvents
> come out of order. For example:
> [image: image]
> <https://cloud.githubusercontent.com/assets/3475426/13293888/98978e30-daef-11e5-846b-6aa40b474fe9.png>
>
> Should we instead of written our projection something along the lines of:
>
> //// Collects all the Package events in a single stream// known major consumer is the readmodel service//var $destStream = 'tst::AllPackageEvents';fromAll()
> .when({
>     $init : function (s, e) {
>         return {
>             countReceived : 0,
>         };
>     },
>     'PackageIdentified' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackageDecoded' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackageDecodedWithConcerns' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackageCreated' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackageContainerized' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackagePlaced' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackageIntegrated' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackageIgnored' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackageConcernsAddressed' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'PackagePublished' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'ItemDecoded' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'ItemConcernsAddressed' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     },
>     'ItemEventsPublished' : function (s, e) {
>         linkTo($destStream, e);
>         s.countReceived += 1;
>         return s;
>     }
> });
>
> When I do this I do not get an identical output stream:
> [image: image]
> <https://cloud.githubusercontent.com/assets/3475426/13295297/2cc23320-daf6-11e5-9b39-e3312b5cd11b.png>
>
> I had thought that these two projection definitions were functionally
> identical, that it would not matter if I used $et. Is this actually the
> case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/814>.
>



-- 
Studying for the Turing test

**Comment by kstrauss** [comment]
I'm not sure what you mean about the same events? They are from the same original source stream of  Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 , The two projections created do not have the same events in the same positions, but should have all the same events.

So if what you recall is true then you should not compose projections (with sub projections, the first example), if ordering is important ? You should use the second example.

**Comment by mathiasbn** [comment]
This issue is added to 3.6.0, but it didn't sound like you see it as a bug.
At least they are still out of order in "EventStore-OSS-Win-v3.6.0".
 
Reading the blog "Projections 8: internal indexing" I would expect it to be equal but faster to use fromStreams('$et-XXX','$et-XXY',...) instead of fromAll().

> "...This can now be converted into an indexed projection using fromStreams()..."

So my question at last. Is this a bug (and will it / should it be fixed)?

**Comment by pgermishuys** [comment]
All the issues raised on github is seen as a bug unless it's clear that it's a question or a suggestion.
Projections are actively being worked on and looked at as we it's being moved from Beta to Production and this is one of the issues we are looking to resolve which is why this issue is still open

**Comment by mathiasbn** [comment]
So you are considering making it "perfect ordered" but are not sure? Or how should this issue be read.

**Comment by hayley-jean** [comment]
`fromStreams` uses best-attempt ordering so we can't guarantee that the events you receive will be in order.

If you need guaranteed ordering, use `fromAll` instead.
