### ISSUE TITLE
ES Client Subscription delivering event out of order

### ISSUE THREAD

**Issue by kstrauss** [EventStore/EventStore#815]
Happened at the same time as #814 , but I believe coincidental.

An service had a subscription to the same stream that was created by the projection in #814, so it's a single catchup subscription.

We saw an event that was delivered out of order as compared to the source stream. i.e. the stream looks like:
![image](https://cloud.githubusercontent.com/assets/3475426/13295946/360a8984-daf9-11e5-8079-5fba41a90ecf.png)

Yet in our logs (a edited version) we see that we handled:
PackageMonitorSvc starting to handle eventType ItemEventsPublished from stream Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 @ 1,067
PackageMonitorSvc successfully handled eventType ItemEventsPublished from stream Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 @ 1,067
PackageMonitorSvc starting to handle eventType PackageIdentified from stream Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 @ 0
PackageMonitorSvc successfully handled eventType PackageIdentified from stream Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 @ 0
PackageMonitorSvc starting to handle eventType ItemEventsPublished from stream Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 @ 1,069
PackageMonitorSvc successfully handled eventType ItemEventsPublished from stream **Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 @ 1,069
PackageMonitorSvc starting to handle eventType PackageIdentified from stream Xi::Nicor-ReceivedPackage_28b47b4e00ca56b39dad6df511e150fd @ 0
PackageMonitorSvc successfully handled eventType PackageIdentified from stream Xi::Nicor-ReceivedPackage_28b47b4e00ca56b39dad6df511e150fd @ 0**
PackageMonitorSvc starting to handle eventType ItemEventsPublished from stream Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 @ 1,071
PackageMonitorSvc successfully handled eventType ItemEventsPublished from stream Xi::IntegrysMgu-ReceivedPackage_39be72a53c1654528eca33f6a3e960f3 @ 1,071

The bold lines show that these events were delivered by the client out of order. We understand that we might received events more than once, but in this case we received things way out of order.

In the ES log, i don't see anything unusual during this period

ES. 3.0.3 server and 3.0.3 client.

**Comment by gregoryyoung** [comment]
Is this reproducible? What do verbose client logs say as opposed to your logs? Also you have not specified what type of subscription this is?

**Comment by kstrauss** [comment]
I'm now more confused as to what's happening! In an effort to reproduce I dropped the database (read model) where these events were being sent and reset our checkpoints and restarted the services.

Now looking at the logs not only did it not happen again, but the events arrived in the expected order (i.e. event 0, 1, 2, 3, 4) even though the stream (which has not changed) has events out of order as I showed in #814 .

**Comment by gregoryyoung** [comment]
Maybe you can show us which events are in which stream? As of now it seems
you have some stream with incoming messages. Have some projections which I
presume are also creating streams. Have a subscription to some stream from
one of the two or maybe some other stream?). I am not really sure what is
actionable on our side (even to try to diagnose) in any of these threads.

CatchupSubscriptions don't reorder events. They will provide events in the
same order the events are in the stream the subscription is from.

On Thu, Feb 25, 2016 at 1:40 AM, Karl Strauss <notifications@github.com>
wrote:

> I'm now more confused as to what's happening! In an effort to reproduce I
> dropped the database (read model) where these events were being sent and
> reset our checkpoints and restarted the services.
>
> Now looking at the logs not only did it not happen again, but the events
> arrived in the expected order (i.e. event 0, 1, 2, 3, 4) even though the
> stream (which has not changed) has events out of order as I showed in #814
> <https://github.com/EventStore/EventStore/issues/814> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/815#issuecomment-188518886>
> .
>



-- 
Studying for the Turing test

**Comment by kstrauss** [comment]
after further review, I did get myself confused. They did come in the order that they were in the stream, i got myself confused. Sorry.

I was not able to reproduce the result.
The subscription was a catchup subscription.
We do not normally enable client logging, so I do not have those to share.

**Comment by pgermishuys** [comment]
No problem @kstrauss. Thanks for getting back to us.
I'm going to close the issue for now, please reopen if you feel there is still an issue we need to look at
