### ISSUE TITLE
maxSubscriberCount ignored when creating/updating persistent subscriptions.

### ISSUE THREAD

**Issue by rayrutjes** [EventStore/EventStore#835]
maxSubscriberCount always stays at 10 whatever we provide as a value.

I am using the http api.

This affects both the create and update operations of persistent subscriptions.

This can also be observed by updating the MaxSubscriberCount value in the UI.

**Comment by gregoryyoung** [comment]
:+1: will check where its not coming through

**Comment by rayrutjes** [comment]
:+1: thx!
