### ISSUE TITLE
Scavenging UI does not update correctly

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#838]
If some sort of "expected" error happens and a node commits suicide after having done a scavenge, then the UI still says it is running, e.g.:

![screen shot 2016-03-08 at 1 47 15 pm](https://cloud.githubusercontent.com/assets/153607/13603655/ac200094-e536-11e5-9117-fff921a8f761.png)

You can see that I have initiated a second run for a node that still says it is running.

**Comment by gregoryyoung** [comment]
I think its just the message that needs to be changed in the UI.

Basically there is a started event, some events that happen along the way, then a finished event. Maybe having the messages read "started" would be better than "running".

**Comment by ahjohannessen** [comment]
It's probably a completed event that is not emitted when an exception is thrown during scavenging.

**Comment by gregoryyoung** [comment]
You have said two very different things here. One is a node being shutdown during a scavenge the other is an exception during a scavenge. An exception should put an error but shutting down a node during scavenge just stops the scavenge mid way (no errors etc) but it will never complete.

**Comment by ahjohannessen** [comment]
@gregoryyoung Yeah, I know, sorry for being vague. I looked through a stream and noticed started and finished events, and reckoned that when an exception is thrown, the completed part is not reflected on the UI (even though it is "finished").

**Comment by ahjohannessen** [comment]
>>An exception should put an error but shutting down a node during scavenge just stops the scavenge mid way (no errors etc) but it will never complete.

Perhaps that is a bit unfortunate UI wise, having a "Running..." forever.

**Comment by ahjohannessen** [comment]
Could it be solved with some sort of max TTL?

**Comment by gregoryyoung** [comment]
Not really unless we put it at a silly level like 2-3 days (there are people out there with multi-tb dbs running on spindle disks!)

I would lean towards just changing the wording to "Not finished". @hayley-jean what do you think?

**Comment by ahjohannessen** [comment]
Yeah, good call. "Not Finished" is a good compromise in this case, IMO.

**Comment by hayley-jean** [comment]
Yeah, I agree, "Not finished" would be much better

**Comment by ahjohannessen** [comment]
@hayley-jean you get my point:

![screen shot 2016-03-08 at 2 20 49 pm](https://cloud.githubusercontent.com/assets/153607/13604109/1e9aea9c-e539-11e5-9594-9170cebfb196.png)

**Comment by hayley-jean** [comment]
@ahjohannessen Yeah, that doesn't look great at all

**Comment by gregoryyoung** [comment]
@hayley-jean lets change that quickly and reference this issue.

@ahjohannessen <https://github.com/ahjohannessen> as its just a UI change
you can pull the UI down at anytime (no need to wait for next version).

Cheers,

Greg

On Tue, Mar 8, 2016 at 4:25 PM, Hayley Campbell <notifications@github.com>
wrote:

> @ahjohannessen <https://github.com/ahjohannessen> Yeah, that doesn't look
> great at all
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/838#issuecomment-193802930>
> .
>



-- 
Studying for the Turing test

**Comment by ahjohannessen** [comment]
@gregoryyoung arright, not a biggie. Thanks :+1:
