### ISSUE TITLE
Why do two events with the same GUID in a batch end up being written as two distinct events?

### ISSUE THREAD

**Issue by Jubobs** [EventStore/EventStore#841]
I'm using the HTTP API of Event Store 3.4.0.0 for [batch writes](http://docs.geteventstore.com/http-api/3.4.0/writing-to-a-stream/#batch-writes). I've noticed that, if a batch contains two (or more) events with the same GUID, those events end up being written as _distinct_ events.

Below is a sample HTTP request for reproducing the behaviour; note that the JSON array in the payload contains two events with identical GUID:

```
POST /streams/myStream0 HTTP/1.1
Host: 192.168.99.100:2113
Authorization: Basic YWRtaW46Y2hhbmdlaXQ=
ES-EventType: SomeEvent
Content-Type: application/vnd.eventstore.events+json
Cache-Control: no-cache
Postman-Token: f91b8d0f-c628-a195-90ee-a6b84954fbf1

[
  {
    "eventId": "fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4",
    "eventType": "event-type",
    "data": { "a": "1" }
  },
  {
    "eventId": "fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4",
    "eventType": "event-type",
    "data": { "a": "1" }
  }
]
```

If I send this request, two events get written in the Web UI:

<img width="1385" alt="screen shot 2016-03-09 at 15 29 48" src="https://cloud.githubusercontent.com/assets/7138892/13640364/3f74b1c0-e60c-11e5-8b77-35c832767588.png">

I find this behaviour surprising. On the one hand, you could argue that, if the client specifies the GUID herself, the onus is on her not to batch multiple events with the same GUID. On the other hand, shouldn't the server prevent the user from shooting herself in the foot?

Is this behaviour the result of a deliberate design decision, or can it be considered a bug? If it is by design, what is the rationale behind this design decision?

**Comment by gregoryyoung** [comment]
The check happens before the write they are then written as a batch. 

We are generally assuming that people don't put duplicate guids inside of a batch. We could check for this but it has a cost.

**Comment by Jubobs** [comment]
> Are you suggesting you want us to make you idempotent within your own request?

Nah, I guess that's the user's responsibility. The associated cost of checking this server-side probably isn't worth it. I was just being curious.

Thanks, Greg. Keep up the good work!

**Comment by gregoryyoung** [comment]
You will likely run into another "oddity" with idempotency. As example:

Reqeust 1:
W id 17
W id 19
W id 20

Request 2:
W id 14
W id 19
W id 20
W id 28

Will reject the entirety of the batch.

**Comment by Jubobs** [comment]
That's good to know. Thanks.

For information, I ran into this initially puzzling behaviour while testing. Would it be worth documenting it somewhere else than the GitHub issue tracker (i.e. in the Event Store documentation)?

**Comment by gregoryyoung** [comment]
You can add it to the idempotency page if you want (the docs are just a git repo)

**Comment by Jubobs** [comment]
Will do! Thanks again.
