### ISSUE TITLE
Invalid characters in stream name

### ISSUE THREAD

**Issue by ircnelson** [EventStore/EventStore#865]
I append an event using '/' and '\' in the stream name on purpose and it was saved, but in the management it broke. 

I tried to fix it and put some tests, but the infrastructure and test runner in the project are messy in my opnion.
When I execute the run_tests.sh nothing happens.

If anybody want explain for me how I run the unit tests I will be glad. :-)

**Comment by gregoryyoung** [comment]
There is a pull request around / in stream name. Oddly this is a special case between TCP clients and http clients.

https://github.com/EventStore/EventStore/pull/859

re run_tests if you cat the script its not very complex works fine on any linux box I have worked on that had mono installed

**Comment by gregoryyoung** [comment]
Also I havn't tried \ but it should be %5c encoded ...

**Comment by ircnelson** [comment]
Ok @gregoryyoung. tks for awnser.
