### ISSUE TITLE
Method ConnectToPersistentSubscription causes deadlock

### ISSUE THREAD

**Issue by Andrii-Litvinov** [EventStore/EventStore#881]
Hi,

I have started to use EventStore recently in my project. Especially Persistent subscription. I encounter deadlock when I try to subscribe. I can 100% reproduce with following use-case:

- Connect to persistent subscription for the first time while it's not yet exists.
- Catch ArgumentException with message "Subscription not found" and create requested subscription.
- Connect to newly created pesistent subscription.

Deadlock occures in ConnectToPersistentSubscription method. Sometimes in happens during first try to connect. In other cases it deadlocks on second try.

I have investigated an implementation and noticed that StartSubscription method of EventStorePersistentSubscription class waits on a task. Which actually causes a deadlock.

I have worked it around by using a reflection for now to start that StartSubscription task and await it properly.

Is there any reason why that task is waited instead of making ConnectToPersistentSubscription method fully async? If not, would it be possible to have an async method ConnectToPersistentSubscriptionAsync? I believe I can create a pull-request with this fix implemented.

Cheers,
Andrii

**Comment by gregoryyoung** [comment]
I am trying to figure out why the wait is actually needed there at all. If it blocks then yes it should have an async version and return a task

**Comment by edblackburn** [comment]
Just to add that I am intermittently observing this behaviour too.
