### ISSUE TITLE
fromAll linkTos

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#890]
FromAll should support saying whether or not it wants the events resolved if it currently does not.

**Comment by pgermishuys** [comment]
When setting up projections, there a set of options that can be set, one of them that applies to `fromAll` is `$includeLinks` which you can set to true/false.
e.g.
```
options({
    $includeLinks: false
})
fromAll().whenAny(function (s, e) {
    linkTo("no_links", e);
});
```
There is some logic missing, expect a PR shortly.
