### ISSUE TITLE
Read only access to web UI

### ISSUE THREAD

**Issue by rcknight** [EventStore/EventStore#893]
Currently it is not possible to create a user with no write permissions, but who is still able to log in to the web UI. This is due to hardcoded checks for membership of $admins:(https://github.com/EventStore/EventStore/blob/8ceb6419f797356e050d00bc57d92c43bf605650/src/EventStore.Core/Services/Transport/Http/Controllers/InfoController.cs#L63)

I hoped that something like the following in $settings would work, but admins are currently too special,  a member of READONLY_ADMINS cannot log in.

```
{
    "$userStreamAcl" : {
        "$r"  : "$all",
        "$w"  : "NONSYSTEM_WRITERS",
        "$d"  : "NONSYSTEM_WRITERS",
        "$mr" : "$all",
        "$mw" : "NONSYSTEM_WRITERS"
    },
    "$systemStreamAcl" : {
        "$r"  : ["$admins","READONLY_ADMINS"],
        "$w"  : "$admins",
        "$d"  : "$admins",
        "$mr" : ["$admins","READONLY_ADMINS"],
        "$mw" : "$admins"
    }
}
```

Alternatively, maybe I should be able to remove system write access from $admins and grant it to another group instead?

```
{
    "$userStreamAcl" : {
        "$r"  : "$all",
        "$w"  : ["NONSYSTEM_WRITERS", "SUPER_ADMINS"],
        "$d"  : ["NONSYSTEM_WRITERS", "SUPER_ADMINS"],
        "$mr" : "$all",
        "$mw" : ["NONSYSTEM_WRITERS", "SUPER_ADMINS"]
    },
    "$systemStreamAcl" : {
        "$r"  : ["$admins","SUPER_ADMINS"],
        "$w"  : "SUPER_ADMINS",
        "$d"  : "SUPER_ADMINS",
        "$mr" : ["$admins","SUPER_ADMINS"],
        "$mw" : "SUPER_ADMINS"
    }
}
```

**Comment by pgermishuys** [comment]
There was some work done around this, most of it was done in the UI repository.
This (https://github.com/EventStore/EventStore.UI/pull/122) PR along with another for projections will allow a non admin user to login to the UI.
