### ISSUE TITLE
Improve performance of EnqueueSend

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#896]
Code here https://github.com/EventStore/EventStore/blob/8ceb6419f797356e050d00bc57d92c43bf605650/src/EventStore.Transport.Tcp/TcpConnectionLockless.cs#L131. This could likely be the source of many allocations and should be improved as it's part of a critical piece of the tcp code.

**Comment by shaan1337** [comment]
Any specific reason why segments are merged before being sent?
Here, the segments are enqueued one after the other: https://github.com/EventStore/EventStore/blob/release-v4.0.2/src/EventStore.Transport.Tcp/TcpConnection.cs#L120
