### ISSUE TITLE
Catchup subscription on $all failing NRE on server side

### ISSUE THREAD

**Issue by kstrauss** [EventStore/EventStore#900]
when trying to do a comparison against our production instance for distribution of event sizes in #899 , i was unable to read all the events from the All stream and was getting the following error in the ES logs. Opened another issue as it seems to be unrelated (I think), though perhaps it is related to #503 . This however is with 3.5.
```
[PID:06912:009 2016.04.23 15:30:42.617 ERROR TcpDispatcher       ] Error while wrapping message EventStore.Core.Messages.ClientMessage+ReadAllEventsForwardCompleted.
System.NullReferenceException: Object reference not set to an instance of an object.
   at EventStore.Core.Messages.TcpClientMessageDto.EventRecord..ctor(EventRecord eventRecord) in c:\work\EventStore\src\EventStore.Core\Messages\TcpClientMessageDtoExtensions.cs:line 30
   at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.ConvertToResolvedEvents(ResolvedEvent[] events) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 391
   at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.WrapReadAllEventsForwardCompleted(ReadAllEventsForwardCompleted msg) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 361
   at EventStore.Core.Services.Transport.Tcp.TcpDispatcher.WrapMessage(Message message) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\TcpDispatcher.cs:line 64
```

**Comment by gregoryyoung** [comment]
Is this a db you can send to us?

On Sat, Apr 23, 2016 at 6:42 PM, Karl Strauss <notifications@github.com>
wrote:

> when trying to do a comparison against our production instance for
> distribution of event sizes in #899
> <https://github.com/EventStore/EventStore/issues/899> , i was unable to
> read all the events from the All stream and was getting the following error
> in the ES logs. Opened another issue as it seems to be unrelated (I think),
> though perhaps it is related to #503
> <https://github.com/EventStore/EventStore/issues/503> . This however is
> with 3.5.
>
> [PID:06912:009 2016.04.23 15:30:42.617 ERROR TcpDispatcher       ] Error while wrapping message EventStore.Core.Messages.ClientMessage+ReadAllEventsForwardCompleted.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at EventStore.Core.Messages.TcpClientMessageDto.EventRecord..ctor(EventRecord eventRecord) in c:\work\EventStore\src\EventStore.Core\Messages\TcpClientMessageDtoExtensions.cs:line 30
>    at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.ConvertToResolvedEvents(ResolvedEvent[] events) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 391
>    at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.WrapReadAllEventsForwardCompleted(ReadAllEventsForwardCompleted msg) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 361
>    at EventStore.Core.Services.Transport.Tcp.TcpDispatcher.WrapMessage(Message message) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\TcpDispatcher.cs:line 64
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/900>
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
There isnt too much here to fail

https://github.com/EventStore/EventStore/blob/8ceb6419f797356e050d00bc57d92c43bf605650/src/EventStore.Core/Messages/TcpClientMessageDtoExtensions.cs#L30



On Sat, Apr 23, 2016 at 6:49 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> Is this a db you can send to us?
>
> On Sat, Apr 23, 2016 at 6:42 PM, Karl Strauss <notifications@github.com>
> wrote:
>
>> when trying to do a comparison against our production instance for
>> distribution of event sizes in #899
>> <https://github.com/EventStore/EventStore/issues/899> , i was unable to
>> read all the events from the All stream and was getting the following error
>> in the ES logs. Opened another issue as it seems to be unrelated (I think),
>> though perhaps it is related to #503
>> <https://github.com/EventStore/EventStore/issues/503> . This however is
>> with 3.5.
>>
>> [PID:06912:009 2016.04.23 15:30:42.617 ERROR TcpDispatcher       ] Error while wrapping message EventStore.Core.Messages.ClientMessage+ReadAllEventsForwardCompleted.
>> System.NullReferenceException: Object reference not set to an instance of an object.
>>    at EventStore.Core.Messages.TcpClientMessageDto.EventRecord..ctor(EventRecord eventRecord) in c:\work\EventStore\src\EventStore.Core\Messages\TcpClientMessageDtoExtensions.cs:line 30
>>    at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.ConvertToResolvedEvents(ResolvedEvent[] events) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 391
>>    at EventStore.Core.Services.Transport.Tcp.ClientTcpDispatcher.WrapReadAllEventsForwardCompleted(ReadAllEventsForwardCompleted msg) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\ClientTcpDispatcher.cs:line 361
>>    at EventStore.Core.Services.Transport.Tcp.TcpDispatcher.WrapMessage(Message message) in c:\work\EventStore\src\EventStore.Core\Services\Transport\Tcp\TcpDispatcher.cs:line 64
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/issues/900>
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by kstrauss** [comment]
Greg, it is large I have compressed a copy and made it available at a URL that I'll send you to you (greg@geteventstore.com) . Compressed it's ~400mb expanded it's ~3.2 gb. Let me know when you have downladed and I'll it from being available.

**Comment by pgermishuys** [comment]
Are you checking that the `ResolvedEvent.Event` property is not null in the `event appeared` callback before accessing it? If you have links pointing to deleted streams the `Event` property will be null.

**Comment by gregoryyoung** [comment]
@pgermishuys my understanding is that the message is on the server

**Comment by kstrauss** [comment]
@gregoryyoung you are correct, it is server side. Do you need a more complete log ?

**Comment by pgermishuys** [comment]
Would you mind sharing the client code that reproduces the behaviour?

**Comment by kstrauss** [comment]
sure it's a linqpad script so it, i've made a gist of it.
https://gist.github.com/kstrauss/4dffd77133ab54843288f544fece0327

This is not quite our normal pattern but it's something that I use often in linqpad as a utility.

it works talking to one of our servers and fails with a server running the data I put up for you guys. Any questions let me know.

**Comment by pgermishuys** [comment]
Thank you! Will let you know if we have any issues.

**Comment by kstrauss** [comment]
User error. A non-recent version of ES was being used. Sorry for goose chase.

**Comment by pgermishuys** [comment]
No worries, thanks for providing us with the needed information to debug this issue.
