### ISSUE TITLE
Need to be more robust on server stress

### ISSUE THREAD

**Issue by xiangwu007** [EventStore/EventStore#903]
The EventStore application just can't handle the server stress even on a one node system, and reported TCP error, while the network indeed was fine. 

The problem happened when I was installing .net frame 4.6, which generated some load on disk/memory and CPU. 

[PID:02688:018 2016.04.25 13:47:14.128 TRACE QueuedHandlerMRES   ] SLOW QUEUE MSG [MainQueue]: PurgeTimedOutRequests - 374ms. Q: 4/6.
[PID:02688:017 2016.04.25 13:47:17.706 TRACE TcpConnectionManager] Closing connection 'external-normal' [127.0.0.1:59532, L127.0.0.1:1113, {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}] cleanly. Reason: HEARTBEAT TIMEOUT at msgNum 317437
[PID:02688:017 2016.04.25 13:47:18.441 INFO  TcpConnection       ] ES TcpConnection closed [13:47:18.426: N127.0.0.1:59532, L127.0.0.1:1113, {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}]:Received bytes: 6983640, Sent bytes: 6983699
[PID:02688:017 2016.04.25 13:47:18.488 INFO  TcpConnection       ] ES TcpConnection closed [13:47:18.488: N127.0.0.1:59532, L127.0.0.1:1113, {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}]:Send calls: 317438, callbacks: 317438
[PID:02688:017 2016.04.25 13:47:18.488 INFO  TcpConnection       ] ES TcpConnection closed [13:47:18.488: N127.0.0.1:59532, L127.0.0.1:1113, {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}]:Receive calls: 317439, callbacks: 317438
[PID:02688:017 2016.04.25 13:47:18.911 INFO  TcpConnection       ] ES TcpConnection closed [13:47:18.911: N127.0.0.1:59532, L127.0.0.1:1113, {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}]:Close reason: [Success] HEARTBEAT TIMEOUT at msgNum 317437
[PID:02688:017 2016.04.25 13:47:19.630 INFO  TcpConnectionManager] Connection 'external-normal' [127.0.0.1:59532, {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}] closed: Success.
[PID:02688:022 2016.04.25 13:47:19.645 DEBUG PersistentSubscripti] Lost connection from 127.0.0.1:59532
[PID:02688:018 2016.04.25 13:47:21.786 TRACE InMemoryBus         ] SLOW BUS MSG [MainBus]: WriteEvents - 109ms. Handler: RequestManagementService.
[PID:02688:018 2016.04.25 13:47:21.786 TRACE QueuedHandlerMRES   ] SLOW QUEUE MSG [MainQueue]: WriteEvents - 109ms. Q: 0/1.
[PID:02688:018 2016.04.25 13:47:21.958 TRACE QueuedHandlerMRES   ] SLOW QUEUE MSG [MainQueue]: WritePrepares - 125ms. Q: 0/0.
[PID:02688:032 2016.04.25 13:47:23.223 INFO  TcpService          ] External TCP connection accepted: [Normal, 127.0.0.1:63735, L127.0.0.1:1113, {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}].
[PID:02688:015 2016.04.25 13:47:24.161 TRACE QueuedHandlerMRES   ] SLOW QUEUE MSG [StorageWriterQueue]: WritePrepares - 2203ms. Q: 0/0.
[PID:02688:017 2016.04.25 13:47:25.661 TRACE TcpConnectionManager] Closing connection 'external-normal' [127.0.0.1:63735, L127.0.0.1:1113, {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}] cleanly. Reason: HEARTBEAT TIMEOUT at msgNum 1
[PID:02688:017 2016.04.25 13:47:25.661 INFO  TcpConnection       ] ES TcpConnection closed [13:47:25.661: N127.0.0.1:63735, L127.0.0.1:1113, {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}]:Received bytes: 48, Sent bytes: 22
[PID:02688:017 2016.04.25 13:47:25.661 INFO  TcpConnection       ] ES TcpConnection closed [13:47:25.661: N127.0.0.1:63735, L127.0.0.1:1113, {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}]:Send calls: 1, callbacks: 1
[PID:02688:017 2016.04.25 13:47:25.661 INFO  TcpConnection       ] ES TcpConnection closed [13:47:25.661: N127.0.0.1:63735, L127.0.0.1:1113, {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}]:Receive calls: 3, callbacks: 2
[PID:02688:017 2016.04.25 13:47:25.661 INFO  TcpConnection       ] ES TcpConnection closed [13:47:25.661: N127.0.0.1:63735, L127.0.0.1:1113, {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}]:Close reason: [Success] HEARTBEAT TIMEOUT at msgNum 1
[PID:02688:017 2016.04.25 13:47:25.661 INFO  TcpConnectionManager] Connection 'external-normal' [127.0.0.1:63735, {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}] closed: Success.
[PID:02688:006 2016.04.25 13:47:25.661 DEBUG PersistentSubscripti] Lost connection from 127.0.0.1:63735
[PID:02688:032 2016.04.25 13:47:37.474 INFO  ProtobufExtensions  ] Deserialization to EventStore.Core.Messages.TcpClientMessageDto+TransactionCommit failed
ProtoBuf.ProtoException: Invalid field in source data: 0
   at ProtoBuf.ProtoReader.ReadFieldHeader() in c:\Dev\protobuf-net\protobuf-net\ProtoReader.cs:line 642
   at proto_8(Object , ProtoReader )
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate) in c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs:line 679
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs:line 581
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in c:\Dev\protobuf-net\protobuf-net\Serializer.cs:line 77
   at EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.Deserialize[T](ArraySegment`1 data) in c:\projects\eventstore\src\EventStore.Core\Services\Transport\Tcp\ProtobufExtensions.cs:line 58

Detail please check the log.
[2016-04-25.zip](https://github.com/EventStore/EventStore/files/237719/2016-04-25.zip)

**Comment by gregoryyoung** [comment]
What do you have TCP heartbeats set to by default they are fairly low and
machine jitter could easily be causing them

On Wed, Apr 27, 2016 at 3:18 AM, xiangwu007 <notifications@github.com>
wrote:

> The EventStore application just can't handle the server stress even on a
> one node system, and reported TCP error, while the network indeed was fine.
>
> The problem happened when I was installing .net frame 4.6, which generated
> some load on disk/memory and CPU.
>
> [PID:02688:018 2016.04.25 13:47:14.128 TRACE QueuedHandlerMRES ] SLOW
> QUEUE MSG [MainQueue]: PurgeTimedOutRequests - 374ms. Q: 4/6.
> [PID:02688:017 2016.04.25 13:47:17.706 TRACE TcpConnectionManager]
> Closing connection 'external-normal' [127.0.0.1:59532, L127.0.0.1:1113,
> {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}] cleanly. Reason: HEARTBEAT TIMEOUT
> at msgNum 317437
> [PID:02688:017 2016.04.25 13:47:18.441 INFO TcpConnection ] ES
> TcpConnection closed [13:47:18.426: N127.0.0.1:59532, L127.0.0.1:1113,
> {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}]:Received bytes: 6983640, Sent
> bytes: 6983699
> [PID:02688:017 2016.04.25 13:47:18.488 INFO TcpConnection ] ES
> TcpConnection closed [13:47:18.488: N127.0.0.1:59532, L127.0.0.1:1113,
> {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}]:Send calls: 317438, callbacks:
> 317438
> [PID:02688:017 2016.04.25 13:47:18.488 INFO TcpConnection ] ES
> TcpConnection closed [13:47:18.488: N127.0.0.1:59532, L127.0.0.1:1113,
> {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}]:Receive calls: 317439, callbacks:
> 317438
> [PID:02688:017 2016.04.25 13:47:18.911 INFO TcpConnection ] ES
> TcpConnection closed [13:47:18.911: N127.0.0.1:59532, L127.0.0.1:1113,
> {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}]:Close reason: [Success] HEARTBEAT
> TIMEOUT at msgNum 317437
> [PID:02688:017 2016.04.25 13:47:19.630 INFO TcpConnectionManager]
> Connection 'external-normal' [127.0.0.1:59532,
> {6a77a319-6a1c-4fea-80a1-a7a1cab5572f}] closed: Success.
> [PID:02688:022 2016.04.25 13:47:19.645 DEBUG PersistentSubscripti] Lost
> connection from 127.0.0.1:59532
> [PID:02688:018 2016.04.25 13:47:21.786 TRACE InMemoryBus ] SLOW BUS MSG
> [MainBus]: WriteEvents - 109ms. Handler: RequestManagementService.
> [PID:02688:018 2016.04.25 13:47:21.786 TRACE QueuedHandlerMRES ] SLOW
> QUEUE MSG [MainQueue]: WriteEvents - 109ms. Q: 0/1.
> [PID:02688:018 2016.04.25 13:47:21.958 TRACE QueuedHandlerMRES ] SLOW
> QUEUE MSG [MainQueue]: WritePrepares - 125ms. Q: 0/0.
> [PID:02688:032 2016.04.25 13:47:23.223 INFO TcpService ] External TCP
> connection accepted: [Normal, 127.0.0.1:63735, L127.0.0.1:1113,
> {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}].
> [PID:02688:015 2016.04.25 13:47:24.161 TRACE QueuedHandlerMRES ] SLOW
> QUEUE MSG [StorageWriterQueue]: WritePrepares - 2203ms. Q: 0/0.
> [PID:02688:017 2016.04.25 13:47:25.661 TRACE TcpConnectionManager]
> Closing connection 'external-normal' [127.0.0.1:63735, L127.0.0.1:1113,
> {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}] cleanly. Reason: HEARTBEAT TIMEOUT
> at msgNum 1
> [PID:02688:017 2016.04.25 13:47:25.661 INFO TcpConnection ] ES
> TcpConnection closed [13:47:25.661: N127.0.0.1:63735, L127.0.0.1:1113,
> {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}]:Received bytes: 48, Sent bytes: 22
> [PID:02688:017 2016.04.25 13:47:25.661 INFO TcpConnection ] ES
> TcpConnection closed [13:47:25.661: N127.0.0.1:63735, L127.0.0.1:1113,
> {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}]:Send calls: 1, callbacks: 1
> [PID:02688:017 2016.04.25 13:47:25.661 INFO TcpConnection ] ES
> TcpConnection closed [13:47:25.661: N127.0.0.1:63735, L127.0.0.1:1113,
> {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}]:Receive calls: 3, callbacks: 2
> [PID:02688:017 2016.04.25 13:47:25.661 INFO TcpConnection ] ES
> TcpConnection closed [13:47:25.661: N127.0.0.1:63735, L127.0.0.1:1113,
> {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}]:Close reason: [Success] HEARTBEAT
> TIMEOUT at msgNum 1
> [PID:02688:017 2016.04.25 13:47:25.661 INFO TcpConnectionManager]
> Connection 'external-normal' [127.0.0.1:63735,
> {b0554f6f-a257-4fe3-9e10-41e2fdfcc5ea}] closed: Success.
> [PID:02688:006 2016.04.25 13:47:25.661 DEBUG PersistentSubscripti] Lost
> connection from 127.0.0.1:63735
> [PID:02688:032 2016.04.25 13:47:37.474 INFO ProtobufExtensions ]
> Deserialization to
> EventStore.Core.Messages.TcpClientMessageDto+TransactionCommit failed
> ProtoBuf.ProtoException: Invalid field in source data: 0
> at ProtoBuf.ProtoReader.ReadFieldHeader() in
> c:\Dev\protobuf-net\protobuf-net\ProtoReader.cs:line 642
> at proto_8(Object , ProtoReader )
> at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type,
> Object value, Boolean noAutoCreate) in
> c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs:line 679
> at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type
> type, SerializationContext context) in
> c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs:line 581
> at ProtoBuf.Serializer.DeserializeT <http://Stream%20source> in
> c:\Dev\protobuf-net\protobuf-net\Serializer.cs:line 77
> at EventStore.Core.Services.Transport.Tcp.ProtobufExtensions.DeserializeT
> in
> c:\projects\eventstore\src\EventStore.Core\Services\Transport\Tcp\ProtobufExtensions.cs:line
> 58
>
> Detail please check the log.
> 2016-04-25.zip
> <https://github.com/EventStore/EventStore/files/237719/2016-04-25.zip>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/903>
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
I will close this now. The TCP connections were not "lost" they were closed due to a heartbeat timeout. On a machine with heavy load its quite likely that it just didn't get scheduled in time. Raising the heartbeat timeout will make the issue go away.
