### ISSUE TITLE
Windows - EventStore.WindowsManager.exe install - fail when not logged in

### ISSUE THREAD

**Issue by tdeheurles** [EventStore/EventStore#905]
##### I'm trying to automate the installation of an eventstore cluster on a windows virtual machine (Azure-Windows-server-2012 R2 datacenter).

I have a simple script that, after the installation of the .NET4.6.1, run the windows command to install ES as a service (at the end of [this documentation page](http://docs.geteventstore.com/server/3.6.0/cluster-with-manager-nodes/)) :
```
C:\EventStore-HA-v3.0.1\> EventStore.WindowsManager.exe install -InstanceName es-cluster1 -ManagerConfig C:\EventStore-Config\manager.yaml
```

But this result in an error:
```
Cannot start service from the command line or a debugger. 
A Windows Service must first be installed (using installutil.exe) 
and then started with the ServerExplorer, 
Windows Services Administrative tool or the NET START command.
```

I suppose that I shouldn't install the service installer (EventStore.WindowsManager.exe) as a service no ?

**Comment by pgermishuys** [comment]
The issues created on this repository is intended for the OSS version of Event Store and not the commercial manager. If you have any issues regarding the Manager please contact us via freshdesk so that we can appropriately address the issue.

What does your script do exactly and what version of the WindowsManager are you using?

**Comment by tdeheurles** [comment]
Sorry for the mistake. I'll contact you via freshdesk.

Reading again my issue, I was not detailed ... sorry for that.

The script attempt to install the service without manual user login. When the vm start on azure, it runs it automatically and fail on the installation of the service with the error message from the previous post.

But when the script is run manually on the machine (using remote desktop), it works fine and eventstore is installed and running.

**Comment by pgermishuys** [comment]
No worries.
