### ISSUE TITLE
Http permissions registration fails

### ISSUE THREAD

**Issue by klym1** [EventStore/EventStore#906]
I'm trying to run Event store v3.5.0 (win10 x64), it prompts popup for allowing to add permissions:
 
![eventstorepermission](https://cloud.githubusercontent.com/assets/3988917/14915313/93bacdec-0e1a-11e6-8776-add7c099e65e.png)

I'm clicking Yes, but nevertheless it fails:

![image](https://cloud.githubusercontent.com/assets/3988917/14915358/ffc15a4c-0e1a-11e6-9534-384c26e5f5b3.png)

Running in Administrator mode helps, but that's not an option for me. I tried to add permissions manually as described here:

http://docs.geteventstore.com/server/3.4.0/

It's acceptable for me register permissions with administrative mode once, but later I need to run event store without prompts and Administrative mode.

UPD. Earlier I was working with ES 3.0 and as I remember I registered permissions once and later everything worked perfectly.

**Comment by jageall** [comment]
I had a similar issue recently, adding the permissions sometimes fails if there is already a similar url already registered or when the entry gets corrupted for some reason.

I did the following

netsh http show urlacl

and then used

netsh http delete urlacl url=[reservedUrl]

replacing reservedUrl with any urls on port 2113

and then ran EventStore 3.5 again on the same platform and it worked.

**Comment by klym1** [comment]
Hmm, interesting thing, ES is listening two endpoints : `http://127.0.0.1:2113/` and `http://localhost:2113/`. I run `netsh http add urlacl url` for both of them, and now it finally works.

![image](https://cloud.githubusercontent.com/assets/3988917/14916573/2857d834-0e23-11e6-8883-390d2eba2f87.png)

BTW, @jageall thanx for the help!

**Comment by pgermishuys** [comment]
This is because 
- AddInterfacePrefixes is set to `true` (default) 
- Internal/External IP Addresses is set to `127.0.0.1` (default)

If the above is true, Event Store will attempt to add prefixes for `http://localhost:{ext-http-port}`, `http://127.0.0.1:{ext-http-port}`,`http://localhost:{int-http-port}`, `http://127.0.0.1:{int-http-port}`

And since you are running a single node, the internal parts of the above mentioned never cause any issues.

**Comment by pgermishuys** [comment]
Going to close this issue for now unless there is an actual issue here.
