### ISSUE TITLE
Scripts: Use HTTPS when available

### ISSUE THREAD

**Issue by dustinkingen** [EventStore/EventStore#910]
I noticed in the build scripts some requests are sent over http and others https.

After a preliminary analysis I found these scripts are fetching files over plain http:

    scripts/build-js1/build-js1-linux.sh
    scripts/build-js1/build-js1-mac.sh
    scripts/build-windows/build.ps1
    scripts/nuget-clientapi/package-clientapi.ps1

They are the SVN urls for v8, gyp, and protobuf.

I am a Windows user so I verified `build.cmd -target full` and `package-clientapi.ps1` work with https urls.

As far as I can tell changing the urls will have no impact on existing users.

**Comment by gregoryyoung** [comment]
Why are you using these scripts? Normally you should build quick (we package the js1/v8 dependencies as they don't change much).

Cheers,

Greg

**Comment by dustinkingen** [comment]
It is merely my observation.

**Comment by gregoryyoung** [comment]
:+1:

**Comment by dustinkingen** [comment]
Requests sent over non-encrypted http may be vulnerable to man in the middle attacks. To make sure the source code is not vulnerable I think this is a simple change however small the possibility that the attack may happen.
