### ISSUE TITLE
Dump data from memory to disk

### ISSUE THREAD

**Issue by klym1** [EventStore/EventStore#912]
I started my event store instance with `--mem-db=true` key, and it stores all data completely in memory, so when I restart event store instance all data will be gone. 

It's probably not very common use case, but still i would like to know - Is there any way to dump data to filesystem (when ES is running in memory) and get db folder like in default?

**Comment by pgermishuys** [comment]
One way is to start a `non-mem-db` node and connect a client to the `mem-db` node and write the data to the `non-mem-db` node.

**Comment by klym1** [comment]
So there is no built-in command/request/etc.. that could do that?

**Comment by pgermishuys** [comment]
No, not currently

**Comment by klym1** [comment]
ok, thanks for the reply

**Comment by pgermishuys** [comment]
Going to close this issue as this seemed more like a question instead of an actual "issue". Feel free to reopen if this is not the case.
