### ISSUE TITLE
Gossipseed connectionstring

### ISSUE THREAD

**Issue by suddenelfilio** [EventStore/EventStore#917]
Hello

we are trying the "new' connectionstring feature.

`var connection =          EventStoreConnection.Create("GossipSeeds=\"172.30.78.4:1112,172.30.78.4:2112,172.30.78.4:3112\";HeartBeatTimeout=1500");`

this will however throw an exception since there is no Connect To in the connectionstring. I copied the connectionstring sample from the documentation site. (also error on the site missing closing double quotes)

I would expect when using the GossipSeeds no Connect To is required?

**Comment by hayley-jean** [comment]
You are correct that you shouldn't have to set the ConnectTo if you are using GossipSeeds
I'm opening a PR for this, and we'll do a patch of the client with this fix

**Comment by pgermishuys** [comment]
Fixed by #918 as part of the 3.6.2 client that went out today.
