### ISSUE TITLE
cluster crash after 2 days

### ISSUE THREAD

**Issue by suddenelfilio** [EventStore/EventStore#919]
We are running a cluster on commodity servers on 6 servers each with 2 nodes and mostly default settings. After 2 days we keep getting issues with performance counters.

at **first** we had: 

> System.InvalidOperationException: The Counter layout for the Category specified is invalid, a counter of the type:  AverageCount64, AverageTimer32, CounterMultiTimer, CounterMultiTimerInverse, CounterMultiTimer100Ns, CounterMultiTimer100NsInverse, RawFraction, or SampleFraction has to be immediately followed by any of the base counter types: AverageBase, CounterMultiBase, RawBase or SampleBase.
   at System.Diagnostics.CategorySample.GetCounterDefinitionSample(String counter)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at EventStore.Core.Services.Monitoring.Utils.PerfCounterHelper.GetGcStats() in c:\projects\eventstore\src\EventStore.Core\Services\Monitoring\Utils\PerfCounterHelper.cs:line 119
   at EventStore.Core.Services.Monitoring.SystemStatsHelper.GetSystemStats() in c:\projects\eventstore\src\EventStore.Core\Services\Monitoring\SystemStatsHelper.cs:line 66
   at EventStore.Core.Services.Monitoring.MonitoringService.CollectStats() in c:\projects\eventstore\src\EventStore.Core\Services\Monitoring\MonitoringService.cs:line 135

We solved this with lodctr \R

Now we have:

> System.InvalidOperationException: Could not Read Category Index: 5908.
>    at System.Diagnostics.CategorySample..ctor(Byte[] data, CategoryEntry entry, PerformanceCounterLib library)
>    at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category)
>    at System.Diagnostics.PerformanceCounter.NextSample()
>    at EventStore.Core.Services.Monitoring.Utils.PerfCounterHelper.GetGcStats() in c:\projects\eventstore\src\EventStore.Core\Services\Monitoring\Utils\PerfCounterHelper.cs:line 119
>    at EventStore.Core.Services.Monitoring.SystemStatsHelper.GetSystemStats() in c:\projects\eventstore\src\EventStore.Core\Services\Monitoring\SystemStatsHelper.cs:line 66
>    at EventStore.Core.Services.Monitoring.MonitoringService.CollectStats() in 
c:\projects\eventstore\src\EventStore.Core\Services\Monitoring\MonitoringService.cs:line 135 

as these errors are thrown consequently the reaction time of the nodes slows down and eventualy the node dies with message:

> 0904:014 2016.05.13 06:40:36.551 ERROR GossipServiceBase   ] Time difference between us and [172.30.76.18:1112] is too great! UTC now: 2016-05-13 06:40:36.551, peer's time stamp: 2016-05-13 06:39:05.929.
> [PID:10904:296 2016.05.13 06:41:32.676 ERROR QueuedHandlerThreadP] ---!!! VERY SLOW QUEUE MSG [Worker #2]: SendOverHttp - 7500ms. Q: 651/1369.
> [PID:10904:014 2016.05.13 06:41:39.613 ERROR GossipServiceBase   ] Time difference between us and [172.30.78.12:1112] is too great! UTC now: 2016-05-13 06:41:39.613, peer's time stamp: 2016-05-13 06:40:31.294.
> [PID:10904:160 2016.05.13 06:41:40.832 ERROR QueuedHandlerThreadP] ---!!! VERY SLOW QUEUE MSG [Worker #5]: SendOverHttp - 8578ms. Q: 994/1329.
> [PID:10904:014 2016.05.13 06:41:42.769 ERROR GossipServiceBase   ] Time difference between us and [172.30.76.17:2112] is too great! UTC now: 2016-05-13 06:41:42.769, peer's time stamp: 2016-05-13 06:40:40.346.
> [PID:10904:014 2016.05.13 06:41:44.144 ERROR GossipServiceBase   ] Time difference between us and [172.30.78.4:2112] is too great! UTC now: 2016-05-13 06:41:44.144, peer's time stamp: 2016-05-13 06:40:29.914.
> [PID:10904:014 2016.05.13 06:41:44.160 ERROR GossipServiceBase   ] Time difference between us and [172.30.78.4:2112] is too great! UTC now: 2016-05-13 06:41:44.160, peer's time stamp: 2016-05-13 06:40:37.976.
> [PID:10904:014 2016.05.13 06:41:44.363 ERROR GossipServiceBase   ] Time difference between us and [172.30.76.17:2112] is too great! UTC now: 2016-05-13 06:41:44.363, peer's time stamp: 2016-05-13 06:40:27.206.
> [PID:10904:014 2016.05.13 06:41:44.879 ERROR GossipServiceBase   ] Time difference between us and [172.30.78.12:1112] is too great! UTC now: 2016-05-13 06:41:44.879, peer's time stamp: 2016-05-13 06:40:43.420.
> [PID:10904:014 2016.05.13 06:41:45.207 ERROR GossipServiceBase   ] Time difference between us and [172.30.76.17:1112] is too great! UTC now: 2016-05-13 06:41:45.207, peer's time stamp: 2016-05-13 06:40:26.439.
> [PID:10904:014 2016.05.13 06:41:45.394 ERROR GossipServiceBase   ] Time difference between us and [172.30.76.17:3112] is too great! UTC now: 2016-05-13 06:41:45.394, peer's time stamp: 2016-05-13 06:40:35.611.
> [PID:10904:014 2016.05.13 06:41:45.613 ERROR GossipServiceBase   ] Time difference between us and [172.30.78.13:2112] is too great! UTC now: 2016-05-13 06:41:45.613, peer's time stamp: 2016-05-13 06:40:44.861.
> [PID:10904:014 2016.05.13 06:41:48.097 ERROR GossipServiceBase   ] Time difference between us and [172.30.76.17:3112] is too great! UTC now: 2016-05-13 06:41:48.097, peer's time stamp: 2016-05-13 06:40:31.549.
> [PID:10904:014 2016.05.13 06:41:48.754 ERROR GossipServiceBase   ] Time difference between us and [172.30.76.17:2112] is too great! UTC now: 2016-05-13 06:41:48.754, peer's time stamp: 2016-05-13 06:40:43.377.
> [PID:10904:014 2016.05.13 06:41:51.097 ERROR GossipServiceBase   ] Time difference between us and [172.30.78.13:1112] is too great! UTC now: 2016-05-13 06:41:51.097, peer's time stamp: 2016-05-13 06:40:47.283.
> [PID:10904:014 2016.05.13 06:42:08.738 ERROR GossipServiceBase   ] Time difference between us and [172.30.78.4:1112] is too great! UTC now: 2016-05-13 06:42:08.738, peer's time stamp: 2016-05-13 06:40:39.335.
> [PID:10904:014 2016.05.13 06:42:08.925 ERROR GossipServiceBase   ] Time difference between us and [172.30.78.13:2112] is too great! UTC now: 2016-05-13 06:42:08.925, peer's time stamp: 2016-05-13 06:41:08.251.
> [PID:10904:276 2016.05.13 06:42:17.628 ERROR MonitoringService   ] Error while collecting stats

We are currently at the point to abandon eventstore as we don't have a lot of time to concern us about these issues, but since I really like this product I want to give it another try.

any advise?

**Comment by gregoryyoung** [comment]
What version are you running?

And the errors you are getting about statistics are just calls to windows perf counters (windows is giving the error to ES, this is why a windows command fixes it). ES has read only access to the perf counter db. And did you run lodctr \R or  lodctr /R the last is what fixes it not the first. We see windows nodes who never give errors and we see images where lodctr needs to be run regularly. Even on the same machine etc we have seen people reinstall from a different windows image (assuming using images) and the issue completely go away. We have also seen on these same nodes other tools using the same dbs have identical issues.

The second bit is related to very slow http calls (blocking) which doesn't happen often but has already been resolved in the current version. Were you seeing this in 3.6.0 or higher?

**Comment by suddenelfilio** [comment]
This is in version 3.6.0

**Comment by pgermishuys** [comment]
@suddenelfilio would you be able to share logs with us?
If you dont want to share them on here you can send them to pieter at geteventstore.

**Comment by suddenelfilio** [comment]
sure there is no data in the store yet as we were checking to see if the cluster would run event without activity. I'll bundle them up and send them over

**Comment by pgermishuys** [comment]
Thank you @suddenelfilio much appreciated and hopefully we can help you resolve the issues your are experiencing.

**Comment by suddenelfilio** [comment]
okay small question which logs do you need? as only 1 node with 8 days of logs is 5GB x 12 nodes is a bit too much for me to carry

**Comment by pgermishuys** [comment]
Ok, so the important bits for me would be
1. The startup bits for each node.
e.g.
```
ES VERSION:               0.0.0.0 (release-v3.7.0/a107044d88f91e22ea01961810b304a7c24b997b, Tue, 3 May 2016 10:10:05 +0200)
OS:                       MacOS (Unix 15.4.0.0)
RUNTIME:                  3.12.1 (tarball Sun Dec 27 16:42:40 SAST 2015) (64-bit)
GC:                       2 GENERATIONS
LOGS:                     /Users/pieterg/source/EventStore/bin/clusternode/logs
MODIFIED OPTIONS:
	MEM DB:                   True (Command Line)
DEFAULT OPTIONS:
	HELP:                     False (<DEFAULT>)
	VERSION:                  False (<DEFAULT>)
```
For the above I would like to complete options output.
2. The bits from the logs for the period and hour before up until the node exhibits the time difference error.

Is the time difference issue reproducible?

Also, once we have the logs, would you mind if we ask for more information once we have analysed the logs and have possibly more questions?

Thanks for your assistance.

**Comment by suddenelfilio** [comment]
Okay this will take some time, but let me see what I can do here. I'll get back to you

**Comment by pgermishuys** [comment]
No problem, and thank you for the assistance

**Comment by gregoryyoung** [comment]
Why is one node 5GB of logs? This sounds like some misconfiguration or?

**Comment by suddenelfilio** [comment]
Yes we had to turn of TRACE level to prevent the disk from filling. Anyways the entire log set is at your disposal via Pieter. I would love to here where I've dropped the ball so I can get it fixed and keep eventstore in the stack for our project

**Comment by gregoryyoung** [comment]
This config is a bit weird, @pgermishuys will be following up with some further questions as I have a talk to run to. What were you trying to achieve with this configuration?

**Comment by suddenelfilio** [comment]
Well without any prior knowledge and using the documentation online I wanted to setup a cluster for an audit feature we are building into our project. Idea was to send business actions as events to a certain stream and then let projections split those into streams aggregating per user or per entity that is being manipulated in the event. 

The reason for the current setup is because I looked at the appliances that are being sold I was hoping spreading them over multiple "lighter" machines would have a similar effect.

**Comment by gregoryyoung** [comment]
So the clustering here is not a sharding cluster but a high availability cluster. Keeping 12 copies of data is unusual.

Are your nodes time synchronized with ntp etc?

**Comment by suddenelfilio** [comment]
Yes I was under the impression each node needs it data stored locally how else would it be resilient when the node with data goes down?

I did not do anything in particular for synchronization with ntp? would this apply: http://www.sysadminlab.net/windows/configuring-ntp-on-windows-server-2012

**Comment by pgermishuys** [comment]
As Greg mentioned, this configuration is unusual, we generally expect 3 or 5 node clusters (odd number as explained [here](http://docs.geteventstore.com/server/3.6.0/cluster-without-manager-nodes/)).
Keeping this in mind, for each write, a majority of nodes needs to confirm the write. Introducing more nodes, increases the number of nodes required to confirm a write thus meaning that the more nodes you add, the slower writing will become.

Apart from the writing, there's also gossiping on which you can find more information in the *cluster gossip* section [here](http://docs.geteventstore.com/server/3.6.0/cluster-with-manager-nodes/).

With gossiping there is also an allowed time shift between the nodes which is by default set to 1 minute. i.e. we cannot allow out of date information about the cluster.

**Comment by pgermishuys** [comment]
This appears to have been a non-issue. @suddenelfilio please reopen if you feel we haven't solved this particular one.
