### ISSUE TITLE
ES Client stops reconnecting after 10 retries

### ISSUE THREAD

**Issue by manlpn** [EventStore/EventStore#920]
It seems that connection settings are overriden by cluster settings. After network loss, client tries to discover cluster 10 times (default), then it permanently closes connection. Of course, we can set SetMaxDiscoverAttempts(Int32.MaxValue), but what if we want the client to keep reconnecting to infinity?... SetMaxDiscoverAttempts(-1) rises an exception:

> "maxDiscoverAttempts value is out of range: -1. Allowed range: **[-1, infinity]**."
 

Connection settings:
<pre>
<code>
     EventStoreConnection.Create(
                ConnectionSettings.Create()
                                  .KeepReconnecting()
                                  .SetHeartbeatTimeout(TimeSpan.FromSeconds(7))
                                  .SetOperationTimeoutTo(TimeSpan.FromSeconds(30))
                                  .UseCustomLogger(new EventStoreLogger(LogManager.GetLogger("EsService")))
                                  .SetDefaultUserCredentials(new UserCredentials(esUsername, esPassword)),
                ClusterSettings.Create()
                                .DiscoverClusterViaDns()
                                    .SetClusterDns(esClusterDns)
                                    .SetClusterGossipPort(esPort));
</code>
</pre>

**Comment by gregoryyoung** [comment]
int.maxvalue should be high enough for most systems :)
