### ISSUE TITLE
Event Store crashes on projection using Date.toLocaleString (Windows only)

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#926]
Original source of the issue https://groups.google.com/forum/#!topic/event-store/SZ31hiaQe30

> Using Date.toLocaleString in a query makes my EventStore crash. I'm running it from console in a Windows 8.1 and I've tried with versions 3.6.1 and 3.6.2. I don't think it has any impact but I've tried running the query from both Chrome and Internet Explorer.
> 
> The moment I run the query, EventStore crashes showing the usual Windows dialog stating that my "EventStore.ClusterNode.exe has stopped working" and immediately exiting in the console without showing any error message there. I've found no information regarding the crash in neither -cluster-node.log nor -cluster-node-err.log.
> 
> Others Date methods such as toDateString (which is what I ended up using) work without problem.

```
[
  {
    "eventId": "fbf4a1a1-b4a3-4dfe-a01f-ec52c34e16e4",
    "eventType": "testEvent",
    "data": {
      "Timestamp": "2016-05-24T09:38:27.8995302+02:00"
    }
  }
]
```

```
curl -i -d @testEvent.txt "http://127.0.0.1:2113/streams/newstream" -H "Content-Type:application/vnd.eventstore.events+json"
```

```
fromStream('newstream')
    .when({ $any: function(s,e) {

        var date = new Date(e.body['Timestamp']).toLocaleString();
        return date;
}}) 
```

**Comment by riccardone** [comment]
My guess is that 'toLocaleString' is a not implemented feature in v8 js engine.
https://bugs.chromium.org/p/v8/issues/detail?id=1034 
http://v8-dev.narkive.com/UWhuWhhz/issue-1034-in-v8-tolocalestring-does-not-support-on-chrome-browser

I wrote a unit test that reproduce the issue. 
Hope this help.

**Comment by pgermishuys** [comment]
@riccardone you are correct, we would need to upgrade v8 to resolve this issue correctly.
