### ISSUE TITLE
Client recieves 'ReadStreamEventsCompleted' message with empty event list when running es cluster

### ISSUE THREAD

**Issue by msemys** [EventStore/EventStore#940]
I'm running a test that writes N events (where N is random number greater than 100 and less than 500)  to stream and then reads and asserts them. This write/read action is repeated 10000 times (in for loop).

When running EventStore v3.6.3 cluster, sometimes (with 10000 iterations - always) the 'ReadStreamEventsBackward' operation returns 'ReadStreamEventsCompleted' message with no events. The received message has status, nextEventNumber, lastEventNumber, isEndOfStream flag set, but events field is empty list.

**machine details**:
- ubuntu 14.04 x64
- ram 8gb
- cpu i7-4770K CPU @ 3.50GHz x 8
- ssd (samsung 840 pro)

**es cluster nodes started with these commands (same machine)**:
````sh
./run-node.sh --mem-db --log log/node1 --int-ip 127.0.0.1 --ext-ip 127.0.0.1 --int-tcp-port=1111 --ext-tcp-port=1112 --int-http-port=1113 --ext-http-port=1114 --cluster-size=3 --discover-via-dns=false --gossip-seed=127.0.0.1:2113,127.0.0.1:3113

./run-node.sh --mem-db --log log/node2 --int-ip 127.0.0.1 --ext-ip 127.0.0.1 --int-tcp-port=2111 --ext-tcp-port=2112 --int-http-port=2113 --ext-http-port=2114 --cluster-size=3 --discover-via-dns=false --gossip-seed=127.0.0.1:1113,127.0.0.1:3113

./run-node.sh --mem-db --log log/node3 --int-ip 127.0.0.1 --ext-ip 127.0.0.1 --int-tcp-port=3111 --ext-tcp-port=3112 --int-http-port=3113 --ext-http-port=3114 --cluster-size=3 --discover-via-dns=false --gossip-seed=127.0.0.1:1113,127.0.0.1:2113
```

**es logs**:
- [node1.txt](https://github.com/EventStore/EventStore/files/304779/node1.txt)
- [node2.txt](https://github.com/EventStore/EventStore/files/304781/node2.txt)
- [node3.txt](https://github.com/EventStore/EventStore/files/304785/node3.txt)


**notes**:
- issue occurs with es cluster only (with single node ok)
- it is reproducible with java8/netty (esjc 1.4.0) and scala/akka (es.jvm 2.1.2) clients
- test passed when I add delay (thread.sleep 50ms) between write and read operations in test


**reproduce with esjc 1.4.0 client**
```java
@Test
public void readsWrittenEvents() {
    final EventStore eventstore = EventStoreBuilder.newBuilder()
        .clusterNodeDiscoveryFromGossipSeeds(asList(
            new InetSocketAddress("127.0.0.1", 1113),
            new InetSocketAddress("127.0.0.1", 2113),
            new InetSocketAddress("127.0.0.1", 3113)))
        .clusterNodeGossipTimeout(Duration.ofSeconds(1))
        .clusterNodeUnlimitedDiscoverAttempts()
        .userCredentials("admin", "changeit")
        .operationTimeout(Duration.ofSeconds(5))
        .heartbeatInterval(Duration.ofSeconds(2))
        .heartbeatTimeout(Duration.ofSeconds(10))
        .maxClientReconnections(2)
        .requireMasterEnabled()
        .build();

    final String stream = "reads-written-events-" + UUID.randomUUID().toString();

    range(0, 10000).forEach(i -> {
        final int count = ThreadLocalRandom.current().nextInt(100, 500);

        List<EventData> events = range(0, count).mapToObj(n -> EventData.newBuilder().type("test").build()).collect(toList());

        WriteResult writeResult = eventstore.appendToStream(stream, ExpectedVersion.any(), events).join();

        StreamEventsSlice readResult = eventstore.readStreamEventsBackward(stream, writeResult.nextExpectedVersion, count, false).join();

        assertEquals(SliceReadStatus.Success, readResult.status);
        assertEquals(writeResult.nextExpectedVersion, readResult.fromEventNumber);
        assertEquals(count, readResult.events.size());

        range(0, count).forEach(n ->
            assertEquals(events.get(n).eventId, readResult.events.get(count - n - 1).originalEvent().eventId)
        );
    });
}
```

**reproduce with es.jvm 2.1.2 client**
```java
@Test
public void readsWrittenEvents() {
    final EsConnection connection = EsConnectionFactory.create(ActorSystem.create(), new SettingsBuilder()
        .cluster(new ClusterSettingsBuilder()
            .gossipSeeds(asScalaBuffer(asList(
                new InetSocketAddress("127.0.0.1", 1113),
                new InetSocketAddress("127.0.0.1", 2113),
                new InetSocketAddress("127.0.0.1", 3113))))
            .gossipTimeout(1, SECONDS)
            .build())
        .defaultCredentials("admin", "changeit")
        .operationTimeout(5, SECONDS)
        .heartbeatInterval(2, SECONDS)
        .heartbeatTimeout(10, SECONDS)
        .maxReconnections(2)
        .requireMaster(true)
        .build());

    final String stream = "reads-written-events-" + UUID.randomUUID().toString();

    range(0, 10000).forEach(i -> {
        final int count = ThreadLocalRandom.current().nextInt(100, 500);

        List<EventData> events = range(0, count).mapToObj(n -> new EventDataBuilder("test").eventId(UUID.randomUUID()).build()).collect(toList());

        WriteResult writeResult = await(connection.writeEvents(stream, ExpectedVersion.Any$.MODULE$, events, null));

        ReadStreamEventsCompleted readResult = await(connection.readStreamEventsBackward(stream, new EventNumber.Exact(writeResult.nextExpectedVersion().value()), count, false, null));

        assertEquals(count, readResult.events().size());

        range(0, count).forEach(n ->
            assertEquals(events.get(n).eventId(), readResult.eventsJava().get(count - n - 1).data().eventId())
        );
    });
}

private static <T> T await(Future<T> future) {
    try {
        return Await.result(future, Duration.apply(15, SECONDS));
    } catch (Exception e) {
        throw new RuntimeException(e);
    }
}
```

tests fails when asserting read events count:

```
>>> assertEquals(count, readResult.events.size());

java.lang.AssertionError: 
Expected :177
Actual   :0
```

**Comment by pgermishuys** [comment]
The results you are seeing is likely due to the node that you are connected to (Master) has not written the events, but the other 2 nodes have. You are then reading from master expecting it to have written the data. I guess what you will see in the nextEventNumber, lastEventNumber, isEndOfStream is the results of the write before last. Is this correct?

In a 3 node cluster, a quorum of nodes have to confirm a write before the write is deemed to have been successful. This doesn't require the **master** and a **slave** to confirm the write, just 2 nodes.

You can confirm the explanation by reading from the slaves at the same time and you will see that they will yield the results you expect.

What are you trying to achieve?

**Comment by msemys** [comment]
I'm writing events to stream and expecting that with next read operation I will be able to read them from stream.

I've added some debug info in client side (esjc) to see, what I'm recieving from server (details of 'ReadStreamEventsCompleted' message):
```
...
...
...
ReadStreamEventsCompleted: event count=136, nextEventNumber=256731, lastEventNumber=256867, isEndOfStream=false
ReadStreamEventsCompleted: event count=264, nextEventNumber=256867, lastEventNumber=257131, isEndOfStream=false
ReadStreamEventsCompleted: event count=148, nextEventNumber=257131, lastEventNumber=257279, isEndOfStream=false
ReadStreamEventsCompleted: event count=255, nextEventNumber=257279, lastEventNumber=257534, isEndOfStream=false
ReadStreamEventsCompleted: event count=0, nextEventNumber=257534, lastEventNumber=257534, isEndOfStream=false
```

**Comment by hayley-jean** [comment]
The only guarantee that we offer is that a quorum of nodes will have the write. But we can't guarantee that the node you are reading from will have that write at the point of you reading it.

You won't have this problem with a subscription because a subscription only gets the data when it's available.

**Comment by msemys** [comment]
When I started es cluster nodes with "--commit-count 3", it seems works as I expected.

**Comment by pgermishuys** [comment]
With that setting, if one of your nodes goes down, you will not get a write confirmation.

**Comment by pgermishuys** [comment]
@msemys going to close this issue for now. If you feel that the issue needs any further work, please feel free to reopen.

**Comment by gregoryyoung** [comment]
@msemys <https://github.com/msemys> commit count 3 defeats the purpose of
having a cluster :) you will have less availability than a single node. By
default we ack with a majority of nodes. This gives consistency but its
always possible that you are reading off a slave node that doesn't have the
write yet (since we only need a majority).

On Thu, Jun 9, 2016 at 3:40 PM, Pieter Germishuys <notifications@github.com>
wrote:

> @msemys <https://github.com/msemys> going to close this issue for now. If
> you feel that the issue needs any further work, please feel free to reopen.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EventStore/EventStore/issues/940#issuecomment-224882350>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXRWh5LaAbtdu5EXdenLZD0XWNouU8Yks5qKAmhgaJpZM4Iw8PP>
> .
>



-- 
Studying for the Turing test

**Comment by msemys** [comment]
I was using stream read operation (ReadStreamEventsForwardOperation) to load aggregate. But now it looks like it is not the right way, because there is no guarantee that it will read the latest events in stream.

**Comment by gregoryyoung** [comment]
So two things here:

1) you can write with expected version set. In case you were missing one you will get a concurrency error.
2) you can read from the master. The master always has the latest (not sure how this is handled in the java client)

**Comment by msemys** [comment]
2) to read from the master, it is to set 'RequireMaster=true' in client settings (https://github.com/EventStore/EventStore/blob/release-v3.7.0/src/EventStore.ClientAPI/ConnectionSettings.cs#L58), isn't it?

**Comment by gregoryyoung** [comment]
From looking this will work almost always in production but in a dev
environment with all on one node it may cause an occasional misread
(timing) stick to #1.

On Fri, Jun 10, 2016 at 12:11 AM, Mindaugas Šėmys <notifications@github.com>
wrote:

> 2) to read from the master, it is to set 'RequireMaster=true' in client
> settings (
> https://github.com/EventStore/EventStore/blob/release-v3.7.0/src/EventStore.ClientAPI/ConnectionSettings.cs#L58),
> isn't it?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/EventStore/EventStore/issues/940#issuecomment-225028115>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXRWq07TvkdpoFpew3BGmhOdRPpg797ks5qKIGYgaJpZM4Iw8PP>
> .
>



-- 
Studying for the Turing test

**Comment by msemys** [comment]
I've updated test that uses expected version for write operation (require master is also set).

```java
@Test
public void readsWrittenEvents() {
    final EventStore eventstore = EventStoreBuilder.newBuilder()
        .clusterNodeDiscoveryFromGossipSeeds(asList(
            new InetSocketAddress("127.0.0.1", 1113),
            new InetSocketAddress("127.0.0.1", 2113),
            new InetSocketAddress("127.0.0.1", 3113)))
        .clusterNodeGossipTimeout(Duration.ofSeconds(1))
        .clusterNodeUnlimitedDiscoverAttempts()
        .userCredentials("admin", "changeit")
        .operationTimeout(Duration.ofSeconds(5))
        .heartbeatInterval(Duration.ofSeconds(2))
        .heartbeatTimeout(Duration.ofSeconds(10))
        .maxClientReconnections(2)
        .requireMasterEnabled()
        .build();

    final String stream = "reads-written-events-" + UUID.randomUUID().toString();

    ExpectedVersion expectedVersion = ExpectedVersion.noStream();

    for (int i = 0; i < 10000; i++) {
        final int count = ThreadLocalRandom.current().nextInt(100, 500);

        List<EventData> events = range(0, count).mapToObj(n -> EventData.newBuilder().type("test").build()).collect(toList());

        WriteResult writeResult = eventstore.appendToStream(stream, expectedVersion, events).join();

        StreamEventsSlice readResult = eventstore.readStreamEventsForward(stream, writeResult.nextExpectedVersion - count + 1, count, false).join();

        assertEquals(SliceReadStatus.Success, readResult.status);
        assertEquals(count, readResult.events.size());

        range(0, count).forEach(n ->
            assertEquals(events.get(n).eventId, readResult.events.get(n).originalEvent().eventId)
        );

        expectedVersion = ExpectedVersion.of(writeResult.nextExpectedVersion);
    }
}
```

writes succeeds (no WrongExpectedVersion in WriteEventsCompleted message), but test sometimes fail when asserting read event count (the same as it was when using ```ExpectedVersion.any()```)

I think that this should be reproducible with .net client as well.

**Comment by hayley-jean** [comment]
What you are seeing here is a symptom of running all three nodes on the same machine, and is not something you will see in production.

In a real world scenario where the nodes are communicating over a network, Master will always acknowledge writes before either of the slaves, and then a slave will acknowledge a write. Therefore Master should always have the latest events.

In your scenario, there is no latency between the nodes, so the slaves are able to acknowledge a write before Master, meaning that Master will not always have the latest events. This is why your assertion fails.

Again, this is not something that would happen in a real world scenario.

**Comment by msemys** [comment]
Thanks for explanation, now it's clear why this is happening... It's just not the behavior that I was expected of using es cluster with 'RequireMaster=true'.

I have this situation once per week in production, where all tree es nodes are in separate machines (centos, es upgraded to the latest v3.3.1 -> v3.6.3).

**Comment by gregoryyoung** [comment]
@msemys it would be extremely unusual to see this on separated machines, you would need a network hop and disk write to out-perform a local read. How are you measuring this? Its possible something gets context switched but this would seem to be highly unlikely.

As for how to work around it. Use expected version with what you read when you do your write. This also will handle the case of a second writer writing something you didn't read when you read.

Cheers,

Greg

**Comment by msemys** [comment]
Just wanted to note, that I'm able to work around aggregate loading logic by adding delay and retry read operation.

The previous code that I was used to load aggregate:
```java
...

StreamEventsSlice slice;
int fromPosition = XXXXX;
        
do {
    slice = eventstore.readStreamEventsForward(stream, fromPosition, 100, false).join();

    if (slice.status != SliceReadStatus.Success) {
        break;
    }

    apply(slice.events);

    fromPosition = slice.nextEventNumber;
} while (!slice.isEndOfStream);

...
```

I've replaced it with:
```java
...

StreamEventsSlice slice;
int fromPosition = XXXXX;

final int batchSize = 100;
boolean retried = false;
boolean done = false;

do {
    slice = eventstore.readStreamEventsForward(stream, fromPosition, batchSize, false).join();
    
    if (slice.status != SliceReadStatus.Success) {
        break;
    }
    
    apply(slice.events);

    fromPosition = slice.nextEventNumber;

    if (slice.isEndOfStream && (slice.events.size() == batchSize || slice.events.isEmpty()) && !retried) {
        Thread.sleep(100);
        retried = true;
        continue;
    } else {
        done = slice.isEndOfStream;
    }
} while (!done);

...
```

it's not perfect, but it's better then having aggregate without the latest events.

**Comment by gregoryyoung** [comment]
Much easier way:

Read without it. But when you write set expected version based on the last event you read. This will prevent you from having a bad write (and no delay)

**Comment by msemys** [comment]
I've double-checked that with test:
```java
ExpectedVersion expectedVersion = ExpectedVersion.noStream();

for (int i = 0; i < 10000; i++) {
    final int count = ThreadLocalRandom.current().nextInt(100, 500);

    List<EventData> testEvents = range(0, count).mapToObj(n -> EventData.newBuilder().type("test").build()).collect(toList());

    WriteResult writeResult = eventstore.appendToStream(stream, expectedVersion, testEvents).join();

    StreamEventsSlice slice;
    List<ResolvedEvent> events = new ArrayList<>();

    int fromPosition = writeResult.nextExpectedVersion - count + 1;

    do {
        slice = eventstore.readStreamEventsForward(stream, fromPosition, 100, false).join();

        events.addAll(slice.events);

        fromPosition = slice.nextEventNumber;
    } while (!slice.isEndOfStream);

    assertEquals(SliceReadStatus.Success, slice.status);
    assertEquals(count, events.size());

    range(0, count).forEach(n -> assertEquals(testEvents.get(n).eventId, events.get(n).originalEvent().eventId));

    expectedVersion = ExpectedVersion.of(slice.lastEventNumber);
}
```

it fails sometimes when asserting count (we already discused why this is happening)

**Comment by gregoryyoung** [comment]
You seem to misunderstand what I am saying.

When you read events from a stream to build up an object you are doing it so you can issue a write correct? Even in if miss an event (though I am really curious how you are getting this in the first place but more on that later) if you set the expected version to the last thing when you *write* if by chance some was missing (also protects against another thread writing concurrently) you will get a version conflict and can retry. Does this make sense?

In terms of how this occurs, are these nodes (real ones) running on say single core vms? I can't come up with any reason why a thread would get parked for so long doing a local in memory operation.

**Comment by msemys** [comment]
I've workarounded without delay in simpler way:
```java
...
StreamEventsSlice slice;
int fromPosition = XXXXX;

boolean done = false;

do {
    slice = eventstore.readStreamEventsForward(stream, fromPosition, 100, false).join();

    if (slice.status != SliceReadStatus.Success) {
        break;
    }

    apply(slice.events);

    fromPosition = slice.nextEventNumber;

    if (slice.isEndOfStream && slice.lastEventNumber != writeResult.nextExpectedVersion) {
        logger.warn("Retrying read operation from stream '{}' #{}", stream, fromPosition);
    } else {
        done = slice.isEndOfStream;
    }
} while (!done);
...
```

about nodes in production - nodes are running with 2 core vms
