### ISSUE TITLE
add a Savepoint mechanism

### ISSUE THREAD

**Issue by riccardone** [EventStore/EventStore#941]
Add a savepoint feature to the EventStore client api connection to reduce the boilerplate code code that a Catch Up subscription's client must write to maintain the last position.
e.g.:

`Task<WriteResult> SavepointAsync(string identifier, Position position);`

and other behaviors like reset or restart

**Comment by gregoryyoung** [comment]
I would tend to prefer this in a library on top. This sounds like the kind of thing one should be very opinionated about and someone else may be very opinionated in another direction.

**Comment by pgermishuys** [comment]
I agree with @gregoryyoung

**Comment by urbanhusky** [comment]
I also agree with @gregoryyoung. 
In a CQRS/ES system you also should store your position in your read model, otherwise you might go out of sync or face the challenges of a distributed commit or duplicated events.

**Comment by ahjohannessen** [comment]
Is there a simple way to store a single pointer with existing API? I suppose a single stream with a max count set to one or similar?

**Comment by gregoryyoung** [comment]
@ahjohannessen yes.

**Comment by pgermishuys** [comment]
I am going to close this one for now unless there is any motivation to build this into the client API.
