### ISSUE TITLE
Race condition when subscribing with PersistentSubscription

### ISSUE THREAD

**Issue by mpielikis** [EventStore/EventStore#942]
Sometimes when subscribing to a stream with PersistentSubscription I get NullReferenceException in eventAppeard handler when "acking" event. It feels like there is some race condition between [subscription started](https://github.com/EventStore/EventStore/blob/release-v3.7.0/src/EventStore.ClientAPI/EventStorePersistentSubscriptionBase.cs#L72) and [EventAppeared](https://github.com/EventStore/EventStore/blob/release-v3.7.0/src/EventStore.ClientAPI/ClientOperations/VolatileSubscriptionOperation.cs#L38). 

I am using the latest 3.7.0 code.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EventStore.ClientAPI.EventStorePersistentSubscriptionBase.Acknowledge(ResolvedEvent event) in i:\Dev\GitHub\EventStore\src\EventStore.ClientAPI\EventStorePersistentSubscriptionBase.cs:line 92
```

```
Action<EventStorePersistentSubscriptionBase, ResolvedEvent> eventAppeared = (s, e) =>
                {
                    try
                    {
                        handler(e);

                        try
                        {
                            s.Acknowledge(e); // throws NullReferenceException
                        }
                        catch (Exception exc)
                        {
                            log.Error(exc);
                            Environment.Exit(100);
                        }
                    }
                    catch (Exception exc)
                    {
                        s.Fail(e, PersistentSubscriptionNakEventAction.Park, exc.Message);
                    }
                };


connection.ConnectToPersistentSubscription(
                            stream: streamName,
                            groupName: groupName,
                            eventAppeared: eventAppeared,
                            subscriptionDropped: subscriptionDropped,
                            userCredentials: credentials);
```

**Comment by mpielikis** [comment]
Just wanted to add that this situation is quite reproducible when system is on heavy load.

**Comment by hayley-jean** [comment]
Would you be able to provide us with a full reproduction of the issue?
And what do you consider "heavy load"?

**Comment by mpielikis** [comment]
I am trying to make reproduction sample, but no luck for now, maybe it's too naive. Basically what I mean by heavy load, is a full CPU usage, also the client app uses a lot of async tcp communication, maybe that causes some thread pool exhaustion for some period in time. I will try to investigate more here, maybe the EventStore client log will help.

**Comment by hayley-jean** [comment]
I have also not been able to reproduce this issue on my side

However, I notice that your exception is being thrown from inside `EventStore.ClientAPI.EventStorePersistentSubscriptionBase.Acknowledge` which looks to me like it is not your subscription that is null, but something in the [Acknowledge method](https://github.com/EventStore/EventStore/blob/release-v3.7.0/src/EventStore.ClientAPI/EventStorePersistentSubscriptionBase.cs#L92). There's not much there, so it's most likely the OriginalEvent that is null.

Something that can help us determine whether this is happening because of the subscription or the event is when the exception is thrown.
Does it only happen directly after connecting to the persistent subscription, so on the first event, or can you leave it running for a while before it errors?

If the Subscription Start is causing this issue, I would expect the exception to only be thrown when you are first connecting to the subscription. Otherwise, this could be being caused by an event

**Comment by gregoryyoung** [comment]
There could be a race condition with:

https://github.com/EventStore/EventStore/blob/release-v3.7.0/src/EventStore.ClientAPI/EventStorePersistentSubscriptionBase.cs#L72

If this is happening on the start of the subscription.

On Tue, Jun 14, 2016 at 10:15 AM, Hayley Campbell <notifications@github.com>
wrote:

> I have also not been able to reproduce this issue on my side
>
> However, I notice that your exception is being thrown from inside
> EventStore.ClientAPI.EventStorePersistentSubscriptionBase.Acknowledge
> which looks to me like it is not your subscription that is null, but
> something in the Acknowledge method
> <https://github.com/EventStore/EventStore/blob/release-v3.7.0/src/EventStore.ClientAPI/EventStorePersistentSubscriptionBase.cs#L92>.
> There's not much there, so it's most likely the OriginalEvent that is null.
>
> Something that can help us determine whether this is happening because of
> the subscription or the event is when the exception is thrown.
> Does it only happen directly after connecting to the persistent
> subscription, so on the first event, or can you leave it running for a
> while before it errors?
>
> If the Subscription Start is causing this issue, I would expect the
> exception to only be thrown when you are first connecting to the
> subscription. Otherwise, this could be being caused by an event
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EventStore/EventStore/issues/942#issuecomment-225798462>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXRWsw5rO91leDeYpRDnpO9ahmB_IyMks5qLlUFgaJpZM4IyCqv>
> .
>



-- 
Studying for the Turing test

**Comment by hayley-jean** [comment]
Just following up on this: @mpielikis could you tell us when the exception is thrown so we can narrow down the possible causes?

Is the exception thrown only on the start of the subscription, or while processing the events?

**Comment by mpielikis** [comment]
sorry for the late reply. The error appears on the start of subscription. It happens at client side in production with three virtual machines connected in a cluster, so it is hard to debug there, now we are getting closer to reproduce this problem locally.
