### ISSUE TITLE
Slaves hang when posting invalid event

### ISSUE THREAD

**Issue by fpighi** [EventStore/EventStore#947]
Hi,
I was trying to post an event with curl and I've noticed it was hanging and eventually timing out.
Upon further investigation I noticed that my event had an invalid json due to unclosed curly braces.
It's failing straight away when I hit the master with 400, but when I'm hitting one of the slaves the connection is left open and the log on the slave is saying the following:

```
[PID:03109:014 2016.06.14 16:04:34.637 ERROR HttpEntityManager   ] Failed to set up forwarded response parameters for 'http://10.192.14.24:2113/streams/warehouse'.
System.NullReferenceException: Object reference not set to an instance of an object
  at EventStore.Transport.Http.EntityManagement.HttpEntityManager.ForwardReply (System.Net.Http.HttpResponseMessage response, System.Action`1 onError) [0x00000] in <filename unknown>:0
```

**Curl invocation**
```
curl -i -d@event.json "http://eventstorehost:2113/streams/warehouse" -H "Content-Type: application/vnd.eventstore.events+json"
```

**event.json**
```
[
  {
    "eventId": "143e68a6-bc55-47d0-9767-7032f8c6c666",
    "eventType": "test_event",
    "data": {
        "foo": "bar"
    }
]
```

**Comment by hayley-jean** [comment]
A fix for this issue is in PR https://github.com/EventStore/EventStore/pull/951

This fix will be merged into 3.7.0 but we can get a 3.6.4 patch out later today.
