### ISSUE TITLE
Unable to limit nr of stats events in $all stream

### ISSUE THREAD

**Issue by rickardoberg** [EventStore/EventStore#950]
Given:
EventStore that has been up for a while with default settings (one stats event created every 30 seconds).
Set metadata for $stats stream to $maxCount:5.

When:
Get $all stream through HTTP API

Expected:
Max 5 $stats events are included

Actual:
More than 5 $stats events are included

**Comment by gregoryyoung** [comment]
$all is an optimized stream they would only disappear once scavenged.

**Comment by rickardoberg** [comment]
@gregoryyoung thanks, so my understanding is that the $stats stream has a default $maxAge of 24h, is that correct? Should stats events older than that have been scavenged? The reason I ask is because when I just copied our staging eventstore $all stream to my local machine I got 74.000 stats events (total size is 2.2M events). It would have been awesome to not see those, or at least skip a majority of them.

**Comment by gregoryyoung** [comment]
If you run scavenge and if they are out of the current chunk (the current
chunk doesn't get scavenged).

$all is a special stream that is optimized for reading all. It bypasses
indexes etc and gets raw data.

On Wed, Jun 15, 2016 at 11:34 AM, Rickard Öberg <notifications@github.com>
wrote:

> @gregoryyoung <https://github.com/gregoryyoung> thanks, so my
> understanding is that the $stats stream has a default $maxAge of 24h, is
> that correct? Should stats events older than that have been scavenged? The
> reason I ask is because when I just copied our staging eventstore $all
> stream to my local machine I got 74.000 stats events (total size is 2.2M
> events). It would have been awesome to not see those, or at least skip a
> majority of them.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/EventStore/EventStore/issues/950#issuecomment-226123103>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXRWg1bv5bSk7gK1xf64SNntwxSZQVWks5qL7kegaJpZM4I2DPM>
> .
>



-- 
Studying for the Turing test

**Comment by rickardoberg** [comment]
@gregoryyoung what is scavenge, and how do I run it? Is this documented somewhere?

**Comment by pgermishuys** [comment]
The UI has a button on the admin page that issues an http request to `http://{eventstore-uri}/admin/scavenge`. You can do the same via curl for example.
![image](https://cloud.githubusercontent.com/assets/1062417/16104648/758506c4-3383-11e6-9c50-e548d81d545d.png)

**Comment by rickardoberg** [comment]
@pgermishuys ok, cool. Is it documented somewhere about this feature, what it does, and how to invoke it? People are not actually supposed to click on that thing manually, right?

**Comment by rickardoberg** [comment]
Also, in a cluster, is it necessary to run scavenge on the instances individually, or will triggering it on one run it on all. Etc. etc.

**Comment by pgermishuys** [comment]
Scavenge will remove deleted things. If you don't regularly delete, you don't have to run scavenge often. The scavenge process could be run by a scheduler that will just issue a web request to `/admin/scavenge` to each of the nodes.

Each of the nodes have an independent database and the scavenge request should be issued to each.

**Comment by pgermishuys** [comment]
@rickardoberg noted and will get documented. To run a scavenge you will need to issue a `POST` to `/admin/scavenge` with the credentials of a user that either has the `admin` or `ops` role.
