### ISSUE TITLE
Emitted Stream to be a bit more lenient

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/EventStore#968]
In the case where a projection has been deleted and another projection has been created that emits to the same stream the validation `Multiple projections emitting to the same stream detected. Stream: 'StreamName'. Last event projection: '5'. Emitting projection: '6'` stops the new projection from emitting to that stream.

Things to look into can include introducing a `run-with-scissors` mode for projections that would disable these types of validations. Introduce the ability to track emitted streams and delete them when deleting a projection.

**Comment by riccardone** [comment]
question: is the label "up for grabs" necessary to start implementing?

**Comment by pgermishuys** [comment]
Hey @riccardone it's not. The up for grabs are issues we identify as being issues that new contributors can start out with as they are likely require minimal effort to implement.
I submitted a PR last night that fixes this particular issue though :( sorry.
