### ISSUE TITLE
Current Version of Stream in WrongExpectedVersionException

### ISSUE THREAD

**Issue by tanerg** [EventStore/EventStore#972]
Is it possible to have the Current Version of a Stream when the WrongExpectedVersionException is thrown? So it would be possible to act on it for example in conflict resolution.

**Comment by gregoryyoung** [comment]
This has been added to the http api and will be added to the client api in 4.0

**Comment by bartelink** [comment]
Doesn't seem to have been added yet at present; can it be added please?

**Comment by gregoryyoung** [comment]
hmm let me look.
