### ISSUE TITLE
How to properly use projections

### ISSUE THREAD

**Issue by mkuts12** [EventStore/EventStore#976]
Hello,

I read almost all the posts by [Rob Ashton](http://codeofrob.com/entries/playing-with-the-eventstore.html) and [Greg](https://goodenoughsoftware.net/2013/02/12/projections-1-the-theory) and still I seem to not understand few things:
1. Is there a way to write and manage projections outside the server GUI? looks like everyone just pastes them inside the db. I want an external application to hold all the projections, but it seems that the only way to do this is subscribe to streams and not use projections. If this is true, and all I can do is only use subscribtions, why should I have projections? What is the use-case?
2. Is there a way to fetch the state of different projections in a single projection? For example in the projection `cats-jump-counter` get the property `dogs.amount`? Should I subscribe to the `dogs` stream and calculate the `dogs.count` in `cats-jump-count`?
3. Can I nest categories more than one level? for example, can I have a stream named `users-admins-michael` and then do `fromCategory('users-admins')`?
4. Can I pick the streams to subscribe to in a JQuery-like way? `fromCategory('cats').fromSub('black').when...` or `fromRegEx(/..../)`, or even a way to create bigger streams `fromCategory('cats').fromCategory('dogs').when(...)`?
5. Is there a way to use JS libraries like [`babel`](https://babeljs.io/) to write projections?

On other note, The JS projections syntax is not JS-like. For example in JS one would use `stream.on('event-name', func).on('event-name'...)` instead of sending an object.
Besides that, is there any other function of `fromStream` other than `when`? If there is none then why not write simply `fromStream('cats', { $init: func, 'jump': func} )`. These can be a whole issue.

Thanks in advance

**Comment by mkuts12** [comment]
Another question, In the [documentation](https://geteventstore.com/blog/20130213/projections-2-a-simple-sep-projection/) it is written:
```
Hint: as projections are experimental as of the last release you need to enable them on the command line or in configuration when bringing up the Event Store. The command line is –run-projections.
```

Is it still relevant? I know that I had to run the EventStore node with allow-projections=all to get projections...

**Comment by pgermishuys** [comment]
experimental should be replaced with "beta" and the 4.0 release of Event Store will have projections out of beta.

**Comment by pgermishuys** [comment]
Hi @mkuts12 
See some of the answers inline.

> Is there a way to write and manage projections outside the server GUI? looks like everyone just pastes them inside the db. I want an external application to hold all the projections, but it seems that the only way to do this is subscribe to streams and not use projections. If this is true, and all I can do is only use subscribtions, why should I have projections? What is the use-case?

Yes, the GUI merely uses the HTTP API to issue commands to Event Store. This means that whatever you can do in the UI you are able to do by issuing http requests to Event Store. The Event Store CLI does this for example and turning on verbose logging you are able to see what it does and replicate yourself without having to read the source code. (This is true for projections as it's currently not documented)

> Can I nest categories more than one level? for example, can I have a stream named users-admins-michael and then do fromCategory('users-admins')?

Categories are created based on the contents the `$by_category` which is 
```
first
-
```
This means that it will create the category from the `first` word after splitting by `-`. The available options for the part `first` are `first` and `last`. The separator can be anything.

This means you can cater for your scenario above by changing the projections' contents from `first` to `last`

> Can I pick the streams to subscribe to in a JQuery-like way? fromCategory('cats').fromSub('black').when... or fromRegEx(/..../), or even a way to create bigger streams fromCategory('cats').fromCategory('dogs').when(...)?

Not by default due to what fromCategory returns which currently is
```
    function fromCategory(category) {
        eventProcessor.fromCategory(category);
        return {
            partitionBy: partitionBy,
            foreachStream: foreachStream,
            when: when,
            whenAny: whenAny,
            outputState: outputState,
        };
    }
```

**Comment by mkuts12** [comment]
Thank you for your response!

>Yes, the GUI merely uses the HTTP API to issue commands to Event Store. This means that whatever you can do in the UI you are able to do by issuing http requests to Event Store. The Event Store CLI does this for example and turning on verbose logging you are able to see what it does and replicate yourself without having to read the source code. (This is true for projections as it's currently not documented)


It's a bit weird. I tried looking for documentation for the cli but it is very poor. Do you have any document on it?

>This means you can cater for your scenario above by changing the projections' contents from first to last

I'll try it. Thanks

>Not by default due to what fromCategory returns which currently is

Is there a chance you will add these features? With the new `class` feature in js, you can create something like this:
```
class Streams{

  constructor( streams ){
    this.streams = streams;
  }

  fromCategory(name){
    return new Streams( concat( this.streams, concat( getStreams, getCategoryStreamNames ) ) );
  }

  fromStreams( arrayNames ){
    return new Streams( concat( this.streams, getStreams( arrayNames ) ) );
  }

  where( regExp ){
    return new Streams( concat( this.streams, getStreams( arrayNames ) ) );
  }

  when,
  whenAny,
  on( eventName, foo ) {
    return new Streams( map( this.streams, stream => return stream.on(eventName), foo ) );
  }
}

```

What do you think of it?

Some things you didn't address,

- Is there a way to fetch the state of different projections in a single projection? For example in the projection cats-jump-counter get the property dogs.amount? Should I subscribe to the dogs stream and calculate the dogs.count in cats-jump-count?

- On other note, The JS projections syntax is not JS-like. For example in JS one would use stream.on('event-name', func).on('event-name'...) instead of sending an object.
Besides that, is there any other function of fromStream other than when? If there is none then why not write simply fromStream('cats', { $init: func, 'jump': func} ). These can be a whole issue.

- Is there a way to use JS libraries like babel to write projections?

- Is there a way to fetch the state of different projections in a single projection? For example in the projection cats-jump-counter get the property dogs.amount? Should I subscribe to the dogs stream and calculate the dogs.count in cats-jump-count?

**Comment by gregoryyoung** [comment]
Try using the cli. The commands are documented in the documentation. It
will give you further help when you try to use it.

ex try eventstorecli projections new or projections status



On Mon, Jul 11, 2016 at 4:40 PM, mkuts12 <notifications@github.com> wrote:

> Thank you for your response!
>
> Yes, the GUI merely uses the HTTP API to issue commands to Event Store.
> This means that whatever you can do in the UI you are able to do by issuing
> http requests to Event Store. The Event Store CLI does this for example and
> turning on verbose logging you are able to see what it does and replicate
> yourself without having to read the source code. (This is true for
> projections as it's currently not documented)
>
> It's a bit weird. I tried looking for documentation for the cli but it is
> very poor. Do you have any document on it?
>
> This means you can cater for your scenario above by changing the
> projections' contents from first to last
>
> I'll try it. Thanks
>
> Not by default due to what fromCategory returns which currently is
>
> Is there a chance you will add these features? With the new class feature
> in js, you can create something like this:
>
> class Streams{
>
>   constructor( streams ){
>     this.streams = streams;
>   }
>
>   fromCategory(name){
>     return new Streams( concat( this.streams, concat( getStreams, getCategoryStreamNames ) ) );
>   }
>
>   fromStreams( arrayNames ){
>     return new Streams( concat( this.streams, getStreams( arrayNames ) ) );
>   }
>
>   where( regExp ){
>     return new Streams( concat( this.streams, getStreams( arrayNames ) ) );
>   }
>
>   when,
>   whenAny,
>   on( eventName, foo ) {
>     return new Streams( map( this.streams, stream => return stream.on(eventName), foo ) );
>   }
> }
>
>
> What do you think of it?
>
> Some things you didn't address,
>
>    -
>
>    Is there a way to fetch the state of different projections in a single
>    projection? For example in the projection cats-jump-counter get the
>    property dogs.amount? Should I subscribe to the dogs stream and calculate
>    the dogs.count in cats-jump-count?
>    -
>
>    On other note, The JS projections syntax is not JS-like. For example
>    in JS one would use stream.on('event-name', func).on('event-name'...)
>    instead of sending an object.
>    Besides that, is there any other function of fromStream other than
>    when? If there is none then why not write simply fromStream('cats', {
>    $init: func, 'jump': func} ). These can be a whole issue.
>    -
>
>    Is there a way to use JS libraries like babel to write projections?
>    -
>
>    Is there a way to fetch the state of different projections in a single
>    projection? For example in the projection cats-jump-counter get the
>    property dogs.amount? Should I subscribe to the dogs stream and calculate
>    the dogs.count in cats-jump-count?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EventStore/EventStore/issues/976#issuecomment-231736839>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXRWhOSSaLew24LZDI_bwj2QzkwHWdlks5qUke9gaJpZM4JJMq_>
> .
>



-- 
Studying for the Turing test

**Comment by pgermishuys** [comment]
Hey @mkuts12, see answers inline,

> Is there a way to fetch the state of different projections in a single projection? For example in the projection cats-jump-counter get the property dogs.amount? Should I subscribe to the dogs stream and calculate the dogs.count in cats-jump-count?

There isn't a built in way of doing what you want to do. What is your the case that you have in mind?

> On other note, The JS projections syntax is not JS-like. For example in JS one would use stream.on('event-name', func).on('event-name'...) instead of sending an object.
> Besides that, is there any other function of fromStream other than when? If there is none then why not write simply fromStream('cats', { $init: func, 'jump': func} ). These can be a whole issue.

Noted about your concern with regards to the syntax. We can review but might possibly not change the syntax right now. There are other possibilities such as having a version 2 syntax.
There are other methods returned `fromStream`. This includes `whenAny`, `partitionBy` and `outputState`

> Is there a way to use JS libraries like babel to write projections?

Yeah, there is a simple way which is essentially including a minified version of the library you want to use in your projection definition.

**Comment by pgermishuys** [comment]
@mkuts12 I am going to close this issue for now unless you have any more questions. As part of the alpha release of Event Store 4.0.0 we have put up the initial set of [projections documentation](http://docs.geteventstore.com/projections/4.0.0/getting-started/) which should hopefully answer any other questions you might have.

Please don't hesitate to reopen this issue if you need any further help or questions answered.

**Comment by amanmanocha** [comment]
> There isn't a built in way of doing what you want to do. What is your the case that you have in mind?

Consider a simple application where users can purchase products. There are two category of streams -> Users (one stream per user) and Products(one stream per product). 
User streams keeps getting Purchased(productId) events.
I need to build a projection which will accept user id and return all products purchased along with details of the product(not just id) which are present in Product stream only. Is there a way to build this kind of projection?
