### ISSUE TITLE
Creating a onetime projection with emit=1 fail with a Server timeout

### ISSUE THREAD

**Issue by fchaillou** [EventStore/EventStore#991]
Hello,
I'm implementing a Projection client in scala and i encountered an issue when trying to create a onetime projection :
```
curl -X POST -v http://localhost:2113/projections/onetime\?name\=error2\&type\=JS\&emit\=1 -u admin:changeit --data '
    fromAll().
       when({
         $init : function(state,event){
           return { count : 0 }
         },
         $any : function(state,event){
           state.count += 1
         }
       })'
```

returns an error HTTP 408 from the server :
```
HTTP/1.1 408 Server was unable to handle request in time
```

When i did it using the interface, it appeared that i needed to add ```checkpoints=yes``` to my query.

But i would expect the server to return an error instead of timing out.

Thanks !

**Comment by pgermishuys** [comment]
Thanks @fchaillou. If you look at the server logs/console output it will show `Emit requires checkpoints`. This should be surfaced as an error as you have described.
