### ISSUE TITLE
How to reliably read the oldest event from stream?

### ISSUE THREAD

**Issue by klym1** [EventStore/EventStore#994]
My app needs to read the oldest event from some stream. You can say that there is nothing more easier, just use 

`connection.ReadStreamEventsForwardAsync("stream", StreamPosition.Start, 1, false);`

 and this will work. Yes, it will, but things get worse when stream has max-age and scavenging works. How in this case obtain oldest event (or at leats its number)?

**Comment by pgermishuys** [comment]
Closed due to inactivity.
